dlang/phobos

std/algorithm.d

Fix canonical bad example of how to format Ddoc comments. Shorter and much simpler. No semantic changes.

std.algorithm: fix execrable formatting

---

std/stdio.d

[I just modified the ddmd frontend to dump all imported symbols](https://gist.github.com/joakim-noah/09cf49bee3d82b03a54f), based on [Daniel's newmagic ddmd branch from a couple weeks back](https://github.com/yebblies/dmd/tree/newmagic).  I was able to make these small cleanups by running this modified ddmd on `std.stdio` and looking for places to tighten up the imports, doing more soon.
I'm posting this PR early so that it can be looked over as I go, and run through the auto-tester.

Start using the ddmd frontend to more narrowly scope imports

---

std/algorithm.d

GroupByImpl needs to initialize _prev in the constructor when its type is a nested struct.
https://issues.dlang.org/show_bug.cgi?id=13805

Fix Issue 13805 - groupBy over nested struct range

---

std/array.d

Just a diagnostic issue. The assignment in the loop won't work with non-mutable keys. We now catch in the constraint.
https://issues.dlang.org/show_bug.cgi?id=13909

Fix Issue 13909 - assocArray with const values

---

std/array.d

This started with fixing a simple typo, but I decided to go ahead and go all out. If I'm on the right track with this, I'll do more.
I've added an extra paragraph, appropriate DDOC tags (Examples, Params, Returns), and changed the template type parameters to match the type parameters for std.algorithm.splitter. I also renamed the delimiter parameter to 'sep' to match std.array.join which follows this (std.algorthim.splitter calls it 's' instead).
I'm not sure about the description of the returned array. Should it be called an 'array of ranges'?
Finally, I think the version of the template that has the 'alias isTerminator' needs to be documented separately, but I haven't figured out yet what that template alias is doing.

Ehance ddoc for std.array.split.

---

posix.mak
win32.mak

After recent dlang.org pulls, these files are now necessary.

Use needed html.ddoc, dlang.org.ddoc files for HTML generation

---

std/range/package.d

This appears to be the last caching range in Phobos.
This is a potentially breaking change: we lose the ability to moveFront, and obviously there may be performance implications if the function is expensive and users are calling front more than once. I think this is still a worthwhile change since it is better to have a uniform policy of no caching on ranges rather than arbitrary selection of ranges that do caching.
https://issues.dlang.org/show_bug.cgi?id=5036

Fix Issue 5036 - Remove caching from Sequence

---

std/socket.d

I'm not sure why the Address classes do not have opEquals implemented.  I've added it to the InternetAddress class.  If this get's "approved" then I can add the other opEquals methods to the other Address classes.

Added opEquals to InternetAddress

---

std/bitmanip.d

As [requested on the forum] (http://forum.dlang.org/thread/ofccpzlslcektihpipmv@forum.dlang.org).

Implement <<= and >>= for std.bitmanip.BitArray.

---

std/bitmanip.d

Reverse sense of `<<=` and `>>=` to be consistent with `bt()`.
Don't use palindromic bit patterns in unittest.

Fixup for PR 2797

---

std/random.d

The existing docs have not been tweaked in any way, so the new additions result in some duplication of information.  This seems a better first step than a more major revision.
Documentation for struct methods has been left unchanged, and will be addressed in a later patch.
I've also left the documentation for `uniformDistribution` unchanged as IMHO this function is so broken in its design, it really ought to be deprecated and removed :-)
Note that some of the parameter documentation will run into issues caused by https://issues.dlang.org/show_bug.cgi?id=13270.

Add Params/Returns ddoc to free functions in std.random

---

std/algorithm.d

Future-proofing std.algorithm docs. References to std.range using LINK2 will break under the new layout. XREF2 helps guard against that.

Replace some instances of LINK2 with XREF2.

---

std/array.d

I messed up the syntax for FULL_XREF in #2817. FULL_XREF wasn't appropriate anyway. This replaces it with the new XREF2 (see https://github.com/D-Programming-Language/dlang.org/pull/748).

Fix broken link to isForwardRange in split doc.

---

std/container/array.d
std/container/binaryheap.d
std/container/dlist.d
std/container/package.d
std/container/rbtree.d
std/container/slist.d
std/container/util.d

In the header of each std.container module, the links to other std.container modules were missing the .html extension.

Fix broken documentation links in all std.container modules.

---

win32.mak

Documentation for std.container.util was not being generated.

Gen std.container.util doc

---

std/algorithm.d
std/typecons.d

https://issues.dlang.org/show_bug.cgi?id=13781
@9rnsr explains why Tuple.opAssign isn't deduced to be @nogc:
"'swap' is used from the opAssign template function in Tuple, but swap checks (hasElaborateAssign!T || !isAssignable!T) and it would see the signature of T.opAssign. On mutual function calls, attributes are inferred as non-@nogc by default. It's a design so this is not a compiler bug.
The correct fix is to mark std.algorithm.swap function as @nogc."

Fix Issue 13781 - Tuple assign should be @nogc

---

std/array.d

Depends on: https://github.com/D-Programming-Language/druntime/pull/1080

Implement byPair.

---

posix.mak

At work we have a custom build of druntime for a variety of reasons. Currently we need to modify phobos/posix.mak by hand because it insists on building druntime by itself. This pull detects DRUNTIME when defined in the command line and does not attempt to build it.

Do not build druntime if DRUNTIME is explicit in the command line

---

std/algorithm.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=13935
When the incoming range to cartesianProduct is parametrized on something that requires a frame pointer, we cannot declare default-initialized instances of its type. To work around this in .save, just make a copy of `this` and then kick it into shape before returning it.

Issue 13935: do not assume range can be default-initialized.

---

std/algorithm.d
std/range/package.d

https://d.puremagic.com/issues/show_bug.cgi?id=12409

fix Issue 12409 - Add "each" function as found in Ruby and jQuery

---

std/conv.d

Issue URL: https://issues.dlang.org/show_bug.cgi?id=13931

Issue 13931 - Missing overflow checks in `std.conv` for negative numbers which start from the most negative number digits

---

std/net/curl.d

Also added a note about needing to link `libcurl`.
=====
Note:
=====
I'm pretty sure other functions in this module are missing `Throws:`, but only added it for `get()` which I tried.
Someone who knows more about http/etc should improve this.
Also, `CurlException on error` works, but it would be better to explain possible error cases.

[trivial but see description][DDoc] Throws: for std.net.curl.get()

---

std/concurrency.d

FiberScheduler wasn't resetting notified state when Condition.wait completed.

Fix a bug with FiberScheduler

---

std/concurrency.d

I experimented with a lock-free freelist (which turned out to be ridiculously slow) and a locked freelist.  The locked freelist provided a bit of a performance advantage over no free list at all in my tests, and should scale better in large applications.

Add message free list to std.concurrency

---

std/concurrency.d

- works now that core.sync.* is completely nothrow too

mark rest of std.concurrency Scheduler as nothrow

---

std/concurrency.d

- uses double-checked locking (the correct one)
- all instances shared the same global mutex
- minimal overhead and simple API

add initOnce

---

std/bitmanip.d

* moved comment examples to unittests
* removed examples from comments as following unittest was used to verify
example
* whitespace

bitmanip documentation updates

---

std/algorithm.d

See discussion here: http://forum.dlang.org/post/qvwlyrkfcsvfiefadzbv@forum.dlang.org
Bug report: https://issues.dlang.org/show_bug.cgi?id=13990

Fix issue 13990 -- std.algorithm.move incorrectly uses hasAliasing for class references

---

std/getopt.d

some of the symbols where clearly only used from within getopt but still where
public.
additionally some style violation fixes

getopt public undocumented symbols and style

---

std/algorithm/mutation.d

I didn't notice there were 2 move overloads. This is a supplement to https://github.com/D-Programming-Language/phobos/pull/2876

Fix issue 13990 part 2 -- std.algorithm.move incorrectly uses hasAliasing for class references

---

std/algorithm/iteration.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=13936
Basically, rip out support for non-equivalence ranges (for now) and restrict the current `groupBy` implementation to input ranges only. Forward ranges and higher will use Andrei's proposed design that avoids the need to `popFront` through each subrange more than once in a linear traversal of the underlying range.
However, the new code is not expected to pass the autotester just yet, because of blocking issues with `RefCounted` being neither `@safe`, `pure`, nor `nothrow`.

New implementation of groupBy

---

std/bigint.d

* moved example from comment to unittest
* documentation for three function (toDecimalString,toHexString,absUnsign)
all were public and had no doc
* fix some indentation
* removed bad code from 2010

documentation update for bigint.d

---

std/container/array.d

This often comes up on the forum/stackoverflow, and I think it's best to mention it right in Array's documentation.
It should probably be mentioned in `std.algorithm` docs too, but in more detail/more generally.

[DDoc] [trivial] Mentioning that a container is not a range.

---

std/outbuffer.d
std/stream.d

This replaces the current awkward version condition, and makes the code future-proof with regards to the hopefully imminent removal of `__va_argsave`.

Use presence of __va_argsave to determine if __va_argsave hack is needed

---

std/bitmanip.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=13806
Look at how much more readable the unittests are after the deprecation! Seriously, how did we ever put up with this for so long??
Split into 3 commits deliberately, because I know Vladimir is going to complain about sudden deprecations, so the first commit is just a comment, the second commit is to clean up some blatant style violations, and the third is the actual deprecation and unittest cleanup.

Issue 13806: BitArray should not define member function called init()

---

std/outbuffer.d
std/stream.d

This reverts commit f07a77d106432d70468bb86e34f2ef5b8cb12d61, reversing
changes made to 4bd949406af646370504208cd569ace0707f2b82.
It's breaking std.outbuffer unittest in Win64 platform.

Revert "Merge pull request #2902 from yebblies/typeofva_argsave"

---

std/bigint.d

For long/ulong, use the implementation of opOpAssign and return BigInt.
https://issues.dlang.org/show_bug.cgi?id=13963

Fix Issue 13963 - BigInt modulo ulong is rejected

---

std/container/rbtree.d

version(RBDoChecks) generates some functions, but they uses writefln, so should be inferred as impure. Currently it has been overlooked by the compiler bug.
We should use `debug` for them instead of `version`.

Use debug instead of version

---

std/range/package.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=6447
Partially fixes: https://issues.dlang.org/show_bug.cgi?id=10762
Basically, as long as a type supports comparison via `<` and incrementing via `++`, `iota` should work.
This is an initial stab at issue 10762; it provides the baseline for the most general user-defined types, so the returned range for non-built-in types will only be input ranges. Subsequent PRs will gradually refine this, e.g., to support random access if `x + y*k` is a supported operation in the underlying type.

Issue 6447 & 10762: support user-defined types in iota()

---

std/format.d

They were added by #2890 (ab9e15222a5f17ea7f3255fa0861c70ddcc8b11b), but they were incorrectly accepted by the compiler regression.

Remove pure attribute from the unittests which contain formatting floating point values

---

posix.mak
std/concurrency.d
std/experimental/logger/core.d
std/experimental/logger/filelogger.d
std/experimental/logger/multilogger.d
std/experimental/logger/nulllogger.d
std/experimental/logger/package.d
win32.mak
win64.mak

Logging facilities for Phobos.
Docu:
http://burner.github.io/phobos/phobos-prerelease/std_experimental_logger_package.html
http://burner.github.io/phobos/phobos-prerelease/std_experimental_logger_core.html
http://burner.github.io/phobos/phobos-prerelease/std_experimental_logger_filelogger.html
http://burner.github.io/phobos/phobos-prerelease/std_experimental_logger_multilogger.html
http://burner.github.io/phobos/phobos-prerelease/std_experimental_logger_nulllogger.html
dub
http://code.dlang.org/packages/logger

std.logger

---

std/algorithm/package.d
std/digest/crc.d
std/digest/digest.d
std/digest/md.d
std/digest/ripemd.d
std/digest/sha.d
std/math.d
std/net/curl.d
std/string.d
std/traits.d
std/uuid.d

Screenshot together with <https://github.com/D-Programming-Language/dlang.org/pull/843>:

[DDoc] add HTML class "quickindex" to manually maintained jump link tables

---

std/outbuffer.d
std/stream.d

Finally!  `va_start` works on all dmd platforms.  Now only `va_copy` remains horrifically broken.
@andralex @ibuclaw

Stop using va_argsave now that va_start works correctly without it

---

index.d

The current page requires too big a minimum browser width, which causes the page layout to bleed badly when viewed on a narrow screen device. This PR moves the category headings into leading rows to alleviate some of the horizontal width requirements.
Addresses concerns raised in: https://github.com/D-Programming-Language/phobos/pull/2770#issuecomment-71524933

Reduce minimum width requirements of Phobos index page.

---

std/zip.d

The limit of 65536 files in an archive was bypassed by adding support for reading and writing the Zip64 flavour of Zip archives, which has two extra blocks before the end of central directory record (eocd), namely the zip64 eocd and zip64 eocd locator. 
Other than that, all is the same, files over 4 GB still aren't supported, but with the current implementation of zip creating the complete archive in memory it wouldn't make much sense anyway. I have, however, changed the index used in the reader from int to uint, because IMO it unnecessarily limited the archives to 2 GB. 
To test the code, I have written a small utility - https://github.com/fgda/d-stuff/blob/default/ziptest.d -
and tried it in both 32- and 64-bit on win64 with dmd together with 7-zip and Cygwin/zip, to test reading and …

Fix Issue 2138 - Allow more than 65535 files in Zip archives

---

std/container/package.d

One commit is a patch to #2866:
* Removed use of personal pronouns
* Fixed some broken DDoc syntax
* Fixed/changed some English grammar
The other two commits add additional example code.
P.S.
Please don't use personal pronouns like "you" in reference documentation.

Supplement to #2866

---

std/container/array.d

Thanks to @aG0aep6G this works as far as I can see.

Fix constness of array.d

---

std/container/rbtree.d

https://issues.dlang.org/show_bug.cgi?id=14082
The red black tree unit tests are template-based, so they instantiate based on the parameters to the template. Previously, the only consideration was that the type should be integral. If someone created a Red Black Tree with a custom lambda, it still tries to run the unit test with the assumption that it's "a > b". This precludes that.

Fix issue 14082 -- RedBlackTree unittest fails with custom predicate less

---

std/conv.d

https://issues.dlang.org/show_bug.cgi?id=14042
Somehow `cond ? char[] : string` was implicitly convertible to `char[]` before D-Programming-Language/dmd#4285 got merged.

Fix Issue 14042 - std.conv.to of a immutable char pointer

---

std/variant.d

Do not call destructor in VariantN.opAssign if no allowed type requires

---

std/format.d

`<dl>` and `</dl>` were not matching.

Fix Issue 14111 - Broken DDOC for std.format

---

std/utf.d

- bsr(0) returns an undefined result
[Issue 14105 – strideImpl fails for 0xFF](https://issues.dlang.org/show_bug.cgi?id=14105)

fix Issue 14105 - strideImpl fails for 0xFF

---

std/concurrency.d

Although https://github.com/D-Programming-Language/druntime/pull/1143 technically takes care of this, use after remove is not nice. cc @complexmath

Avoid use after remove from hashtable

---

std/range/primitives.d
std/typecons.d

- need attribute inference to toString delegate
[Issue 14106 – sort is @safe in release mode, @system in debug mode](https://issues.dlang.org/show_bug.cgi?id=14106)

fix Issue 14106 - sort is unsafe in debug mode

---

std/internal/math/gammafunction.d
std/mathspecial.d

`digamma(x)` is asymptotically equivalent to `log(x)`. `logmdigamma(x)` computes `log(x) - digamma(x)` without subtractive cancellation for large x. See also [cran.statmod](http://cran.r-project.org/web/packages/statmod/index.html).

Log Minus Digamma function

---

std/algorithm/searching.d

I'd file an issue but it's unclear what the bug is here; see [this thread](http://forum.dlang.org/post/eznmimqkrcfkghizcvwz@forum.dlang.org) for more information.
The path is already tested as verified by coverage analysis.

Change foreach loop in std.algorithm.searching.find to a for-loop

---

std/math.d

For future `double` and `float` versions of `log2`.

fix unittest

---

std/format.d

https://issues.dlang.org/show_bug.cgi?id=14059
I adjusted enforce condition, because it reads two(or three if '-' exists) characters in one loop.

Issue 14059 - Formatted write with wrong formatting string

---

std/container/package.d
std/container/util.d

std.container.make!(Array!T) now returns a reference
to an actual container, not a 'null reference' that
initializes itself upon use.
A more elegant solution would be to provide an overload for Array, but if I define it in std/container/array.d it will issue a conflict (even if the template is more specialized) and to do it in std/container/util.d would require to import std.container.array and I am not sure if we want that, because of the ongoing effort to decouple the imports in phobos. Regardless, setting length to 0 shouldn't be a problem for any struct based container constructed without arguments.

Fix #13872

---

std/math.d

Allow `std.math.poly` accept `double[]` and `float[]` arrays.

poly template

---

std/algorithm/searching.d

`std.range` is not imported in module level, so the missing import error looks legitimate.
But, I'm not sure why the error happens only in win32/64 platforms...

Add missing imports

---

std/file.d

Many D1 functions got deleted for D2, and the replacements aren't always obvious. This adds an example to `dirEntries()` showing how it can be used to replace `listdir()`.

document replacing D1's listdir()

---

std/typecons.d

Issue noticed in [this thread](http://forum.dlang.org/post/axgwaskjtkozmjuoifyi@forum.dlang.org).
For the purposes of forward-compatibility, `RefCounted` has rejected classes because it is intended that in the future `RefCounted!SomeClass` reference-counts the actual instance and not just a class reference. Once implemented, interfaces should be handled in a similar way.
It is my intention to work on class support for `RefCounted`, but in case the status quo continues for a long time, we have to reject interfaces as well.

Reject instantiating RefCounted with interface types

---

std/getopt.d

Currently, the endOfOptions separator ("--" by default) is stripped from args by getopt.  At times it may be advantageous to keep this separator, such as when your program is forwarding command line arguments to some other program.
Without this, hacks such as
```D
auto remaining = args.find(endOfOptions);
args = args[0 .. $ - remaining.length];
getopt(args, opts);
args = args ~ remaining;
```
are needed to achieve the desired behavior.

Add keepEndOfOptions flag to std.getopt

---

std/exception.d

* Refactored to not use AliasThis as discussed in #2949
* Added `RangePrimitive.access` and `RangePrimitive.pop` to make doing the right thing in the common case easier
* Added example using `handle` to replace invalid code points with spaces instead of throwing
Ping @burner; I examined the possibility of adding `handleAccess` and `handlePop` convenience functions, but I think this way, using additional members of `RangePrimitive` is cleaner. IMO, this way, doing the right thing is easy while flexibility is still available. What do you think?
About opSlice infinite ranges, maybe leaving the `take`ing to the handler function and static-asserting if the return type isn't correct would be a nice solution. That way the user can't make the easy mistake of not implementing slicing properly, but …

Improve std.exception.handle

---

std/string.d

Melds together string.splitLines() and algorithm.splitter() to make a line splitter that doesn't allocate memory and accepts ranges as input instead of just arrays.

add std.string.splitterLines()

---

posix.mak

We have a bunch of unittest failures in BUILD=debug mode, partly because "make unittest" only cares for the release build. cc @braddr @MartinNowak

make unittest should test both debug and release

---

index.d
posix.mak
std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d
std/container/array.d
std/container/binaryheap.d
std/container/dlist.d
std/container/package.d
std/container/rbtree.d
std/container/slist.d
std/container/util.d
std/exception.d
std/range/interfaces.d
std/range/primitives.d
win32.mak
win64.mak

Also put in order the package and module definitions.

Fix name of package documentation: std_xyz_package.html -> std_xyz.html

---

std/algorithm/searching.d

Per title. No need to do decoding if comparing two strings that have the same representation.

skipOver: no unnecessary decoding

---

std/outbuffer.d

I wanted to change writing to a file with `fp.writef(...)` to writing to an `OutBuffer` without rewriting code, and found it couldn't be done. Hence, this PR adds `writef()` and `writefln()` to `std.outbuffer.OutBuffer`. The implementations are trivial.

add writef and writefln to std.outbuffer

---

std/experimental/logger/multilogger.d

`std.range.interfaces` privately imports `std.range.primitives`. So selective importing `back` and `popBack` via `std.range.interfaces` is not possible.

Fix imports

---

std/string.d

Rename std.string.splitterLines to std.string.lineSplitter

---

win32.mak
win64.mak

Note this is **NOT** tested on Win64 because I have no such environment.

Make phobos.lib include std.experimental.logger 

---

std/math.d

This PR allows many special math function be executed at compile time.

CTFE-able poly

---

std/array.d

https://issues.dlang.org/show_bug.cgi?id=14230
Putted length (`len`) was used to determine whether to insert separator there or not, so the first element is not separated correctly if it's empty.

Fix Issue 14230 - [REG2.067b2] std.array.join misses the first element which is empty string

---

std/range/package.d

The regression seems that a late crash (in `front`, dmd 2.065) became an early crash (in the constructor, dmd 2.066.0). There are several unexciting ways to consider:
* Fail early, aka `assert` before construction
* Fail late, aka `assert` in each method
* Cycle dummy data (there are different ways to do that, all are underwhelming)
* Return an empty range and violate the static condition about cycles
In this light I guess fail early is the best choice. The old behavior might be considered a bug. Then this fix just defines valid input.

Fix Issue 13390 - Be explicit about non-empty input and fail early

---

posix.mak

- and it ought to be MAKEFLAGS=$(MAKEFLAGS) anyhow

make flags are automatically communicated to sub-make

---

posix.mak

Reverts D-Programming-Language/phobos#3006. Refer to discussion in there for the rationale. cc @MartinNowak - thanks.

Revert "make flags are automatically communicated to sub-make"

---

std/variant.d

https://issues.dlang.org/show_bug.cgi?id=14233
In pull #2453, VariantN.opIndex has been changed to return `Variant`.
It affects to OpID.catAssign case in handler(A), because it's using `alias E = typeof((*zis)[0]);` to determine concatenated element type.

[REG2.067b2] Issue 14233 - Can't build Algebraic!(This[]) anymore

---

std/math.d

intrinsics for `fabs` should be added to DMD.

std.math: №2, fix abs, fabs

---

std/numeric.d

Fixes trivial copy-paste error.

[Minor] Fix last `std.numeric.findRoot` overload without tolerance delegate.

---

std/conv.d
std/variant.d

This was caused by the format functions recursively calling `to!string`, resulting in it not being inferred properly as pure. A specialization fixes it.

fix Issue 14198 - [REG2.067a] Link failure with Variant

---

std/concurrency.d

- we had troubles turning vibe.d's mutex class
into nothrow and have to undo the changes
for now
- use internal lock_nothrow/unlock_nothrow
functions so that the Scheduler API need
not be changed

roll back Mutex nothrow

---

std/concurrency.d
std/experimental/logger/core.d

- synchronized (mtx) is neither pure not const
- the compiler currently doesn't check attributes
for synchronized statements

fix attributes for synchronized (mtx)

---

std/stdio.d

fputc is already ```@trusted```, all that's needed to make this work is to use ```trustedStdout```
replaces https://github.com/D-Programming-Language/phobos/pull/3039

make 0-arg writeln @trusted: Fix Issue 13681 take 2

---

std/regex/internal/ir.d

This code worked before because of bug in qualifiied package protection
implementation in DMD which resulted in merging protection levels of
aggregates and their member symbols.
Needed for https://github.com/D-Programming-Language/dmd/pull/4476

Fix mixed package protection in std.regex

---

std/random.d

https://issues.dlang.org/show_bug.cgi?id=13649
We have to throw away the result and try again when it is rounded to 1. As a result, this PR disables 93fe844.
See also [boost/random/uniform_01](http://www.boost.org/doc/libs/1_57_0/boost/random/uniform_01.hpp), which is the original, according to #2050.

Fix Issue 13649 - uniform01 Assertion failure

---

std/uuid.d

Issue 14135 - std.uuid.randomUUID breaks @safety
https://issues.dlang.org/show_bug.cgi?id=14135
Do note I am committing this completely blind, and do not even know if it compiles. It should. The unit-tests *should* also pass, but if not, the unittests are arguably wrong.
Also, this *should* be a faster implementation, as it prefers reinterpret to primitive than assign, over re-interpret to array, then do slice copies.

Issue 14135 - std.uuid.randomUUID breaks @safety

---

std/bitmanip.d

25ac0482acb2887d03c23b9c644c2d8a5463f005 should do either of
* change init to this
* announce deprecation of init
but actually did both.

Unmark BitArray.this() for deprecation

---

std/json.d

Add opEquals to struct JSONValue.  Needed for correct comparison of the union used for member store.  Without this change, some std.json unittests will fail on iOS armv7.

Give std.json an opEquals

---

std/numeric.d

https://issues.dlang.org/show_bug.cgi?id=14231

findRoot: fix Issue 14231

---

std/algorithm/sorting.d

This fixes the issue described in [this article](http://envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/) which found most implementations of Timsort are incorrect. I took the fix provided in that article and adapted it to the Phobos implementation.
I don't have a formal proof that my fix is correct. However, I added a check to debug builds which traverses the stack and confirms that the invariant of the stack is preserved. I also found a few test cases which broke the invariant on the old implementation but work correctly with this new fix. I added a unittest for the simplest of these cases.
A few other minor changes:
* The comment describing the invariant was wrong so I corrected that.
* uninitializedArray now works correctly in CTFE so …

Fix Issue 14223 - TimSort algorithm is incorrect

---

std/string.d

- add public aliases to std.array.replace/replaceInPlace
- std.string should at least cover any basic string
manipulation needs
[Issue 14197 – "replace" was moved from std.string without alias added](https://issues.dlang.org/show_bug.cgi?id=14197)

fix Issue 14197 - replace was removed from std.string

---

std/array.d

- turn constraints into static asserts
[Issue 14056 – std.array.assocArray with a const value](https://issues.dlang.org/show_bug.cgi?id=14056)

improve diagnostic for assocArray

---

std/variant.d

Required by: https://github.com/D-Programming-Language/dmd/pull/4499
In `opArithmetic` member function, `VariantN` is instantiated struct type, not template identifier.

Supplemental fix for issue 14290

---

std/regex/internal/tests.d

[Issue 7157 – Optimiser is O(n^2) w.r.t. function length](https://issues.dlang.org/show_bug.cgi?id=7157)

fix compile times for regex tests

---

index.d

- use explicit .html links, as redirects aren't
available for local browsing
[Issue 14297 – [2.067.0-rc1] Broken links in phobos/index.html](https://issues.dlang.org/show_bug.cgi?id=14297)

[2.067.0-rc1] fix Issue 14297 - Broken links in phobos/index.html

---

std/net/curl.d

It's showing up in the documentation for the subsequent function as a result. I don't know why it's there to begin with.

comment not supposed to be ddoc

---

std/container/dlist.d

- All insert methods should take `auto ref T t`
instead of `Stuff t`, because the latter is
an unnecessary temporary if `Stuff` isn't `T`.
- Small, copyable, register sized Ts should always be
passed by-value instead of auto ref.
[Issue 14300 – [2.067-rc1] DList casting to base type is broken](https://issues.dlang.org/show_bug.cgi?id=14300)

fix Issue 14300 - DList casting to base type is broken

---

std/algorithm/iteration.d

Cache is a too prominent type name to use it for a private __visible__ symbol.
[Issue 14301 – [2.067-rc1] Private symbols of module conflicts with public from another](https://issues.dlang.org/show_bug.cgi?id=14301)

fix Issue 14301 - private symbol Cache conflicts with client code

---

std/bigint.d

Fix punctuation in a few places. Add code examples. Document all public methods and module-global functions.
I didn't write a code example for `absUnsign` because it's unclear whether this function even belongs in this module, since it doesn't directly deal with `BigInt` but with built-in integer types! Not sure where it should go, though. Any suggestions?

Improve std.bigint docs.

---

std/math.d

Note that since the different overrides take different parameter names, the parameters will be imperfectly documented until https://issues.dlang.org/show_bug.cgi?id=13270 is fixed.  Looks like up until now, lack of explicit documentation has led authors to write "self-documenting" overrides whose parameter names indicate or hint at their different use-cases.

Document std.math.abs with Params and Returns

---

std/stdio.d

[Issue 13590](https://issues.dlang.org/show_bug.cgi?id=13590)
Added an example showing that algorithm.joiner can be used to turn byChunk into a single (lazy) range.

Add stdio.byChunk example

---

std/complex.d

The template parameters have been included (with note) in the main `Params` list.  The single-parameter version has had its template parameter name tweaked for consistency.

Document std.complex.complex with Params and Returns

---

std/stdio.d

These changes make byLine more than 3x faster on OSX without changing semantics. Given that part of the changes involve paths taken by the other OSs, it's possible there's speedup elsewhere as well. Please measure, thanks!

3x faster byLine implementation on OSX, probably faster on Linux as well

---

std/process.d

use CRuntime_Microsoft instead of Win64.

Win32 COFF: fix std.process unittests

---

std/stdio.d

In https://github.com/D-Programming-Language/phobos/pull/3089, a static buffer was introduced to help alleviate reallocating the getline buffer each call. However, in certain cases, the static buffer can be free'd, but not set to null. On a subsequent call to getline, realloc may be called on this invalid pointer. This PR simply nulls the pointer if it's free'd

Make sure the free'd lineptr doesn't leave a dangling pointer.

---

std/conv.d

- turn the chunk size and alignment checks into asserts
[Issue 14194 – nothrow emplace for classes needed](https://issues.dlang.org/show_bug.cgi?id=14194)

fix Issue 14194 - nothrow emplace for classes needed

---

std/experimental/logger/core.d

* the defaultLogFunctions were not callable with zero arguments

std.logger defaultLogFunction constraint fix

---

std/string.d

Other changes are removal of trailing whitespace.
People really ought to run `detab` before committing.

improve doc for std.string.assumeUTF

---

std/uni.d

The NEL character was added to the Unicode official line endings list. We must support it.

add nelSep

---

std/format.d

The HTML at http://dlang.org/phobos/std_format.html#.format is malformed because one of the arguments to the XREF macro is the same as the name of the symbol being documented.

Fix macro expansion for format()

---

std/stdio.d

This adds a File.tempFile, which generates a random file name and
returns an open std.stdio.File for it. Unlike with File.tmpfile, it's a
normal file which is _not_ deleted when the file is closed, and you
actually have access to the file's name, which is necessary in many
situations - particularly when writing unit tests that need to write to
a file and then read from it.

Implement issue# 13996. Add File.tempFile.

---

std/array.d

After this pull, and https://github.com/D-Programming-Language/druntime/pull/1202 is pulled, I will remove the `@disable clear` section of Appender.

Remove unit test that checks for the removal of object.clear

---

std/random.d

@JakobOvrum [spotted this in my original change](https://github.com/D-Programming-Language/phobos/pull/3126#discussion_r27450427).

[minor] Missing Ddoc parenthesis in std.random docs

---

std/stdio.d

reduce performance gap between fread and rawRead
https://issues.dlang.org/show_bug.cgi?id=14368
Currently std.stdio rawRead is much slower than cstdio fread. Benchmark indicates that rawRead is roughly 2.5x slower than directly calling fread in a tight loop (not counting time in syscalls). The overhead comes from the compiler failing to inline calls to std.exception.enforce, calling errnoEnforce even when fread's return indicates success, and from buffer slicing overhead.
This patch fast paths the ordinary (no error) case, reducing the overhead to almost nil when compiled with gdc and about 1.35x when compiled with dmd.

Fix Issue 14368 - rawRead performance

---

std/conv.d

https://issues.dlang.org/show_bug.cgi?id=14401
Required by the druntime change: https://github.com/D-Programming-Language/druntime/pull/1205

Supplemental fix for issue 14401 - Deal with the type change of typeid(ClassType).init to const(void)[]

---

std/process.d

[Issue 14282 – executeShell should use sh and ignore the SHELL env variable](https://issues.dlang.org/show_bug.cgi?id=14282)

fix Issue 14282 - executeShell should use sh and ignore the SHELL env variable

---

std/bitmanip.d

Convenient, but of course does expose a new public symbol

make std.system.Endian public from std.bitmanip

---

std/math.d

The expression `6L * x` with 6 being a `long` literal (instead of an intended `real` literal) and `x` of type `double` evaluates to a `double`, while `poly()` uses `real` precision.

Fix an std.math.poly() unit test.

---

std/string.d

Added soundexer() to replace soundex(). (soundex() is retained for backwards compatibility, but is rewritten as a wrapper around soundexer().)
soundexer():
1. accepts ranges as input
2. does not allocate memory
3. returns a static array that fits into a register, thus is efficient
This makes soundexer() into a more modern style 'reduce' algorithm.

add std.string.soundexer

---

std/math.d

This fixes these compilation errors:
- phobos/std/math.d(2599): Error: only global variables can be referenced by identifier in naked asm
- phobos/std/math.d(2611): Error: only global variables can be referenced by identifier in naked asm
- phobos/std/math.d(2612): Error: only global variables can be referenced by identifier in naked asm

Fix compilation of std.math.

---

std/array.d

This unittest originally checks the UFCS hijacking problem between `object.clear` function and `Appender.clear` method but the former was removed in D-Programming-Language/druntime#1202.
Now it only checks that `Appender.clear` is not supported for immutable and const element types.

Fix comment in unittest for std.array.Appender

---

std/math.d

~~Depends on https://github.com/D-Programming-Language/dmd/pull/4425~~

std.math: №4, workaround for intrinsics

---

std/process.d
std/stdio.d

https://issues.dlang.org/show_bug.cgi?id=14422
I'm not 100% sure about this one - we're avoiding a Microsoft process bug by adding a workaround in std.stdio. CC @schveiguy @kyllingstad
Interesting observation - http://www.cplusplus.com/reference/cstdio/fopen/ says:
> Repositioning operations (fseek, fsetpos, rewind) are ignored. 
But here we exactly need a repositioning operation to fix the problem.

fix Issue 14422 - std.process: Pipes do not append to files on Win64

---

std/algorithm/comparison.d

1. replaced gc allocation of internal work buffer with realloc/free
2. levenshteinDistanceAndPath() still allocates gc memory for the return value.
3. improved unit test coverage

remove gc allocation from std.algorithm.levenshteinDistance()

---

std/string.d

http://dlang.org/phobos/std_string.html#.indexOf
Currently it only works with string inputs.
It still throws on invalid UTF.

Enhance std.string.indexOf() to work with ranges

---

std/typecons.d

Add 'also' to make it clear that these two templates can be used for `AutoImplement` as well as `WhiteHole` and `BlackHole`.

[Trivial] One-word addition to descriptions for generateAssertTrap and generateEmptyFunction

---

std/typecons.d

- Add Params section.
- Add LREF to the See_Also entries.
- Change example to a documented unittest.

Improve Blackhole documentation

---

std/variant.d

The documentation said that types larger than maxSize will be rejected, but that's not the case according to [this](http://stackoverflow.com/questions/29483110/behavior-of-std-variant-with-large-types). I have changed the documentation to reflect that types larger than maxSize will be automatically boxed by the Variant, instead of the non-existent compile-time error which the documentation wrongly mentions.

Document that types larger than maxSize will be automatically boxed

---

std/math.d

@rainers Thanks for merging PR #3152 .
I found another bug in the code: one jump statement is missing.
This still makes an assumption about the return value being passed through eax. I've tested this code using LDC's inline assembler and the code works well with a few test values.

Fix bug in std.math.ilogb in CRuntime_Microsoft path.

---

std/json.d

`JSONValue.toString` outputs 'nan', 'inf', or '-inf', when it has type
`JSON_TYPE.FLOAT` and value double.nan/double.infinity/-double.infinity.
However, `parseJSON` would fail on encountering these values in a string.
This patch enables `parseJSON` to read special float values.
I submitted this as issue #14399 a bit ago and then decided to take a shot at fixing it.
To be clear: this does not change the output of `std.json.toString`, which was already outputting special values for nan/inf. It simply allows `std.json` to read the special values that it outputs.

Enable std.json.parseJSON to parse nan/inf.

---

win64.mak

Even though unittest8.obj was compiled, it was never linked into the test executable, causing a number of tests never to be executed.

win64: fix lots of unittests never executed

---

std/getopt.d

Fixes a typo in the error message for a missing required option in std.getopt. There is a space missing between the option name and the rest of the error message.

Fix a minor typo in std.getopt

---

etc/c/curl.d

I bounced all the const-ness changes off the curl c headers, particularly in relation to char*'s.  Not sure why the import of them didn't include them from the beginning.  The @trusted annotations are based on my needs and assumption that the implementations aren't doing anything nefarious, but are simple enough functions.
I'm using the 'in' pattern since that's what this file does elsewhere.

fix const-ness of char* parameters and mark some apis as @trusted

---

std/string.d

Fixed the regression introduced in https://github.com/D-Programming-Language/phobos/pull/3172

Re-add overload for fixed-size arrays to `std.string.indexOf`

---

std/range/package.d

https://issues.dlang.org/show_bug.cgi?id=14373

fix Issue 14373 - std.range.refRange doesn't work on mere input ranges

---

std/uni.d

Replaces http://dlang.org/phobos-prerelease/std_string.html#.capitalize with a range version analogous to http://dlang.org/phobos-prerelease/std_uni.html#.toLowerCase

add std.uni.toCapitalized()

---

std/typecons.d

- Add documented unittests for member functions
- Add new examples
- Document some behavioural quirks
- Add Params, Returns and Throws where appropriate
For some reason the `alias get this` won't show up in the generated DDOC. I guess that must be a bug. Also, is there a way to link to the second "overload" of Nullable in the documentation of the first? I couldn't figure out how to do it.

Improve Nullable documentation

---

std/string.d

fromStringz wasn't declared `@nogc nothrow`, but it can easily take on those attributes. This will make it usable in `@nogc nothrow` functions. This was so trivial I just did it directly through GitHub again.

Declare fromStringz @nogc nothrow

---

std/algorithm/comparison.d
std/algorithm/sorting.d

Incidentally fixed a doc bug and a few trailing whitespaces in algorithm/comparison.d as well.

Testing whether a few given values are ordered

---

std/algorithm/mutation.d
std/typecons.d

- add RefCounted!T.this(T) which takes an RValue or a copy
and use move to initialized the refcounted store
- add refCounted to infer T from the argument and disable
RefCounted's autoInit, also move initializes the store

fix Issue 14432 - move construction for RefCounted

---

std/container/rbtree.d

- import only binaryFun from std.functional
- moved _add down with the rest of private functions since issue 2810 has been fixed
- added reference equality optimization in opEquals
- added reflexivity unittest for opEquals
- fixed documented time complexity of opEquals (should be O(n) since range is traversed once)
- removed "use more efficient algo" FIXME; this is the same equality check that SGI's C++ stl_tree.h uses, so I am fairly certain there is no better algorithm

std.container.rbtree cleanup

---

std/uni.d

I marked unittests, non-template functions and template functions with limited template arguments as `@safe` `pure` `nothrow` `@nogc` if possible.
They will not break any existing codes.
Note:
- I replaced `@trusted` or `@system` with `@safe` in some unittests and function because now they work with `@safe`.
- I added template constraints to `comparePropertyName` and `propertyNameLess`. They implicitly require template arguments `Char1` and `Char2` to work with `std.ascii.toLower`.
- I remove some comments "iota is system" because now it can work with `@safe`.
- `decoder` and `units` are template functions but they only takes char types as a template argument.

Mark unittests and functions in std.uni as @safe pure nothrow @nogc

---

std/string.d

1. Added entabber() which takes a range as input and and returns a lazy range.
2. Rewrote entab() to use entabber().
3. Added support for nelSep.
4. Fixed bug where trailing spaces followed by newlines were not removed.
5. Added unittests to fill in missing cases.
6. 100% unittest coverage
7. Improved documentation.

Range-ify std.string.entab() by adding entabber()

---

std/range/primitives.d

Excluding the UTF-decoding variants, because those throw GC allocated
exceptions.
Makes sure that issue 12666 - "@nogc std.array.front, popFront, and more"
stays fixed.
https://issues.dlang.org/show_bug.cgi?id=12666

@nogc for std.range.primitives.{empty,save,popFront,popBack,front,back}

---

std/typecons.d

Whenever D is brought up to the general programming public, the garbage collector is quickly raised as a point of contention. Regardless of how legitimate or well-informed these concerns are or are not, it would be a massive public relations boon — and great for the language, to boot — if we could trot out a solid set of RAII-based smart pointers for those who prefer to use them. We have a solid start in `std.typecons.Unique` and `std.typecons.RefCounted`. Unfortunately, these seem to be victims of bit rot and compiler bugs of days long gone.
This is the first of several pull requests that attempt to clean these up. An overview of the changes in this request is as follows (updated 2015-04-21):
- `Unique` uses `malloc` and `free` instead of the GC for backing memory storage. Unfortunately …

Improve std.typecons.Unique

---

std/variant.d

https://issues.dlang.org/show_bug.cgi?id=14457
Currently VariantN allows assignment from its allowed types and from a an instance of the exact same type.  This expands that functionality to allow assignment from another VariantN that has a strict subset of allowed types.  Implements an opAssign overload that specializes on VariantN instantations that are not the current VariantN but whose AllowedTypes are a subset of the current variant's.
The new overload has an explanatory comment, but does not have a documentation comment as the original opAssign is not documented.
Adds an accompanying unittest.
Fix Issue 14457

Fixes 14457 (VariantN assignment from subset VariantN)

---

std/uni.d

`MultiArray` is a template struct but it does not affect the attributes of its method because
it only uses the sizes of the types in `Types`.
`MultiArray.slice` and `ptr` are template methods but their template arguments do not affect their `@nogc`-ness.

Mark std.uni.MultiArray.slice and MultiArray.ptr as @nogc

---

std/string.d

add range support to std.string.stripLeft

---

std/string.d

This adds range support to overload number 3.
http://dlang.org/phobos/std_string.html#.indexOf.3

enhance std.string.indexOf(substring) with ranges

---

std/string.d

Upgrade http://dlang.org/phobos/std_string.html#.indexOf.2 to handle input ranges as well as arrays.

enhance std.string.indexOf(startIdx) with ranges

---

std/variant.d

It's too broad.
This fixes issue 13534 - std.variant can violate memory safety.
https://issues.dlang.org/show_bug.cgi?id=13534

remove "@trusted:" from std.variant

---

std/datetime.d

The std.datetime unit tests currently fail on FreeBSD 9+ because of a
bug in FreeBSD itself (which it looks like Martin reported):
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=168862
tzname[] is set incorrectly in many time zones - including
America/Los_Angeles, which is what's causing the unit test failures in
std.datetime.
Sadly, the bug report has been around for almost 3 years without the bug
getting fixed (with the report including a patch no less), so I don't
know how long it will take them, and it just seems better to version out
the test in FreeBSD for now, since it's potentially a blocker for anyone
developing Phobos on FreeBSD.
The autotester doesn't exhibit the problem, because it's using FreeBSD
8.x.

Add workaround in std.datetime unit tests for bug in FreeBSD 9+.

---

std/uni.d

`PackedPtrImpl` is a template struct but `T` and `size_t` does not affect its `@safe`-ness and `@nogc`-ness and
`this` does not contain any unsafe and GC-related operations.
Note: `PackedPtrImpl` is already marked as `@trusted` but I think it is better to use `@safe` or `@trusted` for narrower scope such as methods or functions.

Mark std.uni.PackedPtrImpl.this as @safe and @nogc

---

std/cstream.d

to change directly the handle could lead to leak the handle in `close()` because `isopen` was not defined
like it's the case when the `file()` setter is properly called.
possible breakage: no property...for class...
CFile.file() must be called instead.

fix, file handle must not be visible.

---

std/uni.d

It does not contains any unsafe, impure, throwable, and GC-related operations.
Note: It may throw `RangeError` when `n >= sz.length` but it does not affect `nothrow`-ness
because `RangeError` is an error, not an exception.

Mark std.uni.MultiArray.length as @safe pure nothrow @nogc

---

.gitignore

Xamarin Studio creates various directories and files for build output and for "projects." This change adds those directories and files to the ignore list.

Modify gitignore to ease building Phobos in Xamarin Studio

---

std/getopt.d

DDoc did not consider that this second comment was connected to the first, leading to part of the comment being missing at http://dlang.org/phobos/std_getopt.html#.Option

Fix ddoc for Option.required

---

std/bitmanip.d
std/conv.d
std/string.d

Added some missing parameters and return sections to the documentation.
In `std.conv` i've moved part of the doc block and the unittest to better document the `to` function within the `castFrom` template, a'la [`std.algorithm.aggregate`](http://dlang.org/phobos/std_algorithm_iteration.html#aggregate).
All changes can be previewed here: http://nomad.so/misc/d/dlang.org/fix-ddoc-parameter-warnings/phobos-prerelease/index.html

Updated some missing params and return sections in the documentation.

---

std/array.d

Thanks to the concept of [unique object](http://dlang.org/changelog.html#uniqueinference), we can remove unsafe cast from `replicate`.
This request makes `std.array.replicate` for dynamic arrays `@safe` for most cases.
That is, it will be unsafe only if `ElementEncodingType!S` has unsafe `opAssign`.

Make std.array.replicate for most cases @safe

---

std/traits.d

Added missing documentation.
Bugzilla: https://issues.dlang.org/show_bug.cgi?id=14079

Issue 14079 - Variable templates' documentation not generated.

---

std/format.d

Adds formatted output support for cent/ucent if supported.
Requires #3153.

Cent-ify std.format.

---

std/utf.d

We can safely remove unsafe `assumeUnique` from `toUTF8`, `toUTF16` and `toUTF32` because their return values are unque objects :-)
I also remove `pure` attribute from `toUTF16` because it is aleady in `pure` block. It is redundant.

Make std.utf.toUTF falimy @safe

---

std/uni.d

Currently `graphemeStride` is in global `@trusted:` block but its `@safe`-ness depends on its template argument.
It will break existing code which treats `graphemeStride` as `@safe` for unsafe template argument
but we should avoid to mark unsafe functions as `@safe` or `@trusted`.
This request partially solves [issue 13560](https://issues.dlang.org/show_bug.cgi?id=13560).

Remove std.uni.graphemeStride and its unittest from @trusted block

---

std/path.d

This was changed in pull request #3185, for reasons unknown.  The [correct term](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#namespaces) is "Win32 device namespace".

Undo change from "Windows" to "Win32"

---

std/traits.d
std/typetuple.d

Does the following renames in std.traits:
isExpressionTuple => isExpressions
ParameterTypeTuple => Parameters
FieldTypeTuple => Fields
ParameterDefaultValueTuple => ParameterDefaults
and in std.typetuple:
TypeTuple => Arguments
The original names are kept and documented as aliases kept for legacy compatibility. I didn't do a global search/replace in Phobos to change the names, preferring to keep this PR simple. Over time, as various modules get worked on, the names can be changed.

Rename *Tuple symbols

---

std/format.d

https://github.com/D-Programming-Language/druntime/pull/1222 cleaned up the usage of `next` and `base` in TypeInfo_Const by using object_.d instead of object.di. This needs to be adjusted to in std.format.

Adjust to change in TypeInfo_Const.next/base 

---

std/utf.d

Should have written `byChar`, etc., this way in the first place. It enables generic code to be more concisely written.

add std.utf.byUTF

---

std/net/curl.d

https://issues.dlang.org/show_bug.cgi?id=14535

fix Issue 14535 - std.net.curl.CurlException should include status line

---

std/traits.d

Motivation: my Visual Studio 2015 patch for LDC uses a D wrapper as `core.stdc.stdio.printf`.

std.traits: Make unittest independent of std.stdio.printf linkage.

---

std/file.d
std/net/curl.d
std/parallelism.d

This PR uses `std.typecons.Flag` for several boolean arguments in the standard library, similar to `std.stdio.byLine` and its `KeepTerminator`. The boolean versions are deprecated and encourage users to switch to the `Flag` versions.
For rationale, see the docs for [`Flag`](http://dlang.org/phobos/std_typecons.html#.Flag) as well as ["The boolean parameter trap" section](https://wiki.qt.io/API_Design_Principles#Avoiding_Common_Traps) of Qt's API design guidelines. To wit, boolean arguments are often a mistake and make it simple to forget or invert their meaning. Since `std.typecons.Flag` exists for this very reason, it should be used more in the standard library.

Prefer std.typecons.Flag over booleans for some Phobos arguments

---

std/variant.d

The destructor thing (14585) could probably be fixed more cleverly, without the additional space and indirection. But trying to be clever has lead to the issue in the first place.
The two overloads of get are effectively identical. The duplication could be eliminated by calling the mutable one from the const one, but with the duplication it's more robust against const-related bugs.
https://issues.dlang.org/show_bug.cgi?id=14585
https://issues.dlang.org/show_bug.cgi?id=14586

fix std.variant issues 14585 and 14586

---

std/math.d

Found this source for the value: http://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format

Add missing EXPBIAS value for 128bit floats.

---

std/stdio.d

Reverts D-Programming-Language/phobos#2956
because of https://issues.dlang.org/show_bug.cgi?id=14539

Revert "Implement issue# 13996. Add File.tempFile."

---

std/utf.d

Add parameter to `decode()` and `decodeFront()` so they will return `replacementDchar()` upon decoding invalid UTF rather than throwing. This makes it possible to use them in `@nogc` and `nothrow` code.
Add function `invalidUTFstrings()` that provides a menagerie of invalidly encoded UTF strings for handing testing.
Improve unit test coverage.
Minor doc improvements.

std.utf: add replacementDchar option in place of throwing

---

std/math.d

Correct IeeeFlags exception masks and FloatingPointControl RoundingModes for ARM fpscr
These changes will help GDC @ibuclaw and LDC @klickverbot with their 32-bit arm targets.  Tested on cortex-a9 armv7.

ARM FPSCR bit corrections

---

posix.mak

I have an alias for posix.mak as GNUmakefile, so I didn't detect this until I moved code to another machine.

[TRIVIAL] Pass the makefile name along in recursive invocations

---

std/path.d

The behavior changes here:
1. decode only if case insensitive or the arguments are different string encodings
2. if decoding, treat invalid UTF encodings as if they were replacementDchar's, rather than throwing an exception
This has the effect of making the function:
1. faster
2. nothrow and @nogc
Being a low level function, of course this affects everything up the call stack.

Range-ify std.path.filenameCmp()

---

std/range/package.d

Phobos has all sorts of algorithms for looping, but none for selection. `choose` plugs that gap, and can be used for ranges where one would use `if-else`, `?`:, and `switch` for expressions.
Despite the number of lines in this, it is mostly just copy/pasta code from its cousin, `chain`.

add std.range.choose()

---

std/internal/math/gammafunction.d

As supplement for https://github.com/JohanEngelen/phobos/commit/2ac2581fe49da475bf6f687cfb7bcb9c9ddf8b71 (1st commit of https://github.com/D-Programming-Language/phobos/pull/3045; that commit alone doesn't depend on the other PR).

std.internal.math.gammafunction: loosen some tests for 64-bit reals.

---

std/socket.d

See https://issues.dlang.org/show_bug.cgi?id=14611

Fix 14611 - socket.localAddress fails on Unix sockets with longer path (> 13 characters)

---

std/socket.d

https://issues.dlang.org/show_bug.cgi?id=14616

Fix 14616 - ddoc shows std.socket.UnixAddress as "abstract" 

---

std/socket.d

`fds()` returns a slice of length `count()`, and since fds() is invoked before evaluating the index expression (incl. increasing the count), its length is the old count, so we cannot assign to the element at index = old count, that's 1 past the end.

[Windows] Fix a range error in std.socket.SocketSet.add()

---

std/algorithm/iteration.d

- accidentally added in 2.067.0
- replaced by compat alias to chunkBy in 2.067.1

remove groupBy

---

std/variant.d

This fixes a problem with PR #3284, reported by @schuetzm: https://github.com/rejectedsoftware/vibe.d/issues/1115

fixup PR #3284 - do a reinterpret cast

---

std/cstream.d
std/net/curl.d
std/socketstream.d
std/stream.d
std/typecons.d

deprecate
* std.stream
* std.socketstream
* std.cstream
this needs to be pulled before https://github.com/D-Programming-Language/phobos/pull/3318

deprecate std.stream and friends

---

osmodel.mak
posix.mak

There were slight difference between the logic in `posix.mak` compared to `osmodel.mak` (DRY)
Also see https://github.com/D-Programming-Language/dmd/pull/4684

Use osmodel.mak from dmd repo

---

std/cstream.d
std/socketstream.d
std/stream.d

this removes the `deprecated module std.s`

stream deprecation breaks doc building

---

std/conv.d
std/datetime.d
std/exception.d
std/file.d
std/format.d
std/math.d
std/mmfile.d
std/parallelism.d
std/path.d
std/process.d
std/socket.d
std/stdio.d
std/system.d

Building on submitted dmd pulls [#4111](https://github.com/D-Programming-Language/dmd/pull/4111) and [#3643](https://github.com/D-Programming-Language/dmd/pull/3643) and druntime pull [#1010](https://github.com/D-Programming-Language/druntime/pull/1010), this pull substitutes the new `CRuntime_Glibc` and `CRuntime_Bionic` predefined global versions where appropriate.  After those dmd pulls are merged, `linux` will be defined for both desktop/server linux and Android, as opposed to the current situation where either `linux` or `Android` alone is expected to be defined (which is why I had to change the order in `std.system`).  dmd #4111 will have to be merged before this pull will compile and pass tests.

Separate linux kernel, glibc, and bionic APIs where appropriate

---

std/socket.d

Added constructors for InternetAddress and Internet6Address from a sockaddr_in or sockaddr_in6, respectively.

Internet address constructors

---

std/socket.d

See https://github.com/D-Programming-Language/phobos/pull/3349#issuecomment-107649732

Remove superfluous ctor in ddoc version of UnixAddress

---

std/traits.d

This will make compile-time reflection slightly more convenient. At the moment any code that uses user-defined attributes needs to re-invent this wheel.

Add hasUDA template

---

std/string.d
std/traits.d

Please see https://github.com/D-Programming-Language/phobos/pull/2562 for context.
This change adds a CopyStorageClasses template based on the existing ModifyTypePreservingSTC template. It also makes MutableOf, InoutOf, etc. public so that they can be used in user code.

Add CopyStorageClasses template and allow access to ConstOf and others.

---

std/file.d

Older versions of Linux, older versions of FreeBSD, and current versions
of Darwin can return EISDIR to signal an existing directory[1].  Accept
that as a possible return code.
[1] http://cr.yp.to/docs/unixport.html

Accept EISDIR as an error code for mkdir(2)

---

std/conv.d

Currently, `std.conv.octal` is only usable with compile-time parameters. This change should be fairly minor, and makes `octal` usable at runtime.

Modify std.conv.octal to be usable at runtime

---

std/range/primitives.d

https://issues.dlang.org/show_bug.cgi?id=14544
Historically, we have not checked for `@property` on range mechanisms, even if they were technically properties. For instance, this compiles:
```D
import std.range.primitives;
struct R
{
int front() { return 0;}
bool empty() { return false;}
void popFront() {}
}
static assert(isInputRange!R);
```
However, a quirk in `typeof(someInstance.someMethod)` returns the type of the member function instead of the type of the *result* of calling the function. So for instance:
```D
// define R as above
R r;
assert(!is(typeof(r.front) == int)); // typeof(r.front) is int(), not int.
```
Therefore, I'm removing several questionable tests from std.range.primitives, as it is erroneous to allow users to call no-arg functions as properties, but deny they are …

Fix issue 14544 - isForwardRange failed to recognise valid forward range

---

posix.mak
win32.mak
win64.mak

This gives control to the repository rather than the auto-tester.
The choice of target is based on current behavior.  For auto-tester-build, the tester isn't specifying a target, so the behavior is 'whatever is first in the makefile'.  That's 'all' for posix and 'targets' for the two windows make file.  For auto-tester-test, that's explicitly 'unittest' in the current tester build scripts.
This will need to be merged to the other branches before the tester can switch to using these new targets.

add auto-tester specific targets

---

posix.mak

On my Powerbook, ran the command:
make clean && /usr/bin/time -lp make -j6 BUILD=debug MODEL=64
Took the best of three runs for baseline and proposed.
Before:  4.93s, 960270336 maximum resident set size
After: 3.85s, 618004480 maximum resident set size
On a big iron at work running Centos 6, ran the command:
make clean && /usr/bin/time -f "%P %M" make -j64 BUILD=debug MODEL=64 lib
Took the best of three.
Before: 5.12s, 1191664
After: 3.86s, 767252

Build phobos package at a time

---

std/conv.d

Reverts D-Programming-Language/phobos#3343
I forgot that `to` and `parse` already do this:
```D
auto x = parse!int(octalString, 8)
```
having 2 ways to do this, within the same module no less, is unnecessary. I'm wondering actually whether `octal` (the one that uses the literal at compile time) could actually simply forward to `parse` instead of having its own special mechanism.

Revert "Modify std.conv.octal to be usable at runtime"

---

std/typecons.d
std/variant.d

Now Algebraic can be used for creating self-referenced types. Refer to https://issues.dlang.org/show_bug.cgi?id=9608 for more motivation (probably this ought to close it).

Alpha renaming, yay

---

std/getopt.d

Removed redundant documentation for `GetoptResult`

Document --help better.

---

etc/c/odbc/sql.d
etc/c/odbc/sqlext.d
etc/c/odbc/sqltypes.d
etc/c/odbc/sqlucode.d
posix.mak
win32.mak
win64.mak

Just a little testing with iODBC - could folks on other OSs give it a shot? There are plenty of simple samples online, I went through this:
```D
import etc.c.odbc.sql;
import etc.c.odbc.sqlext;
int main() {
SQLHENV env;
SQLCHAR driver[256];
SQLCHAR attr[256];
SQLSMALLINT driver_ret;
SQLSMALLINT attr_ret;
SQLUSMALLINT direction;
SQLRETURN ret;
SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &env);
SQLSetEnvAttr(env, SQL_ATTR_ODBC_VERSION, cast(void *) SQL_OV_ODBC3, 0);
direction = SQL_FETCH_FIRST;
while(SQL_SUCCEEDED(ret = SQLDrivers(env, direction,
driver.ptr, driver.sizeof, &driver_ret,
attr.ptr, attr.sizeof, &attr_ret))) {
direction = SQL_FETCH_NEXT;
printf("%s - %s\n", driver.ptr, attr.ptr);
if (ret == SQL_SUCCESS_WITH_INFO) printf("\tdata truncation\n");
}
return 0; …
```

Add etc.c.odbc

---

std/range/package.d

In compliance with C++ STL `std::merge`: http://en.cppreference.com/w/cpp/algorithm/merge
but variadic, of course! :)
Implementation is a tweak of `roundRobin` extended to support bidirectional access iff all its input ranges does.
Respects `CommonType` of the `ElementTypes` of the input ranges.
Propagates infiniteness if any of the inputs is infinite.
- Need advice on what to write about in documentation.
- How about putting `CommonElementType` in std.traits?
- How do we assert that the inputs are sorted according to the template parameter `pred`?
- How about putting `isSortedRange` in `std/range/primitives.d`?
- There might be some clever optimization of the min calculations in successive calls to popFront for a large number of parameters. But that's perhaps outside the scope of this …

Add new lazy range: merge()

---

std/process.d

Can't use result of `tempCString` after it goes out of scope.

std.process.browse() - fix memory corruption bug

---

posix.mak
std/experimental/logger/core.d
std/file.d

Package-shared artifacts used only for unittesting should not be versioned with `version(unittest)` because that precludes unittesting one or more modules against the build library. Example:
make std/experimental/logger.test
has link-time errors. This PR fixes them.

package-shared unittest functions should not be under version(unittest)

---

std/internal/cstring.d

This redoes tempCString() to accept a range as well as a string. The implementation uses a resizable array instead of the complex length estimation logic, and requires only one pass through the range. Removed some functions of dubious merit that were not called from anywhere. Simplified logic now uses the new `byUTF()`. Many unit tests were removed as redundant.

Range-ify std.internal.cstring

---

std/encoding.d

unable to encode/decode symbol "en dash" ('\u2013')

SERIOUS BUG in the windows-1252 charMap

---

std/conv.d

This is in response to the reverting found in pull #3375.
This removes a mention of being experimental and possible future deprecation of a no longer valid 0 prefix.
It also mentions parse for runtime parsing of octal strings.

Minor change to octal documentation

---

std/internal/cstring.d

Reverts D-Programming-Language/phobos#3404
Because it's breaking Phobos std.process unittest in Win32 and 64.

Revert "Range-ify std.internal.cstring"

---

std/bitmanip.d

http://forum.dlang.org/thread/ildhefvrvxxuphkfckcy@forum.dlang.org

Add warning about GC to taggedPointer and taggedClassRef docs

---

std/process.d

Destructors are called for temps created in the leaves of ?: statements. See also https://github.com/D-Programming-Language/phobos/pull/3404

std.process.spawnProcessImpl memory corruption bug

---

std/internal/cstring.d

The same code as for https://github.com/D-Programming-Language/phobos/pull/3404. The https://issues.dlang.org/show_bug.cgi?id=14696 issue is not caused by this PR, and the existing cstring.d it replaces has the same latent issue. Also, 14696 should not hold up this PR, and the Phobos problem has been worked around with https://github.com/D-Programming-Language/phobos/pull/3413

Range-ify std.internal.cstring 2nd try

---

std/net/curl.d

Not tested `static if` branch used `File` symbol without
having proper import
Import got removed unnoticed at some point and broke dub

[REG] Add missing std.stdio import to std.net.curl

---

std/internal/cstring.d

This refactoring is done so that @safe-ty can be inferred from the range input type.

get tempCString to infer @trusted

---

win64.mak

This adds targets `phobos32mscoff` and `unittest32mscoff` to win64.mak.
The 32-bit compiler is derived from the setting for the 64-bit compiler, but can be overwritten on the make command line with `CC32=`
The usual conditions for `VCDIR` and `SDKDIR` apply, ~~though the default is improved by using `$(ProgramFiles)`~~. As for Win64 since the `-conf=` setting, it is necessary to set `LINKCMD`and `LIB` in the environment to link the unittests.

Add targets for Win32/COFF to win64.mak

---

std/range/package.d

All these usages did is badly reinvent `assert()`, but in a way that was more complex and prevented a lot of range based code from inferring `@nogc`.

std.range remove dubious use of RangeError

---

std/internal/cstring.d

Templates should infer their attributes - after all, what if the range argument allocates gc memory (which it does in parts of Phobos)?

std.internal.cstring - @nogc must be inferred

---

std/process.d

Currently using both alloca and finalizers (==destructor call) in a function is unsupported excepting Win32 ([issue 3753](https://issues.dlang.org/show_bug.cgi?id=3753)). However compiler doesn't recognize implicit destructor calls sometimes, and they're not called during stack unwinding ([issue 14708](https://issues.dlang.org/show_bug.cgi?id=14708)).
For the workaround, replace alloca call with malloc + scope(exit) free.

Prevent using alloca and tempCString in same functions

---

std/math.d

- comment out the affected unittests for now
[Issue 14718 – float parsing depends on libc strtold precision](https://issues.dlang.org/show_bug.cgi?id=14718)

workaround Issue 14718 - float parsing depends on platform strtold

---

std/file.d

http://dlang.org/phobos/std_file.html#.remove

Range-ify std.file remove, getSize

---

std/traits.d

This pull request adds the `getSymbolsByUDA` template. It is used for getting a(n) Arguments/TypeTuple from a symbol consisting of that symbol or parts of the symbol that have the specified UDA. This functionality is very important for compile-time reflection.

Add getSymbolsByUDA template

---

std/meta.d
std/typetuple.d

There is no reason to expose this more than it needs to. This ensure the role of backward compatibility already.

Move TypeTuple alias to std.typetuple.

---

std/concurrency.d
std/datetime.d
std/parallelism.d

- use core.time.MonoTime in std.concurrency to break
cyclic dependency of std.datetime and std.concurrency
requires #3208

use initOnce for lazy shared initialization

---

std/datetime.d

This adds an option for getting the time using the coarser, faster
realtime clock on systems that support it for those who need to get the
time frequently (and thus quickly) but don't need it to be particularly
precise.
https://issues.dlang.org/show_bug.cgi?id=13433
The OSX change is because it's the only one using `gettimeofday`. I figured that it was better to change that to go off of the OS version rather than whether `clock_gettime` existed or not.

Implement issue 13433 - add option for using coarser realtime clock.

---

std/string.d

The slice expression `s[]` will match to T[n] by using compile-time length deduction.
Required by: https://github.com/D-Programming-Language/dmd/pull/4779

Supplemental fix for issue 14735 - Prevent self-recursive match

---

std/internal/math/gammafunction.d

Should fix builds on non-x86 targets, where the pretty lame ``yl2x`` intrinsic is not available at compile-time.

Relax compile-time assertion in gammafunction to runtime

---

std/bigint.d
std/internal/math/biguintcore.d

Partial fix for https://issues.dlang.org/show_bug.cgi?id=14503.
Make `BigInt.toString()` distinguish between "%x" and "%X".
In addition, make `toHex()` return explicitly in upper case, for compatibility.

Fix BigInt.toString with "%x"

---

std/uri.d

Can't have cycling static constructor problems if there aren't static constructors!

std.uri - replace static construction with compile time construction

---

std/file.d

This fixes the error:
```
safe function 'std.file.timeLastModified' cannot call system function 'std.file.getTimesWin!(const(char)[]).getTimesWin'
```

std.file: Fix building documentation on Windows

---

std/base64.d

Major cleanup of docs -- grammar, style, missing `Params:` and `Returns:` sections, etc.. Add code examples.
Also fixed two latent ref bugs discovered while adding ddoc'd unittest code examples. Kudos to @AndrejMitrovic (IIRC?) for this life-saving feature! We seriously should convert all Phobos code examples (or as many as possible) to ddoc'd unittests -- you never know what nasty latent bugs you might run into!
For easier review, I've split this PR into 4 commits: the first one is a general documentation overhaul, the second adds code examples, the third addresses said latent bugs, and the last is a minor coding style fix to conform to Phobos bracing style. I thought about submitting separate PRs for these, but since they all touch the same module in scattered locations, the risk of …

TLC for std.base64

---

std/meta.d
std/typetuple.d

Because deep down, it is an alias of sequence. I dropped list as @WalterBright was against the terminology as it is tied to linked list.
I dropped CT (for compile time) as in fact, this is not always compile time. You can have a declaration with a sequence of type as type and a sequence of runtime values as value (it can be used to build tuples for instance).
We could add TypeSeq and ValueSeq if people feel the need (pretty much the same as Alias, but check it contains only types or values).

Rename Arguments to AliasSeq for alias sequence

---

std/format.d

I tried to straighten out the awful logic in this:
1. removed redundant computations
2. it was modifying its ref parameter - to the chagrin of its caller. Fixed that.
3. large arrays should be void initialized
4. most of the explanatory comments were simply wrong
5. did an unnecessary divide op
6. separated the computation logic from the writing operation

std.format.formatUnsigned: refactor

---

posix.mak
std/concurrency.d
std/concurrencybase.d
win32.mak
win64.mak

Following the stdio.d / stdiobase.d model, this adds concurrencybase.d, in order to eliminate the following circular import madness:
```
object.Exception@src\rt\minfo.d(167): Aborting: Cycle detected between modules with shared ctors/dtors:
std.concurrency* ->
std.exception ->
std.range ->
std.range.primitives ->
std.traits ->
std.array ->
std.functional ->
std.ascii ->
std.uni ->
std.format ->
std.conv ->
std.string ->
std.typecons ->
std.json ->
std.math ->
std.stdio ->
std.file ->
std.datetime ->
std.path ->
std.process ->
std.uuid ->
std.digest.md ->
std.digest.digest ->
std.digest.hmac ->
std.algorithm.mutation ->
std.algorithm.comparison ->
std.algorithm.iteration ->
std.parallelism* ->
std.concurrency
```
which happens when building for unit tests on Windows.

add std.concurrencybase

---

std/regex/internal/parser.d
std/regex/internal/tests.d

When encounting the end of a character set ']' we have to correctly add the last
encountered valid character to the regex and resepect flags. This bug caused the
last character to not be correctly case folded if case folding was requested.
This fixes https://issues.dlang.org/show_bug.cgi?id=14529.

std.regex: correctly add last character of a set to regex (bugzilla 14529)

---

std/regex/internal/parser.d
std/regex/internal/tests.d

Simplify the case in std.regex.internal.parser as proposed in the code. Please take this as a RFC to help me understand the code base a bit better. I added some more unittests which should be useful.
@DmitryOlshansky

std.regex: simplify case

---

std/file.d

`timeLastModified()`
`getAttributes()`
`getLinkAttributes()`
`setAttributes()`

Range-ify std.file attribute functions

---

std/uni.d

It is a template function but it only takes `size_t` as a template argument.
It does not contain any impure, throwable, and GC-related operations.
BTW, the expression `storage.ptr+offset[n]` seems  to implicitly assume that `starage.length > offsets[n]` always holds.
Is it correct?
It seems to be equivalent to `&storage[offset[n]]` and it is completely safe operation in the assumption.
If such assumption is correct, can I add an assert `starage.length > offsets[n]`, replace `storage.ptr+offset[n]` with `&storage[offset[n]]` and mark this method as `@safe`?

Mark std.uni.MuliArray.raw_ptr as pure, nothrow and @nogc

---

std/conv.d

Currently, std.format does not return a range, making it not very composable, and std.conv's toImpl() allocates memory. This is a start on fixing that, by adding toChars() which takes an integral type and returns a range of characters, rather than an allocated string.
It uses compile time parameters as much as possible as it is expected this will be a bottleneck for string processing programs.
toImpl() was rewritten to use toChars() internally.

std.conv add toChars()

---

std/algorithm/sorting.d
std/container/binaryheap.d

This pull request replaces the function `percolateDown` in `BinaryHeap` with a more efficient version simply dubbed `percolate`. This function is used initially to build the heap and to restore the heap property when an element is inserted or removed. The original function used a sift-down approach which is typical. This new function uses a [bottom-up](https://en.wikipedia.org/wiki/Heapsort#Bottom-up_heapsort) approach. The code is about 15% faster and performs nearly half the number of comparisons in most cases.
The code was copied over from `std.algorithm:sort`.

Fix Issue 12966 - Optimization for BinaryHeap

---

std/stdio.d

This PR is meant to mitigate the performance drop for some uses of `readln` caused by fixing https://issues.dlang.org/show_bug.cgi?id=13856 in #2794.
Following this example should yield performance similar to byLine.

Follow-up to PR 2794 - add better performing example to readln

---

std/net/curl.d

clearContentLength method make content length option clear as same as contentLength property for cleaing the extra option.
It is done to test the changes by persistent connection.

Issue 14760 - Add clearContentLength for avoiding segmentation fault

---

std/net/curl.d

Test code is in https://github.com/karronoli/std_net_curl_test
It is not tested in curl.d unittest block, because test http server is poor.
- client
- options.d
- server
- options.go

Issue 14763 - Use optionsData argument for options function.

---

std/math.d

Attribute was changed for `RealFormat`, `floatTraits`, `floorImpl`. This
suff is usefull (#3045) in other modules like `std.numeric` and
`std.mathspecial`.

std.math: №1, change protection

---

std/exception.d

assertNotThrown can call expressions that return data.
This allows the data to be returned from assertNotThrown.

assertNotThrown return value

---

std/datetime.d

https://issues.dlang.org/show_bug.cgi?id=14792
We've had the ability to convert from unix time to SysTime, but it has
been more unwieldy than it should be. This adds fromUnixTime to go with
toUnixTime.
In addition, these changes solve the problem where you sometimes need a
value for unix time that doesn't fit in time_t (e.g. a 64-bit value on a
32-bit system), or you're dealing with a 64-bit time_t on a 32-bit
system (which Windows sometimes does). So, toUnixTime and
stdTimeToUnixTime now take an optional template argument which indicates
how many bits the result should be (defaulting to match the size of
time_t), and fromUnixTime and unixTimeToStdTime now take long rather
than time_t so that they can accept 64-bit values on 32-bit systems.

Implement issue# 14792: Add SysTime.fromUnixTime.

---

std/digest/digest.d

Explicitly document return type. Also add a note that string are allocated using the GC.

Extend documentation for toHexString

---

std/range/package.d

The current docs only imply what happens; it is better to be explicit. Even better yet, to have unittests to verify that this is indeed the behaviour.

[dox] Document what happens to take/takeExactly if the range is too short.

---

std/typecons.d

This reverts commit 8f4a85bc83d0205f053b80cafc87b65ad8032ec7, reversing
changes made to d74e4d787a440a00a3d9f9bd7f5c2511e577c15c.
Delay unfinished feature until after 2.068.x.
see #3139

Revert "Merge pull request #3139 from mrkline/better-unique"

---

std/range/package.d

Remove stray `//` from generated docs.
Reorder that example to flow better with the preceding prose.
Fix coding style in code examples.

Improve Lockstep docs.

---

std/meta.d
std/typetuple.d

- cherry-picked all merges regarding AliasSeq

Rename Arguments to AliasSeq

---

std/traits.d
std/utf.d

Reopened #3510 to target stable.
[Issue 14765 – [Reg2.068.0] Rangified functions no longer accept types that implicitly cast to string](https://issues.dlang.org/show_bug.cgi?id=14765)

add std.traits.isAutodecodableString() to fix Issue 14765

---

std/math.d

[Issue 14732 – [2.068 beta] Failing unittest in std.math](https://issues.dlang.org/show_bug.cgi?id=14732)

Fix-up coefficients and smallest denormal value for ieeeDouble in exp()

---

std/net/curl.d

After http request is done, Clear curl option for below problems.
- Prefer CUSTOM request by libcurl
https://github.com/bagder/curl/blob/master/lib/http.c#L1834
- Change any method to PUT after PUT by libcurl
https://github.com/bagder/curl/blob/master/lib/http.c#L1830

Issue 14762 - Reduce confusion for libcurl after HTTP request.

---

std/concurrency.d

http://stackoverflow.com/questions/31616339/non-blocking-concurrent-message-receive

std.concurrency: receiveTimeout: document behavior with negative timeout

---

std/outbuffer.d

- using appropriate type for storage array data allows removing GC.clrAttr(NO_SCAN) calls
- pre-allocating a little more data avoids a number of GC calls that actually don't change the allocation size

std.outbuffer: remove gratuitious calls into the GC

---

std/csv.d

https://issues.dlang.org/show_bug.cgi?id=14846
`new Input!(Range, ErrorLevel)` should take the `input` parameter to initialize its field by that, because: if `Range` is a nested struct, its context pointer is not accessible from inside CsvReader.
Required by: https://github.com/D-Programming-Language/dmd/pull/4848

Supplemental fix for issue 14846

---

std/internal/math/gammafunction.d

Because MAXGAMMA, MAXLOG, and MINLOG are only defined for 80-bit reals, gammafunction.d unittests fail for targets that have 64-bit reals (notably MSVC).
This PR conditionally defines the 64-bit equivalent constants. Also, it contains a fix for gammaStirling(x) in which a call to pow() would overflow for 64-bit reals for x > 143. This fixes several failing unittests. The changes should be a noop for 80-bit reals.
floatTraits from std.math is used to detect whether 80- or 64-bit reals are used; therefore there is a dependency on PR #3011.
The changes are tested using DMD 2.066.1 (Windows) and LDC2 (Windows, version 192583 based on DMD v2.066.1 and LLVM 3.7.0svn-r230699).
Comments are very welcome.

std.mathspecial: for 64-bit reals, provide MAXGAMMA, MAXLOG, and MINLOG

---

std/parallelism.d

https://issues.dlang.org/show_bug.cgi?id=14860
Required by: https://github.com/D-Programming-Language/dmd/pull/4856
`task[] = RTask.init;` has two bugs:
1. `RTask` is a nested struct, so `RTask.init` contains null context pointer.
2. That is a block assignment, so there is a possibility to call
`RTask.~this()` on garbage objects (stack allocated `buf` is initialized by `void`).
Fixed to use `emplaceRef` on each elements.

Supplemental fix for issue 14860

---

std/math.d

The reasons for this PR:
- Gets rid of assembly code that is DMD-specific and does not work for LDC. Special case for Windows CRT is no longer needed.
- Avoiding the x87 FPU means this implementation is faster than the assembly code.
- Not calling C-runtime: ilogb can be inlined and the compiler can reason about it.
- Templated so it runs faster for floats and doubles
Some quick benchmarking showed that it is indeed quite a bit faster, especially (not surprising) for float and double. But the first reason is my main motivation.
I do not know how to do the casts to enable CTFE.
I added a few extra unittests to increase code coverage.
(edit: removed wrong comment about ARM)

Add a D implementation for std.math.ilogb

---

std/variant.d

variant hat some code disabled due to compiler bugs.
Some of these bugs have been fixed.
This re-enables this dead code.
removed some old code

std.variant housekeeping

---

etc/c/zlib.d
std/zlib.d

It looks like the etc.c.zlib.d was mostly written in D1; it isn't const correct, even compared to the original C! http://www.zlib.net/manual.html
Fixing that constness, I went up and started fixing other const related issues in the public API. `compress` returned a const void[]... and uncompress took a mutable array. Why? With the fixed C binding, there was no need for these. (And the presence of two casts on most unittest lines that used this showed the signature was just wrong to begin with anyway. Any typical usage that requires two casts ought to be a bit smelly. Especially since those unittests are the closest thing std.zlib has to usage examples!)
So this fixes the broken api in a way that won't break any code - the fixed signature will still implicitly cast to/from the old one, …

eliminate dangerous and/or useless casts from zlib

---

std/math.d

- promote any comparision with integers to real
[Issue 14842 – [REG 2.068-b2] approxEqual does not work with integers](https://issues.dlang.org/show_bug.cgi?id=14842)

fix Issue 14842 - [REG 2.068-b2] approxEqual does not work with integers

---

std/algorithm/mutation.d

- have to use `(T t) @safe {}`
- turns out that T in `(T) @safe {}` is the parameter
name of a polymorphic lambda not the parameter type
of a function literal

remove workaround for invalid bug 14878

---

std/algorithm/mutation.d

- it's a programming error to call the function w/o
knowing if tgt can accomodate all of src
- for cases where it cannot be known in advance
there is moveSome which will stop when either
range is exhausted
- allows to make moveAll nothrow @nogc depending
on the destructor of T

use assert instead of enforce for moveAll

---

std/mmfile.d

Issue 14868:
MmFile(File,Mode,..) constructor caused the underlying file descriptor to be closed twice, in ~File() and ~MmFile(). Since MmFile destructor called enforce to check return status of close() system call, exception was thrown from inside GC.
The .close() call is safe and the only meaningful error is EBADF, when the descriptor is closed already, so I commented out the enforce part.

mmfile.d: MmFile destructor changed not to cal enforce

---

std/traits.d

This pull request is necessary for https://github.com/D-Programming-Language/dmd/pull/4868.

Fix unittests that ignore the return attribute

---

std/traits.d

I had to introduce a workaround in https://github.com/D-Programming-Language/phobos/pull/3547 because the unittests would not pass without the matching compiler change https://github.com/D-Programming-Language/dmd/pull/4868. Now that the compiler fix is merged, the workaround can be removed.

Remove workaround for unittests failing with compiler change

---

std/container/rbtree.d

Const versions of opSlice, upperBound, lowerBound and equalRange functions are added. They return ConstRange that is a range of const type elements.

Const opSlice, upperBound, lowerBound and equalRange for rbtree

---

std/net/curl.d

This reverts questionable idea of allowing std.net.curl OPTIONS requests with non-empty body.
See #3466

Revert "Merge pull request #3466 from karronoli/fix-curl-options-arg"

---

std/container/slist.d

same as https://github.com/D-Programming-Language/phobos/pull/3554 but targeting the stable branch. I can't edit the target branch. More information about desired target branch on http://wiki.dlang.org/Pull_Requests would help:)
fix https://issues.dlang.org/show_bug.cgi?id=14920
- add a call to initialize() (similar to other insert* functions)
- add unit test

fix issue 14920 - [REG2.067.0] SList.insertAfter on uninitialized list triggers assertion in _first targeting stable branch

---

std/range/package.d

Add more examples to show exactly what happens if one end of the range is reached first.

Improve std.range.radial documentation.

---

std/getopt.d

https://issues.dlang.org/show_bug.cgi?id=14724

Fix issue 14724 - std.getopt: config.required breaks --help

---

std/experimental/logger/core.d
std/experimental/logger/filelogger.d
std/experimental/logger/multilogger.d
std/stdio.d

Finishing up the work from #2393, use `std.file.deleteme` instead.  This is useful on Android, which doesn't allow writing to arbitrary directories and doesn't have a global /tmp directory, so you can [easily hack in the app's absolute path in one place](https://gist.github.com/joakim-noah/5c03801fa6c59b1e90df#file-phobos_ldc_arm-L103).
I had to remove the `pure` attribute for `std.stdio.testFilename` to have it use `std.file.deleteme`, but that didn't matter anywhere in the tests.  I don't think we guarantee such test helper functions will stay the same for users, so I doubt dropping the attribute will matter.

Use a central directory for remaining tests that create a temporary file

---

std/array.d

Also, fixed issues with non-compatible arrays matching the first overload.
Note the rewritten constraint of the second version. It was getting very hairy, so I just decided on a strategy of "it doesn't match the first, and I can call replace, so do it"

Fix issue 14925 -- narrow strings should not match the first overload of replaceInPlace.

---

std/net/curl.d

The examples assign the results of curl functions to a string.  But that doesn't work (at least on on dmd 2.068 running on arch), so I suggest we update them.  Please double-check my changes as I made them very quickly as limited time.

update curl.d documentation

---

std/net/curl.d

- content-length must be set to allow follow-up
post/put/trace requests with empty body
- reset content-length to 0 after _basicHTTP

fix Issue 14760 - Clear content-length for libcurl

---

std/file.d
std/stdio.d

Continue of [phobos#3138](https://github.com/D-Programming-Language/phobos/pull/3138). [Issue 7648](https://issues.dlang.org/show_bug.cgi?id=7648) was [fixed](https://github.com/D-Programming-Language/phobos/pull/3138#issuecomment-103371633) in DMC runtime.
This PR removes Issue 7648 from bugs list in docs. And add Non-ASCII characters in filename for unittests.

Cleanup for Issue 7648: std.stdio expects file names to be encoded in CP_ACP on Windows instead of UTF-8

---

changelog.dd
etc/c/curl.d
posix.mak
std/net/curl.d

- avoids issues with versioned symbols on different platforms
- lazy loading/initialization of curl library
- quick unittests now also need $(LINKDL)
[Issue 13324 – dynamically load libcurl at runtime](https://issues.dlang.org/show_bug.cgi?id=13324)

dynamically load libcurl

---

std/variant.d

Assuming that Foo.depth and Bar.depth are both const (e.g. both are just int
members), the following should compile:
```
int depth(in FooBar fb) {
return fb.visit!((Foo foo) => foo.depth,
(Bar bar) => bar.depth);
}
```
However, it was failing with:
```
std/variant.d(2246): Error: cannot implicitly convert expression (variant.peek())
of type const(Foo)* to Foo*
std/variant.d(2246): Error: cannot implicitly convert expression (variant.peek())
of type const(Bar)* to Bar*
```
This patch changes an explicit `T*` declaration to an `auto` declaration so
const types can be visited.

Allow Variant.visit to support const types.

---

std/net/curl.d

- use infilesize for anything but post requests
though apparently curl can use both for non-POST
methods
[Issue 14877 – std.net.curl needs PATCH http method](https://issues.dlang.org/show_bug.cgi?id=14877)

fix Issue 14877 - std.net.curl needs PATCH http method

---

std/string.d

The `TT` macro was used in the wrong place, causing HTML tag leakage, and there are extraneous spaces that cause the generated link to be broken even after fixing the tag leakage.

[dox] Fix broken hyperlinks to std.algorithm submodules.

---

std/container/package.d

Depends on: https://github.com/D-Programming-Language/dlang.org/pull/1071

[dox] Leading rows in Container Primitives table should span all columns.

---

std/algorithm/iteration.d

https://issues.dlang.org/show_bug.cgi?id=14904
The verbose message is shown only when the given `fun` is actually valid.

[REG2.067.0] Issue 14904 - bad error message in reduce: 'Incompatible function/seed/element'

---

index.d
unittest.d
win32.mak
win64.mak

It seems I missed a few places where the new std.digest.hmac should have been mentioned, because the documentation is missing:
http://dlang.org/phobos/std_digest_hmac.html
Please don't merge yet, I want to make sure there are no other missing places. Can one of the build-system gurus please have a look?

Add missing references to std.digest.hmac to fix doc generation

---

std/array.d

These were missing from the index at the top of the docs.

[dox] Add sameHead/sameTail to function list in docs.

---

std/array.d
std/traits.d

This way opDispatch'ed members are recognized.
Fixes [issue 14605 - RefAppender fails isOutputRange](https://issues.dlang.org/show_bug.cgi?id=14605).
Drive-by change: add a missing Ddoc parenthesis.
This is an alternative to PR #3294.

std.traits.hasMember: just forward to __traits(hasMember, ...)

---

std/syserror.d

Yes, I'm quite aware that the link is a broken one; that's because of [issue 13516](https://issues.dlang.org/show_bug.cgi?id=13516). I think that's outside the scope of this PR. Nevertheless, I think we should put in this deprecation message, otherwise people reading the docs will only see a blank page for the module's docs, which is confusing.

[dox] Add deprecation message to std.syserror module.

---

etc/c/curl.d
std/net/curl.d

- implement test server on second thread that can be
fed with premade responses and records the requests
- rewrite tests
- fix upload which didn't work at all
[Issue 14938 – std.net.curl tests should use localhost or stub any networking](https://issues.dlang.org/show_bug.cgi?id=14938)

fix Issue 14938 - std.net.curl tests should use localhost or stub any networking

---

std/algorithm/iteration.d
std/conv.d
std/format.d

Changed `format()` to return the same type of string that was inputted.
For instance, formatting a *dstring* returns a *dstring* and not *string*.

format() returns the correct type

---

std/zip.d

For whatever reason, the dmd test suite has tests for std.zip, though
for the most part, they seem to just run it without actually checking
the results, making them of questionable value. But this commit ports
them to std.zip (to remove a Phobos dependency in the dmd test suite)
and attempts to make it so that they actually check the results. So, the
tests are not identical by any means, but they're similar. Perhaps the
most significant test is the one that tests a file that's written with
std.zip against the unzip utility, since that's testing against
something that we didn't write.
The corresponding PR for dmd to remove the tests from the dmd test suite is here: https://github.com/D-Programming-Language/dmd/pull/4987

Port std.zip tests from the dmd test suite to std.zip.

---

std/zlib.d

https://issues.dlang.org/show_bug.cgi?id=14799

fix Issue 14799 - Documentation for std.zlib.compress is incorrect

---

std/complex.d

Add `Params:` and `Returns:`, make unittests ddoc'd examples.

[dox] Improve std.complex ddocs.

---

std/exception.d

Add `Params:` and `Returns:`.
Reorder function overloads to appear consecutively so that ddoc will merge them correctly in the output. The original order causes ddoc to produce funky output.
Replaced the doc reference to `pointsTo` with `doesPointTo` based on the current definition of `pointsTo`, which has been marked deprecated.  I think this is correct...?

[dox] Improve docs for std.exception.{does,may}PointTo

---

std/experimental/logger/core.d
std/typecons.d

https://issues.dlang.org/show_bug.cgi?id=14940

fix Issue 14940: Can't call logger with more complex objects

---

std/algorithm/sorting.d
std/math.d

Adds a `totalOrder` function as specified in IEEE 754-2008.
An immediate benefit is the ability to sort arrays of floating-point values and get predictable results even in presence of NaNs (see http://dpaste.dzfl.pl/1f78bc6f7d2b).

Total ordering for floating-point values.

---

std/path.d

Plus various doc improvements.
This PR adds `Params:` and `Returns:` sections to the docs of all public functions in `std.path` that don't already have these sections. Some rewording was done to eliminate repetition in the resulting docs.

[dox] Add missing Params and Returns to std.path docs.

---

std/array.d

https://issues.dlang.org/show_bug.cgi?id=10895
Test case only.

Issue 10895 - incorrect std.array.join behavior with array of string-like class using alias this

---

std/container/rbtree.d

Low hanging fruit:
https://issues.dlang.org/show_bug.cgi?id=5945
My solution is a little different than the original suggestion, as it isn't known if the redBlackTree factory function was used or not.

Fix Issue 5945: redBlackTree printing

---

index.d

Before, table rows were faked with $(BR). This has a couple issues:
* pseudo rows fall apart when one cell breaks but the other doesn't;
* copy/paste doesn't work properly;
* editing the table is more complicated and error-prone;
* it's just plain wrong.

index.d: proper table rows

---

posix.mak

- fixes make CC=/path/to/cc
- fixes Issue 15012
[Issue 15012 – Druntime Makefile whitelists compilers](https://issues.dlang.org/show_bug.cgi?id=15012)

filter on basename of compilers

---

std/cstream.d
std/socketstream.d
std/stream.d

stream needs to go
as discussed at dconf15:
* remove streams from docs 2.068
* deprecate streams 2.069
* remove streams 2.071 ( move to undead)

stream deprecation

---

std/concurrency.d

NB: Is the use of "analog" correct here? It sounds a bit odd to me.

Removed typo in std.concurrency, line 1196

---

std/algorithm/comparison.d

Add `Params:` and `Returns:`, and turn unittest into ddoc'd code example.

[dox] Improve docs for std.algorithm.comparison.min

---

std/range/package.d

https://issues.dlang.org/show_bug.cgi?id=15033
Use CommonType in iota()
See also: http://forum.dlang.org/post/ahjmgdslmiakoxszynty@forum.dlang.org

Fix issue 15033 -  Element type of float iota is double

---

std/cstream.d
std/socketstream.d
std/stream.d

2.070 is too early to remove std.stream. Our normal policy has been to deprecate something for a year and leave it documented and then remove its documentation but leave it deprecated for another year before removing it. So, folks have about two years to update their code, and we minimize how often someone goes to update their compiler and finds that their code doesn't compile anymore, because a symbol that they were using is now gone, and they never saw the deprecation message for it, because they were slow to upgrade. std.stream has been marked for years as being intended for deprecation but not actually deprecated. With 2.068, it was removed from the documentation but not deprecated. For 2.069, it's been deprecated but was marked for removal in 2.070, meaning that it would have been …

Adjust deprecation messages for std.stream.

---

std/encoding.d

This is freshly remade PR #3173 to have clean commit history as requested.
It is the same as in the original, but with added private keyword to the EncoderInstance templates for cp1250 and iso-8859-2 only (I left the other ones intact).
Sorry for messed up PR, still not used to some git usages.

Fix issue 14433 - std.encoding does not support Central European ISO-8859-2 and CP1250 encodings

---

std/datetime.d

This reverts the changes that Robert made to some of std.datetime's tests in three recent PRs:
https://github.com/D-Programming-Language/phobos/pull/3655
https://github.com/D-Programming-Language/phobos/pull/3662
https://github.com/D-Programming-Language/phobos/pull/3661
Robert's changes are well-intentioned, but putting unit tests inside of templates results in them be instantiated every time that the template is instantiated, resulting in extra compilation time and making the tests take longer. Even worse, if all of the tests are moved into the template, then they don't even get instantiated.
The *Interval structs in std.datetime are templated, and the tests were quite carefully put outside of the templates so that they would not get instantiated over and over again or run over and over …

Undo changes that move std.datetime unit tests inside of templates

---

std/mmfile.d

https://issues.dlang.org/show_bug.cgi?id=14868
https://issues.dlang.org/show_bug.cgi?id=14994
https://issues.dlang.org/show_bug.cgi?id=14995

std.mmfile - fix multiple issues

---

std/encoding.d

Modified the same way as in #3626
I'm planning to add more encodings on top of this - let me know if you prefer to add it to this PR or make it separate (for example by encoding usage region).
For now I kept it simple for review.
GenericEncoder is modified to handle narrowed character map as with cp1252 only a small subrange is not mapped directly.
Also modified the gen tool [0] to generate EncoderInstance from encoding mapping files.
[0] https://github.com/chalucha/encgen

std.encoding - optimization of windows-1252

---

std/datetime.d

Okay. I updated the time zone conversions to the latest.
https://issues.dlang.org/show_bug.cgi?id=15085

Fix for issue# 15085: Microsoft changed their timezone names again.

---

std/stdio.d

Add underscores to prevent auto formatting of parameter name "format".
https://issues.dlang.org/show_bug.cgi?id=15095

fix issue 15095

---

std/range/package.d

* removed dead code
* moved imports to local

Trivial Improvements To SortedRange

---

std/algorithm/package.d

My understanding is that passing predicates as lambdas is a current best practice for `std.algorithm`. This mentions them in the docs for the package.

Mention lambda predicates in std.algorithm

---

std/typetuple.d

https://issues.dlang.org/show_bug.cgi?id=15115

[Ddoc] fix links on std.typetuple page (issue 15115)

---

std/conv.d

By importing std.exception for assertThrown().

Fix std.conv unittest compile error for platforms with 64-bit reals

---

std/string.d

this was broken by recent rangefing of indexOf.
This PR recreates this feature.
https://issues.dlang.org/show_bug.cgi?id=15057

indexOf used to accept user defined structs

---

std/uuid.d

https://gist.github.com/9il/7480f54792e22b1e916f
based on DMD v2.067.1 and LLVM 3.6.0
```
$ldmd2 -O -inline -release -boundscheck=off -run uuid_bench.d
Old constructor: 397 μs and 3 hnsecs
New constructor: 41 μs and 9 hnsecs
Old toString: 47 μs and 3 hnsecs
New toString: 21 μs and 8 hnsecs
```
2.068.2
```
$dmd -O -inline -release -boundscheck=off -run uuid_bench.d
Old constructor: 1 ms, 852 μs, and 7 hnsecs
New constructor: 75 μs and 4 hnsecs
Old toString: 184 μs and 7 hnsecs
New toString: 51 μs and 6 hnsecs
```
_______
*time for 1000 conversions.

Optimize UUID to/from string conversion

---

std/algorithm/iteration.d
std/algorithm/mutation.d

* fixed two spelling mistakes
* Added missing params and returns
* removed in doc examples (one of which didn't even compile) for unit test examples
* fixed examples for `reduce` not being included

Fixed some docs in std.algorithm

---

std/getopt.d

https://github.com/D-Programming-Language/phobos/commit/6c8b8232c30c38cd2140625225e0b7211a4319ae#commitcomment-13600264

std.getopt: Re-add constructor removed in PR #3489

---

std/experimental/allocator/package.d

https://issues.dlang.org/show_bug.cgi?id=15187
Duplicate of #3687
The bug can cause memory leaks when `dispose` is used with blocks like FreeList.

[DMD 2.069][allocators] Fix issue 15187

---

std/experimental/allocator/building_blocks/free_list.d

`deallocate` cause memory leaks 
https://issues.dlang.org/show_bug.cgi?id=15188

[DMD 2.069][allocators] Fix issue 15188

---

std/experimental/allocator/typed.d

Fixed compile-time error when Policies was empty. Repro with
```
import std.experimental.allocator.mallocator;
import std.experimental.allocator.typed;
alias A = TypedAllocator!(Mallocator);  // slice[1..0]
```

Allow TypedAllocator.Policies to actually be empty

---

etc/c/curl.d
std/container/array.d
std/json.d
std/socket.d

Doc formatting fixes needed for https://github.com/D-Programming-Language/dmd/pull/4745

Doc formatting fixes for DMD PR 4745

---

std/variant.d

A unittest triggers in line 1918 when testing `Variant!(void[0])` with LDC (current `merge-2.068` branch).
When taking the address of a truly empty type, such as `T[0]`, LDC always returns a null constant; nothing is allocated on the stack.
Disabling this assert in case the target type's size is 0 should be safe, there's no private state which could be modified by the following assignment (it may still have side effects though) - right? ;)

std.variant: don't assert that target address != null if type size is 0

---

std/bigint.d

https://issues.dlang.org/show_bug.cgi?id=15212

fix Issue 15212 - BigInt should implement opCast!long and opCast!int

---

std/getopt.d

https://issues.dlang.org/show_bug.cgi?id=15220

fix Issue 15220 - [REG2.065] std.getopt parses -o=value as "=value"

---

std/experimental/allocator/building_blocks/free_list.d

It seemed apparant that allocateEligible should request 'max' bytes from the parent, otherwise a bigger subsequent allocation that takes the returned memory from the root may request an array slice that's too large for an existing buffer. I tested this by creating a class that was 24 bytes, allocating and then deallocating a number of them (4 at a time) on a free_list (with minSize 24, maxSize 108) on top of a mallocator, then switching to allocating a class that used the max, which caused a crash. This change fixes that case and should prevent this class of error.
This was previously a pull request for andralex's fork for that he requested I move here.

Modified allocateEligible to prevent memory stomping

---

std/exception.d

Per discussion in https://github.com/D-Programming-Language/phobos/pull/3589

[dox] Revise confusing wording of "if !value is false" in std.exception.enforce

---

std/string.d

make entab take custom types again that have an alias this to string as auto
ref

std.string.entab_alias_string_fix

---

std/string.d

make splitLines take custom types again that have an alias this to string

std.string.splitLines_alias_string_fix

---

std/format.d

Currently when a floating point argument to format is not provided a compatible format character i.e. one of `fgFGaAeEs`, then it throws an exception whose message is just "floating", which is vague, to say the least. I have made it now give a meaningful message.
I'm not sure why this can't be detected at compile time, though, since I seem to remember Clang warning me of incompatible specifiers in case of C `fprintf`... Even `dmd -wi` doesn't give any warning.

std.format: give a proper message when a floating point value is not given a compatible format character

---

std/file.d

https://github.com/D-Programming-Language/phobos/pull/3753 now on stable.
This adds the usual overload taking the struct by auto ref, avoiding issues with expensive or disabled posblit.
https://issues.dlang.org/show_bug.cgi?id=15027
Other functions in std.file have been rangified in previous releases, these should get the same fix.

fix Issue 15027 - rangified function isDir no longer works with alias this'ed strings

---

std/format.d
std/uni.d

This PR enables Phobos to compile properly without error with [DMD PR #5229](https://github.com/D-Programming-Language/dmd/pull/5229). This PR must be merged first, so that the DMD PR can pass the auto-tester.
The change to `std.uni` simply makes an implicit cast into an explicit one. This is necessary because the basis on which the old version of the compiler "proved" the cast to be safe included the faulty assumption that `dchar` values can never be greater than `dchar.max`. (Hopefully in the future VRP can be improved to take the assertion on line 4890 into account, instead. But that's probably a big project.)
The change to `std.format` is to prevent a "statement not reachable" warning on the original line 544, caused by the upgraded compiler correctly detecting that when `A.length == …

Trivial fixes to enable Phobos to compile properly with DMD PR #5229.

---

std/algorithm/comparison.d
std/file.d
std/path.d
std/string.d
std/traits.d
std/uni.d

- [Issue 15027 – rangified functions no longer work with alias this'ed strings (e.g. DirEntry)](https://issues.dlang.org/show_bug.cgi?id=15027)

fix Issue 15027 – rangified functions no longer work with string-like types

---

std/algorithm/comparison.d
std/file.d
std/path.d
std/string.d
std/traits.d
std/uni.d

- undocument overloads for aliased/static strings
- make std.traits helpers phobos internal
- rename isStringLike to isConvertibleToString for clearer documentation
- rename peelStringLike to convertToString
- fix a few staticMap!(selectString) uses in std.path

fixup for string-like overloads

---

std/algorithm/searching.d
std/typecons.d

This enables the following useful syntax:
```D
if (const split = line.findSplit(`-`))
{
// do something with split
}
```
instead of current
```D
const split = line.findSplit(`-`)
if (!split[1].empty)
{
}
```
for the Phobos algorithms `findSplit`, `findSplitBefore` and `findSplitAfter`.
See also discussion at: http://forum.dlang.org/thread/etttlwazcguwpaltyrps@forum.dlang.org#post-tbnvyqawcqmccvociwrr:40forum.dlang.org

Struct Returned findSplit*() with implicit bool conversion

---

std/algorithm/comparison.d
std/traits.d

Thanks to D's lazy parameters this function simplify pattern matching:
`either()` similar to Python/Lisp's `or`. Same as D's `any` but returns first parameter value which implicitly convert to true, or last argument otherwise. I guess `any` could be modified but that would cause breakage on its return type.
I've found real use of `either()`in various parsing contexts.
I'm very open to changing the namings if you feel they are misguiding.
Note that `either` currently cannot be `nothrow` because of issue    https://issues.dlang.org/show_bug.cgi?id=12647

Add new algorithm: either()

---

std/typecons.d

This request adds `@safe`, `pure`, `nothrow` and `@nogc` to several methods for `RefCounted` and `RefCountedStore`.
Here are the details:
- `RefCountedStore.isInitialized` and `refCount`: There are no impure nor GC-related operations.
- `RefCounted.this(this)`: There are no unsafe, impure, throwable nor GC-related operations.
- `RefCounted.refCountedPayload`: There are no impure nor GC-related operations.

Add attributes to several methods for std.typecons.RefCounted

---

std/container/dlist.d

As createNode was taking a value by ref, Dlist.insertFront could not be
called with a range with a non-ref front.
Fix by providing a createNode overload to use for non-ref values.
Resolves #15263.

Fix DList.insertFront(range) regression - #15263.

---

std/datetime.d

Requires https://github.com/D-Programming-Language/druntime/pull/1423.

Add missing functionality for OpenSolaris to std.datetime.

---

std/meta.d

Add template that allows for conversion of arrays and input ranges to AliasSeqs.

Add AliasSeqOf to std.meta

---

std/stdio.d

2612 was the only bug that still had a workaround.

[Issue 3764] Remove Phobos workarounds for fixed bugs

---

std/datetime.d

`GetTimeZoneInformation` is a Windows API function, and thus will never throw a D exception. Presumably, at the time this code was written, it was not marked as nothrow. However, instead of fixing the function's signature, the code contained try/catch blocks with messages such as `assert(0, "The impossible happened. GetTimeZoneInformation() threw.");`
CC @jmdavis

std.datetime: Remove redundant try/catch around GetTimeZoneInformation

---

std/uni.d

This lays on the foundation of UTF word notion,
a 32-bit integer that contains UTF encoded codepoint.
Top non-zero byte is the UTF-8 starter, so it's BigEndian
when reading directly from strings.
Same applies to UTF-16 word.
Also this invents simpler API for matching that easily combines:
- length of code point matched
- result of match (true/false if belongs to this set)
- bad encoding flag
In one packed 32-bit machine word.

New primitive - Tiny UTF Binary Search Table

---

std/internal/math/gammafunction.d

Using LDC master on Win64, I get a relative diff of 1.068e-15 for the second tuple (input = 1/8), exceeding the allowed upper bound by not even 7%. I chose to be generous and doubled the limit. ;)
More details for the 2nd tuple:
```
actual:   0x1.0a333fd8b6880p+2
expected: 0x1.0a333fd8b687bp+2
rel diff: 1.067682e-15
```
The other 4 tuples are perfect matches.

Slightly relax std.internal.math.gammafunction unittest for 64-bit reals

---

std/conv.d

The pattern `static assert(__traits(compiles, xyz))` arised probably as a converse to its negation, e.g.:
```d
static assert( __traits(compiles, emplace(&ss2)));
static assert(!__traits(compiles, emplace(&ss2, SS2.init)));
```
However, the pattern should be avoided for two reasons:
1. Often it's best to also execute the code and make sure it works as expected (as this PR shows for the octal examples)
2. When working on the module, a failure of `static assert(__compiles)` does not show the reason in the error messages. This makes code more difficult to work with gratuitously.
This is just the beginning - could someone please eliminate this pattern from all of Phobos? Thanks!

Remove `static assert(__traits(compiles, xyz))` from `std.conv`

---

std/string.d

* removed old, obsolete doc comment
* added unittest examples
* rewrote documentation to use params and returns

Add unittest examples to std.string.isNumeric

---

std/format.d

* reactived outcommented unittests
* moved comment examples into unittest examples
* fixed indention

std.format_housekeeping

---

std/stdio.d

This removes the decoding misfeature of LockingTextReader. Also, the call to ungetc() is moved to the destructor, so it only gets called once.
https://issues.dlang.org/show_bug.cgi?id=14861
The earlier attempt:
https://github.com/D-Programming-Language/phobos/pull/3622
Alternate fix proposal:
https://github.com/D-Programming-Language/phobos/pull/3696

[REG] fix Issue 14861 - Error in stdio.d in LockingTextReader.readFront()

---

std/stdio.d

ReadlnAppender tried to claim the capacity of the passed buffer, calling
assumeSafeAppend on the result so that on the next call it has a capacity
again that can be claimed.
The obvious problem with that: readln would stomp over memory that it has
not been given.
There was also a subtler problem with it (which caused issue 15293):
When readln wasn't called with the previous line, but with the original
buffer (byLine does that), then the passed buffer had no capacity, so
ReadlnAppender would not assumeSafeAppend when slicing the new line from
it. But without a new assumeSafeAppend, the last one would still be in
effect, possibly on a sub slice of the new line.
https://issues.dlang.org/show_bug.cgi?id=15293

fix issue 15293

---

std/conv.d

The logic in `emplace` copies the logic used by the compiler itself in generating constructors. After sleeping on it for a night I figured I could get most of that logic just work for us by defining a `struct` with only one member and one constructor. Then the rest is taken care of.

Simpler emplace

---

std/file.d

https://issues.dlang.org/show_bug.cgi?id=15146

fix Issue 15146 - std.file.dirEntries("") only works on Windows

---

std/bitmanip.d

```d
@property void alice(bool v) @safe pure nothrow @nogc { if (v) _alice_bob |= 1U;else _alice_bob &= ~1U;}
```
This getter is wrong because the `&=~1U` would clear not just the first bit, but bits 32-64 as well. This in turn because of the code in `myToString`, which picks the smallest type suffix, `U` in this case.
Fixed by casting the `1U` to the type of the storage, before negating.

[Issue 15305] bitfields! setter erroneously clears subsequent fields

---

std/math.d

From the conversation and comparing of results in #3483 - the following was found for the result of ``exp(-0x1.64p+9L)``:
Win64 | ARM | ARM libm (expl) | x86 (double) | x86 libm (exp) | LLVM intrinsic | GCC intrinsic
----- | ----- | ----- | ----- | ----- | ----- | ----- 
0x0.06f84920bb2d3p-1022 | 0x0.06f84920bb2d4p-1022 | 0x0.06f84920bb2d4p-1022 | 0x0.06f84920bb2d4p-1022 | 0x0.06f84920bb2d4p-1022 | 0x0.06f84920bb2d4p-1022 | 0x0.06f84920bb2d4p-1022 
With feqrel giving the following number of mantissa bits in common (53 means identical to ``0x0.06f84920bb2d3p-1022L``).
Win64 | ARM | ARM libm (expl) | x86 (double) | x86 libm (exp) | LLVM intrinsic | GCC intrinsic
----- | ----- | ----- | ----- | ----- | ----- | ----- 
53 | 51 | 51 | 51* | 51* | 51 | 36*
[*] UPDATE: Whoops, I forgot to set …

Adjust expected result of test to match ARM and others

---

std/file.d

Add std.path to the See Also section, because it is relevant to users of std.file.
This replaces my earlier [3826](https://github.com/D-Programming-Language/phobos/pull/3826). I did not change the top paragraph, as requested in the previous PR.

Add reference to std.path

---

std/file.d

I merged a comment only PR that added a litte bit of doc.
It containted whitespace at the end.
This PR removes that whitespace.

std.file whitespace fix

---

std/algorithm/iteration.d
std/algorithm/mutation.d
std/array.d
std/datetime.d
std/meta.d
std/path.d
std/range/package.d
std/range/primitives.d
std/traits.d
std/typecons.d
std/utf.d

https://issues.dlang.org/show_bug.cgi?id=15320
There are still some occurrences remaining:
* 12 in `std/concurency.d`: `spawn`s create threads
* 3 in `std/conv.d`: couldn't figure it out
* 1 in `std/exception.d`: must stay, `__traits(compiles` is called in a loop with different checked results
* 24 in `std/file.d`: file operations
* 3 in `std/numeric.d`: don't know if it can/should be replaced
* 2 in `std/traits.d`: don't know how
The regex used for searching: `static\s+assert\s*\(\s*__traits\s*\(\s*compiles`

[Issue 15320] eliminate 'static assert(__traits(compiles,..'

---

std/algorithm/iteration.d
std/bitmanip.d
std/complex.d
std/datetime.d
std/system.d
std/traits.d
std/typecons.d

DDLINK/DDSUBLINK use ROOT_DIR which is more robust than a relative path.
Together with https://github.com/D-Programming-Language/dlang.org/pull/1159 this fixes the links in the online DDox docs.

use DDLINK/DDSUBLINK instead of LINK2 and raw HTML

---

std/internal/test/uda.d
std/traits.d

Resolves #15335: getSymbolsByUDA fails if type has private members.
Generous (ab)use of mixins allows getSymbolsByUDA to reference symbols
without trying to access them, allowing it to inspect private members
without failing.
Testing this required private symbols defined outside of std.traits.
This adds std.internal.test.uda, which defines a struct containing
private members that is used in a unittest added to std.traits.
My previous implementation, #3817, simply ignored private members.

Enable getSymbolsByUDA to retrieve private members.

---

win32.mak
win64.mak

Let's try this again. This is a copy of #3841 opened against stable.
There were a few lines that used spaces instead of tabs, so I changed those to tabs as well. These changes seem to work, but please review them carefully as I don't actually know make; I just imitated what was already there. I also have not tested the win64.mak changes.

Fix Issue 15281 - Add std.experimental.allocator to the build script

---

std/range/package.d

https://issues.dlang.org/show_bug.cgi?id=15385
There is an internal function, getTransitionIndex(), which is already optimal in terms of predicate calls. I simply forwarded the call to that function and performed one last predicate call to check for equality.

Fix Issue 15385 - SortedRange.contains() optimize predicate calls

---

std/datetime.d

There is currently no usage example and no way for the reader to know how to specify a duration.

Documentation: Added example to DateTime opBinary and reference to core.time.Duration

---

std/math.d

This is a simple fix for Phobos [Issue #14786](https://issues.dlang.org/show_bug.cgi?id=14786).
Negative one raised to any odd power should yield negative one.
However, when using 80-bit real arithmetic, -1 raised to a power greater than 2^^63 and less than 2^^64 yields +1.
This is despite the fact that integers in this range can still (just barely) be represented without loss of precision by an 80-bit real; even and odd can still be distinguished.
```D
/** Test cases that fails without this PR **/
void main(string[] args)
{
real b = -1;
real e = long.max;
e += 2;
assert(e % 2 == 1);
real r = b ^^ e;
assert(r == 1);  // Passes, but shouldn't
assert(r == -1); // Fails, but shouldn't
e = ulong.max;
assert(e % 2 == 1);
r = b ^^ e;
assert(r == 1);  // Passes, but shouldn't
assert(r == -1); // …
```

Fix Issue 14786 -  std.math.pow sometimes gets the sign of the result wrong.

---

std/range/package.d

There's an assert(chunkSize != 0) in the constructor which needs to be
documented.
https://issues.dlang.org/show_bug.cgi?id=10087

document that chunkSize must be positive

---

std/conv.d

This is a fix for [Phobos Issue #15419](https://issues.dlang.org/show_bug.cgi?id=15419): `std.conv.parse()` does not accept string literals.
I saw someone complaining about this on [dlang.org "Learn"](http://forum.dlang.org/post/n451e6$jg6$1@digitalmars.com). This also resolves the bug report embedded in a (pre-PR) `unittest`, with the somewhat silly label, `@@@BUG@@@ the size of China`.
For now, I have added a simple wrapper to handle character arrays, specifically; I don't see an easy way to support arbitrary rvalues. The long-term solution to this problem would be `scope ref`, but who knows when that will be fully implemented...

Fix Issue 15419 - "@@@BUG@@@ the size of China"

---

std/container/package.d

takeOne returns a special type for ranges without slicing, so it just
happened to work with Array, but it doesn't work with say, linked lists.

s/takeOne/take/ in std.container package documentation

---

std/random.d

The documentation of std.random.RandomSample shows all range primitives except .front

RandomSample.front was not documented

---

std/json.d

Currently `std.json` treats the Unicode control characters asymmetrically: it can decode them, but on encoding it throws an exception.
This PR implements the control character encoding similarly to other JSON libraries (ex. python)

std.json: Encode control characters

---

std/algorithm/iteration.d
std/bitmanip.d
std/c/fenv.d
std/c/freebsd/socket.d
std/c/linux/linux.d
std/c/linux/linuxextern.d
std/c/linux/pthread.d
std/c/linux/socket.d
std/c/linux/termios.d
std/c/linux/tipc.d
std/c/locale.d
std/c/math.d
std/c/osx/socket.d
std/c/process.d
std/c/stdarg.d
std/c/stddef.d
std/c/stdio.d
std/c/stdlib.d
std/c/string.d
std/c/time.d
std/c/wcharh.d
std/c/windows/com.d
std/c/windows/stat.d
std/c/windows/windows.d
std/c/windows/winsock.d
std/format.d
std/windows/iunknown.d

This includes deprecating std.c.*, which apparently was marked as
scheduled for deprecation in 2.068 but never actually deprecated (though
it looks like it was previously removed from the documentation build,
since it doesn't show up on dlang.org).

Move deprecations along.

---

std/range/package.d

It was added to the top of std.algorithm but not here.

Add Ali's range tutorial to std.range docs

---

posix.mak
std/experimental/ndslice/internal.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/package.d
std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d
win32.mak
win64.mak

[![Coverage Status](https://coveralls.io/repos/9il/dip80-ndslice/badge.svg?branch=master&service=github)](https://coveralls.io/github/9il/dip80-ndslice?branch=master)
DUB package at [dip80-ndslice at code.dlang.org](http://code.dlang.org/packages/dip80-ndslice).
Voting thread: http://forum.dlang.org/thread/nexiojzouxtawdwnlfvt@forum.dlang.org
Review thread: http://forum.dlang.org/thread/uesnmkgniumswfclwbgt@forum.dlang.org
Old announce at [forum](http://forum.dlang.org/thread/rilfmeaqkailgpxoziuo@forum.dlang.org). 
See the last commit for documentation (CyberShadow/DAutoTest -> Details -> Phobos -> std -> experimental -> ndslice).
Source: https://gist.github.com/9il/bc7966823d96557c566c
LDC disassembled: https://gist.github.com/9il/47aea1621a9fba609869 (all functions are inlined!)
DMD …

std.experimental.ndslice [ready to merge]

---

std/concurrency.d

It shows how to create a thread in the air with an anonymous function without requiring to define separately.

An extra example is added for spawn function.

---

std/experimental/ndslice/slice.d
win32.mak
win64.mak

@MartinNowak this PR upgrades the win*.mak files to build docs on windows and uncomments a unittest with dummyranges. The unittets was commented before #3806 was merged.

[2.070][ndslice] update win*.mak & uncomment unittest with dummyranges

---

std/math.d

I get:
```
poly(3.1, pp)
= 215.13000000000000622168982999937725
(56.1L + (32.7L + 6.0L * 3.1) * 3.1)
= 215.13000000000000896949181594663969
```
Using the non-IASM paths in ``polyImpl``.

Fix precision bug in poly unittest

---

std/typecons.d

For the conversation and reasons for the reopening see [here](github.com/D-Programming-Language/phobos/pull/3594). In a nutshell, I did a wrong rebase.
From [Forum: Make Tuple.toString useful](http://forum.dlang.org/thread/srofuqyrdzphgzylbwds@forum.dlang.org):
With this, you can easily format a `Tuple` from its content, similar how to do with an array.
The `toString(delegate, FormatSpec)` function takes the formats `%(nested%)` and `%(nested%|separator%)` a bit different: The second one treats the Tuple as it was an array. The first one applies the nested format to the expanded fields, like `format(nested, tup.expand)` did.
With this, the forum question [Formatted output of range of tuples](http://forum.dlang.org/post/ntqawkupddjcijwtwovp@forum.dlang.org) gets a trivial answer: Use …

PR "Tuple's toString made useful" once again.

---

posix.mak
std/c/windows/com.d
std/c/windows/stat.d
std/c/windows/windows.d
std/c/windows/winsock.d
std/windows/charset.d
std/windows/iunknown.d
std/windows/syserror.d

This is a blunt-instrument attempt at fixing: https://issues.dlang.org/show_bug.cgi?id=14972
This PR causes docs to be generated from `std.windows.*` modules. It's not perfect, however, as everything under `version(Windows)` is still not generated. But at least `std.windows.syserror` appears to have been specifically written to generate docs on all platforms, so at least this will fix: https://issues.dlang.org/show_bug.cgi?id=13516
There are probably many issues that I overlooked. Please comment.
Depends on: https://github.com/D-Programming-Language/dlang.org/pull/1083

Issue 14972: Generate Windows docs regardless of host platform

---

std/algorithm/sorting.d

The code requires slicing but the template does not specify that.
Ping @MartinNowak, this is a bug fix that should go into 2.070

Fix Too Permissive Template Constraint in topN

---

std/process.d

This diff: This diff makes it possible to specify your preferred shell for the various `*shell` functions in `std.process`. By default it uses the new `nativeShell` function. `nativeShell` to always returns the native system shell (see the "some history" section for why this is the default value). I chose to create `nativeShell` rather than changeing `userShell` because I think it is still valuable to have something like `userShell` around in Phobos.
The one part of this diff I'm not super thrilled by is the use of variadic arguments (easier to see than to explain); if you have a suggestion for something better I'd love to hear it :).
Note: The default shell is a breaking change for Windows, which probably *should have* been broken same as posix in the diffs listed in the history section …

Issue 15276: Allow users to specify shell for executeShell, pipeShell, spawnShell

---

std/range/package.d

Forum thread:
http://forum.dlang.org/post/n3sfgg$1hpm$3@digitalmars.com
Differences from Andrei's suggestion:
* Returns `Range`, not `TakeExactly!Range` - the end of the resulting range is always the same as the input so this checks out and is a useful artifact.
* Supports non-forward ranges when `hasLength`.
* Rejects infinite ranges.
I thought `tail` was clever so I named it that, but I'll happily change it to the originally proposed `advanceWithin` if people want that.

Add std.range.tail

---

std/algorithm/searching.d
std/algorithm/sorting.d

* Replace random selection with getPivot, which is also used by sort. 
* Use a local copy instead of swapping range elements around when possible
* Special-case n==0, which may be either requested from the beginning or occur naturally toward the end of the search.

Fix Issue 15553 - topN very inefficient [slower than sort, even for topN(0)] but should be O(n)

---

std/typecons.d

Is it a bit of a hack? Yes, but it works without language changes (see http://forum.dlang.org/post/vfgawgvzzfgjhshavmlq@forum.dlang.org).
Thanks to @tgehr (Timon Gehr) for the idea, although it seems others have also been using the same technique elsewhere.

Fix Issue 15561

---

std/bitmanip.d
std/math.d
std/numeric.d

This PR requires [druntime #1452](https://github.com/D-Programming-Language/druntime/pull/1452), which adds `ulong` support to `bsf()`, `bsr()`, and `popcnt()` in `core.bitop`, even on 32-bit systems.
Phobos currently contains three different private implemenataions of `bsr` for `ulong`, one of which appears to not work properly on big endian systems. This updates Phobos to just use the improved `core.bitop.bsr()` everywhere, instead.
It also fixes another minor bug in `std.Numeric`: in `roundDownToPowerOf2()`, this expression: `(1 << bsr(num))` is always 32-bit, whereas it should, at a minimum, match the bit-ness of `num`.
**EDIT:** I noticed that the integer overloads of `ilogb()` are undocumented, so I fixed that too.

Update Phobos for druntime PR #1452 core.bitop changes

---

std/experimental/ndslice/package.d

See also #3921 - _Fix Issue 15553 - topN very inefficient [slower than sort, even for topN(0)] but should be O(n)_
______
- 3x3 blocks: the new `topN` 90% faster than old `topN` and 10% slower than `sort`
- 7x7 blocks: the new `topN` 110% faster than old `topN` and 10% faster than `sort`

Replace sort with topN in ndslice example

---

std/getopt.d

Remove use of exit() in std.getopt example

---

std/algorithm/iteration.d

The two most common things that I hear when introducing D to people are
* "Is `writeln` actually a property of `string`!?" (misunderstanding of UFCS)
* "Does D really use strings instead of lambdas?"
Nothing much can be done for the first one, idiosyncrasies are part of learning a new language. But the second one is mostly because the docs use string predicates more than lambdas. String predicates are bad practice compared to lambdas IMO and should be discouraged by not including them in docs. Yes, there are legitimate uses of string predicates, but 99% of the time, you should use lambdas.

Removed string predicates from std.algorithm.iteration documentation

---

std/algorithm/sorting.d

I was surprised that building and sorting the heap call percolate which in turn has two stages - going up and going down. To the best of my knowledge, all you need to do to build a heap is to sift elements down (not up). @Xinok could you please comment?

Faster heap operations

---

std/algorithm/searching.d

Adds overload that enables calling `startsWith` and `endsWith` with only a `haystack` and predicate `pred`.
See discussion at: http://forum.dlang.org/post/zobvqdmxnjnilqibtcph@forum.dlang.org
Should `RandomAccess` have special treatment via `.length` and `opIndex` or should we just use `.empty` and `.front` for every case?
If not I guess we could just do
```D
{
return !haystack.empty && haystack.front.unaryFun!pred
}
```
right?

Add Unary Overload of startsWith() and endsWith()

---

std/datetime.d

MS recently added it with https://support.microsoft.com/en-us/kb/3093503

[Windows] std.datetime: Add North Korean timezone

---

std/typecons.d

Per [Andrei's comments](https://forum.dlang.org/post/n7rbm7$2s20$1@digitalmars.com). We might also consider explaining why an alias is a bad idea (I haven't quite figured it out myself).

Remove suggestion in documentation to add an alias to uses of Flag

---

std/datetime.d

It's proven to be a maintenance problem to maintain the time zone
conversions between the IANA TZ database names and the Windows time zone
names in std.datetime. So, rather than compiling them in, this provides
a way to get them at runtime (which will also make it so in the future,
older releases can work properly on up-to-date Windows boxes, which is
not the case currently with regards to time zone conversions). The
current conversion functions can be deprecated after parseTZConversions
has been out for a release (so that it's possible for users to compile
their code for two releases in a row without getting deprecation
messages).

Fix for issue# 15376. Get time zone conversions at runtime.

---

changelog.dd
std/bitmanip.d

- keep ptr and len as deprecated (unsafe) properties

fixup for #3822

---

std/experimental/allocator/package.d

Objs should be deallocated by the same allocator used to allocate them.

Fix a typo in stack allocator usage example

---

std/math.d

This fixes a small mistake I made in [#3888](https://github.com/D-Programming-Language/phobos/pull/3888).

Don't use selective import in std.math due to DMD issue 314.

---

std/algorithm/searching.d

Rationale: it's not immediately obvious what the order of arguments passed to the predicate is (is it haystack item first, or needle first?).
Also, the "obvious" call:
````
haystack.canFind!startsWith(needle)
````
as well as the simpler call
````
haystack.canFind!((a,b) => a.startsWith(b))(needle)
````
actually do not compile, because the current compiler's template inference doesn't seem to be able to deduce the right types. The full incantation, including specifying `string` types, appears to be necessary to make it work. This would be far from obvious to a newbie, and thus justifies explicit documentation.

Add example of how to use a custom predicate with canFind.

---

changelog.dd
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/gc_allocator.d

GC always allocates from bins, and has very well-defined behavior here. So goodAllocSize can be implemented quite easily.
Rules:
1. If allocation size < 16, allocate 16 bytes
2. For allocations of 16 to 8192, use the power of 2 size that will hold it.
3. For allocations greater than 8192, use the multiple of 4096 that will hold it.
I had to change some other unit tests because of the assumptions made for the default implementation of `IAllocator.goodAllocSize`

Add goodAllocationSize to GCAllocator

---

std/file.d

The target path is actually relative to the link, not to the current
working directory. This is in line with the ln shell command, so changing
the documentation to match the behavior seems in order.
Also changing some wording, and un-highlighting "symlink" throughout as
it never refers to the function.

fix documentation for symlink

---

std/file.d

Letting attribute inference take care of things. Making a unittest @safe
to ensure that setTimes itself doesn't do anything unsafe.

remove @safe from template setTimes

---

std/experimental/allocator/common.d
std/experimental/allocator/mallocator.d

Also made the attribute style more consistent, because it was all over the place throughout the package.
I looked at the [Phobos styleguide](https://dlang.org/dstyle.html), but I couldn't find anything about this, so I decided to follow the soft limit of 80 chars per line. That's why I put the attributes on their own line.
Overall the scheme is something like this:
```
[@safe] [@nogc] [nothrow] [pure]
[protection-level] [extern] <function-name / unittest>[params] [shared]
```
Let me know if there is an existing style that I need to follow. I only care about adding correct attributes on the functions, not about bikeshedding about the code style.

Add attributes to most functions in allocator.mallocator and allocator.common.

---

std/net/curl.d

The upload function needs std.stdio.File, but the import is missing.

Add missing import

---

std/concurrency.d

The previous behavior generated a string that was different for every copy of the same Tid. With this change it outputs the address of the unique MessageBox instance instead.

Fix Tid.toString().

---

changelog.dd

Removing old entries, fixing a link.

Cleanup changelog

---

std/utf.d

`std.utf.toUTF8()` violates memory safety when fed an invalid `dchar` value, causing segfaults or other wrong behaviour: https://issues.dlang.org/show_bug.cgi?id=15586
While this PR is technically independent, the related DMD issue (https://issues.dlang.org/show_bug.cgi?id=15585) really ought to be fixed at the same time. PR here: https://github.com/D-Programming-Language/dmd/pull/5229

Fix Phobos Issue 15586

---

std/typecons.d

Fix #12914: std.typecons.alignForSize will not accept immutable names argument

---

std/internal/digest/sha_SSSE3.d
std/process.d
std/zip.d

Changing the language so that local imports no longer 'shadow' other symbols revealed some problems in Phobos, which this addresses.

fix problems that prevent implementing import shadowing protection

---

std/format.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=15663

Fix issue 15663: format("%#o", 0) should be "0" not "00".

---

std/algorithm/sorting.d

Rework of #3831 based on [Andrei's wording in the forum](http://forum.dlang.org/post/n6govh$1643$1@digitalmars.com).
Also added a reference in the docs for `sort` so that people who don't already know about `schwartzSort` can actually find it other than by accident.

Improve schwartzSort documentation.

---

std/string.d

The test assumed that the unit test runner would be executed from
the Phobos root directory, which is neither specified anywhere,
nor the case for the LDC build system.

lineSplitter: Remove gratuitous filesystem access from unit test

---

std/string.d
std/uni.d

Many of the functions for which this wrapper is used return
string ranges. Comparing these for object identity does not
make a lot of sense.
This is actually an issue, because toUTF, which is used in quite
a few of the tested functions, contains a void-initialized buffer,
so the identity comparison is not guaranteed to succeed. The tests
just so happen to pass on current DMD regardless, but this is not
the case for an optimized LDC build.

Fix testAliasedString() unit test helper

---

std/experimental/allocator/package.d

All other overloads modify their parameter, this one doesn't.

Fix Issue 15677. Take array by ref for expandArray with init

---

std/uni.d

https://issues.dlang.org/show_bug.cgi?id=15686
No actual code changes. Just moving one overload of toLower next to the
other one.

fix issue 15686 - std.uni overloads documentation

---

std/meta.d

This should help eliminate a lot of tiny helper templates, including those that tend to be visible in template constraints despite not being documented anywhere.
Ping @Dicebot, @John-Colvin in case there's something about std.meta I should know about before adding new functionality to it.

Add std.meta.applyLeft and std.meta.applyRight

---

std/process.d

Current document says:
```d
auto p = pipe();
p.writeEnd.writeln("Hello World");
assert (p.readEnd.readln().chomp() == "Hello World");
```
This means that the buffer of `p.writeEnd` is yet to be flushed.
Therefore `p.readEnd.readln` can't recieve the input, for readln waits forever if the buffer is not flushed.
Then I fixed as follows:
```d
auto p = pipe();
p.writeEnd.writeln("Hello World");
p.writeEnd.flush();
assert (p.readEnd.readln().chomp() == "Hello World");
```

Fix Document of process.d with pipe

---

std/getopt.d

related issues:
- https://issues.dlang.org/show_bug.cgi?id=10956
- https://issues.dlang.org/show_bug.cgi?id=10955
In short, this PR proposes a way to statically check  the variadic options in getOpt (it detects invalid pattern such as two consecutive recipients). The problem is that it uses `pragma(msg)` to output the diagnostic, but `pragma(msg)` is never used in phobos (so far). 
The constraint works fine but maybe you'll be able to find and suggest a better way to output the diagnostic without losing the line of the error (for example with `assert(0)` the error origin is lost).

Static verification of std.getopt arguments with more helpful error messages

---

changelog.dd
std/net/curl.d

Added use of `Appender` instead of plain `~=`. And call `reserve` on receive of "content-length" header.
It makes `get` slightly (50-200ms) faster for large files. Still quite [slower][0] than vibe.d's API.
[0]: http://forum.dlang.org/post/pwfstlnodtstqojcxlyz@forum.dlang.org

std.net.curl: _basicHTTP: use Appender

---

std/meta.d

`Alias` is super-useful and has been copied/pasted from phobos source or reimplemented by many people independently, there's even an article about it. Time to make it public.
`Alias!int` used to evaluate equivalent to `AliasSeq!int`. This pull changes it to evaluate to `int` and refuse multiple arguments.
Thought process:
If you want to grab an arbitrary number of things, whatever they are, and use one name for them with  indexing and auto-expansion, use `AliasSeq`. If you want to alias a single thing, whatever it is, use `Alias`.

make std.meta.Alias public and orthogonal to std.meta.AliasSeq

---

std/conv.d

Link: https://issues.dlang.org/show_bug.cgi?id=15695
The problem is that the parsing code advances the incoming range too eagerly, so that by the time the error message is constructed, the range has already advanced past the invalid character. Rewrote the code to only advance the range after it's sure that the character is valid.
Also, took the opportunity to fix some misleading comments and minor code issues leftover from who knows when.

Issue 15695: wrong error message in failed conversion from string to int

---

changelog.dd
std/meta.d

This template `Repeat` is an easy way to make an `AliasSeq`. For example, `Repeat!(3, real)` is equal to `AliasSeq!(real, real, real)`.

Introduce std.meta.Repeat

---

std/format.d
std/stdio.d

I'm doing this on 2 modules that came up first.
1. I don't want to do all of them, because it's a lot of mindless busy work, and if the way I'm doing it isn't acceptable, don't want to waste time.
2. I followed these 2 rules:
a. In cases where we are selectively importing, and names wouldn't conflict, remove the FQN (not necessary anyway)
b. In cases where the FQN is required (e.g. using std.file.write in std.stdio, where write is also defined), change import to static.
I found one case where a symbol was being used without being imported. So this new system is definitely finding legitimate bugs.
If this is acceptable, I'll work on the other deprecation messages.

Fix import issues for std.format and std.stdio to remove deprecation messages

---

std/algorithm/comparison.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/complex.d
std/container/slist.d
std/conv.d
std/cstream.d
std/datetime.d
std/file.d
std/net/curl.d
std/parallelism.d
std/range/package.d
std/range/primitives.d
std/regex/package.d
std/socket.d
std/string.d
std/uni.d

See https://github.com/D-Programming-Language/phobos/pull/4015
This is the rest of them.
There are some places where it's not 100% clear whether the right call is a static import or a selective import.
This should be merged fairly quickly, because it touches a lot of files, the risk of this becoming conflicting is pretty high.

Fix remaining import deprecation messages

---

std/internal/test/dummyrange.d

* fixating the current DummyRange behaviour in a unittest.
* structured the tests a little
* DummyRange with custom types
* DummyRange line coverage from < 10% to 100%
* DummyRange and AllDummyRanges bahaviour have unchanged interface and semantics

Make DummyRange work this types other than uint

---

std/datetime.d
std/experimental/allocator/building_blocks/stats_collector.d
std/file.d
std/format.d
std/process.d
std/socket.d

Merge [fixes](https://gist.github.com/joakim-noah/5d399fdcd5e484d6aaa2) from [latest Android work](https://gist.github.com/joakim-noah/5c03801fa6c59b1e90df), comments and explanations provided inline.  The version of this PR from the first link was the first to get all tests passing on Android/x86 a couple months ago, with phobos from git master.
There are two additional workarounds I found for prior Android versions, but didn't include here:
* [Bionic up till Android 4.1 didn't support calling `getcwd` with null and 0 arguments](https://github.com/android/platform_bionic/commit/04a83a48ed89f433c78e31106ed50059764797a0), so [I allocated a static array and passed it in](https://gist.github.com/joakim-noah/5c03801fa6c59b1e90df#file-phobos_ldc_arm-L375).  However, [the share of 4.1 and older …

Android update

---

std/algorithm/iteration.d

Followup to PR #4000 ([issue 15683](https://issues.dlang.org/show_bug.cgi?id=15683)).
There are a few more missing escapes and a typo in the ddoc for `std.algorithm.iteration.cache`.

[doc only] Improve ddoc for std.algorithm.iteration.cache

---

std/bigint.d

Fixes: https://issues.dlang.org/show_bug.cgi?id=15678

Issue 15678: BigInt("") should not break array bounds

---

std/random.d

While it would definitely be nice to deliver on this idea, better not to mention it until we have an actual implementation lined up and approved.
Requested in forum discussion: http://forum.dlang.org/thread/nandht$1dnj$1@digitalmars.com

Remove ddoc references to 'second-generation std.random'

---

std/json.d

This request fixes the [issue 15742](https://issues.dlang.org/show_bug.cgi?id=15742) by using `out` parameter instead of pointer parameter for `parseValue`.
Related: [issue 15741](https://issues.dlang.org/show_bug.cgi?id=15741).

Make parseJSON CTFEable for object of object and array of array

---

std/container/dlist.d

Like #4039 - here's an example for the documentation for DList.

add documentation example for DList

---

std/container/slist.d

As a follow-up to #4038 (my confusion that SList isn't an InputRange).
Here's an example that might help newcomers to gain a better understanding of SList.
The documentation on containers is still pretty sparse, but let's go step by step ;-)

add documentation example for SList

---

std/datetime.d

std.datetime - bring plaintext examples back in sync with tests

---

std/digest/md.d
std/digest/ripemd.d

Fix big endian version of std.digest.md and std.digest.ripemd.

---

std/stdio.d

https://issues.dlang.org/show_bug.cgi?id=15377

fix Issue 15377 - std.stdio: Use MSVCRT's _fseeki64 / _ftelli64 on Windows COFF

---

std/zlib.d

I thought it might be nice to show the two main use cases for zlib. 
Currently [the page](http://dlang.org/phobos/std_zlib.html) contains no code examples: 
The first example is copied from the unittest. The second one I created myself - I hope it is according to idiomatic D ;-)
I also added the magic `///` to the adler unit test - seemed like an example doesn't hurt.

std.zlib: add documentation header example

---

std/random.d

See first example in the docs for the std.random [1]. Ordinary parenthesis character should be used, not $(RPAREN).
[1] http://dlang.org/phobos-prerelease/std_random.html

Use proper right parenthesis in example's comment: "$(RPAREN)" -> ")".

---

std/regex/internal/thompson.d

Roughly 10-15% faster on a few common patterns.
15 minutes with profiler are worth few days of puzzling.
In short - quickTest scans bytecode forward to see if there is something matching current symbol ahead. This trades extra switching on bytecode for avoding to create a new state. It makes sense in backtracking engine to avoid pushing too much on stack. For thompson VM this just adds a extra work since we are going to recheck that same bytecode anyway.

2 minor tweaks to std.regex default engine

---

posix.mak

- restrict any test to 60s
- don't trigger the 1h timeout for the auto-tester
- get a make error message w/ a specific test on timeout failure
- the timelimit program is used b/c the auto-tester already relies on it
See also https://github.com/D-Programming-Language/druntime/pull/1503

 use timelimit to kill deadlocked tests

---

std/algorithm/setops.d

Separated from #4044 as this might be a controversial edit.
This is part of my move to put more examples into unittests and here I put a modified version of the docstring after the example.
For the first example I preferred  to show code instead of showing that how to generate the largestPartialIntersection with more than one item - I think this is nice, because it shows that the highest is the last element of the array and that one really has to duplicate the array to avoid it being emptied.

convert docstring examples to unittests [setops]

---

std/functional.d
std/net/isemail.d
std/traits.d

in reference to #4042 more converted examples.

convert docstring examples to unittests [part 2]

---

std/datetime.d

This fixes two issues:
* [issue# 15655](https://issues.dlang.org/show_bug.cgi?id=15655): H, H:MM, H:M, and HH:M (with either + or - in front) were incorrectly accepted as valid time zone strings by SysTime.from*String, when ISO 9601 requires HH or HH:MM (with either + or - in front). There also was no proper verification that the minutes were less than an hour.
* [issue# 15654](https://issues.dlang.org/show_bug.cgi?id=15654): SysTime.toISOString output the time zone in the extended format - HH:MM - rather than the non-extended format - HHMM. This fixes that.
Unfortunately, the fix for 15655 does risk breaking code for anyone accepting strings from elsewhere which didn't follow the ISO standard properly, but I don't know how to avoid that, and as long as the other sources for an ISO string …

Fix compliance issues with SysTime.to*String and SysTime.from*String.

---

std/stdio.d

Fixes doc to match code and test.

std.stdio: Fix documentation of File.error

---

std/experimental/allocator/gc_allocator.d

A few notes here:
1. I changed from `@trusted` to `@system`. I have no idea how this should possibly have been `@trusted`, and the new version is even less so.
2. This assumes that expand can use up more of the current block. If this isn't supposed to be the case, let's discuss. Since `allocate` is supposed to return the *exact* data requested, expand would be near useless if it can't expand into the current memory block.
I think this may fix the Win32 error, I re-enabled it just in case. I don't know what the original problem was, but expand certainly wasn't implemented correctly.

Fix GCAllocator.expand to properly utilize GC.extend

---

std/digest/md.d
std/digest/ripemd.d

The current import for version(BigEndian) is still wrong.
This finally fixes the import.

Linux/PPC: Really fix the import for md.d/ripemd.d.

---

std/experimental/allocator/building_blocks/region.d

This should cover most architectures which D supports.

Allocator: Add stack direction for a lot of non-Intel architectures.

---

std/range/package.d

this is a follow-up to the discussions from the [forum](http://forum.dlang.org/post/qypadwjlzpktuqawbsza@forum.dlang.org)
1) I tried to add an explanation for the differences 
2) I removed the `foreach` example for `zip` - this is too confusing!
3) I had to add the remaining `zip` unittest in the documentation as otherwise the order with See_Also would be messed up :S

std.range: explain difference between lockstep and zip

---

std/math.d

https://issues.dlang.org/show_bug.cgi?id=6343
Added a new function to std.math `nextPow2`. The code here is adapted from the DDMD function, which is why it is different than the suggested code in the bug report. Also, this code is safe, as well as 11% faster.
ping @9il, you asked me to notify you when I made a math PR.

Added nextPow2 and truncPow2

---

std/experimental/allocator/package.d

revert the changes made in #4023 because they are more deeply fixed in #4057. However keep unittest to verify that 15639 is still well fixed.

fix redundant static checking, keep the deeper one from 15772

---

std/container/rbtree.d

In reference to #4039 and #4040 also an example for Red Black Trees.

add documentation example for RBTree

---

std/experimental/allocator/building_blocks/bitmapped_block.d
win64.mak

Unittests for std.experimental.allocator were never built with win64.mak. Enabling these triggers
```
testAllocator failed for BitmappedBlock!(1u, 1u, NullAllocator)
core.exception.AssertError@std\experimental\allocator\building_blocks\bitmapped_
block.d(158): Data must be aligned properly
```
for win32mscoff builds.

enable and fix tests of std.experimental.allocator for Win64/Win32mscoff

---

std/meta.d

They return general templates, not values.
Added in #3798, which has not been released yet.

meta: CamelCase apply{Left, Right}

---

std/internal/cstring.d
std/signals.d
std/string.d
std/uuid.d

Inspired by #4039 I propose to go through all old modules and replace the examples in docstring with checked unittests.
The advantage is quite clear - it is possible to verify that the documentation is correct and up-to-date.
A quick regex yielded that there a 55 files affected:
```
107 ./datetime.d
45 ./xml.d
40 ./net/curl.d
25 ./experimental/logger/core.d
16 ./stdio.d
11 ./file.d
10 ./socket.d
10 ./parallelism.d
9 ./exception.d
7 ./regex/package.d
7 ./range/package.d
7 ./process.d
6 ./net/isemail.d
6 ./base64.d
5 ./uni.d
5 ./random.d
5 ./functional.d
5 ./concurrency.d
4 ./windows/registry.d
4 ./traits.d
4 ./conv.d
3 ./typecons.d
3 ./path.d
3 ./internal/scopebuffer.d
3 ./experimental/allocator/typed.d
3 ./encoding.d
3 ./digest/ripemd.d
3 ./digest/digest.d
2 ./zip.d
2 ./format.d
2 …
```

convert docstring examples to unittests

---

std/stdio.d

Hey I came by `std.stdio` and saw that you don't show the unittest examples for `rawRead`, `rawText`, ... even though they are quite nice.
Moreover I removed `static` from the import as those unittests will now be displayed to the users.
I also saw that the unittest for `byRecord` is in comments for no (commented) reason. Anyone remembers this?
[Git blame](https://github.com/D-Programming-Language/phobos/commit/9e4e3cbe88937d2ffa052de90a5d133cd672ea09#diff-7945921c543e1ab7460797aeb759d7c5L1825) goes to @andralex 
I know it was 7 years ago, but do you by chance have any memories?

std.stdio: add unittest examples to doc output

---

changelog.dd

follow-up to #4041 - maybe it's a good idea to document the addition?
ping @schveiguy 
Btw I don't know why there are two "Library changes" sections - is this by design or a bug?

update changelog: range support for the convenience wrapper redBlackTree

---

std/algorithm/iteration.d

@MartinNowak and @CyberShadow identified a regression with respect to support in `std.algorithm.iteration.map` for cross-module overload sets. This turned out to be caused by [DMD issue #15777](https://issues.dlang.org/show_bug.cgi?id=15777), but for now @CyberShadow has suggested a workaround for `map()`, specifically.
This PR also fleshes out the `unittest` for [Phobos issue #15480](https://issues.dlang.org/show_bug.cgi?id=15480) added by my [previous PR](https://github.com/D-Programming-Language/phobos/pull/3969), again as requested by @CyberShadow .

Fixup for PR#3969

---

std/datetime.d

All regression fix PRs based on stable branch are blocked by the red in Phobos unittest.

Cherry-pick #3945 to stable branch - [Windows] std.datetime: Add North Korean timezone

---

std/file.d

As verified by the unittest below.

std.file: Clarify documentation of mkdirRecurse when target exists

---

std/algorithm/sorting.d

in reference to the reverted #4025, here the two small bug fixes
- fix for zero length random access ranges
- `save` the forward range before iterating through it

std.algorithm.sorting: fix save reference in isSorted

---

std/internal/math/errorfunction.d
std/math.d

This is a mod that allows std.internal.math.errorfunction unittest to pass on several other platforms.
For some platforms, math on a NaN may change the sign.  Replaced with test that ignores signbit for NaN.
Is this the appropriate?  We are discussing it here: ldc-developers/phobos#25.

Fix NaN payload unittest in errorfunction

---

std/range/package.d

https://issues.dlang.org/show_bug.cgi?id=13409
~~Added the new function `padLeft` to `std.range`. Separated `padLeft` and `padRight` into separate PRs.~~

[Issue 13409] std.range.padLeft/Right

---

std/file.d

`DirEntry` got a member function named `isFile`. So the function tried to call this one instead of the other global `isFile()` overload.

fix issue 15658 - UFCS used in isFile caused a conflict with a DirEntry member

---

std/bitmanip.d

The warning is pure FUD. Any GC implementation in D must recognize interior pointers, so will recognize tagged pointers.

Remove FUD warning

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/package.d
std/experimental/ndslice/slice.d

https://github.com/DlangScience/mir/pull/9

[ndslice] Math Index Order

---

std/process.d

Because it's unnecessary to restrict it to immutable ones.

browse() should take const(char)[] parameter

---

std/regex/internal/backtracking.d
std/regex/internal/generator.d
std/regex/internal/ir.d
std/regex/internal/parser.d
std/regex/internal/thompson.d

Make use of bloom filter on dchar to predict if we should take the
out of loop branch. Fairly unique trick for regexes far as I know.
This greatly helps backtracking engine that relied on dubious concept of
"quick test" which is scanning bytecode to see if lookahead will match it.
It was a poor trade-off between spending time executing that bytecode 
essentially twice and pushing/poping extra state on the stack.

[std.regex] Introduce filtered loops with bloom filters

---

std/file.d
std/stdio.d

https://d.puremagic.com/issues/show_bug.cgi?id=12368

fix Issue 12368 - std.file.write conflicts with std.stdio.write

---

std/stdio.d

follow-up to #4075 / #4053 - this PR just adds documentation for `byRecord` (as suggested by @ntrel)

document std.stdio.byRecord

---

std/concurrency.d

Within Phobos, this appears to be the only occurrence of synchronizing on an immutable object. Removal of this deprecated function allows us to resolve Issue 14251. The removal is needed for DMD PR https://github.com/D-Programming-Language/dmd/pull/5564 .
Ping @yebblies and @MartinNowak because you have marked this method as deprecated.

Remove deprecated `std.concurrency.MessageBox.isClosed() const`.

---

std/regex/internal/backtracking.d
std/regex/internal/ir.d
std/regex/internal/parser.d
std/regex/internal/thompson.d

Profiler strikes back, most of the time was actually spent inside of lookup tables.

[std.regex] Faster tables for ASCII case

---

std/algorithm/package.d

AFAIK brackets for one argument were long a limitation of the compiler. While this doesn't hurt in the code base, it might be a nice idea to update the documentation, so that future code/users know about this feature ;-)

Suggest bracket-free template syntax in the doc of std.algorithm

---

std/math.d

This change "fixes"/works-around a unittest failure with LDC with optimizations on. Note that the return type of `impl` is `real` (not `Float`) and thus changing the type of `sign` to `real` should not matter / be more correct?

std.math.pow: change type from `double` to `real` for internal variable.

---

std/typecons.d

@DmitryOlshansky @quickfur 
Slightly tweaked version of https://github.com/D-Programming-Language/phobos/pull/3016. This one doesn't static assert that std.algorithm.move fails to compile (it does compile).
Fix note about moving a class instance.
Show automatic destruction of `scoped` result.
Show how `scoped` can lead to invalid class references.
Show move(typeof(scoped!A)) is wrong.
Show scoped member variable initialization.

Improve docs for `std.typecons.scoped`

---

CONTRIBUTING.md

In reference to #4128, I propose to add a link to the new contribution guide.
It also fixes the typo of Styleguide and adds a link to the IRC channel.

Link from CONTRIBUTING.md to the new wiki contribution guide

---

std/bigint.d
std/internal/math/biguintcore.d

Second part of fix to: https://issues.dlang.org/show_bug.cgi?id=14503

Issue 14503: Implement formatting BigInt in octal

---

std/math.d

* The SoftFloat floating point emulation doesn't support the IEEE flags.
* The unittest isn't `@safe` (taking address of a local variable + pointer cast)
Ping @kinke @redstar does LDC support the IEEE flags with floating point emulation?

Small std.math fixes for ARM

---

posix.mak
std/experimental/typecons.d
win32.mak
win64.mak

This implements the ability to wrap a structure into a specified interface using std.typecons.wrap. Some notes:
Bug is not an issue in HEAD.
-During these changes I came across this bug: https://issues.dlang.org/show_bug.cgi?id=12993-
When the struct is unable to be unwrapped I have thrown a ConvException. I considered using Nullable but think I was hitting issue 12993; another option would be to allow the user to specify the unwrap type to be Nullable!T.
I have pulled some logic into the isConceptWith template, which is private for now but may be something we'd want to be public and renamed?
I also added a constraint to wrap which verifies that Targets are all interfaces, which required a private template isInterface to be added.
https://issues.dlang.org/show_bug.cgi?id=14098

Wrap struct

---

std/math.d

Uses the same code as FreeBSD.

Solaris: Add inline assembly version of poly().

---

std/json.d

As shown in the discussion in [Issue 4037](https://github.com/D-Programming-Language/phobos/pull/4037), the combination of `ref` parameter and void initializer is potentially fragile for future changes in `JSONValue` in the sense of memory `safe`-ty.
This request replaces `out` parameter with `ref` parameter of the nested function in `parseJSON`.
It will not change the behavior of the function and CTFEability.

Using `ref` instead of `out` for std.json.parseJSON

---

std/uni.d

When testing the old version vs this version on `dchar a = '7';`, I got the following results for 1 million calls:
```
isNumber		85 ms, 914 μs, and 3 hnsecs
isNumber2		4 ms and 368 μs
```

std.uni.isNumber: significant performance increase for ASCII

---

std/path.d

Even though it's spelled out in black on white, people still get this wrong:
http://forum.dlang.org/post/rkanltnlqavcgxlvhzrb@forum.dlang.org
Perhaps making it bold and a paragraph of its own will help.

std.path: Emphasize that isValidPath does not check existence

---

changelog.dd
std/process.d

The current Posix implementation of spawnProcess calls close on every fd from 3 to the max fd count (as gathered by `rlimit()`). Given that the process doesn't have that many descriptors open
in the *vast* majority of cases, this is quite pessimal.
Instead, check `/proc/self/fd` to see which descriptors are actually open, and close those.
A similar solution is probably possible for BSD and friends.

Avoid brute force fd close() on Linux

---

std/json.d

A number of methods are marked @safe because they do not do anything in themselves that could pose memory issues, but they affect internal state that could, if incorrectly set, cause the @trusted methods to produce memory errors. I'm not sure if it's best to make those @trusted as well to indicate to future programmers that caution is required to avoid memory errors.
The general strategy was to make the basic accessors @safe or @trusted and refactor everything to use those rather than to access the `Store` union directly. This works pretty well but occasionally can cause extra validation. For the most part, I removed that by removing extra validation that most public methods perform. For `opEquals`, I made the method @trusted instead. In some places, I used a temporary variable instead. …

Make std.json @safe.

---

std/traits.d

This handles case where there are no specific UDAs in a struct.

Fix Issue 15874 - getSymbolsByUDA fails if struct has no UDAs

---

std/algorithm/mutation.d
std/algorithm/sorting.d
std/container/binaryheap.d
std/random.d

Hey I have seen that `swapAt` is used quite often even though it's undocumented.
In phobos `swapAt` is used 19 times in other modules and [other people](https://github.com/DlangScience/mir/pull/29) seem to know about it too.
Imho it looks nicer to write `myArray.swapAt(0, i)` than `swap(myArray[0], myArray[i])`.
I couldn't find a unittest for the  `else` in the `static if` - maybe @quickfur?
If you don't like to expose `swapAt` I would suggest we remove it entirely from Phobos.
```
algorithm/sorting.d:            swapAt(r, 0, len - 1);
algorithm/sorting.d:            swapAt(r, 0, mid);
algorithm/sorting.d:            swapAt(r, mid, len - 1);
algorithm/sorting.d:            swapAt(r, 0, mid);
algorithm/sorting.d:            swapAt(r, mid, len - 1);
algorithm/sorting.d:            swapAt(r, …
```

document std.algorithm.mutation: swapAt

---

std/regex/internal/backtracking.d

By inlining a couple of functions on a critical path. This combines and builds on top of all other improvement pulls.

[std.regex] Even faster C-T regex

---

std/meta.d
std/traits.d

As discussed in https://issues.dlang.org/show_bug.cgi?id=14561, this pull makes EnumMembers use divide-and-conquer (through staticMap), and adds to NoDuplicates support for lists longer than 500 elements.

Fix 14561 - Large enums cannot be parsed due to too many recursive template expansions

---

changelog.dd

bed2df7e804005830e14d323f31fc1ed09c0a3bf doesn't seem to have made 2.071.0 (see the online changelog, source snapshots, `git rev-list v2.071.0`, etc.).

Get std.process change back into changelog

---

std/json.d

This new option allows a better interoperability with software made in other languages and that are not able to read string values containing non-ASCII characters.
- no breakage
- no additional code (excepted a test) because the encoder already existed for unicode ctrl chars

fix issue 12897 - toJSON, add the escapeNonAsciiChars option

---

win32.mak
win64.mak

1. A new experimental module `std.experimental.typecons` is added, but its ddoc generation is not supported in win32.mak.
2. `std.range.*` modules unittests are not actually tested under win32 and 64, because their object file has been overwritten by the output of `std.experimental.ndslice.*`.

Fix two bugs in win32/64mak files

---

std/encoding.d

I need this for my date string parsing library.

Add Informative Example to canEncode

---

changelog.dd
std/regex/internal/parser.d
std/regex/internal/tests.d
std/regex/package.d

Adds hackish comment syntax that's supported by a lot of regex engines.

Fix issue 12367 - std.regex: Recognize (?# ... ) comment syntax

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/slice.d

Description:
Slices accept static array type of `size_t[N]` as multidimensional index. So this PR fix it for cases like `slice[[1, 2, 3]]`, so it allows automatic type conversion for `[1, 2, 3]` to type `size_t[3]`.

fix Issue 15872

---

std/concurrency.d

Related #3516.
This assert was introduced in #1910, which contradicts #1279.

std.concurrency: receiveTimeout: allow negative timeout

---

std/algorithm/iteration.d

The current examples are pretty hard to follow. What I think happened is someone created some tests that were never meant to be examples, and then sometime later someone added the ddoc comment on it.
My version uses UFCS and reorganizes everything to be much friendlier.

Cleaned up std.algorithm.joiner's examples

---

std/algorithm/iteration.d
std/range/package.d

Using an iterative approach instead of recursive. When I originally wrote this I recorded an order-of-magnitude speedup on arrays and approx. 2x on more complicated ranges.

faster pairwise summation

---

std/datetime.d

This should fix the autotester.
https://support.microsoft.com/en-us/kb/3148851
http://forum.dlang.org/post/570E94F7.1040200@puremagic.com

std.datetime: Update Windows time zones for KB3148851

---

std/regex/internal/backtracking.d
std/regex/internal/ir.d
std/regex/internal/parser.d
std/regex/internal/thompson.d
std/regex/package.d

A long awaited feature is in. The helpers for matchFirst/matchAll etc. are not provided but regex can now be constructed with a array of patterns more or less following the API outlined.

Fix issue 12227 - Allow matching multiple patterns in one go with std.regex

---

std/regex/internal/parser.d
std/regex/internal/tests.d

<del>This was marked as blocked for release, no idea why it was shipped anyway.</del>
EDIT: This simply a bugfix for current master

Fix issue 15864 - chmgen triggers exception in std.regex

---

std/json.d

This fix will now encode all string types, mutable and immutble, as JSON strings:
```d
wchar[] wstr = "a"w.dup;
JSONValue testValw = wstr;
assert(testValw.type == JSON_TYPE.STRING);
```
https://issues.dlang.org/show_bug.cgi?id=15884

Fix issue 15884 Encode wstring/wchar[]/dstring/dchar[] as JSON string

---

std/socket.d

Remove abuse of `@trusted` in template function `getAddressInfo` that cannot guarantee that the incoming type argument `T` is actually `@safe`. Localize `@trusted` to the single call to `getAddressInfoImpl`, so that any `@system` code in `T` will be caught by the type system.
Add unittest to ensure such examples of `T` will be rejected at compile-time.
Mark normal unittest for `getAddressInfo` as `@safe` to ensure that the function body itself does not introduce any non-`@safe` code.
The rest of this module has frightening amounts of `@trusted` functions, which need to be properly vetted (and probably the scope of `@trusted` reduced), but let's leave that for another battle.

Fix issue 14137: std.socket.getAddressInfo breaks @safe

---

std/range/primitives.d

* Show that range length/topology doesn't change calling `moveFront`.
* Use `enum` instead of `@property` for better readability. The property case is still covered in an undocumented unittest and for `moveBack`.

[trivial] Tweak moveFront example

---

changelog.dd

Also remove nextPow2 entry, it was added in previous release.

Changelog for std.regex

---

changelog.dd

See #4167 and #4127 for the merged PRs.

changelog update: swapAt, moveAt, iota.length

---

std/ascii.d

There should never be a time where this isn't inline-able.

Force Inlining of isASCII

---

std/random.d

AFAIK was D1 EOL in 2010, so maybe it's time to remove that message.
However the tip is still useful - so why not put it into the examples?

std.random: remove upgrading from D1 notice

---

std/algorithm/sorting.d

I just realized that there is `release` for a SortedRange  that returns the original array.
I think we should document that better (I was looked for it one month ago without success), thus I propose to make parts of the `sort` doc look nicer ;-)

std.algorithm.sort docu: use release to get the source back

---

std/datetime.d
std/file.d

https://issues.dlang.org/show_bug.cgi?id=15803
~~Needs https://github.com/D-Programming-Language/druntime/pull/1513~~

fix Issue 15803 - std.file should support sub-second file time precision on POSIX

---

std/algorithm/iteration.d

https://issues.dlang.org/show_bug.cgi?id=15735

Fix issue 15735

---

std/conv.d
std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/common.d
std/experimental/allocator/package.d

This PR is the first step toward implementing an idea by @Dicebot: use the allocator for storing metadata about objects (in particular reference counts).
An `AffixAllocator` offers systematic metadata storage before/after an allocation. Even if that allocation is later used to store `immutable` data, the allocator is able to return the affix as `shared` without violating the type system.
If data is unqualified/mutable, there is no burden of proof needed at all - just return the mutable affix.

Allow affix access from qualified data

---

std/regex/internal/parser.d
std/regex/package.d

This should aid readability and reduce the obscurity of the parser.
Also potentially non-generating parser is possible reusing the same code.

[std.regex] Split code generation and parsing, almost completely.

---

std/regex/package.d

Should improve cases where a lot of temporary captures allocated with big number of submatches.

[std.regex] Use ref-counting for Captures struct

---

index.d

Eh, this is the missing element that ties https://github.com/dlang/dmd/pull/5344 and https://github.com/dlang/dlang.org/pull/1282 together.

DDOC_BLANKLINE

---

std/range/package.d

This fixes https://issues.dlang.org/show_bug.cgi?id=15860 by adding opApplyReverse to Lockstep.

Fix Issue 15860 - lockstep should support foreach_reverse

---

changelog.dd
std/file.d

Removing @safe from the signatures so that attribute inference takes
care of things. There are @safe unittests already, ensuring that the
functions themselves don't do anything unsafe.
Replacing @trusted declarations with @trusted function literals. This
way it's more clear that the specific call is @trusted, not the called
function.

rangify readLink and symlink

---

etc/c/odbc/sqlext.d
etc/c/odbc/sqltypes.d
std/c/process.d
std/concurrency.d
std/datetime.d
std/getopt.d
std/internal/math/biguintcore.d
std/internal/math/biguintnoasm.d
std/internal/test/dummyrange.d
std/math.d
std/meta.d
std/process.d
std/range/primitives.d
std/regex/internal/generator.d
std/regex/internal/ir.d
std/string.d
std/traits.d
std/uni.d
std/uuid.d

- remove empty statement - e.g. `struct {};`
- change infinite `empty` property functions  to `enum`
- removed unnecessary parenthesis 
- removed implicit string concatenation
- replaced `enum` with `static immutable` for arrays and `immutable` for dicts

minor style fixes

---

etc/c/curl.d
etc/c/odbc/sqltypes.d
etc/c/sqlite3.d
etc/c/zlib.d
std/experimental/allocator/building_blocks/affix_allocator.d
std/range/package.d
std/typecons.d

AFAICT we should only use one `alias` syntax in Phobos (and hopefully deprecate the older soon).
This PR deprecates the  old `alias type identifier`  in favor of the new `alias identifier = type` syntax.

use the 'new' alias syntax

---

.dscanner.ini
.travis.yml

follow-up to #4239. Here's a simple setup with Travis.
Obviously a lot of stuff fails (= Phobos doesn't stick to it's own style), but I argue that we should fix this and then enable this bot to help submitters.
Using [DScanner](https://github.com/Hackerpilot/Dscanner) allows us to check for a couple of goodies:
- Check for array literals that cause unnecessary allocation
- Check for poor exception handling practices
- Check for use of the deprecated 'delete' keyword
- Check for use of the deprecated floating point operators
- Check number literals for readability
- Checks that opEquals, opCmp, toHash, and toString are either const, immutable or inout.
- Checks for .. expressions where the left side is larger than the right.
- Checks for if statements whose 'then' block is the same as the …

use travis CI to lint Phobos

---

std/datetime.d
std/regex/internal/generator.d

@klickverbot quickly removed the `@property`.
(follow-up to #4247)

trivial: remove @property from enums

---

std/uni.d

Add explicit return type to two auto functions `Grapheme.opSlice`, then
their calls will have no dependency to return type inference.
This is blocked by [issue 15961](https://issues.dlang.org/show_bug.cgi?id=15961), but it will be fixed in dmd master soon (#5719).

Issue 15963 - Hidden unresolved forward reference issue in std.uni

---

changelog.dd
std/conv.d

http://forum.dlang.org/post/hapxiqrdmjdiavqlpzlv@forum.dlang.org

Make all toImpl overloads private

---

std/algorithm/searching.d

@andralex @CyberShadow @Hackerpilot turns out that Dscanner also scans for this errors that slipped that slipped through. Travis should pass now ;-)
Maybe we should have autotester check Travis from now on...
Edit: for reference introduced by #4221

std.algorithm.searching.extremum - fix float comp in unittest

---

std/uni.d

The main points:
1. The constraints for `sicmp` were completely wrong because `decode` cannot be called with forward ranges. In the future this could be made to work with forward ranges but for now this needs to be fixed
2. Emphasized the fact that `icmp` can be `@nogc @safe nothrow pure` if used with `byUTF`.
3. Added more detail to `icmp`'s docs

Improvements to std.uni.sicmp and std.uni.icmp

---

std/numeric.d

It is fixed version of R's `optimise`.
f~~Blocked by https://issues.dlang.org/show_bug.cgi?id=15204~~

Add findLocalMin

---

std/bigint.d
std/internal/math/biguintcore.d

* ~~This contains the commit from https://github.com/D-Programming-Language/phobos/pull/3874 which this PR requires and was separated out for convenience~~
* ~~This is technically a breaking change because the ctor no longer errors on parsing problems, but throws~~
* The decimal path requires only a forward range, but the hex path requires a bidirectional range. I would like to make it possible for people to pass in forward ranges if they are just using decimals, as bidirectional ranges are less common than forward ranges. But, I couldn't figure out how to make the signiture accept any forward range and only accept bidriectional ranges for hexs at run time.
* For some reason I get a out of memory error on my machine for a specific unittest block. The error message is very unhelpful, so …

[issue 15229] Range-ified BigInt's Ctor to Accept Ranges of Characters

---

std/traits.d

Have a look at
https://dlang.org/library-prerelease/std/traits.html
https://dlang.org/library/std/traits.html
`` shows up there. Did you want to hide this from the user?

std.traits: remove html comment

---

std/regex/internal/backtracking.d
std/regex/internal/ir.d
std/regex/internal/kickstart.d
std/regex/internal/parser.d
std/regex/internal/tests.d
std/regex/internal/thompson.d

Also should optimize a tiny bit things like '.' and '^' by separating e.g. beginning of line vs beginning of string on the instruction level rather then checking a run-time flag every time.

[std.regex] Support for inline flags

---

changelog.dd

Accidentally deleted in 7d332592590f83573ff6d7729391557e69cdb021.

restore accidentally deleted "swapAt"

---

std/algorithm/mutation.d

All overloads require a bidirectional range with lvalue elements.

documentation: fix requirements of remove

---

std/socket.d

In particular, `send`/`receive` weren't `@nogc`.

std.socket: Decorate Socket methods

---

std/encoding.d

* move to std.encoding
* less overengineering
https://github.com/D-Programming-Language/phobos/pull/3870 rework

Byte Order Mark (BOM) handling functions rewrite

---

std/range/primitives.d

They should be documented for clarity - narrow string front/back don't have `ref` return.
Also make back not compile when T is void, as front does.

[trivial] Document narrow string front, back

---

std/traits.d

On a slightly related note, @wilzbach I think the dscanner warning about undocumented public symbols should be enabled to avoid things like this.

Fix Issue 15980: std.traits.Identity is undocumented but public

---

std/algorithm/sorting.d

As I now bumped for the second time into the problem of having a chainable `multiSort` (=SortedRange), I quickly wrote my own solution. Afterwards I realized that #4061 is already open, there are a couple of minor differences, here
1) a inline, static function instead of MultiPred struct is used.
2) no `shrink` method is provided (but can be in the future)
So in summary less (possibly controversial) changes.
As always, I am very happy about feedback.
@SzMK - let's join efforts to get this into Phobos?

Fix issue 10777 - multiSort should return a SortedRange

---

std/net/curl.d
std/uri.d

This overload provides the ability to send properly escaped www-form-urlencoded data using an associative array.
I am rather new to d language so I am sure improvements may be needed to the provided code. I assume that this would be a useful addition to the std.net.curl library, since you usually want to send name value pairs via post using www-form-urlencoding, rather than an array of ubytes.
The syntax for use as documented is: 
```d
import std.net.curl;
auto content = post("mydomain.com/here.cgi", ["name1" : "value1", "name2" : "value2"]);
```

Implement post overload in std.net.curl

---

std/traits.d

It seems sensible to me to show examples of what __is__ a char instead of what is not.

Added documentation for isSomeChar/isSomeString.

---

std/file.d

In Solaris call getcwd(null, 0) is wrang.

Solaris: corrected getcwd call.

---

.travis.yml
std/traits.d
std/variant.d

It turns out that currently dscanner is failing, but we just silently filter these error messages.
1) Thus for (yet to be known reasons) dscanner throws exceptions for a couple of modules in `std` (and everything in `etc`). I will try to dig deeper into the assertion error, but for now this should actually test most of phobos with dscanner ;-)
2) the replacement `sed 's/dparse_verbose/StdLoggerDisableWarning/'` is to use the fast debug build without any debug logging ;-)
Ping @CyberShadow @Hackerpilot

proper filtering of dscanner

---

std/functional.d

In this case, there should be a less or equal comparison, instead of less than.

Fibonacci should only be calculated for values bigger than 2.

---

std/experimental/ndslice/iteration.d

There are couple of other places where `iota` is used throughout this module (such as [this](https://github.com/ZombineDev/phobos/blob/9e2268ca19691949266e622dc531c7c1ef7193dd/std/experimental/ndslice/iteration.d#L534)), but I chose to leave them as they are, because they're more clear that way, IMO.
Let me know if you want me to replace them all.

Use iotaSlice instead of iota in one more place

---

changelog.dd

I forgot to add this in the original PR

Add regex splitter changes in the change log

---

std/uni.d

This optimizes std.uni.asLowerCase and std.uni.asUpperCase by adding an ascii check in the shared std.uni.toCaser template. This is to help address issue: https://issues.dlang.org/show_bug.cgi?id=11229. There have been similar optimizations in other case conversion code recently to address this issue. This change tries to be consistent with the others.
In my tests, this change sped up asLowerCase in latin languages about 75% (English, German, Spanish, Finnish). For example, 1000 repetitions over a Finnish text went from 23 seconds to 5 seconds. Similarly, a German text from 31 seconds to 7 seconds. Japanese and Chinese texts were unchanged, as expected. Tests were done on OSX with dmd settings `-release -O -boundscheck=off -inline`.
Note: This is my first pull request, please review …

ASCII optimization check in toCaser, for asLowerCase and asUpperCase

---

std/process.d

Needed for https://github.com/dlang/druntime/pull/1569 to pass the autotester without requiring https://github.com/dlang/phobos/pull/4294, which depends on it.

std.process: Disambiguate fork calls

---

std/uni.d

* Removes all total, non-global imports and replaces them with selective imports
* ~~encapsulates a unsafe subtraction from `size_t`~~

Clean up of std.uni (part 2)

---

std/datetime.d

The windows tester systematically fails because a new windows time zone entry was added for the Easter Island.
https://blogs.technet.microsoft.com/dst2007/2016/03/23/time-zone-update-for-chile-and-haiti/
This PR fixes the two functions involved.  (_tzDatabaseNameToWindowsTZName_ and _windowsTZNameToTZDatabaseName_). They're gonna be deprecated in next rlz but they still need to be maintained.
reference for the names:
- "Pacific/Easter": https://en.wikipedia.org/wiki/Pacific/Easter.
- "Easter Island Standard Time": value from windows itself.

hotfix (tester) - Easter Island & Haiti Windows time zone

---

std/math.d

The affected line cannot be directly tested right now, but the new algorithm has been verified:
* It passed at CTFE on all 10 auto-tester platforms, as part of a larger PR that I subsequently closed for unrelated reasons: https://github.com/dlang/phobos/pull/4328
* You can also see the test code just for this PR on [DPaste](https://dpaste.dzfl.pl/0ac4bdd211af).
* Unlike the old algorithm, this one actually makes sense...

Fix the broken fallback algorithm for `std.math.isInfinity()`

---

.travis.yml
std/container/rbtree.d
std/conv.d
std/csv.d
std/datetime.d
std/exception.d
std/experimental/ndslice/selection.d
std/getopt.d
std/net/curl.d
std/parallelism.d
std/range/package.d
std/regex/internal/parser.d
std/socket.d
std/uuid.d
std/xml.d

I realized we forgot to add `catch` to the enforce whitespace after operator list.
`switch` was already sticking to the style guide. So this is the result of a simple `sed`:
```
sed -i "s/catch(/catch (/" **/*.d
```
Btw a short look the D spec yielded the following statements - do we consider one of them as operator?
```
mixin
version
scope
synchronized
with
```

enforce: whitespace after catch

---

std/file.d
std/math.d
std/stdio.d
std/zip.d

Tests that use the local directory cannot be run from an Android apk, and Android comes with gzip, but not unzip.

Fix Android regressions

---

.dscanner.ini
.travis.yml

This PR updates dscanner and its configuration because the old file is not compatible with a recent change in dscanner (which is that a test can be _"enabled"_ | _"disabled"_ | _"skip-unittest"_)

update dscanner to alpha 6

---

std/bigint.d

Because it's faster and bigint only accepted things in the ASCII range anyway.

Remove auto decoding in bigint's ctor

---

std/math.d

This PR fixes [Phobos issue #16026](https://issues.dlang.org/show_bug.cgi?id=16026): `std.math.frexp!float()` and `std.math.frexp!double()` return a wrong significand for subnormal values.
The problem turns out to be a wrong "*magic number*" `0x8000` which selects which values of the highest 16 bits should be preserved while manually changing the exponent using bitwise operations. The correct value is `~F.EXPMASK`, which happens to equal `0x8000` for the 80-bit and 128-bit IEEE formats, but not for 32- or 64-bit.
(Ultimately, I intend to replace the entire `frexp()` implementation with a clearer and more concise one based on [`RealRep`](https://github.com/dlang/phobos/pull/4336), but I realize that it may take a while to get such a large change pulled, so I thought I'd submit this quick …

Fix issue 16026: std.math.frexp!float() wrong for very small subnormals

---

std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/setops.d

Here's a small project that I intend to do when I am on the road - document the public methods in Phobos or set them private etc ;-)
As you can imagine, many parts in Phobos aren't properly ddoced - so let's do this bit by bit.
If someone wants to help out, here's the [current output of dscanner](http://sprunge.us/LjXd).
There are some fixes which might be controversial - I will mark them so.

std.algorithms: document public methods

---

std/variant.d

Because {} looks like a delegate, block statement, struct literal, dessert topping, and floor wax.

Fix delegates in unit test so that they actually return void and do nothing

---

std/algorithm/searching.d

Added two unittests and restricted the remaining ones with `@safe pure nothrow @nogc` when possible.
Question: Should the parameter `rhs` to `opAssign` be qualified as a constant reference?

Fix Issue 15918

---

std/container/array.d

adds a top-level module example to `std.container.array` - ping @schveiguy

add module example to std.container.array

---

std/json.d

```d
@property inout(JSONValue[]) arrayNoRef() inout pure @trusted
{
enforce!JSONException(type == JSON_TYPE.ARRAY,
"JSONValue is not an object");
return store.array;
}
```
changed to 
```d
enforce!JSONException(type == JSON_TYPE.ARRAY,
"JSONValue is not an array");
```

Wrong exception message in std.json

---

std/uni.d

follow-up to #4354 - this document is hard to read with all the unnecessary whitespace.
http://dlang.org/phobos/std_uni.html

fix table formatting in uni.d

---

std/process.d

Also fix erroneous usage of errnoEnforce in fork.
Needs https://github.com/dlang/druntime/pull/1571

std.process: Enforce nothrow/@nogc in forks

---

std/math.d
std/stdio.d

The idea is that once leaking of symbols from module-level selective imports is considered fixed, ie in all downstream code too, and its use is enabled, someone can make the commented out symbols at the top selective and these modules won't have the compiler searching for any symbols afterwards.  These changes were made by hacking ldc to dump all the symbols that it had to search for ([as described previously with dmd](http://forum.dlang.org/thread/pbpckzwmfglzgwqveoza@forum.dlang.org) and [done before for `std.stdio`](https://github.com/dlang/phobos/pull/2809)), and then making them either selective or adding them to the commented out list at the top of the module, if the symbol was needed at module scope.

std.math and std.stdio: use more selective imports

---

std/uni.d

Checked by dumping data from ldc frontend, as done for other modules, #4361.

std.uni: use selective imports and document module-scope imported symbols

---

std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d

As I use the Phobos docs recently I am quite annoyed by the whitespace ddoc produces - it turns out that one can't have `<br>`'s in table, thus this PR removes them and ... the whitespace is gone :)
https://dlang.org/phobos/std_algorithm.html
https://dlang.org/phobos/std_algorithm_mutation.html

remove whitespace in ddoc output of std/algorithm

---

std/regex/internal/ir.d

Will be required by https://github.com/dlang/dmd/pull/5737
@Hackerpilot : Shouldn't dscanner have picked that up ?
Ping @DmitryOlshansky since inlining this part of the code seems critical.

Do not rely on the result of a comma expression

---

std/container/rbtree.d

Simple -- if type doesn't support formatting the range, then don't define `toString`. This means it defaults to `Object.toString` in those cases, but this isn't really a problem.
There are likely better ways to do this, but this fixes the regression now.
Need to see how docs get generated to find out if I did that part right.

Fix issue 15941 -- rbtree no longer supports classes

---

std/experimental/allocator/building_blocks/bucketizer.d

With the latest compiler, running unittests yields:
```
std/experimental/allocator/building_blocks/segregator.d(188): Deprecation: std.experimental.allocator.building_blocks.bucketizer.Bucketizer!(FreeList!(GCAllocator, 0LU, 18446744073709551615LU, cast(Flag)false), 1LU, 128LU, 16LU).Bucketizer.reallocate is not visible from module std.experimental.allocator.building_blocks.segregator
std/experimental/allocator/building_blocks/segregator.d(182): Deprecation: std.experimental.allocator.building_blocks.bucketizer.Bucketizer!(FreeList!(GCAllocator, 0LU, 18446744073709551615LU, cast(Flag)false), 129LU, 256LU, 32LU).Bucketizer.reallocate is not visible from module std.experimental.allocator.building_blocks.segregator
std/experimental/allocator/building_blocks/segregator.d(188): Deprecation: …
```

Remove spurious deprecation lookup warning

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/package.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/common.d
std/experimental/allocator/gc_allocator.d
std/experimental/allocator/package.d

I had what now seems to be a wrong design: if `expand` is called with the `null` array, it attempts to allocate. That is counterintuitive because putative clients expect `expand` to either fail, or succeed without modifying the pointer in the array.
This PR embodies the new design: the null array cannot be expanded in place.

Change semantics of expand: the null array cannot be expanded 'in place'

---

std/meta.d

It seems like I am not the only one (e.g https://github.com/dlang/phobos/pull/4088) who didn't realize there was a system behind the naming in std.meta, better document it?
Ping @klickverbot

add quickindex table to std/meta.d

---

std/ascii.d
std/datetime.d

Found two modules with weird copyright info.
The new default Ddoc macro is "Copyright © 1999-2016 by the D Language Foundation".
The copyright notice is only displayed at the bottom of the page.

remove invalid copyright notices

---

std/json.d

This is a continuation of @BBasile 's PR #4343 .

Fix issue 15885 - float serialized to JSON loses precision

---

std/container/package.d

follow-up to #4354 - you currently have to scroll _a lot_ to reach the container table.
http://dlang.org/phobos/std_container.html
I took the opportunity to reformat the table properly.

fix table formatting in container

---

std/container/binaryheap.d

- adds a top-level example for the binary heap
- adds support to extend/grow a normal array (didn't see a reason why this shouldn't be allowed)
- removes the out-commented private (seems like the bug was fixed)
Ping @schveiguy

add top-level example for binary heap

---

std/meta.d

Move allSatisfy, anySatisfy and staticIndexOf to searching category in the quick index table

---

std/uni.d

Ping @DmitryOlshansky, this slipped through in #4365.

std.uni: roll back module-scope selective import that slipped through

---

std/algorithm/searching.d

Slipped through pull request #4362. Since "above" is a different
algorithm the removed comment is misleading. It did make sense in
previous versions of PR #4362.

Removed outdated comment

---

std/string.d
std/traits.d

Checked with ddmd, as always, ~~also fixed extra spaces in `std.uni`~~, never mind, that's now fixed in a later PR, #4380, so removed it from this one.

std.string and std.traits: use locally-scoped selective imports and document module-scope symbols

---

std/net/curl.d

follow-up to #4312 - `stopped` was exposed to the public - I wasn't sure whether this was on prupose, but  to be sure I added a wrapper around it.

std.curl: document public methods

---

std/stdio.d

As a companion to https://github.com/dlang/phobos/pull/4400, this should be done as well, as it could be months before that commit goes into a release, if it's even merged at all.
The programmer should be warned in the mean time.

Warn about Issue 15768

---

std/math.d
std/stdio.d
std/string.d
std/traits.d
std/uni.d

Range primitives for built-in arrays were mostly moved to module scope, unless they were used rarely in the module.  Some local selective imports were missed previously because they were used in untested `debug`/`version` blocks, filled those in too, went through and made sure all local imports were in alphabetical order.  I tried making a few last imports selective, more notes below.

Fix recent local selective imports and finish up

---

.travis.yml
std/algorithm/searching.d
std/string.d

It turns out that Travis doesn't like the string `"import ([^ ]+) : ", this prevent it from running for the last five days and hence two style violations slipped through. I am sorry about that.
This PR fixes our Travis setup and fixes the two violations ;-)

Fix travis build

---

std/json.d
std/stdio.d

I used [linkchecker](https://github.com/wummel/linkchecker) to find these.
Unfortunately it doesn't build by default and I had to patch it, hence the setup is a bit more complicated. If someone wants to try it for himself, here's my "simple" script
```
git clone https://github.com/wummel/linkchecker && cd linkchecker
wget http://sprunge.us/VIWV > my.diff # maybe you don't need that, I do
git apply my.diff
virtualenv build/python -p /usr/bin/python
build/python/bin/pip install -r requirements.txt
build/python/bin/python setup.py install
build/python/bin/linkchecker -t 100 http://localhost:8080 --no-warnings --check-extern -o html --ignore-url "bugstats.php" --ignore-url "dlangspec.pdf" --ignore-url "https://code.dlang.org" --ignore-url="dlangspec.mobi" --ignore-url="/library/" …
```

Fix more 404s links

---

std/experimental/allocator/building_blocks/package.d
std/experimental/allocator/package.d

Replacing LINK2, A, and the custom XREF2 with MREF and friends. Also
removing other unused macros.
This fixes the links on DDOX pages.

Ddoc: clean up macros in std.experimental.allocator

---

changelog.dd
index.d
posix.mak
std/digest/murmurhash.d
win32.mak
win64.mak

A proposal of addition of murmurhash3 to phobos.
Maybe it should go in experimental first. Please let me know what you think.

Adding murmurhash3 digest to phobos

---

std/zip.d

LINK2 is OK for external links, right?

Fix bad host.

---

std/meta.d

The added codes in unittest not work before.

make ApplyLeft/ApplyRight work with deep template

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/gc_allocator.d
std/experimental/allocator/mallocator.d
std/experimental/allocator/mmap_allocator.d
std/experimental/logger/core.d
std/experimental/logger/filelogger.d
std/experimental/logger/multilogger.d
std/experimental/logger/nulllogger.d

The DDOX based documentation is configured to only show entities with doc comments and thus hides modules without one. This adds an empty comment to all public Phobos modules that have stayed undocumented so far.
They should probably get a proper documentation with description/license/copyright/.... This just fixes the documentation until then.

Add empty doc comments to all public Phobos modules to fix /library/.

---

std/datetime.d

Checked using ddmd, this module was my bete noir, as I wasn't looking forward to scanning this massive file.  Turned out not to be that different from other large modules, especially since it already extensively uses locally-scoped selective imports.  This PR merely does the rest.

std.datetime: use locally-scoped selective imports and document module-scope symbol imports

---

posix.mak

Since the update to use native TLS on OS X the minimum deployment
target is now OS X Lion (10.7).

Set deployment target to the minimum supported version of OS X

---

std/bitmanip.d

add missing comma to authors of std.bitmanip

---

std/utf.d

Necessary for https://github.com/dlang/dmd/pull/5860

fix unsafe .ptr access in Phobos

---

std/datetime.d
std/experimental/logger/package.d
std/string.d
std/typecons.d

As mentioned in https://github.com/dlang/dlang.org/pull/1337 and https://github.com/dlang/dlang.org/pull/1333, yet another `sed` adventure!
Today's purge are the `WEB`, `HTTP`, `HTTPS` macros. 
Reason: We still have way too many custom ddoc macros to make simple links - creating a link should be simple!
Have a look at this selection:
```
A = <a href="$1">$+</a>
AHTTP = <a href="http://$1">$+</a>
AHTTPS = <a class="https" href="https://$1">$+</a>
ALOCAL = <a href="#$1">$+</a>
LINK = $(A $0, $0)
LINK2 = $(A $1, $+)
HTTP = $(LINK2 http://$1,$2)
HTTPS = $(LINK2 https://$1,$2)
WEB = $(HTTP $1,$2)
```
Some people might argue that `WEB` is great, because it's a bit shorter, but
- it leads to problems if you think it's a normal link and use `http://` (happens quite often, even here in Phobos)
- …

Fix broken WEB links

---

std/datetime.d

This should do it. See #4433. Used data from https://blogs.technet.microsoft.com/dst2007/2016/06/02/introducing-new-windows-time-zones/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones to figure out missing time zone information.
Please do not pull without auto tester. Ping @jmdavis. If this works, it should be cherry-picked into stable.

Add missing time zones to fix build issue.

---

std/algorithm/iteration.d
std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/common.d
std/math.d
std/numeric.d
std/uni.d

This is intended to supersede [PR #4308](https://github.com/dlang/phobos/pull/4308), which adds `std.math.isPowerOf2()`. Improvements:
* Support floating-point numbers.
* Corrected handling of signed integers.
* Reduced template bloat, by marking `x` as `const`.

Add `std.math.isPowerOf2()`. Supports floating-point and integers.

---

changelog.dd
std/math.d

This is a generalization of @jamadagni 's PR #3759 . Changes:
- I flipped the sign for `prec` / `exp`.
- Very large and very small values are handled correctly.
- NaN and infinities are handled correctly.
- The base is now a parameter; it is not locked to `10` any more.
- The rounding function is a parameter, to allow reusing the same logic with `floor()`, `ceil()`, and `nearbyint()`. It defaults to `rint()`, since that seems to be the fastest method which respects the current rounding mode.
- A couple of overloads were added to allow optimizations when the `base` (and possibly `exp`) are known at compile time. In particular, I wanted to use `ldexp()` to speed up the case where `base` is a power of two. This is not currently implemented though, because so much of `std.math` doesn't work …

Add std.math.quantize() for rounding to a multiple of some number.

---

std/traits.d

Nested member's `@disable opAssign` should propagate to parents.
Required by https://github.com/dlang/dmd/pull/5854

Issue 16142: Correct test for hasElaborateAssign

---

std/functional.d
std/range/package.d

Checked with ddmd, similar to #4365.
__Update:__ I was getting a lot of shared ctor cycles in the auto-tester from updating `std.range`, which appeared to be from importing `std.algorithm.comparison` directly instead of `std.algorithm`.  I tried changing all those instances to `std.algorithm` and that fixed it, but seemed like a hack.  If I simply didn't touch the pre-existing uses of `std.algorithm` for symbols from `std.algorithm.comparison` and didn't change the few pre-existing direct imports of `std.algorithm.comparison`, the cycle still came up, ie simply from adding or modifying other imports.  That seems like a bug.
Rather than going back to importing the package `std.algorithm` everywhere, I went down the list of imports in the cycle, conveniently listed by the druntime error, …

std.range and std.functional: use locally-scoped selective imports and document module-scope symbol imports

---

std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/setops.d

follow-up to #4312. This includes a couple of accidentally exposed publicly exposed methods - they weren't documented.
For permutations I added deprecations, but I would prefer if we can live without them ;-)

std.algorithm: set accidentally exposed methods to private

---

std/range/interfaces.d
std/range/package.d
std/range/primitives.d

std.range: document public methods

---

std/typecons.d

https://issues.dlang.org/show_bug.cgi?id=16054
Code from the bug report showing how immutable can be broken when `get` returns a reference:
```d
import std.typecons: Rebindable;
class C
{
int x;
this(int x) pure { this.x = x; }
}
void main()
{
Rebindable!(immutable C) ic = new immutable C(1);
immutable(C)* p = &ic.get();
assert(p.x == 1); /* passes */
scope (exit) assert(p.x == 1); /* fails */
ic = new immutable C(2);
}
```

fix issue 16054 - can break immutable with std.typecons.Rebindable

---

std/math.d

If an overflow or underflow occurred in one of ``exp``, ``expm1``, or ``exp2`` we should return infinity or 0.0 computationally at runtime, forcing overflow/underflow ``ieeeFlags`` to be set.   At the same time, this still respects the fast path in CTFE.
This should fix the ``exp``/``exp2`` and ``ieeeFlags`` unittests for non-x86 targets (though only tested on gdc x86_64).

Force overflow/underflow in generic std.math implementations

---

std/algorithm/iteration.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d

The higher motivation here is:
1) to have copy-able code for the users that works (without import errors)
2) to be able to run the unittest directly on dlang.org (see #1297)
This PR is done semi-automatically with a [small tool](https://github.com/wilzbach/d-scripts/blob/master/check_phobos_tests.d) that runs all tests in Phobos `outside` of the module scope, so further automation is planned & hopefully will be part of Phobos in the foreseeable future ;-)

add external imports to documented unittests in std.algorithm

---

std/typecons.d

Because `size_t` isn't guaranteed to be the same size as a pointer, while `uintptr_t` is. Also, when checking for alignment, casting to `uint` is better because it can be faster.

typecons: size_t should be uintptr_t

---

std/uni.d

Fixed typo: "below" instead of "bellow".

---

changelog.dd
std/traits.d

Using Kenji Hara's code that was posted in the issue tracker; I guess he just never got around to making a PR?
Adds the following traits:
* `isType`
* `isFunction`
* `isPropertyFunction`
* `isVariable`
* `isEnum`
* `isFinal`

New Traits for std.traits

---

std/range/package.d

- useful for searching around a mid-point in a sorted array,
e.g. foreach (e; r.radial(r.lowerBound(pivot).length))
- symmetric support of both empty left and right subrange
- still throws when startingIndex is bigger than r.length

support startingIndex == r.length for std.range.radial

---

std/functional.d

There are so many exact tests in the test suite that we don't need to duplicate them here - just a covariant test will do.

use covariant tests rather than exact ones

---

std/conv.d

This is a blocker for https://github.com/dlang/dmd/pull/5881

std.conv: need cast(void) to address warning

---

std/format.d

This has been "planned for deprecation" pretty much since the beginning of D2. It's only user in Phobos is in std.stream, so I figure it should follow std.stream into undeaD. I've already copied it to undeaD.

std.format: deprecate doFormat()

---

std/format.d

Another blocker for https://github.com/dlang/dmd/pull/5881
This fix makes it work with or without 5881.

fix formatting of inference

---

std/traits.d

Because the inference rules change, and this makes traits resistant to such changes. Yet another blocker for:
https://github.com/dlang/dmd/pull/5881
so please don't delay reviewing/pulling this.

std.traits: prevent inference of attributes of test cases

---

std/range/package.d

Necessary for the better rules on function attribute inference (nested functions should not inherit @safe from enclosing function).

add @safe to test structs

---

std/typecons.d

Because the inference rules change, and this makes traits resistant to such changes. Yet another blocker for:
dlang/dmd#5881
so please don't delay reviewing/pulling this.

std.typecons: prevent inference of attributes of test cases

---

std/file.d

This is blocking https://github.com/dlang/dmd/pull/5887

std.file: delete is not @safe

---

std/range/package.d

`save` was not called properly

Fix bug in std.range.roundRobin example
