std/algorithm.d
Fixup for: https://github.com/D-Programming-Language/phobos/pull/2828
=> Fixup for PR #2828 to respect line length limits.

std/algorithm.d
A small documentation improvement in std.algorithm.
=> Sort lists of functions

std/c/fenv.d, std/c/freebsd/socket.d, std/c/linux/linux.d, std/c/linux/linuxextern.d, std/c/linux/pthread.d, std/c/linux/socket.d, std/c/linux/termios.d, std/c/linux/tipc.d, std/c/locale.d, std/c/math.d, std/c/osx/socket.d, std/c/process.d, std/c/stdarg.d, std/c/stddef.d, std/c/stdio.d, std/c/stdlib.d, std/c/string.d, std/c/time.d, std/c/wcharh.d, std/c/windows/com.d, std/c/windows/stat.d, std/c/windows/windows.d, std/c/windows/winsock.d, std/windows/iunknown.d
Per https://github.com/D-Programming-Language/phobos/pull/2337#issuecomment-68633607
Just revert this once 2.067 is out the door.
=> Temporarily replace new deprecations with comments

std/outbuffer.d
=> add annotations to std.outbuffer

std/math.d
Add detail, example, and helpful links.
=> improve doc of std.math.sin

std/format.d
Per: https://github.com/D-Programming-Language/phobos/commit/e03e647cea5a2cff0ff72195e8c7907127b3b5e6#commitcomment-9194481
=> Get rid of obsolete useless comment.

std/array.d
e.g. with `r.map!(someExpensiveFunction).join`, `join` would previously iterate twice: once to compute length, and again to build up the result. The extra iteration to compute length may be disproportionately expensive, so we now only precompute length for built-in arrays, since we know those are cheap to iterate.
The heuristic could be improved over time, although I can't think of anything better right now.
https://issues.dlang.org/show_bug.cgi?id=13877
=> Fix Issue 13877 - join assumes forward range can be cheaply iterated twice

std/algorithm.d
This is just the first stab at it, since this module is way too big to do all in one go. I'll submit separate PRs for the rest of it later.
=> Improve std.algorithm docs (part 1)

std/net/isemail.d
Make std.net.isemail.EmailStatus properties const.
=> Const correctness in std.net.isemail

std/algorithm.d
Improve docs for splitter, joiner, and uniq.
=> Improve std.algorithm docs (part 2)

std/algorithm.d
I had the need to split an array of structs using a modified equality test. Since slitter is build on top of find, this is a rather simple change. I do not know of any downsides.
=> Add predicate to splitter

std/algorithm.d
https://issues.dlang.org/show_bug.cgi?id=13124
=> Fix Issue 13124 - Allow non-bool predicates for until

std/algorithm.d
These were required to get splitter with a non-symmetric working.
=> Various small fixes to get non-symmetric predicats working

std/container/array.d, std/container/package.d
I tried to explain some things that confused at least me in the beginning.
=> Improve docs of std.container

std/algorithm.d, std/digest/crc.d, std/digest/digest.d, std/digest/md.d, std/digest/ripemd.d, std/digest/sha.d, std/math.d, std/net/curl.d, std/outbuffer.d, std/socket.d, std/string.d, std/uuid.d
Makes sure that each module has a brief intro at http://dlang.org/library-prerelease/index.html
=> Ensure each module has a description at the top.

std/array.d
Is this what you are looking for? There is more where this came form, however, I'd rather not be off by miles.
=> Update std.array documentation

std/algorithm.d, std/digest/crc.d, std/digest/digest.d, std/digest/md.d, std/digest/ripemd.d, std/digest/sha.d, std/math.d, std/net/curl.d, std/regex/package.d, std/string.d, std/uuid.d
Factored MYREF into std.ddoc and fixed a backtick.
=> Verbatim-related changes in phobos

std/socket.d
https://issues.dlang.org/show_bug.cgi?id=14012
https://issues.dlang.org/show_bug.cgi?id=14013
=> fix std.socket issues 14012 and 14013

std/csv.d
* moved examples from comments to unittests
* documented public but not documented function
* tabs to whitespace
=> documentation update for csv

std/conv.d
=> conv.d example moved from comment to unittest

std/complex.d
=> complex.d example moved from comment to unittest

std/algorithm/iteration.d, std/algorithm/package.d
As [requested by Andrei](http://forum.dlang.org/thread/m9u2mu$1rjd$1@digitalmars.com).
=> Implement aggregate().

std/json.d
Hope ya'll forgive the shout-out to perl
=> Documentation code samples for std.json

std/functional.d
https://issues.dlang.org/show_bug.cgi?id=14025
do not assume memoize cache initialized before the arguments and the result are actually written
=> fix Issue 14025 - unittests for memoize fail intermittently 

std/encoding.d
* moved examples form comments to unittests
* marked unittests as examples
* removed 6 year old dead code
=> encoding.d documentation update

std/outbuffer.d, std/stream.d
Try #2902 again, now that the win64 problem has been fixed.
=> Revert "Merge pull request #2905 from 9rnsr/revert_pull2902"

std/math.d
* many small doc updates, a lot of examples 
* many unittests were marked safe, pure etc.
=> std.math documentation update and @safe pure etc. unittests

std/format.d
* to much to name it all
this is WIP
=> documentation update for std.format.d

std/numeric.d
* moved examples to unittests
* removed dead code
* removed trailing whitespace
=> documentation update for numeric.d

std/exception.d
When an Exception is thrown by a Range the execution of the Range is usually aborted.
This PR add two functions:
* handleFront
* handlePopFront
that wrap a Range and call the functions front and popFront of the wrapped Range. If the wrapped Range throws an Exception an user provided handler is called. This handler gets the Range and the Exception passed and can then be used to handle the Exception and put the Range in an workable state again.
Additional PRs will add handler Ranges for back|popBack, empty and opIndex
=> Rangeexception

std/datetime.d, std/mmfile.d, std/windows/syserror.d
In preparation for the warning in https://github.com/D-Programming-Language/dmd/pull/2885
=> Remove implicit conversions from array to bool

win32.mak, win64.mak
Fixes building documentation.
Broken in b77b89dceae4b3c809d03f7c5e4ead0538e24f74
=> Windows Makefile fixup

std/json.d
https://issues.dlang.org/show_bug.cgi?id=14065
=> fix Issue 14065 - std.json not tracking line:column properly

std/format.d
The current implementation of `doFormat` forges a `va_list` so it can recurse to print out array and AA members.  This was straightforward on X86, but the complexity of X86_64 varargs abis means that it has to jump through some rather horrific and non-portable hoops to get this to work.
This replacement implementation instead copies all variadic arguments to a buffer, being careful to preserve required alignment.  This allows the arguments to be iterated through with a simple pointer on all platforms.
The copy to the buffer naturally comes with a slight performance penalty, but given the simplification of the code, the improved portability, and the fact that `doFormat`'s only remaining caller is `std.stream`, I think it's worth that cost.
@andralex @ibuclaw
=> Copy variadic arguments to buffer to avoid horrific varargs hacks

std/conv.d, std/format.d, std/json.d, std/process.d, std/range/package.d, std/signals.d, std/string.d
Needed for https://github.com/D-Programming-Language/dmd/pull/2885
=> Replace more implicit array to bool conversions

std/typecons.d
* moved examples into unittests
=> typecons documentation update

std/traits.d
* moved nearly all examples from comments to unittests
** some few had error
* marked existing unittest as examples
** splitted some in the process as they where to long
* ditto for one pair of templates with the same name
* deleted unused code from 2008
=> std.traits documentation update

std/uri.d
* moved some examples to unittests
* made a only privately used enum private
* URIException made up to spec
=> uri documentation update

std/uni.d
* moved examples into unittests
=> uni documenation update

std/experimental/logger/package.d
* Headings make stuff easier to find
* Thread local logger description
tab to whitespace
=> logger.package documentation update

std/uuid.d
* moved some examples from comments to unittests
* one ctor was disabled, reimplemented it
=> uuid documentation update

std/stdio.d
https://issues.dlang.org/show_bug.cgi?id=14041
=> Fix issue 14041 -  Refused writeln of a fixed size array of chars

std/exception.d
Includes both semantic and documentation improvements. Also, opSlice wasn't working due to [bug #14057](https://issues.dlang.org/show_bug.cgi?id=14057) (seriously, can we PLEASE stop merging patches with half-assed review?), so I disabled support for that for now.
I also still think the interface should be more conducive to doing the right thing; for example, I doubt handling `front` but not `back` is often what is really desired, yet it's an easy mistake to make with the current interface. That's for another PR though...
Ping @burner, @quickfur.
=> Cleanup of #2724

std/file.d
https://issues.dlang.org/show_bug.cgi?id=14110
=> fix Issue 14110 - std.file.read cannot read files open for writing

std/digest/md.d, std/digest/ripemd.d, std/range/package.d, std/utf.d, std/uuid.d
This fixes unittest failures with BUILD=debug. I'll submit separate bug reports for the respective issues.
=> Unittest failures

std/range/interfaces.d, std/range/package.d, std/range/primitives.d
* moved examples from comments to unittests
* marked verify unittests as doc unittests and deleted duplication
=> range documentation update

std/variant.d
* moved examples from comments to unittests
* some tests failed because of old copy paste bugs (fixed)
=> variant documentation update

std/file.d
This is one step toward fixing https://issues.dlang.org/show_bug.cgi?id=14125
=> Fix read() on posix

std/format.d
https://issues.dlang.org/show_bug.cgi?id=14153
=> [DDoc] fix Issue 14153 - std.format page displaying incorrectly

std/experimental/logger/core.d
The single arg optimization broke log calls with zero arguments. This is fixing it.
Additionally log call with a LogLevel off must not be logged.
=> log specification of zero arg call was broken

std/array.d
Sets `uninitializedArray()` to be @system when it is returning uninitialized pointers.
Removes code that uses @trusted to inject unsafe code into surrounding context.
Discovered that `insertInPlace()` does not work when faced with a postblit and CTFE. CTFE and blitting memory about with system code really doesn't work too well. This aspect still needs work, but at least it'll error out with the memcpy call now.
=> fix trusted issues in std.array

std/algorithm/sorting.d, std/conv.d, std/getopt.d
See comments from #2974, specifically
https://github.com/D-Programming-Language/phobos/pull/2974#discussion_r24388654
=> Remove unneeded .dup of arrays

std/string.d
Was using `splitLines()` and ran into some problems. Fixes:
1. improved documentation
2. eliminated excessive and quite unnecessary decoding - only LINESEP and PARASEP ever need decoding, and those only for UTF-8 (never ever need to decode surrogate pairs)
3. no longer throws on invalid UTF - current practice is to ignore invalid UTF if possible, and substitute in 'Replacement Character' 0xFFFD if not. This change simply ignores invalid UTF. UTF validation should be done separately by the user if desired, not on every string operation. Throwing wasn't documented for `splitLines()` anyway, so this should be ok.
4. eliminates memory allocation that `decode` may do (for its exceptions)
5. reduced number of variables in critical loop, should result in better register allocation
6. not …
=> improve string.splitLines()

std/zip.d
These bugs are marked as FIXED.
=> Zip.d documentation update

std/algorithm/setops.d
=> [TRIVIAL] Improved constraints and front() for setUnion

posix.mak, std/algorithm/comparison.d, std/algorithm/internal.d, std/algorithm/iteration.d, std/algorithm/mutation.d, std/algorithm/package.d, std/algorithm/searching.d, std/algorithm/setops.d, std/algorithm/sorting.d, win32.mak, win64.mak
https://issues.dlang.org/show_bug.cgi?id=14149
Added `import std.algorithm.internal : algoFormat;`.
Still the code doesn't work (fails with forward reference error). Blocked by https://issues.dlang.org/show_bug.cgi?id=13372
=> Issue 14149 - Bad std.algorithm error messages

std/traits.d
Required by: https://github.com/D-Programming-Language/dmd/pull/4396
=> Supplemental fix for issue 2789

std/csv.d
Modified double comparison from
a == b
to
abs(a-b) < epsilon
=> Fix std.csv assertion

win64.mak
this should fix it
win32 fix https://github.com/D-Programming-Language/phobos/pull/3023
=> the win64 makefile is somehow not including the logger

std/array.d, std/format.d, std/functional.d
This is beautification. Not sure if I should include the std.range documentation, especially since #3003 is still open.
=> Add table headers in ddoc function tables

std/math.d
=> [2.067.0-b2][regression] fix Issues 14212 and 6586

std/numeric.d
@MartinNowak  please add this doc fix to the release.
`sumOfLog2s` is new function.
=> fix docs for 2.067

std/bigint.d, std/internal/math/biguintcore.d
Also add comment to `internal.math.biguintcore.fromDecimalString`.
=> Add (mostly `@nogc`) attributes to `bigint` module.

posix.mak
Reverts D-Programming-Language/phobos#3033
=> Revert "Revert "make flags are automatically communicated to sub-make""

std/internal/math/gammafunction.d, std/mathspecial.d
~~Depends on #3021.~~
See also Log Minus Digamma function #2957.
=> Inverse of the Log Minus Digamma function

std/typecons.d
https://issues.dlang.org/show_bug.cgi?id=14213
=> [REG2.067a] Issue 14213 - Strange deprecated message in std.typecons.Proxy with using method

std/range/package.d
These changes are in keeping with the vision of ```assert```s being for program bugs.
* std.range.stride is now usable from ```@nogc``` and ```nothrow```.
* std.range.iota for non-floating types now works with ```@nogc``` and ```nothrow```.
This is a breaking change for anyone who relied on the old exceptions to validate their input.
=> std.range: replace some enforces with contracts

std/uni.d
Add missing sections of documentation
http://dlang.org/phobos/std_uni.html#sicmp
=> fix documentation for std.uni.sicmp

std/uni.d
http://dlang.org/phobos/std_uni.html#.graphemeStride
=> improve doc for std.uni.graphemeStride()

std/algorithm/comparison.d
=> doc comments for algo.cmp.among

posix.mak, std/ascii.d
Add `Returns:`, `Params:`, code examples, improve wording of some existing docs.
=> Improve std.ascii docs.

std/algorithm/comparison.d
=> std.algo.cmp.levenshteinandpath docu

std/algorithm/comparison.d
=> std.algo.cmp.equal docu

std/algorithm/comparison.d
=> std.algo.cmp.levenshtein docu

std/range/package.d
A search on a sorted list is so much nicer, especially for humans.
=> Sort ddoc table of functions in range package

std/algorithm/comparison.d
Params, Returns
Also removed some incomplete sentences
=> std.algo.cmp.cmp doco

std/algorithm/comparison.d
* Returns and Params for clamp
=> std.algo.cmp.clamp docu

std/typecons.d
- Add examples
- Move old examples to documented unit tests
- Document certain behaviours (such as how tuples are compared)
=> Improved std.typecons.Tuple documentation.

std/string.d
Adheres to http://www.unicode.org/versions/Unicode7.0.0/ch05.pdf
=> Add all line breaking whitespace to splitLines and lineSplitter

std/zlib.d
Jumping in on the "Phobos Documentation - call to action" action.
=> added documentation for std.zlib.adler32

std/algorithm/comparison.d
* selective import
* some symbols where used only private
* missing ditto
=> algorithm_comparison maintenance 

std/algorithm/comparison.d
=> std.algo.cmp.max docu

std/algorithm/comparison.d
=> std.algo.cmp.castSwitch docu

std/typecons.d
Add a Params and Returns section.
=> Improve alignForSize Documentation

std/typecons.d
- Add Params and Returns where appropriate
- Turn examples into documented unittests
=> Improve Rebindable documentation

std/string.d
http://dlang.org/phobos/std_string.html#.outdent
=> improve doc for std.string.outdent()

std/typecons.d
- Formatting and wording fixes
- Fix documented unittest for expand
- Add Params and Returns where appropriate
- Document toHash
=> Further improvements for Tuple's documentation

std/string.d
http://dlang.org/phobos/std_string.html#.column
=> improve doc for std.string.column

std/typecons.d
- Add a better opening explanation
- Add Params section
- Add documented unittest examples
=> Improve documentation for std.typecons.Proxy

std/string.d
String functions should handle input ranges of text. Also upgraded the unit tests for `column()` so the coverage is complete.
=> upgrade std.string.column to handle ranges and nelSep

std/experimental/logger/core.d
=> Typo & grammar fixes

std/string.d
1. improves documentation
2. remove dead variable
3. hoist loop invariant
4. remove unnecessary allocation
5. go to 100% unittest coverage
6. add testing of default parameters
=> improve efficiency and testing of std.string.wrap

std/range/primitives.d
http://dlang.org/phobos/std_range_primitives.html#isInputRange
=> improve doc for std.range.primitives.isInputRange

std/experimental/logger/core.d, std/experimental/logger/multilogger.d, std/experimental/logger/nulllogger.d
http://forum.dlang.org/post/idxyitbsvshwntaugbqs@forum.dlang.org
=> default LogLevel should all be equal

std/uni.d
Need range versions of toUpper() and toLower(). It's pretty much a copy-pasta of toUpper() and toLower(), converted to ranges.
100% unittest coverage.
=> add std.uni.toUpperCase and toLowerCase

std/string.d
1. accept ranges as input
2. `nelSep` is accepted as a line ending
3. unittests to 100% coverage
4. Params: and Returns: documentation
http://dlang.org/phobos/std_string.html#.chomp
=> enhance std.string.chomp so it accepts ranges

std/zip.d
Related stackoverflow question.
http://stackoverflow.com/questions/29373470/d-how-to-extract-data-from-archive/29373957
=> add introductory example to std.zip

std/algorithm/mutation.d
* Improve template parameter names
* Remove use of personal pronoun in text
* Update examples to use preferred syntax for `new` and most importantly, left-to-right range compositions through UFCS
=> Improve docs for std.algorithm.copy

std/container/rbtree.d
[Issue 14234](https://issues.dlang.org/show_bug.cgi?id=14234)
=> Mark RBTree.length as const

posix.mak
index.d is missing from the phobos.zip file
=> add index.d to zip file

index.d
1. add explanations that were completely missing for many modules
2. remove unnecessary/redundant verbage
=> add missing information to index

std/digest/crc.d
=> Improve documentation for std.digest.crc.crc32Of

std/internal/math/biguintcore.d, std/uni.d
Required by: https://github.com/D-Programming-Language/dmd/pull/4558
=> Supplemental fix for issue 5770

std/traits.d
Adds traits support for cent/ucent if supported.
=> Cent-ify std.traits.

std/typecons.d
- Add documented unittests.
- Add Params and Returns sections where appropriate.
=> Improve NullableRef documentation

std/typecons.d
- Add Params section.
- Simplify the complex wording.
- Add LREF to the See_Also entries.
- Change example into a documented unittest.
=> Improve WhiteHole documentation

std/range/package.d
Add all imports needed to run this unittest as a separate code.
Add detailed description of unittest.
Improved readablitity (removed slicing of static arrays and rearranged functions calls).
=> Improve unittest for std.range.cycle for better documentation.

std/container/rbtree.d
Fixes Issue 12702.
https://issues.dlang.org/show_bug.cgi?id=12702
=> const RedBlackTree.opBinaryRight

std/uni.d
It does not contain any unsafe code.
=> Mark the example in synopsis as @safe

std/bigint.d
=> correction to std.bigint doc

std/path.d
http://dlang.org/phobos/std_path.html#.isValidFilename
http://dlang.org/phobos/std_path.html#.isValidPath
Also upgraded coverage tests to 100%.
=> upgrade std.path.isValidFilename and isValidPath for Ranges

std/algorithm/sorting.d
Added multiSort to cheat sheet of std.algorithm.sorting
=> Added multiSort to cheat sheet of std.algorithm.sorting.

std/traits.d
I think it would be nice to have examples for `isAggregateType` and `isBuiltinType` as the documentation comments don't say much.
=> Usage examples: isAggregateType, isBuiltinType.

std/internal/processinit.d, std/range/primitives.d, std/regex/package.d
Fix some DDOC PHOBOSSRC broken links.
=> Fix PHOBOSSRC broken links

std/uni.d
It does not contain any GC-related operations.
=> Mark std.uni.isPowerOf2 as @nogc

std/concurrency.d
- to avoid circular module dependencies
=> replace shared static this with cas based lazy initialization

std/uni.d
It does not contain any unsafe operations.
=> Mark a unittest for std.uni.graphemeStride as @safe

std/conv.d
This is a reboot of https://github.com/D-Programming-Language/phobos/pull/3058 written by @BBasile which was mysteriously closed.
Forum discussion: http://forum.dlang.org/thread/me4njq%241cul%241@digitalmars.com
=> add std.conv.hexString() to replace core language hex strings

std/getopt.d
https://issues.dlang.org/show_bug.cgi?id=14526
=> fix Issue 14526 - GetOptException DDOC needs cleanup

std/csv.d
IMO it it not obvious how to get the content of a file to the csvReader
the new example shows how to do it
=> std.csv std.stdio.File.byLine example

std/path.d
The logic is simpler, too, but not as simple as I'd like. Also makes it `nothrow`.
=> Refactor std.path.expandTilde() to remove unnecessary gc allocations

std/conv.d
Depends on https://github.com/D-Programming-Language/druntime/pull/1181 for `_postblitRecurse`.
=> Use _postblitRecurse in emplaceRef to enable attribute inference

std/range/package.d
=> [trivial] Fix typo

std/range/package.d
Removes workaround for https://issues.dlang.org/show_bug.cgi?id=4706
=> std.range.chain() - remove bug workaround

std/string.d
http://dlang.org/phobos/std_string.html#.chompPrefix
unittests at 100%
=> Range-ify std.string.chompPrefix

std/string.d
=> Add std.string.detabber(), a range version of detab()

std/path.d
Still one loop left, arrgghh. Can't range-ify it yet because of dependencies.
=> Refactor std.string.relativePath() to use algorithms

std/string.d
http://dlang.org/phobos/std_string.html#.leftJustify
Unit tests at 100%.
=> Range-ify std.string.leftJustify() with leftJustifier()

std/path.d
1. Now accepts a forward range as input
2. Added unit tests to bring it to 100% coverage
3. Reduced gc allocations from N per invocation to 1. Can make it go to 0 with a pure way to malloc a buffer.
=> Range-ify std.path.globMatch()

std/internal/math/biguintcore.d
Also see https://github.com/D-Programming-Language/dmd/pull/4643
=> Remove a bad cast (Required for fixing issue 3841). Functional noop.

std/string.d
http://dlang.org/phobos/std_string.html#.rightJustify
=> Range-ify std.string.rightJustify() with rightJustifier()

std/math.d
These tests spotted an implementation issue of LDC.
Provided by KevinBrogan.
@KevinBrogan I find this test from your LDC contribution really good. It must go upstream. Thanks!
=> Add additional tests for std.math.sqrt()

std/math.d
their results are always of type  bool.
see previous failed PR (#3286)
=> fix several misleading ddocs and return types in the function isXXX()

std/random.d
revert erroneous fix for issue 11738, add a relevant unittest
=> reverted partialShuffle to match its documentation (issue 11738)

std/string.d
http://dlang.org/phobos/std_string.html#.center
=> Range-ify std.string.center() with centerJustifier()

std/string.d
Upgrade std.string.chop() to accept/return ranges.
100% unit test coverage.
http://dlang.org/phobos/std_string.html#.chop
=> Range-ify std.string.chop

std/path.d
Accept input and bidirectional ranges, too. Foundational to range-ify more of std.path.
Added unit tests for relaxed types.
=> accept more range types for std.path.*trimSeparators()

std/math.d
Slight syntactic changes in isNaN/isInfinite to allow CTFE evaluation when https://github.com/D-Programming-Language/dmd/pull/4674 is merged.
=> Make isNan and isInfinite available at compile time.

std/array.d
I added a unittest to provide an example of the sameHead function in phobos documentation (not quite sure if it's the correct way to do it)
Sorry for my bad english.
=> Add a use example to sameHead in array.d

std/socket.d
=> fix ddoc issues for UnixAddress

std/json.d
Add `pure`, `nothrow`, `@safe`, and `@nogc` where possible for methods, but not for the templated functions and methods.
=> Add attributes to methods in std.json.

posix.mak, win32.mak, win64.mak
nobody ever remembers the zip files when adding new files
=> add osmodel.mak to zips

std/path.d
http://dlang.org/phobos/std_path.html#.rootName
=> Range-ify std.path.rootName()

std/path.d
http://dlang.org/phobos/std_path.html#.driveName
=> Range-ify std.path.driveName()

std/path.d
http://dlang.org/phobos/std_path.html#.dirName
First use of `std.range.choose()` !!
=> Range-ify std.path.dirName()

std/path.d
http://dlang.org/phobos/std_path.html#.stripExtension
And removed some redundant unit tests.
=> Range-ify std.path.stripExtension()

std/path.d
http://dlang.org/phobos/std_path.html#.defaultExtension
=> Range-ify std.path.defaultExtension by adding defaultExt()

std/path.d
http://dlang.org/phobos/std_path.html#.setExtension
This is a reboot of https://github.com/D-Programming-Language/phobos/pull/2423 which was itself a reboot of https://github.com/D-Programming-Language/phobos/pull/2149
The recent addition of std.utf.byUTF makes this function much more convenient to write.
=> Range-ify std.path.setExtension by adding setExt()

std/path.d
This isn't quite complete, because the 3+ range chaining does not work. It does not work because other templates in std.path take arguments by `const R`, which is incorrect. Removing it causes several other functions to fail to compile. Essentially, the rest of std.path has to be range-ified for this to become fully functional.
=> Range-ify std.path.buildPath by adding chainPath()

std/path.d
http://dlang.org/phobos/std_path.html#.absolutePath
=> Range-ify std.path.absolutePath by adding toAbsolutePath()

std/path.d
http://dlang.org/phobos/std_path.html#.buildPath
=> rewrite std.path.buildPath in terms of chainPath()

std/range/package.d
I was surprised that the docs made it very difficult to figure how tee is supposed to be used.
=> Improve docs for tee

std/range/package.d
https://issues.dlang.org/show_bug.cgi?id=14660
=> std.range.choose() - add Bugs section

std/path.d
http://dlang.org/phobos/std_path.html#.relativePath
This means that relativePath is no longer CTFE'able due to a bug in std.range.choose() which is not CTFE'able. I don't think that actually matters, because it is usually used with getcwd() which is not CTFE'able, either.
=> Range-ify std.path.relativePath by adding toRelativePath()

std/path.d
http://dlang.org/phobos/std_path.html#.pathSplitter
Now accepts ranges as input.
=> Range-ify std.path.pathSplitter()

index.d
the next first step in removing stream from phobos
https://github.com/D-Programming-Language/dlang.org/pull/1002
=> remove index of socketstream

posix.mak
Competes with #3380, pull one or the other.
=> Fix makefile to do what ./configure normally would do for zlib

std/path.d
http://dlang.org/phobos/std_path.html#.buildNormalizedPath
buildNormalizedPath is rewritten to use toNormalizedPath internally. Most of the unit tests were moved to toNormalizedPath.
=> Range-ify std.path.buildNormalizedPath by adding toNormalizedPath()

std/windows/registry.d, std/windows/syserror.d
https://issues.dlang.org/show_bug.cgi?id=14288
https://issues.dlang.org/show_bug.cgi?id=14289
=> Better std.windows.registry exceptions

std/experimental/logger/core.d
* file is not completely the same on win and posix
=> logger clean up

std/experimental/logger/core.d, std/experimental/logger/filelogger.d, std/experimental/logger/multilogger.d
* random filenames were not the best idea
=> logger cleanup2:

std/process.d
https://issues.dlang.org/show_bug.cgi?id=14696
=> add comment about Bugzilla 14696

std/traits.d
This pull adds a template to get a user-defined attribute of a specific type from a symbol.
=> Add getUDA template

std/file.d
Requires https://github.com/D-Programming-Language/phobos/pull/3417
http://dlang.org/phobos/std_file.html#.read
=> Range-ify std.file.read()

std/file.d
Also:
1. combined common code in read() implementation
2. updated Ddoc comments
http://dlang.org/phobos/std_file.html#.write
=> Range-ify std.file.write(), readText() and append()

std/file.d
http://dlang.org/phobos/std_file.html#.rename
=> Range-ify std.file rename() and exists()

std/digest/sha.d
See https://github.com/D-Programming-Language/phobos/pull/3233
=> Remove static ctor in template to avoid issue with cycles.

std/datetime.d
Also removed pointless code that checked if Linux system APIs threw D non-recoverable exceptions. This is not a practice that we should endorse.
=> std.datetime - start using ranges

std/exception.d
https://issues.dlang.org/show_bug.cgi?id=14685
=> [REG2.067] Issue 14685 - Silent incorrect behavior with enforce and custom exception

std/net/curl.d
https://issues.dlang.org/show_bug.cgi?id=14712
=> fix Issue 14712 - GIT HEAD : std.net.curl regressions

std/algorithm/sorting.d
IIRC, this was some sort of joke.
=> std.algorithm.sorting: Remove dead YouTube link from schwartzSort DDoc

std/string.d
http://dlang.org/phobos/std_string.html
=> Range-ify std.string.strip and stripRight()

std/file.d
http://dlang.org/phobos/std_file.html#.setTimes
=> Range-ify std.file getTimes(), getTimesWin(), setTimes()

std/uni.d
https://github.com/D-Programming-Language/phobos/commit/1b6b381fa42142a258a521f1aefc1360dccacc0f#commitcomment-11860337
=> std.uni: Remove stray std.stdio import

std/typecons.d
Issue 1238: https://issues.dlang.org/show_bug.cgi?id=1238
This request fixes [Issue 14405](https://issues.dlang.org/show_bug.cgi?id=14405) which was introduced by #1414
=> Add workaround for issue 1238

std/range/package.d
https://issues.dlang.org/show_bug.cgi?id=14744
=> Workaround for Issue 14744 - std.range DDox page corrupted

std/algorithm/comparison.d, std/range/package.d
Required by: https://github.com/D-Programming-Language/dmd/pull/4790
=> Supplemental fix for issue 14747 - remove unreachable statements

std/digest/sha.d
Makes branch prediction work better this way, rather than indirection. Double plus good!
Requires https://github.com/D-Programming-Language/druntime/pull/1311
=> std.digest.sha remove static constructor

std/parallelism.d
The original had it inside a template, when the ctor has no dependencies on the template type. Also avoids problems with duplicate copies of the template instantiation, including 0.
=> std.parallelism: move static constructor out of template

std/format.d
minor refactor to save a bit of code
=> std.format - better formatChar()

std/random.d, std/utf.d
in order to reduce dependencies and bloat. Reduces size of "hello world" by 4K.
Requires https://github.com/D-Programming-Language/druntime/pull/1309
=> remove unnecessary uses of std.format

posix.mak
see https://github.com/D-Programming-Language/druntime/pull/1317
=> adapt druntime paths for fix to Issue 11414

std/algorithm/mutation.d
The diff is a bit messy, but the change is essentially to remove the `isOutputRange!(Range2, ElementType!Range1)` condition from the template to allow `char[]` and `wchar[]` targets (they aren't output ranges). The check is now only at the end when we try to use the non-array path.
https://issues.dlang.org/show_bug.cgi?id=13650
=> Fix Issue 13650 - Cannot copy (w)char[] into (w)char[]

std/meta.d, std/typetuple.d
See forum discussion http://forum.dlang.org/post/mnhfhs$2b9o$1@digitalmars.com
This is an alternative to https://github.com/D-Programming-Language/phobos/pull/3487
=> Rename AliasSeq to AliasTuple

std/traits.d
This builds on @Hackerpilot's previous PR for [CopyStorageClasses](https://github.com/D-Programming-Language/phobos/pull/2782). It adds a template that will only copy the "constness" of a type, leaving it un-`shared` even if the source type is `shared`. This is a companion PR to https://github.com/D-Programming-Language/phobos/pull/3442.
=> Add CopyConstness

std/container/array.d
there was a bug workaround that works know
+ more testing
=> std.container.array remove workaround

std/file.d, std/windows/syserror.d
=> Range-ify: std.file chdir and others

std/meta.d, std/typetuple.d
See http://forum.dlang.org/post/mo8jrn$1kro$1@digitalmars.com
=> Revert AliasTuple back to AliasSeq

etc/c/odbc/sql.d
Please let me know of more instructions, thanks.
=> Add ODBC linking instructions

std/algorithm/sorting.d, std/json.d, std/path.d, std/uni.d
Follow-up to the discussion:
http://forum.dlang.org/post/rvaguhviuldknnqktkbq@forum.dlang.org
This PR targets the correct branch (stable).
Previous PR: https://github.com/D-Programming-Language/phobos/pull/3439
=> 2.068 renames

posix.mak
This reverts commit a928a21dff5b4dbc70a69220ca8a53d846a02851, reversing
changes made to 7ca4060b721f2a2b886f60b6e1a85af63e5b5341.
=> Revert "Merge pull request #3379 from andralex/build-per-package"

std/file.d
analogous to changes made to chdir()
=> Range-ify std.file rmdir()

std/typecons.d
https://issues.dlang.org/show_bug.cgi?id=14890
=> [REG 2.068.0-rc1] Issue 14890 - Can not construct a RedBlackTree of Tuples

std/functional.d
some bugs where resolved, so some tests could be enabled
remove outcomment code last modifed 2009
=> std.functional housekeeping

win64.mak
=> split std.algorithm unittest compilation

std/array.d
From the discussion: https://github.com/D-Programming-Language/phobos/pull/3561#discussion_r37432507
Ping: @schveiguy
=> Supplemental fix for issue 14925

std/net/curl.d
- it's unlikely that the non-usage of
OPTIONS body changes anytime soon
=> remove data argument from options

std/range/package.d
- example unittests must directly follow the declaration
=> fix doc generation

std/datetime.d, std/exception.d, std/experimental/logger/core.d, std/file.d, std/process.d, std/socket.d, std/zip.d
Some of these are a bit old, since I haven't been on top of this as I should have been, but we haven't been deprecating a lot these days, so the list isn't all that long.
=> Move along some of the deprecations.

std/internal/cstring.d
https://issues.dlang.org/show_bug.cgi?id=14980
=> [REG2.068] Issue 14980 - getAddressInfo(null) broken

std/zlib.d
https://issues.dlang.org/show_bug.cgi?id=14777
=> fix Issue 14777 - 0 is not the initial value for std.zlib.adler32

std/socket.d
High-level unittest only. Real fix in #3612 
https://issues.dlang.org/show_bug.cgi?id=14980
=> std.socket: Add test for issue 14980

std/net/curl.d
- split headers and body
- partly parse request header for content-length
and handle 100-continue
- return headers and body separately
- fix missing content-length in patch method
=> properly decode content-length

std/random.d
some examples could be moved unittests
=> std.random unittest docs

std/socket.d
* One example could be moved to unittest doc
=> std.socket unittest doc

etc/c/sqlite3.d
https://issues.dlang.org/show_bug.cgi?id=14798
https://github.com/D-Programming-Language/phobos/pull/2574#commitcomment-12990919
https://github.com/D-Programming-Language/phobos/pull/184#commitcomment-12991102
=> etc.c.sqlite3 declaration fixes

std/algorithm/searching.d
Missed these two in the last PR.
=> [dox] Add Params:, Returns:, to minCount and minPos

std/file.d
move some examples from comments to unittest
=> std.file unittest doc example

std/range/primitives.d
https://issues.dlang.org/show_bug.cgi?id=15046
Trivial ddoc unittest fix.
=> [REG2.068] Issue 15046 - isForwardRange documentation is documenting issue 14544

std/algorithm/mutation.d, std/file.d
Reboot of #3509 now with a unittest.
=> [REG master] Issue14817 std.algorithm.copy/std.file.copy conflict

std/uni.d
this PR removes a lot of comment examples and replaces them with unittest examples
=> std.uni unittest examples

std/process.d
Requires https://github.com/D-Programming-Language/druntime/pull/1388
=> fix Issue 15076 - Get ID of current thread

std/experimental/logger/core.d
used to work. This PR fixes that
=> std.experimental.logger: structs and classes with @system toString methodes did not

std/experimental/logger/core.d
* removed some debug statements
* fixed TODO (because of druntime fix)
=> logger housekeeping

std/path.d
* a lot of comment example could be moved to unittest examples
* removed unittest duplication due to move
=> std.path unittest doc

std/uuid.d
https://gist.github.com/9il/c07e04b3cb1dbe13642f
```
$ ldmd2 -O -inline -release -boundscheck=off -m32 -run bench.d
4 secs, 32 ms, 829 μs, and 4 hnsecs (old)
2 secs, 659 ms, 94 μs, and 9 hnsecs
$ ldmd2 -O -inline -release -boundscheck=off -run bench.d
2 secs, 950 ms, 126 μs, and 5 hnsecs (old)
1 sec, 985 ms, 773 μs, and 4 hnsecs
```
```
$ dmd -O -inline -release -boundscheck=off -m32 -run bench.d
3 secs, 534 ms, 132 μs, and 1 hnsec (old)
2 secs, 741 ms, 926 μs, and 5 hnsecs
$ dmd -O -inline -release -boundscheck=off -run bench.d
3 secs, 211 ms, 136 μs, and 5 hnsecs (old)
2 secs, 448 ms, 48 μs, and 1 hnsec
```
=> update UUID hash function

std/string.d
lineSplitter used to accept struct and classes with an alias this to a string
returning function.
This PR add that feature again.
https://github.com/D-Programming-Language/phobos/pull/3694
=> std.string.lineSplitter_string_alias_fix

std/string.d
make stripLeft accept types with an alias this to a string member(function)
=> std.string.stripleft_string_alias_fix

std/string.d
make stripRight accept custom types with alias this to string
member(functions)
=> std.string.stripRight_string_alias_fix

CONTRIBUTING.md, etc/c/odbc/sqlext.d, etc/c/odbc/sqltypes.d, etc/c/odbc/sqlucode.d, std/algorithm/iteration.d, std/container/array.d, std/conv.d
http://forum.dlang.org/help#canonical
=> Use canonical links to forum.dlang.org

std/string.d
make detab and detabber accept custom types with an alias this to a string
member of member function
=> std.string.detab_alias_fix

std/experimental/allocator/building_blocks/bitmapped_block.d
https://issues.dlang.org/show_bug.cgi?id=15196
=> Issue 15196 - Fix memory leak in bitmapped-block unit tests

std/experimental/allocator/building_blocks/allocator_list.d
https://issues.dlang.org/show_bug.cgi?id=15197
=> Issue 15197 - Allow allocator_list to work with allocators that don't have 'expand()'

std/string.d
make entab and entabber accept custom types with an alias this to a string
member of member function
@MartinNowak I created this against master as the 2.069 beta was already created. Input?
=> std.string.entab_alias_fix

std/algorithm/iteration.d
https://issues.dlang.org/show_bug.cgi?id=15133
=> fix Issue 15133 - Error message is incomprehensible

std/array.d, std/concurrency.d, std/format.d, std/regex/internal/parser.d, std/regex/package.d, std/stdio.d, std/uni.d
https://issues.dlang.org/show_bug.cgi?id=15208
=> fix Issue 15208 - Eradicate all uses of "Enforcement failed" in Phobos

std/string.d
make indexOf consistend and accept auto ref ranges
=> std.string.indexOf_rangifed_fixup

std/net/curl.d
https://trello.com/c/YwsVrCxj/114-fix-test-race-condition-in-phobos-std-net-curl
=> Fix test race condition in phobos std.net.curl

std/file.d, std/process.d, std/windows/registry.d
Requires https://github.com/D-Programming-Language/druntime/pull/1402
=> Remove declarations already declared by the new Windows headers

std/datetime.d
This moves all of the private, helper templates for isTimePoint into
isTimePoint (which reduces code) and cleans up their implementation a
bit. The tests have also been improved to actually check types which are
supposed to be false with isTimePoint and the implementation adjusted
accordingly (previously, they failed to compile with isTimePoint rather
than resulting in false).
The checks for TickDuration have been removed in the process, since
we're getting rid of it. No code will break from that, since all it
means is that a type which passes isTimePoint no longer needs to work
with TickDuration. If it does work with TickDuration (as the time point
types in std.datetime will until it's been fully removed), then it will
just continue to work as it has.
This commit also improves the …
=> Code reduction and clean-up for std.datetime.isTimePoint.

std/getopt.d
Adopted from https://github.com/D-Programming-Language/phobos/pull/3615
=> std.getopt: Documentation fixes and improvements

std/bitmanip.d
Required for https://github.com/D-Programming-Language/dmd/pull/5189
=> Avoid strict equality check on assert message

std/internal/math/biguintcore.d
And eliminate unused parameter.
=> biguintcore: eliminated unnecessary divides

std/internal/digest/sha_SSSE3.d
Gets rid of unnecessary allocation, too.
=> sha_SSSE3.d: small optimization

std/string.d
make soundexer take custom types again that have an alias this to string
=> std.string.soundexer_alias_string_fix

std/string.d
make strip take custom types again that have an alias this to string
test stuff
=> std.string.strip_alias_string_fix

std/string.d
make stripLeft take auto ref custom types with to string alias
forgot a {
=> std.string.stripLeft_alias_string_fix

std/string.d
make capitalize take custom types again that have an alias this to string
=> std.string.capitalize_alias_string_fix

std/string.d
make stripRight take auto ref custom types with to string alias
=> std.string.stripRight_alias_string_fix

std/string.d
- use auto ref to avoid expensive copies
- leave the overloads undocumented
- move them below the real implementations
- use explict template instantiation to avoid casts
- had to factor out LineSplitter b/c of fwd
reference complaints by the compiler
=> consistently handle StringTypeOf overloads

std/typecons.d, std/variant.d
https://issues.dlang.org/show_bug.cgi?id=15039
Fixing limitations in `std.typecons.ReplaceType` will naturally fix the issue.
=> Issue 15039 - Algebraic cannot store a Typedef along with Typedef'ed type

std/regex/package.d
The current example for std.regex.replaceAllInto does a dup of the sink's data, thereby undermining the whole objective of the sink and of the *Into function i.e. to avoid extra allocations. The proposed patch provides an example which makes better use of the sink.
=> Give a better example for std.regex.replaceAllInto

std/string.d
make column take custom types again that have an alias this to string
=> std.string.column_alias_string_fix

std/traits.d
Before there wasn't any example section.
=> Added unittest docs to std.traits.isNarrowString

std/string.d
=> std.string.splitLines_unittest_example

std/conv.d
* The parsing code is now executed at compile-time even if `octal` is used in a runtime context.
* No longer is a parsing function generated for every unique instantiation of `octal`.
* Fixed oversight where `uint` and `ulong` were not automatically deduced as intended... although I don't think this patch fixes all signedness issues.
* Made public undocumented helper functions and templates `private`.
This also serves to remove a bad precedent from Phobos: using templates with nullary functions to "do stuff at compile-time", which is a mistake.
=> Fix std.conv.octal issues

std/random.d
https://issues.dlang.org/show_bug.cgi?id=15238
=> fix Issue 15238 - Heisenbug running std.random unittests

std/string.d
=> std.string.capitalize_unittest_example

changelog.dd
Take number three
@MartinNowak @CyberShadow
=> Mention documentation improvements

std/typecons.d
[Issue 15168 – [REG2.068.0] std.variant.Algebraic interacts badly with string alias this sub-types](https://issues.dlang.org/show_bug.cgi?id=15168)
=> fix Issue 15168 - ReplaceType broken for string sub-types

std/experimental/logger/core.d, std/socket.d, std/stdio.d, std/utf.d
Required by: https://github.com/D-Programming-Language/dmd/pull/3416
=> Fix imports

std/string.d
* added unittest example
* removed unnecessary function annotations
=> Add unittest example to std.string.wrap

std/traits.d
=> Allows std.traits.getUDAs to filter attributes by template type.

std/string.d
* added unittest doc examples for center
=> std.string.center_unittest_example

std/string.d
* added unittest doc examples for rightJustify
=> std.string.rightJustify_unittest_example

std/string.d
added unittest doc examples for leftJustify
=> std.string.leftJustify_unittest_example

std/conv.d
I've made successive simplifications of the complicated helper code around emplace. Last commit fixes the actual bug.
=> Issue 15313 - std.conv.emplace cannot initialize const objects 

std/string.d
* added unittest doc examples for indexOf lastIndexOf
=> std.string.lineSplitter_unittest_example

std/file.d
https://github.com/D-Programming-Language/phobos/pull/3690#issuecomment-156877602
=> std.file: Update dirEntries documentation regarding path==""

std/conv.d, std/file.d, std/stdio.d, std/string.d
Also see #4689 for reducing the number of false positives. There are still some left, will work on that.
Can we add ddoc warning checks to the auto-tester please? At least prevent it from increasing.
=> Fixed some doc warnings

std/file.d
=> Fix issue 15319 - broken import in std.file.copy

std/algorithm/iteration.d, std/bitmanip.d, std/conv.d, std/system.d, std/traits.d, std/typecons.d
This is a companion PR to <https://github.com/D-Programming-Language/dlang.org/pull/896>. Do not pull without that one.
=> update links to spec pages

std/experimental/allocator/common.d, std/experimental/allocator/mallocator.d
note that no additional unittest is needed since I annotated those which already exist with @nogc to force the checking.
=> fix issue 15409 - Mallocator cant be used in @nogc code

std/json.d
+ fix, other ddocs, use standard section to indicate what's thrown
=> fix issue 15336, opIn undocumented for JSONValue

std/stdio.d
https://issues.dlang.org/show_bug.cgi?id=15429
=> fix issue 15429 - [std.stdio] Broken link in documentation

std/algorithm/internal.d, std/container/rbtree.d, std/file.d, std/net/curl.d, std/parallelism.d, std/process.d, std/random.d, std/range/package.d, std/string.d, std/uni.d
Required by: https://github.com/D-Programming-Language/dmd/pull/2305
=> fix property enforcement

std/datetime.d
This gets us another step closer to being able to deprecate `TickDuration`.
=> Deprecate the non-benchmarking uses of TickDuration in std.datetime.

std/algorithm/sorting.d
Bug unittests should go in their own blocks.
=> Fix mistakes in pull #3864

std/string.d
* added unittest doc examples for indexOf lastIndexOf
=> std.string.index_unittest_examples

std/utf.d
The overload sets `stride` and `strideBack` now have one entry each. This makes a big difference for the readability of std.utf's docs.
Further changes that would improve the situation:
* These two overload sets are big - collapse them into two overloads per overload set, with and without the index parameter
* Add examples
* (Implement `decodeBack`!)
I'll leave these to someone with deeper UTF knowledge.
=> Consolidate documentation for std.utf.stride[Back]

std/algorithm/sorting.d, std/array.d, std/container/rbtree.d, std/container/slist.d, std/conv.d, std/datetime.d, std/digest/digest.d, std/digest/md.d, std/digest/ripemd.d, std/digest/sha.d, std/encoding.d, std/exception.d, std/experimental/logger/core.d, std/file.d, std/functional.d, std/internal/cstring.d, std/net/isemail.d, std/parallelism.d, std/path.d, std/process.d, std/range/package.d, std/regex/package.d, std/traits.d, std/uuid.d, std/xml.d, std/zip.d
As per the discussion here: http://forum.dlang.org/post/n4vhoa$21t2$1@digitalmars.com
=> Changed "Examples:" in Ddoc to "Example:"

changelog.dd
Add missing change log entry for #3872
=> Add changelog entry for #3872

std/file.d, std/net/curl.d
Required by: D-Programming-Language/dmd#3416
=> Fix for issue 12359

std/experimental/logger/package.d
* Bastiian Veelo spelling error from forum
=> std.logger.minor_doc_fix

std/experimental/logger/filelogger.d, std/experimental/logger/package.d
* change default FileLogger LogLevel to all
* fix minor doc error
=> std.logger_consolidate_default_loglevel

std/experimental/logger/package.d
=> Documentation fixes.

std/algorithm/iteration.d
=> Mention "flatten" in docs for std.algorithm.iteration.joiner

std/internal/test/dummyrange.d
This was separated out of an upcoming PR of mine.
=> Added ReferenceBidirectionalRange to std.internal.test.dummyrange

std/algorithm/iteration.d
These two showed up in `dmd -vtls`.
=> Remove TLS variables from ReduceSeedType

posix.mak, win32.mak, win64.mak
- fix Issue 15222 - std.experimental omitted from phobos zip file
- avoids outdated manifest lists
=> recursively create zip file

std/experimental/ndslice/slice.d
https://issues.dlang.org/show_bug.cgi?id=15549
=> fix Issue 15543

std/string.d
There's been a few forum threads about this and another question on irc just now so we might as well just follow user expectations.
=> publically import empty too because users expect it

std/algorithm/mutation.d, std/conv.d, std/experimental/allocator/package.d, std/typecons.d
Depends on and complements <https://github.com/D-Programming-Language/druntime/pull/1403>.
=> TypeInfo.init -> TypeInfo.initializer

std/experimental/allocator/building_blocks/free_list.d
Root PR - https://github.com/andralex/phobos/pull/22 
ping @andralex
=> [allocators] add approxMaxNodes for shared free list

std/algorithm/sorting.d
* There was an unlisted bug - if `nth > r.length` the doc says "has no effect" but what happened was a range violation.
* Eliminate a redundant test
* Add special casing for the "max" case. Saves a whole lot of work and could happen during the algorithm if the user specifies a large-ish `nth` (e.g. median).
=> topN: define behavior for nth >= r.length, improve speed

std/conv.d
Some ideas inspired by Andrei's optimization talks:
1. fast path for one digit conversions
2. reduce number of expensive divides by one for each conversion
3. uints are faster than ulongs
4. uints are faster than bytes
5. use `=void` for unnecessary initializations
6. schedule `--i` to avoid data dependency
Worthwhile due to the ubiquity of these sorts of conversions.
=> std.conv: improve toChars() performance

std/concurrency.d, std/csv.d, std/exception.d, std/getopt.d, std/process.d, std/regex/internal/ir.d, std/socket.d, std/uri.d, std/utf.d
As per https://github.com/D-Programming-Language/druntime/pull/1413#issuecomment-149167301...
=> Standard exception constructors

std/algorithm/iteration.d
This fixes [Phobos issue #15480: std.algorithm.iteration.map not accepting multiple lambdas](https://issues.dlang.org/show_bug.cgi?id=15480).
The solution is rather hackish, due to the need to work around [DMD issue #5710: cannot use delegates as parameters to non-global template](https://issues.dlang.org/show_bug.cgi?id=5710).
This PR is intended to supersede [PR #3963](https://github.com/D-Programming-Language/phobos/pull/3963) by @tirkarthi .
=> Fix Phobos issue 15480

std/container/slist.d
https://issues.dlang.org/show_bug.cgi?id=15659
=> Fix Issue 15659 - fix crash in SList.clear()

std/stream.d
Another bit of code that depends on import hiding. Needed for https://github.com/D-Programming-Language/dmd/pull/5445
=> fix import shadowing

std/regex/internal/ir.d
This is blocking https://github.com/D-Programming-Language/dmd/pull/5445
=> conform to new import lookup rules

std/stream.d
Another fix needed for: https://github.com/D-Programming-Language/dmd/pull/5445
=> fix lookup of core.stdc.stdio.remove()

std/experimental/ndslice/iteration.d, std/experimental/ndslice/package.d, std/experimental/ndslice/selection.d, std/experimental/ndslice/slice.d
https://issues.dlang.org/show_bug.cgi?id=15532
https://issues.dlang.org/show_bug.cgi?id=15540
Mir PR https://github.com/DlangScience/mir/pull/4
Forum discussion: http://forum.dlang.org/thread/mailman.3392.1452142075.22025.digitalmars-d@puremagic.com
First four commits fix unittests.
=> Issue 15532 & fix Issue 15540

std/container/binaryheap.d, std/container/dlist.d, std/container/slist.d
Hey all,
I just had a rough time finding common structures like queue, stack, priority queue in phobos and after a long search I realized that you everything is already included. Hence for future users like me which blindly enter "dlang queue" in google, I propose to add some keywords with common terms or usages of these data structures.
This PR is in no way complete (ideas and suggestions are more than welcome), but I guess this should be a small step in the direction of user friendliness ;-)
If it finds consensus, I would also be happy to add more examples - especially `dlist` is pretty sparse.
=> hotlink common collection keywords for user search

std/experimental/allocator/package.d
See https://github.com/D-Programming-Language/phobos/pull/4022#commitcomment-16474681
=> Fix spacing around equals

std/range/package.d, std/regex/package.d
=> convert docstring examples to unittests [part 3]

std/meta.d
=> added staticSort

std/experimental/ndslice/selection.d
https://github.com/DlangScience/mir/pull/13
=> [ndslice] fix issues 15714 and 15715

changelog.dd
The change log is as much a marketing document as it is a historical one. These changes should be promoted in order to get people to download this new version.
=> Document improvements in the Change Log

etc/c/zlib/gzlib.c, std/zlib.d
https://issues.dlang.org/show_bug.cgi?id=15457
=> fix Issue 15457 - Symbol Undefined __lseeki64

std/file.d
=> Don't allocate more than upTo bytes in std.file.read

std/algorithm/sorting.d
Hey I just noticed that there is no way to check for strict ordering with ranges.
This adds a bit of redundant code, it would have been much nicer and intuitive to use the alias `a < b` for strict ordering and `a <= b` (default) for non strict ordering, but I assume this isn't so easy to change without breaking code.
Was this choice made to save performance by saving the extra `=` comparison?
=> add isStrictlySorted for ranges

std/algorithm/sorting.d
This reverts commit 1f008535131910849948aa140afd667b90f00227, reversing
changes made to 580d72f3b30cee31996d6b170c39b987a02aabc9.
=> Revert "Merge pull request #4025 from greenify/is_strictly_sorted"

std/socket.d
splitted failing #4049 into two parts - this is just std.socket
=> std.socket: Examples to unittest [part 6]

std/regex/internal/ir.d
=> [std.regex] Allow nextChar to be inlined by DMD

std/conv.d
1. Move `emplace!Class(Class*)` documented unittest to correct overload & update description.
2. Add actual example for `emplace!Class(void[])`.
3. Use ddoc precondition blocks.
[Existing docs](www.dlang.org/phobos/std_conv.html#.emplace) (see 3rd overload for `emplace!Class(void[])`).
=> Fix std.conv.emplace docs

std/bitmanip.d
This is necessary because of type qualifier conversion rules (struct with and without pointes are differents) and the current implementation would be incompatible with a precise GC (that we don't have, but may at some point).
=> Change taggedClassRef and taggedPointer so that the bitfield appear as a void* in the parent

posix.mak
Analogous to the one in druntime's posix.mak
=> add gitzip target

std/variant.d
https://issues.dlang.org/show_bug.cgi?id=15827
=> Fix Issue 15827 -  std.variant.Variant can not be initialized with some struct

std/typecons.d
Trivial. It's more lightweight.
=> Use __traits(identifier) instead of stringof + startsWith in std.typecons.Proxy

std/algorithm/mutation.d
Should now be easier to read and clearer.
See commit message for details.
=> Improve docs for std.algorithm.mutation.move & related functions

std/file.d
https://issues.dlang.org/show_bug.cgi?id=15865
Stat the target fd and check for sameness before truncating the file.
=> fix Issue 15865 - std.file.copy(from,to) deletes the file if from and to specify the same file

std/xml.d
casting `super` to non-const does not work when trying to call base class implementation of a function.
=> fix issue 14966: misuse of super

std/uni.d
=> [Issue 13422] std.ascii has isAlphaNum but std.uni doesn't

std/regex/internal/backtracking.d
Going super-sonic with yet another update:
This cuts down on redundant backtracking on most real-world inputs. Also neatly replaces horribly limited infinite trackers state variable that sole task was preventing infinite empty loops.
=> [std.regex] Add rolling trace filter to backtracking engine

std/algorithm/comparison.d, std/algorithm/mutation.d, std/array.d
remove dependency from `std.range`
=> Fix imports in std.algorithm

std/regex/internal/backtracking.d
Finally generate optimal source code for small codepoint sets. Large improvement for these cases.
=> [std.regex] Faster compile-time regex

win32.mak, win64.mak
Arrange & rename target names to increase maintenance ability.
=> Refactor win32 and 64 make files

std/uni.d
With the test character `dchar a = '.';` with one million calls:
```
isPunctuation		79 ms, 385 μs, and 4 hnsecs
isPunctuation2		7 ms, 58 μs, and 9 hnsecs
```
=> std.uni.isPunctuation: significant performance increase for ASCII

std/encoding.d
=> Removed commented out, undocumented function

std/regex/package.d
Add function to split a string with a regex pattern but keep the matches
=> [Issue 15797] Add std.regex.splitterWithMatches

std/array.d, std/range/primitives.d, std/regex/package.d
Fixes some import deprecations that show while building phobos tests.
There are still other import problems but they are trickier to solve.
=> Fix some imports

std/datetime.d
Merge pull request #4196 from CyberShadow/pull-20160413-210023
std.datetime: Update Windows time zones for KB3148851
=> Cherry-pick commtis in #4196 from master to stable branch

std/regex/internal/ir.d, std/regex/internal/parser.d, std/regex/package.d
The oldest enhancement request for std.regex...
=> Fix issue 2104 - escape function for regular expressions

std/range/package.d
They perform the same optimizations.
=> TRIVIAL: reuse popFrontN for stride

CONTRIBUTING.md
=> update links to dlang

std/csv.d
I fixed two grammatical errors and added parentheses in one place to make text easier to understand.
=> Minor improvements to std.csv docs

std/range/package.d
This is by far the easiest and least ugly solution. I can't think of any instance where someone would actually rely on `length` being `size_t`.
=> Clean up iota.Result.length

std/experimental/ndslice/internal.d, std/experimental/ndslice/slice.d
PR is simple, but it has a lot of style fixes.
This is the last synchronization from the Mir library because the basic API become stable.
ndslice will be removed from Mir when LDC get DMD front-end 2.072.
=> Add ptr method for Slice

changelog.dd
=> tidy up changelog.dd

std/range/package.d
See https://issues.dlang.org/show_bug.cgi?id=9082
I agree with Walter that we need less one liner functions and more examples.
=> Add informative example to roundRobin

std/traits.d
The implementation of MemberFunctionsTuple didn't quite understand how covariance can be true both ways. It has now been enlightened.
=> Fix 15920 - std.traits.MemberFunctionsTuple gives a wrong result

std/experimental/ndslice/iteration.d, std/experimental/ndslice/package.d, std/experimental/ndslice/selection.d, std/experimental/ndslice/slice.d
I had a quick pass through ndslice's docs - I should start to do this every week ;-)
Ping @9il
=> std.experimental.ndslice: improve docs

std/string.d
One step towards range-ification.
=> Modernize isNumeric

std/experimental/ndslice/slice.d
@9il 
#4237 forgot the changelog entry - moreover I added the grammatic fix pointed out by @tsbockman and reindented the lines (it was > 120).
=> [ndslice]: doc fix follow-up

std/net/curl.d
It's not modifying anything...
=> toString() on HTTP.StatusLine should be const

changelog.dd
added changelog entry for #4221
=> [changelog entry] std.algorithm.searching.{min,max}Element

std/experimental/ndslice/slice.d
ping @9il - I added a changelog entry to show the fancy new allocation support in ndslice.
It got a bit bigger, so I put the unittest in `package.d` to show them - I think they can be quite useful to starters too?
Moreover two small fixes:
- `T` can be inferred for makeSlice when used with an init element (we do this for `slice` too)
- `slice` didn't allow an `init` - this is confusing for the user (see [discussion at mir](https://github.com/libmir/mir/issues/202))
=> [ndslice] allow init elem for slice()

std/encoding.d
* followup to bom2
https://github.com/dlang/phobos/pull/3880
=> move typecons import to top of encoding

std/functional.d
=> Fix typo in memoize summary description

std/file.d
It's actually not a bug because it's documented (see http://man7.org/linux/man-pages/man2/write.2.html). As a workaround, this limit is specified in append() and write() ddoc.
Additionally an input contract's been added to detect clearly the error during any testing phase.
=> fix issue 11791 - std.file.write failed to write huge files

std/uni.d
When profiling this function using the plain text version of Pride and Prejudice located [here](https://www.gutenberg.org/cache/epub/1342/pg1342.txt), the results are as follows:
before the changes:
```
result	52 ms, 127 μs, and 8 hnsecs
```
after
```
result	35 ms, 958 μs, and 4 hnsecs
```
=> Add ASCII case for string versions of std.uni.toLower/toUpper

std/algorithm/iteration.d
This addresses some concerns/confusion brought up in [this SO question](http://stackoverflow.com/questions/33779822/unable-to-call-each-on-a-lockstep-range-containing-2-or-more-ranges).
The first is that `each` will accept a 2-arg lambda, but assumes that the first is for an index and doesn't pass by ref. This means that if you try to pass two args by ref (e.g. using `lockstep`), one will not reference the source.
The second is that `each` cannot iterate with an arbitrary number of variables (e.g. iterating over a range produced via `lockstep`/`zip` with >2 args). This adds support for such a scenario, but is a bit messy (involving a mixed-in generated foreach loop), and doesn't work for a templated `opApply` (cannot determine the arity).
I can break apart the PR if people like the first …
=> Improve std.algorithm.iteration.each

std/uni.d
Separated into three disparate commits:
* remove analogs to `std.math.nextPow2` and `std.math.trucPow2` to keep DRY
* remove custom analog of `std.algorithm.comparison.equal`
* fix doc strings on functions and make several undocumented public functions package
=> Clean up of std.uni

std/datetime.d
Merge pull request #4317 from BBasile/fix_wtz
hotfix (tester) - Easter Island & Haiti Windows time zone
=> Cherry-pick commtis in #4317 from master to stable branch

std/experimental/ndslice/slice.d
This allows passing rvalues directly.
@9il
=> Remove ref from the Slice.this parameters

std/string.d
Also removed commented out code
=> Add example to std.string.toStringz

std/range/interfaces.d, std/range/package.d, std/range/primitives.d
I was always confused by this weird error. Let's remove the placeholder!
=> remove placeholder copyright

std/string.d
Surprise, surprise, I had to special case for auto-decoding so the performance doesn't drop off the face of the earth.
Also, had to correct the template constraint for `icmp`.
=> Range-ified std.string.isNumeric

std/algorithm/iteration.d, std/algorithm/mutation.d, std/algorithm/searching.d
Fixes three files in std.algorithm
=> Partial Fix for Issue 16073

std/algorithm/searching.d
For find a string within a string, std.algorithm.searching.find was
unnecessarily slow. The reason is it created intermediate slices. A
naively written nested-for-loop implementation was a few times
faster.
For random access ranges (which strings are) this uses an index based
algorithm, which does not need to create an intermediate slice. Speed
is now comparable to the nested-for-loop implementation even in rather
pathological cases.
This might help with [issue 9646](https://issues.dlang.org/show_bug.cgi?id=9646).
The benchmark used for speed measurements can be found in [its own repository](https://github.com/qznc/find-is-too-slow).
=> Improve speed of find for random access needles (strings)

std/file.d
Way too much going on there for a documentation example.
http://forum.dlang.org/post/ixpujamnyhguuqiflvom@forum.dlang.org
=> std.file: Simplify readText example

std/algorithm/sorting.d
At least make the schwartzSort() safe.
Partial fix for https://issues.dlang.org/show_bug.cgi?id=13054
=> make the Schwartz @safe

std/algorithm/sorting.d
That does it for std.algorithm
=> Partial Fix for Issue 16073 (part 2)

std/stdio.d
Add two missing alias definitions setmode and fileno for version (MICROSOFT_STDIO)
=> Add two missing alias definitions setmode and fileno for version (MICROSOFT_STDIO)

std/file.d
needed for https://github.com/dlang/dmd/pull/5876
=> std.file - fix for stricter @safe rules

std/typecons.d
=> std.typecons implicit string join

std/format.d
=> fix unsafe code from std.format readUpToNextSpec

std/format.d
=> fix unsafe code in std.format headUpToNextSpec

std/format.d
The previous PRs:
https://github.com/dlang/phobos/pull/4466
https://github.com/dlang/phobos/pull/4465
for std.format enable many @safe annotations. Notably not safe is formatObject(), because it calls Object.toString().
=> annotate std.format with @safe

std/complex.d
This enables:
1. Writer can be an OutputRange as well as an array
2. toString() can now be inferred to be @safe if Writer is @safe 
Still a problem though with assumeUnique(), as that is @system
=> switch complex.toString to use Writer instead of sink

std/variant.d
Explicitly list attributes instead of relying on inference.
Blocking https://github.com/dlang/dmd/pull/5881
=> std.variant: add attributes of test cases

std/ascii.d
=> Add @safe to std.ascii unittests

std/complex.d
All unit tests are now `@safe`
=> Add @safe to std.complex unittests

std/json.d
By clicking through the docs, I saw this page
http://dlang.org/phobos/std_json.html
- from comment to unittest
- use assert instead of writeln
=> fix top-level json.d example

std/outbuffer.d
All unit tests in std.outbuffer are now `@safe`
=> Add @safe to std.outbuffer unittests

std/file.d
Few code formatting of the documentation's example, for more readable
=> Added some spaces (std.file documentation)

std/functional.d
Added `@safe` to all unit tests that will allow it.
=> Add @safe to some std.functional unit tests

std/conv.d
Second try of #4515, followup to #4460
=> Move unit test so it makes it into the docs

std/traits.d
This is blocking https://github.com/dlang/dmd/pull/5897
Please do not delay pulling it.
=> std.traits: scope is only for types with pointers

std/path.d, std/process.d, std/random.d, std/regex/internal/backtracking.d, std/regex/internal/generator.d, std/regex/internal/ir.d, std/regex/internal/kickstart.d, std/regex/internal/parser.d, std/regex/package.d, std/socket.d, std/stdio.d, std/stream.d, std/utf.d, std/windows/syserror.d
That's all of them.
Will enable the check once this and https://github.com/dlang/phobos/pull/4513 are pulled.
=> Finish work on checking of too broad local imports outside of unit tests

std/array.d, std/bigint.d, std/bitmanip.d, std/concurrency.d, std/container/array.d, std/container/rbtree.d, std/container/slist.d, std/container/util.d, std/datetime.d, std/experimental/allocator/building_blocks/affix_allocator.d, std/experimental/allocator/building_blocks/bitmapped_block.d, std/experimental/allocator/building_blocks/free_list.d, std/experimental/allocator/mmap_allocator.d, std/experimental/allocator/package.d, std/file.d, std/format.d, std/json.d, std/net/curl.d, std/net/isemail.d, std/numeric.d, std/parallelism.d
Let's see where this breaks, and then I'll fix them
=> Start work on checking of too broad local imports outside of unit tests

std/traits.d
This is blocking https://github.com/dlang/dmd/pull/5901
=> std.traits: fix return ref

std/traits.d
Follow up on https://github.com/dlang/phobos/pull/4421 now that https://github.com/dlang/dmd/pull/5854 has been merged.
=> Issue 16142 - Enable test for disabled recursive identity opAssign

std/regex/internal/backtracking.d, std/regex/internal/ir.d, std/regex/internal/parser.d, std/regex/internal/thompson.d, std/regex/package.d
There's more to be done, but this is a good first step
=> Fix several imports in std.regex

std/xml.d
Also added @safe to some functions
=> Add @system and @safe to std.xml unit tests

std/internal/phobosinit.d
=> [HOTFIX] Fix Travis CI

std/range/package.d
It sucks when I have to open my local copy of Phobos to figure out what went wrong with my code. We should be telling the user what went wrong.
=> Added error messages to asserts in std.range

std/net/curl.d, std/regex/package.d
The regex changes were a prerequisite for some of these changes.
=> [trivial] Added const and immutable to several variables in std.net.curl

std/datetime.d
Do not pull until travis likes.
=> [trivial] Fix formatting to appease travis

std/utf.d
=> [trivial] Added immutable to several variables in std.utf

std/string.d
blocks https://github.com/dlang/dmd/pull/5860
=> replace unsafe use of .ptr in std.string

std/stdio.d
Blocking https://github.com/dlang/dmd/pull/5860
=> std.stdio: fix unsafe use of .ptr

std/internal/cstring.d
blocking https://github.com/dlang/dmd/pull/5860
=> cstring.d: fix unsafe use of .ptr

std/internal/math/biguintcore.d
And removed some unused variables
=> [trivial] Added const and immutable to several variables in std.internal.math.biguintcore

std/utf.d
blocks https://github.com/dlang/dmd/pull/5860
=> std.utf: fix unsafe .ptr usage

.travis.yml
Should un-block https://github.com/dlang/phobos/pull/4668
=> Update D-Scanner to alpha 8.

.travis.yml
As YAML comments aren't displayed on Travis, I think it could be useful to see a short message about each enforced check.
=> [trivial] Make travis output more user friendly

std/experimental/logger/package.d
Sole improvements of documentation.
=> Typos corrections for logger

std/experimental/ndslice/selection.d
=> Make iotaSlice implementation easier to understand

std/algorithm/iteration.d
=> add unittest attributes to std.algorithm.iteration

std/uni.d
Cannot tolerate overflows in storage allocation computations.
=> std.uni: add overflow checks to storage allocation

std/range/primitives.d
0 should not be passed to bsr, it has undefined return value.
=> Fix issue 16385:  std.range: undefined behaviour when skipping over 0xff in string.popFront

std/experimental/allocator/package.d
splitup of #4677 - depends on #4679.
=> Add attributes to makeArray - part 2 (length + init)

std/experimental/allocator/gc_allocator.d, std/experimental/allocator/package.d
Splitup of #4677  - part 1.
This PR is required by the others.
=> Add attributes to GCAllocator and theAllocator

std/experimental/allocator/package.d
splitup of #4677 - depends on #4679.
=> Add attributes to makeArray - part 1 (length)

std/experimental/allocator/package.d
splitup of #4677 - depends on #4679 & the attributes in #4682
=> Add attributes to makeArray - part 3 (input range) 

std/algorithm/comparison.d
=> add unittest attributes to std.algorithm.comparison

circleci.sh
Copy & paste error from the DMD script, fixes CircleCi for #4737
=> CircleCi: Change PR query path to Phobos

std/algorithm/sorting.d
https://issues.dlang.org/show_bug.cgi?id=16179 (multiSort no longer callable with delegate with context)
Moved multiSort's nested functions to module scope. 
Sorting predicates that access the frame of a function should work.
=> Fix issue 16179 - multiSort no longer callable with delegate with context

std/algorithm/sorting.d
=> Fix Issue 16413 - multiSort doesn't work with @system comparison function

.codecov.yml
an attempt to customize CodeCov.
=> add codecov config

std/algorithm/mutation.d
`TypeInfo_StaticArray.initializer` only returns an initializer for one element. In the case where `initializeAll` is given a range of static arrays of types with elaborate assign, random data would be used. This is also a memory corruption issue, since memcpy was reading past the end of the initializer. I tested the unit test before making the fix, and it was failing.
=> Fix issue where initializeAll does not properly use initializer

std/utf.d
=> add 'scope' to utf.UTFException.setSequence()

std/traits.d
https://issues.dlang.org/show_bug.cgi?id=16387
(getSymbolsByUDA works with structs but fails with classes)
- added a filter to skip the inaccessable 'this' member
=> Fixed Issue 16387 - getSymbolsByUDA works with structs but fails with classes

posix.mak, std/internal/test/uda.d, std/traits.d, win32.mak
This reverts commit d10780f19544f73907540e98aeee0039807e4578, reversing
changes made to 01eb06bb3897cd359d01a6c268785e5ee42789c0.
=> Revert "Merge pull request #4747 from MartinNowak/fix15907"

std/experimental/ndslice/selection.d, std/experimental/ndslice/slice.d
=> remove pragma inline for generic code

std/algorithm/iteration.d, std/array.d, std/json.d, std/range/interfaces.d, std/traits.d
This is already mostly done, just a few stragglers
=> add 'scope' to opApply() parameter

std/internal/unicode_comp.d, std/internal/unicode_decomp.d, std/internal/unicode_grapheme.d, std/internal/unicode_norm.d, std/internal/unicode_tables.d
Slowly chipping away at the number of public undocumented symbols
=> [trivial] Mark internal unicode declarations as package

std/uni.d
Incorrect overuse of @trusted makes std.uni unsafe, see https://issues.dlang.org/show_bug.cgi?id=14136
This doesn't resolve the issue, but it makes progress.
=> make std.uni a bit safer

std/experimental/ndslice/slice.d
This primitives required by future ndslice.algorithm, which is already part of the Mir project https://github.com/libmir/mir/blob/master/source/mir/ndslice/algorithm.d
=> add anyEmpty and backward for Slice

std/zip.d
Fixes https://issues.dlang.org/show_bug.cgi?id=16310
=> Allow specifying zip archive member order.

std/uni.d
=> std.uni: Don't hard-code @safe on template accepting output range

std/experimental/logger/multilogger.d
=> Fix mistake in std.experimental.logger.multilogger unit test

posix.mak, std/algorithm/comparison.d, std/algorithm/iteration.d, std/algorithm/setops.d, std/base64.d, std/container/package.d, std/csv.d, std/digest/digest.d, std/digest/hmac.d, std/exception.d, std/experimental/logger/multilogger.d, std/meta.d, std/range/interfaces.d, std/range/package.d, std/range/primitives.d, std/socket.d, std/utf.d, std/uuid.d, std/windows/syserror.d, std/zip.d, std/zlib.d
That's all of them!
I also added a style check to make sure we never add on more
=> Remove all package wide std.algorithm imports from Phobos

std/stdio.d
Removed an imported symbol that isn't used.
=> Removed unused import symbol.

std/typecons.d
This is blocking https://github.com/dlang/dmd/pull/5972
=> Blocker: add 'return' annotation to Tuple.rename()

std/algorithm/sorting.d
This is a component of fast deterministic selection, but is also useful in isolation.
=> Add medianOf function

std/stdio.d
https://issues.dlang.org/show_bug.cgi?id=16544
=> Fix Issue 16544 - Add File.reopen

std/algorithm/sorting.d
Separate the various implementations of `std.algorithm.sorting.partition` into overloads.
In addition to this making the code more readable, this partially fixes issue 16170 by fixing bad constraints that were too permissive for some of the implementations. Also fixes going past the ends of ranges.
Unfortunately, the results partition gives for ranges are wrong, and I don't have the know-how to fix it. 
Example:
```
import std.internal.test.dummyrange;
static bool even(int a) { return (a & 1) == 0; }
auto data = new ReferenceBidirectionalRange!int([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
auto r = partition!(even)(data);
r.writeln;
```
prints
```
[6, 7, 8, 9, 10]
```
=> [Issue 16170] Partial Fix for Broken std.algorithm.sorting.partition

std/algorithm/comparison.d, std/algorithm/searching.d, std/algorithm/setops.d, std/algorithm/sorting.d, std/datetime.d, std/file.d, std/net/curl.d, std/net/isemail.d, std/socket.d, std/stdio.d, std/string.d, std/utf.d
Apologies for the large diff. This is a find/replace job to update uses of Flag types of the form `Option.no`, `Option.yes` to `No.option` and `Yes.option`.
=> [trivial] [large diff] Update uses of Flag to use the Yes/No structs.

posix.mak
https://issues.dlang.org/show_bug.cgi?id=16568
@andralex (please test first)
=> posix.mak: Clean up /tmp test directory unconditionally

std/algorithm/iteration.d
This reverts commit b438bf5a0653b616ef6debe2a0dfe247d8fc5928.
https://issues.dlang.org/show_bug.cgi?id=16587
=> Fix Issue 16587 - split("", "x") should be ""

std/math.d
Less code, better codegen for signed case, passes unit tests. Removed the recursive instantiation.
I tried (but failed) to make the signed/unsigned cases the same code :(
I still suspect it's possible...
=> Improved isPowerOf2.

std/range/primitives.d
Smaller code with ldc:
http://ldc.acomirei.ru/#compilers:!((compiler:ldc,options:'-release+-O3+-boundscheck%3Doff',sourcez:G4ewlgJgBADiMDEBOIB2AXAjACiQUwDMoBjACwEMkBtAXSgGcBKKAAXSQFd709oYP8UVCHSkUAdygBvAFBQoYALaKO6cgCMANnhJQAvAyoAGGgG45CotmJQAPFCMAPABxHms%2BfPr6GAOhjsVJhQvr5%2B2qgA5qJmFgC%2BUHia9DoenkpwSOgkIPi%2B6mDo8OaeUBxgGAo%2BAOwcUAC0UOr0SNgAfjYAPlCYHIwl6YqZ2dwQvuSakbmFpIoD8mBWYFAAfFAAbH1VBpjzDD70/oGKFdhgADTheFGizKFXN6Sx8nEyrzKgkLDwyGjoAEy4QgkCjUOjcJDMNicbi8WACHTCUQSaQWJQqNRaHQ2AwQ4zPSxQax2BwuNwWNLyAD0VICSAU3i4cKKUHIn2gHFQXLwxDw9HolAAnk0QJyIN4yDyANYVSK%2BCxedgHdhHajBe4Q3wRaJPAaveRJFKE4l6AxOAgERgUhVQGlNFplVAQQgVOEEXIOG0Q5VIVVBEJhTXamJ6iyGvDW0oZXLZYi5PD5QrwKAALntSD25FUICginozRqDXT7WI/RtiyJ2DzBfs/2Y3Sr%2Be8a3WjCtpUpnhpAElUMAJl8AKoAFQQ9WcNvk1e8Oz2%2BsGwwY6DGEymSBmcy9StxKrpVBOqEbzUuQeuOrugZ …
=> Tighten popFront

std/signals.d
[https://issues.dlang.org/show_bug.cgi?id=16249](https://issues.dlang.org/show_bug.cgi?id=16249)
=> fix issue 16249 - std.signals: disconnect() is unsafe during emit() 

std/regex/internal/thompson.d
Surprisingly non-zero performance gain. It's also very dependent on the exact layout.
=> [std.regex] More compact ThompsonMatcher struct

std/algorithm/sorting.d
Algorithm description at https://arxiv.org/abs/1606.00484.
=> Implementation of "Fast Deterministic Selection" algorithm

std/algorithm/mutation.d, std/algorithm/searching.d, std/algorithm/sorting.d
https://issues.dlang.org/show_bug.cgi?id=8087
=> Fix Issue 8087 - Improve clarity of std.algorithm documentation

std/variant.d
=> [docs] Tweak std.variant docs

std/process.d
tldr; the windows api for reading environment variables is a complete pain and the previous implementation ran in to some of the pitfalls of it.
Perhaps there is a significantly shorter way of achieving the same results as this, but I can't find one.
=> Improve getting environment variables on windows

std/process.d
some systems can have a very large maximum number of file descriptors. In one test, a docker container allowed over 8 million. Hence `alloca` isn't a great idea.
~~solved by polling only a chunk of the possible fds at a time.~~
~~One question: what do people think about `enum chunkN = 1024;`, too small? too large?~~
Solved by using `malloc` instead
=> Fix Issue 16955 - std.process.spawnProcessImpl can crash due to alloca

std/random.d
Solved the bug. Now randomCover.popFront and length work correctly
=> Fix Issue 16724 - RandomCover.popFront is a no-op for the first call

.dscanner.ini, std/conv.d, std/experimental/ndslice/iteration.d, std/experimental/ndslice/slice.d, std/format.d, std/math.d, std/regex/internal/tests2.d, std/socket.d
There doesn't seem to be a style guide for long lines, so I grouped the logic where possible. Perhaps additional rules could be added to the style guide on what to do for long lines.
=> Enables long line style check.

std/range/package.d
It's funny how the pseudo-code is actually correct.
=> Fix std.range.Zip.save

std/algorithm/iteration.d
Is there any case where we wouldn't want to use `ref` for an `Iterable` (not range) if we can?
=> Fix issue 16255 - std.algorithm.iteration.each on opApply doesn't support

std/datetime.d
Failure spotted here: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2326773&isPull=true for https://github.com/dlang/dmd/pull/6361
=> Fix random std.datetime unit test failure

std/range/package.d
Added attributes to some std.range.package unittests so they have a better chance to catch regressions.
=> add attributes to some unittests of std.range 

std/getopt.d
Fixes https://issues.dlang.org/show_bug.cgi?id=16048
=> getopt: assert on duplicate long/short options

std/algorithm/mutation.d
bringToFront now accepts narrow strings.
=> Fix Issue 16959 - bringToFront fails on char array

std/range/package.d
- still unresolved issues before release
See https://github.com/dlang/phobos/pull/5002#issuecomment-270357813.
=> remove bitwise documentation

std/process.d
Tests that the code changed in https://github.com/dlang/phobos/pull/4934 actually does what it says it does
This isn't perfect, it turns out that testing whether a fd is open in a way that is both posix-portable and doesn't require compiling C is basically impossible. Currently I print a warning if I can't find a way of testing, but that could be a failure instead, I can't decide.
I'd love to know if there's an easier way.
=> test inheritFDs

std/net/curl.d
I added a function which is a wrapper over the C api function curl_easy_getinfo in order to ease the fetching of various timings. I only tested for http that the c function is called correctly (i.e. after the function is called the result is CURLE_OK) since I do not know how to test if the timings are correct.
=> Issue 16736 - Retrieving cUrl time values is quite cumbersome

std/conv.d
I would also be possible to use a template Yes/No parameter to avoid the new runtime conditional branch on existing code that uses `parse`.
=> fix issue 9615, std.conv.parse!(T[]) should allow a trailing comma

std/utf.d
The trouble here is `decodeImpl()` uses pointers directly for speed, meaning the function is not `@safe`. Being not `@safe` means it does not infer `scope` for its parameters, and then `popFront()` doesn't infer `scope` either, causing cascading problems up the call stack.
To fix is a bit clumsy, saying that `popFront()` is `scope`, and then trusting `decodeImpl()`. Note that inferring `@safe` for `popFront()` still works correctly, since it winds up calling `empty` and `front` and `popFront` so if those aren't `@safe` then it won't be inferred `@safe`.
P.S. `scope` cannot be inferred reliably for `@system` code.
=> get byUTF() to work with -dip1000

std/process.d
Prompted by reading https://rachelbythebay.com/w/2017/01/30/env/
=> warn about glibc & changing environment variables

std/random.d
Update to work with `-dip1000`
=> [scope]: annotate std.random

std/utf.d
=> Range-ify and DRY std.utf.toUTF32

std/outbuffer.d
MS conforms to the standard beginning with VS 2015, i.e., if the buffer is too small, `vsnprintf()` returns the number of required characters (excl. terminating null) [[MSDN](https://msdn.microsoft.com/en-us/library/1kt27hek(v=vs.140).aspx)]. VS 2013 and earlier always returned -1 in that case.
So just use the generic (previous POSIX) version, it's compatible with older VS anyway.
Already unittested in line 380 ("hello world 6" vs. "hello world 62665").
=> [Trivial] Fix std.outbuffer.[v]printf() for Visual Studio 2015+

std/conv.d, std/file.d, std/string.d, std/utf.d
=> Add checks for infinite ranges in many range function signitures

std/stdio.d
Same basic example as writeln and readln.
=> Fix Issue 16991 - Make writeln documentation palatable

.dscanner.ini
These checks are already passing atm - so let's enable them & prevent regressions ;-)
=> Dscanner: enable more checks

std/net/isemail.d
Some more clean up of old code
=> Modernized regex code in std.net.isemail

std/net/isemail.d
Last of the improvements/modernizations to this module.
=> Make std.net.isemail.isEmail @safe

std/string.d
Previous code had to iterate over the array twice and allocated two strings. 
Performance:
```
old	816 ms, 65 μs, and 6 hnsecs
new	506 ms, 437 μs, and 7 hnsecs
```
code
```d
import std.array;
import std.datetime;
enum testCount = 1_000_000;
S capitalize1(S)(S input) @trusted pure
if (isSomeString!S)
{
import std.array : array;
import std.uni : asCapitalized;
return input.asCapitalized.array.to!S;
}
S capitalize2(S)(S input) @trusted pure
if (isSomeString!S)
{
import std.array : array;
import std.utf : byUTF;
import std.uni : asCapitalized;
return input.asCapitalized.byUTF!(ElementEncodingType!(S)).array;
}
void main()
{
auto result = …
```
=> Small optimization for std.string.capitalize

.dscanner.ini, etc/c/curl.d, etc/c/odbc/sql.d, etc/c/odbc/sqlext.d, etc/c/sqlite3.d, std/algorithm/iteration.d, std/datetime.d, std/functional.d, std/internal/math/biguintcore.d, std/internal/math/errorfunction.d, std/internal/unicode_tables.d, std/math.d, std/parallelism.d, std/random.d, std/zip.d
And enable the dscanner check
cc @wilzbach
=> Check For Underscores in Number Literals With Five or More Digits

std/algorithm/comparison.d, std/algorithm/iteration.d, std/algorithm/mutation.d, std/algorithm/searching.d, std/algorithm/setops.d, std/algorithm/sorting.d
... in std.algorithm
Also fixed a spelling mistake.
=> Linked to the definition of input ranges where they're mentioned

std/regex/package.d
(also removed unwanted whitespace in the example)
=> [BOOKTABLES]: Add BOOKTABLE to std.regex

std/file.d
=> [BOOKTABLES]: Add BOOKTABLE to std.file

std/ascii.d
=> [BOOKTABLES]: Add BOOKTABLE to std.ascii

std/path.d
=> [BOOKTABLES]: Add BOOKTABLE to std.path

std/array.d, std/conv.d, std/string.d
=> Add more links to std.range definitions

std/conv.d
=> [BOOKTABLES]: Add BOOKTABLE to std.conv

std/algorithm/comparison.d, std/algorithm/iteration.d, std/algorithm/mutation.d, std/algorithm/package.d, std/algorithm/searching.d, std/algorithm/setops.d, std/algorithm/sorting.d
While the `BOOKTABLE` looks nice, it's quite a pain to maintain as everyone seems to keep forgetting them :/
=> std.algorithm: remove quickIndex, fix outdated book tables & HTML links

std/experimental/checkedint.d
tl:dr: Removes the (ugly) quickIndex as all symbols are mentioned within the first two paragraphs and makes the hooks a table
Header
----------
Before:
After:
Hooks
---------
Before:
After:
Combinations
-------------------
Here I am not sure whether it looks better:
Before:
After:
=> [BOOKTABLES]: Add BOOKTABLE to stdx.checkedint

posix.mak
I noticed that the windows makefiles don't have a checkwhitespace rule. Is that ok?
=> Updated posix.mak makefile to use ../tools/checkwhitespace.d

std/bitmanip.d
Basically, the bug is in the static if that wrongly assumes that if a range has `ubyte` elements and has slicing, then its slices are assign-copyable to `ubyte[]`. This fails for a user-defined range with ubyte elements that supports slicing, but does not return something convertible to `ubyte[]` when you slice it.
=> Fix issue 17247: std.bitmanip.read should not assume hasSlicing means assign-copyable

std/utf.d
=> std.utf: Fix broken tests

std/net/curl.d, std/uri.d, std/uuid.d
Mostly changes to immutable. Also fixed an issue where a keyword was used as a parameter name.
=> Fix dscanner sugesstions in several files

win64.mak
- as seen on win-farm-1 tester
=> split std.algorithm tests to avoid OOM

std/container/array.d
- make formatting consistent
- add missing details, e.g. about exception being thrown
- fix wrong descriptions
- fix wrong complexity specifications
- delete redundant comments
=> std.container.Array - documentation cleanup

std/string.d
In conjunction with https://github.com/dlang/phobos/pull/5310
=> Mention the extra checks in the std.string.assumeUTF docs

std/experimental/allocator/package.d
=> [BOOKTABLES]: Add BOOKTABLE to stdx.allocator

std/digest/digest.d
Given two strings that represent two crypto digests, using std.algorithm.equal to compare them leaves your web application open to timing attacks because it has a short circuit, i.e. it returns `false` on the first inequality it finds.
The attack comes from allowing attacker to brute force your HMAC key for example. See this article for more information, evidence that the attack exists, and why Java gets it wrong: https://codahale.com/a-lesson-in-timing-attacks/
The solution is to have a string comparison that will always be constant time given two strings of the same length.
Ping @andralex, this is a name addition.
=> Fix Issue 17286 - A function for comparing two digests securely

std/experimental/allocator/gc_allocator.d
=> Fix style problems in std.experimental.allocator.gc_allocator

std/conv.d
Fixes the issue without any backwards incompatible changes, and is therefore not DRY.
Ping @MartinNowak
=> [REG] Fix Issue 17282 - std.conv.parse throws with -debug

std/format.d
This needs to be in in order to support non-pure onRangeError.
=> Replace use of onRangeError

Jenkinsfile
- finally moved repo under dlang
=> update pipeline ci repo url

std/regex/package.d
Now one can click on a section to get a link to it.
=> [Ddoc] self-link sections

std/datetime.d
=> netbsd small changes: fix datetime.d

std/bigint.d
If anyone else has a cleaner solution, I'd like to know. I'll quote Walter in describing the problem 
> I think that trouble here is that attribute inference is not done until the template is instantiated. But the compiler does not instantiate a template until it matches a template, and
this(Range)(Range s)
> does not match for constructing an immutable. I don't see a way out of this chicken-and-egg problem.
=> Fix Issue 17330 - [REG 2.072] BigInt's constructor used to be pure

std/experimental/allocator/common.d, std/experimental/allocator/package.d
Add a shared allocator interface that should be used by shareable allocators. The processAllocator will implement this interface.
=> Add ISharedAllocator and have the _processAllocator use it

std/encoding.d
"Booktablified" yet another module :)
=> [BOOKTABLES]: Add BOOKTABLE to std.encoding

posix.mak
=> Specify the exact folder location for the style Makefile target of the D source files

posix.mak
make -f posix.mak std/XXXXX.test is awesome but sometimes I need to attach a debugger
DEBUGGER=ddd BUILD=debug make -f posix.mak std/XXXXX.debug allows to do that
=> debugger target for posix

std/algorithm/iteration.d
A bit awkward. Efficiency-wise, branch prediction should help with repeated tests against `_primed`.
=> Fix Issue 16326 - filter is not lazy enough & has weird save behavior

std/datetime/stopwatch.d
Seen here: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2560534&isPull=true
CC @jmdavis
=> std.datetime.stopwatch: Fix another random test failure on Win32

std/algorithm/mutation.d
=> Revert "[Static if] replace overload constraints with static if (mutation.d)"

std/utf.d
Since it is supposed to be replaced by encode(), might as well implement it in terms of encode(), which will also help as a guide to people fixing their code to use encode().
=> reimplement toUTF8/16 in terms of encode()

std/algorithm/searching.d
See https://github.com/dlang/phobos/pull/5420 for performance
=> Removed auto-decoding from the single needle version of endsWith

std/experimental/logger/core.d
=> fix issue 15954, 16256, 17328

std/math.d
Also replace other uses of the constant with EXPBIAS.
Verified on LDC/AArch64.
=> std.math: Fix frexp() for 128 bit reals by aligning EXPBIAS with other formats

std/traits.d
using __traits
fix Issue 17421 - add __traits(getFunctionVariadicStyle, f)
=> reimplement std.traits.VariadicFunctionStyle()

std/experimental/logger/core.d
cc @burner I think this can be simplified significantly, follow up after we pull this?
=> Eliminate shared static this() from std.experimental.logger

std/process.d
Fixes CircleCI style checks.
Introduced here: https://github.com/dlang/phobos/pull/5431/files#diff-8ac4ebb5dcc368ac0e9b7b9f118aa824R577
=> std.process: Fix brace style

std/datetime/timezone.d, std/net/curl.d, std/regex/package.d
A couple of Ddoc weirdnesses that I observed while playing with https://github.com/dlang/phobos/pull/5495 and the blacklist generator.
=> Fix Ddoc comments

std/experimental/logger/core.d, std/experimental/logger/filelogger.d, std/file.d, std/net/curl.d, std/zip.d
Should have faster compile times.
=> Switched package-wide datetime imports to new sub-packages

std/net/curl.d
Using atexit upon initialization.
=> Eliminate shared this from std/net/curl.d

std/parallelism.d
In an attempt to fight the right CI crosses.
Follow-up to:
https://github.com/dlang/phobos/pull/5534#issuecomment-312727009
=> Add // nocoverage to non-deterministically covered lines

index.d
=> index.d: Use MREF to fix broken DDox links
