std/algorithm/iteration.d

Also fixed `filterBidirectional` while I was at it.

[Issue 14485] .front of empty filtered zip range is accessible

---

etc/c/curl.d

Functions that take pointer and length separately cannot be memory-safe.
The caller can pass a length that's too large, leading to an out-of-bounds
read.
These were added in #3190 by @braddr. Out-of-bounds reads were not addressed in the rationale.

remove bad @trusted annotations from etc.c.curl

---

std/signals.d

None of them are @safe due to calls to object.destroy

Add @system to std.signals unit tests

---

changelog.dd

changelog entry for removed @trusted attributes in etc.c.curl

---

std/digest/digest.d

Returning scope variables doesn't work. This is a blocker for https://github.com/dlang/dmd/pull/5903

std.digest: remove wrong use of scope

---

std/string.d

- 100% coverage cannot be reached because of a `if (__ctfe)` branch (line 1199 - 1204)
- 3 lines of coverables code remain: 456, 2986 - 2987
Otherwise this PR annotates the unittests that were not yet.

Add @safe and @system to std.string unittests, + coverage

---

std/format.d

Also gets rid of suspicious use of sep.ptr

harmonize use of std.format sep[]

---

std/digest/digest.d

This reverts a part of commit 77aa18e3e5e3cfa6682d5f8ee961afe70f948d67 (PR #4549).
As noted in the discussion to #4549, the function does not return its argument. If I'm wrong here, I'd appreciate if someone could spell out how `digest` returns a reference to `data`. I just can't see it.

restore mistakenly removed 'scope'

---

std/parallelism.d

This is a blocker for https://github.com/dlang/dmd/pull/5903

remove incorrect use of 'scope'

---

std/string.d

Lesson to learn here: We should be testing with -de.

fix issue 16238 - std.string.lastIndexOf fails compilation with -de

---

std/parallelism.d
std/range/package.d

Hopefully this fixes the cycle detected in dlang/druntime#1602

Fix loop during unit tests between std.parallelism and std.range

---

std/xml.d

This is a resubmission of #4064 which @coderabhishek wasn't able to finish. I've added the requested asserts in a separate commit. CC @quickfur.
If this gets merged, #4064 can be closed.

Fix issue 4509 - XML parser in std.xml throws TagException if the attr value is put in apostrophes.

---

std/range/package.d

Change the phobos iota implementation so that it does not conflict with
custom types that have a custom implementation of iota.

Allow iota implementation of custom types

---

std/datetime.d

- change to list all missing WinTZ translations when running std/datetime
unittests w/ -version=UpdateWindowsTZTranslations so they can be
updated manually
Currently blocks https://github.com/dlang/dmd/pull/5924.

fix test failure for updated Windows TZs

---

std/algorithm/iteration.d
std/bigint.d
std/parallelism.d
std/range/package.d

Finally got a windows box test environment set up. This should fix all remaining cycles in Phobos.
Note that I had to move some documented examples. I tried to keep the spirit of the documentation, and still have the examples moved to different files where they won't cause cycles.

Fix all windows cycles

---

.travis.yml
std/conv.d
std/string.d

Seems like this one slipped through during our Travis setup. Hence let's actually enable the automatic check for the whitespace between selective imports ;-)

[automation] enable travis check for selected imports

---

std/conv.d

Small performance increase for std.conv.text/wtext/dtext

---

std/algorithm/iteration.d

This is a continuation of https://github.com/dlang/phobos/pull/4568 and https://github.com/dlang/phobos/pull/4573

Added Asserts and Messages to Asserts in std.algorithm.iteration

---

std/range/primitives.d

Based on [this post](https://forum.dlang.org/post/lotwodutjmkowdoccufs@forum.dlang.org), many core devs were in agreement that one basic rule of ranges is that many calls to `front` without a call to `popFront` should all yield the same value. Some ranges break this rule.
This PR formalizes this rule as to make it crystal clear that these violations are bugs that must be fixed:
```
Calling front multiple times without calling popFront yields the same result for each call.
```
Ping @schveiguy @jmdavis

[RFC] Make the behavior of calling range primitives clear

---

std/net/curl.d

Documentation of async function : byLineAsync & byChunkAsync has a little typos.
There was no such a variable `range` in each of sample code's scope.
```diff
* auto range3 = byLineAsync("dlang.com");
- * if (range.wait(dur!"seconds"(2)))
- *     writeln(range.front);
+ * if (range3.wait(dur!"seconds"(2)))
+ *     writeln(range3.front);
```
```diff
* auto range3 = byChunkAsync("dlang.com", 10);
- * if (range.wait(dur!"seconds"(2)))
- *     writeln(range.front);
+ * if (range3.wait(dur!"seconds"(2)))
+ *     writeln(range3.front);
```
It must be `range3`, I fixed.

Fix typos in std.net.curl.byLineAsync&byChunkAsync

---

std/json.d

Having a union with overlapping pointers is unsafe to write to. This is a blocker for https://github.com/dlang/dmd/pull/5940 please do not delay review.

json.d: union pointer access is unsafe

---

std/datetime.d
std/json.d
std/math.d
std/traits.d

This deprecates the time zone name conversion functions and related functionality which was scheduled for deprecation. It also removes a few deprecated items that have reached the point where they're supposed to be permanently removed.

Move deprecations along

---

std/algorithm/sorting.d

* Tweak wording of rationale for returning `SortedRange` for readability
* Use *Preconditions* section
* Move note about `shwartzSort` to top

[trivial] Tweak docs for std.algorithm.sort

---

std/experimental/ndslice/slice.d

Follow-up to #4263.
CC @9il.
I could only find this sole occurrence.

[ndslice]: rename mod -> replaceWithArray

---

std/base64.d

It looks like the commas in the text were causing:
> RFC 4648 - The Base16, Base32, and Base64 Data Encodings
To be truncated to 
> RFC 4648 - The Base16
Changing `$(HTTP)` to `$(LINK2)` appears to fix this.

[trivial] Correct truncation of std/base64.d "References" section

---

std/experimental/allocator/package.d
std/experimental/ndslice/slice.d

As discussed earlier, it's possible to infer the ElementType for `makeArray` with Ranges.
Even better we can keep full compatibility and make this feature opt-in - is anyone against this?
tl;dr: let's allow the variant b! (a is still possible)
```
auto a = alloc.makeArray!long([5, 42]);
auto b = alloc.makeArray([5, 42]);
```
Ping @9il @andralex

infer elementType for ranges in makeArray,makeSlice

---

std/path.d

blocker for https://github.com/dlang/dmd/pull/5860

std.path: make .ptr access trusted

---

std/exception.d

blocks https://github.com/dlang/dmd/pull/5860

remove unsafe use of .ptr in std.exception

---

std/file.d

endless cases of these.
Blocks https://github.com/dlang/dmd/pull/5860

file.d: fix unsafe use of .ptr

---

std/experimental/ndslice/selection.d

The reason is to reduce computations in case of 1-dimensional slices. Both specialisations just return the slice.

add specialisation for byElement & byElementInStandardSimplex in case of 1D

---

std/typecons.d

typecons.Unique.opDot() should be inout to allow use through const access paths.

make Unique.opDot() inout

---

std/algorithm/iteration.d

`sum` is not precise. Precise algorithms are Python `fsum` and Mir's [`sum!(Summation.precise)`](http://docs.mir.dlang.io/latest/mir_sum.html)

fix docs in algorithm.iteration

---

std/experimental/ndslice/selection.d

The original example for pack has too much stuff going on. Replacing it with a slimmer version that makes it a bit more clear what the impact of pack is. In particular, I feel like the asserts for shapes are necessary to make it obvious.

[ndslice] Change pack example to something simpler

---

.travis.yml
std/numeric.d

Hi all, the idea for this automation is simple, let's ensure (1) that no PR decreases the code coverage, (2) help reviewers judging code coverage improvements PRS, (3) provide simple tools for contributors to see which parts are uncovered.
You can preview this [here](https://codecov.io/gh/wilzbach/phobos/tree/5fc9eb90076101c0266fb3491ac68527d3520fba/std).
That being said, this won't be perfect in the near future as Travis can only run Linux and Mac OS builds, so special versioned paths will not be treated right. The idea here is to get an easy 90% solution that already helps reviewers in most cases (=a lot better than 0%). In the future we might add Codecov reporting to the AutoTester.
Now to this PR:
1) Thanks to the help from @stevepeak, Codecov.io is able to recognize the code coverage …

show code coverage with Codecov.io

---

std/conv.d

Like the title says, I removed auto-decoding from `parse`, which only checked for things in the ASCII range anyway.
The reason why this is so messy is `parse` takes its range by `ref`, so `byCodeUnit` cannot be used without using `refRange`, which requires using `&r`, which is unsafe. So the only solution left is to do it manually with a bunch of `static if`s.
I tried putting the `refRange.byCodeUnit` in a `@trusted` block, but that resulted in a speed pessimization (I'm guessing due to the inability to inline at that point).
By my measurements, this is anywhere between 2.5-5x as fast as the original implementation.
```
Total time: 41 ms, 366 μs, and 9 hnsecs
Total time: 223 ms, 437 μs, and 5 hnsecs
```
Here's the …

Removed auto-decoding from std.conv.parse

---

std/container/array.d

Working with `std.container` is a huge pain as one bumps into bugs all the time :/
Are there any plan yet to rewrite this module?, e.g.  [emsi's container](https://github.com/economicmodeling/containers) could be a a good start.

Fix issue 16331 - std.container.array should allow uncomparable values

---

std/traits.d

https://issues.dlang.org/show_bug.cgi?id=16182
It is beyond my comprension as to why this irrelevant change helps
fixes #16182. I believe there is something amiss becuase expression
fqnSym!(__traits(parent, T)) ~ '.' is returning a char[] while
fqnSym!(__traits(parent, T)) ~ "." returns a string. This while
expression fqnSym!(__traits(parent, T)) returns a string.

Fix for for issue 16182 - std.traits.fullyQualifiedName Bug

---

std/digest/digest.d

in reference to #4684, let `toHexString` be `@safe`.

std.digest.digest: make toHexString @safe

---

std/algorithm/sorting.d

Saw this while looking through the code,  seems like DMD has evolved since 2.060 ;-)

std.algorithm.sorting: enable CTFE test for Timsort

---

std/algorithm/sorting.d

> It's possible that someone introduced new unittests that aren't explicitly @safe or @system, but with the exception of std.stream (because of imminent deprecation) all phobos unittests are now explicity tagged.
@atilaneves how did you check that?  `grep -r "^unittest" -r std` still yields a lot.

add unittest attributes to std.algorithm.sorting

---

std/process.d

v.idup returns null when called on an empty but non-null array.  This is
undesirable because we want to differentiate between not-present and
empty-but-present.
This is a continuation of https://github.com/dlang/phobos/pull/4616 but with master as the base.

Properly handle the case where an environment variable is an empty string

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d

The reason is that Slice never calls front/popFront and others
primitives of underlaying range.

fix Issue 16308 - [ndslice] should always has save primitive

---

std/experimental/allocator/building_blocks/null_allocator.d

Commented out documentation for the commented out function goodAllocSize in NullAllocator
Previously, the docs showed the additional line "Returns n.". This documentation comment belongs to the goodAllocSize function, which is commented out, so commented out the doc comment, too.

[trivial] Fix docs for NullAllocator

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/slice.d

https://issues.dlang.org/show_bug.cgi?id=16315

fix Issue 16315 and optimise arithmetic operations for Slice

---

std/digest/digest.d

This should increase code coverage for `std.digest.digest` to 100%. (-false positives)

Add unittest for .length and .peek (std.digest.digest.WrapperDigest)

---

std/functional.d

These can be done at compile time since `maxSize` is a template parameter.

std.functional: add overflow checks

---

std/algorithm/sorting.d

Putting the schwartz back in `schwartsSort()`
Blocking https://github.com/dlang/dmd/pull/5860

fix .ptr safety problem in schwartzSort()

---

std/experimental/ndslice/slice.d

Just tested and saw that this pragma slowdown the code. This was added as ad-hock to help vectorization and does not need anymore

remove pragma(inline, false)

---

std/digest/murmurhash.d
std/experimental/ndslice/slice.d

The code has grouping of elements. And optimisation in case of `stride!(N-1) == 1`.
Coverage equals 100%. Codecove shows attribute propagation in `murmurhash.d` as not covered for no reason (probably because Travis is always 64-bit for Phobos).

fix Issue 16311 - toHash for Slice is not defined

---

std/stdio.d

When using nonstandard output libraries such as
https://github.com/sickill/stderred argumentless writeln() will fail on
the enforce because it check specifically for a newline to be returned.
Checking instead that the output is not EOF follows the documentation
and allows overridden write() functions from the standard library.

Fix issue 16351

---

changelog.dd
std/numeric.d

... in order to make the code more `@nogc` and `nothrow` friendly.
And also use `onOutOfMemoryError` instead of allocating and throwing a new
exception when `malloc` fails.

Use assert instead of enforce in std.numeric

---

std/base64.d

Forum thread: https://forum.dlang.org/thread/nnkik5$1nfq$1@digitalmars.com

[trivial] Fixed in contract for Base64.decode for arrays

---

std/traits.d

`getUDAs` worked with checking for templated types with just the template and not a specific instantiation, whereas `hasUDA` did not, and `hasUDA` worked with UDAs that were values, whereas `getUDAs` did not. This makes them consistent, which will hopefully make them easier to use correctly. I had a horrible time dealing with them in my own code due to the inconsistencies.
Having `getUDAs` fetch stuff like `@(42)` probably isn't very useful, but I don't really see any harm in it, and since it's by far the simplest to just make `hasUDA` use `getUDAs`, it would actually be more work for `getUDAs` to not work with values like `hasUDA` does. So, it just seems to me to make more sense for it to work with them even if it isn't terribly useful (and maybe someone will find a use for them - …

Fix issue# 16364. Make getUDAs and hasUDA consistent.

---

std/encoding.d

Because requiring immutable characters doesn't make sense.
See also <http://forum.dlang.org/post/noashv$1bgv$1@digitalmars.com>.
The second commit ("remove pointless variable t") is just a little cleanup I noticed when looking at this.

let transcode accept mutable/const characters

---

std/net/curl.d

RF2616 says: "The type, subtype, and parameter attribute names are case-insensitive."
https://tools.ietf.org/html/rfc2616#section-3.7
See also: <http://forum.dlang.org/post/scoeormeciaoiqxsefkz@forum.dlang.org>.

ignore case when looking for "charset"

---

std/algorithm/sorting.d

I might be missing something - looks like there was a bit of redundant work there during partitioning.

Simplify, eliminate redundant work in sort

---

std/concurrency.d

Avoid the assignment operator on an object that has been destroyed, it will call the destructor again.

fix issue 16386: std.concurrency: destructors called twice on objects passed as Message

---

std/stdio.d

Also fixing another mistakenly highlighted "format".

fix issue 16372 - Broken links in documentation

---

std/experimental/allocator/common.d

Noticed while reviewing #4702 that we never check `reallocate` with an allocated array.

[trivial] Extend reallocate test for all Allocators

---

std/traits.d

This new trait allows to check whether a class is nested inside another and `this.outer` can be used to access the enclosing class.
This is needed to implement a solution for issue 16319.

New trait std.traits.isInnerClass

---

std/conv.d
std/experimental/allocator/package.d
std/traits.d

This changes `emplace` so that, when dealing with inner classes, the first argument after the memory pointer must be a pointer to an instance of the outer class, used to initialize the outer pointer of the emplaced object.
It also contains a related fix to `std.traits.isInnerClass`, which was recently introduced to address this issue.
Incidentally, this also solves issue 16319, representing a more complete solution wrt. #4732 , which this replaces.

Fix emplace for inner classes

---

std/internal/cstring.d

The idea is not to conflate pointers-to-stack with pointers-to-heap, otherwise the compiler gets concerned that the former escapes.
This is blocking https://github.com/dlang/dmd/pull/5972
As this is a blocker, please don't delay reviewing/pulling it.

fix tempCString() to follow strict scope rules

---

std/parallelism.d

Monkey business with stack pointers now can only be done in explicit `@system` code.
This is blocking https://github.com/dlang/dmd/pull/5972
Please don't delay reviewing/pulling.

use @system to return pointers to stack

---

std/experimental/allocator/building_blocks/scoped_allocator.d

This is a simpler fix than https://github.com/dlang/phobos/pull/4702.

Fix issue 16046 - ScopedAllocator does not set prev, causing segfaults

---

std/bitmanip.d

Otherwise it fails more advanced scope checking.
Blocking https://github.com/dlang/dmd/pull/5972

bitmanip: missing a 'return' attribute

---

std/datetime.d

SysTime's opEquals only compares the _stdTime member, so do that for toHash as well.

Add toHash to SysTime

---

std/getopt.d

Prevent a segmentation fault when the option name is empty.
I am not convinced the type of Exception is correct since this is not a user error, but a programming error.
Comments are appreciated.

Fix Issue 16443 - Segmentation fault when option name is empty

---

changelog.dd
std/experimental/typecons.d

This is a revival of #3862 (which was an revival of #2881).
The status from @andralex was:
> For more detail: we should define std.experimental.typecons and put this in it. With that I preapprove this addition. Thanks!
Unfortunately @JakobOvrum seems to be away for the last few months, but we shouldn't let this great PR die ;-)
I copy/pasted the addition to `std.experimental.typecons`, added the missing import. Full credit of course goes to @JakobOvrum (luckily git allows to set the history accordingly).
I also included the changelog entry in a separate commit.

Add std.experimental.typecons.Final

---

posix.mak
std/internal/test/uda.d
std/traits.d
win32.mak

- change of __traits(allMembers) semantics cause getSymbolsByUDA to no
longer return invisible (private) symbols
- add test for using getSymbolsByUDA as mixin template to still access
private symbols

supplemental change for Issue 15907 fix

---

std/range/package.d

Issue 16363 (Cannot construct a random access range using frontTransversal)
https://issues.dlang.org/show_bug.cgi?id=16291
- Added length property to frontTransversal (only if the length is known)

Fix issue 16363 - Cannot construct a random access range using frontTransversal

---

std/experimental/allocator/building_blocks/allocator_list.d

Wrong `return` position. That says it all. Creating unnecessary allocators, memory leaks and so on.

fix AllocatorList.allocate weird behavior

---

README.md

We finally made the switch to CircleCi -> updated badge.
Moreover I have seen that the Issuestats badge sometimes wasn't displayed correctly.
[Since one month](https://github.com/badges/shields/pull/656) Shields.io supports IssueStats, so I use d the opportunity to give them a try.

Update badge links on README.md

---

std/traits.d

Sparked by @lodo1995 showing me in [a Learn thread](http://forum.dlang.org/post/fojuhqetulrvvmlhpgmq@forum.dlang.org) that `TemplateOf` supports this.

implement std.traits.isInstanceOf for non-types

---

std/traits.d

This is the first time I've contributed code to a project(other than a slight documentation improvement), so I'm sorry if I've messed up something.
https://issues.dlang.org/show_bug.cgi?id=16168

Issue 16168 - isCopyable trait for value types

---

std/experimental/allocator/package.d

splitup of #4677 - depends on #4679.

Propagate attributes in std.experimental.allocator.make

---

std/algorithm/searching.d

So the caller knows it doesn't escape. Blocking scope checking.

add scope to searching.find()'s needle

---

std/experimental/allocator/package.d

[trivial] std.allocator.expandArray: Move ForcedInputRange example into undocumented test

---

std/container/array.d
std/container/binaryheap.d
std/container/dlist.d
std/container/slist.d
std/container/util.d

This has bugged me for a while. The copyright and author tags got replicated to all the sub-modules when std.container was split, and I frequently get pinged because I'm the "author" of all these modules. But I'm only the author of the Red Black Tree.

Remove Steven Schveighoffer as author of all container modules.

---

std/traits.d

Binary literals are borderline illegible, especially with the weird _ placement. Use hex values like everywhere else.

replace binary literals with hex

---

std/typecons.d

Circular references are usually bad news when used in `static if`, and this got tripped up when inferring `scope` on pointer parameters. This change makes it work with and without `scope` inference.
This is blocking https://github.com/dlang/dmd/pull/5972

make Proxy.accessibleFrom() work with 'scope' inference

---

std/internal/cstring.d

This simple addition enables the result of `tempCString()` to be also treated like an array without having to run `strlen()` on it.

cstring: add opIndex to result

---

std/container/binaryheap.d

While trying to create an top-level unittest for this module (#4331), I realized that with an array as storage, it's not possible to insert new items, which seems like a bug. 
```
import std.container.binaryheap;
auto q = heapify!"a > b"([1, 4, 5]);
q.insert(2); // ERROR: Cannot grow a heap
```
Here's the fix ;-)

fix issue 16072 - container.binaryheap should be extendable for arrays

---

std/algorithm/iteration.d

Removed a scoped debug line for the ```auto joiner(RoR)(RoR r)``` unittest. It was removed since it obscured the example in the Phobos docs.
https://dlang.org/phobos/std_algorithm_iteration.html#joiner

Removed debug lines from example unittest

---

.editorconfig
circleci.sh

As discussed in #4719 we have run into some troubles with the reporting of the coverage between the `test_runner` and individual tests. This PR is there to continue testing for this problem.
(while this PR will increase coverage, it does so by running both the `test_runner` and individual builds)

[WIP] Use test_runner for coverage testing

---

std/utf.d

Added fast paths in std.utf.byUTF

---

std/signals.d

detachDisposeEvent called even with remaining connected slots for that instance.
[Issue 15341](https://issues.dlang.org/show_bug.cgi?id=15341)

Fixes issue 15341

---

std/encoding.d

When trying to make a `format` call pure, I noticed that all of the impure problems could be traced back to std.encoding, which is called by std.range.put. Most of the problems here are the result of not using template inference or missing attributes. There was one instance of accessing a mutable private member, which was made immutable.
Making these changes will make a lot of templates in other modules `@safe pure` as a side effect

Make std.encoding mostly @safe pure nothrow @nogc

---

std/utf.d

* Improve docs
* removed repeated code between this and byUTF
* removed indiscriminate `pure` application
* Range-ified

Make std.utf.toUTF8 DRY by using byUTF internally

---

std/typecons.d

Particularly useful to `map` on to a range of tuples generated from e.g. `zip` or `cartesianProduct`.

Add std.typecons.Tuple.rename

---

std/csv.d

replace empty parameter catch with assertNotThrown

csv catch warning fix

---

std/random.d

The random number generators defined in std.random don't allocate. This allows instances of them to be used in statically verified GC free code.

Make most random number generator methods @nogc.

---

std/array.d

Related: http://forum.dlang.org/post/ner843$2cag$1@digitalmars.com but this is an improvement regardless of one's opinion of `inout`.

Simplify overlap

---

std/algorithm/searching.d
std/algorithm/sorting.d
std/net/isemail.d

From looking at these enums it seems they can only be yes/no enums, so for the sake of being able to use Yes and No structs at the call site I changed these to be Flags.
Here's a relevant forum post from me: https://forum.dlang.org/post/dsveniziykybybgpfgnp@forum.dlang.org

[trivial] Convert yes/no enums to std.typecons : Flag

---

std/typecons.d

enables the use of NaN as a the null value of Nullable!float
https://issues.dlang.org/show_bug.cgi?id=11135

Issue 11135 - Nullable(T, T nullValue) does not support NaN

---

std/algorithm/sorting.d

This introduces specialized routines for short arrays, which are the end game of quicksort. This allows being more aggressive with the small data threshold. Results show a 4% improvement for sorting large arrays of random doubles and 8% improvement for sorting real-world 1-gram frequencies (column 2 in the dataset https://issues.dlang.org/show_bug.cgi?id=16517).

Optimized sort, 4%-8% speed improvements

---

std/net/curl.d

This feature will hopefully be deprecated soon.

[TRIVIAL] Remove last use of implicit string concatenation

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/package.d
std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d

This is part of #4652. `ndMap` was renamed to `mapSlice`, it is correct, because we already have this  `iotaSlice`, `indexSlice`, and `repeatSlice`. Other `ndXXX` algorithms are not part of this PR.
Additional changes:
1. [Issue 16501 fixed](https://issues.dlang.org/show_bug.cgi?id=16501)
2. Some private / package / undocumented stuff from `.slice` now public and moved to `.internal`. This is done to allow Mir to remove already accepted modules from its code base.
3. `Pack` and `Map` in internal is stuff that is new (but already reviewed in #4652).
The last commit also fix [issue 16503](https://issues.dlang.org/show_bug.cgi?id=16503).

add mapSlice and fix  Issue 16501

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d

There are 2 commits with different template bloat optimizations. `auto ref` was also removed.
This PR follows suggestions from @aG0aep6G and @timotheecour  from the thread http://forum.dlang.org/thread/njcoyysqeqhbejxperyv@forum.dlang.org?page=1

reduce ndslice template bloat

---

std/algorithm/sorting.d

New algorithm `pivotPartition`. I considered adding it as an overload to `partition` but the charter and working is sufficiently different. We should be able to use this in `sort`.

Add pivotPartition

---

std/experimental/ndslice/slice.d

Motivation:
1. most `ndslice` users would be scientists without engineering experience. `ndslice` should provide a set of simple concepts, that will help scientists to start use it. Otherwise we will lose our potential users.
2. It is optimised to reduce template bloat in case of the identical type

add ndslice.slice.as

---

std/typecons.d

Clean up a couple of deprecated features used in Unique.

Unique cleanup

---

std/algorithm/sorting.d

This is a clean redo of https://github.com/dlang/phobos/pull/3922, which I'll close. Two ideas here:
1. Use the new medianOf functions to take the median of 3/5 as a pivot heuristic
2. Add a unittest that counts total comparisons so we don't regress performance

Use medianOf 3 and 5 to estimate pivot

---

std/file.d

I removed the call to `dirEntries` altogether, as it's not needed to make sure the function compiles. As [the original bug writeup for 15319](https://issues.dlang.org/show_bug.cgi?id=15319) shows, this test is only to make sure this function always compiles, but the original author simply copied the testcase with `dirEntries` from bugzilla.  Since that adds nothing to a simple compile check, I just removed it.
__Update:__ also marked this test as `@safe` now.

Fix Issue 16571 - Unittests should not list /tmp/ recursively

---

std/parallelism.d

The `Thread.opApply` static method will use `realloc` from `core.stdc.stdlib` instead of `gc.gc.GC.malloc` which sometimes fails with `onInvalidMemoryOperationError` when run within a `static ~this` module dtor
```
(gdb) bt
#0  0x00007f17edd2a9c8 in raise () from /lib64/libc.so.6
#1  0x00007f17edd2c65a in abort () from /lib64/libc.so.6
#2  0x0000000001352f5e in _d_throwdwarf ()
#3  0x00000000013d0a69 in onInvalidMemoryOperationError ()
#4  0x00000000013b832e in gc.gc.GC.runLocked!(_D2gc2gc2GC12mallocNoSyncMFNbmkKmxC8TypeInfoZPv, _D2gc2gc10mallocTimel, _D2gc2gc10numMallocsl, ulong, uint, ulong, const(TypeInfo)).runLocked(ref ulong, ref uint, ref ulong, ref const(TypeInfo)) ()
#5  0x00000000013b1c8a in gc.gc.GC.malloc(ulong, uint, ulong*, const(TypeInfo)) ()
#6  0x0000000001350be3 in …
```

Avoid GC Allocations in sharedStaticDtor

---

posix.mak
std/internal/phobosinit.d
std/internal/processinit.d
std/process.d
win32.mak
win64.mak

- partially Revert "Merge pull request #4493 from schveiguy/fixcycles2"
- recreate processinit (and import it from std.process)
to call std.process shared ctor w/o creating a cycle
- keep it separate from phobosinit to not drag std.encoding
into any binary using std.process

fix Issue 16580 - spawnShell segfaults on macOS

---

std/typecons.d

- we can't really solve Issue 15316 w/ signaling NaNs
b/c any optimization, copying et.al. might turn signaling into
quiet NaNs, therefor we want to solve Issue 15316 by switching
Float.init to use quiet NaNs
- the workaround depends on a specific dmd bug (see dlang/dmd#6163)
that looses SNaNs when writing struct initializers but keeps
them for Float.init
- this workaround might not be portable to GDC/LDC and
will easily break w/ slightly different dmd optimizations
(it's responsible for the test failure of the gdc-built dmd)
- this PR will reopen https://issues.dlang.org/show_bug.cgi?id=11135
this partially reverts commit 0efa1d3bf92bcaa6c4a99cad0b574185a537906a

fix gdc-dmd test - remove the workound for Issue 15316

---

std/range/primitives.d

Fix typo in moveAt doc

---

std/conv.d

`emplace` requires the buffer to have the same or higher alignment than the emplacement type.
(bug found with LDC)

[Trivial] Fix alignment of std.conv emplacement test buffers.

---

std/range/primitives.d

As per title.
On average 15% more performance because of smaller code and avoiding bsr

20% more performance for popFront(char[])

---

std/container/util.d

Model-checking that forbids construction of containers from infinite generators.

Restrict making of containers to non-infinite ranges

---

std/regex/internal/bitnfa.d

This speeds up BitNFA a little bit as all reads are for apriori existing items.

[std.regex] Optimize reads from hash table

---

std/algorithm/searching.d

Also remove typo.
This example is taken from the docs for `std.range.only`, but is more useful here.

[trivial] Add findSplitBefore example with an element using only()

---

std/traits.d

- gets parsed as is(Type Identifier) but an alias identifier isn't needed
- fixup of ee683ae79f (#2624)

remove spurious x identifier in IsExp

---

std/path.d

This typo is especially painful when you know you want to search for the word "transforms" and you don't get all the hits you know you should :/

The word "tranforms" is a typo, should be "transforms"

---

std/traits.d

- workaround scope escape error to get default parameter
- would require a working `return scope` for a proper implementation
Got broken by https://github.com/dlang/dmd/pull/5903

fix Issue 16582 - ParameterDefaults fails w/ scope parameter

---

std/experimental/ndslice/slice.d

This is required
1. To reduce template bloat in generic GLAS.
2. For precompiled GLAS API.
All Mir tests pass

{please} Implicit cast to const slices

---

std/socket.d

https://github.com/dlang/phobos/pull/4273
https://issues.dlang.org/show_bug.cgi?id=16514

Revert #4273 + add test

---

std/experimental/ndslice/slice.d

I thought #4869 was merged to stable. The same commit, but for stable. ping @MartinNowak

❗️❗️❗️Implicit cast to const slices in case of underlaying range is a pointer.

---

std/meta.d

The issue was that PR #4374 introduced a private symbol (`SmartAlias`) between `ApplyLeft` and `ApplyRight`'s and they're ddoc-ed unittests. Since ddoc-ed unittests bind to first symbol above them and that symbol was private, they were omitted from documentation.
Also put the signature of `isImplicitlyConvertible` in a comment to make the example more clear.

Resurrect ApplyLeft and ApplyRight's documentation

---

changelog.dd
std/traits.d

Add a `Promoted!T` trait which evaluates to the type used for (non-unary) arithmetic operations on type `T`. Example: `static assert(is(typeof(Promoted!ubyte == int)));`.

Add `Promoted` to `std.traits`.

---

.dscanner.ini
std/file.d
std/internal/math/biguintcore.d
std/mmfile.d
std/zlib.d

1. delete is scheduled for deprecation
2. delete is unsafe: https://github.com/dlang/dmd/pull/5887
3. the GC should be the one to decide when things should be freed

Remove all uses of the delete keyword and enable the Travis check

---

std/regex/internal/parser.d

Should fix out of memory problems with ctRegex.

[std.regex] Disable Bit-NFA in CTFE

---

std/algorithm/comparison.d

* If one of the ranges has `Range.empty == true`, we can define `equal` even when each `front` is not comparable.
* If one range is known to be infinite and the other defines `length`, return false.
* If both are known to be infinite, cause a compile-time error.

Fix Issue 16628 - std.algorithm.equal for known empty or infinite ranges

---

std/experimental/ndslice/slice.d

The problem with this PR and the Issue is that toMurmurHash may looks too complex to mark it `@trusted`.

fix issue 16609

---

std/meta.d

Please review! Let me know if this example is appropriate.
Link: https://issues.dlang.org/show_bug.cgi?id=8799
Thank you!

fix issue 8799

---

std/file.d
std/traits.d

A string-typed enum passes isSomeString but not isConvertibleToString.
Because isConvertibleToString is used as a template constraint for
std.file.exists, it could not be passed a string-typed enum.
Resolves [#16573](https://issues.dlang.org/show_bug.cgi?id=16573).
Also see [the forum discussion](http://forum.dlang.org/thread/zjkxomchxheycsgpevzh@forum.dlang.org).
@jmdavis

Ensure std.file.exists(StringEnum.name) compiles.

---

std/experimental/ndslice/selection.d

Added some docs and unittest example on how to select overlapping blocks in ndslice API. Inspiration for PR is from libmir/mir#369.
Pinging @9il. This is my first PR to any of dlang repos, so please help by pinging relevant people for English clarity checkup on what I have added.

[docs] [ndslice] Hint on overlapped blocks

---

etc/c/zlib/win64.mak

phobos.lib is agnostic to the used MS C runtime, but preselects one. Creating the automatic reference when building main/WinMain/DllMain is good enough.
Needs corresponding druntime change to be effective: https://github.com/dlang/druntime/pull/1691

Issue 12125: do not enforce specific MS runtime

---

std/algorithm/setops.d
std/algorithm/sorting.d

Removing the one that refers to std.algorithm.setops.SetUnion, because
that is not documented anymore (it's deprecated). This overlaps very slightly with #4888.
Targeting stable to minimize the chance of XREF creeping back in again. master would work too, but I'd like to finally get this over with.

[Ddoc] XREF -> REF

---

std/random.d

Added a choice() function to std.random as it was being discussed in the issue. The function returns a random element from a given Range. If no uniform random number generator is supplied, it will default to rndGen.
I read the D Style Guidelines and I hope I managed to comply with all of them.
https://issues.dlang.org/show_bug.cgi?id=4851

enhancement issue 4851: add choice function to std.random

---

std/stdio.d

@JackStouffer please redo that change against master (after the merge of stable) with symbols
undergoing deprecation phase for at least one release first.

Fix issue 16682: "privatization" of symbols in std.stdio breaks DFMT

---

std/format.d

- fix incorrect pointer diff computation introduced by PR #4427
commit 2be035584f31131ebd3e2123b19f457c326d070d

fix Issue 16661 - failing dstring/wstring format string

---

posix.mak

On some FreeBSD the unittest timeout with increased frequency, hence this change.

Increase time limit

---

std/parallelism.d

At the time std.parallelism was developed, module-level ddoc-ed unittests weren't available and probably that's why nobody noticed that example from the module synopsis broke.

Fix issue 16705 - TaskPool.reduce fails to compile "cannot get frame pointer to D main"

---

std/container/rbtree.d

This request removes a void initializer from `_add` and makes most unittests in `std.container.rbtree` `@safe.`
I also added `pure` attribute for unittests.

Make std.container.rbtree.RedBlackTree._add @safe

---

std/uni.d

https://issues.dlang.org/show_bug.cgi?id=16663
I have completely reverted https://github.com/dlang/phobos/pull/4790 because change is non-trivial (and even PR itself contains open discussion) and we need point release out ASAP.

Fix issue 16663: std.unit.toUpper rejects an alias this to a string

---

std/algorithm/sorting.d

The LREFs were broken. Could fix that with underscores, but the links would
just point back at the current section. There's no point in having such
links.

remove pointless LREFs

---

std/parallelism.d

I accidentally swapped the two numbers in the previous PR.

Fix typo introduced in PR #4915

---

std/variant.d

std.variant: Minor fixes

---

std/conv.d

Also document `to` template functions within parent `to` template.

[trivial] std.conv: Don't allow to!T() in constraint

---

std/conv.d

* Use specialization to prefer `to!S` when S is a static array.
(For background, see https://github.com/dlang/phobos/pull/4898#issuecomment-262796333)
Ping @schveiguy.

Really fix Issue 16478 - Don't allow to!T() in constraint

---

std/range/primitives.d

Technically, prior to this change, it was possible to define popFront
and popBack to be callables that required parens - such as member
variable with an overloaded opCall or a delegate. It's unlikely that
anyone has actually declared popFront or popBack in this manner, but
it's possible. Because of that, calling popFront or popBack without
parens would technically not work with some valid ranges (even if such
ranges are unlikely to exist) and thus without this change, it's
arguably not valid to call popFront or popBack without parens in generic
code - especially in the standard library.
Andrei wants to be able to call popFront without parens in generic code,
and when I pointed out the existing problem with that, he wanted me to
change it so that it's no longer legal to have a range where …

Require that popFront and popBack be callable without parens.

---

std/variant.d

* Add `VariantN.opIndexOpAssign`.
* Also undocument & tweak test for `const(Variant).opIndex`.

Fix Issue 16758 - Variant.opIndex result not modified after opAssign

---

std/algorithm/searching.d
std/format.d

Added functionality so that find can take advantage of SortedRange's functions when:
1. A single element is searched in a SortedRange.
2. A a range is searched in another range and both ranges are SortedRange with the same signature

Issue 8829 - std.algorithm.find fails to take advantage of SortedRange

---

std/container/binaryheap.d

If Store does not have the ```dup``` property, then dup is not available for the BinaryHeap either.

fix issue 13314  - BinaryHeap assumes Store has dup property 

---

std/format.d

Added raw reading for integers

Issue 5236 - raw reading for integers and a few refactorings

---

.dscanner.ini
circleci.sh
posix.mak
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d
std/array.d
std/conv.d
std/csv.d
std/datetime.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/package.d
std/experimental/ndslice/slice.d
std/parallelism.d
std/random.d
std/range/package.d
std/regex/internal/backtracking.d
std/regex/internal/bitnfa.d
std/regex/internal/ir.d
std/regex/internal/parser.d
std/regex/internal/shiftor.d
std/regex/internal/tests2.d
std/signals.d
std/typecons.d
std/uni.d
unittest.d

It seems like we/I accidentally disabled the style target on CircleCi (`style` is not defined in the command switch). I take the full blame for this, but at least it's a good proof that the CI actually does catch quite a few things ;-)
I split up the fixes depending on their category.
There's only [one line](https://github.com/dlang/phobos/blob/master/std/regex/package.d#L421) left about which DScanner is complaining (hence the "blocked" label):
```
public static immutable ctRegex(alias pattern, alias flags=[]) = ctRegexImpl!(pattern, flags).nr;
```
It warns with:
```
std/regex/package.d(421:32)[error]: Declaration expected
std/regex/package.d(421:62)[error]: Declaration expected
std/regex/package.d(421:64)[error]: Declaration expected
std/regex/package.d(421:97)[warn]: Empty declaration …
```

Fix CircleCi style checker

---

std/variant.d

The documented tests all use `Variant` (which is already instantiated outside of `VariantN`) - so only compile the tests when VariantN is Variant.
* Also move a non-documented unittest out of `VariantN`.

std.variant: Guard documented unittest members in VariantN

---

std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d

Changes:
1. not `nothrow` API is deprecated. An alternative more flexible API is provided.
2. Internal binary representation is public now. It is required for user implemented ndslice plugins.
3. remove `byElement` specialisation for N = 1
After this be merged `ndslice` will be 100%:
1. no-throw
2. @nogc
3. betterC compatible
4. friendly for non-phobos plugins like `mir.ndslice.algorithm`.
5. Generic only (source library, no need to compile)

std.ndslice migration preparation

---

std/algorithm/sorting.d
std/container/binaryheap.d
std/internal/test/dummyrange.d

I rebased https://github.com/dlang/phobos/pull/3865 which seems abandoned.
The test for ranges still fails unless I use the cheat to transform the range to an array before passing it to topN and sort (which defeats the purpose of the test actually). It might be a problem with DummyRange, I'm still looking into it, but ideas are welcome.
https://issues.dlang.org/show_bug.cgi?id=15421

fix issue_15421 [reloaded] - The behaviours of the topNs differ with the bottom

---

posix.mak
std/algorithm/setops.d
std/internal/math/gammafunction.d

As suggested [here](https://github.com/dlang/phobos/pull/4940#discussion_r91747540) this simply enforces a common style for `do` blocks, or in other words this will forbid the verbose `do {` followed a newline. Inline `do`s are still allowed, e.g.:
```
> grep -i 'do *{' **/*.d
std/path.d:            do { ++j; } while (j < path.length && isDirSeparator(path[j]));
std/path.d:                do { ++j; } while (j < path.length && !isDirSeparator(path[j]));
std/process.d:    do { s = tryWait(pid); } while (!s.terminated);
```

Enforce Allman style for do {

---

std/numeric.d

After conducting some benchmarks we arrived to the conclusion that currently the dmd compiler works best with Euclid's algorithm for GCD, othewise we use Stein's algorithm for ldc or gdc.
https://issues.dlang.org/show_bug.cgi?id=4125

Fix Issue 4125 - std.numeric.gcd can use a binary GCD

---

std/algorithm/sorting.d

I added the functionality so that partialSort accepts two ranges and I also modified the overload which takes a range and an index to call the overload I implemented.

Issue 14294 - partialSort should also accept two ranges

---

posix.mak

update dscanner to 0.4.0-beta.3
`sed -i` isn't portable across all posix, so we just do it out-of-place and mv

make style improvements

---

std/process.d

In accordance with https://github.com/dlang/phobos/pull/4938#discussion_r91655136 and https://github.com/dlang/phobos/pull/4938#discussion_r91655158

use WindowsException for errors from windows api

---

changelog.dd
std/meta.d

This is a logical counterpart to `std.meta.staticSort`.
Among other possible uses, `isStaticSorted` could facilitate major reductions in template bloat for templates with a variadic parameter that either requires sorting, or is order-independent.
Also included in this PR is a second commit which optimizes `std.meta.staticSort` to skip unnecessary calls to the **O(N^2)** `staticMerge` when `top` and `btm` do not need to be interleaved. In my tests, this makes `staticSort` about 3x faster **and** reduces compile-time memory consumption by about 3x (about **80 MB**!) for reverse-ordered **N = 450**. It also appears to benefit smaller **N** to a lesser degree, although it's hard to tell how much.

Add `std.meta.isStaticSorted`

---

circle.yml
circleci.sh
posix.mak
std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/sorting.d
std/exception.d
std/experimental/ndslice/slice.d
std/experimental/typecons.d
std/format.d
std/json.d
std/path.d
std/range/primitives.d
std/regex/package.d
std/string.d
std/uni.d

This is an effort to revive https://github.com/dlang/dlang.org/pull/1297, which will allow to run unittests directly on dlang.org
The main problem is that for quite many snippets we don't know which imports are needed. The proposed solution is to extract all unittest blocks from Phobos and execute them :)
To ensure that the snippets on dlang.org will be runnable in the future this PR adds a new Makefile target `publictests` and enables this in the CircleCi setup. I opened a PR at the tools repo for  the extraction script: https://github.com/dlang/tools/pull/203 on which this PR obviously depends on.
As a start this PR also contains "fixes" to a couple of modules by adding required local imports to their public unittests.
The idea is to gradually increase the number of supported modules …

Add check for public unittests

---

std/array.d

For the second demo I managed to replace all imports with selective imports in std.array. It was a major effort that involved grepping for heuristics such as "static if", "typeof", "^if", "compiles", "has", "\Wis" etc. A few examples of the difficulties for fun:
1. Remove `isStaticArray` from the import list. The error is:
```
std/conv.d(4169): Error: static assert  "DirIteratorImpl cannot be emplaced from (string, SpanMode, bool)."
std/conv.d(4250):        instantiated from here: emplaceRef!(DirIteratorImpl, DirIteratorImpl, string, SpanMode, bool)
std/typecons.d(4998):        instantiated from here: emplace!(DirIteratorImpl, string, SpanMode, bool)
std/typecons.d(5091):        instantiated from here: initialize!(string, SpanMode, bool)
std/file.d(3802):        instantiated from here: …
```

[DEMO for DIP1005] Converted imports to selective imports in std.array

---

std/experimental/ndslice/internal.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/package.d
std/experimental/ndslice/selection.d
std/experimental/ndslice/slice.d

Including ndslice to Phobos was my mistake. It is better to distribute it as DUB package. Please merge this PR. Phobos synchronization terrificly slowdown ndslice packages development, also Phobos is a classic D library while Mir projects require strong BetterC guaranties. I has not enough resources to maintain both Mir and Phobos versions. Hope this will be merged and users would not be confused anymore by Mir and Phobos ndslices incompatibility.
ndslice author

deprecate std.experimental.ndslice

---

std/algorithm/sorting.d

This is revival of my previous https://github.com/dlang/phobos/pull/3315 applied on top of existing implementation of `merge` that sneaked in without me noticing it ;)
**Improvements**:
- Bidirectional support if all inputs are bidirectional
- Propagates infiniteness if any of the inputs is infinite.
- Add in-place checking of sortedness in `popFront` and `popBack`. Done by comparing current and next element if element type allows it.
**Other notes**:
- Checking for `isSortedRange` in my previous implementation has been removed because we currently cannot compare all the different formats for the comparison alias (`pred`) fed to `SortedRange`.
**Update**:
I just noticed that `Merge` is used in setops. I guess this removes the opportunity for making this a Voldermort type, right?

Improve merge() algorithm

---

std/range/package.d

Add a generic bitwise adapter to std.range

[WIP] std.range: implement bitwise adapter over Integral type Ranges

---

std/algorithm/mutation.d
std/algorithm/searching.d
std/algorithm/sorting.d

from the H2 2016 agenda:
> Make sure every function in Phobos has an example
So I went ahead a wrote a [small script](https://github.com/wilzbach/style-checkers/blob/master/has_public_example.d) that search for all public functions that violate don't come with an example.
This here is more a proof of concept of the script. However my plan would be to go similarly as with runnability of the tests and start with a exclude list of modules and gradually decrease it.
Ideally I would like to add such checks (like e.g. the other for [missing Returns/Params](https://github.com/Hackerpilot/Dscanner/pull/390)) to Dscanner (CC @Hackerpilot). Is this possible or should I add them somewhere else, e.g. the `tools` repo or directly here?
Related Bugzilla Issue: …

Add public examples to std.algorithm

---

changelog.dd

Add changelog entry about ndslice removal

---

std/traits.d

https://issues.dlang.org/show_bug.cgi?id=16653

fix issue 16653 - ParameterDefaultValueTuple fails to compile when function has lazy param 

---

std/typecons.d

* Use `auto` function return instead of ReverseTupleType as that is private.
* Document `tuple` function inside template.

Improve tuple-related docs

---

std/math.d

There was duplicate code in core.math and std.math: the same function declarations and the same unittests. yl2x and yl2xp1 are implemented in the compiler.
There is indeed no proper documentation for their existence in phobos. I could not find documentation for core.math.yl2xp1 either. Maybe it should be added as part of this PR?
So far, I removed these functions from phobos, since they are available in core.math and std offers no extra functionality with regard to them. Please let me know if there is a valid reason for keeping them in both druntime and phobos. If that is the case, we can simply document the situation.

fix issue 16634 -  std.math exposes yl2x and yl2xp1 publicly

---

circle.yml
circleci.sh

I just realized that for https://github.com/dlang/phobos/pull/4921 the style check fixes aren't included. In general it makes a lot of sense to merge to merge with the upstream branch, s.t. changes are always tested as they would be merged (@CyberShadow's DAutoTest behaves similarly). While I was at the file I did a few tiny improvements:
- provide default value for `CIRCLE_NODE_INDEX` (makes the script easier to run
manually)
- move setup_repos before style task, s.t. the latest style requirements
are enforced
- removed exclusion of failing modules for the individual module
coverage tests (this is due to @schveiguy's & @MartinNowak's [work](https://github.com/dlang/phobos/pull/4840) on [issue 16291](https://issues.dlang.org/show_bug.cgi?id=16291). Thanks!)
CC @MartinNowak

[CircleCi] updatebuild script: merge with upstream branch

---

std/experimental/allocator/building_blocks/free_list.d

https://issues.dlang.org/show_bug.cgi?id=16352
Also fixes ```deallocateAll``` not updating free list count and dereferencing after free which were found in the process.

Fix issue 16352 - dead-lock in std.allocator.free_list unittest

---

std/string.d

This is a trivial change to take advantage of
std.exception.basicExceptionCtors and avoid having StringException
explicitly declare the normal exception constructors. It also has the
advantage of adding the second constructor that was missing from
StringException.

Make std.string.StringException use basicExceptionCtors.

---

std/experimental/allocator/building_blocks/free_list.d

https://issues.dlang.org/show_bug.cgi?id=16352
#4988 Fixed the cause, this allows the test to fail properly.
What was typically happening was
```
private void decNodes() shared
{
assert(nodes);
atomicOp!("-=")(nodes, 1);
}
```
Would fail the assertion (because of data race.) 
I don't know why ```scope(exit) tid.send(true);``` didn't allow the main thread to exit.
Anyway, instead I used ```ThreadGroup.joinAll``` to rethrow exceptions in the unit test thread.

Addendum PR4988 - dead-lock in std.allocator.free_list unittest

---

std/digest/sha.d
std/internal/digest/sha_SSSE3.d

- access SHA1 constants through extra register in x64 code
- tried same for x86 (several hours) but there is no register left and
loading constants via stack was way too slow
- little to no interest in x86 PIC code, as the platform is almost dead, and PIC is too slow on x86 anyhow
Roughly 10x faster (now also with shared phobos library).
Prerequisite to fix [Issue 16794 – .deb not working on Ubuntu 16.10 because of default PIE linking](https://issues.dlang.org/show_bug.cgi?id=16794).

partly fix Issue 9378 - SHA1 asm not PIC compatible

---

std/array.d

Revert "[DEMO for DIP1005] Converted imports to selective imports in std.array"

---

std/range/package.d

Follow-up to @edi33416's https://github.com/dlang/phobos/pull/4927 (which imho was merged too early) and adds some of my unaddressed review comments:
- adds to booktable (s.t.  it's listed on the [docs](http://dlang.org/phobos-prerelease/std_range.html)
- adds `bitwise` and hides the helper struct (no need to expose it and gives more flexibility later. The exposed public symbols are a relict)
- adds a nice public example and hides the internal tests (see [current docs](http://dlang.org/phobos-prerelease/std_range.html#.Bitwise) for the motivation
- fixes style (no parenthesis for `@property` functions)
- fixed various typos
- removes `__PRETTY_FUNCTION__` from `assert` (current Phobos policy is to use plain `assert`. Improvements to `assert` should be done in the compiler)
- addresses …

First cleanup of bitwise adapter + add to docs

---

std/regex/internal/parser.d

- consumes too much memory, introduced by
e98fa4ad5ad39487844c91357cfec4f698e88230 (#4286)

disable kickstart in ctfe to workaround Issue 16626

---

std/typecons.d

Such construction helpers are there for literally every other type in Phobos, even in the same module, e.g. `refCounted`, `rebindable`, `tuple` - so I assume it was just forgotten?

Add nullable{,Ref} construction functions

---

std/algorithm/iteration.d
std/exception.d
std/range/package.d
std/socket.d
std/stdio.d
std/utf.d

Fixed ddocs in order to remove warnings when compiling html phobos, as mentioned on [bugzilla](https://issues.dlang.org/show_bug.cgi?id=16970).
I did not touch std/experimental/ndslice, since it's going to be deprecated.

Fix issue 16970 - Fix deprecations and warnings when compiling Phobos

---

std/algorithm/sorting.d

Noticed this here: https://dlang.org/library/std/algorithm/sorting/sort.html

Fix unstable sort documentation.

---

std/algorithm/comparison.d

Pretty trivial - as `format` was used in the lazily evaluated `assert` error, but I didn't know of a good way to test for `static assert` errors.
Moreover, I added the (modified) example from the bug as one can never have enough tests ;-)

Fix Issue 16135 - missing std.format import in std.algorithm.comparison

---

std/conv.d

Based on Andrei's advice in https://github.com/dlang/phobos/pull/4674, I cleaned up the code here.
Now even faster. 
Built with `ldc2 -O5 -release`, [code here](https://gist.github.com/JackStouffer/42aae01b9cd4c86ae42086642270b407#file-test-d).
```
Total time: 10 ms, 730 μs, and 5 hnsecs
#current
Total time: 36 ms, 573 μs, and 4 hnsecs
#old
Total time: 181 ms, 850 μs, and 5 hnsecs
```

Cleaned up auto decoding special case in std.conv.parse for integers

---

changelog.dd
std/traits.d

As discussed in #4274 the std.traits API for querying after function attributes is not very user-friendly.
```
functionAttributes!((int a) { }) == (FunctionAttributes.pure_ | FunctionAttributes.nothrow_ | FunctionAttributes.nogc | FunctionAttributes.safe
```
wouldn't it be nicer, if we have a dedicated function for this?
```
hasFunctionAttributes!((int a) { }, "pure", "nothrow", "@nogc", "@safe"); 
```
Imho this makes it a lot more intuitive for the user to read and easier for us to maintain.
I heard about a DIP to cleanup and unify function attributes, so having a function allows us to stay flexible for the future ;-)
Btw the `trait` `getFunctionAttributes` already returns a string tuple.
Ping @ntrel

std.traits: hasFunctionAttributes

---

std/conv.d

New version of https://github.com/dlang/phobos/pull/4674
13.5x faster! [Code here](https://gist.github.com/JackStouffer/0cf93d3cc861d699b334e18ea67fb66c#file-test-d).
```
Total time: 387 ms, 506 μs, and 8 hnsecs
Total time: 5 secs, 238 ms, 59 μs, and 4 hnsecs
```

Removed auto-decoding from the floating point version of std.conv.parse

---

std/getopt.d

Looks like an useless(in outer code) enum constant exist in module std.getopt. The documentation keep silence about this too. I decided to make it private and make a small contribution to this amazing library and language.

Make std.getopt.autoIncrementChar use private modifier

---

std/datetime.d

The POSIX version of **struct tm** has no **tm_gmtoff** field.
This field is a BSD extension.
In GNU C library this field is derived from BSD.
This pull fixing Clock.currTime() wrong return in Solaris.

Solaris: fix std.datetime:LocalTime.utcToTZ issue.

---

std/traits.d

ketmar said:
> and now one can't have argument with name `value` anymore, 'cause it conflicts with `value` variable in fix. dunno if it worth opening new bug, tho, 'cause fix is not in any release yet, so it can be... fixed right here. ;-)
So changing the name to be more wild, same as the line next to it, makes namespace collision less likely.

better workaround for issue 16653, fix ketmar comment

---

README.md

The CircleCI badges seems to use the _lastest_ build by default and thus it's
[currently](https://github.com/dlang/phobos/blob/master/README.md) showing "Failed" even though everything is green.
This fixes the CircleCi badge/shield to the `master` branch. [Preview](https://github.com/wilzbach/phobos/blob/a4182ab6dc2327cd0b146aea62e22bb6b16b08a6/README.md).

CircleCI badge: only show build status for the master branch

---

changelog/README.md
changelog/ndslice-removal.dd
changelog/std-algorithm-searching-maxindex.dd
changelog/std-algorithm-searching-minindex.dd
changelog/std-meta-statisissorted.dd
changelog/std-traits-hasFunctionAttributes.dd
changelog/std-traits-promoted.dd

As discussed at the [newsgroup](http://forum.dlang.org/post/pbfgjdvhvfgobcpnlvfb@forum.dlang.org) I think it would be more painless if we put the pending changes into a folder, s.t. that no merge conflicts arise anymore. 
- I also found that we can eliminate one main error source - the `$(LI )` ddoc macro and make it even easier to add entries as one entry is always one item
- For cross-platform compatibility (and maybe further improvements) I included a small script that builds the changelog from all pending entries.
- I added small README that should provides instructions to contributors
- I use a `p_` prefix, s.t. removing the pending entries is easier, but this is not required.
- I copied all pending entries into the new format
I am happy to hear your feedback.
Pinging @CyberShadow …

move changelog to a folder

---

posix.mak
std/bitmanip.d
std/concurrency.d
std/conv.d
std/csv.d
std/datetime.d
std/digest/sha.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/logger/core.d
std/experimental/logger/nulllogger.d
std/file.d
std/net/isemail.d
std/numeric.d
std/stdio.d
std/utf.d

Follow-up to #4943: this PR reduces the module exclusion for modules that can be run on dlang.org
For this all tests within a module need to pass separately _without_ the module.

Make more modules publicly runnable on dlang.org

---

std/digest/crc.d

- use slicing by 8 algorithm with bigger precomputed tables
- roughly 4x faster

faster CRC32 implementation

---

std/array.d

* Expand some docs.
* Inline undocumented `T`, `AppenderType`.
* Merge `opOpAssign` overloads.
* Document `RefAppender.opDispatch`.
* Rename `appender(E[]*)` parameter -> `arrayPtr` to better distinguish from
`appender(E[])`.

Improve docs for Appender, RefAppender

---

std/internal/scopebuffer.d

* Respect `realloc` parameter.
* Fix ddoc for commented out `this(this)` concatenated into `put`'s docs.
* Fix missing ddoc for `put(CT[])` due to private `CT`.
* Use documented unittest for scopeBuffer instead of inline code (which had a typo).

Tweak std.internal.scopebuffer docs

---

circleci.sh

Short follow-up to https://github.com/dlang/phobos/pull/4964 - this should make CircleCi more resilient when used with branches that don't exist at DMD / Druntime, so this shouldn't be the usual case.

CircleCi: use master as fallback for DMD and Druntime

---

std/meta.d

the documentation of anySatisfy was identical to allSatisfy.
Which is of course wrong.

correct anySatisfy docs

---

std/conv.d

Increase the performance of `textImpl` by
* Reducing GC allocations with numbers by using `toChars` rather than `to`, which allocates a temporary array and then throws it away
* Using a very dumb heuristic to pre-allocate space for the elements 
Just adding the `toChars` case gave a small boost in LDC and no difference in DMD. But, the heuristic added a lot of performance.
Recording performance gains of 12.8% with LDC and 5.5% with DMD
```
result	1 sec, 435 ms, 49 μs, and 4 hnsecs
result2	1 sec, 251 ms, 957 μs, and 6 hnsecs
$ dmd -O -inline -release -noboundscheck test.d &&./test
result	2 secs, 510 ms, 745 μs, and 2 hnsecs
result2	2 secs, 372 ms, 147 μs, and 4 hnsecs
```
The code
```
import …
```

Slight optimization for std.conv.text/wtext/dtext

---

std/traits.d

* Fix non-existent parameter names for `hasFunctionAttributes`.
* Fix order of constraint tests.
* Fix wrong use of `REF` macro.

Tweak std.traits function-related docs

---

changelog.dd
changelog/std-range-bitwise.dd
std/range/package.d

This PR brings the following:
- Fixed opSlice bug.
- More unittests.
- A changelog entry
- Fixed typos
- There were mixed tabs and spaces in `changelog.dd`. Now there are only spaces.

Bitwise cleanup: Fix opSlice index error. Add unittests and changelog entry

---

std/typecons.d

I was getting sick of this not working, and there have been multiple bug
reports on this, so I'm just fixing it. With these changes, using == and
!= on null Nullables will not result in an AssertError but instead will
consider them equal if they're both null, equal if they're both non-null
and have the same value, and not equal otherwise.

Fix issue #13017: opEquals for null std.typecons.Nullable

---

std/algorithm/searching.d

> If both operands are pointers, and the operator is -, the pointers are subtracted and the result is divided by the size of the type pointed to by the operands. **It is an error if the pointers point to different types**. The type of the result is ptrdiff_t.
See DMD's [PR](https://github.com/dlang/dmd/pull/6440)

Cast a void pointer to char* before subtracting it

---

std/concurrency.d
std/container/rbtree.d
std/experimental/typecons.d
std/socket.d

very few actually since phobos almost always use `struct`. Mostly some `private final`. See also https://github.com/dlang/druntime/pull/1745.

style fix - remove wrong usages of the final attribute

---

std/experimental/allocator/package.d

The dispose function now checks recursively if there are multidimensional arrays allocated and deallocates them accordingly

Fix Issue 16824 - std.experimental.allocator.dispose leaks memory 

---

std/algorithm/iteration.d
std/regex/internal/tests3.d

Make joiner work with ranges that have immutable members.

Fix issue 17066

---

std/experimental/allocator/building_blocks/kernighan_ritchie.d

```
The smallest size that can be allocated is two words (16 bytes on 64-bit systems, 8 bytes on 32-bit systems).
```
The reason for this bug was that sometimes the buffer only had two words left free which were never allocated. When deallocating, coalescing is done based on adjacent blocks/nodes and this doesn't take into consideration this remaining space. Actually this space is completely erased in ```allocate```:
```
if (balance >= Node.sizeof)
{
}
else
{
root = null; // auch
}
```
When deallocating one by one and coalescing the blocks back together, this gap is omitted. A simple check  on the root for a gap < Node.sizeof (2 words) after a dealloc should ensure that the gap is ultimately summed up to the size of the root node (upon the last dealloc),

fix issue 16564 - KRRegion.empty sometimes returns Ternary.no

---

etc/c/zlib.d
etc/c/zlib/ChangeLog
etc/c/zlib/README
etc/c/zlib/adler32.c
etc/c/zlib/compress.c
etc/c/zlib/crc32.c
etc/c/zlib/deflate.c
etc/c/zlib/deflate.h
etc/c/zlib/gzguts.h
etc/c/zlib/gzlib.c
etc/c/zlib/gzread.c
etc/c/zlib/gzwrite.c
etc/c/zlib/infback.c
etc/c/zlib/inffast.c
etc/c/zlib/inflate.c
etc/c/zlib/inflate.h
etc/c/zlib/inftrees.c
etc/c/zlib/trees.c
etc/c/zlib/uncompr.c
etc/c/zlib/zconf.h
etc/c/zlib/zlib.3
etc/c/zlib/zlib.h
etc/c/zlib/zutil.c
etc/c/zlib/zutil.h

These are the changes updating zlib from 1.2.8 to 1.2.10. The new release includes fixes for security
issues CVE-2016-9840, CVE-2016-9841, CVE-2016-9842, CVE-2016-9843.
http://seclists.org/oss-sec/2016/q4/602
Apart from below changelog, I also sync'd up the documentation between zlib.h and zlib.d.  There were also some missing functions.
- deflatePending (added in 1.2.5.3)
- inflateGetDictionary (added in 1.2.7.1)
- inflateMark/inflateReset2 (added in 1.2.3.4)
- gzbuffer/gzoffset/gzclose_r/gzclose_w (added in 1.2.3.5)
---
Changes in 1.2.10 (2 Jan 2017)
- Avoid warnings on snprintf() return value
- Fix bug in deflate_stored() for zero-length input
- Fix bug in gzwrite.c that produced corrupt gzip files
- Remove files to be installed before copying them in Makefile.in
- Add warnings when …

Update zlib to the 1.2.10 release

---

std/utf.d

decodeBack consists of 4 overloads: one not taking an index as an argument and underneath calling one of the 3 remaining overloads:
1. taking a string which is `@trusted` and `pure`
2. taking a finite random access range
3. taking a bidirectional (but not random access) range
I added unit tests for this function to existing `decode` tests, modifying them a bit.

Fix issue #16323 - implement utf.encodeBack function

---

std/file.d

https://issues.dlang.org/show_bug.cgi?id=17102

fix issue 17102 - Don't pass null to strlen in std.file.cenforce

---

std/typecons.d

Interestingly enough this was found thanks to a code metric tool that indicates that the volume (as defined by the Halstead complexity) of this function is a bit excessive. Quickly after starting to review the function I saw the bug.

fix issue 17116 - std.typecons.ReplaceType is not able to process const delegates

---

std/regex/internal/tests3.d

Seems to be compiler bug but have no time to dig down deeper, at least this fixes the auto-tester.

Fix auto-tester heisenbug on OSX 32

---

etc/c/zlib.d
etc/c/zlib/ChangeLog
etc/c/zlib/README
etc/c/zlib/deflate.c
etc/c/zlib/gzlib.c
etc/c/zlib/gzwrite.c
etc/c/zlib/inffast.c
etc/c/zlib/inftrees.c
etc/c/zlib/trees.c
etc/c/zlib/zlib.3
etc/c/zlib/zlib.h
etc/c/zlib/zutil.c

Follow-up from #5031.  If there's any more quick successive releases, maybe it's better to wait until development stabilizes.  In the meantime however, this is a small bug-fix in comparison to the last merge.
---
Changes in 1.2.11 (15 Jan 2017)
- Fix deflate stored bug when pulling last block from window
- Permit immediate deflateParams changes before any deflate input

Update zlib to the 1.2.11 release

---

std/traits.d

Use builtin `__traits` https://dlang.org/spec/traits.html in `std.traits` and perhaps others for less template instantiations.
http://forum.dlang.org/post/azthdyasrlsojztsyoqs@forum.dlang.org

Use builtin __traits when possible

---

std/range/package.d

Fixed a bug: takeOne with unslicabe ranges did not pop its source range when popped. This made it inconsistent with take and takeExactly when using reference ranges. Also corrected its documentation.

Bugfix for takeOne (issue 16999)

---

std/typecons.d

This PR changes the type of the built-in properties (`.min`, `.max`, etc) of the basic types when they are used to make a `TypeDef` instance or alias.
In the current state, the type definition can be broken in any expression that would extract the type using a property, eg:
```
typeof(T.max) a;
```
even if very unlikely to ever happen.

fix issue 11703, Typedef properties should not be of the original type

---

std/uri.d
unittest.d

* removed most global imports
* removed commented out code
* made some declarations private

std.uri Cleanup

---

std/typecons.d

This makes `RefCounted!T` `pure/nothrow/@nogc` when possible.

std.typecons: Make RefCounted pure nothrow @nogc when possible

---

changelog/std-format-formattedRead-only-pointers.dd
std/format.d

Allow only types with unary `*` operator. Could be improved if `isLvalue` template constraint has existed.

Fix issue #8260 - add template constraints for formattedRead parameters

---

std/conv.d

`strtod()` is `@system` and thus can't be called from a `@safe` unittest.

[Trivial] Fix std.conv unittest compile error for double-precision reals

---

.dscanner.ini
posix.mak
std/experimental/logger/core.d
std/regex/internal/bitnfa.d

After this phobos PR and [this Dscanner PR](https://github.com/Hackerpilot/Dscanner/pull/398) the check for final _"could"_ be enabled in dscanner.ini

[style] remove several useless usages of "final"

---

std/windows/registry.d

Fix messages:
```
std\windows\registry.d(572): Deprecation: module core.bitop is not accessible here, perhaps add 'static import core.bitop;'
std\windows\registry.d(658): Deprecation: module core.bitop is not accessible here, perhaps add 'static import core.bitop;'
```

std.windows.registry: fix deprecation messages about core.bitop.bswap

---

std/conv.d

Removed `goto`s and used `enforce` which IMO is more in keeping with D style.

Small clean-up in std.conv.parse

---

std/json.d

Using line comments for blocks doesn't work with Ddoc, see https://github.com/dlang/dmd/pull/4745 for discussion. (It's ugly, too, and not in the Phobos style.)
Using `/* ... */` immediately after Ddoc comments is also poor style.

std.json: use proper block comments

---

std/format.d

After https://github.com/dlang/phobos/pull/4599 was merged, most of std.format became pure automatically.
This PR adds static checking for pure with unit test attributes.

Added pure to unittests in std.format

---

std/string.d
std/utf.d

The inference of `return scope` is a bit primitive in the compiler, sometimes it has to be specified.

[scope] add 'return scope' to std.utf.byUTF and std.string.leftJustifier

---

std/traits.d

At least so it doesn't fall over when encountering `scope`.

[scope] add some 'scope' support to std.traits

---

std/array.d

The `@trusted` is documented in the comments. The need for `scope` is there for `join` because the use of `sep` is convoluted enough the relatively simple inference engine in the compiler cannot infer it, so a little help is needed.

[scope] add @trusted and 'scope' annotations to std.array

---

std/conv.d

LDC
```
Total time: 6 secs, 244 ms, 694 μs, and 2 hnsecs
Total time: 8 secs, 555 ms, 476 μs, and 5 hnsecs
```
DMD
```
Total time: 10 secs, 220 ms, 605 μs, and 5 hnsecs
Total time: 14 secs, 600 ms, 397 μs, and 1 hnsec
```
Code
```
import std.container;
import std.meta;
import std.datetime;
Target parse1(Target, Source)(ref Source s, dchar lbracket = '[', dchar rbracket = ']', dchar comma = ',')
if (isSomeString!Source && !is(Source == enum) &&
isDynamicArray!Target && !is(Target == enum))
{
import std.array : appender;
auto result = appender!Target();
parseCheck!s(lbracket);
skipWS(s);
if (s.empty)
throw new ConvException("");
if (s.front == rbracket)
{
s.popFront();
return result.data;
}
for (;; …
```

Optimization For Array Overload of std.conv.parse

---

std/conv.d

Small performance increase. But still, it makes this function `nothrow` for strings.
```
Total time: 11 ms, 2 μs, and 4 hnsecs
Total time: 14 ms, 978 μs, and 3 hnsecs
```
```d
import std.container;
import std.meta;
import std.datetime;
Target parse1(Target, Source)(ref Source source)
if (isInputRange!Source &&
isSomeChar!(ElementType!Source) &&
is(Unqual!Target == bool))
{
import std.ascii : toLower;
static if (isNarrowString!Source)
{
import std.string : representation, assumeUTF;
auto s = source.representation;
}
else
{
alias s = source;
}
if (!s.empty)
{
auto c1 = toLower(s.front);
bool result = (c1 == 't');
if (result || c1 == 'f')
{
s.popFront();
foreach (c; result ? "rue" : "alse")
{
if …
```

Removed auto-decoding from the bool version of std.conv.parse

---

std/socket.d

Using line comments for blocks doesn't work with Ddoc, see dlang/dmd#4745 for discussion. (It's ugly, too, and not in the Phobos style.)
Using /* ... */ immediately after Ddoc comments is also poor style.

std.socket: use proper block comments

---

std/parallelism.d

Not sure if this hack prevents the line starting with "data:" to be interpreted as a data section, please test.
Note: data sections seem to be an undocumented feature of ddoc: https://dlang.org/spec/ddoc.html
Maybe ddoc should require an empty line above (real) sections?

[doc] Remove spurious data section.

---

std/conv.d

```
Total time: 283 ms, 779 μs, and 4 hnsecs
Total time: 205 ms, 546 μs, and 5 hnsecs
```

Removed auto-decoding from the int with radix version of std.conv.parse

---

std/stdio.d
std/utf.d

These functions are exactly the same as `std.utf.encode`. And they are quite old, originating in 2007 according to git blame. So they probably existed before `std.utf.encode`. 
They also return a slice over a static array, which is a Bad Idea<sup>TM</sup>.
Doing a deprecation cycle because they are publicly accessible and were used in other parts of Phobos.

Deprecate Obsolete Encoding Functions in std.utf

---

circleci.sh

- adds the fallback to nightlies in case of a failure to download the install script (see also the regarding [Travis PR](https://github.com/travis-ci/travis-build/pull/910))
- fix the soft fallback to `master` in case of an overuse of the GitHub API has e.g. occurred at https://github.com/dlang/phobos/pull/5011 (with the `-e` option the bash script immediately exits on an error, hence the `|| echo` trick)

[CircleCi]: use more fallbacks in case of a failure

---

std/exception.d

ErrnoException used to take the global errno variable; the overloaded ctor allows one to provide a custom errno (e.g., one that's been stored in a variable, or asynchronous operations).
Add unittests to the new ErrnoException ctor

ErrnoException: add a ctor overload that takes errno as an argument

---

std/stdio.d

Such a common function, probably should have a simple example.
People complained about it in this thread https://forum.dlang.org/thread/gtydhqbobwljnnvvlmjc@forum.dlang.org

Added example to std.stdio.writeln

---

std/algorithm/mutation.d
std/range/primitives.d

Also fix related `hasSwappableElements `docs.
`hasSwappableElements` already tests for `isInputRange`.

swapRanges: Remove redundant constraint tests

---

std/format.d

Ok, so the diff is so large, because for some reason, there were a bunch of unrelated unit tests strewn about the functions here. In order for the docs to be properly formatted, they had to be moved.
Otherwise, this takes some horrible docs and makes them understandable.

Consolidated and added examples to the std.format.unformatValue docs

---

std/file.d
std/path.d

Fun fact: without these checks, most of these functions just keep allocating memory until the program crashes when called with an infinite range

Add checks for infinite ranges in many range function signitures (part 2)

---

std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/array.d
std/functional.d
std/range/package.d
std/range/primitives.d
std/string.d

So I found [this old discussion](https://github.com/dlang/phobos/pull/147):
> Perhaps until and find should mention takeWhile and dropWhile. It's not entirely uncommon for someone to think that there's no function in Phobos which does what they want simply because none of them have a name that they recognize as doing what they want. It's not an entirely solvable problem, but we can probably find ways to improve the situation.
So here's an attempt to make the docs a little bit nicer (and Google-friendlier) by providing a couple of reference to other common names in other languages or Phobos.
Should we maybe use a category like `Other names`?

Provide references to other common names

---

changelog/std-random-MersenneTwisterEngine.dd
std/random.d

These patches update `MersenneTwisterEngine`'s implementation to use the new and much faster implementation @9il prepared for `mir.random`.  The standard 64-bit Mersenne Twister implementation is added as a side benefit.
The original Mersenne Twister algorithm (as per the reference C code by Matsumoto and Nishimura) first regenerates the contents of the entire state array, before looping over the resulting values and tempering them in order to generate the actual variates.  Once the entire state array has been iterated over, the array's values are then regenerated, and so on and so forth.
Ilya's implementation reworks this idea to intertwine update of a single entry in the state array with the tempering of another value to produce the next variate.  This ensures that all the registers …

Rework MersenneTwisterEngine using Ilya Yaroshenko's faster algorithm

---

changelog/std-random-MersenneTwisterEngine.dd

This was an oversight when finalizing dlang/phobos#5011.

Add a note about word size to the MersenneTwisterEngine changelog entry

---

std/json.d
std/stdio.d
std/uri.d

It seems like DMD doesn't like deprecating only one symbol. For selective imports it will always trigger a deprecation warning even if the symbol isn't used ([issue 17193](https://issues.dlang.org/show_bug.cgi?id=17193)).
This PR fixes the deprecation warnings from `toUTF8` on Posix. `grep` shows that there are more on Windows.

Fix deprecation: std.utf.toUTF8 -> encode

---

.dscanner.ini
std/algorithm/comparison.d

There were only two uses of `assert(true)` in Phobos.

DScanner: check for useless asserts

---

.dscanner.ini
std/algorithm/mutation.d
std/internal/test/dummyrange.d

Quite simple, `init` was only used in the internal `dummyrange` module and a unittest in `std.algorithm.mutation`

Dscanner: enable check for conflicts with builtin properties

---

std/container/array.d

Despite `Array` not using the GC for allocating its elements, it was still unusable for `@nogc` code because of its use of `throw` and `enforce`.
This PR turns those into `asserts` and makes the majority of the functions `@nogc`.

Fix Issue 17153 – Make std.container.array @nogc

---

std/traits.d

Another regression from https://github.com/dlang/phobos/pull/5038
(if we change this behavior we need to do so via a proper deprecation)

Issue 17195 - [Reg 2.074] isFloatingPoint!cfloat is now true

---

std/traits.d

Quick fix to restore the behavior before https://github.com/dlang/phobos/pull/5038 (this hasn't landed in `stable` yet).

Issue 17196 - [Reg 2.074] isUnsigned!bool now true

---

std/process.d

Useful because:
* Fewer windows API calls than `get`
* Less bookkeeping than `get` on windows & posix
* It's syntactically nice.
Why does it not return a `string` with the variable? Because that would mean it was just an alternative syntax for `get` and pretty pointless.
Why not do something clever and return a `const(string)*` in order to fully mimic an AA? Because I don't think there's any way of doing that even _close_ to efficiently.

add opIn for std.process.environment

---

posix.mak
std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/searching.d
std/array.d
std/complex.d
std/conv.d
std/exception.d
std/experimental/allocator/mallocator.d
std/experimental/allocator/package.d
std/experimental/logger/core.d
std/experimental/ndslice/slice.d
std/file.d
std/functional.d
std/internal/math/biguintcore.d
std/math.d
std/path.d
std/process.d
std/range/package.d
std/range/primitives.d
std/regex/internal/ir.d
std/stdio.d
std/typecons.d
std/uri.d
std/uuid.d
std/variant.d

>> BTW (and I realize you're sticking to existing style) I think Phobos style is to treat `assert` like a function, not a keyword (i.e. no space before `(`).
> yah, no space after `assert`
First commit adds a simple check, the second one applies another RegExp (`s/assert +\(/assert(/`) over the Phobos codebase to be able to enforce the former automatically.
CC @andralex

Style: enforce no space after assert

---

std/algorithm/iteration.d

Just discovered this useful idiom. I was doing this manually using `foreach` over ranges and incrementing the count in an AA for my stats plotting code.
All manual `foreach` loops in user code are bugs!

Added practical example to std.algorithm.iteration.group

---

std/experimental/allocator/package.d

Unfortunately I was away when #4982 was merged (and no one else has raised their voice either).
However, luckily this hasn't been released :)
Imho we can do provide a better API if
- (1) the type `T` is always the first parameter (after all that's the only template parameter manually provided by the user)
- (2) use variadic arguments and thus let the compiler do the hard work for us
FWIW I really don't like the name and would prefer sth. like `makeNdarray` (that was the name of this method in [`ndslice`](http://dlang.org/phobos/std_experimental_ndslice_slice.html#.makeNdarray).
In short - instead of:
```
size_t[3] dimArray = [2, 3, 6];
auto mArray = Mallocator.instance.makeMultidimensionalArray!(dimArray.length, int)(dimArray);
```
let's better write code like this:
```d
auto mArray = …
```

Allocator: fix experimental makeMultidimensionalArray API

---

index.d
posix.mak
std/experimental/checkedint.d
win32.mak
win64.mak

This is the checkedint design I was discussing recently in the [forum](http://forum.dlang.org/thread/nkk8r2$2lvi$1@digitalmars.com). It's work in progress - I think a couple more policies would be useful.

add std.experimental.checkedint

---

std/experimental/checkedint.d

https://github.com/dlang/phobos/pull/4613 broke CircleCi, this should fix it again.
How about enforcing CircleCi to pass to avoid such sneak-ins in the future?

Fix CircleCi for std.experimental.checkedint (add unittest attributes)

---

circle.yml
posix.mak
std/algorithm/iteration.d
std/conv.d
std/experimental/allocator/package.d
std/experimental/ndslice/iteration.d
std/experimental/ndslice/slice.d
std/range/package.d
std/utf.d

Ddoc already triggers a nice warning if there's a parameter mismatch - this PR fixes the last remaining error (expect for a [eponymous templates](https://issues.dlang.org/show_bug.cgi?id=16988) in deprecated ndslice/iteration.d).
This PR also adds adds a CI check for sth. similar to `dmd -w -D -main -c -o- **/*.d`, s.t. future additions we can ensure that no new violations get in ;-)
Btw I was also looking at [public symbols without Returns/Params](https://github.com/Hackerpilot/Dscanner/pull/390) and it seems to be a lot :/
edit: [bugzilla issue for public symbols without return](https://issues.dlang.org/show_bug.cgi?id=16989)

Enforce successful ddoc run

---

changelog/std-experimental-checkedint.dd

```
$ make -C ../dlang.org -f posix.mak pending_changelog
make: Entering directory '/home/andrei/d/dlang.org'
This command will be available soon.
make: Leaving directory '/home/andrei/d/dlang.org'
```
@wilzbach

Changelog for checkedint

---

changelog/std-format-formattedRead-only-pointers.dd
changelog/std-random-MersenneTwisterEngine.dd
changelog/std-range-bitwise.dd
changelog/std-stdio-readf-only-pointers.dd
changelog/std-utf-decodeBack.dd
posix.mak

It seems that not everyone was consistent with the changelog format - some people even left out the description :O
> The changelog tool should enforce that there's a blank line after the title line.
Well the changelog tool isn't called here directly, but on DAutoTest.
I tried to fix the changelog files & added a simple validator, s.t. we can at least automatically ensure that
- the entry contains a description (and a separating line between them)
- has no `$(REF)` in the title
Yes in theory the `changed.d` could have a flag `---validate`, but I would like to have this check enforced before next summer (PRs at tools have a tendency to hang in the queue).
> Or, alternatively, allow multiple lines for the title, until the first blank line.
I don't think it's worth supporting this as (a) it's …

Fix changelog files & add a simple validator

---

std/format.d

This PR brings `unformatValue` docs to the same style as the docs for `std.conv.to`. The user doesn't need to know the exact overloads that they can use, it's covered in the docs. And if they get it wrong, the compiler still prints out the overloads of `unformatValueImpl`.

Simply the docs of std.format.unformatValue

---

std/conv.d

Introduced in c6fb78ed14449725d0f5d10f38852eefb1e5dbfe (#5067).

std.conv: Fix off-by-one regression in integer radix parse

---

std/format.d

This solution uses "dumb" `static if`s to guarantee backwards compatibility with raw pointer usage. Splitting it off into two functions and triggering deprecation warnings for pointer usage might also be an option.

Fix issue 16281 - std.format.formattedRead should use ref instead of requiring pointers

---

std/conv.d

Fix formatting issues in std.conv.to docs

---

posix.mak

This list was pretty hard to read. Hence:
First commit:
- only use `add_prefix` if actually saves space (i.e. don't use `add_prefix` for single words)
- sort alphabetically
- indent properly
- add `add_prefix` where it improves readability (e.g. `unicode`
Second commit (after cleanup): add `stdiobase` to the list internal modules
A PR to dlang.org to exclude it from the menu will follow soon.

Posix.mak: cleanup EXTRA_MODULES_INTERNAL + add stdiobase to internal

---

.dscanner.ini
std/range/package.d

@BBasile created this nice plugin for Dscanner to check for `auto` function with `void` return statement:
https://github.com/Hackerpilot/Dscanner/pull/372
With its improvement in false-positive detection (https://github.com/Hackerpilot/Dscanner/pull/383), I think it is now ready for Phobos (apart from one minor "false-positive" in `std.range.RefRange`).
Btw is there any reason why we don't use `inout` in `RefRange`?
edit: there was a previous PR that did the ground work for this, but I can't find it atm.

DScanner: check for auto function with void return statement

---

std/algorithm/searching.d

I just noticed that I accidentally ended up in the wrong header.

std.algorithm.searching: move `takeWhile` line to the current definition

---

std/experimental/checkedint.d

As CircleCi builds doesn't get re-run, there's the slight potential that `master` has evolved. This has just happened with the newly enabled Dscanner check in https://github.com/dlang/phobos/pull/5160
tl;dr: `std.experimental.checkedint` has two `auto` function that don't return a value.

Fix CircleCi: auto functions that return null should be void

---

std/algorithm/sorting.d

So it turns out that using a random seed leads to "interesting" effects. One example is that our coverage report jumps _randomly_ up & down.
Don't believe me? Check it out for yourself:
https://codecov.io/gh/dlang/phobos/compare/77f1a9067b59395f8444cb2d01047680aebcfe5f...f2b58341725a6d195b388c1b6f31dcdaa9f000f7/changes
https://codecov.io/gh/dlang/phobos/compare/22331db571d874ba44e412777ed8310536a18dff...89e4014e3d89c7de4d2e2c50eca7924e465ff062/changes
https://codecov.io/gh/dlang/phobos/compare/86050a1c59eda327fa263549f0b53e56a4cfa9ed...2749175ceb24e4b780725677b7e233f65e4f791c/changes
https://codecov.io/gh/dlang/phobos/compare/77f1a9067b59395f8444cb2d01047680aebcfe5f...2e05f29d3c4cc7690198c3ad0d06eb23293da48a/changes
...
(endless list)
I think it's quite reasonable to fix the random test …

Derandomize std.algorithm

---

circle.yml
circleci.sh
posix.mak
std/algorithm/mutation.d
std/bigint.d
std/container/binaryheap.d
std/container/rbtree.d
std/digest/digest.d
std/format.d
std/functional.d
std/variant.d

To improve Phobos's documentation, here's another addition to the `style` Makefile target.
Here's the idea that _every public function should have at least one public example_ as stated in the [high-level vision](https://wiki.dlang.org/Vision/2016H2) (btw for all public examples the `publictests` Makefile target we will enforce that it's runnable on dlang.org) 
[Script is at the tools repo](https://github.com/dlang/tools/blob/master/styles/has_public_example.d).
Note: this just adds the tool and comes with quite a long blacklist. While I started to fix some modules (e.g. https://github.com/dlang/phobos/pull/4973 and trivial ones in this PR), it's quite a lot of effort. However, once this has been enabled, everyone should be able to help to reduce the blacklist :)

Check public functions for public examples

---

std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/package.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d

These didn't even work because std.stdio wasn't imported. I highly doubt anyone was using them, and they're not particularly useful anyway.

Remove unused debug writelns in std.algorithm

---

etc/c/odbc/sql.d
etc/c/odbc/sqlext.d
etc/c/odbc/sqltypes.d
etc/c/odbc/sqlucode.d
std/algorithm/comparison.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d
std/container/binaryheap.d
std/container/rbtree.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/package.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/mmap_allocator.d
std/functional.d
std/numeric.d
std/random.d
std/range/package.d
std/regex/package.d
std/stdio.d
std/uni.d
std/variant.d

The Ddoc macro system seems to be able to continuously amaze me everyday.
So there's `LUCKY` which will insert a link to a lucky google search with the highlighted word.
I get the idea of this to avoid broken manual or book links, but not really for common terms for which there are high-quality Wikipedia articles on abundance.

Replace LUCKY links with actual links

---

std/range/interfaces.d
std/range/primitives.d

I wasn't quite sure whether it's worth to document `outputRangeObject`, `inputRangeObject`, `MostDerivedInputRange` and `put` (I did it anyways as they were appearing on the quickindex)

std.range: remove quick index and fix docs (part 2)

---

std/array.d
std/container/array.d
std/container/dlist.d
std/container/slist.d
std/container/util.d
std/demangle.d
std/functional.d
std/mmfile.d
std/outbuffer.d
std/signals.d
std/typetuple.d

One full sweep through the remaining Phobos modules:
- most didn't have a `BOOKTABLE` (or were already using `inhibitQuickIndex`)
- when there was only one symbol to jump to, it doesn't make sense to show the quick index table
Something interesting: even though `splitter` was deprecated in [std.array](http://dlang.org/phobos/std_array.html) and doesn't use ddoc comments, it's still visible in the quickIndex :/

Remove quickIndex for modules with booktables or only one symbol

---

std/algorithm/iteration.d

> Best outcome of this: a ddoc unittest of fold that prints the last line of a file.
Hmm we don't have many tests based on files and they usually are a bit clunky as one needs to write the file first.
So I simply added the "`walkBack` usage" to the existing unittests of `fold`.
However, I am happy to add a file example as well if you know a good spot ;-)

walkBack follow-up: Mention fold's potential in the examples

---

changelog/std-stdio-readf-only-pointers.dd
std/stdio.d

Follow-up to #5009 (since `formattedRead` accepting `ref` parameters, `readf` can do so as well)

Fix 16281 - std.stdio.readf should use ref instead of requiring pointers

---

changelog/std-variant-genericfunc.dd
std/variant.d

If a lambda with a single generic parameter is provided as a handler
to std.variant.visit, it is invoked for any type contained in the
Algebraic which does not have a handler for that type.
This allows something like:
```
// Assume Circle, Square, and Triangle all define center()
Algebraic!(Circle, Square, Triangle) someShape;
auto center = someShape.visit!(x => x.center);
```
This may be combined with explicitly typed handlers and a single
fallback handler for an empty variant:
```
Algebraic!(int, float, string) something;
something.visit!((string s) => s.length, // called for string
x          => x,        // called for int/float
()         => 0);       // called if empty
```

Allow a generic function for std.variant.visit.

---

changelog/std-algorithm-searching-extremum.dd
std/algorithm/searching.d

In #4265 I showed that `extremum` (aka `minElement` and `maxElement`) can be made a lot faster if we provide a special path for the identity case, because the compiler can then make use of SSE instructions.
In theory the compiler should be smart enough to figure it out himself, but well neither dmd nor ldc are that smart :/
For reference here are the benchmarks from #4265:
```
dmd -release -O foo.d && ./foo
0 4 secs, 610 ms, 609 μs, and 5 hnsecs
1 3 secs, 769 ms, 89 μs, and 4 hnsecs
```
```
ldc -release -O3 foo.d && ./foo
0 1 sec, 345 ms, and 914 μs
1 216 ms, 347 μs, and 1 hnsec
```
Source for benchmarks: http://sprunge.us/QSWP
This PR does the specialization via overloads whereas #4265 does them via comparison of strings.

std.algorithm.searching: no mapping-specialization for extremum

---

std/bitmanip.d

- I am not entirely sure about the grouping for this module, especially I don't like the name "Integral ranges"
- the weird whitespace wrapping is a known issue and independent from this PR

[BOOKTABLES]: Add BOOKTABLE to std.bitmanip

---

std/utf.d

@jmdavis I think you are probably the best person to judge the grouping.
I wasn't sure whether:
- to show `byUTF` at all (the user is only interested in the three convenience overloads)
- combine "Decode" and "Lazy decode" (I went with the current option as I wanted to stress the laziness)

[BOOKTABLES]: Add BOOKTABLE to std.utf

---

std/array.d
std/base64.d
std/experimental/checkedint.d
std/format.d
std/functional.d
std/range/interfaces.d
std/range/package.d
std/range/primitives.d

From the [NG](http://forum.dlang.org/post/ohjurtkzhvufqsahmimj@forum.dlang.org)
> On second thought, yes, ddox shouldn't output invalid HTML if it can help it, but this is actually an antipattern I see a lot in Phobos and hate:
> $(D $(LREF Abort)))
> That's an unnecessary repetition! If it is an LREF in a D source file, then you *already know* it is a D symbol, so the `$(D)` macro is redundant anyway.
> I'd simplify that to just be `$(LREF ...)` in all cases it appears in the Phobos source, and then if you want it to be styled in the monospace font, do a css rule for *that*.
Your wish has been heard:
```
sed -E 's/[$]\(D [$]\(LREF (.*)\)\)/$(LREF \1)/' -i **/*.d
```
CC @andralex @adamdruppe

Fix links from $(D $(LREF ...)) -> $(LREF ...)

---

std/algorithm/package.d

This isn't a complete fix of 17232, but it's a simple step to improve the current status and it also looks nicer on the Desktop as I think it's quite obvious to the reader that he's looking at `std.algorithm` (title, left sidebar, url, ...)
Before:
After:

Issue 17232 - make std.algorithm table more digestable

---

std/typecons.d

I made a failed pull request (https://github.com/dlang/phobos/pull/5136) lately trying to make Unique partially @safe, which turned out to be unworkable. But it had an idea to make release() to use move(), since they do the same thing, and this pr contains that.

Typecons.Unique.release() change

---

changelog/std-traits-hasStaticMember.dd
std/traits.d

Opening this new pull request as @jmdavis seems busy and hasn't replied to pings, credit to him (#4834)

Issue 16485 - Add trait for testing if a member is static.

---

std/file.d

When looking at the signatures of std.file, it looks like
it only takes input ranges and specifically disallows strings.
The text of most functions say it can take strings, but the
proper overload isn't displayed at all.
This gave me a moment of confusion earlier today, so I decided to
just fix it with a bunch of little dittos. Now, the string overloads
should appear right with the non-string overloads.

Document undocumented overloads that take string

---

std/regex/internal/backtracking.d
std/regex/internal/tests.d

Backtracking engine reused stale data in matches from the previous run.

Fix issue 17157 ctRegex.matchAll doesn't set last item in Captures

---

std/concurrency.d

Make std.concurrency functions leaner by using static functions

---

std/utf.d

Basically, `byCodeUnit` works properly with strings, with structs that are ranges of characters (but do not implicitly convert to any string type), and with structs that use `alias this` with a member variable to convert to a string type. It does not work properly with enums (which pass the template constraint but fail to compile, because they're not actually ranges), it does not work with structs that use a member function with `alias this`, and it does not work with structs that are already ranges of characters but also use `alias this` with a string type. This PR fixes all that.
The main thing is that it now forces the conversion to the string type when the type needs an implicit conversion to be a range of characters. In general, it's bad practice to have a template test for an …

Fix Issue 16642  - byCodeUnit doesn't work properly with alias this.

---

std/typecons.d

I had trouble understanding how Unique!T was supposed to help me manage resources.  These document changes should clarify the process and make it easier for others to understand.
Caveat: I'm not absolutely sure if $(REF destroy, object) will do what I intend after doc generation.  I don't have time to learn how to build Phobos' documentation to test it.  I intend it to reference https://dlang.org/library/object/destroy.html so that the reader can easily understand the implications.
This is follow-up after this post on the D learn forum: https://forum.dlang.org/post/qctmkqpqnreysxcjmrgm@forum.dlang.org
If this change goes well, then I will attempt to update RefCounted!T as well.

Clarify deallocation done by std.typecons.Unique.

---

std/algorithm/mutation.d

Even if the new overload is not a real range operation, `fill()` can handle `char[]`, `wchar[]` for better generic code.

fix issue 16342 - add std.algorithm.mutation.fill fallback for mutable strings

---

std/stdio.d

The correct name is `byChunk` not `byChunks`.

[trivial] Fix typo in std.stdio.File.byChunk ddocs

---

std/math.d

I'm far from being an expert on this stuff. I learned about the different control registers only when investigating this issue here. If someone more experienced wants to take over, be my guest.
I have a [test file for unmasked exceptions](https://gist.github.com/aG0aep6G/bcf65e37cc4a9e5f71a96b4c20bbc3e7), but I don't know how to incorporate it into the phobos tests.
A test for `roundToNearest` is missing, because I'm having a hard time thinking of one.

fix issue 17243 - std.math.{FloatingPointControl,ieeeFlags} don't work on x86_64

---

std/conv.d

Only checking for ASCII whitespace anyway.
Gives performance boost of about 7% on DMD

Removed auto decoding from a helper function in std.conv

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/package.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/common.d
std/experimental/allocator/gc_allocator.d
std/experimental/allocator/package.d

Have the resolveInternalPointer method defined in the module's static allocators abide the IAllocator API.

Make the resolveInternalPointer method abide the IAllocator API

---

std/algorithm/iteration.d

[Static if] replace overload constraints with static if (iteration.d)

---

std/stdio.d

The fix is basically to disallow compiling the putting of `ubyte` data into the output range. It will now only accept arrays of a character type, or ranges of a character type. Any other type is not really a character, and should be cast if that's what you really meant.
Note that the original code did really bad things. For instance, an array of `ubyte` was put into the output stream by integer promoting each `ubyte` into a `dchar`, and then encoding whatever the result of that was into utf-8 code units.
I'm not sure if we need a deprecation here, as code that is passing `ubyte[]` to `lockingTextWriter` is fundamentally broken, but maybe I'm wrong and there are some valid uses for this that need to be migrated to `char[]` casting?
Also updated the example to reflect the correct usage for …

Fix issue 17229 - File.byChunk (ubyte) w/ stdout.lockingTextWriter corrupts utf-8 data (and is very slow)

---

std/format.d

The grammar description in `std.format` is missing the part about `%|`, which is used inside `%(...%)`.

[dox] Fix missing '|' in std.format grammar.

---

changelog/std-format-formattedWrite.dd
std/format.d

* Add overloads for formattedWrite, formattedRead, format, sformat.
Check compile-time format strings match the given argument types. I'm using CTFE to evaluate `format(fmtStr, Args.init)` and see if an exception was thrown; the actual runtime code is unchanged. This is not optimal but makes this PR easy to implement and avoids code duplication/refactoring of `formattedWrite`. Users can start to pass format strings as compile-time arguments.
* Throw FormatError when formatValue is called with CTFE and a floating point argument.
This allows `snprintf` to be avoided in CTFE when checking format strings so floating point arguments can be checked.
@quickfur

Issue 13568: Add CT-checked format string overloads to std.format

---

std/concurrency.d

std/concurrency.d uses a non standard style, this brings it into line with the rest of the codebase
used the default dfmt options with some manual fixes.
CC @wilzbach

Use dfmt on std/concurrency.d

---

changelog/std-format-formattedWrite.dd
std/format.d
std/stdio.d

This follows on from merged #5288.
* Add overloads for readf, writef, writefln.
* Separate `fmt` argument from `args` for writef[ln] to improve docs.
@quickfur

Issue 13568: Add CT-checked format string overloads to std.stdio

---

std/experimental/typecons.d

Code:
````
import std.experimental.typecons;
void main()
{
Final!int s;
s += 5;
}
````
Compiler output (before):
````
test.d(5): Error: function std.experimental.typecons.Final!int.Final.opOpAssign!("+", int).opOpAssign is not callable because it is annotated with @disable
````
Compiler output (after):
````
/usr/src/d/phobos/std/experimental/typecons.d(867): Error: static assert  "Final!int cannot be reassigned."
test.d(5):        instantiated from here: opOpAssign!("+", int)
````
The current error message (before) is rather unhelpful from the user's POV, and exposes too much implementation detail ("I just used `Final!int` to declare a variable, what does `@disable` have to do with it?").  The new error message is more informative and explains why the operation is not allowed.

Nicer error messages for std.typecons.experimental.Final

---

std/random.d

indicating unsuitability for cryptographic purposes.

std.random disclaimer

---

std/array.d

The two overloads taking an element and a const range were conflicting because `canPutConstRange` is overlapping the definition of `canPutItem`.

Fix issue 17251 - Appender.put doesn't accept const input range elements

---

std/digest/hmac.d

Looks like these not being included was a mistake, as the member functions are documented.

Documented undocumented HMAC helpers

---

std/range/package.d

Well, this is breaking since it disallows cycling infinite ranges which are not forward ranges. But since cycle is intended for forward ranges only, I don't think it should compile with others even when it would just alias itself away.

Simplified overloads of std.range.cycle.

---

std/typecons.d

I had trouble understanding how RefCounted!T was supposed to help me manage resources.  These document changes should clarify the process and make it easier for others to understand.
This is follow-up after this post on the D learn forum: https://forum.dlang.org/post/qctmkqpqnreysxcjmrgm@forum.dlang.org
and after commits cd86cc25b60950dfd26f8f0f8840e576e0da1fc0 and 33217eb46f4bb5668cc5b763e9e428f93218545a "Clarify deallocation done by std.typecons.Unique."

Clarify deallocation done by typecons.RefCounted.

---

std/experimental/logger/core.d

Docs seem to refer to a string parameter, that apparently was removed.
Also reworked the docs to be more appropriate ddoc style (and modernized with backticks)
ping @burner

Fix issue 15534 - [std.experimental.logger.core] Documentation mismatch

---

std/typecons.d

This issue was discovered while trying to fix a compiler bug (see [1]). It turns out that std.experimental.typecons uses some templates from std.typecons which are private. Since the templates are used in another module, I modified the private attribute to package. At the moment, this is blocking the merging of [1]
[1] https://github.com/dlang/dmd/pull/6660

Fix Issue 17283 - std.experimental.typecons uses private module members

---

std/format.d

* Show wrong format specifier or invalid type in exception message
* Fix throwing `FormatException` when width/precision arguments passed without a following value to format.

std.format: Improve FormatException messages

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/package.d

Allocators that rely on taking a block of unused memory to manage and allocate
from it should take a ubyte[] instead of a void[] in order to prevent users
from accidentally passing valid data and cause memory corruption/leaks.

Allocators should take a ubyte[] memory block instead of a void[] one

---

std/math.d

Also fix issue where symmetry was assumed when lhs was a value and rhs was not. Instead of swapping the arguments (which clearly isn't equivalent), I copied the implementation of the range processing, but for rhs instead of lhs.

fix issue 15763 - Document behavior of relative difference

---

std/container/binaryheap.d

When length is 1, length * 3 / 2 is still 1, so insert didn't make room for the new item.
https://issues.dlang.org/show_bug.cgi?id=17314

Fix Issue 17314 - BinaryHeap crashes upon insertion if heapified with an array of length 1

---

std/parallelism.d

Ok, so apparently you cannot reopen a PR if you force push to it. Weird :/
So I think this is exactly what inout was designed to solve. Please destroy if still unsafe.
CC @andralex

Add const/inout to std.parallelism

---

std/regex/package.d

Instances don't refer to the parameter. This fixes the S_LINK links.

[Ddoc] un-highlight 'format'

---

std/format.d

Big numbers are hard to read. D allows to insert underscores into numbers to aid readability.
This PR gives std.format the ability to insert underscores into numbers.
```D
string tmp = format("%_d", 1234567);
assert(tmp == "1_234_567");
tmp = format("%_4f", 1234567.891011);
assert(tmp == "123_4567.8910_11");
```
The numbers of digits between underscores can be specified similar to the way a precision is given.
Todo:

fix Issue 10001 - std.format insert underscores into numbers

---

std/experimental/allocator/building_blocks/kernighan_ritchie.d

Otherwise LLVM sometimes chooses to align the stack buffers at a 4-bytes boundary (on x86_64) leading to an assertion in the `KRRegion` constructor.

Fix missing alignment for kernighan_ritchie allocator unittests

---

std/getopt.d

At present there are no unit tests in std.getopt where delegates are used as callbacks. This adds a few basic tests.

std.getopt: Add unit tests for delegates as callbacks.

---

std/stdio.d

datetime.d - for some reason NetBSD return EPT for America/New_York
stdio.d - It contains note: "Note: Calling `reopen` with a `null` `name` is not implemented
in all C runtimes." and NetBSD is example of such runtime. I decided pass name from File struct, because as I remember we should not use "version" blocks in phobos if possible.

netbsd small changes

---

std/getopt.d

This change make a pair of internal std.getopt functions `@safe`. This enables some additional `@safe` getopt use: callbacks via delegates and config option setting. `@safe` unit tests for both are included.
I also went through all the existing unit tests to see if any could be converted from `@system` to `@safe`. However, the existing `@system` unit tests take the address of local variables are cannot be `@safe`.
This PR is a follow-up to PR #5347.

std.getopt: Make private functions safe.

---

std/traits.d

https://issues.dlang.org/show_bug.cgi?id=17340

Fix issue 17340 - isNumeric!bool should not be true

---

std/conv.d

Removes an extra array allocation.

Remove unnessesary call to text from std.conv.convError

---

std/numeric.d

This PR does the following:
1. Add sig constraints to the current version of `std.numeric.gcd` so that it won't pick up types that it actually can't support. The current implementation is dependent on builtin types and fails in ugly ways with non-builtin types (including `BigInt`).
2. Add a generic overload of `gcd` that implements both Euclid's algorithm and Stein's algorithm in a minimalistic way of doing the most while requiring the least.  While I realize that this involves a lot of copy-pasta, I couldn't find a nice way to do it without potentially breaking existing code or turning the code into an unmaintainable mess of `static if`s, due to the original overload being a rat's nest of dependencies on properties of builtin integer types and other implementation details.  Also, another …

Fix issue 7102: std.numeric.gcd overload that works with non-builtin types

---

std/experimental/logger/core.d

Buffers for preallocated class instances should be typed void[], not ubyte[] and must be properly aligned.
This blocks https://github.com/dlang/druntime/pull/1798.

std.experimental.logger: allow precise scanning of DATA/TLS segment

---

std/uni.d

I am not really sure here what the best way to go is. The current documentation already contains a good introduction, which is pretty much destroyed by the quickIndex. 
https://dlang.org/phobos/std_uni.html
So we could also try to (a) include the missing functions in the "text-based" overview or (b) use the full-text information in a table overview as well.
Moreover for some symbols I wasn't entirely sure how to categorize them, e.g. `Grapheme` was a tough one.

[BOOKTABLES]: Add BOOKTABLE to std.uni

---

std/range/package.d

- added missing elements to the booktable (if everything is listed in there, there's no need for the quick index)
- added more links to guides about ranges
- fixed a couple of ddoc issues (variables without a beginning underscore, HTML links to other modules, ...)

std.range: Add missing methods to the booktable, disable the quickindex and improve the docs

---

std/uni.d

This removes some inappropriate attributes from a fullCasedCmp. It's
templated, and their applicability depends on the template argument, so
they should be inferred. And the unit tests for icmp which test the
attributes (including @safe) pass without the attributes on
fullCasedCmp, so I have no idea why any of them (particularly @trusted)
were ever there.

issue# 17372: icmp chokes on a lambda that can throw.

---

std/datetime/package.d
std/datetime/systime.d

A baby-step to fix the most visible broken HTML links due to Ddoc's nice behavior of auto-escaping symbols ...
For reference please see: https://dlang.org/phobos-prerelease/std_datetime.html

Fix Ddoc links in std.datetime

---

circle.yml
posix.mak

CC @jmdavis @schveiguy 
One simple trick that we can do is simply splitting the target up into its subdependencies, s.t. it is easier to browse on CircleCi. Moreover, IIRC CircleCi will __continue to execute the subsequent tests__ (see e.g. [1](https://circleci.com/gh/dlang/phobos/2612) or [2](https://circleci.com/gh/dlang/phobos/2617))

Split style target for CircleCi

---

std/datetime/timezone.d

The tests fail depending on your timezone due to a known FreeBSD bug, so
we need to disable them until the bug in FreeBSD gets fixed.

Fix std.datetime autotester failure for FreeBSD 10.3/11.

---

posix.mak

Send documentation output to /dev/null when checking for warnings.

posix.mak: Discard DDoc output of DDoc warning test

---

posix.mak

- for development, people can use the much faster std/algorithm.test targets
- for batch unittest recompiling isn't of much interest as all the
testers just start from a clean slate anyhow
- furthermore the .deps generation is broken anyhow, see Issue 7016

remove .deps file generation

---

std/experimental/logger/core.d

fix Issue 16232 - std.experimental.logger.core.sharedLog isn't thread-safe

Logger sharedLog comment on thread-safety

---

std/process.d

Setting null as environment value leads to removing this variable
according to SetEnvironmentVariable documentation while Posix leaves
unspecified what setenev should do if value is null.

Make behavior of environment.opIndexAssign on Posix to match the behavior on Windows

---

std/xml.d

There was no reason for them to be system. Seems like this code was written before `@safe` was added to the language.

Make two common functions in std.xml @safe

---

std/algorithm/iteration.d

This reverts #4961 and fixes https://issues.dlang.org/show_bug.cgi?id=17264.
Rationale:
1. The PR introduced a performance regression for the most common case.
- As it added additional state to the type, it is unlikely that it can be optimized away by an optimizing compiler.
2. It introduced a regression (issue 17264).
- The PR author has not responded to the regression notification within 5 days now.
3. The PR fixes a rare use case. To run into the bug, you must use `uniq` in combination with two uncommonly-used features:
- Using `uniq` with a custom predicate, i.e. filtering items only when they are partially equal.
- Using `uniq`'s `BidirectionalRange` primitives (i.e. `.back`).
As for fixing the original bug ([16588](https://issues.dlang.org/show_bug.cgi?id=16588)), I can think of two …

Revert #4961 (uniq.back)

---

std/xml.d

Removes an odd choice to keep the base string of a tag as a pointer to a string rather than the string itself.
I don't see an obvious reason why this was done, so I removed it for code simplicity and possible speed improvements.

Remove a level of indirection from internal std.xml.ElementParser code

---

posix.mak

This allows to run the execution of the independent public unittests (aka ddoc-ed) in parallel with GNUMake (e.g. `-j16).
This is a first step on the journey of cleaning up the `Makefile`.
CC @jmdavis @schveiguy

Allow parallel execution of public unittests

---

std/string.d
std/xml.d

These functions are old D1 string functions from before std.regex's existence. With std.regex and std.algorithm, these functions are no longer needed, and their use should be discouraged, as the std.algorithm versions will be faster (better search algorithms, better handling of auto-decoding).
Plus, this removes a domain specific language that's in use only in one minor part of D.

Deprecate obsolete pattern matching functions in std.string

---

std/algorithm/mutation.d

[Static if] replace overload constraints with static if (mutation.d)

---

std/getopt.d

I don't think that it makes sense to use slang like "dunno" in a
standard library.

Fix some bad/slangy English in std.getopt.

---

changelog/split-std-datetime.dd
posix.mak
std/datetime/package.d
std/datetime/stopwatch.d
win32.mak
win64.mak

std.datetime.package has StopWatch, benchmark, comparingBenchmark, and
measureTime, all of which use TickDuration (which would be deprecated,
but it can't be deprecated as long as those functions in std.datetime
are deprecated). This commit introduces
std.datetime.stopwatch to replace those functions in std.datetime. In
order to avoid symbol conflicts, std.datetime.stopwatch will not be
publicly import in std.datetime.package until the old symbols have been
removed.
std.datetime.experimental.stopwatch contains StopWatch and benchmark
which have essentially the same APIs as the ones in
std.datetime.package, but they use MonoTime and Duration.
comparingBenchmark has not been ported to MonoTime and Duration, because
it is simply a wrapper around benchmark.
measureTime has not been ported to …

Add the MonoTime equivalents of std.datetime.StopWatch/benchmark.

---

std/range/package.d

Fix issue 16246 - cannot call iota with 3 [u]bytes or 3 [u]shorts

---

std/datetime/stopwatch.d

I'm seeing a bunch of random failures on Win32 on this line, e.g.:
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2557560&isPull=true
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2557534&isPull=true
I suppose an alternative would be to sleep for e.g. twice the timer resolution.
CC @jmdavis

std.datetime.stopwatch: Fix random test failure on Win32

---

changelog/std-range-slides.dd
std/range/package.d

* fixed some small use of over-applied attributes
* fixed some error messages
* renamed `slides` to `slide`

Clean-up for PR #4027

---

std/range/package.d

Practically reopening https://github.com/dlang/phobos/pull/5396

Fix Issue 15720 - iota(long.max, long.min, step) does not work properly

---

std/datetime/systime.d

ISO 8601 says that it's up to the application to decide how many digits
to put in the fractional seconds if they're present. `SysTime.to*String`
puts up to 7 (stripping trailing zeroes), because that's
hecto-nanosecond precision, and `SysTime` holds the time in
hecto-nanoseconds. Currently, `from*String` only accepts up to 7 digits in
the fractional seconds, which _does_ follow the spec in that (per the
spec) the number of digits is up to the applications. However, while we
never emit more than 7 digits, other applications do, so only accepting
7 digits makes us incompatible with them, whereas accepting them would
make us more compatible with other programs, and it would actually be
more efficient, since we'd have fewer checks in the code.
So, these changes make is so that …

Fix it so that SysTime's from*String supports more than 7 digits.

---

std/file.d

There are a lot of lot hanging fruits in `std.file` and in general imho we should invest a lot more work in making Phobos work nicely with `@safe` because currently it's really an empty promise as every second standard library function needs to be `@trusted` ...

Fix issue 17394 - mkdirRecurse isn't @safe

---

std/typecons.d

This is a mitigation for [Phobos issue 15645 - Tuple.slice() causes memory corruption.](https://issues.dlang.org/show_bug.cgi?id=15645)
Through several previous discussions, the community reached the conclusion that there is no *good* solution to this problem - that is, one which preserves *all* of the following desirable characteristics:
1) Breaks no currently working code.
2) Actually *fixes* those cases which currently silently corrupt data.
3) Optimal (or very close) performance in all cases.
4) `Tuple` slices are just 100% normal `Tuple`s.
5) Simple and implementable in very few lines of code.
The candidates solutions were:
A) [Front-pad Tuple by-ref slices as needed to correct the alignment of the members.](https://github.com/dlang/phobos/pull/3973) (Violates 4 & 5)
B) [Slice …

issue 15645 - Prevent unsafe usage of Tuple.slice

---

std/conv.d

In order to fix https://issues.dlang.org/show_bug.cgi?id=6227, we need to recommend the appropriate way of comparing different enum types if the user wants so. This supports that.

Add asOriginalType function for enums

---

circleci.sh
std/parallelism.d

This adds a work-around to the non-deterministic coverage fluctuations
in std.parallelism. Lines with `nocoverage` on them will be excluded
from coverage analysis, and be considered as not containing any code.

Allow ignoring individual lines for coverage analysis

---

std/path.d

If you're dealing with types which are convertible to string, they _must_ be converted at the call point, or if any portion of the string is returned by the function, you're returning a slice of a memory local to the function, which is obviously very bad. I don't know if -dip1000 can catch all such cases yet, but it at least did with `baseName` once I added some additional tests.
In any case, `isConvertibleToString` is inherently unsafe because of this problem, and we need to excise it from Phobos, but first we need to fix it so that nothing in Phobos uses it anymore. std.path also has `BaseOf` that it uses in conjunction with `StringTypeOf` to essentially do what `isConvertibleToString` does. So, `BaseOf` and all uses of it need to go too.
This PR just fixes `baseName` and `dirName` in …

Fix safety issues with baseName and dirName

---

std/digest/crc.d

Add crc64 support

---

std/digest/crc.d

Follow up to https://github.com/dlang/phobos/pull/5047
I didn't see this during my review. Sorry for the noise.

Moved ddoc unittest block back to its proper position in std.digest.crc

---

changelog/std-digest-digest-secureCompare.dd

Unfortunately Ddoc doesn't support real Markdown. Imho we should extend the subset of Markdown that is accepted by Ddoc, but that's a challenge for another day.
This PR is simply intended to fix the changelog, as  it currently looks like this:
https://dlang.org/changelog/2.075.0_pre.html

Unmarkdownify the secureCompare changelog entry

---

std/algorithm/searching.d

No need to auto decode if looking for a ASCII character
Results
```
old	523 ms, 91 μs, and 5 hnsecs
new	302 ms, 142 μs, and 1 hnsec
```
Code
```d
import std.datetime;
import std.functional;
enum testCount = 100_000_000;
bool startsWith1(alias pred = "a == b", R, E)(R doesThisStart, E withThis)
if (isInputRange!R &&
is(typeof(binaryFun!pred(doesThisStart.front, withThis)) : bool))
{
return doesThisStart.empty
? false
: binaryFun!pred(doesThisStart.front, withThis);
}
bool startsWith2(alias pred = "a == b", R, E)(R doesThisStart, E withThis)
if (isInputRange!R &&
is(typeof(binaryFun!pred(doesThisStart.front, withThis)) : bool))
{
if …
```

Removed auto-decoding from the single needle version of startsWith

---

std/xml.d

Removed unsafe pointer access and marked some functions as @safe in std.xml

More safe fixes for std.xml

---

std/format.d
std/json.d

A loss-less roundtrip (to string <=> parse) apparently isn't guaranteed when using double-precision reals.

Relax a few unittests for double-precision reals

---

std/format.d

* Use `switch (index) foreach` to simplify code - see commits.
* Fix integer width/precision message which now applies to separator char too.
* Throw exception when positional format spec index exceeds `args.length`.
Note: `formatNth` is used for positional (and standard) formatting, `getNth` is used for reading integer width/precision and format separator char.

std.format: Refactor argument indexing, improve exception messages

---

std/datetime/date.d

Following https://github.com/dlang/phobos/pull/5404, this PR optimizes the `fromISOString` constructor of `TimeOfDay` substantially.
Changes
* Removed conversion to `dstring` as `to` no longer auto decodes
* Used conversion to `uint` to auto check for bad characters, removing three extra loops
* Replaces use of `format` with `text` for error messages, as format is slower due to string parsing when all you really need for this is concatenation
Results
```
old	4 secs, 347 ms, 869 μs, and 3 hnsecs
new	929 ms, 331 μs, and 1 hnsec
$ dmd -release -inline -O test.d && ./test
old	9 secs, 175 ms, 614 μs, and 7 hnsecs
new	1 sec, 896 ms, 854 μs, and 5 hnsecs
``` 
Benchmark code
```d
import …
```

Optimized std.datetime.date.TimeOfDay.fromISOString

---

circleci.sh
posix.mak
std/datetime/systime.d

The publictests checking got accidentally broken as part of #5364 (and stayed silent, but green).
Luckily not much has slipped in since, so we better hurry to enable it again ...

Re-enable publictests checking on CircleCi

---

std/traits.d

Note: unittest serves as a regression test to make sure the circular reference bug does not come back.

Fixed circular reference bug in fullyQualifiedName.

---

std/experimental/logger/core.d

was already fixed but had no fixture

fix Issue 15517: std.experimental.logger: using 'sharedLog' to change to file logging for default logger does not work

---

std/container/array.d

As long as [DIP82](https://wiki.dlang.org/DIP82) isn't implemented, it's a pretty bad idea to use unittest blocks within a templated aggregate.
This is one of the few small things that broke Vibe.d and the Dlang-Tour with dmd-nightly ...
CC @ZombineDev 
The linker error can be observed starting with https://github.com/dlang/phobos/pull/5295

Fix Issue 17452 - Undefined references in std.container.array

---

std/complex.d

Seeing as the constructors weren't documented, I half-expected there were none and that therefore `Complex!double(0)` would leave `.im == double.nan`

Document std.complex .im 0 initialization

---

std/traits.d

Resolve #15335 Remove ability in getSymbolsByUDA to get a private members If it is located in another module.
If you trying to get symbols from another module you will get errors. This commit resolve this. Now you can access to all attributes if you have access otherwise you will not get private members but also not throws errors.
examples:
**uda.d**
```D
enum Attr;
struct HasPrivateMembers
{
@Attr int a;
int b;
@Attr private int c;
private int d;
}
```
**main.d**
```D
unittest
{
import uda : Attr, HasPrivateMembers;
// Trying access to private member from another file therefore we do not have access
// for this otherwise we get deprecation warning - not visible from module
static assert(getSymbolsByUDA!(HasPrivateMembers, Attr).length == 1);
static …
```

errors with getSymbolsByUDA to get a private members

---

std/algorithm/comparison.d

I already removed most of these in another PR. I must have missed these ones.

Remove some debug writelns

---

std/conv.d

When DMD encounters string concatenation that can be done at compile time, it automatically inserts the resulting string literal into the program at that location.
This removes two string allocations.

Removed extra string allocations in std.conv.to

---

std/datetime/date.d

Here's a summary of the changes
* Replaces use of `format` with `text` for error messages, as format is slower due to string parsing when all you really need for this is concatenation
* The string being passed must be all ASCII characters to be valid, so there is no need to convert it to a `dstring`
* There's no need to check if the day and month strings are all digits if you're going to convert them anyway. Leave validation to the conversion functions. This eliminates some loops.
* Changed the conversion to `int` rather than `ubyte`s and `short`s, as they use slower paths inside of `std.conv.parse` than `int`.
Here's the results
```
old	4 secs, 541 ms, 59 μs, and 1 hnsec
new	1 sec, 410 ms, 713 μs, and 4 hnsecs
```
Result with second commit
```
old	4 …
```

Optimized std.datetime.date.Date.fromISOString

---

std/math.d

Verified on LDC/AArch64.
Similar to other implementations, adapted for wide case.

std.math.lrint: Implement for 128 bit reals

---

std/math.d

Also minimally uncrustify code. Verified on LDC/AArch64.

std.math.nextUp: Fix 128 bit real implementation

---

std/math.d

The implementation previously failed the existing tests.
Verified on LDC/AArch64.

std.math.ieeeMean: Fix for 128 bit reals

---

std/process.d

The issue on bugzilla states that we are currently missing the functionality of converting a pid to a std.process Pid in order to be able to use the kill function, if someone were to implement a task manager for example.

Partial Fix Issue 16615 - convert os pid to std.process Pid

---

std/stdio.d

Eliminate redundant `static` in `static __gshared`

---

std/range/package.d

This was causing a ddoc unbalanced parens error, and possibly may have also broken the HTML output.

[Trivial] Fix wrong parens in std.range ddoc.

---

std/meta.d

This particular unittest does not give any additional information to the user, and the bugzilla note only serves to confuse. So it should not be part of the ddoc'd unittest.

[Trivial] Hide bugfix unittest from ddoc.

---

std/stdio.d

fix Issue 17472 - typeof(stdin) is no longer a File

---

std/process.d

Reverts dlang/phobos#5086
See https://github.com/dlang/phobos/pull/5086#issuecomment-307426691 for rationale.

Revert "Partial Fix Issue 16615 - convert os pid to std.process Pid"

---

std/traits.d

Reimplement to remove dependency on demangler.
Blocked by https://github.com/dlang/dmd/pull/6829

reimplement std.traits.ParameterStorageClassTuple()

---

std/xml.d

Add annotations to make its interaction with Object safe, and scope to make it work with -dip1000.
It requires covariant overrides to work, so it is blocked by https://github.com/dlang/dmd/pull/6731

std.xml: make work with -dip1000

---

std/conv.d

Enables conversions to string for structs with a disabled postblit

Fix Issue 16108: to!string fails on struct with disabled postblit

---

std/traits.d

Reverts dlang/phobos#5427. Let's see if this takes care of the errors in vibe.

Revert "reimplement std.traits.ParameterStorageClassTuple()"

---

std/range/primitives.d

Should this be a compiler error? cc @WalterBright

Eliminate redundant __gshared, immutable data is shared already

---

circleci.sh
posix.mak
std/conv.d
std/digest/crc.d
std/range/package.d
std/stdio.d

Seems like we silently have disabled the style targets on CircleCi during the Makefile re-organization at DConf.
Luckily the number of "violations" that got in is fairly small, but there was a great variety...
CC @CyberShadow @andralex @JackStouffer

Fix CircleCi: actually run the style targets

---

std/container/dlist.d

There are currently two ways to remove elements from DList while iterating over it:
* using `Range remove(Range r)` wich takes private DList.Range as a parameter.
* using `Range linearRemove(Take!Range r)` with r being of type Take!(DList.Range).
Both ways are unable to provide an efficient solution to the following problem:
`While iterating the list backwards, remove arbitrary elements.`
Two proposed methods exploit cursor nature of ranges, and provide means to remove elements form the list while iterating over it, in one loop.
Additionaly, I would like to bring up the idea of further encouragement of cursor properties of ranges in Phobos. Quick glance at std.container shows, that many of them share the abovementioned problem, or rely on Take!Range and may or may not be optimal (depends …

DList mutation: popFirstOf and popLastOf

---

std/experimental/allocator/package.d

Eliminate shared this for allocators

---

std/process.d

This commit changes behavior of spawnProcess on Posix.
Previously spawnProcess just reported child errors via perror. But the true D way is to throw exception. The problem is that it's not easy to transfer error from forked process to parent. This commit uses pipes to solve this problem.
This commit also adds new overload for ProcessException.newFromErrno that allows to create exception object from arbitrary error number, not just from the current value of errno.
To check that it works:
```
touch emptyfile
chmod +x emptyfile
```
Then use spawnProcess on emptyfile. The old phobos will just report error to stderr. The patched one will throw an exception with message saying that exec format is invalid.

Track errors that may happen in forked process on Posix

---

std/algorithm/package.d
std/datetime/date.d
std/experimental/allocator/building_blocks/free_list.d
std/json.d
std/math.d
std/random.d
std/socket.d
std/traits.d

Seems like we should really check for such errors automatically ...
Discovered in https://github.com/dlang/dlang.org/pull/1694#issuecomment-308663796

Fix invalid undefined Ddoc macros

---

std/xml.d

Regression was introduced by #5380. I don't know what exactly is wrong with it. Just reverting and adding a test.

fix a regression in std.xml (2.075a)

---

changelog/std-range-has-length.dd
std/range/primitives.d

Fixes https://issues.dlang.org/show_bug.cgi?id=16566. `hasLength` was in fact intended to allow only integrals, but its code predates `alias this` and we didn't update it.
Throughout Phobos we use interchangeably `auto s = r.length;`, `size_t s = r.length;`, cache the length of a range in a variable, or just use it as a `size_t`. Supporting other types than `size_t` meaningfully would put too much burden on the definition and the implementation.

Restrict length

---

std/range/package.d

https://github.com/dlang/dlang.org/pull/1526#issuecomment-309263501

std.range.package: Fix DDoc syntax

---

osmodel.mak

Changes copied from https://github.com/dlang/druntime/pull/1843

osmodel.mak: add comments

---

.dscanner.ini
posix.mak
std/range/package.d
std/uni.d

The Dscanner check for long lines turned out to be erroneous (see e.g. https://github.com/dlang-community/D-Scanner/pull/465 or https://github.com/dlang-community/D-Scanner/pull/440)
Hence, some bits of Phobos kept hidden.
Unfortunately I don't know a good way to deal with `std/datetime/timezone.d` (the parser expects every item to be on a single line), but in the worst case we can now (#5495) always do `-std.datetime.timezone`
Any ideas @jmdavis?

Fix long lines in Phobos

---

changelog/split-std-datetime.dd

Fix the upcoming changelog (https://dlang.org/changelog/2.075.0_pre.html)
Ddoc is a really nasty engine, everyone gets punished if there's a missing parenthesis ...
@CyberShadow should we automatically replace all parenthesis which aren't in macros by the `LPAREN` or `RPAREN` to avoid stuff like this in the future?
Or maybe simply counting the braces and making it a hard error? (Ddoc doesn't support this)

Add missing closing parenthesis to changelog entry

---

std/file.d

We _really_ should get rid off this anti-feature in Ddoc to auto-magically highlight all words in the doc that match the parameter or name of the symbol ... it's highly error-prone!
https://dlang.org/phobos/std_file.html#.slurp

Fix REF links in std.file.slurp

---

changelog/pattern-deprecate.dd

Added pattern migration guide to the change log

---

circleci.sh

This should fix the CircleCi build failures on older PRs and avoids the unnecessary need to rebase.
Background: we merge the PR branch into the target branch, hence the newest `circleci.sh` is always applied, but unfortunately we the `circle.yml` isn't updated. While we could use just one target e.g. `test`, using multiple has the advantage of visually grouping them nicely and thus helping a reader to track down the root of the failure.
CC @CyberShadow @schveiguy @JackStouffer @ZombineDev

Re-add has_public_example to circleci.sh for legacy compatibility

---

std/math.d

The fptan instruction pushes a 1.0 onto the FPU register stack after a successful operation, but when abs(input) >= 2^63 the C2 flag is set to indicate that the input was out of bounds, _and it doesn't push the 1.0_.
Prior to this PR, the top value of the FPU stack was popped irrespective of whether C2 was set, which in the case of an out-of-bounds input caused the input to be removed from the stack and ultimately resulted in an incorrect return value of -nan. This PR changes this behavior, only popping after fptan when C2 was not set.
See: http://x86.renejeschke.de/html/file_module_x86_id_109.html

Fix tan returning -nan for inputs where abs(x) >= 2^63

---

std/traits.d

Analogous to https://github.com/dlang/dlang.org/pull/1701

Issue 17224 - Foreach documentation still refers to TypeTuples, rather than AliasSequences

---

std/experimental/allocator/package.d

This switches to lazy initialization of theAllocator, so that accessing it form within `shared static this` works as expected.

Issue 17564: Eliminate "static this" for theAllocator

---

std/typecons.d

And while we're at it, might as well use the new backtick notation for `$(D ...)`.

[trivial] [dox] Fix broken ddoc macro.

---

std/math.d

See #4132 and the revert of it in #4592.
Added a comment so that the mistake is not done for the third time in a row.

Fix ARM unittest (again) in std.math.

---

std/experimental/allocator/building_blocks/segregator.d
std/net/curl.d
std/regex/package.d
std/stdio.d
std/string.d
std/typecons.d

Follow-up to https://github.com/dlang/phobos/pull/5523 (let's automate this)
dlang.org PR (for the automated check): https://github.com/dlang/dlang.org/pull/1782

Fix broken ddoc

---

std/exception.d

Users should know from docs that there's a constructor that takes error code.

Add documentation comments for ErrnoException constructors

---

std/datetime/date.d

~The only controversial part of this PR is in `dayOfYear`. There I changed `throw new DateTimeException(msg)` to `assert(0, msg)`, because that prevented a lot of stuff from being @nogc. Even though this technically is a breaking change, I would regard this use of exceptions inappropriate as it is meant to catch a programmer error, rather than incorrect user input. From the programmer's side of view, it is trivial to validate the user's input simply by using `std.datetime.date.yearIsLeapYear` and comparing with either `daysInLeapYear` (366) or `daysInYear` (365).
(Speaking of which, `daysInLeapYear` and `daysInYear` should probably be made public.)~
Edit: I changed this PR so that exceptions were changed to asserts only internally. The external API still uses exceptions, so there are no …

Annotate with @nogc most of std.datetime.date's API

---

std/concurrency.d

Reboot of #5309 which is a reboot of #5194.

Generator implements InputRange interface

---

std/exception.d
std/file.d
std/process.d
std/stdio.d

I found too many similar pieces of code in phobos code related to errno string handling.
Make it into one errnoString function. For now it's package function, but can be made public.
There's also a lot of duplication in std.socket code related to the same thing, but I did not touch it yet.

Add errnoString to remove code duplication from some modules

---

std/datetime/date.d
std/datetime/interval.d

Months are 0-11 in C's tm and the old std.date, so it's better to clarify the range for every instance of `int month` in the API.

std.datetime: Clarify range of integer month parameters

---

.codecov.yml

Apparently CodeCov seems to wait until all CIs have finished:
This is based on a CodeCov issue I found:
https://github.com/codecov/support/issues/312
On the CodeCov side it looks like this:

Immediately send CodeCov notifications

---

std/format.d

The first commit adds a test for a previously-untested / undocumented feature of `std.format`.
I didn't add documentation for it (it seems very non-standard and of little use), but since it's here, it should be tested to ensure no regression happens.
The second commit modernizes the code which calls `formatValue`. Commit message below:
```
The previous code was needlessly complicated, storing arguments' as `void*` in an array,
and having a matching array of delegates to cast them.
It was not ctfe-able which required an extra code path, and tricks such as an artificial call to the `formatValue` function to ensure correct inference of `@safe`ty.
The new code do away with those limitations by simply using a switch of which branches are CT-generated.
This simple technique makes the code …
```

Simplify and improve format positional argument output (+bonus test)

---

std/traits.d

The first commit fixes infinite recursion when a class has a member of its own type. (Then I realized that class references don't own a context pointer, so `hasNested` should ignore class reference *members* of an aggregate - this has been dropped for now though).

std.traits: Make hasNested ignore class reference members

---

circleci.sh
posix.mak

After https://github.com/dlang/tools/pull/237, we can simplify the Makefile a bit.
CC @CyberShadow 
I considered for a bit doing sth. like:
```
TOOLS_HASH=87c63705dcacac38ba7c84d19699f656d834139d
TOOLS_DIR=../tools-$(TOOLS_HASH)
```
But then dropped it because from the developers we can expect to have moderately recent tools version around (they know how to pull if they get an error) and it would be probably pretty annoying to have multiple versions of `dlang/tools` around.

Upgrade to latest tools

---

std/json.d

Please see the individual commits for details.

JSON fixes

---

std/parallelism.d

Stupid workaround to get `rdmd_test` compile without errors...

Fix Issue 17539 - std.parallellism.parallel triggers 'statement not reachable'

---

std/algorithm/mutation.d

Rationale: the most common use for this function is to remove an element from an array. Therefore, the first example the user should see in the docs is how to achieve this.  All the rest of the complications, like `remove` not changing the length of the array and what-not, should be discussed *afterwards*, not smack in the user's face.  The current first example is a poor choice for a first example from a user's POV, because it throws a complicated case out there without first telling the reader (presumably someone new to the language, since seasoned D coders wouldn't be needing to read the docs for `remove`) how to accomplish the simplest, and most common, use case.

Improve docs for std.algorithm.remove.

---

std/datetime/date.d

A micro optimization. No reason to allocate the string twice.

Remove some extra string allocations in std.datetime.date.datetime

---

circleci.sh
posix.mak
std/algorithm/searching.d
std/csv.d
std/datetime/timezone.d
std/file.d
std/string.d
std/uni.d
std/windows/charset.d
std/windows/registry.d
win32.mak
win64.mak

https://github.com/dlang/phobos/pull/5083#issuecomment-313140290
> Yeah but it doesn't make sense otherwise, does it? Seems antithetical to deprecate something for everyone else but not ourselves.
> Any reason not to enable `-de` on the test suite then?

Trigger a hard error on deprecation messages

---

std/traits.d

There seems to be no difference in results anymore. The current implementation relies on a given mangling scheme, but his might change soon with https://github.com/dlang/dmd/pull/5855.

map std.traits.mangledName directly to mangleof

---

std/json.d

See also: https://github.com/dlang/phobos/pull/5541#issuecomment-313282541
CC @CyberShadow 
(will investigate how it managed to get through Circle)

Fix style (space between a .. b) in std/json.d

---

std/algorithm/searching.d

Following the discussion in #5545 , I created this separate PR for the count optimization. The implementation uses walkLength to compute the count. If walkLength will be deprecated, then I will replace the call with the code, otherwise we can close the other PR and keep just this oprimization

Optimize count with an overload which calls walkLength

---

circleci.sh

I observed the following on https://github.com/dlang/phobos/pull/5557:
```
libdparse 0.7.0: building configuration "library"...
../.dub/packages/libdparse-0.7.0/libdparse/src/dparse/ast.d(1346,10): Deprecation: cannot implicitly override base class method object.Object.opEquals with dparse.ast.Declaration.opEquals; add override attribute
/home/ubuntu/phobos/../dmd/generated/linux/release/64/dmd failed with exit code 1.
make: *** [generated/linux/release/64/tests_extractor] Error 2
```
In `setup_repos` we merge with the master branch, thus only the later targets have an updated `circleci.sh`.
A long-term solution might also simply be building DScanner without `-de`, but this is the simpler fix for now (the other requires a bit of Makefile fiddling).

Move tools checkout to style_lint to avoid failing PRs

---

std/file.d

This clarifies the terminology used for describing the iteration order of `dirEntries`, as the current terminology has been found misleading.

Improve documentation of std.file.SpanMode (issue 8680)

---

std/string.d

Continuation of https://github.com/dlang/phobos/pull/5180

Removed old debug printfs in std.string

---

std/algorithm/sorting.d

The random coverage error appearing in https://github.com/dlang/phobos/pull/5570, is, as usual, our fault.
https://codecov.io/gh/dlang/phobos/compare/551ffa6e0d247dcdb560feb2e297346886de17d0...8cf459324303a19307ec173d36596dff99d71a11/changes
However, this one can be fixed easily - we just need to use the fixed seeds for the random number generator ;-)

Fix random coverage in std.algorithm.sorting

---

std/datetime/date.d

In the vein of https://github.com/dlang/phobos/pull/5413 and https://github.com/dlang/phobos/pull/5404

Optimized std.datetime.date.DateTime from string methods

---

std/net/curl.d

- To make them distinguishable from (e.g. connection) errors and allow
appropriate handling in client code.

throw specific HTTPStatusException on http request errors

---

circleci.sh
std/c/linux/pthread.d

- use single tests as workaround for Issue 16397
- fix single tests (broken sed command)

fix test coverage

---

posix.mak
std/base64.d
std/file.d
std/typecons.d
std/uuid.d

As no one seems to push this, I went into another round and pushed the status quo one step forward.
---
Outstanding modules
-----------------------------
Here's a list of all the modules that are sill missing - with a short explanation why it's currently blocked.
```
> pmake std/math.publictests
generated/linux/release/64/publictests/std_math.d(90): Deprecation: std.math.equalsDigit is not visible from module std_math
generated/linux/release/64/publictests/std_math.d(90): Error: function std.math.equalsDigit is not accessible from module std_math
generated/linux/release/64/publictests/std_math.d(145): Deprecation: std.math.equalsDigit is not visible from module std_math
generated/linux/release/64/publictests/std_math.d(145): Error: function std.math.equalsDigit is not accessible from …
```

Make more modules runnable

---

std/experimental/allocator/building_blocks/free_list.d

When instantiating SharedFreeList with a 0 minSize and a
chooseAtRuntime maxSize, it will give an error like so:
std/experimental/allocator/building_blocks/free_list.d(822): Error: undefined identifier _min, did you mean alias min?
This commit resolves the error message by using 'min' instead
of '_min', because '_min' is only available when
(minSize == chooseAtRuntime).

Bugfix for "undefined identifier _min" in SharedFreeList.

---

std/concurrency.d
std/random.d
std/typecons.d
std/variant.d

~~With the new `RUNNABLE_EXAMPLE` Ddoc macro, in theory we just need to slap it around documented examples that can be run online. 
Of course, the requires a valid `main` method, imports etc. and examples without output are quite boring to the reader.~~
~~This is a test to see whether more work is required or it "just works".~~
edit: this now just converts documented examples into real `unittests`s, testing the new `RUNNABLE_EXAMPLE` Ddoc macro will happen in another PR.

Make Phobos module examples runnable

---

posix.mak
std/digest/hmac.d

When I first encountered the `version(StdDdoc)` unittest in `std.digest.hmac`, I tried to go "the easy way" and ignore versioned unittest in the tests_extractor (-> https://github.com/dlang/tools/pull/249).
However @CyberShadow correctly reminded me that it makes more sense to fix the outlier and I even discovered another problem about the `version(StdDdoc)` approach - it's not part of the testsuite and apparently at some point in the time `std.digest.hmac` was `@safe` (it's not anymore). I fixed that as well and as a consequence `std.digest.hmac` is now completely `@safe` :tada: 
So I am really happy about @CyberShadow's remark to avoid working around the outlier with the tool!
CC @jpf91

Make std.digest.hmac @safe and runnable

---

CODEOWNERS

GitHub [recently introduced code owners](https://help.github.com/articles/about-codeowners/).
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. When someone with admin permissions has enabled required reviews, they can optionally require approval from a code owner.
Moreover, it's a simple plain-text format:
> A CODEOWNERS file uses a pattern that follows the same rules used in gitignore files. The pattern is followed by one or more GitHub usernames or team names using the standard @username or @org/team-name format. 
For more information, the [help page](https://help.github.com/articles/about-codeowners/) goes into more details.
We were actually looking to implementing sth. similar with the Dlang-Bot, so I am very …

Add initial version of a CODEOWNERS mapping

---

std/datetime/date.d
std/datetime/systime.d

I should have done this years ago, but this makes the documentation
clear that std.datetime's toString is intended simply for easy printing
of the type rather than for code that actually cares about the format of
the string. There are other, explicit functions for code that actually
cares.
And this reminds me, I really need to get back to the custom formatting stuff that I started earlier this year - something else which also should have been done years ago.

Fix issue 16993: Clarify documentation of std.datetime's toString functions.

---

etc/c/curl.d
etc/c/odbc/sqlext.d
std/bigint.d
std/c/linux/socket.d
std/c/osx/socket.d
std/c/process.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/showcase.d
std/internal/math/biguintcore.d
std/internal/scopebuffer.d
std/internal/windows/advapi32.d
std/mathspecial.d
std/mmfile.d
std/socket.d
std/typecons.d
std/uni.d
std/uri.d
std/windows/charset.d
std/windows/registry.d
std/zlib.d

Very very old versions of D (well into 0.x) had imports public by default,
like C header files. This modernizes the codebase and removes the
redundant `private` access specifier.
This has been done with:
sed "s/private import/import/g" -i **/*.d
See also: https://github.com/dlang/phobos/pull/5546#discussion_r125759182
CC @CyberShadow 
I don't think it's worth adding a check here, because no one uses `private import` nowadays.

Remove old, redundant private import access specifier

---

std/algorithm/mutation.d

https://dlang.org/phobos-prerelease/std_algorithm_mutation.html#remove
We really need to turn off this Ddoc "feature".

Fix docs for std.algorithm.remove (avoid Ddoc auto-escape)

---

std/experimental/logger/filelogger.d

I added an optional parameter to the constructor of FileLogger which specifies if the Logger should create the directory path offered. It defaults to false.

Fix Issue 15771 - FileLogger should create the output directory if it does not exist

---

std/math.d

I added a doc comment so that it is known that on windows lround is not implemented.

Issue 5418 - std.math.lround not implemented on win32 and not documented

---

CODEOWNERS

Let's hope that this solves the problem with the CODEOWNERS file. Thanks for noticing @JackStouffer!

Remove invalid stars from the CODEOWNERS file

---

std/concurrency.d

Arguably the `version(unittest)` trick was a bad idea. As a workaround to achieve a similar output, let's use `__gshared`.
Moreover, I moved the sending of the success notification into the receive function, s.t. it's send _after_ the first message has been received ...

Fix Issue 17640 - std.concurrenct writeln conflicts with std.stdio writeln in unittests

---

CODEOWNERS

According to the friendly GitHub support:
> We currently have a bug with CODEOWNERS files where commenting out a line will __stop__ the feature working __entirely__. If you remove any lines with a # it should start to work correctly again. Alternatively - since you have a lot of commented out lines in that file - you can add a space after the # characters which should also fix the issue.
> Formatting it like this should fix the issue, with the space between the # and the filepath:
```
#abc <- Will break the whole file x_x
```
I hope this helps ...

CODEOWNERS: Add whitespace after # comments due to GitHub bug

---

changelog/std-meta-stride.dd
std/meta.d

As suggested in  https://github.com/dlang/phobos/pull/5596#discussion_r126774763 this adds `Stride` to std.meta.
`Stride` allows selecting a stride of the template argument list, e.g.:
```d
alias attribs = AliasSeq!(short, int, long, ushort, uint, ulong);
alias attribs = AliasSeq!(short, int, long, ushort, uint, ulong);
static assert(is(Stride!(3, attribs) == AliasSeq!(short, ushort)));
static assert(is(Stride!(3, attribs[1 .. $]) == AliasSeq!(int, uint)));
static assert(is(Stride!(-3, attribs[1 .. $]) == AliasSeq!(ulong, long)));
```

Add std.meta.Stride

---

std/getopt.d

This fixes an issue in std.getopt private function optMatch. This function is used to see if a command line argument represents an option (e.g. "--file", "-a", etc.). It looks at all the arguments on the command line, including option values. (In `$ command -f 1 -g 2`, "1" and "2" are option values.)
The range violation occurs if an option value is a single hyphen. The `optMatch` function sees the hyphen and assumes it might be an option argument (like "-f"). It then tests the next character in the string. When the value is a single hyphen the next character does not exist.
A single hyphen (or a single `optionChar`) only introduces an option, it is never an option by itself. So the easy fix is to also check that the length is at least 2.
Note: Looking through this code it appears there …

Issue 17650: std.getopt range violation when option value is a hyphen

---

std/range/primitives.d
std/traits.d

https://github.com/dlang/phobos/pull/5461, but this time hopefully without CI weirdness

Convert range primitives to CNF like a boss

---

CODEOWNERS
std/getopt.d

https://github.com/dlang/phobos/pull/5612 should have been targeted at stable.
Also at https://github.com/dlang/phobos/pull/5614 I realized the CODEOWNERS file isn't part of `stable` and will take quite a long time to get be merged back into `stable` again, so I cherry-picked this as well while I was at it.
Note that due to the GH bugs in the CODEOWNERS implementation it took us [three PRS](https://github.com/dlang/phobos/pulls?utf8=%E2%9C%93&q=codeowners) to achieve a working CODEOWNERS file.

Cherry-picking commits to stable: 17650 + CODEOWNERS

---

std/algorithm/setops.d

And adds: alias nWayUnion = multiwayMerge. Also the documentation is updated accordingly.
This is a partial fix to Issue 6718[1]
[1] https://issues.dlang.org/show_bug.cgi?id=6718

Rename nWayUnion => multiwayMerge and NWayUnion => MultiwayMerge

---

std/algorithm/searching.d

First step at allowing partial instantiation of `find` (I will try to keep the PRs small) - more work to follow soon.
This PR groups three overloads into one overload. As discussed so often - a user shouldn't need to know about internal performance optimization, so this should be valuable regardless.
See: https://github.com/dlang/phobos/pull/5497#issuecomment-310289207
CC @CyberShadow @andralex

Unify needle overloads of std.algorithm.searching.find

---

std/range/package.d

Created a new PR due to CI errors in https://github.com/dlang/phobos/pull/5605

Unify function overloads in std.range

---

std/algorithm/setops.d

This is the second part of solving the above metioned issue. Adds the function multiwayUnion which computes the true union of 2 ranges. The implementation returns the result of nWayUnion piped through  uniq. This will be updated after #5619 is merged.
Next step is to add a multiwayIntersection function which computes the intersection of sets.

[WIP] Fix Issue 6718 - nWayUnion => nWayMerge, plus true nWayUnion

---

std/algorithm/sorting.d

[Static if] replace overload constraints with static if (sorting.d)

---

std/traits.d

The current doc for isStaticArray is pretty ridiculous: the ddoc'd unittest gives the user examples of what is *not* a static array, but not even a single example of what *is* a static array!

[dox] Positive examples for isStaticArray.

---

std/concurrency.d

Spotted here: https://codecov.io/gh/dlang/phobos/compare/e8ebd82eab15bf8b9378a9cd8d16090cec999a81...9efa504bdca2b2644375e86d3b1527170512b726/changes
(at https://github.com/dlang/phobos/pull/5620).

Mark random coverage line in std.concurrency

---

std/process.d

The pid() property of the ProcessPipes struct asserts that the pid is not null. This makes it impossible to check for a null pid (see bug description for a more detailed description). The solutions are : either remove the assert and expect the user to check for a null pid or add a new function isNullPid. In my opinion, the first solution is the better one as checking for a null pid can be simply done and doesn't need a one liner function. Either way, if for some reason, the latter solution is preferred, I will update my commit.

Fix Issue 17250 - ProcessPipes (std.process) should provide a test for a null pid

---

posix.mak

Small-scale follow-up to https://github.com/dlang/phobos/pull/4968 as triggering deprecation isn't very welcome, but at least we can stop newcomers being confused.
Other PRs: https://github.com/dlang/phobos/pull/5484 and https://github.com/dlang/dlang.org/pull/1701

Issue 17224 - Remove std.typetuple from the documentation build

---

std/functional.d

The first example is taken from the [DLang tour](http://tour.dlang.io/tour/gems/7).
It was assumed that memoization works with more than basic builtin-types.
This fixes the issue with unlimited, but for the limited size I get the weird error that after the args are emplaced into the allocated memo array, the array is changed - it is reverted:
```
[7, 5, 3] // args
[3, 5, 7] // args after being emplaced to memo
```
Has anyone an idea about the latter?

Fix issue 16079 - memoize should work with arrays and objects

---

std/functional.d

Sorry for this ... we really need to automate to restart all CircleCi builds from time to time (e.g. https://github.com/dlang-bots/dlang-bot/issues/132).
See also: https://github.com/dlang/phobos/pull/4367

Add @safe to unittests to fix CircleCi

---

std/digest/crc.d
std/digest/md.d
std/digest/murmurhash.d
std/digest/ripemd.d
std/digest/sha.d

Clickable links are nicer!
- Convert references to MREFs
- Add source link to std.digest.murmurhash
- Add assert to the examples in std.digest.murmurhash

std.digest link cleanup

---

std/functional.d

There's even more broken stuff here here :/
With current CSS styling
---------------------------------
@JackStouffer There was https://github.com/dlang/dlang.org/pull/1593, which mainly was about the `left-padding` here:
```css
```css
table.book tbody a:first-child + a {
padding-left: .6em;
}
/*style.css:1034 */
table.book tbody a + a {
padding-right: .6em;
}
```
Without:
-----------
If both left and right-padding are disabled:

std.functional: Fix more DDoc links

---

std/json.d

On input, both escaped and unescaped slashes must be recognized. They don't
need to be escaped on output.
Fixes issue 17587 (enhancement request).
----
As far as I see, the argument for escaping slashes is that it turns `"</script>"` into `"<\/script>"`. The latter can be put into JavaScript code without breaking it. But one can still emit stuff like `"<!-- <script>"` which confuses JS engines. So this seems a weak argument.

don't escape slash in toJSON (issue 17587)

---

changelog/std-base64-base64urlnopadding.dd
std/base64.d

Many applications require Base64URL without the padding: RFC4648, RFC7515.
Vibe.d provides this alias, but many other libs (jwtd) have their own non-trivial implementation, even though Phobos is flexible enough.

Added Base64URLNoPadding (backport from vibe.d)

---

changelog/std-socket-abstract.dd
std/socket.d

Lack of support for abstract UNIX domain sockets was discussed in forums [1], but I couldn't find a related issue in bugzilla.
According to [2]: "abstract:  an abstract socket address is distinguished (from a pathname socket) by the fact that sun_path[0] is a null byte ('\0'). The socket's address in this namespace is given by the additional  bytes  in  sun_path  that  are covered by the specified length of the address structure. (Null bytes in the name have no special significance.)"
For this reason, the previous implementation using strlen() was not sufficient, and additional class field containing the length of the address was required.
[1] http://forum.dlang.org/post/mmk50s$1qm$1@digitalmars.com
[2] UNIX(7)

Support abstract UnixAddress

---

std/format.d

At the moment formattedWrite takes output range by value. It prevents to pass non-copyable ranges.

formattedWrite should take output range by reference

---

std/range/package.d

std.range.package - add asserts/static asserts for unused variables in unittests

---

std/conv.d

`parse` with radix requires `isIntegral!T` anyway.

std.conv: Make constraint for `toImpl` with radix clearer

---

std/datetime/date.d

Functions which now have a documented public example:
- valid!"days"
- daysToDayOfWeek
- monthsToMonth
- yearIsLeapYear
- validTimeUnits
- cmpTimeUnits
Some examples reuse parts of previously existing unittests.

Add public examples to std.date.

---

std/bitmanip.d

Makes use of the identity `~x == -1 - x` to cause integral promotion to happen properly.
Blocking https://github.com/dlang/dmd/pull/7013

bitmanip - inure against integral promotion changes

---

std/file.d

Corrected typos and added $(D) where necessary. Added underscores to
non-identifier tokens which weren't properly prefixed (and were
therefore wrongly hightlighted in the docs).
(Note: Further doc improvements will follow in subsequent portions, in order to keep the PRs unbloated and manageable).

Fix documentation for std.file

---

changelog/std-process-config-detached.dd
std/process.d

spawnProcessDetached is function similar to spawnProcess, but user does not need to wait on spawned process to avoid zombies (resource leak). Instead of returning Pid instance spawnProcessDetached returns integer pid via pointer. Rationale: user should not be able to wait on detached process.
Currently only Posix version is implemented. It uses double fork technique and setsid to detach the new process from its caller. Since this implementation reuses a lot of stuff from spawnProcess I moved some implementation details to separate private functions to share them between spawnProcess and spawnProcessDetached.
THIS IS WIP
I'll add more unittests and Windows version later. For now say if you like the idea.

Add spawnProcessDetached

---

std/math.d

Makes use of the identities `~x == -1 - x` and `-x = 0 - x` to cause integral promotion to happen properly.
Blocking dlang/dmd#7013

math - inure against integral promotion changes

---

std/conv.d
std/stdio.d

I added a test so that when the exception contains a '\n' it is outputted as "\\n" so the user knows exactly what the error refers to

Fix Issue 12260 - Improve error of std.stdio.readf when involving whitespace

---

std/traits.d

This an alternative implementation to https://github.com/dlang/phobos/pull/4920

Fix Issue 16744: Add Typeof

---

std/stdio.d

As discussed in https://github.com/dlang/phobos/pull/5591/files#r127962554, using `collectException` is nicer as:
- less, more obvious code
- _ensures_ that an exception is thrown

Fixup 5591 - Shorten unittest

---

std/traits.d

Reverts dlang/phobos#5662 as this hasn't been approved by @andralex 
> @jmdavis the simplest question is: since it's a trivial one-liner, why not just ask the user to do it if they have a need? We need to have a case for high frequency of use.
https://github.com/dlang/phobos/pull/4920#issuecomment-317086769

Revert "Fix Issue 16744: Add Typeof"

---

changelog/std-typecons-AutoImplement.dd
std/typecons.d

This PR adds an AutoImplement template very much like the existing one, but with the additional feature of deriving from a baseclass while auto-implementing an interface.

AutoImplement with baseclass

---

changelog/std-range-input-chunks.dd
std/range/package.d

Rationale: sometimes all you can get is an input range (e.g., `File.byLine`), and it is undesirable to have to buffer the entire input range just to be able to call `chunks` on it. This extension of `chunks` to support non-forward input ranges allows for the possibility of caching such ranges by chunks so that you process it incrementally while offering better range primitives on the cached portion of the range.
For example:
````
File("data").byLineCopy
.chunks(bufSize)
.map!(chunk => chunk.array) // cache each chunk on a buffer
... // now each chunk is a forward range and
// you can do more stuff with it
// Even though outer range is still only input range
````
For now, I'm implementing this as a separate overload of `Chunks`, due to the unfortunate historical accident that `Chunks` was …

Extend std.range.chunks to work with non-forward input ranges.

---

std/array.d

There's nothing about the implementation of `byPair` that precludes it from being used with const AA's, other than the way it's declared.

Fix issue 17711: std.array.byPair ought to work with const AA's.

---

std/traits.d

Looks like probably an oversight that `//` was used instead of `///`.

[dox] [trivial] Enable ddocs for QualifierOf.

---

std/range/package.d

I decided against implementing it for floating pointed iotas because comparing floating points is so unreliable.

Issue 11252 - In operator requested for std.range.iota

---

std/regex/internal/parser.d
std/regex/internal/tests.d

Missing check in charset parser + side effect of how multi-pattern regex was implemented.

Fix issue 17667 - regex([r".", r"[\(\{[\]\}\)]"]);

---

std/regex/internal/parser.d
std/regex/internal/tests.d

Another mistake in charset parser code. 
It's rather baroque I wish we could use some parser combinators for it, should easily fit operator grammar.

Fix issue 17668 - assert failure regex(q"<[^]>")

---

std/traits.d

Improved reboot of the abandoned #5446.

fix issue 17192 - ParameterDefaults fails when parameter is called "i"

---

std/conv.d

An optimization of the conversion to octal.
I also removed an unnecessary `@system` tag on its unittest.
Test benchmark on my machine:
```
$ cat test_octal.d
import std.datetime : benchmark;
int octal_new(const string s) {  // Quick re-write of the new way
int res = 0;
foreach(c; s) {
if(c < '0' || c > '7') continue;
res *= 8;
res += c - '0';
}
return res;
}
int octal_old(const string num) { // Quick re-write of the old way
int pow = 1;
int value = 0;
foreach_reverse (immutable pos; 0 .. num.length) {
char s = num[pos];
if(s < '0' || s > '7') continue;
value += pow*(s - '0');
pow *= 8;
}
return value;
}
int main() {
auto ds = benchmark!(() => octal_new("1234567"), () => octal_old("1234567"))(10_000_000);
real new_ns = to!real(ds[0].nsecs);
real …
```

Faster octal conversion

---

std/experimental/allocator/building_blocks/package.d

Documented Segregator uses GCAllocator for allocation of the blocks
greater than 4072kB, not Mallocator.

Correct the documentation about the used allocator in Segregator

---

posix.mak
std/internal/test/range.d
std/range/package.d
win32.mak
win64.mak

Due to an oversight in PR #5624, an unnecessary `alias this` was left in the implementation of `Chunks`.  This causes an import visibility error when `Chunks` is instantiated from another module.  There is actually no need for this at all, since `empty` can just refer to `impl` directly.
I need some help with the unittest, though: the bug doesn't show up in a unittest in this module, obviously, because it only happens when `Chunks` is instantiated in another module. How to write a Phobos unittest in this case?? As in, where to put it?

Don't use alias this in chunks implementation.

---

std/range/package.d

In operator from righthand side for SortedRange.

---

std/concurrency.d
std/traits.d
std/variant.d

There were 2 major issues:
1. `Variant` was not properly removing the `shared` qualifier when copying data from the stack into the payload (this is always safe, as the `Variant` itself is not shared, so the payload, which is never accessible by reference, is also not actually `shared`).
2. `std.traits.ImplicitConversionTargets` incorrectly returned `const(T)[]` as a valid conversion target for `shared(T)[]`. It should have been `const(shared(T))[]`.
All the tests for the bug were ported to verifying `Variant` could accept the types, and this in turn fixes the `send` and `receive` functions (I added one unit test to verify the original test case to std/concurrency.d).

fix issue 13262 - Cannot send certain shared data to another thread

---

std/range/package.d

The original bug report requested the addition of the function unzip to phobos which is the opposite of zip. Fortunately, the function `transversal` exists (as @wilzbach pointed out) which can be used to solve the problem elegantly. I updated the docs to mention that this feature is called `unzip` in other languages and added the example posted in the bug report.

Fix Issue 6004 - std.range.unzip()

---

std/regex/internal/ir.d
std/regex/internal/parser.d
std/regex/internal/tests.d
std/uni.d

It's a bunch of unwieldy code that I planed to reuse long ago.
Libraries such as ICU also do provide means to construct sets of codepoints from strings with regex syntax.

Add public API for regex charset parser

---

std/range/package.d

fix issue 17780 -  Malformed DDOC links in std.range

---

std/stdio.d

Various `stdxxx` implementations may not be aliasable, so remove the dependency on that.
This is blocking https://github.com/dlang/druntime/pull/1914

stdio: remove reliance on std*** being aliasable

---

std/datetime/date.d
std/datetime/systime.d

The from*String functions in std.datetime did not have tests to make
sure that they worked with various character types or various levels of
constness, and some optimizations that were done to the from*String
functions on DateTime for 2.076 broke them for const strings. So, this
adds tests for all character types and levels of constness to each of
the from*String function in std.datetime, and fixes the functionality
for DateTime that then doesn't pass the tests.

Fix issue 17801: DateTime.fromISOExtString no longer works with const strings.

---

std/typecons.d

Issue 8494 is a two-part issue, with the other part requiring changes in DMD. This takes care of the Phobos side by having `Tuple.opAssign` return `ref Tuple`.
This allows `Tuple` to act like built-in types when assigning to it, e.g. `return myTuple = myOtherTuple;`.

Fix issue 17803 std.typecons.Tuple: opAssign should return ref Tuple

---

.dscanner.ini
std/experimental/allocator/package.d

The parameter must be passed as `ref` (when possible), otherwise this has no effect. Statically checking if the parameter is `ref` would be possible but it is pointless because the operation that's added is super fast (usually `xor reg,reg`) so we can save a bit of compile-time complexity.

fix issue 16512 - Nullify the argument passed to allocator.dispose

---

std/conv.d

Fixes build failure when building testsuite on ARM.

Adjust @safe-ty of 64-bit real unittest.

---

std/traits.d

The trait misses from the ddoc index.

ddoc, add missing isSIMDVector to the index trait

---

std/mmfile.d

All the cases of a mmFile.Mode are present, [as bearophile noticed in 2013](https://issues.dlang.org/show_bug.cgi?id=9501#c3), allowing to drop the assert and make the related switches final.

style, switches in MmFile can be final

---

std/array.d

I added an overload for array which accepts pointers to iterable ranges and calls the existing overload with the value of the pointer.

Fix Issue 15096 - std.array.array cannot be instantiated for pointers to ranges

---

std/concurrency.d

As initiated by @ZombineDev (https://github.com/dlang/phobos/pull/4551#discussion_r130091297).
Depends on #4551 (included here) and https://github.com/dlang/druntime/pull/1605.

let initOnce take a shared Mutex

---

posix.mak

This should remove the CircleCi error message seen in https://github.com/dlang/phobos/pull/5729.
See also: 
- https://github.com/dlang-community/libdparse/pull/169
- https://github.com/dlang-community/D-Scanner/pull/521

Update Dscanner to libdparse 0.7.2-alpha.1

---

posix.mak

@MartinNowak already builds the official releases with `-fPIC` (since 2.072.2) as there was no measurable performance penalty. As more on OSes are switching to -fPIC ([ArchLinux is already in testing](http://forum.dlang.org/post/isncdeeeycbmsfjsmluo@forum.dlang.org)), building everything at Phobos with `-fPIC` only makes sense (we have already `-fPIC` enabled for the C source code in `etc`).
Moreover, as a nice benefit this solves
- the unittest issues from [17375](https://issues.dlang.org/show_bug.cgi?id=17375)
- solves the problem of building DScanner and the tests_extractor on OSes with `-fPIC` enabled (now `DFLAGS` are properly propagated)
CC @CyberShadow 
Other PRs:

Issue 17375 - use -fPIC by default for Phobos on Posix

---

std/meta.d

This solves the problem in the referenced issue. I've added the solution as a documented unit test for `Instantiate`.

Fix issue 9591 - Allow Instantiate template to be public

---

posix.mak

tl:dr: yet another step to make the dev build work smoother with `-fPIC` - we are close to the finish line :)
[By default, DMD passes `-fPIC` to the linker](https://github.com/dlang/dmd/blob/master/ini/linux/bin64/dmd.conf), but sadly the development build of DMD uses a different config and thus doesn't pass `-fPIC` by default. The PR to change this doesn't seem to move into any direction: https://github.com/dlang/dmd/pull/7002
However, thanks to https://github.com/dlang/druntime/pull/1880 and https://github.com/dlang/phobos/pull/5586, which are both in `master` now, the development build of `libphobos2.a` is compiled with `-fPIC` :tada:  and we can thus compile D-Scanner with `-fPIC` as well.
Regarding PRs at D-Scanner:
- master: https://github.com/dlang-community/D-Scanner/pull/523
- …

Upgrade D-Scanner: Compile D-Scanner with -fPIC

---

std/regex/package.d

Just a minor tweak I happened to spot, since I'm currently writing some code that passes the 's' flag.

Include 's' in the list of valid regex flags

---

std/windows/registry.d

The `Key` and `{Key,Value}NameSequence` objects weren't referenced during and after iteration in `...NameSequence.opApply()`, so there was no guarantee the `Key` object owning the HKEY handle would stay alive and keep the handle open - its destructor closes the handle.
This lead to a failing `std.datetime.timezone` unittest for optimized LDC builds.
Pinging @klickverbot @ZombineDev @rainers as involved in the discussion starting [here](https://github.com/ldc-developers/ldc/pull/2252#issuecomment-333325654).

std.windows.registry: Keep Key object alive while iterating over it

---

posix.mak
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/quantizer.d
std/math.d
std/stdio.d
std/traits.d

After quite a bit of work, we are heading for an end :)
This PR removes the last five modules from the runnable blacklist, s.t. with 2.076 all unittests are runnable
(FYI: the effort started in https://github.com/dlang/phobos/pull/4943)
For some modules, I wasn't sure sure on the best approach and I will mark these bits individually.

Enable runnable examples - remove the last modules from the blacklist

---

std/math.d

See also: https://github.com/dlang/druntime/pull/1554
`FloatingPointControl` rounding control and interrupt masks should be given similar treatment.  Where their values all correspond to macros from `fpu_control.h` in libc (there does exist any binding in druntime).

std.math: Use core.stdc.fenv for exception mask values

---

std/algorithm/iteration.d

This fixes incorrect documentation of `std.algorithm.splitter` behavior when the argument is an empty range (https://issues.dlang.org/show_bug.cgi?id=15735). There was significant discussion of the merits changing the behavior vs changing the doc in PR https://github.com/dlang/phobos/pull/4030. The resolution was to change the documentation.
The descriptive text was changed and a pair of examples were added showing the behavior.
Note: I'm considering submitting some additional changes to the splitter documentation to clarify things for users. If reviewers would prefer that I submit these together with this PR please let me know. I'm happy to do both together if that's preferred, though I'm not sure when I'll get to the latter piece.

Fix issue 15735: Correct splitter documentation when arg is an empty range.

---

std/uni.d

Dmitry said he had problems with locally scoping these, [see issue 17813](https://issues.dlang.org/show_bug.cgi?id=17813), but I haven't been able to reproduce on linux/x64 with the latest dmd 2.076.1.  Let's see what the auto-tester says.

Move new top-level selective imports in std.uni to local scopes

---

std/range/primitives.d

Should we implement other range primitives for AA's?

Fix Issue 6409 - std.array.empty for associative arrays too

---

std/typecons.d

I also did some testing and it seems that if Tuple has a list of types longer that 500 you get a recursive expansion error due to the fact that dmd does not support to expand more than 500 times [1]. Accordingly I did some measurements with and without the distincFieldNames constraints and it seems that the performance is not affected by this diff. The worst time without this patch was 3,263s and with patch 3,347s. I think that this is a negligible difference considering that the error message will be very helpful this way. Thanks to bearophile_hugs for his solution which is basically copy-pasted.  
[1] https://github.com/dlang/dmd/blob/master/src/ddmd/dtemplate.d#L7438

Fix Issue 4582 - distinct field names constraint for std.typecons.Tuple

---

win32.mak

On #5331 I've ran into the following issue:
On Windows 32bit, dmd fails to generate `unittest6.obj` because this object has more than 32767 symbols. This PR fixes this issue.

Split unittest6.obj to get past the 32767 max symbols limitation

---

std/experimental/allocator/building_blocks/bucketizer.d

It looks like `alignedAllocate` had some residues, probably from a copy-paste.
Fixed the typos and made the function infer the safety of it's parents.
@andralex @wilzbach

Fix bucketizer aligned allocate

---

std/file.d
std/typecons.d

I have put trusted for some small functions which are basically wrappers for C calls, and made sure that the strings used in the implementation are null terminated.
Since RefCounted is not yet safe, I have also put trusted for the constructor of DirIterator.
The only thing preventing DirIterator to be completely safe, is this issue here [1].
[1] - https://issues.dlang.org/show_bug.cgi?id=17867

Make DirEntry and DirIterator safe

---

std/math.d

This implementation for powmod correctly handles overflow for unsigned types.
For at most 32-bit inputs, to avoid overflow during modulo sum or multiplication, we can cast the values to 64-bit types and do the operations.
For unsigned 64-bit types I implemented a special mulmod and addmod functionality to avoid overflows.
Tested with boost multiprecision powm function.

Fix Issue 6244 - Add powmod / modpow function to std.math

---

std/regex/internal/backtracking.d
std/regex/internal/ir.d
std/regex/internal/kickstart.d
std/regex/internal/parser.d
std/regex/internal/tests.d
std/regex/internal/thompson.d
std/regex/package.d
std/uni.d

Finally I pulled this one off :
- immutable Regex!Char works
- **StaticRegex** is just a **Regex** alias
- enum vs static **ctRegex** doesn't matter
- template bloat is cut by a decent percent - **match*****/**replace***** functions no longer templated by engine type nor **StaticRegex** is a distinct type
- finally single point of managing intrusive ref-counting of Engines
More importantly this opens up future enhancements:
- regex objects now contain a factory that produces optimal matcher for this pattern, the engine choice now can be completely adaptive (each ctRegex has a unique instance of such factory). Now I can special case the heck out of common patterns w/o degrading the design of the library a bit.
- less of good ol' messy code, which eventually should bring more contributions …

std.regex: major internal redesign, also fixes issue 13532

---

std/utf.d

This makes it possible to extract the underlying string from the result of `byCodeUnit` so that it's possible to temporarily wrap a string to pass it to a function that would otherwise auto-decode it but still be able to have a string afterwards (assuming that the function that's called doesn't wrap the `byCodeUnit` range in its own range of course).
Without this, you're frequently stuck having to allocate a new string from the `byCodeUnit` range just so that you can have a `string` again, which is just plain wasteful.

Issue 17905: Add source property to byCodeUnit

---

std/stdio.d

Everytime open or popen are called, we reuse the File object instead of creating a new one.
Also, in some cases, we avoid extra calls to malloc for the Impl struct.

Fix Issue 4763 - std.stdio.File.open() : more efficient implementation

---

std/math.d

Blocking https://github.com/dlang/dmd/pull/7013

fix math.d for 16997

---

std/digest/package.d

This is no longer allowed, per https://github.com/dlang/dmd/pull/7110 which this blocks.

std.digest.package: fix slicing of temp array

---

std/container/dlist.d

https://issues.dlang.org/show_bug.cgi?id=9362
Followed the idea from https://github.com/dlang/phobos/pull/5784 and implemented the same for Dlist.

Add liniarRemoveElement for Dlist

---

std/container/slist.d

https://issues.dlang.org/show_bug.cgi?id=9362
If everyone agrees with this I will go ahead and do the same for Dlist.

Fix Issue 9362 - Add a method to remove one item to std.container.SList

---

std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/region.d

For allocators that implement their own `owns` method, such as `Region`, `owns` is a `pure nothrow @safe @nogc` function.
Allocators that are building on top of such allocators should infer the function attributes from their parents.
This PR is a subset of #5330, as this approach will provide us with better granularity. More smaller PRs to come :)

Make owns pure nothrow @safe @nogc

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/building_blocks/stats_collector.d
std/experimental/allocator/common.d
std/experimental/allocator/gc_allocator.d

For stand-alone allocators, such as `GCAllocator`, `goodAllocSize` is a `pure nothrow @safe @nogc` function.
Allocators that are building on top of such allocators should infer the function attributes from their parents.
This PR is a subset of #5330, as this approach will provide us with better granularity. More smaller PRs to come :)

Make goodAllocSize @safe

---

std/parallelism.d

Wondering how to get rid of the `shared static ~this`. cc @dsimcha @wilzbach @quickfur @JackStouffer @MartinNowak

Eliminate static shared this from std/parallelism.d

---

std/algorithm/mutation.d

- needs to be annotated with return scope, so that the return value
lifetime depends on the argument's lifetime
- cannot be tested because phobos doesn't yet work with DIP1000 and
also because of Issue 17932

fix Issue 17730 - move escapes scope variable in @safe code

---

std/math.d

Slight continuation of #4272.
Changes:
- `FloatingPointControl.roundingMask`: New public RoundingMode value
- `FloatingPointControl.ExceptionMask`: New public base type for exception mask enum.
- `EXCEPTION_MASK`, `ROUNDING_MODE`: Remove internal values.
Now, the only parts that need changing for adding ports are FPU exception masks, and the asm code which gets/set the control word.

Small clean-ups of architecture-specific code in FloatingPointControl

---

std/bitmanip.d

This PR implements opSliceAssign(bool val)/opSliceAssign(bool val, size_t start, size_t end) and opUnary for the "~" operator.

Fix Issue 1998 - std.bitarray should have setAll / opSliceAssign

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/gc_allocator.d
std/experimental/allocator/package.d

For stand-alone allocators, such as `GCAllocator`, `resolveInternalPointer` is a `@safe` function.
Allocators that are building on top of such allocators should infer the safety from their parents.
This PR is a subset of #5330, as this approach will provide us with better granularity. More smaller PRs to come :)

Make resolveInternalPointer @safe

---

std/datetime/systime.d

fix skipped "import clock_gettime"

Solaris: add import clock_gettime to currStdTime

---

std/experimental/allocator/building_blocks/region.d

Allocating `0` bytes should return `null`.
Expanding with `0` bytes should return `true`.

Fix region allocate and expand 0 sz

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/building_blocks/stats_collector.d
std/experimental/allocator/package.d

`owns` should take a `const void[]` argument as it should also work with `const` and `immutable` memory chunks.
Added more unittests in order to ensure that allocators inherit from their parents.

Allocators owns should take const void[]

---

changelog/std-range-package-Transposed-deprecate-save.dd
std/range/package.d

After discussing with @andralex we decided to deprecate this.
CC @schveiguy

Fix Issue 17952 - std.range.transposed save is invalid

---

etc/c/zlib/win64.mak

This avoids some symbol references into the VC compiler runtime and makes it easier to replace it with another runtime.
I suspect there are no similar security checks on other platforms.

win64: build C files with /GS- to avoid "security" calls

---

std/experimental/allocator/building_blocks/quantizer.d

It looks like `alignedAllocate` had some residues, probably from a copy-paste.
Fixed the typos and added an unittest.

Fix Quantizer alignedAllocate typo

---

changelog/std-range-package-Transposed-deprecate-save.dd

https://github.com/dlang/dlang.org/pull/1921 is failing due to the trailing whitespace in the
changelog entry.
Ideally we should build the preview changelog again, s.t. new changelog files will be tested during the stable/master cutoff.

Remove trailing whitespace in transposed changelog entry

---

circleci.sh

With DUB 1.6.0 (part of the DMD 2.077.0 release), DUB will retry
downloads from the DUB registry and alternatively use fallback mirrors.
../dmd/src/posix.mak uses 2.072.0 atm, hence the bump of the host
version.

Bump stable DMD and DUB version

---

std/experimental/allocator/building_blocks/bucketizer.d

`Bucketizer.reallocate` should check if `expand` was successful.

Fix bucketizer reallocate bug

---

etc/c/zlib.d

Before this change, ZLIB_VERSION and ZLIB_VERNUM were unmangled TLS variables.
That exposure was unneeded, and could lead to some clash with other zlib binding which would prevent linking.

Do not expose unmangled ZLIB_VERSION, Z_NULL and ZLIB_VERNUM needlessly

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/bucketizer.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/building_blocks/stats_collector.d
std/experimental/allocator/gc_allocator.d
std/experimental/allocator/mallocator.d
std/experimental/allocator/mmap_allocator.d
std/experimental/allocator/package.d

For allocators that define their own `deallocate`, this does not produce any garbage. All the other allocators must infer this from their parents.

Mark deallocate as nothrow @nogc

---

std/experimental/allocator/building_blocks/affix_allocator.d
std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/null_allocator.d
std/experimental/allocator/building_blocks/quantizer.d
std/experimental/allocator/building_blocks/region.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/building_blocks/segregator.d
std/experimental/allocator/building_blocks/stats_collector.d

For allocators that implement their own `empty` method, such as `KRRegion`, `empty` is a `pure nothrow @safe @nogc` function.
Allocators that are building on top of such allocators should infer the function attributes from their parents.
This PR is a subset of #5330, as this approach will provide us with better granularity. More smaller PRs to come :)
In this PR, there are also a couple of bug-fixes:
- `FallbackAllocator` should attempt to test only if it has supplied at least one stateless allocator
- `Region` didn't take into consideration the `growDownwards` flag
- `Segregator` should use the `Ternary` op `&` instead of `&&`

Make empty @safe

---

std/conv.d
std/datetime/date.d
std/math.d
std/typecons.d
std/utf.d

I started to have a quick look at introducing more `static foreach` at Phobos. 
Sadly even the naive idea to mark all `foreach` loops which definitely are at Compile-Time - e.g. with `AliasSeq` doesn't work:
```d
sed -E "s/foreach(.*)AliasSeq/static foreach\1AliasSeq/" -i **/*.d
```
or in simpler words with a simplified example from Phobos (most of the uses of `foreach` + `AliasSeq` are like this):
```
import std.stdio, std.meta;
void main(string[] args)
{
foreach (S; AliasSeq!(string, wstring, dstring))
{
auto s = S.stringof;
writeln(s);
}
}
```
https://run.dlang.io/gist/6ae32becc7ffaa1296a1a4752cebc294?compiler=dmd
And now with `static foreach` this fails due to the symbol being in the outer scope:
```
import std.stdio, std.meta;
void main(string[] args)
{
static foreach (S; …
```

Change AliasSeq(0, ...) uses of foreach to static foreach

---

std/algorithm/iteration.d

This is an attempt to improve documentation for `std.algorithm.splitter`. This was done mostly by changes to the examples. Partly by starting with a more obvious example and adding examples of different results cases. Also by putting the example with adjacent spaces in a context where it was clearer that there are adjacent spaces rather than a single space when reading on the web.
It turns out there is a bug in the documentation as well, as the overload taking a range as a separator indicates a bidirectional range will be returned. This is incorrect. See this [learn forum answer](https://forum.dlang.org/post/mailman.234.1506810353.3410.digitalmars-d-learn@puremagic.com) by @jmdavis. This was corrected as well.

Documentation improvements for std.algorithm.splitter.

---

std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/common.d

alignedReallocate should return false if alignedAllocate fails.
This change however caused the FallbackAllocator tests to fail.
This is because testAllocator uses a FallbackAllocator with implicit constructor, which initializes its members, the primary and fallback allocators, to default values. 
Therefore stateful allocators used by the FallbackAllocator would be not properly initialized, causing tests to fail.
The change is to run tests for FallbackAllocator only for stateless allocators.
Thanks,
Alex

alignedReallocate returns false on failure and FallbackAllocator needs stateless allocators for test

---

std/experimental/allocator/building_blocks/bitmapped_block.d

When passed chooseAtRuntime as a template parameter, BitmappedBlock receives an extra constructor parameter for the block size.
Thanks,
Alex

Fixed Issue 16253 - BitmappedBlock allocator not working with chooseAtRuntime

---

std/experimental/allocator/mallocator.d

The rationale for adding the primitive is that, like explained on bugzilla, the Windows version made for the _Digital Mars_ standard C library already included a "pseudo" alignedReallocate that actually just allocates a new block, copies the old one and frees it.

fix issue 16398 - experimental allocators, add aligned reallocation for Posix

---

std/stdio.d

I also did the same for LockingBinaryWriter and added a test case for each.

Fix Issue 9661 - LockingTextWriter should increment file handle reference count

---

std/container/array.d

Using pureMalloc like std.typecons.RefCounted does would make it
possible to use std.container.Array in  `pure` code.

Fix Issue 17919: Make std.container.Array use pureMalloc

---

std/experimental/allocator/common.d

alignedReallocate test assumed that if a pointer would be aligned to 'alignment', it wouldn't be aligned to 'alignment + 1'.
This is clearly wrong and it caused the test to fail at times.
It should be fine now and sorry for causing this bug,
Alex

Fix Issue 17986 - Erratic failure with std/experimental/allocator/common.d(445): unittest failure

---

std/array.d

I was going to add this function because it's so basic. But then noticed it already existed, just undocumented. The comment said that was because it's not CTFE:able so I made it so.
I also made an unittest to verify it works with @nogc.

std.array.overlap made ctfe:able and redocumented.

---

std/traits.d

__postblit represents a directly declared postblit constructor, but any
struct which either has a postblit constructor or which has a member
which has a postblit constructor will have __xpostblit. So, we should
only need to check for __xpostblit instead of recursively checking all
of the member variables for __postblit.

Simplify hasElaborateConstructor.

---

std/algorithm/searching.d

As I pointed out in https://github.com/dlang/phobos/pull/5497#issuecomment-309629180, `findSkip` is very similar to `skipOver` - in fact before #5497 neither `skipOver` nor `findSkip` has a `pred`-only overload.
My point is that there's no argument to add this overload to `skipOver` and not to `findSkip` - on the contrary there's a even a case for only `findSkip` that @CyberShadow [pointed out](https://github.com/dlang/phobos/pull/5543#issuecomment-313602236):
> That loop simply consumes the two input ranges for comparison; it does not consume multiple instances of the "prefix". Consider the difference between `s.skipOver(' ')` and `s.skipOver!(c => c == ' ')` - intuitively one may think that these should behave the same, but they don't!
`findSkip` intuitively implies that it loops.

Provide pred-only overload to std.algorithm.searching.findSkip

---

posix.mak

- use MODEL=64/32 to decide on default
- allow overriding default with explicit PIC=0/1 make args

fix Issue 17996 - don't build libphobos2.a with PIC for i386

---

std/algorithm/comparison.d

[Static if] Replace overload constraints with static if (comparison.d)

---

std/concurrency.d

* Make the example a DDoc-ed unittest
* Show receiving scalars, as well as tuples
Alternative to #5871.

Improve std.concurrency.receiveOnly example

---

std/concurrency.d

Split-up of https://github.com/dlang/phobos/pull/5603 to see which test is failing for 32-bit on the auto-tester.

Issue 17127 - bad example code for std.concurrency.Generator

---

changelog/std-algorithm-iteration-mean.dd
std/algorithm/iteration.d

Now that https://github.com/D-Programming-Language/phobos/pull/2991 has been closed, I am reintroducing this function. I believe std.numeric to be a better fit than std.algorithm.iteration, so I moved it.
See https://github.com/D-Programming-Language/phobos/pull/3679 for previous discussion
Also fixes issue 14034

Add mean to std.numeric

---

win32.mak

The current object file has 31929 symbols, pushing some PRs over the OMF limit of 32767, for example https://github.com/dlang/druntime/pull/1603

win32: split unittest6.obj, it's becoming too large for OMF

---

std/typecons.d

The unittest converts a double to a string, which depends on the IEEE rounding mode.

Modified a unittest to work independent of IEEE rounding mode 

---

posix.mak
std/experimental/allocator/building_blocks/ascending_page_allocator.d
win32.mak
win64.mak

This is my work so far on a new allocator which is useful for large objects.
The allocator maps on construction a range of virtual adresses, without allocating any physical memory.
All allocations are rounded to a multiple of the page size and take place at increasing virtual adresses. Each allocation is mapped onto a number of virtual pages, for which we change the protection to read/write access. Physical memory is only allocated on demand, when we access the buffer.
On deallocation, we set the protection to none and use various syscalls to tell the OS to reclaim its memory.
The main advantage of this allocator is that it is safe, because we do not reuse memory and fast for large objects.
After some more tweaks I will also come back with a benchmark.
Future work: 
- integrate it with …

AscendingPageAllocator

---

win32.mak
win64.mak

So I'm trying to move ahead with the ddmd -> dmd transition (https://github.com/dlang/dmd/pull/7135) and due to https://github.com/braddr/at-client/pull/4 we are stuck at the moment.
Hence, this PR tries to set the `DMD` binary path by default to one in the `generated` directory. As I have no Windows machine, I'm doing this more or less blindly, but it looks trivial enough.
See also: https://github.com/dlang/druntime/pull/1978

Fix DMD path to ../generated

---

std/digest/sha.d

This PR refactors some unittest code in `std.digest.sha` to support https://github.com/dlang/dmd/pull/7110.
https://github.com/dlang/dmd/pull/7110 has languished for so long in the PR queue that it has reach the maximum 1000 status updates that Github allows for any given commit.  Therefore, you can't rely on the test status reported on the front page of the PR.  But you can still see the auto-tester results by following the "details" link.
See also https://github.com/dlang/phobos/pull/5714 which was a similar fix.
ping @schveiguy

Issue 12625 - [scope] [DIP1000] implicit slicing of RValue static array should be illegal

---

std/experimental/allocator/building_blocks/allocator_list.d
std/experimental/allocator/building_blocks/ascending_page_allocator.d

- Added a couple of tests for AllocatorList together with AscendingPageAllocator.
- AscendingPageAllocator returns null/false for allocate/deallocate in case of failure
- AscendingPageAllocator receives as a constructor parameter the size in bytes, instead of the number of pages
- Removed some unused functions from AscendingPageAllocator
- When in ouroboros mode, the allocator which holds all the other allocators does not simply call deallocate, since it may have state. In case it has state, it creates a copy and then calls deallocate from that copy.

Integrate AscendingPageAllocator with AllocatorList

---

std/algorithm/searching.d

From https://github.com/dlang/phobos/pull/5497#issuecomment-310282326
> Argh! `find` does not use the eponymous template pattern, which means it's not partially instantiatable with just a `pred`.
It turns out that many functions in std.algorithm don't, so this is a RFC for evaluating the best way to move forward here. I picked the non-trivial function `skipOver` as an example.

[RFC] Make std.algorithm.searching.skipOver an eponymous template to allow partial instantiation

---

std/range/primitives.d

note that the popBackN doc is shared with popFrontN. This change moves the description of popBackN up, such that it is closer to where the reader will want to find it. Also adds more explicit mention of popFrontN, such that it is clear which one of the two is being described.
offtopic: About the `O(.)` part, I think it should be `O(O(length) + O(slice)` and `O(n * O(popFront))`?

[Trivial] improve documentation of popBackN

---

std/typecons.d

Currently, `Nullable` always constructs a default value for the type stored in it. This breaks the use of Nullable with types that `disable @this()`, for no good reason. If such types are detected, and the type in question does not use elaborate assignment (which would allow it to read uninitialized values via = void), then switch to `T _value = void;`. Otherwise, error.

Handle structs with @disable this in Nullable

---

std/range/package.d

also extracted the voldemort type to avoid enormous symbol names for chooseAmong.
The core idea:
* Use a `union` to allow `ctfe`
* Slightly abuse `@trusted` by relying on the constructor to be the only place that modifies `r1Chosen`, therefore allowing `@trusted` access to the correct member of the `union` from that point onwards.
Fixes https://issues.dlang.org/show_bug.cgi?id=14660

Make std.range.choose{Among}? @safe & ctfe-able

---

posix.mak

As neither @MartinNowak nor I can reproduce the spurious DScanner failures locally, getting a stack trace on a SEFAULT is probably the best thing we can do.
CC @CyberShadow @ZombineDev @JackStouffer

Run DScanner with gdb to catch the stack on a SEGFAULT

---

std/datetime/package.d

Ddoc's annoying auto-escaping strikes again!
Before:
https://dlang.org/phobos/std_datetime.html#.StopWatch
After:

[DDoc] Avoid auto-escaping of StopWatch in std.datetime

---

changelog/std-range-package-Transposed-deprecate-save.dd

The current changelog can be previewed at https://dlang.org/changelog/pending.html
@ reviewers DAutotest builds the pending changelog too, s.t. changes to it can be conveniently previewed.
In this case, just dropping the Bugzilla link as plain text looks a bit weird.
Before:
After:

Improve wording in the Transposed changelog entry

---

changelog/std-array-bypair.dd
std/array.d

Not sure why it wasn't done this way originally

Use named tuple for std.array.byPair

---

std/format.d

In the vein of https://github.com/dlang/phobos/pull/5191 and https://github.com/dlang/phobos/pull/4208, this hides all of the individual overloads of `formatValue` and brings the documentation and examples into one place.
This is especially useful in the ddox version of the docs, as every overload will no longer be shown on a different page.

Unify overloads and documentation for formatValue

---

circleci.sh
posix.mak

To investigate the repeated, spurious failures on CircleCi.
This should allow us to get a better stack trace.
It also tweaks the gdb command.

Run CircleCi in BUILD=debug

---

std/algorithm/sorting.d

This fixes a warning one gets when compiling with warnings enabled:
"phobos/std/algorithm/sorting.d(3122): Warning: calling testcase.foo.__lambda1 without side effects discards return value of type bool, prepend a cast(void) if intentional"
Testcase that fails compilation with `-w`:
```
import std.algorithm.sorting;
auto foo() {
int[] v = [ 25, 7, 9, 2, 0, 5, 21 ];
return topN!((a, b) => a > b)(v, 100);
}
```
Phobos unittests are compiled with `-w` right? In that case, the expanded testcase takes care of testing this fix.

Fix intentional discarding of return value in topN

---

std/net/curl.d

A first step for https://github.com/dlang/phobos/pull/5916 - there's still much work to do.

Make imports in std.net.curl local & lazy

---

std/range/package.d

The problem is that  `Take` explicitly avoid nesting itself, which usually is really smart, because `take` takes care of removing nested `take` calls:
https://github.com/dlang/phobos/blob/2f539a4c34fbe3c26b2bb951040aac19ee1a51a7/std/range/package.d#L1994-L1998
https://github.com/dlang/phobos/blob/2f539a4c34fbe3c26b2bb951040aac19ee1a51a7/std/range/package.d#L1973-L1981
The fix is really easy in this case: use the logic which is already part of `take` :)

Fix Issue 18092 - takeExactly cannot deduce function from generic forward range

---

std/regex/internal/ir.d

After:
▶ time dmd test_case.d
dmd test_case.d  0.24s user 0.03s system 98% cpu 0.269 total
▶ gco master
Switched to branch 'master'
Before:
▶ time dmd test_case.d
dmd test_case.d  1.10s user 0.12s system 99% cpu 1.228 total

Faster to import std.regex, by lazy eval of wordMatcher

---

std/typecons.d

Investigation following discussion in https://github.com/dlang/phobos/pull/5916

Dramatically faster to compile Tuple

---

std/internal/math/gammafunction.d

Setting MAXGAMMA to the same as for ieeeExtended reals means the range of the gamma function will be limited to the same range as ieeeExtended. However, until someone reviews the algorithm to work fine for ieeeQuadruple ranges, this workaround seems fine. We just lose some 128bit real features, but we're still as good as x86.
This is a revival of https://github.com/dlang/phobos/pull/4047

Porting: gammafunction: Add constants for ieeeQuadruple reals

---

posix.mak
std/datetime/systime.d
std/datetime/timezone.d
std/experimental/allocator/mallocator.d
std/file.d
std/math.d
std/net/curl.d
std/parallelism.d
std/path.d
std/socket.d
std/stdio.d
std/system.d

Related: 
- [DMD Pull Request](https://github.com/dlang/dmd/pull/7463)
- [DRuntime Pull Request](https://github.com/dlang/druntime/pull/1999)
Bootstrapped via 'dmd-cxx' branch: [See](https://github.com/dkgroot/dragonflybsd_dmd_port)
Notes:
- Exclude assertion for dragonfly in std/experimental/allocator/mallocator.d (Needs further investigation, not sure why aligned_realloc is causing trouble).

Add DragonFlyBSD support for phobos

---

std/internal/cstring.d

Fixes memory corruption introduced when (ironically) trying to support dip25: https://github.com/dlang/phobos/pull/4746
Instead of the original mechanism (which was to slice the buffer with an enum), I just added padding when in unittest mode to make sure the size is the same. Very hard to unittest this, since unittests actually change the layout in the original! I'm open to suggestions.
ping @WalterBright

Fix issue 18084 - tempCString type should not change size when used in unittests.

---

posix.mak
std/concurrency.d
std/experimental/allocator/building_blocks/ascending_page_allocator.d
std/experimental/allocator/building_blocks/bitmapped_block.d
std/experimental/allocator/building_blocks/fallback_allocator.d
std/experimental/allocator/building_blocks/free_list.d
std/experimental/allocator/building_blocks/free_tree.d
std/experimental/allocator/building_blocks/kernighan_ritchie.d
std/experimental/allocator/building_blocks/scoped_allocator.d
std/experimental/allocator/mallocator.d
std/experimental/checkedint.d
std/internal/cstring.d
std/net/curl.d
std/variant.d
win32.mak
win64.mak

There's still quite a bit of stuff in Phobos, that shouldn't be parsed & executed when Phobos is imported by a user who runs his tests.
For the motivation of excluding `unittest` in templates, please see https://wiki.dlang.org/DIP82
(I don't have any preferences on the name of this `version`.)

Add a StdUnittest version

---

std/typecons.d

Following https://github.com/dlang/phobos/pull/5948#discussion_r158286141
> I think we should make it a guideline that version(unittest) top-level imports should be used with caution.
In fact we have been removing unused debug statements in the past:
- https://github.com/dlang/phobos/pull/5180
- https://github.com/dlang/phobos/pull/5602
- https://github.com/dlang/phobos/pull/5583
- https://github.com/dlang/phobos/pull/5568
- https://github.com/dlang/phobos/pull/5437

Remove global debug import in std.typecons

---

std/typecons.d

This already works nicely, so imho just adding a public example should do the trick.

Fix Issue 5489 - std.typecons tuples dynamically iterable

---

std/json.d

Otherwise generated documentation contains hml source pieces like:
"json.html#.JSONException">std.json.JSONException if the depth exceeds the max depth."
see: https://dlang.org/phobos/std_json.html#.parseJSON.2

Fix ddoc in std.json

---

std/experimental/allocator/mallocator.d
std/file.d
std/math.d
std/system.d

x86/x64 has no problem with unaligned reads, but the llvm optimizer gets confused by the cast in the `foreach` and assumes the `Element` is 32-bit aligned, generating ARM instructions that require word alignment and causing problems with the last unaligned test.
As for `posix_memalign`, turns out its declared in druntime but wasn't for `OSX`, so added it in dlang/druntime#1819 and used the import instead.  That druntime PR will need to be merged first.

ARM and Android fixes: version out some HardFloat tests, use TMPDIR logic and declaration from druntime, and correct comment

---

.codecov.yml

Propagating the config from https://github.com/dlang/dmd/pull/7470.

Update CodeCov configuration to be always green/successful

---

std/datetime/date.d
std/datetime/systime.d
std/datetime/timezone.d

This has been an iterative process of pushing imports from the top level into the places where imports are being used. That helped not only clarifying dependencies, but also accelerates import time by about 3x. Further improvements are possible.

Dramatically faster to import std.datetime (and anything under it)

---

posix.mak
std/datetime/timezone.d

As mentioned in https://issues.dlang.org/show_bug.cgi?id=15391#c3 the hardcoded path to the tzdata directory does not work on NixOS.
To fix this I implemented a solution to provide the absolute path to tzdata via an import file. The path to the import file can be specified as parameter to make.

Add possibility to specify custom path to tzdata dir

---

std/regex/package.d

- fix copying of structs with RegexMatch fields by making
const interface reference rebindable

fix Issue 18135 - can't join RegexMatch anymore

---

std/conv.d

Fix for issue [18116](https://issues.dlang.org/show_bug.cgi?id=18116). Mentioning @schveiguy for review, due to discussion [here](https://github.com/dlang/phobos/pull/5946)

Fixes Issue 18116 - to!wchar([string, dstring]), and to!char([wstring, dstring]) don't compile

---

std/math.d

I target stable since you don't allow deprecation in the standard library anymore

prevent deprecation message caused by std.math.abs() on short and byte.

---

.circleci/run.sh

We don't download the DUB binary anymore if it's part of the release.
See https://github.com/dlang/installer/pull/214
Hence, `~/dlang/dub/dub` doesn't exist anymore.

Fix CircleCi DUB config

---

.circleci/run.sh

A specific version of the tools repo is cloned during the CircleCi build.
I'm not really happy about this procedure because this means that for a bug fix in libdparse,
we need to bump libdparse at tools first and then bump it here again.
See also: https://github.com/dlang/tools/pull/282

Bump tools repository

---

std/stdio.d

Note: these symbols were documented until 2013/08 in https://github.com/dlang/phobos/pull/1448 (rationale back then: https://github.com/dlang/phobos/pull/1408#discussion_r5178781).
Please see the issue for the motivation.

Fix Issue 18153 - deprecate public symbols ByLine, ByRecord, ByChunk

---

std/regex/package.d

Easiest thing to do was explicitly type the result. It's probably less effort than documenting what it returns in ddoc, and is clearer to the user.
In all other cases in this file, the auto returns have explicit docs as to the return type. This really was the only anomaly.

Fix issue 18124 -- RegexMatch.front isn't clear as to what it returns

---

std/algorithm/comparison.d
std/algorithm/iteration.d
std/algorithm/mutation.d
std/algorithm/package.d
std/algorithm/searching.d
std/algorithm/setops.d
std/algorithm/sorting.d

Done with: https://github.com/wilzbach/dscanner-fix/blob/master/d_code_markdown.d
Revival of https://github.com/dlang/phobos/pull/5801 for `std.algorithm`

Markdownify std.algorithm

---

std/file.d

Taken over from https://github.com/dlang/phobos/pull/4712

file.d: add overflow checks

---

std/bitmanip.d
std/complex.d
std/container/rbtree.d
std/typecons.d
std/uni.d

See https://github.com/dlang/phobos/pull/5991#issuecomment-355122818
While in this instance, the code compiled just fine, the problem is that a `const ref` parameter in `formatObject` ended up being copied in said function if `FormatSpec` wasn't marked as `ref`. This poses a problem because `FormatSpec` is quite a large struct, not to mention the fact that we've already gone through the trouble of making a pointer to one, so making a copy is just extra work.

Changed all instances of FormatSpec in toString to const ref

---

.circleci/run.sh
.codecov.yml

See also:
- https://github.com/dlang/dmd/pull/7574 (Use GitHub's merge head)
- https://github.com/dlang/dmd/pull/7596 (Don't wait for other CIs, attempt IV)
- https://github.com/dlang/dmd/pull/7542 (Don't wait for other CIs, attempt III)
- https://github.com/dlang/dmd/pull/7540 (Use domains to ignore CI providers)
- https://github.com/dlang/dmd/pull/7532 (Fix 'No parent commit was found' by allowing coverage offsets)

Propagate CodeCov + CircleCi updates from DMD

---

std/conv.d

I've added some code to support ieeeQuadruple reals in `parse!real`. I've also documented some of the parser. As I do not fully understand the internals of the parser, I didn't want to extend the parser to allow for higher precision. We'd have to use cent (or, as there is no cent type, two longs for a manual 128 bit in implementation) which probably makes the code slower. So I leave that to somebody who fully understands the parser code. (It would also make more sense to limit precision in the parser for double precision reals. Currently we parse at higher precision and remove precision when converting to the final value. This just adds unnecessary overhead).
I've added code to stuff the parse values into an ieeeQuadruple real though. This just means parse!real on ieeeQuadruple targets is …

std.conv: ieeeQuadruple (AArch64) support for parse!real

---

std/format.d

Discovered while working on https://github.com/dlang/phobos/pull/6014

Use a switch instead of a global dictionary for primitiveTypeInfo

---

std/uni.d

I'm leaning towards removing all `attribute:` usage outside of structs from Phobos...

Remove unsafe, indiscriminate '@trusted:' from std.uni

---

std/uni.d

Mainly to ensure that the fix in https://github.com/dlang/phobos/pull/6008 won't break in the future.

Unittest to ensure CTFE-ability for std.uni.graphemeStride.

---

std/format.d

`primitiveTypeInfo` is a relict from the old doFormat days.
It's not used anywhere anymore.
See also: https://github.com/dlang/phobos/pull/4978
Separated from: https://github.com/dlang/phobos/pull/6014

Remove unused std.format.primitiveTypeInfo and deprecate unused std.format.Mangle

---

std/random.d

Having this code in Phobos leads others to mistakenly copy it since Phobos is generally a model of good D programming practices. Calling unpredictableSeed just once would be faster and would give a better result.
Explanation from https://github.com/dlang/phobos/pull/5788#discussion_r146110307:
>This method of seeding calls `unpredictableSeed` 624 times to initialize the MersenneTwisterEngine's internal array. Currently this just means multiplying a number 624 times modulo 2^^31-1 and XOR-ing the result against the clock each time. This is pointless but fairly harmless, although it means that initially each number will probably have the same high bit. It would be faster and give a better result to just seed MersenneTwisterEngine with a single number. Also, if a proposal like #5230 to make …

Fix Issue 18217: Don't repeatedly call unpredictableSeed to initialize rndGen

---

std/algorithm/searching.d

Removes ambiguity between min element value and index of min element value.

[DOC] Minor update to minElement example

---

changelog/compile-time-format-optimized.dd
std/format.d

Added function to std.format to make an educated guess at the length of the resulting string when it's given at compile time, and use that data to reserve capacity in the appender before anything is written to it.
Performance wise, I only saw differences outside of random-ness in longer format strings.
```
old 1			1 sec, 223 ms, 469 μs, and 8 hnsecs
old 2			2 secs, 427 ms, 447 μs, and 1 hnsec
old 3			2 secs, 448 ms, 949 μs, and 8 hnsecs
old 4			2 secs, 655 ms, 333 μs, and 4 hnsecs
new 1			1 sec, 191 ms, 30 μs, and 2 hnsecs
new 2			2 secs, 432 ms, 636 μs, and 8 hnsecs
new 3			2 secs, 489 ms, 238 μs, and 6 hnsecs
new 4			2 secs, 155 ms, 551 μs, and 3 hnsecs
```
```d
import std.format;
import …
```

Optimized format with compile time format strings

---

std/range/primitives.d

So this behavior is not what I excepted when I called `put`, and took looking at `doPut`'s source to understand why my arrays were coming out empty. This is briefly mentioned in the `put` docs but this example makes `put`'s actions clear.

Make the Behavior of put with Slices Clearer

---

std/traits.d

See also: http://forum.dlang.org/post/bpnfmtqafvasbehzhnom@forum.dlang.org
I also bumped into this a while ago.
While the `is` operator should be preferred anyways, there's no reason we can't
be nice people and return `void` if a basic type was given.

Fix Issue 18214 - TemplateOf should return void for non-templated symbols

---

changelog/std-parallelism-fold.dd
std/algorithm/iteration.d
std/parallelism.d

Implement TaskPool.fold similar to std.algorithm.fold: Seeds come after the range and need not be a tuple.
Plus a couple of link corrections in std.algorithm documentation.

Fix Issue 18096 - Add fold() to std.parallelism

---

std/math.d

Not having any sig constraints causes needless conflicts with user-defined numerical types, e.g.:
````
// myNumber.d
module myNumber;
struct MyNumber { ... }
int signbit(T : MyNumber)(T num) { ... }
// usercode.d
import myNumber;
import std.math;
MyNumber num;
auto x = signbit(num); // tries to call std.math.signbit, and fails
````
To anticipate the objection "user code should not use the name `signbit`": sometimes, we *want* to deliberately reuse established names for certain operations, so that we can drop in a user-defined type as a replacement for built-in floats without having to modify a lot of user code. As long as it behaves similarly enough to a built-in float, it should be allowed with a minimum of roadblocks.

Issue 18244: std.math generic functions need to have sig constraints

---

std/functional.d

Per [discussion](https://forum.dlang.org/post/gucawibkptuwxzgqqpoa@forum.dlang.org), augment std.functional.forward to:
- support single-argument use case
- copy immovables (i.e. const/immutable)

forward: single argument, copy const

---

changelog/std-range-slide.dd
std/range/package.d

This is a revival of `std.range.slide` ... finally!
History
----------
`std.range.slide` was introduced in https://github.com/dlang/phobos/pull/4027 and I delayed its release in https://github.com/dlang/phobos/pull/5614 as at the time of the merge I didn't have to work on it.
Why was it needed to rework this function before its release?
----------------------------------------------------------------------------------
tl;dr: the implementation of `withFewerElements` was broken for `Yes.withFewerElements`.
(see https://github.com/dlang/phobos/pull/5614 for details).
Changes
------------
It's hard make an exact summary of the changes,
- added proper handling for `Yes.withPartial`
- renamed `withFewerElements` to `withPartial` (shorted & clearer name)
- made all tests function use …

Revive std.range.slide from the dead

---

std/experimental/allocator/package.d

Current function in std.experimental.allocator.package:
```d
private void fillWithMemcpy(T)(void[] array, auto ref T filler) nothrow
{
import core.stdc.string : memcpy;
import std.algorithm.comparison : min;
if (!array.length) return;
memcpy(array.ptr, &filler, T.sizeof);
// Fill the array from the initialized portion of itself exponentially.
for (size_t offset = T.sizeof; offset < array.length; )
{
size_t extent = min(offset, array.length - offset);
memcpy(array.ptr + offset, array.ptr, extent);
offset += extent;
}
}
```
When T.sizeof==1 we could use memset instead.

Fix Issue 18239: fillWithMemcpy use memset when T.sizeof == 1

---

changelog/nullable-class.dd
std/typecons.d

This is a reboot of #6038 with a simpler fix that doesn't require extensive, backward-incompatible changes to `Nullable`.
It does *not* take care of the problem of `Nullable!Class` introducing a second, inequivalent null state to a class reference.

Fix issue 17440: do not call .destroy on class instances in Nullable.nullify

---

posix.mak
std/complex.d
std/format.d
std/math.d
std/string.d
std/traits.d
std/typecons.d
std/variant.d
unittest.d

This is first PR which works in the direction of finally going through with the
complex and imaginary type deprecation.
See also: https://github.com/dlang/dmd/pull/7640

Start to move away from complex and imaginary types

---

std/container/rbtree.d
std/experimental/typecons.d
std/regex/internal/tests.d

This currently blocks : https://github.com/dlang/dmd/pull/7760

Fix erroneous imports
