- std/datetime/date.d
First attempt at using GIT for updating the documentation. Added a simple example to the date documentation.
> A simple example added to Date - toString

- std/datetime/date.d
Not sure how https://github.com/dlang/phobos/pull/5448 managed to sneak through CircleCi, but first order of business is to keep the CI green. Investigation will follow
CC @CyberShadow @andralex
> Fix CircleCI - unittests need to be annotated

- index.d
- std/digest/digest.d
- std/digest/hmac.d
- std/file.d
- std/range/package.d
Needs https://github.com/dlang/dlang.org/pull/1802.
> Fix broken links

- std/file.d
Apologies, I missed an overload in #5569.
> Update a missed dirEntries overload (fixup for #5569)

- std/math.d
Mostly showing docs that were accidentally invisible before. See commit messages for details.
> improve docs for std.math.FloatingPointControl

- std/container/rbtree.d
- std/csv.d
- std/exception.d
- std/math.d
Companion to https://github.com/dlang/dmd/pull/6989
> Convert section labels to title case

- std/algorithm/iteration.d
- std/conv.d
- std/datetime/systime.d
- std/datetime/timezone.d
I'll leave the stdc mess to another PR.
> Move some deprecations along

- std/meta.d
See also: https://github.com/dlang/phobos/pull/5485#issuecomment-316040762
Btw I realized that we also need to exclude the file manually from the menu on dlang.org -> https://github.com/dlang/dlang.org/pull/1835
> Mention TypeTuple at std.meta.AliasSeq

- std/functional.d
Split-off from https://github.com/dlang/phobos/pull/5639
> Fix bookmark table for std.functional

- std/typecons.d
https://github.com/dlang/phobos/pull/5642 take 2
> Add bookmark table to std.typecons

- std/bigint.d
https://issues.dlang.org/show_bug.cgi?id=16997
This will enable this code to work with or without 16997 being fixed.
Blocking https://github.com/dlang/dmd/pull/7013
> bigint: fix dependency on broken Issue 16997

- std/utf.d
> std.utf - inure against integral promotion changes

- std/experimental/allocator/building_blocks/free_list.d
This pull request adds the minimize() function to std.experimental.allocator.building_blocks.free_list.SharedFreeList.  This function is a counterpart to the minimize() function in FreeList.  Unless the caller intends to keep a SharedFreeList instance allocated for the entire life of their program after it is constructed, the minimize() function is necessary to be able to return the SharedFreeList's memory resources to its ParentAllocator (ex: if ParentAllocator is the Mallocator, it allows the SharedFreeList to call free() on malloc'ed memory).  The deallocateAll() function can also free a SharedFreeList's memory resources, but deallocateAll() will prefer to call ParentAllocator.deallocateAll(), which could be very undesirable to the caller ("but what if I don't want to free …
> Add minimize() function to SharedFreeList.

- std/traits.d
Adds a trait to see if a type is comparable.
> Fix Issue 6384 - add std.traits.isComparable

- std/concurrency.d
- std/experimental/logger/core.d
Reboot of #4551 to work around the SHA mismatch problem.
> prepare for fix of druntime issue 16230

- std/bigint.d
blocking https://github.com/dlang/dmd/pull/7013
> std.bigint: inure against unary - + ~ promotion rules

- std/range/package.d
Blocking https://github.com/dlang/dmd/pull/7013
> inure std.range.package against unary - + ~ promotion rules

- std/zip.d
This PR fixes the bug report by moving the code that does compression from the `build` method to the `addMember` method. As a result, `addMethod` is not `@safe` anymore due to the use of `compress` and `crc32`.
> Fix Issue 2137 - Data not compressed on fly when adding to zip archive

- std/math.d
I.e., don't use the inline assembly version for CTFE, but the existing generic D implementation.
This is just one possible way of handling this. `exp2()` could also be detected as CTFE builtin by the compiler.
> Make std.math.exp2() CTFE-able for 80-bit target reals

- std/range/primitives.d
**Note:** this PR targets master, rather than stable, because the regression is only in git HEAD, it hasn't gone out in a stable release yet.
> Issue 17661: isInputRange should accept .front that returns reference to range

- std/string.d
A temporary workaround for the issue described in https://github.com/dlang/phobos/pull/5682
I have also filed an issue against DDOX: https://github.com/rejectedsoftware/ddox/issues/168
> Workaround for DDOX bug in the official docs

- std/encoding.d
Added codepage Windows CP1251.
> Added encoding Windows cp1251

- std/format.d
In 2014 there was two previous attempts:
- https://github.com/dlang/phobos/pull/2124: never merged because it required a rebase which was never done, also troubles with the tests.
- https://github.com/dlang/phobos/pull/2220: was closed because the other PR existed already.
Then it was completely forgotten for 3 years for no reason.
> fix issue 10444 - writeln of a SIMD register

- std/process.d
https://github.com/dlang/phobos/pull/5742#issuecomment-331557003
> std.process: Update Config documentation for stderrPassThrough

- std/random.d
As in XorshiftEngine, sanitizing the seed is more useful than throwing
an exception. The original check was broken because it checked the seed
before taking the modulus. Making this change allows unpredictableSeed
to be marked nothrow and @nogc.
> Fix Issue 17847 - Properly sanitize seeds for Park–Miller engines

- std/uni.d
Which is totally unexpected especially in code like this:
```d
writeln("Йоу!".byCodePoint.length);  // prints 7
```
> Fix issue 13829 - byCodePoint has length

- std/algorithm/searching.d
A followup to https://github.com/dlang/phobos/pull/5752
> Change the findSplit example into a documented unit test

- std/math.d
> std.math: Remove junk comment

- changelog/std-typecons-ternary-opBinary.dd
- std/typecons.d
I believe that logical operations between `Ternary`s and `bool`s should be valid.
@andralex @wilzbach @ZombineDev
> Ternary opBinary should be able to take bool

- std/experimental/allocator/building_blocks/region.d
> Fix issue 17901 - FreeBSD SbrkRegion alignment

- changelog/std-container-dlist-linearRemoveElement.dd
- changelog/std-container-slist-linearRemoveElement.dd
Changelog for 
https://github.com/dlang/phobos/pull/5784
https://github.com/dlang/phobos/pull/5786
> Changelog update for Dlist and Slist linearRemoveElement

- std/experimental/allocator/building_blocks/region.d
Please see discussion at #5806 
@andralex @jmdavis
> Fix FreeBSD SbrkRegion alignment issue

- std/experimental/allocator/building_blocks/segregator.d
It looks like `alignedReallocate` had some residues, probably from a copy-paste.
Fixed the typos and updated the docs.
@andralex @wilzbach
> Fix segregator alignedReallocate and empty

- std/experimental/allocator/package.d
Let me know if this is a suitable solution, thanks!
> fix issue 16542 -  makeArray not usable with const initializer

- changelog/std-range-package-Transposed-deprecate-save.dd
- std/range/package.d
> Followup to #5832

- std/experimental/allocator/building_blocks/affix_allocator.d
- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/bucketizer.d
- std/experimental/allocator/building_blocks/fallback_allocator.d
- std/experimental/allocator/building_blocks/free_list.d
- std/experimental/allocator/building_blocks/free_tree.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/experimental/allocator/building_blocks/quantizer.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/building_blocks/segregator.d
- std/experimental/allocator/building_blocks/stats_collector.d
- std/experimental/allocator/package.d
Reverts dlang/phobos#5831
This is currently breaking vibe-d, which in turn is blocking jenkins. Will postpone this
> Revert "Allocators owns should take const void[]"

- std/experimental/allocator/building_blocks/bucketizer.d
> Fix bucketizer alignedAllocate bug

- std/experimental/allocator/building_blocks/bucketizer.d
@andralex @MetaLang 
> This should go in after #5849 
This can be safely merged, now
> Fix bucketizer alignedReallocate bug

- std/experimental/allocator/building_blocks/affix_allocator.d
- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/building_blocks/bucketizer.d
- std/experimental/allocator/building_blocks/free_list.d
- std/experimental/allocator/building_blocks/free_tree.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/experimental/allocator/building_blocks/null_allocator.d
- std/experimental/allocator/building_blocks/quantizer.d
- std/experimental/allocator/building_blocks/region.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/building_blocks/segregator.d
- std/experimental/allocator/building_blocks/stats_collector.d
> This is currently blocked by #5829 
Edit: This can be safely merged as #5829 is now merged.
> Mark deallocateAll as @nogc

- std/file.d
This fixes a regression that was introduced in https://github.com/dlang/phobos/pull/5758. Fortunately, looking at the history in git, I'm pretty sure that it has not yet made it into a release.
> Fix issue 17962: dirEntries is truncating Unicode file names.

- std/experimental/allocator/building_blocks/free_list.d
I also slightly updated the documentation.
Thanks,
Alex
> Fix Issue 15140 - std.experimental.allocator.building_blocks.free_list.FreeList leaks memory

- std/algorithm/iteration.d
> remove unintended highlighting from cache's docs

- std/experimental/allocator/common.d
Also added testcase for alignedReallocate
Thanks,
Alex
> alignedReallocate also checks for correct alignment if sizes are equal

- std/internal/cstring.d
- avoids code duplication and makes better use of the
template cache for the limited number of char types
- also allows to store TempCStringBuffer!char somewhere
> factor out code that does not depend on input range

- std/experimental/allocator/building_blocks/bitmapped_block.d
See also https://github.com/dlang/dmd/pull/7332
> Avoid subtraction of pointers to different types

- changelog/std-algorithm-searching-findSkip.dd
> Add the new findSkip overload to the change log

- std/digest/package.d
> Add secureEqual to the digest booktable

- std/concurrency.d
Split-up of https://github.com/dlang/phobos/pull/5603 to see which test is failing for 32-bit on the auto-tester.
> Issue 17127 - bad example code for std.concurrency.Generator

- std/experimental/allocator/building_blocks/region.d
`SBrkRegion.expand` must take into account the rounding due to alignment.
> Fix SBrkRegion expand bug

- std/internal/math/biguintcore.d
cc @don-clugston-sociomantic @donc @ibuclaw
> Eliminate shared this from std/internal/math/biguintcore.d

- win32.mak
- win64.mak
Cherry-picked https://github.com/dlang/phobos/pull/5892 for the `stable` branch.
From https://github.com/braddr/at-client/pull/4#issuecomment-347937086
> Sorry, not staging, but stable. All tested branches need to have the changes. In fact, since I merged the auto-tester changes in before remembering to check stable, it's currently failing to build. That needs to be fixed asap or I'll have to revert the auto-tester or put in a temporary work around. It'd be best to just get the changes merged.
> Fix DMD path to ../generated

- std/experimental/logger/filelogger.d
fix Issue 18021
https://issues.dlang.org/show_bug.cgi?id=18021
> Issue 18021 - FileLogger Member not accessible to subclasses

- std/net/isemail.d
Leave a trail to make it clear we have permission.
> std.net.isemail: document relicense

- std/range/interfaces.d
See https://github.com/dlang/phobos/pull/5901
CC @Dashster
> Update interfaces.d [rebased to stable]

- std/range/package.d
The added lines explain it all.
> Limitation note to lockstep and zip.

- std/range/package.d
> Added more attributes to unittests so they can catch more regressions.

- std/experimental/allocator/building_blocks/bitmapped_block.d
A lot of functions such as expand, smallAlloc, hugeAlloc changed state before code that could fail.
Also changed BitVector opSliceAssign to correctly set/reset bits for huge allocations.
Also added tests
Thanks,
Alex
> Fixed various bugs in Bitmapped Block

- std/experimental/allocator/building_blocks/ascending_page_allocator.d
I also added and refactored some tests for the new functionality.
> Added alignedAllocate for AscendingPageAllocator

- std/experimental/allocator/building_blocks/bitmapped_block.d
allocateFresh returns unused memory from a BitmappedBlocks.
This is just a puzzle piece, together with AscendingPageAllocator, to create a fast and safe allocator which does not reuse memory.
> Added allocateFresh for BitmappedBlock

- std/format.d
fix issue 17459
fix issue 18047
This is in one commit as the two problem are located at the place
> Fix for two problems with format separators

- std/path.d
Running Phobos unittests in the NixOS build environment while building DMD 2.067.1 or newer, doesn't work because the user root has home directory /build instead of /root.
For now I patch it in the Nix build script but it would be better to not depend on the existence of the /root directory.
See also https://github.com/NixOS/nixpkgs/issues/29443
Here is the error of the build machine with DMD 2.067.1:
****** FAIL release64 std.path
core.exception.AssertError@std/path.d(3083): /build
> Don't expect root home dir in unittest

- std/algorithm/searching.d
> [Trivial] Small std.algorithm fixes: remove stdio + typo

- std/random.d
Supersedes https://github.com/dlang/phobos/pull/4924
> Add Array of Random Numbers Example

- std/format.d
http://forum.dlang.org/post/pmvhclhwxebldzffdwyg@forum.dlang.org
> Make std.format.formattedRead usable with rvalues

- std/algorithm/iteration.d
- std/algorithm/mutation.d
- std/array.d
- std/ascii.d
- std/base64.d
- std/exception.d
- std/format.d
- std/math.d
> @safeify more unittests II

- std/bigint.d
Also add "`" to more things in the docs
> Markdown-ify BigInt's docs

- std/bigint.d
See https://github.com/dlang/phobos/pull/5991#issuecomment-355122818 for more information
> Fix BigInt.toString overload

- .circleci/run.sh
Applying https://github.com/dlang/phobos/pull/5978 to `stable`.
> Fix CircleCi DUB config

- std/array.d
Maybe I'm just too tired, but how is it possible that there wasn't a test for replacing on an array of arrays?
> Fix Issue 18215 - std.array.replace throws a range violation if the from range is longer than the array

- std/format.d
I didn't see it in bugzilla before cooking the fix but apparently it's controversial for some people.
> fix issue 7054 - format() aligns using code units instead of graphemes

- std/parallelism.d
Blocked by https://github.com/dlang/druntime/pull/1996
> std.parallelism: replace explicit code with Throwable.chainTogether()

- std/algorithm/setops.d
> Fix Issue 18230 - multiwayUnion sets wrong pred lambdas

- std/range/primitives.d
Illustrates the behavior better and show why the function itself can be useful.
> Added more examples to std.range.put

- .codecov.yml
See also: https://github.com/dlang/dmd/pull/7711
> Hide codecov/project and codecov/changes

- posix.mak
Also removes the redundant specification of the Ddoc files to dlang.org - this repository
was already required to be exist before.
> Remove old, unused HTML bits from the Makefile

- std/datetime/date.d
I think I can dispense with the benchmarks at this point.
> Optimized std.datetime.date.TimeOfDay.fromISOExtString

- std/net/curl.d
https://issues.dlang.org/show_bug.cgi?id=18316
> Fix Issue 18316 - std.net.curl.SMTP.mailTo fails to compile

- std/exception.d
I used the opportunity to improve the docs and unify all three overloads under one documentation block.
> Fix Issue 18319 - std.exception: enforce example does not compile

- std/conv.d
As requested in [this thread](https://github.com/dlang/phobos/pull/5959) by @JackStouffer and @schveiguy.
> Document std.conv.to for string-to-char conversions

- std/experimental/allocator/building_blocks/ascending_page_allocator.d
Added SharedAscendingPageAllocator, which is the threadsafe version of AscendingPageAllocator.
> Added SharedAscendingPageAllocator

- changelog/std-traits-issomestring.dd
This is the changelog entry for https://github.com/dlang/phobos/pull/5291.
> Add changelog entry for changes to isSomeString.

- std/algorithm/searching.d
Way more complicated than it needed to be.
Also replaced string lambdas with real ones in the vein of https://github.com/dlang/phobos/pull/3800
> Simplify the Example for Find

- std/process.d
Refactor out the need of the warning by placing the part of the test containing "return" statements into its own function.
> std.process: Get rid of goofy warning in unit test

- std/datetime/systime.d
So this rendition is a bit messier than normal because of the issue of using `find`. `indexOf` doesn't have a multiple `needle`s, so I tried to refactor to use `countUntil`, but it ended up being worse readability wise because you need to know which of the elements was found. 
The `static if`s are there because the return type of `byCodeUnit` is different if the source is an array of `dchar`s. In hindsight, this doesn't seem like this was the best idea but w/e.
No performance numbers for LDC because it doesn't have the change which gives access to `source` yet
```
2013-Feb-07 04:39:37.0000503
old		2 secs, 316 ms, 927 μs, and 3 hnsecs
new		1 sec, 350 ms, 355 μs, and 4 hnsecs
```
<details>
```d
import …
```
> Optimized std.datetime.systime.SysTime.fromISOString

- std/datetime/date.d
- std/datetime/interval.d
- std/datetime/stopwatch.d
- std/datetime/systime.d
- std/datetime/timezone.d
A first step to get things started.
CC @jmdavis
> Issue 18345 - add bookmark tables to std.datetime

- std/experimental/allocator/building_blocks/ascending_page_allocator.d
- moved both the StdDdoc and implementation under the struct definition
- added ddoc examples
- updated the paper details.
> Added examples for AscendingPageAllocator

- std/experimental/allocator/building_blocks/region.d
- When growing downwards, the region did not round the allocation size to the alignment inside alignedAllocate. Added testcase.
- On No.growDownwards, "_current" could accidentally exceed "_end" when rounding up to "a".
- Fixed overflow cases for Region
- Added goodAllocSize for all regions
> Region grownDownwards alignedAllocation takes into account alignment

- std/experimental/allocator/building_blocks/package.d
Updated the docs on the building_block page with a description for AscendingPageAllocator
> Update AscendingPageAllocator description

- std/datetime/systime.d
Much less to do now that `find` no longer auto decodes thanks to https://github.com/dlang/phobos/pull/6132.
```
$ dmd/generated/osx/release/64/dmd -O -inline -release test.d && ./test
2010-Jul-04 07:06:12+08:00
old		8 secs, 791 ms, and 976 μs
new		4 secs, 685 ms, 384 μs, and 9 hnsecs
```
<details>
```d
import std.exception;
import std.typecons;
import std.datetime.systime;
import core.time;
import std.random;
enum testCount = 5_000_000;
__gshared a = "2010-Jul-04 07:06:12+08:00";
SysTime fromSimpleString1(S)(in S simpleString, immutable TimeZone tz = null) @safe
if (isSomeString!(S))
{
import …
```
> Optimized std.datetime.systime.SysTime.fromSimpleString

- std/datetime/timezone.d
Rather straight-forward. Will be used in the SysTime versions.
> Work On Issue 10828 - Add Writer Versions of TimeZone toStrings

- std/datetime/systime.d
This is where the writer version of `toString` really starts to shine.
> Work On Issue 10828 - Added writer version of SysTime.toISOString

- std/datetime/systime.d
Finishes out all of the remaining functions.
> Fix Issue 10828 - datetime toString functions should accept sink

- std/format.d
> Added writer version of toString to FormatSpec

- std/algorithm/mutation.d
- std/algorithm/searching.d
- std/numeric.d
I still would be in favor of dropping the links completely, but well one step at a time :/
> Fix Issue 18492 - DLang STL links are broken

- std/utf.d
```
old		1 sec, 664 ms, 214 μs, and 8 hnsecs
new		1 sec, 176 ms, 790 μs, and 3 hnsecs
$ dmd -O -release -inline test.d && ./test
old		3 secs, 281 ms, 757 μs, and 1 hnsec
new		2 secs, 757 ms, 328 μs, and 1 hnsec
```
1. Removes extra call to encode
2. Removes bounds checks on the static array and two `ushort` member variables
3. In order to change the layout, this change uses a different type all together, thereby avoiding tons of  hard to follow `static if`s inside the original type
code:
<details>
```d
import std.exception;
import std.typecons;
import std.datetime.systime;
import …
```
> Optimized byDchar

- std/typecons.d
Regression for 2.078.*. Fixed in future 2.079 (dmd-beta).
> Regression test for #18539 added

- std/stdio.d
> Update lockingTextWriter docs

- posix.mak
This would be a prerequisite for https://github.com/dlang/dmd/pull/7953
Ping @wilzbach
> [dmd-cxx] Backport PIC logic from stable into dmd-cxx

- std/traits.d
Blocking https://github.com/dlang/dmd/pull/7986
> AA key needs at least one data field

- std/algorithm/sorting.d
Sorry I didn't expect to find so many errors.
> Fix Ddoc error in the quickoverview of std.algorithm.sorting

- std/algorithm/searching.d
see also: https://dlang.org/phobos/std_range.html#.SortedRange
> std.algorithm fix typo in reference to std.range.SortedRange

- std/experimental/allocator/building_blocks/region.d
Implemented the threadsafe version of the Region allocator, SharedRegion.
Allocations are lock-free, using the cas mechanism from core.atomic.
> Added SharedRegion

- std/internal/math/biguintcore.d
Blocking https://github.com/dlang/dmd/pull/8048
> biguintcore: more immutability casts needed

- std/experimental/all.d
- std/stdio.d
> Fix Issue 18648 - Document the type of std.stdio.stdin and friends

- dip1000.mak
- std/container/slist.d
Reverts dlang/phobos#6295
It wasn't ready to be pulled.
> Revert "std.container.slist: Fix a @safe cannot call @system issue"

- std/experimental/allocator/building_blocks/ascending_page_allocator.d
The race here was that while 'extendMemoryProtection' was called, some other thread could access memory before the calls to mprotect/VirtualProtect could finish, resulting in segfault.
Fix here was easy, moving 'extendMemoryProtection' under the lock.
> Fixed AscendingPageAllocator race condition

- .dscanner.ini
- std/typecons.d
~~~Postponed the DScanner check until https://github.com/dlang/phobos/pull/6311 is in.~~~
edit: now with DScanner check
> Add public examples to std.typecons + DScanner check

- std/bitmanip.d
There are already many good examples existing in std.bitmanip. They just need to the see light of the D world.
> Make more unittests in std.bitarray public

- std/experimental/allocator/building_blocks/affix_allocator.d
`AffixAllocator` used to only check if `Allocator.instance` is `shared`. If the parent `Allocator` doesn't have an `instance` field, the check will be false, even though the `Allocator` is shared.
> Update how AffixAllocator infers shared from parent

- std/experimental/allocator/building_blocks/free_tree.d
Blocking: https://github.com/dlang/dmd/pull/8101
> [Trivial] Delete test in free_tree

- std/range/package.d
**EDIT:** For posterity I'll mention here that in addition to improving trait inference, being specialized for a single stopping policy also means there is less generation of excess code for untaken branches (the main `Zip` needs switch cases for all stopping policies). Also in some cases we can use a more efficient `empty` and `length`: if we determine at compile time that each range has the same length, we just need to check one range instead of all of them.
**EDIT 2:** Also this version implements `back` correctly for uneven ranges.
> Fix Issue 18638 - The main override of std.range.zip could infer @nogc and nothrow

- std/uni.d
Followup to #6225. Add fast path for ASCII string comparison with fallback to proper decoding in `sicmp` and `icmp`.
Below benchmarks were calculated as in https://github.com/dlang/phobos/pull/6225#issue-171419109. "sicmp_6225" is PR 6225 and "sicmp_new" is PR 6225 plus this PR.
Benchmark ``using ldc2 -O2 -release`` (LDC v1.7.0):
```
strcasecmp 29 ms, 857 μs, and 7 hnsecs
sicmp_6225 ASCII 57 ms, 17 μs, and 8 hnsecs
sicmp_new ASCII 30 ms, 866 μs, and 4 hnsecs
sicmp_6225 Unicode 116 ms, 711 μs, and 3 hnsecs
sicmp_new Unicode 128 ms, 62 μs, and 6 hnsecs
```
Benchmark using ``dmd -O -inline -release`` (DMD v2.078.3):
```
strcasecmp 32 ms, 919 μs, and 5 hnsecs
sicmp_6225 ASCII 84 ms, 394 μs, and 3 hnsecs
sicmp_new ASCII 38 ms, 703 μs, and 9 hnsecs
sicmp_6225 Unicode 282 ms, 52 μs, and 2 hnsecs …
```
> Add ASCII fast path to sicmp & icmp

- std/random.d
> std.random: add a module-level booktable

- std/range/package.d
See https://issues.dlang.org/show_bug.cgi?id=17141
> Add example to chain explaining char corner cases

- std/math.d
Have added `pure` onto the flag getters, and removed `pure` from the flag setters (for now...).
Granted that `std.math.exp` is pure _and still_ raises an FP exception gives us at least an argument for adding pure to these structures also (or removing the `pure`  attribute from this and others functions, breaking everyone's code).
As well, a new private `FloatingPointControl.raiseException` method should be added too.  As this hack can now be defeated by the optimizer, however this wasn't the case in the past.
https://github.com/dlang/phobos/blob/fd9fdeb25d3f497bf68ba5ac29667adb3c912ddb/std/math.d#L1833-L1850
Edit: Although now I'm swayed in the direction that the above should just be removed and unittests updated.
> Mark IeeeFlags and FloatingPointControl as @trusted nothrow @nogc

- std/datetime/timezone.d
`localtime` returns a pointer to a global shared data structure. This is terrible. `localtime` is terrible. `gmtime` is also terrible. Do not call `localtime`. Do not call `gmtime`. Do not interact with `localtime` or `gmtime` in any way, except if the way is "I decided to remove `localtime` and replace it with `localtime_r`".
This PR removes `localtime` and replaces it with `localtime_r`.
> Fix localtime

- .dscanner.ini
- std/random.d
- std/traits.d
+ a few small documentation updates
> Add public examples to std.random + enable DScanner check

- std/algorithm/iteration.d
The same could probably be added to quite a few ranges that use seeds though some already use `assert`.
Maybe there could be a case made to just use `assert` here too?
> Fix Issue 13880 - nothrow @nogc std.algorithm.reduce on fixed-size arrays

- std/experimental/allocator/building_blocks/bitmapped_block.d
This is a subset of the old #5879
> Make bitmapped_block allocate @safe

- std/array.d
Can't enable the dscanner check because of https://github.com/dlang-community/D-Scanner/issues/601
> Added params and returns to std.array functions

- std/math.d
Finishes everything except `rndtonl` which is blocked by issue 18693
> Add public examples to all functions in std.math

- std/file.d
This is currently blocking: https://github.com/dlang/dmd/pull/8167
> [Trivial] Fix double initialization of field errno in std/file.d

- std/experimental/allocator/building_blocks/region.d
Also removed global nogc, because if the parent is the GC, the ctor which receives `size_t` will not be nogc
> Add deallocateAll for SharedRegion

- std/experimental/allocator/building_blocks/allocator_list.d
When an allocation is requested, if two empty nodes are detected, `allocate` and `alignedAllocate` return `null`.
This will not work with allocators which always return fresh memory. Such allocators may not hold alive objects (are empty), but don't have available fresh memory.
I also added a test which this PR fixes.
> Allocator list does not return null if two empty nodes are found

- std/math.d
[Trivial] truncl is defined as pure in core/stdc/math and this was updated a couple of weeks ago to also be true for dragonfly, therefor this different definition can be remove and we can use the default.
> [Trivial] truncl is pure in core/stdc/math -> remove specialization

- std/typecons.d
Current std.typecons.Tuple has a custom `toHash` that is just the sum of the hashes of the tuple's fields. This PR instead combines values using ~~the runtime's default hash function~~ the equivalent of [`boost::hash_combine`](https://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine).
> Fix Issue 18766 - std.typecons.Tuple.toHash could be improved

- std/typecons.d
Fixes some minor issues.
I was asked to split this off from #6499.
Note that a large portion of the changes are white space only due to indentation.
> Typecons minor issues

- std/traits.d
~~The problem was that the template accessed the symbol using `T.stringof` instead of `__traits(identifier, T)`. I use the FQN which doesn't have this issue and decompose it until it can be used to mix an import statement.~~
_This description is out of date, see beyond_
> fix issue 13741 - std.traits.moduleName does not work with functions that have parameters

- std/string.d
This adds a fromStringz function to complement the existing fromStringz function but for works for wide strings.
> Add a wide fromStringz function.

- posix.mak
- std/algorithm/iteration.d
- std/internal/digest/sha_SSSE3.d
- std/internal/math/biguintcore.d
- std/internal/math/biguintx86.d
See also: https://github.com/dlang-community/D-Scanner/commits/phobos
CC @JinShil
Required for https://github.com/dlang/phobos/pull/6515
> Bump Dscanner to 1b88b41f6b882c5e6044f10584e440c36fccbd7a

- std/algorithm/iteration.d
As mentioned in Jon's talk today, `joiner` is __really slow__.
This small improvement that was laying around for far too long.
```
std.joiner      = 5 secs, 180 ms, 193 μs, and 7 hnsecs
std.joiner.alias = 5 secs, 106 ms, and 2 μs
new.joiner      = 3 secs, 168 ms, 560 μs, and 6 hnsecs
foreach         = 2 secs, 537 ms, 962 μs, and 8 hnsecs
```
(ldc 1.9.0)
Benchmark code: https://gist.github.com/wilzbach/ffd5d20639766a831fd4b1962572897a
FWIW dmd is playing in a different universe here:
```
> dmd -O -inline -release ./joiner.d && ./joiner
std.joiner      = 57 secs, 834 ms, 289 μs, and 3 hnsecs
std.joiner.alias = 54 secs, 836 ms, 908 μs, and 6 hnsecs
new.joiner      = 44 secs, 936 ms, 706 μs, and 5 hnsecs
foreach         = 23 secs, 732 ms, 820 μs, and 3 hnsecs
```
> Improve joiner performance for random-access separators

- std/variant.d
The root cause is simply that the wrong static if check is used for something that should be a move semantic.
The two places that I could see this affects are assigning a `Variant` to another `Variant`, and the `get` function.
I'm 99% sure that this is correct. There's no way to get a reference to the data, so the fact that technically const data is changing doesn't matter. It's more like the same memory is just being used for something different.
This is reinforced by the fact that you can simply assign another value and it works (even without this change).
> Fix issue 18934 - make std.variant support getting types that have const members

- std/array.d
Note that I'm calling the delete operator indirectly here, since `delete` has been deprecated. `GC.free` does not run finalizers on the memory. I'm not sure exactly what `GC.runFinalizers` does (it seems to have to do with shared libraries), so I didn't use that.
> Fix issue 18995 - Make sure GC calls destructor when using std.array.array

- changelog/std-algorithm-iteration-joiner.dd
Follow-up to https://github.com/dlang/phobos/pull/6492
Preview:
> Add a changelog entry for the performance improvement of std.algorithmm.iteration.joiner

- std/uni.d
> [Ddoc] make "grapheme" a link

- std/net/curl.d
- std/uri.d
Needed for [druntime#2243](https://github.com/dlang/druntime/pull/2243)
> [trivial] Fix AA tests: order of AA elements isn't determined

- std/json.d
The test corpus provided at https://github.com/nst/JSONTestSuite/ revealed some issues with the std.json.parseJSON function. Since addressing some of the issues required parseJSON to reject input it previously accepted, I have added a new JSONOptions.strictParsing flag so callers can opt-in to the stricter parsing.
The issues, and how I've addressed them, are listed below (approximately from most severe to least):
Silently dropping ASCII NUL characters from strings:
n_string_unescaped_crtl_char.json
This is the most serious problem I found while fixing the test cases. The current implementation of parseJSON() uses a helper function called peekChar() which can store the next character to handle in a variable of type Char (an alias of the character type). Unfortunately it was using 0 to …
> Fix issue 16639 - Review std.json wrt this article on JSON edge cases and ambiguities

- std/functional.d
Flipped the static if statements in partial. It now checks whether we get a template or a struct/class with opCall overloaded. Else it assumes we get a function.
The branches in static ifs are to give better compile errors.
Bugzilla #15732
> Fix issue 15732 - std.function partial does not work with function / delegate references

- index.d
This also requires a dlang.org update.
> Issue 19055 - [404 Not Found] std.digest.digest

- std/exception.d
> Fix Issue 19041 - errnoEnforce: example does not compile

- std/random.d
Solution is to use a private `_randomIndex` function that is guaranteed to be called only with valid bounds. Closing issue 14001 is possible due to https://github.com/dlang/phobos/pull/6576.
> Fix Issue 14001 & Issue 19156 - `@nogc` std.random.randomCover and std.random.randomShuffle

- std/algorithm/searching.d
See https://github.com/dlang/phobos/pull/6143 and https://github.com/dlang/ci/pull/286
> Fix dxml regression in multiple arguments skipOver

- std/json.d
> Remove inout from JSON valuetype getters

- std/algorithm/iteration.d
I've targeted stable because this is a horrible bug
> fix substitute for single subrange subst

- changelog/std-experimental-checkedint-toHash.dd
- std/experimental/checkedint.d
This is a clean version of #6458
> Fix Issue 18675 - Missing toHash in std/experimental/checkedint.d

- std/math.d
To fix the ARM build on GDC, I guess LDC is affected as well? ping @klickverbot @JohanEngelen @kinke @ibuclaw 
I had to move the code to an external `_impl` function, because of this bug:
https://issues.dlang.org/show_bug.cgi?id=19235
An alternative might be inlining the `setControlState` code, but this implementation here is closer to the original code.
> [ARM] [GDC] Make hasExceptionTraps pure on ARM

- .editorconfig
Companion to https://github.com/dlang/dmd/pull/8656
> Fix line endings in .editorconfig

- std/math.d
POWER9 supports 128-bit IEEE, and the old long double format is in the middle of being be phased out in glibc.
We have no desire to support legacy, especially as our support is incomplete.  Better to just drop this type and only focus on completing 128-bit IEEE support.
Best reviewed ignoring whitespace changes.
https://github.com/dlang/phobos/pull/6708/files?w=1
FYI @redstar.
> std.math: Remove support for IBM extended reals

- std/net/curl.d
`std.net.curl.post` cannot be called with `ubyte` since `T` is not passed on.
> Fix Issue 18851 -- std.net.curl.post cannot be used with !ubyte

- std/array.d
For instance:
const Class[][] array;
`array.join` will try to `Unqual` the `const Class`, then build a `Class[]` to return. But since `Class` is a reference type, you cannot assign `const Class` to `Class`, and `join` fails.
Only use `Unqual` if `Unqual!T` is assignable `T`; otherwise return `T[]` instead.
> Fix issue 19257: std.array.join: only remove const if you can actually assign const to non-const values

- std/array.d
I'm not entirely sure about this one.
One one side, it's trivial to add this and it falls in the category of: "We don't add one-liners to Phobos".
OTOH the symbol already exists and it feels more natural for it, to accept two arguments too.
What do you think?
> Fix Issue 5502 - More handy ways to create associative arrays

- std/numeric.d
> [stable] Fix opBinary[Right]`CustomFloat op CustomFloat` ambiguity

- std/string.d
Add ASCII fast path for strings and avoid decoding altogether for wstrings. The benchmark was performed with the same inputs as https://github.com/dlang/phobos/pull/6727.
**string benchmark, ldc2:**
| compiler       | function       | data      | time                                |
|----------------|----------------|-----------|-------------------------------------|
| ldc2 -O2       | old_stripRight | ascii     | 1 sec, 396 ms, 375 μs, and 4 hnsecs |
| ldc2 -O2       | new_stripRight | ascii     | 553 ms, 499 μs, and 2 hnsecs        |
| ldc2 -O2       | old_stripRight | non_ascii | 1 sec, 311 ms, 629 μs, and 2 hnsecs |
| ldc2 -O2       | new_stripRight | non_ascii | 1 sec, 394 ms, 103 μs, and 5 hnsecs |
**wstring benchmark, ldc2:**
| compiler       | function       | data        | time …
> Fix Issue 19404 - Optimize std.string.stripRight

- std/string.d
Benchmark uses same test strings as https://github.com/dlang/phobos/pull/6770. ASCII timings were unaffected.
**string benchmark, ldc2:**
| compiler       | function       | data        | time                                |
|----------------|----------------|-------------|-------------------------------------|
| ldc2 -O2       | old_stripRight | non_ascii   | 1 sec, 362 ms, 31 μs, and 4 hnsecs  |
| ldc2 -O2       | new_stripRight | non_ascii   | 659 ms, 959 μs, and 4 hnsecs        |
**string benchmark, dmd:**
| compiler       | function       | data        | time                                |
|----------------|----------------|-------------|-------------------------------------|
| dmd -O -inline | old_stripRight | non_ascii   | 1 sec, 728 ms, and 184 μs           |
| dmd -O -inline | …
> Fix Issue 19405 - Speed up backwards UTF-8 decoding in stripRight & make nogc nothrow for strings

- std/file.d
Reverts dlang/phobos#6539
The PR was never approved.
> Revert "Add getTimesPosix"

- std/internal/memory.d
> Correct documentation in std.internal.memory

- std/string.d
Please see the individual commits' commit messages for details.
> Fix Issue 19429 - indexOf("a", "b") should be nothrow/@nogc

- std/algorithm/comparison.d
> min/max shouldn't pull std.format.

- std/traits.d
Competing implementation for: https://github.com/dlang/phobos/pull/6757
> Simplify isInnerClass

- std/array.d
Prevent Appender from implicitly calling struct constructors to cast away const.
Sample code:
```
struct Struct
{
int value;
int fun() const { return 23; }
alias fun this;
}
void main()
{
import std.array : Appender;
Appender!(Struct[]) appender;
appender.put(const(Struct)(42));
auto result = appender.data[0];
assert(result.value != 23);
}
```
What happens is that `Appender` checks that it can convert `const(Struct)` implicitly to `Struct`, but it does so via `cast(Struct)`, which then invokes `Struct(const(Struct).fun)` implicitly.
With this fix, instead of checking `const(Struct)` vs `Struct`, we check `Unqual` against `Unqual` and then use the dmd-fixed `cast()` to remove constness, before relying on implicit conversion to do the rest.
Note that this relies on …
> Fix issue 19572: Prevent Appender from implicitly calling struct constructors to cast away const.

- std/net/curl.d
- std/uri.d
> [dmd-cxx] Backport AA unittest fixes

- std/numeric.d
Just like #6839, we can simplify this.
> alias CustomFloat.opCast to get

- std/traits.d
Otherwise nothing gets tested.
> std.traits: use assumePurein the public example

- std/random.d
> [Revival of PR 4136]  Fix issue 15853 - std.random save methods must be const

- std/traits.d
Pull inner Impl templates out into std.traits so they're only instantiated once.
Use anySatisfy, staticMap instead of manually recursing.
Recursive template parameter iteration completely fails for large types. By using `staticMap`, we take advantage of its logarithmic recursion. `anySatisfy` is also inherently more efficient.
It's shorter too.
For an example of the problems the current approach causes, consider
```
import std.format;
struct VeryLargeType
{
static foreach (i; 500.iota)
{
mixin(format!"int v%s;"(i));
}
}
void main()
{
VeryLargeType a, b;
move(a, b);
}
```
> Fix issue 19689: don't use recursive template parameter iteration in std.traits.

- std/digest/murmurhash.d
Backport for GDC/`dmd-cxx` from latest stable to fix  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89177
> Backport: Fix unaligned access in std.digest.murmurhash

- etc/c/zlib/linux.mak
- etc/c/zlib/osx.mak
- etc/c/zlib/win32.mak
- etc/c/zlib/win64.mak
Let's see whether the auto-tester is still happy with this.
> Fix quoting in zlib makefiles

- changelog/comparison_bug.dd
- std/algorithm/comparison.d
Fixed documentation and comparison operator for better memory utilization
> Fixed comparison bug

- std/math.d
Added the correct asserts as well.[1]
[1] https://issues.dlang.org/show_bug.cgi?id=18728
> Fix Issue 18728 - std.math.fdim does not handle nan correctly

- std/utf.d
Constructors should not start reading in / consuming the data. Reading should only be done when asked for.
> byUTF: don't read from range in constructor

- std/utf.d
similar to https://github.com/dlang/phobos/pull/6900
> byUTF: use copy constructor for save()

- std/algorithm/searching.d
Fixes https://issues.dlang.org/show_bug.cgi?id=18806
I'll add a changelog when this is ready to be merged.
> Fix for the issue 18806: InputRange for std.algorithm.minIndex

- std/traits.d
Nobody would guess what this template does without carefully examining its implementation.
> Improve documentation for StringTypeOf

- std/algorithm/mutation.d
User need not be exposed to implementation arcana. Copy works for input ranges and compatible output ranges.
> Consolidate overloads of copy()

- std/variant.d
Issue in focus: <https://issues.dlang.org/show_bug.cgi?id=18818>
> variant.d: Gated unittests behind version(StdDdoc)

- std/range/package.d
Hopefully, this can unstuck the stable merge #6943.
The fix isn't as pretty as I'd like, but it's the best I could find. The difficulty is in trusting only the access to the union. Copies and `.save` calls can't be trusted.
In #6904, Walter solved this by adding `@trusted` helpers like this:
ref get1(return ref ChooseResult r) @trusted { return r.r1; }
That would work here too, but I think it's technically a violation of the `@trusted` contract. That function does not have a safe interface.
> fix safety of ChooseResult.save

- std/range/package.d
Works for me locally. Let's see if Buildkite agrees.
> fix buildkite build

- std/typecons.d
This avoids miscompilation when trying to format `const(Nullable!string)` due to attempted implicit `.get` conversion to string from T.init causing a compiletime error.
_reaches up, flips down counter: "It's been [0] days since the last bug caused by `alias Nullable.get this`"_
> Fix issue 19799: add const toString to Nullable

- std/digest/package.d
Pull out the duplicated code from the static and dynamic array overloads
(first PR from me.  LMK if this type of refactoring is useful or if there are other modules worth digging into)
> Factor out shared code from std.digest.toHexString overloads

- std/algorithm/searching.d
Using LDC with optimizations enabled the end compiled result is the same.
> Decrease template instantiation in std.algorithm.searching : all & any

- std/outbuffer.d
- std/uni.d
- std/xml.d
Tested on SystemZ/Linux and SPARC/Solaris.
> Fix tests that fail on version (BigEndian)

- std/net/curl.d
- std/outbuffer.d
- std/uni.d
- std/xml.d
... and backported std.net.curl patch.
> [dmd-cxx] Fix tests that fail on version (BigEndian)

- std/numeric.d
Normally, when a symbol is resolved, the alias this scope of the aggregate should be searched before moving to the upper scopes. However, due to a dmd bug, the alias this scope is checked after all the upper scopes are searched. [1] fixes the dmd bug, but adds a new transition switch. Compiling phobos with the new transition switch fails because ToBinary is resolved through the alias this. This is the correct behavior according to the new lookup rule. This PR makes phobos compliant with the new compiler transition switch.
[1] https://github.com/dlang/dmd/pull/8885
> Move std.numeric.CustomFloat.ToBinary to top-level

- std/bitmanip.d
> Fix Issue 19892 - Add CTFE support for std.bitmanip: nativeToBigEndian, bigEndianToNative, littleEndianToNative, nativeToLittleEndian

- std/algorithm/comparison.d
- std/algorithm/iteration.d
- std/algorithm/mutation.d
- std/algorithm/searching.d
- std/algorithm/setops.d
- std/algorithm/sorting.d
We can finally do this (: 
See also: https://dlang.org/changelog/pending.html#remove_visibility
> Use selective top-level module imports in std.algorithm

- std/ascii.d
sI -> si,
sO -> so
I have no idea how I did those.
> ControlChar: member name typos

- std/ascii.d
BTW we should replace all of the HTTP we can with HTTPS.
> [TRIVIAL] Make link clickable and safe

- std/array.d
more work on starting to work on dlang/phobos/project/2
> assert messages for std.array

- std/variant.d
> Variant of an array can be compared with another array

- std/experimental/allocator/building_blocks/region.d
This is currently blocking: https://github.com/dlang/dmd/pull/10092
> Fix blocking issue in std/experimental/allocator/building_blocks/region.d

- std/internal/cstring.d
When the source is an array  memcpy can be used if transcoding is unnecessary. The exact length of the output is also known in those cases even when the input is a narrow string.
> Issue 19983 - Add fast path using slice assignment to std.internal.cstring.tempCString

- std/bigint.d
- std/bitmanip.d
- std/internal/math/biguintcore.d
- std/variant.d
- std/xml.d
In support of https://github.com/dlang/dmd/pull/10130
> Replace D1 operator overloads with D2 operator overloads

- std/conv.d
https://forum.dlang.org/thread/hmmwqfuopwqwepxiicqg@forum.dlang.org
The current error message hints at an underflow if the input is NaN ("why am I getting an underflow if I don't have a large negative value?"). It now checks if the input is NaN before applying bounds checks and throws a more helpful exception.
> Clarified error when trying to convert NaN

- std/stdio.d
Don't read the line upon the construction of `byLine`, as that advances the file pointer and interacts badly with some range constructs involving `byLine` (such as `joiner`).
It's possible to avoid introducing `haveLine` by encoding it into null-ness of `line` (and moving EOF state from null-ness of `line` to null-ness of `buffer`), but that's probably too hacky for Phobos.
This patch also changes `byLine` so that `popFront` doesn't advance the file pointer (only calling `front` after `popFront` does that), but that's not necessary to fix the bug.
The overhead of the boolean checks added in this patch is probably negligible compared to that of the C `FILE*` implementation and the actual cost of doing I/O.
> Fix Issue 19980 - File.byLine skips first line in some cases when used inside map!()

- std/format.d
The format functions of FloatingPointType and IntegralType are adjusted and optimized to make their Final width and digits grouping conform to POSIX definition.
> Fix issue 20064,20069 - format functions make their final width and digits grouping conform to POSIX definition

- std/range/primitives.d
I don't know why the `!isAggregate()` needs to be there, I suspect it is a mistake, but this is a refactoring not a redesign.
> start making use of isAutodecodableString()

- std/experimental/allocator/building_blocks/region.d
- std/socket.d
- std/stdio.d
```
This is a cherry-pick of 034988a0db917719b59887d8017addba76076b1f
```
CC @ibuclaw
> [dmd-cxx] Add needed changes to get all tests passing with Musl

- std/math.d
https://github.com/dlang/phobos/pull/7153#issuecomment-524536212
> Issue 20159 Followup - fix ldc-win32 test failure

- std/algorithm/searching.d
- std/range/package.d
- std/typecons.d
In support of https://github.com/dlang/druntime/pull/2777
> Replace `hash_t` and `sizediff_t` with `size_t` and `ptrdiff_t`

- std/math.d
`scalbn` can be an alias of `core.math.ldexp`, which is an intrinsic on DMD and GDC and forwards to `core.stdc.math.ldexpl` on LDC. Calling DMD's intrinsic `core.math.ldexp` results in the same instructions as the inline asm in the existing version of `scalbn`.
> Fix Issue 20201 - Make std.math.scalbn pure

- std/bigint.d
> bigint.d: replace Error with assert()

- std/format.d
The error-checking benefit is probably achieved by just printing the first element and then stopping.
> Fix issue 20218: format: don't try to print the entire range while merely testing the format string

- std/conv.d
Documentation should also say how to define toString
> Reference std.format.formatValue from std.conv

- std/math.d
Reverts dlang/phobos#7182
See: https://github.com/dlang/phobos/pull/7182#issuecomment-538336141
> Revert "Fix issue 20205 - std.math: Wrong result for abs(int.min)"

- std/math.d
> Add unittest to std.math to avoid falling into the trap again.

- azure-pipelines.yml
See also: https://github.com/dlang/druntime/pull/2806
FYI: @rainers
> Run Azure Pipelines

- std/numeric.d
Just a cast was missing to allow for negative values...
> Fix Issue 20263 - Wrong value for CustomFloat.min_exp

- etc/c/sqlite3.d
Like the previous PR (https://github.com/dlang/phobos/pull/6997) I updated the SQLite 3 header to the latest version available
> Update header of sqlite3 to 3.30.1

- std/numeric.d
Not all combinations of template parameters for CustomFloat make sense. Most of them do not even work and yield strange error messages. I tried to narrow the bounds to catch every combination that doesn't work, with template constraints making for better error messages. This PR superseeds PR #7208.
> Fix issues 20260, 20281, 20284 - Limitations of CustomFloat.

- std/utf.d
> Added forgotten assert keyword

- std/format.d
Issue 9592 is about using width (and - flag) in a format parameter. For some types this is used, for others not. More strange: Sometimes it's used for elements (in arrays, ranges, AAs, partly classes and structs, where it shouldn't). More difficult: Elements of arrays and so on are handled different sometimes - e.g. strings are put into quotation marks. I do not address all of this with this PR.
I concentrated on %s only and only fixed some types. Additionally I put a note in the docs, where width is currently used and where not. (Which actually is the fix to issue 9592.)
There is one more, unrelated thing: In line 4541, the style checker hit a false positive. I used a hack to get arround this, but I think, this bug should be reported. Is bugzilla with component Phobos the right place to …
> Fix Issue 9592 - Justified Tuple printing

- std/json.d
std.json.JSONValue.toString and toJSON does not work with output ranges.
This PR fixes it.
https://issues.dlang.org/show_bug.cgi?id=20330
> Issue20330 json toString with OutRange

- std/conv.d
This is the simple part of that issue...
> Fix partially Issue 9621 - std.conv.parseEscape fails on octals and named

- std/zip.d
I removed the remaining artefacts of multidisk support, with the final goal in mind to make this file conformant to [ISO/IEC 21320-1:2015](https://standards.iso.org/ittf/PubliclyAvailableStandards/c060101_ISO_IEC_21320-1_2015.zip). This standard defines a subset of the original zip file which sounds very reasonable (and is quite similar to that, what's allready supported).
(Multidisk has been usefull in the 80ies, when zip files had to be stored on 640K-disks. Nowadays, there is no sensible usecase anymore.)
> Remove multidisk support completely from zip.std.

- std/typecons.d
This currently blocks: https://github.com/dlang/dmd/pull/10541
> Fix static import

- std/zip.d
I went through all exception handling, added a unittest where possible, removed throw statements that could never fire and replaced the remaining throws by calling enforce.
> Replace throw exception by enforce and add unittests. 

- std/internal/math/biguintcore.d
Additionally I removed a wrong comment.
> Fix Issue 16223 - BigUint: undefined shift for small instantiation type

- std/complex.d
- std/math.d
coshisinh link was also broken - fixed that too
> Fix Issue 19733 - expi documentation links broken

- std/format.d
Thanks to Simen Kjaeraas, who pointed out this solution - seems to be the most straight forward to me.
> Fix Issue 9588 - format prints context pointer for struct

- std/conv.d
non-empty range without number
> Fix Issue 18248 - radix overload of std.conv.parse fails to throw on

- std/getopt.d
Adds an parameter to defaultGetoptFormatter that allows a different format to be used.
In my experience, the current format used by getopt isn't what I typically see from tools, this will allow developers to create their own formatting based on their preferences/standards.
> Added a style parameter to defaultGetoptFormatter.

- std/conv.d
I also tried to find out if the same happens to very small numbers. On computers, where real>double, I think this cannot happen. But if real==double, I found an example where I think the current implementation gives a wrong result. I fixed that too.
> Fix Issue 5232 - [patch] std.conv.to & std.conv.roundTo report invalid overflows for very large numbers

- std/range/package.d
ping @aG0aep6G I think this looks much better.
After this, I probably will try and fix [19738](https://issues.dlang.org/show_bug.cgi?id=19738) as the [PR](https://github.com/dlang/phobos/pull/6933) seems stalled (found it while looking to see if this issue already existed).
> Fix issue 20495 (choose copies unused union member, which is unsafe)

- std/algorithm/iteration.d
Let's make the compiler happy...
> Fix Issue 15891 - Compiler error when std.algorithm.cache after 2 layers of std.algorithm.map

- std/algorithm/iteration.d
Only exists to trigger the autotester.
> WIP: Add @nogc to relevant std.algorithm.iteration.map unittests

- std/json.d
> Fix issue 20527. Set the correct union member for integers so CTFE

- std/socket.d
Another one in support for https://github.com/dlang/dmd/pull/10757
> std.socket: Move const to the RHS

- std/datetime/stopwatch.d
@jmdavis could you take a look at the subject?
> [docs] update deprecation schedule

- std/stdio.d
> Fix Issue 20585 - std.stdio.File.open() failure leaves File in invalid

- std/format.d
- std/internal/math/biguintcore.d
- std/zip.d
more endless buggy printf formats. Blocking https://github.com/dlang/dmd/pull/10812
> more printf format fixes

- unittest.d
Blocking https://github.com/dlang/dmd/pull/10812
> unittest.d: printf formats

- std/datetime/systime.d
> Typo fix in Systime describtion

- std/bitmanip.d
I'm doing this blindly, let's find out if the tests also think it's this easy...
> Make BitArray.count() const.

- std/math.d
which in turn means `isInfinity` and others can too.
> Allow floatTraits to work with inout

- posix.mak
- std/range/package.d
- std/typecons.d
Found in https://github.com/dlang/phobos/pull/7408
> Fix @betterC testsuite

- changelog/deprecate-xml.dd
- std/xml.d
See [forum](https://forum.dlang.org/thread/giykzxblfcgaavvndpbn@forum.dlang.org).
> Deprecate std.xml

- std/algorithm/iteration.d
Taken from patch for gdc bugzilla PR other/93756
> std.algorithm.iteration: Fix typo.

- std/digest/sha.d
blocking https://github.com/dlang/dmd/pull/10947
> sha.d: assert msg cannot be scope

- std/math.d
The FP unit-tests are a little better in upstream, but still only work when not optimizing.
> [dmd-cxx] Backport IeeeFlagsSupport and FloatingPointControlSupport

- std/algorithm/mutation.d
Note, I put in a test for static arrays, but I don't believe the compiler currently calls the copy constructor for copy construction (issue 20365), but if it starts doing that, this would possibly fail depending on how `__traits(hasCopyConstructor)` works.
> Fix issue 20732. Do not invoke any complex copy construction for swap

- std/algorithm/iteration.d
- std/container/rbtree.d
- std/conv.d
- std/internal/cstring.d
```
Steven identified a couple mistakes in the massive round of linkification.
Fixing them here.
```
Comments in question:
- https://github.com/dlang/phobos/pull/7441#discussion_r408232978
- https://github.com/dlang/phobos/pull/7441#discussion_r408199458
- https://github.com/dlang/phobos/pull/7441#discussion_r408195920
> Follow up review on PR 7441

- std/array.d
> [dmd-cxx] Appender and RefAppender: use opSlice() instead of data()

- std/algorithm/iteration.d
Provide an lvalue when checking the predicate
> Fix Issue 20496 - chunkby should support ref predicate

- std/complex.d
> std.complex: Add complex tan()

- std/format.d
> Add tests for empty empty static arrays of (|w|d)char's

- std/meta.d
by simply unrolling the template instantiations
> speed up instantation of Reverse and Filter templates

- std/meta.d
Obviate the need for `expectType` and `expectBool`. Also dogfood in `Pack`.
> Simplify isSame and Pack

- std/meta.d
It isn't obvious why the implementation strategy is used, so added an explanation.
> staticMap: explain design

- std/file.d
- Fix Issue 20785 - std.file.setTimes: on macOS use setattrlist to avoid truncating timestamp precision to microseconds
> merge stable

- std/math.d
Blocking https://github.com/dlang/dmd/pull/11236
> scalbn() doesn't inline

- std/bitmanip.d
`byteswap` was recently added to `core.bitop`
> bitmanip: make use of new byteswap() function

- std/digest/sha.d
See also https://github.com/dlang/phobos/pull/7534/files
> std.digest.sha1: don't reinvent bswap()

- std/getopt.d
See confusion of many long-timers (including me) here: https://forum.dlang.org/post/nafdmeyxcqythfcbdomu@forum.dlang.org
> Clarify getopt behavior with arraySep.

- std/digest/sha.d
Split from https://github.com/dlang/phobos/pull/7534
> sha: bswap without intermediate conversion to byte array

- std/utf.d
Propagate the changes in https://github.com/dlang/druntime/pull/3167 to phobos
> EASY: Companion to https://github.com/dlang/druntime/pull/3167/

- std/meta.d
`mixin()` expressions don't work with, for instance, `typeid()` expressions. As a result, `staticMap` to a template that takes `typeid` was broken. Fix this by moving the whole declaration into a statement mixin.
(Targeting `master`, not `stable`, because this was never on a release afaict.)
Also ping @John-Colvin .
> Fix issue 21088: move alias statement into staticMap mixin body.

- posix.mak
- win32.mak
- win64.mak
> Enable -preview=dtorfields for phobos

- std/experimental/checkedint.d
> std.experimental.checkedint should support chain assignment.

- std/traits.d
> Streamline std.traits.AliasThisTypeOf

- std/algorithm/comparison.d
> Fix Issue 21249 - clamp() is not stable and is not constrained

- std/experimental/checkedint.d
- std/process.d
Messages such as "please ignore this message" or warnings that you need to remember are benign have no business in a build log.
> EASY: obey the rule of silence.

- etc/c/sqlite3.d
Like the previous PR (#6997, #7239) I updated the SQLite 3 header to the latest version available
> Update header of sqlite3 to 3.33.0

- std/experimental/allocator/building_blocks/allocator_list.d
Nothing else in druntime/Phobos uses the problematic `minimumPageSize` symbol. Problematic because the page size changes from 4 to 16 KB with macOS 11.0. See https://github.com/dlang/druntime/blob/c27346a7f471b1e31194c71e962c44a0d28a2c85/src/core/memory.d#L168-L179.
> [stable] allocator_list unittests: Use core.memory.pageSize instead of minimumPageSize

- std/stdio.d
spurious crashes occur on Win64, e.g. https://github.com/dlang/dmd/pull/11865
introduced by https://github.com/dlang/phobos/commit/4b416afe1656607ac4f7a1cb704dbc47157d7398
> fix crash: keep a copy of the return value of setlocale(), it can become invalid

- std/internal/math/biguintcore.d
This code affects code coverage and shouldn't be here at all.
> math: remove unused code inside of unittest block

- std/variant.d
Previous link:
http://erdani.org/publications/cuj-04-2002.html = 404 Not found
New link:
http://erdani.org/publications/cuj-04-2002.php.html = 200 OK
> Incorrect link to info about discriminating union

- std/datetime/timezone.d
> timezone: wrap dirEntries foreach in a trusted lambda instead of making the whole function @trusted

- std/functional.d
---
`Iota` should really be in `std.meta`, but I didn't want to introduce a new public symbol in this PR.
> Fix issue 21347 - std.functional.adjoin should work in BetterC

- std/algorithm/searching.d
> Fix broken link in minElement doc

- std/math.d
PR #7176 didn't include extended-precision reals due to problems with FreeBSD in the CI suite. Opening this as a draft to see if I can get tests to pass.
> Make std.math.nextUp and nextDown and nextafter work in CTFE for extended-precision real

- std/stdio.d
This is in preparation for fixing the HAS_GETDELIM logic, which is wrong on some platforms (OSX hasn't always had getdelim).
Best seen using [?w=1](https://github.com/dlang/phobos/pull/7715/files?diff=unified&w=1).
> std.stdio: Merge readlnImpl implementations into one function

- std/stdio.d
Depends on ~#7714 and~ #7715 being merged first.
Although getdelim is currently unconditionally declared in druntime - which will need fixing - this moves the ownership of this platform-dependent detail out of phobos.
>  std.stdio: Replace version(HAS_GETDELIM) with __traits(compiles, getdelim)

- std/traits.d
This should be easy to review.
> fix Issue 21452 - isCallable erroneously returns false on function templates

- std/process.d
On Windows, the message for this common error case wasn't as informative as it should be:
```
Failed to spawn new process (The system cannot find the file specified.)
```
Handle this just like on POSIX via a message like:
```
Executable file not found: 7z.exe
```
> [stable] std.process: Include program name in exception msg if it cannot be found

- std/process.d
Follow-up to #7726.
This is on stable because it's based on #7726, which targeted stable.
Edit: I will open a separate PR for the changes unrelated to #7726, to avoid putting a lot of stuff in stable.
Edit 2: That didn't work.
> std.process touchups

- std/format.d
* W -> Writer
* FormatSpec -> FormatSpec!Char
> Update toString signatures to match formatValue

- std/range/package.d
Reverts dlang/phobos#7719
https://github.com/dlang/phobos/pull/7719#issuecomment-748463165
Blocks merging stable into master after https://github.com/dlang/phobos/pull/7727.
> Revert "Remove some unnecessary undocumented explicit ctors in std.range"

- std/traits.d
> Fix issue 21444: bad string concat in static assert message

- std/container/array.d
Fixes issues #21555 and issue #21556.
> Fix issue 21555, 21556 - container: array: insertAfter and insertBack are wrong

- std/conv.d
This is a copy of #7378. I'm the original author, but as I deleted my old account, I can't do any changes there.
I rebased and replaced "issue 20539" by a link to bugzilla.
> Fix Issue 20539 - std.conv.to: internal overload conflict for enums with base types that have a catch-all opEquals overload (?)

- std/typecons.d
This is a copy of #7301. I'm the original author, but as I deleted my old account, I can't do any changes there.
I rebased and replaced "issue 13663" by a link to bugzilla.
> Fix Issue 13663 - Comparison of Tuples with floating point fields

- std/container/array.d
Array!bool should have the same ctors as Array!T for other types.
> container: array: add ctors for Array!bool

- std/math.d
This is a copy of #7363. I'm the original author, but as I deleted my old account, I can't do any changes there.
I rebased everything and added the requested changes to the documentation unittest.
> Fix Issue 20508 - std.math.pow(-infinity, y) does not return NaN for imaginary or complex results

- std/datetime/systime.d
- std/file.d
- std/stdio.d
Prerequisite for dlang/dmd#12153
> [dmd-cxx] Backport portability fixes for getdelim, getline, and linux clocks

- std/mmfile.d
See note on the forums: https://forum.dlang.org/post/idpkrwpdhvckvvgdgnom@forum.dlang.org
> We should not be promoting using GC.free casually.

- std/algorithm/comparison.d
- std/algorithm/iteration.d
- std/complex.d
- std/conv.d
- std/format.d
- std/getopt.d
- std/internal/math/gammafunction.d
- std/internal/test/dummyrange.d
- std/math.d
- std/numeric.d
- std/parallelism.d
- std/random.d
- std/range/package.d
This is a copy of #7340. I rebased everything on master, removed conflicts and fixed one new place where approxEqual sneaked in in the last year.
> Replace approxEqual with isClose

- std/typecons.d
A little follow-up on something I've noticed during #7745.
> std.typecons.RefCounted: Properly forward r/lvalue-ness of ctor arguments

- .github/workflows/dmd-cxx.yml
> [dmd-cxx] Add GitHub workflow for dmd-cxx branch

- std/datetime/systime.d
- std/file.d
- std/parallelism.d
- std/process.d
- std/stdio.d
`thisExePath` is yet to be ported.
> Implement missing OpenBSD ports in phobos

- std/file.d
- std/parallelism.d
Depends on dlang/druntime#3360.
> Remove private extern(C) declarations from phobos

- std/bitmanip.d
Unittests where scattered around the file; I put them next to the item, they belong too.
> Tidy up unittests.

- std/bitmanip.d
A leftover of PR #7787.
I'm not sure what exactly is meant with the word 'bitfield': A single entry or the whole thing? (According to [Wikipedia](https://en.wikipedia.org/wiki/Bit_field) it is still something else, more or less a BitArray). I used `bitfield` for the whole thing, but after I finished got in doubt and are somewhat confused now. If you think it should be different, I'll reword it.
I also changed some ddoc style. IMHO structs and classes aren't params - it seems to me, that this was some sort of abuse of these macros. Having said this, I couldn't find a definitive description which macros should be used for Phobos docs. For me, it seems, every module uses it's own convention... If you've got a pointer to something useful, I'll be happy.
> Improve documentation and errormessage of bitfields.

- std/bitmanip.d
Additionally I fixed the old style using ".result" instead of template name and removed a superfluous import.
> Fix issues 21635 and 21636 - check parameters of bitfields

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/array.d
- std/datetime/systime.d
- std/parallelism.d
- std/typecons.d
These fully-qualified names are not really exposed in the current scope but are accessible due to bug dlang/dmd#12215.
> Remove a few uses of fully qualified names that rely on a DMD bug

- std/csv.d
https://issues.dlang.org/show_bug.cgi?id=21629
> Fixes #21629: std.csv report one record on empty input

- std/format/internal/write.d
This is the analogue of #7805 for write, but this time splitted into several PRs, because this file is much larger.
Where applicable, I used the D style guide, where not I tried my best. :-) (At least I tried to unify everything.)
> Refactor std/format/internal/write.d: Spaces and line breaks

- std/format/internal/write.d
I kept the two imports `assertCTFEable` and `formatTest` global, because they are used a lot and I have to cope with unittests later anyway (when the non internal modules are split, which is postponed until 2.096.0 is out).
> Make imports of std.format.internal.write local and selective.

- std/format/internal/floats.d
> std.format: Add %g (step 4): Formatting 0.0

- std/format/internal/write.d
When using `-preview=in`, `in` no more degrades to `const`,
and thus is not covariant with it, meaning some `toString`
signatures are no longer recognized.
This fixes it by testing for `in` parameters iff `-preview=in` is on.
> [stable] std.format: Recognize sink with `in` parameters

- std/format/internal/floats.d
%e like formatting is rather simple: There are two changes needed
1. Precision is the number of significant digits, not the number of fractional digits. That means, we have to reduce it at several places by one.
2. Without `#`-flag present, trailing zeros (and dot) have to be removed.
I had to revert the change of #7821, because `fabs` returns for whatever reasons a `real` while we here need the type of the argument. I will take care of that later.
> std.format: Add %g (step 5): %e like formatting

- std/format/internal/floats.d
Most of this PR is about getting the different meaning of `precision` right. Only at the end (of `printFloatF`), there is a part about removing trailing zeros.
> std.format: Add %g (step 6): %f like formatting

- std/format/internal/floats.d
Before going live, there are still a few small things to do:
a) Add an extra char to the buffer. In theory this isn't needed, but during the preparation of step 7 I noticed, that it might happen, if the split is not perfect, that a dot is added and removed later. To avoid problems, I added this extra char.
b) Unittest for gc avoidance.
c) Adding %g to the external unittest, which is versioned out, but in case, someone want's to use it, it should work...
> std.format: Add %g (step 8): Small fixes

- std/base64.d
Unfortunately this adds uncovered lines inside the unittests. But I think it's a little bit awkward to add more code to test these too...
> Add more coverage to base64.

- std/base64.d
This morning I realized, that the six unittests added in #7849 could be written much more compact, using templates.
> Condense six unittests into one

- changelog/std-sumtype.dd
> Add changelog entry for std.sumtype

- std/format/spec.d
Corrected a few whitespaces and made some imports local and selective (and removed a few, that where not used).
Public docs will be handled in a seperate PR.
> std.format: Refactor spec.d

- std/format/read.d
Corrected a few whitespaces and made some imports local and selective.
Public docs will be handled in a seperate PR.
> std.format: Refactor read.d

- std/format/write.d
Corrected a few whitespaces and made some imports local and selective.
Public docs will be handled in a seperate PR.
> std.format: Refactor write.d

- std/format/package.d
This is mainly about source code formatting. Additionally, I removed a few debug statements, that seem to be of no use, an unused label, added pure to a floating point unittest (is meanwhile pure for float/double) and added a link for an issue comment.
> std.format: Refactor package.d (step 1): Whitespace and nits

- std/format/package.d
I switched the order of the two overloads, because in my opinion, the overload that resembles a function call in other languages (and without template constraints) is better understandable by new users and with the switch it's shown first in the docs. This is also the order of the examples below: First "normal" use, then check at compile time. (And `guessLength` does not sit in between these two overloads.)
I added a "normal" example and moved the `traits` stuff from the other example into a non public unittest. IMHO, for a beginner it's easier to understand a comment, telling, that something does not compile, than a `traits` statement.
> Rework documentation of std.format.package : format

- std/complex.d
The current algorithm is based off the Smith algorithm.  This rewrite uses a variant of the Cephes (naive) algorithm that encourages the optimizer to merge the two divides into one (with use of SSE2 `divpd`).
> fix Issue 18627 - Use cephes algorithm for complex divide

- std/format/package.d
I removed `buf` from the first line, because this line might be used in other contexts, where `buf` is not known (for example in overview tables).
I switched the order of the two overloads, because in my opinion, the overload that resembles a function call in other languages (and without template constraints) is better understandable by new users and with the switch it's shown first in the docs. This is also the order of the examples below: First "normal" use, then check at compile time.
I removed the reference to `format()` in the comment about checks at compile time, because I couldn't find anything useful there, apart from a note, that it might produce faster code, which only applies to `format` but not to `sformat`.
I replaced the example, because I dislike unimaginative foo-bar …
> Rework documentation of std.format.package : sformat

- std/format/spec.d
I moved the public unittest up, so it's the first unittest.
> Rework documentation of std.format.spec : FormatSpec

- std/regex/internal/ir.d
- std/regex/package.d
This PR fixes a performance regression in std.regex introduced by PR #7678. Bug issue 
is [2176](https://issues.dlang.org/show_bug.cgi?id=21716).
Note that the PR is for a merge to stable, rather than master, as this is a regression.
PR #7678 made changes to std.regex to provide API functions marked as `pure`. The APIs involved memoizing prior regex matchers for performance, so they are not `pure` from the compiler's perspective. The technique used to change the function attributes to `pure` had the effect of introducing delegates. This caused GC resulting in performance degradation. PR #7678 was released as part of DMD-2.095.
This PR modifies the code to use static functions rather than delegates, avoiding GC. This removed GC generation and brought performance back in line with …
> Fix issue 21716: std.regex performance regression.

- std/format/internal/floats.d
The main problem here is, that the algorithms are designed for mantissas that are at max 60 bit long (maximum that fits in an ulong, because we need 4 bits for carry), but the mantiassa of x87 reals has 63 bit. So we need some extra code to get around these 3 extra bits.
The second added unittest contains a few corner cases where the new code is needed. It also covers the bit extraction at CTFE which could not be covered in #7862.
I ran more than 20 million random external tests comparing the output of `snprintf` with this implementation, without any difference reported. (That took several hours. Formatting reals is rather slow (with `snprintf` as well as with this implementation), because of the large output.)
> std.format: Add %f for x87-reals

- std/format/read.d
I renamed the template parameters `R` and `S` to `Range` and `Args` for consistency with other templates used in `std.format`.
I changed the order of the two overloads, like I did with `format` and `sformat` because I think, for beginners the one without template parameters is better comprehensible. For the same reason I did not use idiomatic D for the first example.
> Rework documentation of std.format.read : formattedRead

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/datetime/systime.d
- std/experimental/typecons.d
- std/parallelism.d
- std/typecons.d
There are some more holes to plug in the package visibility system, this ensures phobos is still compilable after dmd has been patched.
> [dmd-cxx] Backport some more import fixes

- std/format/read.d
This one was more work than I expected. I first had to go through the whole source code to understand what really happens, because no useful documentation was available. I found several issues while doing so, but wrote the docs as if these issues were not there, using what I think was intended.
I wonder a little bit, what's the use case of reading `null`...
> Rework documentation of std.format.read: Module description

- std/format/internal/floats.d
Similar to #7907. I had to give two extra bytes of space for the exponent at three places, which can now be up to 5 digits long.
Additionally I found a small mistake in the unittests of `%f`, where actually a double was used instead of a real. I fixed that too.
And finally I commented out some unittests, which are too slow (5000 digits with extreme values in CTFE) and consume too much memory while compiling. With the current implementation they would be a constant burden on the test suite - I didn't notice this when I filed #7907, but with twice as many of these tests, my OS just killed the compilation process... The downside of this is, that a few lines of the bit extraction for reals are not covered now. I think, we can do this, when `%a` is add. `%a` is much less problematic in this …
> std.format: Add %e for x87-reals

- std/format/internal/write.d
There are three stretchable places in the output of `formattedWrite`: Padding left, padding right, and leading zeros. While the former implementation cared about the first two, this new implementation takes all three into account. It also cares about grouping (which it has to inevitably, when dealing with leading zeros). This has several advantages:
- Code for grouping (which is error prone and still [not always correct](https://issues.dlang.org/show_bug.cgi?id=21777)) is done at one place only.
- It will play a key role in making `printFloat` 100% `@nogc`.
- Support for centering output can be easily added once all (relevant) overloads use this.
I also thought about making `writeAligned` public, so it can be used in `toString` methods too, but decided to postpone this until I had more …
> Extend writeAligned to care about grouping.

- std/format/internal/floats.d
There was almost nothing to do for `%g`, only adding unittests.
I had to fix a bug in the bit extraction routine though: `%g` needs to preserve the original value to decide upon `%e`-like and `%f`-like output.
> std.format: Add %g for x87-reals

- std/format/internal/floats.d
This is the last one, before going life. There was little to do: dmd does not allow a left shift by 64, hence I had to implement a workaround, essentially replacing `(1 << x) - 1` by `(1 << (x - 1)) + 1` which is the same, because we know `x >= 4`. Alternatively one could have replaced the single shift by two.
Anyway, there is [issue 20536, %a on reals is inconsistent with %a on float/double](https://issues.dlang.org/show_bug.cgi?id=20536) remaining, which means that at least on computers with `glibc` formatting will change. For several reasons I think this will not cause much problems:
- The C standard about the result of `%a` is not clear, therefore both versions are valid results and other versions of `libc` might indeed produce the proposed results.
- `%a` is not used much, and if it …
> std.format: Add %a for x87-reals

- std/format/write.d
I intentionally skipped the `struct` examples. I want to cope with these halve a dozen `toString` variations in a separate PR.
I removed the `delegates`-example. Formatting delegates is creepy and buggy currently, and the example does not even use `formatValue` but uses `to` from `std.conv`. IMHO formatting delegates (and functions?) should be completely revised before giving an (almost useless) example.
> Rework examples of std.format.write

- std/digest/hmac.d
Original commit on master = 4c13507fc291d3ca5dfb496286a003c9d62a2a20
> Fix CI testing of stable branch

- std/variant.d
> Fix Issue 18780 - Inconsistent behavior with Variant holding int converting to unsigned types

- std/format/internal/write.d
While trying to use the new version of `writeAligned` to improve formatting of integers I noticed, that I overlooked something: `precision` for integers is used to add leading zeros. As this is another stretching part, it has to be done by `writeAligned`. This PR serves to implement this feature.
I also used it to fix a small bug: Grouping should also work, when no width is specified.
> std.format: Add precision for integers to writeAligned.

- std/variant.d
Initial discussion at https://forum.dlang.org/thread/wbpnncxepehgcswhuazl@forum.dlang.org?page=1
> Try to make `std.variant.maxSize` non-recursive

- std/numeric.d
This is neccesary for fixing gcd to be able to handle negative values (Issue 21834).
> std.numeric: Support mixing integral types in gcd()

- std/math/algebraic.d
Computes the square root of the sum of the squares of x, y, and z.
> std.math.algebraic: Add overload for three-dimensional hypotenuse

- std/format/package.d
Final spurt: After this there will be only one more PR before the document format marathon ends. :-)
As this table has a normative touch, repetitions are somewhat intentional.
I also fixed two nits that I overlooked in the previous PR.
> std.format: Add overview table of all combinations of types and format characters.

- std/stdio.d
Unfortunately, looks like I'm going to have to deprecate and rename everything else, as they are all (unintentionally?) public. :-(
> std.stdio: Remove 'under-the-hood' C I/O functions that are now declared in druntime

- std/process.d
The temporary buffer returned by `tempCString` was assigned to a `char*` and hence destroyed after the statement.
This worked by accident for small URL's because the space was allocated on the stack and not overwritten before forking.
~~IDK how to add a test for this.~~
> Fix 20886 - Retain tempCString buffer in browse

- std/format/internal/floats.d
- std/format/internal/write.d
Followup on #7971 and #8000. See there for more details.
> std.format: Make formatting with %a 100% @nogc.

- std/format/internal/floats.d
- std/format/internal/write.d
Followup on #7971 and #8000. See there for more details. See also #8005 and #8006.
> std.format: Make formatting %f (and %g partly) 100% @nogc.

- changelog/add_centering_flag.dd
- std/format/internal/write.d
- std/format/package.d
- std/format/spec.d
With having `writeAligned` it's not much work, to add centering output too. What do you think, is this extension worthwhile?
> Fix Issue 21858 - std.format: centering output

- std/format/internal/write.d
nested format string of associative arrays should be detected
> Fix Issue 21875 - std.format: wrong number of format specifiers in

- std/stdio.d
It's my first PR against stable, so I hope I made no beginners mistake here.
> Fix Issues 21728, 21729 and 21730 (check for open file, before using trustedFread)

- std/math/algebraic.d
The `static assert(2*(SQRTMAX/2)*(SQRTMAX/2) <= real.max);` condition fails on PowerPC.  This also opens up for adding `float` and `double` overrides of the hypot (possibly by converting the function to a template).
> std.math.algebraic: Support more float types in hypot

- std/math/algebraic.d
Adds support for `float` overload.
> std.math.algebraic: Convert hypot to a template

- std/experimental/checkedint.d
- std/process.d
Co-Authored-By: @bernd-edlinger
Following on from #8074, I've checked phobos-master and found a few more lingering temp files.
> Cleanup temp files in std.process and std.experimental.checkedint

- std/experimental/allocator/common.d
> Annotate allocator/common.d to please dlang/dmd#12520

- std/path.d
> Annotate std/path.d to please dlang/dmd#12520

- std/process.d
> Annotate std/process.d to please dlang/dmd#12520

- std/xml.d
> Annotate std/xml.d to please dlang/dmd#12520

- std/utf.d
> Annotate std/utf.d to please dlang/dmd#12520

- std/uni/package.d
> Annotate std/uni/package.d to please dlang/dmd#12520

- std/string.d
> Annotate std/string.d to please dlang/dmd#12520

- std/stdio.d
> Annotate std/stdio.d to please dlang/dmd#12520

- std/socket.d
> Annotate std/socket.d to please dlang/dmd#12520

- std/internal/digest/sha_SSSE3.d
> Annotate sha_SSSE3.d to please dlang/dmd#12520

- std/net/isemail.d
> Annotate std/net/isemail.d to please dlang/dmd#12520

- std/experimental/allocator/building_blocks/bitmapped_block.d
> Annotate bitmapped_block.d to please dlang/dmd#12520

- std/container/dlist.d
> Annotate std/container/dlist.d to please dlang/dmd#12520

- std/base64.d
> Annotate std/base64.d to please dlang/dmd#12520

- std/format/internal/floats.d
See #8050 for the general idea.
I'll provide a clean-up-PR (removing then unnecessary tokens) once this is merged.
> std.format: Use rounding tool to round %f on floats.

- std/traits.d
- std/variant.d
Not sure how useful those XxxOf are, but added this one for completeness.
Also refactored QualifierOf into something that probably the compiler would have an easier time going through.
> Add missing SharedConstInoutOf and refactor QualifierOf

- std/process.d
Explanation in the comments.
Blocking https://github.com/dlang/dmd/pull/10951
> add @trusted for scope pointer to scope pointer

- std/uni/package.d
Part of https://github.com/dlang/phobos/pull/8113
> Add `return scope` to std.uni MultiArray ctor

- std/datetime/systime.d
Blocking https://github.com/dlang/dmd/pull/12620
> Fix local variable lifetimes in systime parsing

- std/container/array.d
Currently, the implementations of `length` and `reserve` have many lines in common.
For the case of `newLength > length`, many lines can be replaced with `reserve (newLength); _payload = _payload.ptr [0 .. newLength];`.
=> Easier to understand. Easier to re-use future improvements.
Testing information:
```
$ cd std/container/
$ rdmd -unittest --main array.d
1 modules passed unittests
```
> std.container.Array: Simplify implementation of length (by calling reserve).

- std/file.d
Some unittests should compare with a sorted array to be
correct.
> file: document dirEntries as no garantee of sorted output

- std/traits.d
This incidentally fixes a 'TODO' in `BuiltinTypeOf`: `ifloat`/`idouble`/`ireal` and `cfloat`/`cdouble`/`creal` were being collapsed to `ireal` and `creal` and their qualifiers were being discarded.
> Streamline std.traits.BuiltinTypeOf & IntegralTypeOf

- std/container/array.d
This is a unittest for a bug, not a public example.
> std.container.array: Hide unintentionally-public unittest

- std/array.d
---
Read the patches description for context.
> std: array: refactor std.array unittest blocks and attribute annotation

- std/traits.d
> Fix #22110: std.traits: isCallable fails for templated opCall

- std/sumtype.d
Fix for https://github.com/dlang/dmd/pull/12010#issuecomment-877849728
> Fix betterC unittest of SumType for issue 20150

- std/file.d
- std/typecons.d
needed for https://github.com/dlang/dmd/pull/12890
> add cast(void) to silence warnings in tests

- std/regex/internal/ir.d
https://issues.dlang.org/show_bug.cgi?id=21600
> Fix Issue 21600 - (Try to) Document named captures

- std/container/array.d
Add a function called `data()` to return the internal representation of the Array.
The function is marked as `@system`
> [DSSv3] Fix Issue #21100: Add data() function to std.container.array.Array

- std/traits.d
This code is dead since we now have a dedicated trait in the frontend,
instead of deriving it from the mangling.
> Remove dead demangling code for funcattr / param stc

- std/traits.d
> Fix Issue #22140: FunctionTypeOf fails for template opCall without any templated argument

- std/utf.d
I also added unittests and an example.
> [DSSv3] Fix Issue 16210 - std.utf.byUTF can be made into a bidirectional range

- .cirrus.yml
This in the hope to avoid accidental regressions such as dlang/druntime#3546
> Cirrus CI: Add FreeBSD 11 pipeline

- std/math/algebraic.d
> std.math.algebraic: use fabs from druntime

- std/datetime/systime.d
Define it instead of wondering what it means.
> define hnsec

- std/random.d
Moved from the dmd testsuite, as it really belongs here.
> std.random: Add test for Issue 8671

- posix.mak
> make: remove duplicate ifdef block for NO_AUTODECODE

- std/exception.d
> std.exception: make unittests reproducible on -boundscheck=off

- .circleci/run.sh
- posix.mak
> Test compiling Phobos with `-boundscheck=off` in CI

- std/file.d
> std.file: don't initialize stat struct here

- changelog/chunkBy_mostly_safe.dd
I did not wholly fix the linked issue with #8213 so there is no changelog entry. Made one.
> Added changelog for pr #8213

- etc/c/curl.d
I'm not sure this is the right thing to do, because I'm not updating the whole header ¯\\_(ツ)_/¯
> add some more auth types to etc.c.curl

- std/traits.d
This is complement to https://github.com/dlang/druntime/pull/2742
> Alias traits from druntime

- std/typecons.d
While glancing over the `Tuple` template, I've noticed that it uses the anti-pattern of nested template declarations *not* depending on the outer `Tuple` template parameters.
> std.typecons: Minimize redundant template declarations/instantiations wrt. Tuple

- std/typecons.d
In the `unittest`, there was a comment:
```
// file gets properly closed when last reference is dropped 
```
The `unittest` has now been modified so that the statement in the comment is actually tested.
For this, I have moved some of the lines inside a new scope (i.e. a new pair of braces). I have not re-indented the code in order for the Git history to be preserved (e.g. output of `git blame`, `git diff`, `git log -p`).
> refCounted: unittest now also checks object destruction.

- posix.mak
- std/typecons.d
- win32.mak
- win64.mak
Upgrade to spec compliant struct compares
> add -preview=fieldwise to build

- std/process.d
Previously, if this call to 'open' failed, it would result in a spurious
test failure. Now, it instead causes the test to be skipped.
Possibly related to https://issues.dlang.org/show_bug.cgi?id=22350
> Check return value of 'open' in std.process test

- .cirrus.yml
> [stable] cirrus: Switch to big-sur image

- std/variant.d
@ is not encoded. Replaced with %40
Warning: FAT PR
> Fix broken link

- std/container/rbtree.d
- std/internal/math/biguintcore.d
- std/json.d
- std/net/isemail.d
- std/process.d
- std/utf.d
Same as https://github.com/dlang/druntime/pull/3636
> Use `return scope` instead of just `return`

- std/algorithm/iteration.d
Not sure I like that `@trusted`. Then again, I'm not sure why `move` is `@system` either.
`replaceCurrent` is a function instead of the `move` being inlined because `move` wants a lvalue source.
> Fix issue 22561: Allow joiner to reassign range values that contain immutable fields.

- std/format/write.d
Requested at https://github.com/dlang/phobos/pull/8278#issuecomment-997417367. 
FYI, @JohanEngelen.
Test copied from https://issues.dlang.org/show_bug.cgi?id=22609.
> Add unittest for issue 22609

- azure-pipelines.yml
Cherry-picks #8348  to master because of the upcoming brownouts
> Cherry-pick Azure upgrade to master

- std/bigint.d
- std/file.d
- std/internal/math/biguintcore.d
For https://github.com/dlang/dmd/pull/13672
> Unblock "address of ref can be assigned to non-scope parameter"

- std/socket.d
> fix Issue 22791 - std\socket.d(790) Heisenbug random failure

- .cirrus.yml
---
Related to https://github.com/dlang/dmd/pull/13652 .
CC @MoonlightSentinel @thewilsonator
> ci: use ci/run.sh and ci/cirrusci.sh scripts from dmd

- std/sumtype.d
isSumType!T now evaluates to true instead of false when T is a templated
struct type that implicitly converts to a SumType via alias this.
> sumtype: work around issue 21975 in isSumType

- std/datetime/interval.d
- std/datetime/systime.d
Follow up of https://github.com/dlang/phobos/pull/8398 for the unittest build
> Annotate `SysTime.opBinary` as `returnScope`

- std/algorithm/setops.d
Error uncovered by https://github.com/dlang/dmd/pull/13693
> Fix `return scope` in cartesianProduct Result.save

- changelog/log_default_info.dd
- std/experimental/logger/core.d
- std/experimental/logger/filelogger.d
- std/experimental/logger/multilogger.d
Ping @atilaneves Followup to #8336 for next point release.
> Change default log level to info instead of warning.

- std/typecons.d
- negation did not work with unsigned integers with dmd v2.099.0
- also made double negation of flags possible
> Fixed negation of `BitFlags`

- std/datetime/systime.d
- std/json.d
Similar to https://github.com/dlang/druntime/pull/3782
> Fix incorrect `return scope` annotations

- std/windows/syserror.d
This ensures that the method throws a `WindowsException` initialised
with the proper error code. Also avoids unrelated exceptions that
could suppress the error which caused the call to `sysErrorString`.
---
Related: #8420
> Fix 22947 - Use wenforce in sysErrorString

- std/traits.d
The body of the mixin does a copy initialization of the parameter. However, the copy constructor cannot be used with context pointers. This is a known issue: https://issues.dlang.org/show_bug.cgi?id=22239 .
However, this PR solves the issue by implementing a workaround that also might be a potential optimization.
> Fix Issue 20182 - [REG 2.086.0] std.traits.ParameterDefaults fails for copy constructor of nested struct

- changelog/zlib.dd
Follow-on from #8437 but done right this time.
> Add changelog entry for zlib update

- .cirrus.yml
See https://github.com/dlang/dmd/pull/14076
> cirrus.yml: Use an alternative mirror for FreeBSD 11

- std/sumtype.d
Signed-off-by: João Lourenço <jlourenco5691@gmail.com>
> test(sumtype): utilize D_Invariants conditional compilation

- changelog/logger_remove_compile_time_loglevel.dd
- std/experimental/logger/core.d
- std/experimental/logger/package.d
> remove compile features from std.experimental.logger

- std/math/exponential.d
Currently, `std.math.logb` just forwards to `core.stdc.logbl`.  In libm, however, this just calls `core.stdc.ilogb`. As we already have a pure implementation of `ilogb` ourselves, do the same without going through libm.
This also introduces float and double overrides for the `logb` function, which continues the slow migration away from having an x87-only interface to `std.math`.
> std.math.exponential: Implement pure logb() for double and float precision

- std/math/exponential.d
It all still uses `real` under the hood.  This makes it so adding float and double implementations becomes trivial.
Best viewed with [`w=1`](https://github.com/dlang/phobos/pull/8494/files?w=1).
> std.math.exponential: Split generic logN implementations to own impl templates

- std/math/exponential.d
When doing some spot checking, I noticed that we are using different set of log coefficients to what cephes has for its 80-bit real implementation.  The end result would amount to at least a 27bit difference in the computed logarithm.
I trust that cephes would be more accurate than what we are currently doing here.
> std.math.exponential: Fix coefficients for log2 and log10

- std/sumtype.d
```
TagTuple wass previously nested within matchImpl, meaning it gets
a different instantiation for each match call with different handlers.
This is not required, as the only template parameters it needs are
the SumTypes being used. In practice, we might even get away with
using the length, but the gain is likely to be marginal compared
to the gains from moving it out of matchImpl.
Another underlying motivation for this change is that it works around
a compiler bug triggered with complex code using const SumType
(the compiler complains that 'this' for 'invariant' is of the wrong type,
const vs non-const).
```
The issue in question: https://issues.dlang.org/show_bug.cgi?id=22010#c4
```
../dmd/generated/linux/release/64/../../../../../phobos/std/sumtype.d(1979,28): Error: need `this` for …
```
> std.sumtype: Move TagTuple to module level to reduce instantiations

- std/typecons.d
Currently blocking: https://github.com/dlang/dmd/pull/14269
> Use try-catch instead of scope(failure) for block that returns

- changelog/logger_sharedLog_returning_shared_logger.dd
- std/experimental/logger/core.d
- std/experimental/logger/filelogger.d
- std/experimental/logger/multilogger.d
> sharedLog returning shared(Logger)

- std/container/array.d
Fix issue 23140: [https://issues.dlang.org/show_bug.cgi?id=23140](https://issues.dlang.org/show_bug.cgi?id=23140)
> fix issue 23140

- std/array.d
another blocker for https://github.com/dlang/dmd/pull/14367
> more static class in std.array

- std/random.d
so https://github.com/dlang/dmd/pull/14367 can compile it.
> std.random unittest class should be static

- std/conv.d
A much simpler and more efficient implementation using a recursive function.
> std.conv.octal: simplify implementation

- std/stdio.d
> chore(stdio): annotate postblit of File struct

- std/experimental/allocator/common.d
For sample usage see
https://github.com/nordlow/phobos-next/blob/master/src/nxt/dynamic_array.d#L32
Also see discussion at https://forum.dlang.org/post/uiavxptceyxsjulkxlec@forum.dlang.org.
> Add isAllocator

- std/bitmanip.d
> chore(bitmanip): add missing attributes

- std/algorithm/sorting.d
- std/container/array.d
- std/file.d
- std/process.d
- std/socket.d
- std/typecons.d
- std/windows/registry.d
These modifications are made according to D-Scanner's rule that local imports should be selective
> add selective local imports

- std/array.d
> remove use of isPointer from std.array

- std/internal/windows/advapi32.d
- std/stdio.d
- std/typecons.d
This is https://github.com/dlang/phobos/pull/8627 but actually targeting stable this time...
> [stable] Cherry-pick changes from master that are needed for dub to compile

- changelog/unique-struct-dtor.dd
See https://github.com/dlang/phobos/pull/8651.
> Add changelog for Unique!struct calling destroy

- std/traits.d
Blocking: https://github.com/dlang/dmd/pull/14802
> Use traits(getVirtualMethods) instead of traits(getVirtualFunctions)

- std/concurrency.d
Add links to core.thread.fiber.
Tweak formatting.
> Tweak std.concurrency docs

- std/bitmanip.d
I noticed the codegen was really bad for signed integer, and no doubt, it is using a branch instead of leveraging the capability of the CPU to the an arithmetic right shift. The double shift is trivially turned into an and for unsigned operands, so it doesn't change anything for these with any half decent optimizer involved.
> Branchless sign extend in std.bitmanip

- std/stdio.d
Fix Issue 19567 - added information about how ftell function works.
> Fix Issue 19567

- std/range/primitives.d
- std/traits.d
See commits for details.
Follows on from #8682.
> More avoidance of std.traits.ReturnType

- std/traits.d
> Change a unittest in std.traits for upcoming deprecation

- std/concurrency.d
See comment and https://github.com/dlang/dmd/pull/14706#issuecomment-1432027545.
@pbackus
> [std.concurrency] Avoid throwing shared type

- std/path.d
Supersedes https://github.com/dlang/phobos/pull/8723
> Remove redundant `assumeUnique` in std.path

- std/functional.d
Just noticed it wasn't in the table at the top.
> Add bind to the header table

- std/conv.d
Removed another reinvented wheel.
Pull https://github.com/dlang/phobos/pull/8754 first.
> std.conv integer to string: use core.internal.string

- std/range/package.d
Currently blocking: https://github.com/dlang/dmd/pull/14986
> Don't use this in static context in std.range.package

- std/algorithm/iteration.d
- std/algorithm/mutation.d
- std/algorithm/searching.d
- std/complex.d
- std/container/array.d
- std/conv.d
- std/exception.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/format/internal/floats.d
- std/format/internal/write.d
- std/math/operations.d
- std/path.d
- std/random.d
- std/range/package.d
- std/signals.d
- std/stdio.d
- std/traits.d
See https://github.com/dlang/dmd/pull/15328
> User hyperlinks to refer to bugzilla issues

- std/stdio.d
In my recent work on std.stdio, I wasted a lot of time trying to decode what the types were. As a result, this PR adds some internal documentation on the types. It also adds `fileno_t` which is more meaningful than `int`.
The internal documentation isn't complete, but as other aspects are deduced it can be added to.
Terrible documentation in std.stdio is likely a major contributor to baffling problems people have with it:
https://issues.dlang.org/show_bug.cgi?id=24001
> std.stdio: add glossary, fileno_t

- std/math/package.d
- std/stdio.d
The time has come for them to go.
> Remove declarations with expired deprecations

- std/math/package.d
> Cross-link to std.mathspecial.

- std/json.d
- std/socket.d
Made many sentences conciser and clearer as well as corrected capitalization and spelling issues
> Improve documentation in std.json and std.socket

- std/traits.d
Complements the existing `isImplicitlyConvertible`. From discussion in #8819 and #8827, it seems like we might want to include this so that users don't have to invent their own versions.
> Add std.traits.isQualifierConvertible

- changelog/PR8838.dd
> Add changelog entry for isBasicType

- std/array.d
Needed for https://github.com/dlang/dmd/pull/15837.
> Fix assert on array literal

- .github/workflows/main.yml
Required after https://github.com/dlang/dmd/pull/15832.
> GHA: Adapt to recent dmd CI changes

- .gitignore
- tools/unicode_table_generator.d
Make it easier to regenerate `std.internal.unicode*`.
@rikkimax
> Automatically download Unicode files for table generator

- Makefile
Build time goes from 8.6s to 8.2s for me.
> Compile zlib in one go

- std/mmfile.d
https://github.com/dlang/phobos/pull/8891#discussion_r1453361712
> Fix std.mmap documentation

- std/algorithm/iteration.d
This was discovered here:
https://github.com/dlang/dmd/pull/16145#issuecomment-1933424830
> CheckBy postblit should be scope

- .github/workflows/main.yml
The Phobos PR of dlang/dmd#16201.
> gha: Update cross-platform-actions to v0.23.0

- std/typecons.d
This should make it so that a variable of type Nullable!T has the same
behavior with regards to destruction as a variable of type T even when
it's const, immutable, or shared.
> fix Bugzilla Issue 24403 - Nullable doesn't work with non-mutable types with a destructor

- Makefile
> Build: Add option USE_IMPORTC=0 to switch back to compiling zlib with C compiler

- .github/workflows/main.yml
Mainly to work around the macOS 13 issue.
> [stable] GHA: Sync main.yml with DMD repo's

- lib/sys/meta.d
This ports std.meta.staticMap to lib.sys.meta as Map.
The implementation is the same, but the documentation and tests have been expanded.
As has been discussed before, the way that std.meta names things is inconsistent, and the pattern that lib.sys.meta is going with is that its templates will be CamelCased like types, which matches what some of std.meta does but not all of it.
> Add Map to lib.sys.meta.

- lib/sys/traits.d
Their behavior does differ slightly from that of their std.traits counterparts, because they are false for enums even when an enum's base type would match. std.traits is inconsistent with how it treats enums (e.g. isSomeString is false for them, because it was causing bugs with ranges for them to pass, but many of the other traits are true for enums), but unfortunately, this isn't something that we've been able to fix in std.traits (std.traits' isDynamicArray even mentions the problem in a comment in its documentation), since it would break exising code (in potentially very subtle ways no less).
I added a section to the module documentation explaining the reasoning for how lib.sys.traits handles enums and implicit conversions with the isXXX and hasXXX traits, which will hopefully not only …
> Add isDynamicArray and isStaticArray to lib.sys.traits.

- lib/sys/traits.d
This ports over isSomeString and isSomeChar from std.traits. isSomeString behaves the same (since the std.traits version doesn't accept enums), but the new isSomeChar is different in that the old one accepts enums, and this one rejects them. The new isSomeChar also has a simplified implementation, but the behavior is the same aside from how enums are treated.
The documentation and tests have been beefed up in the process, and I added a bit more to the documentation / tests for isDynamicArray and isStaticArray based on what came up with the tests for isSomeString and isSomeChar.
It is not my plan to port over any of the other traits in std.traits which are specifically for strings (e.g. isNarrowString), so checking string types with lib.sys.traits should be less confusing than it has been …
> Add isSomeString and isSomeChar to lib.sys.traits.

- lib/sys/traits.d
isInteger is similar to std.traits.isIntegral, but I went with a different name because it's specifically testing for the built-in integer types and not for all types which are even vaguely integral. It also helps distinguish from __traits(isIntegral, T) which accepts just about anything and its grandmother which is even vaguely integer-like / integral (to the point that I honestly question how much sense it makes to ever use it).
The main difference between isInteger and std.traits.isIntegral is that isIntegral accepts enums, whereas isInteger does not. isIntegral also theoretically accepts cent and ucent, but since it's now an error to use those, I don't think that it accepts them any longer in practice anyway. isInteger makes no attempt to accept them and does not accept their …
> Add isInteger and isFloatingPoint to lib.sys.traits.

- std/utf.d
It was brought up in the DLF meeting that the Unqual template is used so much, it consumes vast amounts of memory. Here is a trial of doing unqualification without a template.
> utf.d replace use of Unqual with cast()

- lib/sys/traits.d
isNumeric!T is equivalent to isInteger!T || isFloatingPoint!T, so I suppose that its value is somewhat questionable with how simple it is, but it does save a template instantiation in the process and arguably is clearer for documentation purposes.
There is an isNumeric in std.traits, but I would have to study it in detail to figure out exactly what it accepts, because it is written in a rather confusing manner (though it does clearly accept enums, which this isNumeric does not).
I have tried to make lib.sys.traits' isNumeric very clear in its documentation about what it accepts.
isPointer does exactly what it says on the tin, so it's quite straightforward all around.
I also beefed up the documentation on isDynamicArray to discuss a bit about dynamic arrays vs slices and why the kind of …
> Add isNumeric and isPointer.

- lib/sys/traits.d
Actually organizing all of the symbols within a file is pretty much a losing game in general, but I was trying to put the is* traits together and accidentally put some in the section containing Unconst, Unshared, and Unshared. So, this just moves Unconst and Unshared so that they're next to Unqual again.
There is zero code that's actually changed. It's just moved within the file.
> Rearrange some code in lib.sys.traits.

- phobos/sys/traits.d
They're similar to isSigned and isUnsigned from std.traits, but these new traits are far more restrictive, because they're only true for the four signed/unsigned built-in integer types, whereas isSigned and isUnsigned accept a bunch of different types (including floating point types and types that implicitly convert to real in the case of isSigned).
From what I've looked at in Phobos v2, most uses of isSigned and isUnsigned are used specifically when the code already knows that it's operating on integer types anyway, so these traits should work for most of those cases, and floating point types are always signed, so including them in a check for signedness seems kind of redundant. I suppose that isNumericSigned might make sense under some set of circumstances, since it would allow for a …
> Add isSignedInteger and isUnsignedInteger to phobos.sys.traits.

- phobos/sys/meta.d
They're the same as their std.meta counterparts, albeit with tweaked documentation and examples.
I also fixed the casing on Map's parameters. They're supposed to be types (or a template in the case of the template that it's applying to the other arguments), so they should be PascalCased.
> Add Filter and Reverse to phobos.sys.meta.

- phobos/sys/meta.d
- phobos/sys/traits.d
indexOf is phobos.sys.meta's version of std.meta's staticIndexOf.
The name was changed to better match our naming scheme. Because the result of the template is a value and not a type or AliasSeq, it is correct for it to be camelCased, but we don't normally prepend templates with static, making it inconsistent to do so in the case of indexOf.
This might result in some symbol conflicts with indexOf from the algorithm modules (assuming that we retain that function and its name for Phobos v3), but a quick test showed that importing both phobos.sys.meta and std.algorithm didn't result in a symbol conflict when using the one from phobos.sys.meta. And even if we do get symbol conflicts in some situations, the module system is designed to allow us to deal with that.
As for the implementation, …
> Add isSameSymbol and isSameType to v3 traits and indexOf to v3 meta.

- phobos/sys/meta.d
Stride is basically the same as std.meta's Stride aside from some improvements to the tests and documentation.
Uniq is the equivalent of std.meta's NoDuplicates except that it's been updated in the same fashion as indexOf. So, instead of checking for whether the elements are "the same" based on some complicated rules, Uniq takes a predicate which it uses to compare the elements for equality (essentially making it the AliasSeq equivalent of std.algorithm's uniq, though uniq requires that the range be sorted, and Uniq has no such requirement). So, the programmer can decide what kind of comparison is used.
> Add Stride and Uniq to phobos.sys.meta.

- std/traits.d
Mention that it accepts a function pointer/delegate type too.
Show opCall and function pointer in example.
> [std.traits] Improve FunctionTypeOf docs

- std/typecons.d
If there's a constructor that looks like a copy constructor except that it takes an rvalue instead of taking the argument by ref, then that type can't have a copy constructor, and one of Tuple's constructors was causing that problem. So, this fixes it so that it doesn't.
> Fix bugzilla #24465: Make Tuple work with copy constructors

- std/bitmanip.d
To unblock https://github.com/dlang/dmd/pull/16356
> Mark `endianToNativeImpl` `@trusted`

- phobos/sys/traits.d
EnumMembers is obviously needed and does the same thing as its std.traits counterpart.
isEqual is new, and it really shouldn't be used in many circumstances, but it's needed in conjunction with Unique to be able to do what NoDuplicates from std.meta does when given an AliasSeq of enum members. So, if you need the list of enum members to have no duplicate values (e.g. when creating a final switch), then you would now do Unique!(isEqual, EnumMembers!E) instead of NoDuplicates!(EnumMembers!E).
As part of isEqual's documentation, I added a list of examples which highlight the difference between operating on the list of enum members as an AliasSeq and operating on them as a dynamic array, since that's not something that's at all obvious - and it shows why you might need to use isEqual with …
> Add isEqual and EnumMembers to phobos.sys.traits.

- phobos/sys/meta.d
- phobos/sys/traits.d
This also makes it so that isImplicitlyConvertible and isQualifierConvertible in phobos.sys.traits can be partially instantiated, since I missed that before.
Instantiate is basically identical to the one in std.meta implementation-wise, but the documentation and unit tests have been improved.
ApplyLeft and ApplyRight should be functionally the same as their std.meta counterparts, but they have a simpler implementation than their std.meta counterparts (I'm pretty sure that the extra complexity in the old implementation is to work around built-in types not working with aliases, which was fixed a while ago). Of course, their documentation and tests have also been improved.
> Adds Instantiate, ApplyLeft, and ApplyRight to phobos.sys.meta.

- phobos/sys/traits.d
They're each the same as their std.traits counterparts, though the documentation and tests have been updated.
I considered renaming KeyType and ValueType to AAKeyType and AAValueType for increased clarity, but that seems pretty ugly, and while "value type" could mean other things depending on the context, I don't know what else it could mean in this context. So, I left the names the same.
> Add OriginalType, KeyType, and ValueType to phobos.sys.traits.

- std/path.d
See https://github.com/dlang/dmd/pull/16381.
> Fix ref foreach range variable

- std/net/isemail.d
See https://github.com/dlang/dmd/pull/16381.
> [std.net.isemail] Fix foreach ref index

- std/internal/math/biguintcore.d
> std.bigint: remove subSimple

- .github/workflows/main.yml
> Add DUB install to VM initialization.

- .github/workflows/main.yml
Reverts dlang/phobos#8992
PR failed to pass CI: https://github.com/dlang/phobos/actions/runs/8872619368
PR still failed to pass CI: https://github.com/dlang/phobos/actions/runs/8872685974
Got merged anyway and broke mainline CI: https://github.com/dlang/phobos/actions/runs/8872929782
Other: https://github.com/dlang/phobos/actions/runs/8873034066
PRs: https://github.com/dlang/phobos/actions/runs/8878962130
Started: https://github.com/dlang/phobos/actions/runs/8901425819
Failing: https://github.com/dlang/phobos/actions/runs/8942547120
> Revert "Add DUB install to VM initialization."

- Makefile
@thewilsonator @rikkimax 
Depends on this PR being merged: https://github.com/dlang/dmd/pull/16422
> Remove OMF flags from Makefile

- std/string.d
Blocking dmd PR dlang/dmd#16510
> fix goto skipping over declaration

- std/net/curl.d
Needed for https://github.com/dlang/dmd/pull/16583.
> Fix copying const(void)[] to void[]

- Makefile
In the Makefile.
https://issues.dlang.org/show_bug.cgi?id=24584#c2
> Improve docs for running a single unittest

- std/array.d
Depends on https://github.com/dlang/dmd/pull/16724
> Bugzilla 23300 - add testcase for std.array on scope InputRange

- std/experimental/allocator/common.d
For sample usage see
https://github.com/nordlow/phobos-next/blob/master/src/nxt/dynamic_array.d#L828
Also see discussion at https://forum.dlang.org/post/uiavxptceyxsjulkxlec@forum.dlang.org.
Depends on https://github.com/dlang/phobos/pull/8598.
> Add AllocatorState

- changelog/fromhexstring.dd
- std/digest/package.d
> Add fromHexString, fromHexStringAsRange and isHexString

- std/digest/package.d
- Optimizes `fromHexString` to no longer depend on `std.array.array`.
- A further optimization would be to use `.ptr` in the code – would downgrade the function to `@trusted` though.
- Adds a `length` property to the range – similar to the (defective-ish) one found in the original implementation by `@Tynukua`.
- Original from #8523 (value set by constructor that didn’t get updated by popFront)
<https://github.com/dlang/phobos/blob/fd8b2bedfd01a49e01cc2e350bb6063e9b37f113/std/digest/package.d#L1302>
- New adaption:
<https://github.com/dlang/phobos/blob/a26761827a9dad7fa7549478f9bc984715cb5ce5/std/digest/package.d#L1496-L1505>
> Optimize fromHexString()

- std/functional.d
Needed for https://github.com/dlang-community/D-Scanner/pull/964
> Fix linting issue in functional.d

- std/socket.d
Following https://github.com/dlang/dmd/pull/20665
> Fix reference to 'samples' folder

- .github/workflows/main.yml
After https://github.com/dlang/dmd/pull/20741.
> GHA main: Add Alpine Linux job, to CI-test musl libc

- std/process.d
> std.process: Fix memory corruption in exec functions

- std/algorithm/iteration.d
For resolved [bugzilla issue 15777](https://issues.dlang.org/show_bug.cgi?id=15777)
> Remove obsolete workaround

- std/file.d
Follow-up PR to #10667; a713259b7cbb1a9652ce5d7071e262362ddce7be is the relevant commit here.
> Cleanup `DirIteratorImpl.__ctor`

- std/conv.d
This adds an extended version of the unittests that I had written for #8251 to `std.conv`.
They aim at catching regressions early on.
The original patch from #8251 would pass its own testsuite just fine, yet was breaking other people’s code (caught by the buildkite tests). I think it would be preferable to be able to detect such breakages on our own.
> Add additional tests to `std.conv`

- std/complex.d
implemented new abs function for small arguments
> Fix issue #10491 Complex!float.abs / hypot invalid result when argument is small

- std/algorithm/iteration.d
This makes it easier to follow the docs.
Move 2 documented unittests under isTerminator overload. 
Tweak isWhite example to use `\t`, not just a single space.
> [std.algorithm] Separate docs for `splitter` overload with isTerminator parameter

- std/algorithm/iteration.d
Update splitter cheat sheet for non-separator overloads. Add constraint for splitWhen's `pred`.
Use Markdown list for 'See Also'.
`splitter!isTerminator` always returns a forward range.
> [std.algorithm.iteration] Tweak splitter, splitWhen docs

- std/algorithm/searching.d
For a single needle, it only requires an input range. 
Document `needle` parameter.
Explain pseudo-tuple returned, extend example.
Split out docs for unary `pred` overload.
> [std.algorithm.searching] Improve `countUntil` docs

- std/array.d
This reverts commit https://github.com/dlang/phobos/commit/bea318447955ab49df765212505d4e2e10294e74.
Adds unittest for #10747.
Closes: #10747
Closes: #10764
> [stable] Revert "Add low-overhead `InPlaceAppender` (#8789)"

- CONTRIBUTING.md
Added a link to a YouTube tutorial to help new contributors set up the D compiler and Phobos development environment.
> docs: Add video tutorial link to CONTRIBUTING.md

- std/datetime/timezone.d
> std.datetime.timezone: Respect the TZDIR environment variable

- std/string.d
See issue #10506 
This PR at least documents what the code currently does.  Enhancements to be done in the future if we deem it necessary.
> Issue 10506: document how columns are counted in std.string.wrap.

- std/random.d
What to do with the false positives at https://buildkite.com/dlang/phobos/builds/9870/steps/canvas?sid=0198f4c9-00cd-4506-a6a8-3763c8d1fb39#0198f4cf-f270-44a6-8ede-1c2337596996/240-378?
> Replace templates with templated enums in std/random.d
