dlang/phobos

- std/experimental/logger/nulllogger.d
- std/file.d
- std/range/package.d
- std/socket.d
This is part 2 of #6048 and is currently blocking : dlang/dmd#7760 because deprecations are treated as errors.
> Fix erroneous imports in unittests

- std/traits.d
This conserves memory, since isDesiredUDA instances can be reused between symbols. Usually we want to check a large number of symbols against a small number of possible attributes. With this change, isDesiredUDA only depends on the number of attributes, not spuriously on the symbol they appear on.
In a large project, this brought compiler memory usage from 8.2GB to 7.3GB.
> std.traits: move isDesiredUDA out of getUDAs, since it depends only on attribute and uda.

- std/digest/crc.d
- std/digest/md.d
- std/digest/ripemd.d
- std/digest/sha.d
Basically `s/x"/hexString!"/`
Required for the deprecation of hexstrings.
Revival of https://github.com/dlang/phobos/pull/5507
> Replace deprecated hexstrings with std.conv.hexString

- changelog/toString.dd
- std/format.d
This proposal
* Modifies `std.format` to recognize any `toString` that accepts a character accepting output range as having a valid `toString` overload
* Modifies `std.format` to prioritize and use the output range method when formatting aggregate types if it exists
* De-emphasizes the `scope delegate` `toString` methods in the docs
Firstly, speed. [According to Walter](https://issues.dlang.org/show_bug.cgi?id=9785#c3), the delegate passed as a parameter can never be in-lined because of how DMD does data flow analysis. Using instead the defined `put` method of an output range would solve that problem.
Secondly, the vision of Phobos.  Ranges are the present and the future. Output ranges really need more support in Phobos (std.conv).
Thirdly, safety. The vast majority of the code I've seen …
> [RFC] Make Output Ranges Using Methods The Preferred toString Option

- changelog/std-algorithm-searching-findSplit.dd
- std/algorithm/searching.d
- std/traits.d
Split-up from https://github.com/dlang/phobos/pull/5962
Motivation: Named tuples are a lot better to read.
There has been a precedent for this, see #5436
> findSplit: return named tuples instead of an anonymous tuple

- std/experimental/allocator/building_blocks/ascending_page_allocator.d
Follow-up to https://github.com/dlang/phobos/pull/6006/files#r160067505
Note that the module title is too long for the menu atm.
CC @Darredevil
BTW why don't we put everything into a `building_blocks.d` file like it's
done for all the other Phobos modules?
> Expose AscendingPageAllocator on dlang.org

- std/algorithm/comparison.d
Right now when comparing non-string ranges std.algorithm.comparison.cmp calls the comparison predicate twice for every pair of elements to determine their order. When the elements have overloaded `opCmp` and the predicate is "a < b" we only need to call `opCmp` once for each pair.
> Fix Issue 18280 - std.algorithm.comparison.cmp for non-strings should call opCmp only once per item pair

- std/bigint.d
- std/internal/math/biguintcore.d
This allows to declare very big BigInt constants but has the same limitation as x86_64 BigInt CTFE.
> fix issue 14767 - Support CTFE of BigInt under x86

- std/concurrency.d
I believe the second `atomicLoad` in this double-checked lock is unnecessary.
> Removed unnecessary atomicLoad inside initOnce

- std/datetime/date.d
Removed explicit auto-decoding and simplified/speed up  format checking.
Previous PRs: https://github.com/dlang/phobos/pull/5550 https://github.com/dlang/phobos/pull/5404 https://github.com/dlang/phobos/pull/5413
Results:
```
old	6 secs, 425 ms, 378 μs, and 3 hnsecs
new	809 ms, 503 μs, and 6 hnsecs
old	12 secs, 946 ms, 437 μs, and 4 hnsecs
new	2 secs, 325 ms, 651 μs, and 9 hnsecs
```
Code
```d
enum testCount = 20_000_000;
Date fromISOExtString1(S)(in S isoExtString) @safe pure
if (isSomeString!(S))
{
import std.algorithm.searching : all, startsWith;
import …
```
> Optimized std.datetime.date.Date.fromISOExtString

- std/datetime/date.d
Using the `toString` format from https://github.com/dlang/phobos/pull/5991, update `Date`'s string methods to accept output ranges.
> Partially Fix Issue 10828 - Add output range version of toString functions to std.datetime.Date

- changelog/std-bigint-getDigit.dd
- std/bigint.d
- std/internal/math/biguintcore.d
Get the elements of the underlying representation. This would also be useful in my `stdxdecimal` library.
> Fix Issue 17249: Added BigInt.getDigit

- posix.mak
See also:
- https://github.com/dlang-community/D-Scanner/pull/549 fix for DScanner
- https://github.com/dlang-community/D-Scanner/pull/550 (update PR for the `phobos` branch)
- https://github.com/dlang/dmd/pull/7766 (compiler fix + origin of the failures)
> Update DScanner to 6ba40537532fd795e83db0a7c8609512decdefc5

- changelog/std-algorithm-iteration-substitute.dd
- std/algorithm/iteration.d
- std/algorithm/package.d
- std/array.d
- std/range/package.d
- std/string.d
As I realized in https://github.com/dlang/phobos/pull/5565 that Phobos has no way to have a lazy range of replacements, I ported @nordlow's `substitute` from [phobos-next](https://github.com/nordlow/phobos-next/blob/1992896e945111aa3f47eb94a42dcc57be4cc61b/src/substitution.d).
`substitute` allows lazy replacements:
--------------------------------------------------
```d
import std.algorithm.comparison : equal;
import std.algorithm.searching : substitute;
// substitute single elements
assert("do_it".substitute('_', ' ').equal("do it"));
// substitute multiple, single elements
assert("do_it".substitute('_', ' ',
'd', 'g',
'i', 't',
't', 'o')
.equal("go to"));
// substitute subranges
assert("do_it".substitute("_", " ",
"do", "done")
.equal("done it"));
// substitution works for any …
```
> Add substitute for lazy replacements

- std/datetime/date.d
Results:
```
old	8 secs, 786 ms, 105 μs, and 7 hnsecs
new	997 ms, 166 μs, and 6 hnsecs
old	18 secs, 190 ms, 732 μs, and 1 hnsec
new	2 secs, 646 ms, 737 μs, and 2 hnsecs
```
See https://github.com/dlang/phobos/pull/6062 for earlier examples of this type of PR
Benchmark code:
```d
import std.utf;
enum testCount = 20_000_000;
Date fromSimpleString1(S)(in S simpleString) @safe pure
if (isSomeString!(S))
{
import std.algorithm.searching : all, startsWith;
import std.ascii : isDigit;
import std.exception : …
```
> Optimized std.datetime.date.Date.fromSimpleString

- std/datetime/date.d
`DateTime`'s from string methods use `countUntil` in order to check for the seperator between
the date and the time strings. This is fine until the result is used to slice the original
string, which can cause incorrect results. This is due to the problem that `countUntil` gives
the number of code points until the Needle and not the number of code units, which is the
how it's sliced.
Normally this doesn't actually pose a problem because actual time strings only contain ASCII
characters, but this does fix two things
1. No more auto decoding in the function, so it's faster
2. Better error messages if there are non-ASCII characters in the string because the break-up is correct
> Fix Auto-Decoding Issue With DateTime From String Methods

- std/datetime/date.d
See #5991 and https://github.com/dlang/phobos/pull/6060 for more details
> Work On Issue 10828 - Add output range versions of toString functions to std.datetime.TimeOfDay

- changelog/std-range-nullsink.dd
- std/range/package.d
`nullSink` returns the `NullSink` by reference and thus allows using it
directly in code which expects an OutputRange by reference.
The pattern is providing convenience wrappers for struct construction is
very common in Phobos, e.g. `rebindable`, `nullable`, `refCounted`, ...
> std.range.nullSink - allow convenient use of the NullSink

- std/string.d
This fixes it so that when types that implicitly convert to string are used with `splitLines`, `lineSplitter`, and `indexOf`, the implicit conversion is done at the call site so that we don't run into safety issues related to the conversion occurring inside the function (e.g. slicing a static array and thus returning a slice of local stack memory).
> Fix safety issues with splitLines, lineSplitter, and indexOf

- std/format.d
This is not an important fix. It allows to stop compiling before the linker failure happening when an aggregate has its `to string` marked with `@disable`, so very unlikely to happen, ever. However since i managed to get the new trait accepted in the language, here is an example of usage.
Funnily enough the fix is impossible to test, see the note in the unittest.
> fix issue 11747 - Better error message with @disabled toString

- std/traits.d
I should have added this warning months ago, but here it is. Hopefully, it won't take all that long to remove uses of `isConvertibleToString` from Phobos so that we can deprecate it, but it is unfortunately used in a number of places, so it will take several PRs to remove them - especially if they sit and rot like my previous PRs for removing uses of `isConvertibleToString` sat and rotted.
> Add warning to isConvertibleToString.

- std/path.d
The documentation currently says "Returns the directory part of a path." That is incorrect, because it actually returns the parent directory no matter what the argument `path` is (even if `path` is a directory).
https://issues.dlang.org/show_bug.cgi?id=18294
> Fix documentation for std.path.dirName

- std/path.d
This fixes it so that when types that implicitly convert to string are used with `driveName`, `stripDrive`, or `rootName` in std.path, the implicit conversion is done at the call site so that we don't run into safety issues related to the conversion occurring inside the function (e.g. slicing a static array and thus returning a slice of local stack memory).
> Fix safety issues with driveName, stripDrive, and rootName

- std/random.d
Random choice default argument was deciding the type of the
template. I'm not sure if this is a deeper bug, but it can easily be
fixed with this patch which simply overloads the function.
Also added a unittest which would have failed under the old code.
> Fix Issue 17832 - std.random.choice cannot be used with other random generators

- std/path.d
Using `isConvertibleToString` is unsafe, because it results in the conversion being done inside the function instead of at the call site, which means that if the string escapes, it's invalid. The only way to make the conversion happen at the call site is for the function to explicitly accept an array. As such, we need to deprecate `isConvertibleToString`, but first, we need to remove uses of it from Phobos.
> Remove more uses of isConvertibleToString from std.path

- std/exception.d
Note that these examples are _not_ verified, but the `RUNNABLE_EXAMPLES` macro will just lead to the edit and run button showing up.
Though in a future version one could search for all these in-text examples and verify them too (like we recently started to do in the spec with `SPEC_RUNNABLE_EXAMPLE`) - though in general we should just think about how we can avoid having them in the first place. In this case the reason is to allow a flow of explanation + examples.
> Runnable examples std exception

- std/datetime/timezone.d
- std/digest/murmurhash.d
- std/math.d
Pinging @klickverbot and @ibuclaw.
> Upstream some LDC patches

- std/algorithm/searching.d
Uses an ugly string comparison to check for the default predicate.
> Fix Issue 18329 - std.algorithm.startsWith & endsWith can sometimes statically determine decoding unnecessary

- changelog/std-bigint-divmod.dd
- std/bigint.d
- std/internal/math/biguintcore.d
Made `divMod` accessible for `BigInt`. The function already exists in biguintcore, but is not publicly accessible.
> Fix Issue 18086 - BigInt DivMod

- std/algorithm/searching.d
I'm not sold on this function's usefulness, but fixing auto-decoding is simple so we might as well.
```
0
old		4 secs, 968 ms, 536 μs, and 6 hnsecs
new		1 sec, 988 ms, and 715 μs
0
old		16 secs, 874 ms, 710 μs, and 5 hnsecs
new		6 secs, 49 ms, 780 μs, and 8 hnsecs
```
```d
import std.utf;
import std.random;
enum testCount = 100_000_000;
__gshared a = "1 + (2 * (3 + 1 / 2)";
bool balancedParens1(Range, E)(Range r, E lPar, E rPar,
size_t maxNestingLevel = size_t.max)
if (isInputRange!(Range) && is(typeof(r.front == lPar)))
{ …
```
> Removed auto-decoding from std.algorithm.searching.balancedParens

- .circleci/run.sh
I can't reproduce the failures locally, so I assume bumping is the easiest
course of action.
> Bump CircleCi to 2.078.1

- std/stdio.d
* Removed code that did extra work by decoding `wstring`s to `dchar`s, and then encoding them to `char`s. Or in the case of writing `wstring` to a wide file, `put` no long has to do any encoding or decoding at all, where as it did a bunch of extra work before.
* Made the `wchar` path throw a UTF exception on bad data
* Improved the docs for LockingTextWriter
> Modified the behavior of std.stdio.LockingTextWriter.put

- std/algorithm/comparison.d
- std/algorithm/mutation.d
- std/algorithm/sorting.d
- std/range/package.d
There's no reason and benefit to link to C++ in our standard library exception for a few
special cases (e.g. saying that this function behaves like XYZ in another language
for better searchability).
See also: dlang/dlang.org#2103
> Remove references to STL

- std/traits.d
The example extractor adds the module import to the top of the tests, so these removed imports were redundant
> Removed Extra Imports From std.traits Examples

- std/traits.d
Having isSomeString and isNarrowString be true for enums whose base type
is a string type is a problem, because the enums will not work with the
same code that strings will, resulting either in compilation errors or
subtle bugs which result in variables of an enum type that contain
values that are not members of that enum type. As with other types that
implicitly convert to a string type, the enums need to be converted to
be used with the code that's designed for strings, which happens when
the function explicitly takes a string type or when the function takes
an array and is templated on the character/element type but does not
happen when the function is templated on the whole parameter type.
In addition to fixing isSomeString and isNarrowString for enums, these
changes catch and fix the …
> Fix it so that isSomeString and isNarrowString are false for enums.

- std/datetime/timezone.d
Results
```
old 2 secs, 411 ms, 644 μs, and 6 hnsecs
new 858 ms, 177 μs, and 6 hnsecs
old 4 secs, 936 ms, 985 μs, and 5 hnsecs
new 1 sec, 536 ms, 176 μs, and 1 hnsec
```
code
```d
import std.utf;
enum testCount = 10_000_000;
__gshared a = "+01:30";
immutable(SimpleTimeZone) fromISOExtString1(S)(S isoExtString) @safe pure
if (isSomeString!S)
{
import std.algorithm.searching : startsWith, countUntil, all;
import std.ascii : isDigit;
import std.exception : enforce;
import std.format : format;
auto dstr = …
```
> Optimized std.datetime.timezone.SimpleTimeZone.fromISOExtString

- changelog/std-string-strip.dd
- std/string.d
Added second argument similar to Python `str.strip`
Second argument accepts list of chars to strip and strips only
those chars.
Examples:
"xyzhello".stripLeft("xyz") == ""hello"
"helloxy ".stripRight("xy ") == "hello"
"xhellox".strip("x") == "hello"
Signed-off-by: Aravinda VK <mail@aravindavk.in>
> Fix issue 13632: Enhancement to std.string.strip

- std/algorithm/mutation.d
- std/algorithm/searching.d
From https://forum.dlang.org/post/spytixhkojgrsbdlgtmy@forum.dlang.org
> Note to self: learn to scroll down in the docs to find other definitions. I was convinced that remove only acted on indices :p
I also took the opportunity to improve the docs in std.algorithm.searching slightly.
Documentation of std.algorithm
------------------------------
BTW in general while I think std.algorithm is one of the best modules in Phobos,
I don't like it's churned with so many redundant symbols - a quick list:
- min, minElement, minIndex, minPos
- find, findAdjacent, findAmong, findSkip, findSplit, findSplitBefore, findSplitAfter
- levenshteinDistance, levenshteinDistanceAndPath
- move, moveAll, moveEmplaceAll, moveSome, moveEmplaceSome
- largestPartialIntersection, largestPartialIntersectionWeighted
- …
> Group documentation in std.algorithm

- std/net/curl.d
The real download can be found in the directory `other` of the *Release Archive*. It wasn't really straight forward to just link the general download page. A link to the archive can be found on the dl page, though.
(Usually people don't like to play hide and seek while coding 🙈)
> @0xNiklas on Discord:
>> well there is no download ^^
>> or i am blind
> Update win32 libcurl link

- std/range/package.d
It's pretty empty here at the moment: https://dlang.org/phobos-prerelease/std_range.html#slide
FWIW Ddox doesn't have this bug: https://dlang.org/library-prerelease/std/range/slide.html
> Move public examples of slides, s.t. they can be detected by ddoc

- std/net/curl.d
Allows avoiding importing std.concurrency unless asynchronous functionality actually needed.
Improves impact on import time by about 15%.
https://github.com/dlang/phobos/pull/5916#issuecomment-362900099
> std.net.curl: Move asynchronous stuff to lazily-instantiated namespace

- .codecov.yml
There are still many parts of Phobos which have a low coverage. Touching them shouldn't make a PR fail.
Example from: https://github.com/dlang/phobos/pull/6041#issuecomment-362899073
> 50% of diff hit (target 90.369%)
> Use informational:true for CodeCov

- std/exception.d
Ddoc replaces `__FILE__` and `__LINE__` - even in the documentation build.
In think, the best course of action here, is to do the same other functions
in this module do and use `string.init` and `size_of.init`
Current function: https://dlang.org/phobos/std_exception.html#enforceEx
This was discovered while working on the assert/rewrite pipeline:
https://github.com/dlang/dlang.org/pull/2069#issuecomment-363154934
(Ddox doesn't show this, I just filed the issue - https://github.com/rejectedsoftware/ddox/issues/197)
> Fix Ddoc template execution bug

- changelog/std-exception-enforce.dd
- std/exception.d
- std/format.d
- std/json.d
- std/process.d
Follow-up to https://github.com/dlang/phobos/pull/5234 and https://github.com/dlang/phobos/pull/6080.
tl;dr summary
> However, if enforce can't fully replace enforceEx, then it needs to stick around for at least one more release so that we can have a release where enforce can fully replace enforceEx. That way, someone can build their code with both the latest release and master without getting a bunch of deprecation messages. And clearly, from how enforceEx is being used in Phobos, enforce needs to be improved first. So, please create a PR to improve enforce, and then we can deprecate enforceEx after the improved enforce has been put out in a release.
I already added the warning in the documentation and removed `enforceEx` from the bookmark summary at the top.
> Turn enforce into an eponymous template + undocument enforceEx

- std/file.d
cf FORUM: dirEntries returns relative, not absolute paths
> fix doc inaccuracy in dirEntries

- std/math.d
last fix was incomplete. abs didn't handle type constructors yet.
> fix issue 18349 - std/math.d(543,33): Deprecation: integral promotion not done for -x

- std/process.d
The REF1 macro should have been used here instead.
See also: https://github.com/dlang/dlang.org/pull/2191
edit: also fixed a few typos while I was at it.
> Use REF1 macro instead of OBJECTREF

- std/datetime/stopwatch.d
Someone using `std.datetime.stopwatch` probably wants to use it to obtain a time in milliseconds or some other unit of time but none of the example code shows how to do this.
Proposed addition:
```d
/// Measure a time in milliseconds, microseconds, or nanoseconds
@safe nothrow @nogc unittest
{
auto sw = StopWatch(AutoStart.no);
sw.start();
// ... Insert operations to be timed here ...
sw.stop();
long msecs = sw.peek.total!"msecs";
long usecs = sw.peek.total!"usecs";
long nsecs = sw.peek.total!"nsecs";
assert(usecs >= msecs * 1000);
assert(nsecs >= usecs * 1000);
}
```
> Issue 18398 - std.datetime.stopwatch documented examples could be better

- std/math.d
- std/net/curl.d
This is required for https://github.com/dlang/dmd/pull/7834
The uses of `_` has been wrong in both cases.
CC @quickfur
> Remove use of undefined ddoc macros from Phobos

- changelog/std-experimental-scripting.dd
- posix.mak
- std/experimental/scripting.d
- win32.mak
- win64.mak
So after I have been thinking about this for quite a while, I realized that I am almost weekly in a case where `import std` would make my life easier. 
Other reasons include:
- Very convenient for short scripts, REPLs and things like run.dlang.io
- Promotes and test the idiom of paying for what you use
- Phobos is usually almost entirely parsed anyways
- A good use case for making imports even more lazily and maybe pushing [DIP1005](https://github.com/dlang/DIPs/blob/master/DIPs/DIP1005.md) forward
- It doesn't hurt/cost anything for people who don't like this
For now I didn't add this file to the documentation build.
Also I didn't include `std.experimental`.
> Add a global convenience package file

- std/algorithm/iteration.d
`cumulativeFold` has been added in 2.072. Let's close the issue by mentioning alternative names, s.t. people can find it easily via Google.
> Fix Issue 11084 - Mention scan in cumulativeFold

- std/algorithm/iteration.d
The implementation already was partially there.
Has anyone a memory why it wasn't enabled?
> Issue 8166 - remove dead _backLength code in std.algorithm.splitter

- std/datetime/stopwatch.d
Revision of https://github.com/dlang/phobos/pull/6139 which isn't showing up due to a ddoc bug documented in [Issue 16992](https://issues.dlang.org/show_bug.cgi?id=16992):
>A workaround would be to set the example as module-level, documented unittest.
> Issue 18398 - std.datetime.stopwatch documented examples could be better (x2)

- posix.mak
We cannot assume the name of the makefile processor has to be 'make', for example on freebsd, gnu make is called gmake.
> [Trivial] Should use '$(MAKE)' instead of 'make', inside posix.mak Makefile

- posix.mak
- std/algorithm/comparison.d
- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/bigint.d
- std/datetime/systime.d
- std/digest/sha.d
- std/exception.d
- std/experimental/allocator/package.d
- std/experimental/scripting.d
- std/format.d
- std/math.d
- std/net/curl.d
- std/range/package.d
- std/regex/package.d
- std/string.d
- std/traits.d
- std/typecons.d
tl;dr: DScanner started to segfaulted in December due to the introduction of the AscendingPageAllocator, which used `~this(){}`. The DScanner bug has been fixed and now we can fix the DScanner warnings that sneaked in and re-enable in.
See also: https://github.com/dlang/phobos/pull/6148
> Fix all DScanner warnings + use -return-exit-code re-enable it

- std/net/isemail.d
Solution is to remove regex from std.net.isemail. May be worth revisiting if std.regex compile times improve. On my machine making the change decreased the time measured by [@wilzbach's import benchmark script](https://gist.github.com/wilzbach/afb9f2edec8ddfabfdd6becec55e62a7) from 0.15 seconds to 0.03 seconds (consistently over repeated trials).
[Link to mention of this issue on the forums.](https://forum.dlang.org/post/qltouuhsxsqltpspuhye@forum.dlang.org)
> Fix Issue 18384 - std.net.isemail is slow to import due to regex

- std/net/isemail.d
Urgh so it looks like due to the fact that DScanner was disabled for two months many PRs are still green, but never actually ran DScanner.
In this case it was https://github.com/dlang/phobos/pull/6129
```
std/net/isemail.d(1869:1)[warn]: same visibility attribute used as defined on line 1713.
std/net/isemail.d(1897:1)[warn]: same visibility attribute used as defined on line 1713.
```
> Fix DScanner - same visibility attribute used as defined on line 1713

- changelog/std-file-readText.dd
- std/file.d
This makes it so that readText checks for a BOM. If there is a BOM, it
is for UTF-8, UTF-16, or UTF-32, and it doesn't match the requested
string type, then a UTFException is thrown. Other encodings are let
through in case they happen to work with the requested string type and
pass UTF validation.
Also, this makes it so that readText checks the alignment of the buffer
against the requested string type and throws a UTFException instead of
letting the cast throw an Error.
> Fix issue 15949: Make readText check BOMs.

- std/bitmanip.d
Calls to std.stdio.writefln!(char, string) in std/bitmanip.d within @safe unittest{...}, when compiled with -dip1000 via make -f posix.mak std/bitmanip.test,
raise following error (for some yet unknown reason not with switch -dip25):
Error: @safe function std.bitmanip.__unittest_L2427_C7 cannot call @system function std.stdio.writefln!(char, string).writefln
Thus the fix trivially replaces writefln by writeln.
> std.bitmanip.d - fix a -dip1000 compilable issue; trivial

- std/datetime/systime.d
```
old		12 secs, 875 ms, 52 μs, and 1 hnsec
new		6 secs, 374 ms, 348 μs, and 1 hnsec
```
code
<details>
```d
import std.exception;
import std.typecons;
import std.datetime.systime;
import core.time;
import std.random;
enum testCount = 5_000_000;
__gshared a = "2013-02-07T04:39:37.000050392";
SysTime fromISOExtString1(S)(in S isoExtString, immutable TimeZone tz = null) @safe
if (isSomeString!(S))
{
import std.algorithm.searching : countUntil, find;
import std.string : strip;
auto dstr = to!dstring(strip(isoExtString));
auto tIndex = dstr.countUntil('T');
enforce(tIndex != …
```
> Optimized std.datetime.systime.SysTime.fromISOExtString

- std/datetime/systime.d
The writer overload is needed for the future writer overload of systime's tostring overloads.
While I was working on it I realized I could make it faster by not using format.
```
.0009999
old		1 sec, 305 ms, 137 μs, and 9 hnsecs
new		749 ms, 261 μs, and 8 hnsecs
```
<details>
```d
import std.exception;
import std.typecons;
import std.datetime.systime;
import core.time;
import std.random;
enum testCount = 5_000_000;
auto fracSecsToISOString1(int hnsecs) @safe pure nothrow
{
assert(hnsecs >= 0);
try
{
if (hnsecs == 0)
return "";
string isoString = format(".%07d", …
```
> Optimized fracSecsToISOString and added writer overload

- std/experimental/allocator/package.d
Since this [PR](https://github.com/dlang/dmd/pull/7874) has been merged, this PR also defines `RCISharedAllocator` as a `shared struct`
> Mark @safe ctor, postblit and opAssign for RCAllocator

- std/regex/internal/ir.d
This fixes the unittests for LDC on ARM (with enabled optimizations).
The code used to store a class instance (whose size isn't padded) right before some buffer, without any padding inbetween. The buffer is thus susceptible to misalignment; e.g., `BacktrackingMatcher.dupTo()` casts the buffer from `void[]` to `size_t[]` (in `initExternalMemory()`), simply assuming an alignment >= `size_t.alignof`, which only holds if the prepended class instance size is a multiple of that (as `malloc()` returns a sufficiently aligned block already in this case).
> std.regex: Alignment hotfix

- std/numeric.d
The special cases of `gcd(0,a)` and `gcd(a,0)` are not handled correctly when `BigInt`s are involved.
(Note: see the overload of `gcd` that handles built-in ints to see the same special cases handled.)
> Fix issue 18434: gcd(BigInt(0), BigInt(1)) fails

- std/typecons.d
Motivation: https://dlang.org/phobos/std_typecons.html#BitFlags
The idea:
- present examples in small chunks, s.t. a reader doesn't need to study 79 lines (!) to grasp the context
- explain _one_ feature per example
- order examples in chronical order (e.g. first introduce `&`, then use it)
This doesn't aim to be perfect, but better than the existing documentation.
Other remarks: Most variable names here use the non DStyle snake_case, e.g. `flags_empty` or `flags_AB`.
I left renaming them to another PR as this PR is purely focussed on reorganizing the content to be better digestable.
> Make examples of BitFields more digestable for a reader

- std/datetime/timezone.d
A call to std.stdio.writefln!(char, string) in std/datetime/timezone.d within @safe unittest{...}, when compiled with -dip1000 via make -f posix.mak std/datetime/timezone.test,
raises following error (for some yet unknown reason not with switch -dip25):
std/datetime/timezone.d(552): Error: [manually/temporarily attributed @safe] function std.datetime.timezone.TimeZone.__unittest_L546_C22.testPZSuccess cannot call @system function std.stdio.writefln!(char, string).writefln
Thus the fix trivially replaces writefln by writeln.
> std.datetime.timezone - fix a -dip1000 compilable issue; trivial

- std/datetime/systime.d
This fixes a few
Error: reference to local variable ... assigned to non-scope parameter this
The only remaining issue in this module is with
Error: @safe function std.datetime.systime.....__unittest_... cannot call @system function std.stdio.writefln
> std.datetime.systime - fix a -dip1000 compilable issue; trivial

- std/algorithm/iteration.d
- std/array.d
I used the opportunity to reorder the examples of `splitter` too and as they are public examples I converted them to DStyle (UFCS, ~~~no string lambdas~~~).
edit: seems like `splitter` has frame access problems with normal lambdas, so I reverted the string lambda -> lambda for now and opened [18470](https://issues.dlang.org/show_bug.cgi?id=18470) for now.
> Fix Issue 18341 - Documentation for std.array.split is confusing/incorrect

- std/typecons.d
Also deprecates the delegate versions because
1. they're slower most of the time due to the inability to inline the delegate
2. they were already undocumented
3. they're rarely directly called by the user, and instead are called by things like `to!string`, which now automatically call the new overload.
> Added writer version of toString to Nullable

- std/exception.d
Note this isn't ideal yet, because `enforce` will be displayed after the the following two overloads but it already improves the status quo and for now I don't have good ideas that can be easily done.
> Expose the enforce overload on the docs

- std/experimental/allocator/building_blocks/region.d
- std/socket.d
- std/stdio.d
Only one assert trips when running the Phobos tests after this patch, [this one in `std.datetime.timezone`](https://github.com/dlang/phobos/blob/master/std/datetime/timezone.d#L781), but I don't know if that's because of the bare minimum install of Alpine I'm testing in or if it needs to be addressed. @yshui, what do you say?
> Add needed changes to get all tests passing with Musl

- std/regex/internal/backtracking.d
- std/regex/internal/ir.d
- std/regex/internal/thompson.d
- std/regex/package.d
- reduce copying of fat structs
- optimize layouts and opAssign of Captures
WIP: still need to figure out how to best handle ref passing of ctRegex
> fix Issue 18114 - regex performance regression

- std/math.d
Reverts dlang/phobos#6040
This seemingly breaks a fair amount of user code, so we should revert it until we can figure out a less intrusive fix.
https://issues.dlang.org/show_bug.cgi?id=18287
https://issues.dlang.org/show_bug.cgi?id=18473
Not sure if this is jumping the gun, but better safe than sorry.
> Revert "Issue 18244: std.math generic functions need to have sig constraints"

- std/meta.d
* Replace uses of *list* with *sequence*.
* `S[n]` is not the nth element (due to zero based indexing).
* Add links, formatting.
> [trivial] Tweak `std.meta` docs

- changelog/std-experimental-all.dd
- posix.mak
- std/experimental/all.d
- win32.mak
- win64.mak
I just tried to explain this to someone as he was confused by `scripting`.
`scripting` was used because it was the first name suggested by @andralex, but while I don't hope that this will stay in `experimental` for too long, it's probably a good idea to use `all` is it will immediately tell every reader what's going on. `scripting` is rather vague.
Credits: this has been suggested by @carun here https://github.com/dlang/phobos/pull/5916#discussion_r167300850
I know the name doesn't matter too much and we ideally can use `import std` soon, but it was a quick five minute change and will hopefully lead to less confusion.
See also: https://github.com/dlang/phobos/pull/5916 (PR that introduced `std.experimental.scripting`)
> Renaming the upcoming global import file to std.experimental.all

- std/complex.d
I'm seeing a diff in the last mantissa bit for the imaginary parts with LDC on Win64 and its 64-bit reals.
> std.complex: Minimally relax unittest for 64-bit reals

- changelog/bitflags-property-opdispatch.dd
- std/typecons.d
- allows for less brittle flag test
(`flags.featureX` vs. `(flags & FlagsEnum.featureX)`)
- allows for simpler testing of combined (unsafe) flags
(`flags.combined` vs.
`(flags & FlagsEnum.combined) == BitFlags!(FlagsEnum, Yes.unsafe)(FlagsEnum.combined)`)
> add opDispatch-based test to BitFlags enum

- std/exception.d
It didn't compile (see https://github.com/dlang/phobos/pull/6080).
- converted to a module unittest
- fixed the example, s.t. it compiles
- made it to a full synposis by adding more cool functions from `std.exception`
> Rewrite synopsis example of std.exception

- std/format.d
So trying to make `Object.toString` const was a nightmare, so I added in this work-around to at least allow the code to compile.
> Fix Issue 7879 - format of const class with non const toString()

- win64.mak
They have been disabled by https://github.com/dlang/phobos/pull/5927
> reenable unittests for Win64

- std/net/curl.d
See also: https://github.com/braddr/d-tester/issues/70#issuecomment-368670639
I'm aware that this isn't ideal and `StdUnittest` would be better suited for this, but it keeps the diff small and `std.net.curl` is broken on FreeBSD 32-bit anyhow.
Moreover, I have the opinion that we should just drop the support for legacy platforms that almost no one actively uses, but well that's a different story.
> Temporarily disable curl tests for FreeBSD 32-bit

- std/net/curl.d
Cherry-pick https://github.com/dlang/phobos/pull/6232 to `stable`, s.t. auto-tester will pass on stable too.
Note this will fail on auto-tester as it requires https://github.com/dlang/dmd/pull/7970 first.
See also: https://github.com/braddr/d-tester/issues/70
> [stable] Temporarily disable curl tests for FreeBSD 32-bit

- std/typecons.d
It is need to avoid silent conversion of Typedef struct itself to string by std.conv.to.
Discussion:
https://forum.dlang.org/post/kjzayldqnixehfprgslc@forum.dlang.org
Previous attempt: #6217
> Adds Typedef.toString()

- std/experimental/allocator/mallocator.d
See https://github.com/ldc-developers/phobos/pull/58
With ASan enabled, posix_memalign returns -1 upon invalid parameters or when not enough memory is available. This bug is reported with compiler-rt here: https://bugs.llvm.org/show_bug.cgi?id=36510
Still, if we deal with the invalid -1 return value in Phobos, we can continue testing with ASan enabled.
It looks like this workaround is only needed on OSX.
@andralex
> [ASan] Handle the (invalid) return value of posix_memalign

- std/random.d
When using a factory function as initializer this saves one line:
```d
auto r = factory();
randomShuffle(r);
```
vs
```d
auto r = randomShuffle(factory());
```
Surprisingly, The `return` were already there but did nothing because of the `void`.
> fix issue 18501 - randomShuffle and partialShuffle should return their input argument

- std/array.d
benchmark:
```d
unittest
{
import std.stdio, std.datetime.stopwatch;
auto str = "a bb ccc dddd eeee fff gg h i jj kkk llll mmmm nnn oo p q rr sss tttt uuuu vvv ww x y zz";
void use_an_array() { auto ret = split(str); }
void use_an_appender() { auto ret = split2(str); }
auto r = benchmark!(use_an_array, use_an_appender)(1_000_000);
writefln("use_an_array: %s", r[0]);
writefln("use_an_appender: %s", r[1]);
}
```
output:
```
use_an_array: 4 secs, 343 ms, 762 μs, and 4 hnsecs
use_an_appender: 2 secs, 882 ms, 757 μs, and 9 hnsecs
```
> Prefer an appender to a dynamic array

- std/datetime/timezone.d
Like on NixOS in the posix subfolder.
Without this the timezone unittest fails on NixOS.
> Use baseName to also skip leapseconds file in subfolders

- std/exception.d
- std/socket.d
glibc and uclibc have the same api for strerror.
> Fix strerror usage in uClibc version

- std/utf.d
Minor enhancement to recent https://github.com/dlang/phobos/pull/6229
When converting from wchar to dchar, the optimization for ASCII characters can be applied to most of the basic multilingual plane.
EDIT: This also applies in reverse when converting from dchar to wchar, so I've added it to that case too.
> Minor optimization for byDchar for wchar[] / byWchar for dchar[]

- std/bitmanip.d
There was a bug caused by misunderstanding `endMask` - which is a mask for bits after the full word. Therefore, when length is multiple of `size_t.sizeof`, i.e. `dim == fullWords`, then `endMask == 0`.
I fixed also a similar problem present in `flip()`, which would reset all the bits in the word after the array.
> Fix issue 18134 - BitArray right shift broken if length is multiple of 8*size_t.sizeof

- changelog/std-format-fixDigitGrouping
- std/format.d
Format string "%,3.0f" used with a non-decimal double (e.g. 16887662) does not group the output digits with a group separator (,). This change fixes it, ensuring correct digits grouping even for numbers without decimal part (e.g. 16,887,662).
> Fix digits grouping in formatValue() for floating point numbers

- std/net/curl.d
stop the TestServer waiting in accept() before thread_joinall
Windows is also affected if libcurl.dll is missing.
> fix issue 18519 freebsd 11 + phobos + curl, timing out

- std/datetime/stopwatch.d
Apparently, with gdc and optimizations turned on, the test in question
is optimized enough that the first function being benchmarked sometimes
takes no time at all (since the function being benchmarked does
nothing), causing the test to fail. This fixes that.
> Fix issue with benchmark unit test when compiling with optimizations.

- std/experimental/logger/core.d
- std/experimental/logger/filelogger.d
Using posix.mak from https://github.com/dlang/phobos/pull/6195
with aa[std.experimental.logger.core]=-dip1000  and running
make -f posix.mak std/experimental/logger/core.test
results in:
...
```
T=`mktemp -d /tmp/.dmd-run-test.XXXXXX` &&                                                              \
(                                                                                                     \
../dmd/generated/linux/release/64/dmd -od$T -conf= -I../druntime/import  -w -de -dip25 -m64 -fPIC -transition=complex -O -release -dip1000  -main -unittest generated/linux/release/64/libphobos2.a -defaultlib= -debuglib= -L-ldl -cov -run std/experimental/logger/core.d ;     \
RET=$? ; rm -rf $T ; exit $RET                                                                   \
) …
```
> [TRIVIAL] std.experimental.logger...: Fix -dip1000 compilable issues

- std/traits.d
For me, the behavior for inherited fields was unexpected; otherwise this just adds tests that should have been there already.
> std.traits.FieldNameTuple: clarify documentation and add testing for classes

- std/algorithm/mutation.d
- std/algorithm/sorting.d
`topN` requires an assignable range. While fixing the constraint of `topN`, I found that almost the entire module had missing constraints.
This should improve the error messages slightly, i.e. now they aren't in `std.algorithm` anymore, but the user at least gets "no matching function found" and sees the constraints.
> Fix Issue 8341 - topN(zip()) doesn't work

- std/uni.d
see also my comment #7 in issue 17961
> Fix Issue 17961 - std.uni does not compile with -unittest -dip1000

- std/math.d
`cast(double*)(&x)[MANTISSA_MSB]` is of type `double*`. Moving the
opening parenthesis gives the right result.
> std.math: fix feqrel for ibmExtended floats.

- std/algorithm/setops.d
This test takes an unfeasibly large amount of time to run. (I've never managed to run it to completion.)
The only reason why it appears to pass is that it completes instantly, because canFind never evaluates the Cartesian range at all due to DMD bug #12486. When I fixed it in DMD PR https://github.com/dlang/dmd/pull/8013, the test started timing out.
By the way, how do I get reviewers for that DMD PR?
> Reduce size of slow testcase in std.algorithm.setops

- std/algorithm/searching.d
`__traits(isSame, a, b)` rocks :)
The specialization was discussed in https://github.com/dlang/phobos/pull/4265 and merged in https://github.com/dlang/phobos/pull/5001.
Use https://github.com/dlang/phobos/pull/6144/files?w=1 for a nicer diff.
> Use __traits(isSame) for min,maxElement

- std/algorithm/searching.d
It's in std.algorithm.comparison: https://dlang.org/phobos/std_algorithm_comparison.html#mismatch
> std.algorithm: remove mismatch from the std.algorithm.searching overview

- std/uni.d
Using posix.mak from https://github.com/dlang/phobos/pull/6278
make -f posix.mak std/uni.test
results in:
...
```
T=`mktemp -d /tmp/.dmd-run-test.XXXXXX` &&                                                              \
(                                                                                                     \
../dmd/generated/linux/release/64/dmd -od$T -conf= -I../druntime/import  -w -de -dip25 -m64 -fPIC -transition=complex -O -release -dip1000  -main -unittest generated/linux/release/64/libphobos2.a -defaultlib= -debuglib= -L-ldl -cov -run std/uni.d ;     \
RET=$? ; rm -rf $T ; exit $RET                                                                   \
)
std/uni.d(7414): Error: scope variable chars assigned to non-scope parameter inp calling …
```
> [Trivial]std.uni: Fix a -dip1000 compilable issue; appeared since #6041

- std/internal/math/biguintcore.d
Even though the return value is unique, the compiler can't infer it, so a cast is necessary.
Blocking https://github.com/dlang/dmd/pull/8048
> biguintcore: immutability cannot be inferred for sub() and add()

- posix.mak
- std/ascii.d
- std/digest/digest.d
https://dlang.org/phobos/std_digest_digest.html
std.digest.digest was moved to std.digest in https://github.com/dlang/phobos/pull/5013
> Remove the empty std.digest.digest site

- std/exception.d
With `enforce` now being an epoynmous template, `enforce` is a superset of `errnooEnforce`.
While it might be deputable to deeprecate tthe symbol, we can definitely simplify its implementation which also helps the readers browsing the documentation.
See also:
https://github.com/dlang/phobos/pull/6086
> Simplify implementation of errnoEnforce

- changelog/std-exception-enforceEx.dd
- std/exception.d
In https://github.com/dlang/phobos/pull/6086 we prepared `enforce` to be a super set of `enforceEx` and thus allow a deprecation of it.
See also: https://dlang.org/changelog/2.079.0.html#std-exception-enforce
> However, if enforce can't fully replace enforceEx, then it needs to stick around for at least one more release so that we can have a release where enforce can fully replace enforceEx.
This has happened, so we finally can start the deprecation rodeo.
The targetted deprecation version is 2.084 as it's marked as a legacy symbol in the docs for quite a while now.
> Push deprecation of std.exception.enforceEx

- std/exception.d
`__FILE__` is expanded to the actual file while Ddoc runs and thus leads to unrelated changes.
At the moment this appears on all PRs:
http://dtest.dlang.io/diff/website-6692bbe81733e200f12e675ad9736f9ea126ac0f-7104e0cf40688f445578d863618c97f4/website-6692bbe81733e200f12e675ad9736f9ea126ac0f-f5c9edd530f5ccf612df5a6a294089a8/web/phobos/std_exception.html
See also: https://github.com/dlang/dlang.org/pull/2268
> Fix unrelated DAutoTest diff changes

- std/container/rbtree.d
RedBlackTree.opEquals() was preventing the use of delegates by explicitly forcing the equal() check to go through a function.
> Fix issue 18634 - support for delegate comparators in rbtree

- std/regex/internal/backtracking.d
- std/regex/internal/ir.d
- std/regex/internal/parser.d
- std/regex/internal/thompson.d
- std/regex/package.d
Prime use case is line by line matching.
Some anecdotal evidence on @jondegenhardt benchmarks shows:
```
▶ ./find_regex '(aa)+(cc)+g' strings.txt               
106437 matches; 5538.671 milliseconds
▶ ./find_regex '(aa)+(cc)+g' strings.txt
106437 matches; 1880.550 milliseconds
```
For roughly ~3x speedup.
See also:
https://issues.dlang.org/show_bug.cgi?id=18114
> Cache and reuse std.regex engine to speed repeated matching

- dip1000.mak
- std/exception.d
See also https://issues.dlang.org/show_bug.cgi?id=18637
https://github.com/dlang/phobos/blob/master/dip1000.mak  with
aa[std.exception]=-dip1000
Error when running: make -f posix.mak std/exception.test
```
std/exception.d(1236): Error: copying & i into allocated memory escapes a reference to local variable i
```
> std.exception: Fix a -dip1000 compilable issue

- std/file.d
So apparently auto-tester is currently broken because `std.file.symlink` is Posix-only. This is a hotfix for the newly added tests.
I'm still impressed that https://github.com/dlang/phobos/pull/6320 passed on auto-tester with "8 pass" and not "8 pass, 2 pending" or "8 pass, 2 fail".
CC @braddr
> Fix std.file unittests for auto-tester

- std/range/package.d
This seems to pop up frequently:
https://forum.dlang.org/post/asocdlqaihkskiilrajd@forum.dlang.org
https://forum.dlang.org/post/oqsmbwnhhhkuvkarbtzf@forum.dlang.org
So let's better add an example and improve the docs.
> std.range: Add example for withPartial for slide + improve docs

- std/random.d
**EDIT: reduced this PR just to using arc4random when available. Other cases left for another PR.**
Use arc4random when available, ~~otherwise replace MinstdRand0 with xorshift64*/32.~~
This pull request does not seek to make `std.random.unpredictableSeed` cryptographically secure, but just correct some basic deficiencies mentioned in https://issues.dlang.org/show_bug.cgi?id=18596:
>Currently `std.random.unpredictableSeed` returns the result of a thread-local MinstdRand0 instance xor'd against the clock. MinstdRand0 is slow (due to integer division) and somewhat outdated. A particular weakness of using MinstdRand0 is that it is very likely that consecutive calls to `unpredictableSeed` will return numbers that are identical in the high bit, since MinstdRand0 only produces results in the …
> Partially Fix Issue 18596: use arc4random when available for unpredictableSeed

- std/random.d
XorshiftEngine.min is defined as 0 regardless of template parameters
but an XorshiftEngine cannot produce a value of zero if its internal
state has the same number of bits as the output element type.
> Fix Issue 17862 - std.random.XorshiftEngine.min is wrong when bits == 32

- std/random.d
The fix for 18631 broke code. Ranges cannot be marked with const or
inout in generic code. The range API does not require that any functions
be const or inout. In this case, with the changes, choice requires that
length and opSlice be const, breaking any code that uses a range with
choice that does not have a const length or opSlice (which is going to
be a large percentage of ranges with those functions which aren't
arrays).
> Revert fix for 18631.

- changelog/std-functional-binaryReverseArgs.dd
- std/functional.d
`reverseArgs` was added in https://github.com/dlang/phobos/commit/29f3cc23f76c97a2782848033136d2d7ec7ca57e, but isn't in Phobos and [very seldom on GitHub](https://github.com/search?l=D&q=binaryReverseArgs&type=Code&utf8=%E2%9C%93) - considering that almost all matches are either a copy of Phobos or a copy of the same Rosetta solution. For the latter `writefln!"..."` would be the idiomatic code anyhow.
> Deprecate binaryReverseArgs in favor of reverseArgs

- std/bitmanip.d
I saw this showing up in the public docs:
https://dlang.org/phobos/std_bitmanip.html#.BitArray.toString
Also I don't see any reason to use `static` in unittests - especially if it's a non-templated struct.
> std.bitmanip: Remove outdated debug info + redundant static

- std/math.d
A continuation of #5822 (or a prelude, works both ways).
When running the unittests for PPC64/LE, found many failures due to it checking the wrong part (`MANTISSA_MSB` value is the least significant index on `LittleEndian`).
Fixed places where Big/Little endian would otherwise differ, but actually should do the same thing.
> std.math: Use DOUBLEPAIR_MSB/LSB for accessing high/low parts of ibmExtended format

- std/file.d
Since we added a whole bunch of new test to std.file, auto-tester sometimes fails:
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3092231&isPull=true
So it's probably a good idea to use unique directories like `deleteme` or
in the case of the `tempDir` examples, generating a unique file.
> Fix spurious build failures in std.file by using more unique test directories

- changelog/std-typecons-nullable-apply.dd
- changelog/std-typecons-nullable-bind.dd
- std/typecons.d
`bind` is an operation for Nullables that unpacks the nullable, if it's non-null, and then repacks the result in another appropriately-typed nullable. This replaces a lot of awkward `thingy.isNull ? Nullable!SomeType.init : op(thingy.get)` with `thingy.bind!op`.
"Monads are underrated."
> Implement apply for Nullable, in analogy to Haskell's monad operation

- dip1000.mak
- std/regex/internal/tests.d
https://github.com/dlang/phobos/blob/master/dip1000.mak with
aa[std.regex.internal.tests]=-dip1000
Error when running: make -f posix.mak std/regex/internal/tests.test
```
std/regex/internal/tests.d(463): Error: @safe function std.regex.internal.tests.__unittest_L55_C7 cannot call @system function std.regex.internal.tests.__unittest_L55_C7.ct_tests
```
> std.regex.internal.tests: Fix a -dip1000 compilable issue

- std/zip.d
This gets us 80% there. You can compress stuff completely `@safe`-ly. The rest relies on `std.zlib`.
> Work On Issue 18184 - std.zip should be usable in @safe

- std/random.d
Example of error:
https://run.dlang.io/is/0nQtvT
```d
void main()
{
import std.random : isSeedable, Random;
static assert(isSeedable!(Random, ulong)); // Passes erroneously.
Random rnd;
rnd.seed(ulong.max); // Compile-time failure.
}
```
> Fix Issue 18663 - std.random.isSeedable has false positives

- std/algorithm/searching.d
Eliminates an error from std.algorithm.searching (the remaining errors are from std.algorithm.comparison and std.uni):
make -f posix.mak std/algorithm/searching.test  [-dip1000 for std.algorithm.searching.d (the posix.mak I'm using is master+ https://github.com/dlang/phobos/pull/6195] + -dip1000 for searching.d; master at Latest commit 4820a49)]:
```
std/algorithm/searching.d(2101): Error: @safe function std.algorithm.searching.__unittest_L2088_C7 cannot call @system function std.algorithm.searching.find!("a == b", SortedRange!(int[], "a < b"), SortedRange!(int[], "a < b")).find
std/algorithm/searching.d(2102): Error: @safe function std.algorithm.searching.__unittest_L2088_C7 cannot call @system function std.algorithm.searching.find!("a == b", SortedRange!(int[], "a < b"), …
```
> std.algorithm.searching: Fix a -dip1000 compilable issue

- dip1000.mak
- std/datetime/date.d
- std/datetime/systime.d
Weeds out the last violations of `-dip1000` in std.datetime.
`writefln` should be fixed, but we want to crack down `-dip1000` module by module.
> std.datetime: make -dip1000 compatible

- std/math.d
Less branching, and doesn't care about endian-ness.  Tested against PPC64/LE.
For comparison between old (source view 1) and new (source view 2) https://explore.dgnu.org/g/fTvttz
Probably better to review with https://github.com/dlang/phobos/pull/5820/files?w=1
> std.math: Implement more optimal floorImpl for ieeeSingle

- std/uni.d
Turns out byDchar is ~2x slower then decodeFront,
time to either deprecate byDchar or make it fast.
<del>
2nd order of magnitude improvement is handling
ascii case w/o lookup tables.</del>
```
//1st module
import core.stdc.string;
import std.uni;
import bench_data;
extern(C) int strcasecmp(const char *s1, const char *s2);
void main() {
auto timings = benchmark!(
() => blackhole = sicmp(ascii1, ascii2),
() => blackhole = sicmp(uni1, uni2),
() => blackhole = strcasecmp(ascii1.ptr, ascii2.ptr)
)(1_000_000);
writefln("ASCII %s", timings[0]);
writefln("Unicode %s", timings[1]);
writefln("strcasecmp %s", timings[2]);
}
// 2nd module to hide data from optimizer
module bench_data;
string ascii1 = "This is some STring";
string ascii2 = "ThiS is some …
```
> Fix awfully slow sicmp

- std/path.d
Shrink the @trusted to the smallest bit of the function that needs it. The rest is to follow the convention that `result` is for the return value.
> make buildNormalizedPath() @safe

- std/stdio.d
- std/traits.d
PR https://github.com/dlang/dmd/pull/7996 is modifying the compiler to comply with the language specification:
> The value of an EnumMember is given by its AssignExpression. If there is no AssignExpression and it is the first EnumMember, its value is EnumBaseType.init.
The current behavior is to assign the value `0` to the first enum member when no assign expression is given.  The referenced PR introduces a deprecation message when an enum's base type's `.init` member is not 0.  This applies to the types `double`, `char` and `real`.  This allows applications to maintain the current behavior for a time until the deprecation is over and the behavior will change to match the specification.  Note that this means you cannot currently create an enum with base type `double`, `char` or `real` …
> Accomodate Enum init deprecation

- std/math.d
According to https://dlang.org/spec/version.html#predefined-versions there is no `MIPS` version.
> Use MIPS32 instead of MIPS

- std/traits.d
hasMember treats T* as T and has no failures. hasStaticMember fails with a T* because of it's use of __traits(getMember. Can be fixed by explicitly handling pointer T.
Either that or hasMember on a T* should maybe instead fail as hasStaticMember does?
> Fix issue 18438 - Handle T* in hasStaticMember like hasMember

- dip1000.mak
- std/typecons.d
https://dlang.org/phobos/std_typecons.html#Proxy
"template Proxy(alias a)
Creates a proxy for the value a that will forward all operations while disabling implicit conversions. The aliased item a must be an lvalue."
There is this unittest in std/typecons.d:
```
@system unittest                  <== line 6579
{
// bug14213, using function for the payload
static struct S
{
int foo() { return 12; }
mixin Proxy!foo;          <== line 6585
}
static class C
{
int foo() { return 12; }
mixin Proxy!foo;
}
S s;
assert(s + 1 == 13);
C c = new C();
assert(s * 2 == 24);
}
```
I don't understanf, why a non-lvalue returning function is used/(usable at all) here as template argument, but it compiles for S and C with -dip25.
With -dip1000 it compiles for C only.
Strange.
This quasi-fix just comments-out …
> std.typecons: Fix a -dip1000 compilable issue

- dip1000.mak
- std/algorithm/iteration.d
https://github.com/dlang/phobos/blob/master/dip1000.mak with
aa[std.algorithm.iteration]=-dip1000
Errors when running: make -f posix.mak std/algorithm/iteration.test
...
```
T=`mktemp -d /tmp/.dmd-run-test.XXXXXX` &&                                                              \
(                                                                                                     \
../dmd/generated/linux/release/64/dmd -od$T -conf= -I../druntime/import  -w -de -dip25 -m64 -fPIC -transition=complex -O -release -dip1000  -main -unittest generated/linux/release/64/libphobos2.a -defaultlib= -debuglib= -L-ldl -cov -run std/algorithm/iteration.d ;     \
RET=$? ; rm -rf $T ; exit $RET                                                                   \
)
std/algorithm/iteration.d(4245): Error: …
```
> std.algorithm.iteration: Fix a -dip1000 compilable issue

- .dscanner.ini
- std/format.d
This is not a breaking change, as any use of try/catch or collectException will continue to work, even if they manually specified the type.
This change just makes sense logically to me.
> Fix 18689 - std.format should throw FormatException on bad format spec

- std/experimental/allocator/common.d
- std/experimental/allocator/package.d
Current function in std.experimental.allocator.package:
```d
private T[] uninitializedFillDefault(T)(T[] array) nothrow
{
T t = T.init;
fillWithMemcpy(array, t);
return array;
}
```
When we can statically determine that the representation of T.init consists of nothing but zeroes we can instead use memset. char and wchar can also be special-cased.
> Fix Issue 18223: use memset in uninitializedFillDefault(T[])

- std/typecons.d
* inline code words easiest as backticks
* prefer https to http
* apply should not be "opinionated" about value vs reference, just transparently pass arguments through
> Followup to addition of apply

- std/container/slist.d
- Optimize implementation of opBinary
- ~Allow concatenation of lists with different element types, if both
element types have a common base type.~ (this change has been removed from the PR)
- Use separate common logic from insertFront and insertAfter, and use it in both of them.
- Explicitly forbid shared element types (did not work anyway, and would be bad usage of `shared` as well).
> SList implementation improvements

- posix.mak
At the moment every execution `make -f posix.mak dscanner` will rebuild Phobos first which is absolutely unnecessary and super annoying.
After all, the dscanner binary only needs to be built once and doesn't need to be rebuilt if a line in Phobos has been changed.
There seems to be no clean way to tell Make to avoid building its order-only dependencies if the final target doesn't need a rebuild anyhow.
So I went with a quick one-line workaround.
> posix.mak: Don't rebuild Phobos when running dscanner

- std/zip.d
Because data member was indexed by an integer, the upper limit of a file which could be archived was 2GB. I replaced every occurrence with uint and manually tested on my machine with files larger than 2GB. 
Adding a test could be problematic, however we can experiment with memory mapping larger than 2GB.
Do you think it is an overkill?.
Thanks, 
Andrei.
> Fix Issue 18452 - std.zip has size limit of 2 GB

- std/math.d
Because they now no longer work, and to be honest they shouldn't be force raising a floating point exception anyway, as that arguably violates `pure`.
> std.math: Remove special cases that attempt to raise FE overflow/underflow flag

- std/experimental/allocator/mmap_allocator.d
This is a subset of the old #5879
> Make mmap_allocator allocate @safe

- std/typecons.d
Other operations that have been missed?
> Fix Issue 14637 - Array operations should work on tuples

- std/bitmanip.d
Found by accident, one should be able to call nativeToBigEndian with const or immutable floating points too.
I'm not sure if this should be handled at `FloatingPointTypeOf` template instead so I've chosen less impacting way.
> [trivial] Fix EndianSwapper to work with qualified types

- std/algorithm/internal.d
- std/algorithm/iteration.d
- std/algorithm/mutation.d
- std/algorithm/sorting.d
- std/random.d
Rationale in review comment by @wilzbach  https://github.com/dlang/phobos/pull/6410#discussion_r178660995:
>Use a fixed seed and a fixed engine, everything else might lead to random coverage changes.
This PR applies this across Phobos. Exceptions are made for public unittests that may be meant to demonstrate use of unpredictableSeed and/or the default Random.
> Issue 18715 - Non-documented unittests should not use unpredictableSeed or default Random alias

- std/datetime/package.d
Many people have remarked that `std.datetime` is confusing: https://github.com/wilzbach/state-of-d-2018/blob/master/12h:%20Which%20parts%20of%20Phobos%20(D%27s%20Standard%20Library)%2C%20if%20any%2C%20do%20you%20find%20difficult%20to%20work%20with%3F
This is the first step to improving that situation.
This PR:
1. Gives links to symbols based on usage in a clear table
2. Adds the most common usage of datetime in examples
3. Removes a large amount of text that is repeated elsewhere. I believe this text was either self-explanitory or gone over on each of the respective function docs
> Simplified std.datetime.package overview

- std/datetime/stopwatch.d
Looks like an optimization issue. With `asm`, DMD gets pretty conservative.
Though ideally we should have something like https://github.com/dlang/phobos/pull/5416 built-in into the `benchmark` method.
> Fix Issue 18704 - std/datetime/stopwatch.d(452) assertion failure on auto-tester

- std/math.d
This is just a slight extension of #5820.  Tested against PPC64/LE.
https://github.com/dlang/phobos/pull/5822/files?w=1
> std.math: Implement floor for ibmExtended reals.

- std/zlib.d
needed for https://github.com/dlang/dmd/pull/8143
> zlib: remove switch from in front of super()

- std/regex/internal/ir.d
- std/regex/internal/tests2.d
- std/regex/package.d
Instead of a messy code that ended up with refcount at the wrong place
provide a clean sealed fixed-size array with required semantics and
build on top of that.
> Fix issue 18691 - memory errors in std.regex.Captures

- std/math.d
The time to rename these was eight years ago. Andrei has made very clear that renames are no longer welcome for Phobos.
> Remove outdated status from std.math

- std/experimental/allocator/gc_allocator.d
- std/experimental/allocator/typed.d
Qualify members of `GCAllocator` as `const` to make it usable in pure contexts.
Because `new` can be used in pure contexts I see no reason why `GCAllocator` shouldn't be that aswell.
> Make GCAllocator usable in pure functions

- std/algorithm/iteration.d
- std/algorithm/mutation.d
- std/algorithm/searching.d
- std/algorithm/setops.d
- std/array.d
- std/format.d
- std/range/interfaces.d
- std/range/package.d
- std/range/primitives.d
- std/uni.d
A first start as finding all `_range` matches and going over the hits was easy.
> Remove superfluous _range used to avoid auto-highlighting

- .dscanner.ini
- changelog/rndtonl-deprecated.dd
- std/math.d
This function 
1. Results in link errors if you're not using DM's C runtime
2. Is non-standard
3. Is covered by `round` and friends
Side note: all of these platform specific math functions which share the C names feel a lot like PHP.  This is not how these would be designed if std.math was to be written today, so any instance of these that we can remove/redesign, the better.
> Work On Issue 18693 - Remove rndtonl from std.math

- std/algorithm/sorting.d
- std/array.d
- std/ascii.d
- std/bitmanip.d
Having imports in `version(unittest)` blocks means that user code being unit tested will also import these files incurring a compile-time penalty.
Should help with dlang/dmd#8124 a bit, at least for the `version(unittest)` portion.
I will submit more PRs for the rest of Phobos, I wanted to make these PRs small and reviewable.
> Remove version(unittest) imports to avoid extra imports in user code.

- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/building_blocks/fallback_allocator.d
- std/experimental/allocator/building_blocks/free_list.d
- std/experimental/allocator/building_blocks/free_tree.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/common.d
- std/experimental/allocator/mallocator.d
Most of the `version(unittest)` stuff here is not needed at all (there's no reason to guard unittests with `version(unittest)`).
A couple of the changes are not trivial, however.
See #6450 for more details.
> Trim as much version(unittest) as possible from allocator

- std/digest/murmurhash.d
- std/internal/cstring.d
- std/math.d
- std/net/isemail.d
- std/numeric.d
- std/parallelism.d
- std/path.d
- std/range/primitives.d
- std/socket.d
- std/traits.d
> More removal of version(unittest)

- std/algorithm/iteration.d
- std/algorithm/setops.d
- std/container/array.d
- std/container/dlist.d
- std/container/slist.d
- std/csv.d
- std/file.d
- std/format.d
- std/meta.d
- std/parallelism.d
- std/path.d
- std/random.d
- std/range/package.d
- std/range/primitives.d
- std/stdio.d
- std/uni.d
- std/utf.d
Unfortunately we can't control when people are introduced to the concept of a range. Ideally they read Ali's chapter on it or go through the tour before they start going through the docs. But, a lot of users will have these terms thrown at them without introduction (from their perspective).
This PR makes mentions of input ranges into links to `isInputRange`. Also, the major range types now have links to the header of std.range which contains lots of range tutorials.
> Make references to input ranges a link to isInputRange

- std/experimental/allocator/common.d
- std/experimental/allocator/gc_allocator.d
- std/experimental/allocator/mallocator.d
- std/experimental/allocator/mmap_allocator.d
- std/experimental/allocator/package.d
Some allocators can allocate zeroed memory more efficiently than allocate + memset.  This pull request takes advantage of this in `std.experimental.allocator : make` and `makeArray`.
This PR adds non-public `allocateZeroed` methods to `Mallocator` and `MmapAllocator` and `GCAllocator`. Various derived allocators could also implement such methods when their parent allocators support them, but that work is left to a future PR (if this PR is merged).
Ignoring whitespace changes when reviewing this PR should make `make` clearer.
> make/makeArray: take advantage of allocators with smth. faster than allocate+memset zero

- changelog/shared-bitmapped-block.dd
- std/experimental/allocator/building_blocks/bitmapped_block.d
Both the shared and non-shared versions of the BitmappedBlock now support two modes of allocation: Yes.multiblock and No.multiblock.
Yes.multiblock means that allocation requests can exceed the block size.
No.multiblock means that allocation requests can be at most a single block.
The motivation here is that the SharedBitmappedBlock only supported the No.multiblock which was inconsistent with the regular BitmappedBlock which allowed for allocation requests larger than a single block.
For the SharedBitmappedBlock with Yes.multiblock, I just put a lock around the old implementation.
The SharedBitmappedBlock with No.multiblock has a separate implementation which is faster, with the tradeoff that we can't allocate more than 1 block at a time.
I updated the docs and added a lot of tests and …
> Add multiblock support for shared and non-shared BitmappedBlock

- std/experimental/allocator/building_blocks/allocator_list.d
`alignedAllocate` mimics the logic of the regular `allocate`, with the exception that if a new node is requested, its size would be at least `allocationSize + alignment - 1`, to make sure that the new aligned allocation would fit.
> Add alignedAllocate for AllocatorList

- posix.mak
https://github.com/dlang/dmd/pull/8089 for Phobos, s.t. downstream packers can set their custom flags and don't need to patch `posix.mak` like e.g. https://github.com/dlang/phobos/pull/5966
It's also useful for quickly applying a flag for local testing:
```
make -f posix.mak std/algorithm/iteration.test DFLAGS="-debug=MyDebug"
```
For reference, environment variables aren't read, so global `DFLAGS` won't start to influence this Makefile, e.g.
```
DFLAGS="-debug=MyDebug" make -f posix.mak std/algorithm/iteration.test
```
> Allow to add additional DFLAGS when building Phobos

- std/experimental/allocator/package.d
This fixes the following bug
```
import std.experimental.allocator.mallocator : Mallocator;
auto a = sharedAllocatorObject(Mallocator.instance);
auto buf = theAllocator.allocate(42);
processAllocator = a;
theAllocator.deallocate(buf);
```
> Fix Issue 18760 - theAllocator dangling reference bug

- std/typecons.d
* Fix `datum` typo.
* Clarify that `Nullable!T.get` doesn't always throw (e.g. in release mode).
* Add preconditions for `Nullable!(T, nullValue).get`.
> [trivial] Fix `Nullable.get` docs

- std/exception.d
This fix is actually more a workaround. I propose it because it's verifiable by hand that `doesPointTo` is well `@nogc`.
> fix issue 17084 - Can't sort array of structs with alias this

- std/zip.d
- std/zlib.d
The buffers are file-sized so it's worth skipping unneeded initialization.
This PR doesn't make this change for `std.zlib.uncompress`.
> [Trivial] zip & zlib: don't zero-fill buffers before writing to them

- std/variant.d
For all 64-bit targets with `real.sizeof` < 16, e.g., Win64 MSVC for LDC.
> Fix std.variant unittest

- std/conv.d
E.g., T=`void[0]` is a 0-sized type. When wrapping it in a struct S, the struct's size is 1. So reinterpret-casting the T target to S and blitting the `S.init` value over it doesn't result in a noop, but a 1-byte copy to the 0-sized target.
> Fix std.conv.emplaceRef() for 0-sized types

- std/math.d
`log1p(-2.0)` returns +NaN for the non-x87 software implementation, and so does the MSVC runtime function. The x87 asm implementation and libm on Linux return -NaN. So just ignore the sign.
> Fix std.math.log1p() unittest

- std/stdio.d
Spin-off from #6469. I'm hoping that this will be relatively easy to get to work on the different platforms.
Instead of throwing a UTFException on unpaired high surrogates, a replacement character could be written. But throwing is what happens currently for unpaired low surrogates, so I went with that.
> fix conversion from wchar to char in LockingTextWriter.put

- std/stdio.d
Since https://github.com/dlang/phobos/pull/6382 was merged running phobos unittests will cause this (on DFly):
```
generated/dragonflybsd/debug/64/unittest/test_runner std.experimental.logger.core
****** FAIL debug64 std.experimental.logger.core
std.exception.ErrnoException@std/stdio.d(566): Could not close pipe `' (File exists)
----------------
std/exception.d:515 _init [0x5fe7c9]
std/exception.d:436 _init [0xb32e0e]
std/stdio.d:566 _init [0xd46333]
std/stdio.d:519 _init [0xd46099]
std/stdio.d:503 _init [0xd4600f]
std/experimental/logger/filelogger.d:83 _init [0x1ffe180]
std/experimental/logger/filelogger.d:42 _init [0x1ffe023]
std/experimental/logger/core.d:1808 _init [0x1fba600]
gmake[1]: *** [posix.mak:381: unittest/std/experimental/logger/core.run] Error 1
```
Looking at the sources …
> Fix stdio File.open / resetFile / detach / refcount

- posix.mak
It seems that there are still many issues with -dip1000 and for the time being it's apparentely better to only test the separate `.test` targets with -dip1000.
This is not ideal as -dip1000 is now only checked on Linux 64-bit, but before it wasn't run on Windows neither and -dip1000 is not very platform dependent.
This should hopefully unblock https://github.com/dlang/dmd/pull/8124
The only downside to this is that now a PR at dmd will no longer run Phobos with -dip1000 checks. We can either
- hope that no one will regress the CircleCi dip1000-enabled `*.test`
- let dmd's CircleCi run the `*.test` targets too
- fix the mangling issues with -dip1000 and re-enable the checking that this PR disables
> Only run -dip1000 checks on CircleCi on not on the auto-tester

- std/uni.d
So, what's happening is that the `toString` of `Appender` now uses `formatValue`, which calls `formatRange`, which calls `graphemeStride`. `Grapheme` uses `TrieBuilder`, which uses `std.conv.text` for an error message which uses `Appender`, and you can see the problem.
If the `Appender.toString` code wasn't already released, I'd suggest removing the format specifier from it, as it would be a much cleaner fix. My guess is that other such return inference issues exist that we can't detect.
The other troubling issue is that the test suite didn't pick this up. The error only appears when compiling a file outside of the Phobos directory. Which strengthens my hypothesis about hidden inference problems.
> Fix Issue 18822 - Compiling byGrapheme Fails

- std/array.d
Pulls the call to `toUTF32` out of a call to `@trusted`. Reduces the scope of the trusted application.
> Remove template wide trusted in std.array

- std/typecons.d
The table explaining format specifiers for `Tuple` has been placed in the parameter explanation.
I moved the table so this is not the case.
The table contained unescaped commas, which are escaped now.
This is also an addition to #6502.
> Fix Misplaced Table

- changelog/std-math-fminmax.dd
- std/math.d
If one of the arguments is a NaN, return the other. These are the C99 semantics; the previous simple ternary expression is covered by `std.algorithm.min/max`.
> std.math: Change fmin/fmax semantics wrt. NaNs

- std/typecons.d
The problem is only fixable for `struct` and `union` and not `class`, since `Typedef` is a `struct`.
> fix issue 18415 - Typedef ignores `@disabled` default constructor

- std/stdio.d
Remove errors in the description: It writes to stdout not args[0], calling without arguments does compile and it does not use std.conv.to.
Use similar description as std.stdio.writef.
> Correct documentation for std.stdio.write.

- std/algorithm/iteration.d
- std/algorithm/package.d
Add missing links to `std.algorithm.iteration : mean` from the indexs of both `std.algorithm` package and the `std.algorithm.iteration`.
> [trivial] Add mean to the doc index of std.algorithm and std.algorithm.iteration

- std/math.d
They were assigned to each other wrongly. FYI @kinke.
> std.math: Fix mask values of inexact and invalid on Mips

- std/array.d
Note that `replace` doesn't have a `sink` parameter. And for `replaceInto`, `sink` must always be defined.
> [Trivial] Improve documentation of std.array.replace and replaceInto

- .dscanner.ini
This check appears to be preventing Circle CI from passing at https://github.com/dlang/phobos/pull/6515
The failure is due to a dscanner bug documented at https://github.com/dlang-community/D-Scanner/issues/593
Unfortunately, like others, I am not able to reproduce the problem locally.   I tried to simply re-initiate Circle CI, but it still failed.
> Temporarily disable dscanner if_else_same_check for std.typecons

- .dscanner.ini
Sorry the .dscanner.ini doesn't support direct excludes/includes in the main section, but only in the special filter section (that is due to inifiled not supporting variant types).
See also: https://github.com/dlang/phobos/pull/6532
CC @JinShil
> Move the -std.typecons exclude to the filter section of the DScanner Ini

- std/file.d
The problem is that run.dlang.io automatically adds `import std.stdio` and thus
we silently print to stdio instead of writing to a file (we should really deprecated
std.file.write because of this!).
Anyhow, I think the easiest solution here is to use the fully qualified symbol.
> Fix Issue 18752 - std.file.read runnable example fails

- std/net/curl.d
Not really happy about this, but converting these examples to real unittest would drag us into the trouble of making sure that the tests never fail on CI builds. Also for run.dlang.io internet access is disabled anyhow.
As the appspot application seems to be down, I replaced the respective links with [HTTPBIN](https://httpbin.org).
> Fix Issue 18940 - [std.net.curl]Can't run examples on page. cannot implicitly convert expression

- std/datetime/timezone.d
- std/experimental/allocator/building_blocks/region.d
`tzname` is unset by default on Musl, and @jercaianu added more code below `SbrkRegion`, so need to version out that part alone for Musl now. With this pull, all Phobos tests pass with Musl on Alpine.
> Musl: last remaining tweaks

- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/experimental/allocator/building_blocks/region.d
Also includes similar fixes for KKRegion and BitmappedBlock as per issue comment.
> Fix Issue 18847 - std.allocator: Region uses .parent before it can be set

- std/regex/internal/thompson.d
This fixes a possible deprecation with https://github.com/dlang/dmd/pull/8320.
> [trivial] popFront is not a property

- std/uni.d
Compares should not be leaking their arguments.
> uni.d: use scope

- changelog/std-algorithm-mutation-remove.dd
- std/algorithm/mutation.d
See the Bugzilla message or the changelog entry for a motivation.
----
Previously, `std.algorithm.remove` used to accept any values as `offset`.
This behavior was very error-prone:
```d
import std.algorithm, std.stdio;
[0, 1, 2, 3, 4].remove(1, 3).writeln; // 0, 2, 4  -- correct
[0, 1, 2, 3, 4].remove([1, 3]).writeln; // 0, 3, 4  -- incorrect
```
With this release, using arrays as individual element is deprecated.
`tuple` can be used to explicitly indicate that a range
from `start` to `stop` (non-enclosing) should be removed:
```d
import std.algorithm, std.stdio, std.typecons;
[0, 1, 2, 3, 4].remove(tuple(1, 3)).writeln; // 0, 3, 4
```
However, only 2-tuples are allowed to avoid this un-intuitive scenario:
```d
import std.algorithm, std.stdio, std.typecons;
[0, 1, 2, 3, 4].remove(tuple(1, …
```
> Fix Issue 12086 - std.algorithm.remove + range of indices produces wrong results

- std/datetime/stopwatch.d
As mentioned on #5367, it would be great if the benchmarking function wouldn't allow compilers to optimize its to-be-tested functions away.
There are a couple of tricks to avoid this behavior, at least:
- assigning return value to `__gshared`
- using the `doNotOptimizeAway` trick (see below or #2995)
- [`@optStrategy("none)` in LDC](https://wiki.dlang.org/LDC-specific_language_changes#.40.28ldc.attributes.optStrategy.28.22strategy.22.29.29)
- ...
I guess this might be a controversial change, so I am very interested to hear your opinions. What strategy to avoid the optimization do you prefer?
> Add dontOptimizeAway to std.datetime.stopwatch

- std/datetime/stopwatch.d
Reverts dlang/phobos#5416
Reason: x86-only. Would require downstream patches in LDC/GDC Phobos to remove it.
> Revert "Add dontOptimizeAway to std.datetime.stopwatch"

- std/experimental/checkedint.d
Also added a few public documentation examples as unittests.
I added them in the top as there was only one high-level example.
> Fix Issue 18952 - std.experimental.checkedint.Saturate prints integral promotion deprecation message

- std/uni.d
Old:
```d
result.put(s[0 .. i]);
result.reserve(s.length);
```
New:
```d
result.reserve(s.length);
result.put(s[0 .. i]);
```
> std.uni.toCase reserve before appending, not after

- std/exception.d
Needed for https://github.com/dlang/dmd/pull/8320.
> [trivial] Getter property should not return void

- posix.mak
- win32.mak
- win64.mak
This builds unittests in about half the time of the sequential build on my mobile i7 quad-core.
> windows: build phobos unittests through posix.mak to allow parallel builds

- dub.sdl
This addition is a convenience for the IDE users, so that we have phobos in the project explorer (or whatever it is called...) rather than a way to build and test (even if this works).
> add a DUB description

- std/algorithm/sorting.d
Looks like a search-and-replace messed up the code markup. Also, it seems like the range specified in the second list item was not consistent with its explanation.
> Fix doc comment for pivotPartition

- .circleci/run.sh
- .gitignore
- dub.sdl
- test/.gitignore
- test/dub_stdx_allocator.d
- test/dub_stdx_checkedint.d
I often had the need to use the latest version of a package in Phobos, but without requiring my library users to upgrade their compiler.
This simple `dub.sdl` allows the usage of the checkedint module via DUB.
Example
-------
```d
#!/usr/bin/env dub
/++dub.sdl:
dependency "phobos:checkedint" path=".."
+/
void main(string[] args)
{
import stdx.checkedint; // From latest Phobos
import std.stdio; // DMD's Phobos
writeln("checkedint: ", 2.checked + 3);
}
```
Motivation
----------
Of course, the main motivation is `std.experimental.allocator`, but that's a bit more complicated.
Future
------
Also, like for [dmd's dub package](http://code.dlang.org/packages/dmd) it will only be exposed as `~master` due to D's versioning not matching SemVer and thus the DUB registry rejecting the versions.
I …
> Expose experimental packages on Dub

- std/datetime/systime.d
There are more @trusted annotations here than should be. However, the code is such a horrific tangle of templates, it so far has proved impractical to straighten it out without rewriting big chunks of Phobos. So, in order to do it piece by piece, I have to temporarily use @trusted.
> dip1000: std.datetime.system replace 'in' with 'scope const'

- std/datetime/timezone.d
There was documentation refering to the now deprecated method of getting one of the of the timezone implementations via the static TimeZone.getTimeZone.
> Document deprecation of TimeZone.getTimeZone

- std/datetime/date.d
None of these uses of const scope should be required, because Date,
TimeOfDay, and DateTime are all value types with no indirections.
> Remove const scope from value types in std.datetime.date.

- std/container/package.d
- std/path.d
- std/random.d
To fix https://github.com/dlang/dmd/pull/8325
> Remove invalid Markdown backticks in std.path

- dub.sdl
- test/dub_stdx_allocator.d
This little trick is needed as `emplaceRef` isn't public (imho it should be, but that's an issue for a different day).
With this patch, the [collections](https://github.com/dlang-stdx/collections) library builds with a stable DMD/LDC compiler as it now can use the `phobos:allocator` package.
> Expose a copy of std.conv with the DUB package of stdx.allocator

- std/datetime/systime.d
This adds a special TimeZone type internal to SysTime which _timezone is
directly initialized to so that SysTime.init will work without
segfaulting but will still be uniquely identifiable with the is
operator. Or at least, _timezone is _supposed_ to be directly
initialized to it, but issue# 17740 currently prevents that. So, the
private accessor timezoneHack has been added for the moment, and any
place where _timezone would have a function called on it, timezoneHack
is called instead. timezoneHack does the null check and returns
InitTimeZone() for SysTime.init. Once issue# 17740 has been fixed,
timezoneHack will be unnecessary and should be removed in favor of
directly initializing _timezone with InitTimeZone().
The new TimeZone type - InitTimeZone - is internal to SysTime and can
only be …
> Fix issue 12507: SysTime.init.toString() segfaults.

- std/datetime/systime.d
This removes unnecessary uses of scope, adds a lot of necessary uses of
scope, and adds basic tests that ensure that each of the functions in
std.datetime.systime compile when given scope arguments. It also enables
some previously commented out tests involving immutable SysTimes (IIRC,
they didn't use to compile due to compiler bugs related to
Rebindable!(immutable TimeZone), but they now compiler, so they should
be enabled).
> Clean up use of scope in std.datetime.systime.

- std/base64.d
- std/format.d
- std/range/primitives.d
- std/uuid.d
There's no reason for this not to work. `put` jumps through hoops to helpfully transcode between character types just so it can work with any kind of output ranges that accept characters, but it had some specific arbitrary limitations for narrow strings that prevented them from working. This removes the restrictions, so putting to a `char[]` or `wchar[]` is now allowed. All widths work.
I'm not 100% sure of the paths that are taken, maybe they could use some improvement. But at least it will now work.
This enables nice optimizations such as easily allocating buffers on the stack to use with `formattedWrite`
> char[] and wchar[] should be output ranges

- std/stdio.d
fopen and popen wrap C functions that exist in druntime, and it's not
uncommon for folks to end up accidentally trying to use the private
functions in std.stdio instead of the ones from druntime - which then
tends to result in questions on D.Learn. There's no reason that either
of these private functions needs to be named the same as the C function
that it wraps. It just causes confusion when folks accidentally try to
use them instead of the C functions.
So, this changes them to _fopen and _popen so that there will be no such
conflict, and the error messages when folks try to call the C functions
but do so incorrectly will not mention std.stdio's internals.
> Remove unnecessary conflicts in std.stdio.

- changelog/std-array-asStatic.md
- std/array.d
This is #6178 rebooted, so most of this is work of @timotheecour  , not mine. It tries to address the last review @andralex made of it, and also some feedback made to #6214, which is my pull request aiming for same functionality.
> Static array UFCS-style

- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/common.d
It was unable to handle alignments > 2^31 bytes, e.g., returning 2 for the 64-bit pointer 0x2FA_00000000. Return a `size_t` instead of a `uint`. Note that it's only called in one place, an assertion in a ctor of the
`BitmappedBlockImpl` mixin, which handles `size_t` fine.
This fixes sporadic `std.experimental.allocator.building_blocks.bitmapped_block` unittest failures for LDC CI on Win64 (something like 1 out of 100 runs failing).
> [stable] Fix std.experimental.allocator.common.effectiveAlignment()

- std/file.d
That might be useful for someone who's working with stat structs and wants to avoid a call of std.file functions like getTimes which accept only filenames and have to call stat function internally again.
Note: I could not figure out why statTimeToStdTime does not appear in generated docs though I added doc comment and added the function to Timestamp category.
> Make statTimeToStdTime public

- std/format.d
Avoid actually calling `toString` when speculatively formatting to check for format exceptions.
`Args.init` is not a constructed value; hence it is not safe to call methods on it.
Two-step solution:
1. avoid actually calling `toString` when writing into `NullSink` (why bother?)
2. call `formattedWrite` to write into `NullSink` in `checkFormatException`.
> Fix issue 19003: don't call toString on T.init

- std/typecons.d
Importing `std.algorithm` and `std.range` would previously import these `core.stdc.*` modules:
* core.stdc.stdint
* core.stdc.config
* core.stdc.stddef
* core.stdc.signal
* core.stdc.wchar_
* core.stdc.stdarg
* core.stdc.stdio
* core.stdc.time
With this, only `core.stdc.stdarg` remains.
This is a big deal for bare-metal platforms without C libs, e.g., WebAssembly. See https://forum.dlang.org/post/threqzyvtpspkxhrvjnb@forum.dlang.org.
> [Trivial] std.typecons: Get rid of unnecessary core.stdc.stdint.uintptr_t import

- std/uni.d
Follow-up to https://github.com/dlang/phobos/pull/6626
As many modules depend on `std.uni`, we would have needed to revert almost all of the existing `-dip1000` work.
The `@trusted` shouldn't be necessary here, but so far no one has come up with a good fix for std.uni :/
> Revert @trusted hotfix for std.uni

- std/range/package.d
DMD currently has a bug that is gagging warnings and deprecations.  That bug is in the process of being fixed at https://github.com/dlang/dmd/pull/8519, but it has revealed some warnings that need to be resolved in Phobos.  This is one.
> Fix warning in std.range.package - calling without side effects discards return value

- std/typecons.d
Makes Nullable usable with every type, aside the crazies who have pointers to their members. opAssign of the underlying type will no longer be called.
This enables Nullable on, for instance, structs with `@disable this();` and a `SysTime`.
> Fix issue 19037: use move/moveEmplace in Nullable

- std/conv.d
This pull was tested with ldc on linux/x64, Android/AArch64, and Android/ARM, exercising 80-bit, 128-bit, and 64-bit reals. The new decimal test was off by one bit on the first and last platforms, but strangely matched exactly for the most precise, AArch64. Putting this up early to see what the CI says on other platforms, ~will~ have also extended the hex parser ~if all goes well~.
> Extend std.conv.parse for strings to full ieeeQuadruple precision and other fixes

- std/conv.d
- std/random.d
> [stable] Remove superfluous core.stdc.* dependencies in std.{conv,random}

- std/complex.d
Labeling variably-typed arguments of templated functions as const causes the same type to be inferred when the argument is const, non-const, and immutable.
> Fix Issue 19147 - Reduce template bloat in std.complex by using const arguments

- std/uuid.d
Right now `std.uuid` has a static assert that `std.random.Random` is `Mt19937`. This is contrary to the public documentation of `std.random.Random`:
```d
/**
The "default", "favorite", "suggested" random number generator type on
the current platform. It is an alias for one of the previously-defined
generators. You may want to use it if (1) you need to generate some
nice random numbers, and (2) you don't care for the minutiae of the
method being used.
*/
```
Depending on implementation details of another module is brittle and risks leading others to believe they can rely on `Random` being `Mt19937` in their code too.
> Fix Issue 19138 - std.uuid.randomUUID should not depend on std.random.Random being Mt19937

- posix.mak
The memory segmentations issues have been solved and actually as we try to retire CircleCi and move the workload to Buildkite this is becoming a problem as `gdb` on older Debian machines doesn't support the full argument syntax.
Moreover, running things in `gdb` is slow, so this will speed-up the CircleCi time (and local `style` builds.)
> Don't run DScanner in GDB anymore

- std/json.d
JSON_TYPE is an egregious violation of the [D Style Guide](https://dlang.org/dstyle.html).
Rewrite std.json.JSON_TYPE to be CamelCase with lowercase members, with underscore attached to avoid keyword collision.
Deprecate the old type via alias.
> Fix Issue 19135: Rename std.json.JSON_TYPE to JsonType with lowercase attributes

- changelog/std-algorithm-searching-skipOver.dd
- std/algorithm/searching.d
Now you can do the following:
```d
auto s = "DLang.rocks";
assert(!s.skipOver("dlang", "DLF", "DLang "));
assert(s == "DLang.rocks");
assert(s.skipOver("dlang", "DLANG", "DLF", "D", "DL", "DLanp"));
assert(s == "ang.rocks");
s = "DLang.rocks";
```
> Fix Issue 12335 - std.algorithm.skipOver should support multiple args like startsWith

- std/algorithm/iteration.d
> Make `each` capable of early stopping

- changelog/math_float_double_implementations.dd
- std/math.d
And make the x87 `real` version CTFE-able.
Based on Cephes like the existing quadruple and x87 implementations,
https://github.com/jeremybarnes/cephes/blob/master/cmath/atan.c &
https://github.com/jeremybarnes/cephes/blob/master/single/atanf.c
> Implement std.math.{atan[2],tan,exp[2],expm1} for single- and double-precision

- changelog/std-algorithm-iteration-each-early-stopping.dd
See also: https://github.com/dlang/phobos/pull/5268
Preview:
> Add a changelog entry for each's early stopping

- std/exception.d
It makes sure the source file can be read from when running the tests.
If the path to `std/exception.d` in the compile-Phobos command line was relative, this required the testrunner to be run in the same working directory as when compiling Phobos.
> [stable] std.exception: Make unittest less brittle

- std/math.d
This shouldn't have been committed to begin with until after the actual issue had been fixed. A breaking change which allows abs() to be instigated for all types irregardless if they have comparison and negative operators.
@wilzbach Per your commit.
> Fix issue 19162 - [REG: 2.079.0] Public Import Overlapping Names Conflict Resolution

- .circleci/run.sh
- posix.mak
- std/algorithm/comparison.d
- std/internal/attributes.d
Open questions:
- Should we remove the `test/betterC` folder? (the @betterC test extraction is imho a better replacement)
Requires: https://github.com/dlang/tools/pull/357
> Allow @betterC tests in Phobos

- std/conv.d
- std/datetime/date.d
- std/datetime/systime.d
- std/experimental/allocator/building_blocks/ascending_page_allocator.d
- std/format.d
- std/internal/math/biguintcore.d
- std/parallelism.d
- std/path.d
- std/process.d
- std/stdio.d
- std/traits.d
- std/utf.d
A check in D-Scanner is planned for this.
> Fix issue 11959 - Set private symbols declared in version(unittest) blocks

- std/typecons.d
This was always wrong, however it has become urgent in 2.082 now that Nullable contains a union and can no longer generate an implicit toHash to call the contained type's toHash.
> [stable] Fix Issue 18682: Forward Nullable.toHash to contained value, if non-null.

- std/json.d
Works the same as `integer`, `floating` etc. 
Seems obvious you need this to use the module in any real-world usage.
> Add a getter and setter for booleans in JSON

- std/experimental/allocator/common.d
- std/experimental/allocator/package.d
Not really convinced that we should encourage people to use `void`, but it's not too hard to support `void` here as this implies uninitialized memory.
> Fix Issue 19085 - std.experimental.allocator.makeArray should work with void

- std/container/rbtree.d
I'm trying to implement `toHash` functionality for RedBlackTree. I used [this](https://github.com/n8sh/phobos/blob/307ac7e4628c0cf4bb7f4e6efdfa62076754a6f2/std/typecons.d#L1177) as a reference, hope it's not a problem.
Offtopic: it would be nice to have an example like the one [here](https://digitalmars.com/d/archives/digitalmars/D/learn/RedBlackTree_and_myClass_79072.html) on how to use rbtrees in the docs, it helped me a lot.
> Fix Issue 18683 - no toHash in rbtree

- std/algorithm/mutation.d
- std/typecons.d
With the new `__traits(isZeroInit)` (https://github.com/dlang/dmd/pull/8583) we can check at compile-time if a type has a zero initializer. Aside from removing a branch and some dead code, removing a use of `TypeInfo` is a step towards -betterC compatibility.
> Fix Issue 19236 - Replace runtime `typeid(T).initializer().ptr is null` checks with compile-time `__traits(isZeroInit, T)`

- posix.mak
The 'betterC' target was renamed to 'betterc' in 1302dd54c1104aa272b52f1f83193c53ca5837be,
but stable was incorrectly merged into master in #6677.
> Fix buildkite build

- std/typecons.d
It takes the address of local variables.
> std.typecons: Unittest isn't safe

- std/format.d
Dynamic-width strings should estimate as width 0, not `int.max`.
Since dynamic format size (`spec.DYNAMIC`) is encoded as `int.max`, which `guessLength` does not understand, it takes it as int.max, leading `format!"%0*d"` to preallocate 3GB per call. Luckily, Linux can tolerate this, and it's not a common format specifier, but it's still silly.
> Fix issue 19252: avoid ludicrous format length overestimate

- std/experimental/allocator/building_blocks/affix_allocator.d
- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/bucketizer.d
- std/experimental/allocator/building_blocks/fallback_allocator.d
- std/experimental/allocator/building_blocks/free_list.d
- std/experimental/allocator/building_blocks/quantizer.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/building_blocks/segregator.d
- std/experimental/allocator/building_blocks/stats_collector.d
- std/experimental/allocator/gc_allocator.d
- std/experimental/allocator/mallocator.d
Followup to https://github.com/dlang/phobos/pull/6411
>Some allocators can allocate zeroed memory more efficiently than allocate + memset.
>[...]
>This PR adds non-public `allocateZeroed` methods to `Mallocator` and `MmapAllocator` and `GCAllocator`. Various derived allocators could also implement such methods when their parent allocators support them, but that work is left to a future PR
> Implement allocateZeroed for building-block allocators

- posix.mak
- test/betterC/algorithm.d
Now that we have `@betterC` (see https://github.com/dlang/phobos/pull/6645) it's a lot easier to annotate existing unittests and avoid the overhead of keeping a separate test folder around.
> Remove separate @betterC tests

- std/format.d
formattedRead is documented as throwing FormatException.
> Fix formattedRead throwing Exception

- std/process.d
MS runtime up to VS2013 used pseudo handle _NO_CONSOLE_FILENO in that case, see https://github.com/shihyu/learn_c/blob/master/vc_lib_src/src/ioinit.c#L285.
No idea how to test a non-console application in phobos.
> Fix Issue 19275 - std.process: redirecting output in a non-console application fails

- std/range/package.d
see https://forum.dlang.org/post/tmqppgmuevecltmxygrd@forum.dlang.org
> Fix Issue 19289 - std.range.transposed with enforceNotJagged not throwing

- std/json.d
JSON does not have any notion of multiple numeric types. (JS only uses double.)
> Fix issue 19297: handle comparison of signed, unsigned and floating JSONValues as in D

- std/string.d
Similar to https://github.com/dlang/phobos/pull/6361. Code for benchmarks in next post.
**string benchmark, ldc2:**
| compiler                | function      | data      | time                                |
|-------------------------|---------------|-----------|-------------------------------------|
| ldc2 -O2 -release       | old_stripLeft | ascii     | 1 sec, 65 ms, 71 μs, and 8 hnsecs   |
| ldc2 -O2 -release       | new_stripLeft | ascii     | 492 ms, 570 μs, and 2 hnsecs        |
| ldc2 -O2 -release       | old_stripLeft | non_ascii | 1 sec, 852 ms, and 350 μs           |
| ldc2 -O2 -release       | new_stripLeft | non_ascii | 1 sec, 209 ms, 13 μs, and 6 hnsecs  |
**wstring benchmark, ldc2:**
| compiler                | function      | data        | time …
> Add ASCII fast path to stripLeft & avoid unnecessary decoding

- std/algorithm/iteration.d
See bug report for more info.
Relevant discussion: https://forum.dlang.org/post/pn498r$2928$1@digitalmars.com
> Allow no-arg splitter function to work on ranges that aren't standard strings

- std/concurrency.d
```
In addition to the fix which makes it recurse in struct,
the instantiation was changed to not use recursive template instantiation,
exception for struct's tupleof.
```
> Fix issue 4957 - std.concurrency rejects structs with Tid

- std/internal/math/errorfunction.d
Solving Issue#19324 . Some of "<" operators did not have " " before.
> Update the coding style in errorfunction.d

- std/array.d
This test assumed that there would happen to be other bytes than zeroes in the area that was allocated. Since random pieces of memory often are just zeroes, this one probably was responsible of some of the random autotester failures.
> Removed an unittest of minimallyInitializedArray that can fail randomly

- std/math.d
Posted and reviewed on gcc-patches, enables building with SPARC32 targets.
> std.math: Use SPARC_Any instead of SPARC64

- std/datetime/date.d
It was not clear from the documentation whether these methods mutate the current object, or return a new object with the applied modification. The fact that these functions have a non-void return type adds to the confusion.
Clarify this by explicitly mentioning that the functions mutate the current object, and add a "Returns:" DDoc section documenting that the methods simply return `this`.
> std.datetime.date: Clarify that add/roll mutate the current object

- std/algorithm/searching.d
Qualify `opCast(bool)` as `const` for `findSplit`, `findSplitBefore` and `findSplitAfter`.
Enables usage
```D
if (const split = "a b".findSplit(" ")) {}
```
as a const variant to
```D
if (auto split = "a b".findSplit(" ")) {}
```
.
See also: https://forum.dlang.org/post/rruitwhbxmbsrfsokuet@forum.dlang.org.
*Update*: 
One of the tests-cases for `findSplitBefore()` fails because `S2.front()` is `non-`const`.
Should we check statically if `S2.front` is const (`!isMutable!(S2.front)`) and only then qualify `opCast(bool)` as const?
> Qualify opCast(bool) as const for findSplit, findSplitBefore and findSplitAfter

- std/algorithm/iteration.d
`$(REF Flag, std.typecons)`!"each"` should have a comma between the package names, not a dot. It was causing the text to render as `std.typecons..Flag!"each"`.
> Typo in REF macro parameter list in each doc.

- std/format.d
This format specification is described later in the documentation, and works as documented, but is not included in the format string grammar.
> Add %-( to format string grammar

- std/algorithm/sorting.d
- std/numeric.d
sorts a given range in constant time into its nth permutation. Using the factorial number system and Lehmer codes
> nthPermutation

- std/traits.d
druntime's `core.internal.traits.Unqual` is a copy of the same code. This PR removes the code duplication and the required double maintenance of `Unqual`.
> Remove duplicate of Unqual implementation

- std/range/package.d
for https://github.com/dlang/dmd/pull/8941
> Don't shorten the width of the iteration variable

- std/meta.d
druntime's `core.internal.traits.anySatisfy` is a copy of the same code. This PR removes the code duplication and the required double maintenance of `anySatisfy`.
> Remove duplicate of anySatisfy implementation

- changelog/pr6580.dd
- std/random.d
Slicing the elephant into smaller pieces. This PR differs from https://github.com/dlang/phobos/pull/6388 in that it omits entirely system entropy.
The PR's visible change is that one may now write `unpredictableSeed!ulong` and get a `ulong`. The PR's under-the-hood change is that instead of thread-local MinstdRand0 `unpredictableSeed` uses a global SplitMix.
**Q: Why prefer global shared (atomic) instance to thread-locals?**
**A:** It gives us an easy guarantee that the same `ulong` seed will not be produced by more than 1 thread except if `unpredictableSeed!ulong` is called 2^^64 times during the life of the application. The question should rather be, what advantage would thread-local storage give us here?
**Q: What about cryptography?**
**A:** This PR changes nothing about the current …
> Fix Issue 18595 & Issue 18596: replace MindstdRand0 w/SplitMix & templatize unpredictableSeed!UIntType

- std/traits.d
druntime's core.internal.traits.hasElaborateCopyConstructor` is a copy of the same code. This PR removes the code duplication and the required double maintenance of `hasElaborateCopyConstructor`.
> Remove duplicate of hasElaborateCopyConstructor implementation

- std/meta.d
druntime's `core.internal.traits.allSatisfy` is a copy of the same code. This PR removes the code duplication and the required double maintenance of `allSatisfy`.
> Remove duplicate of allSatisfy implementation

- std/traits.d
druntime's `core.internal.traits.hasElaborateDestructor` is an **almost** copy of the same code, as you can [see](https://github.com/dlang/druntime/blob/master/src/core/internal/traits.d#L167).
The druntime implementation accepts a list of `T`. I think that the Phobos alias should do the same. What do you think?
This PR removes the code duplication and the required double maintenance of `hasElaborateDestructor`.
> Remove duplicate of hasElaborateDestructor implementation

- std/typecons.d
Now that we have `static foreach`, we can remove these all workarounds.
> Remove staticIota  + mixinAll

- std/array.d
Follow-up to https://github.com/dlang/phobos/pull/6017
Currently there's no constraints that the ranges return similar types.
Should I add such a constraint too?
It would start to get a monster though:
```d
if (isOutputRange!(Sink, E) && isDynamicArray!(E[]) &&
((isForwardRange!R1 && isForwardRange!R2
&& (hasLength!R2 || isSomeString!R2))
&& is(typeof(R1.init.front) : typeof(R2.init.front)) ||
is(Unqual!E : Unqual!R1)) && is(Unqual!R1 : Unqual!R2)))
```
> Fix Issue 10930 - std.array.replace cannot simple replace an element in array

- std/algorithm/iteration.d
So far, a `substitute()` with multiple ranges tried to iterate an empty base range.
See the added `unittest`: the last `assert` fails without this change.
> Corrected initialization of empty substitute

- std/format.d
Check the return value of `fmt.writeUpToNextSpec` to determine if there are more format specifiers to format before handling the separator.
> Fix issue 18778

- std/file.d
I'm not sure about the order of arguments in getTimesPosix.
Maybe you want it to follow getTimesWin-like approach when the additional argument is the first among SysTime arguments.
> Add getTimesPosix

- std/container/array.d
- std/internal/cstring.d
- std/internal/memory.d
- std/random.d
- std/typecons.d
- std/uni.d
The `core.memory.pureMalloc` wrapper reads errno, calls malloc, then resets errno. This is unnecessary if when the allocation fails the program terminates with `assert(false)` or `onOutOfMemoryError()`.
> Fix Issue 19164 - malloc may be considered pure when failure results in program exit (no need to reset errno)

- std/range/primitives.d
- std/string.d
- std/utf.d
Use const(E)[] instead of E[] when it is valid and doesn't change the return type.
> Decrease template bloat for string functions

- std/algorithm/searching.d
So I'm interested on what the consensus on this issue is.
We haven't managed to improve DMD's error message over the last four year and letting Phobos emit better error messages isn't too hard.
So should we do this for a few important functions?
> [RFC] Fix Issue 13683 - More precise error message for wrong lambda

- std/traits.d
Depends on https://github.com/dlang/dmd/pull/8977
> Remove support for `extern(Pascal)`

- std/internal/scopebuffer.d
fixing https://issues.dlang.org/show_bug.cgi?id=19396
> Fix Issue 19396 - ScopeBuffer can't be used in betterC with inline

- std/traits.d
- std/typecons.d
~~There's just one remaining `AliasSeq!(__traits` but it's not aliasable (`getAliasThis`).~~ 
edit: it will be after fix for blocker merged.
> Remove `AliasSeq` when following `__traits` is directly aliasable

- posix.mak
- win32.mak
- win64.mak
All unittests pass when compiled with gdc. Don't need to bother wasting auto-tester time here.
> [dmd-cxx] Disable auto-tester-test from running

- std/traits.d
std.traits.functionLinkage documentation doesn't show the complete list of possible linkage attributes. See https://issues.dlang.org/show_bug.cgi?id=19466
> Fix issue 19466 - functionLinkage documentation omits some values

- std/digest/sha.d
- std/internal/digest/sha_SSSE3.d
druntime benchmarks gcbench/con*.* perform very badly on Win64 (10 times slower in comparison to Win32), so they don't really measure GC performance. This fixes it.
> SHA on Win64: use SSSE3 version by adjusting register usage

- std/file.d
Use `std.process.executeShell` instead of old system function.
> [trivial] Fix `dirEntries` docs

- std/datetime/systime.d
- std/datetime/timezone.d
- std/experimental/allocator/building_blocks/ascending_page_allocator.d
- std/experimental/allocator/mmap_allocator.d
- std/file.d
- std/format.d
- std/internal/cstring.d
- std/internal/windows/advapi32.d
- std/mmfile.d
- std/net/curl.d
- std/parallelism.d
- std/process.d
- std/socket.d
- std/stdio.d
- std/windows/charset.d
- std/windows/registry.d
- std/windows/syserror.d
Importing `core.sys.windows.windows.d` is slow and replacing it can speed up compilation. See https://github.com/dlang/druntime/pull/2400#issuecomment-447933446
> Replace imports of core.sys.windows.windows to speed up compilation

- std/experimental/logger/filelogger.d
Log message currently doesn't have log level, thread ID, etc. Log messages without this information is mostly useless.
However, printing the thread ID requires `std.concurrency` to be `@safe` which is not possible at the moment. So I've added only the log level to the message string.
> logger: print log level string.

- posix.mak
- std/net/curl.d
Adds possibility to specify absolute path to libcurl.
The TZDatabaseDir version option already does the same for the tzdata directory.
This commit enables the same fix for the path to libcurl. It's needed for Operating systems like NixOS without a search path for dynamic libs.
See https://issues.dlang.org/show_bug.cgi?id=15391 for more information.
Additionally I removed the Makefile part of the TZDatabaseDir solution
because the necessary compiler arguments can be easily given via DFLAGS, which is also compiler independent and doesn't use the /tmp dir which leads to problems on NixOS.
> Add LibcurlPath version option

- std/traits.d
> simplify maxAlignment

- std/typecons.d
Array needs https://github.com/dlang/druntime/pull/2426 to work in betterC.
> Fix Issue 19526 - make RefCounted work in betterC

- std/typecons.d
I'm not sure how people want to start testing `-betterC` compatibility with Phobos. I assume the best way would be to do extract all unittests marked with `@betterC`?
```d
unittest @betterC
{
....
}
```
For now I went with a more simple and straight-forward way of simply executing all files in `test/betterC`.
~~~However, I still get an error when using the `alias BOMSeq = Tuple!(int, "schema");`  line:~~~
Also I need to define `main` manually as the default main with `void main` returns with `44` :/
> Make std.typecons.Tuple betterC compatible

- posix.mak
- std/net/curl.d
Second attempt at fixing the issue.
Only a little sceptical that this is more correct here - calling shutdown is recommended however in the docs.  In any case, I can no longer reproduce this on Linux after applying patch.
>  fix Issue 18519: missing curl + phobos = std.net.curl unittest timing out

- std/format.d
Because dealing with raw integers is really error-prone and makes looking at PR diffs really difficult.
BTW @JackStouffer was there any reason not to allow `(P, S)(ref put, S stringLike)` for the new `.put`-writer overloads. The sink overloads accept a format string or a format spec.
> Use enums for hasToString

- std/experimental/allocator/building_blocks/region.d
- std/math.d
> Add minimum HPPA support to phobos

- std/uni.d
Because the scope inference needs a little help sometimes. Needed for -dip1000 compliance.
> std.uni: add scope to addInterval()

- std/array.d
We can eliminate an unnecessary `__traits(compiles, ...)` by doing this and it simplifies things for us. It doesn't look like this change is feasible for RefAppender though.
> alias std.array.Appender.opOpAssign to put

- std/algorithm/iteration.d
This PR address problems in `std.algorithm.chunkBy` when operating on non-forward input ranges. `chunkBy` has separate implementations for forward and non-forward input ranges.
The non-forward version works by instantiating a new struct to iterate over each "chunk" in the input range. One problem with the existing implementation is that the range being chunked is getting copied when these structs are created. This causes them to get out of sync if the same chunk is retrieved multiple time. This PR addresses this by passing a reference to the underlying range to these structs so these structs stay in sync with each other and with the parent range. These changes are in the `ChunkByChunkImpl` struct.
A second problem is that the existing implementation uses `empty` on the underlying range to …
> Fix Issue 19532 - chunkBy errors involving non-forward input ranges

- std/algorithm/setops.d
- std/algorithm/sorting.d
These two functions are related but play two different roles: std.algorithm.sorting.merge takes a static number of ranges of possibly disparate types (but compatible elements), and is useful for composing ranges at compile-time. However, it cannot take a variable number of ranges at runtime because all ranges must be statically known.
That latter role is played std.algorithm.setops.multiwayMerge, which takes a range of ranges to merge, and so can merge a variable number of ranges at runtime.  However, because of that, it cannot merge ranges of disparate types (of compatible elements), and so is unsuitable for compile-time range composition, unless a workaround like the range class interface is used.
The docs for these two functions should cross-reference each other so that users can more …
> [dox] Cross-reference .merge and .multiwayMerge.

- std/regex/package.d
Previously, reassigning such a wrapper resulted in the `static immutable Regex!Char` global for that pattern (`staticRe`) to be overwritten by the global for the new pattern (!). Made possible via `alias this` and the logical-const hack.
Proposed fix: keep on allowing reassignments (people are already using them), but just point to another pattern's global. So use a common Wrapper struct type wrapping a pointer instead of an empty struct type per pattern.
Bug reported in https://github.com/ldc-developers/ldc/issues/2961.
> std.regex: Fix reassignment of ctRegex wrapper structs

- std/functional.d
See also: https://github.com/dlang/druntime/pull/2442
> Use moved core.lifetime.forward for std.functional.forward

- std/range/package.d
This PR fixes a pair of bugs in the `std.range.takeOne.opSlice` implementation. This implementation is used when the range passed to `takeOne` does not support slicing.
Issue 19644 is that the implementation incorrectly asserts when the slice `end` passed to `opSlice` equals the length. This was fixed by checking `end <= length` rather than `end < length`. In addition, the text of the assert messages generated was changed to be more consistent with similar `opSlice` asserts in `package.d`.
Issue 19647 is that the implementation returns a non-empty range if an empty slice (e.g. `[0 .. 0]` is requested. This is fixed by changing the `empty` argument passed to the `takeOne` constructor function from `false` to `true`.
These issues were identified while writing code coverage unit tests for …
> Fix issues 19644, 19647 - std.range.takeOne.opSlice bugs

- std/experimental/allocator/mallocator.d
- std/file.d
- std/math.d
- std/system.d
Somehow the order got messed up by git cherry-pick.
The other parts were taken from #5358, the std.math bits were cherry-picked to dmd-cxx branch in #6838.
> [dmd-cxx] Backport non-math related patches from #5358

- std/file.d
In absence of LREF_ALTTEXT, sacrifice grammatical correctness to get a working link. There is precedence on line 4784.
Or is REF_ALTTEXT prefered, yielding a different link style?
> Fix documentation link.

- std/range/package.d
Progress to -dip1000 compatibility.
> SortedRange.opSlice() should be return scope

- std/range/package.d
This PR fixes a pair of bugs in `std.range.padRight` and adds unit tests to increase code coverage.
[Issue 19042](https://issues.dlang.org/show_bug.cgi?id=19042) is caused by an out-of-range slice access in `padRight.opSlice`. It occurs when the requested slice is entirely in within the region added added by `padRight`. This was fixed by adding a check in `padRight.opSlice`.
[Issue 19681](https://issues.dlang.org/show_bug.cgi?id=19681) is that `padRight.popFront` doesn't correctly update the `padRight.length`.
Maintaining the length value requires tracking the number of elements remaining in both the source range and the padding as elements are popped off the front or back. The original algorithm did this tracking with the same member variables whether the source range was bidirectional …
> Fix issues 19042, 19681 - std.range.padRight bugs

- std/utf.d
Remove false statement from the documentation. Fixes issue 19151.
Probably a note on what to do for LPWSTR is in place, but what that is, is not easy to say. Both suggestions from https://issues.dlang.org/show_bug.cgi?id=19151 (`cast(LPWSTR)` and `.toUTFz!(wchar*)`) are wrong. Note also that `toStringz` is fundamentally broken https://issues.dlang.org/show_bug.cgi?id=12417. The right thing is probably something like
```d
wchar[sufficient_length] str = "\0";
// or
wchar[] str = new wchar[sufficient_length];
str[] = '\0';
Win_API_func(str.ptr); // taking LPWSTR.
// Hope that Win_API_func does not store a reference.
```
> toUTF16z cannot be used for LPWSTR.

- posix.mak
Analog to https://github.com/dlang/dmd/pull/9392
> Disable OSX-32 on the auto-tester

- posix.mak
Disable the build steps For OSX 32 too.
This needs to happen in the order: Phobos, Druntime, DMD.
> Disable OSX-32 on the auto-tester (build)

- .circleci/config.yml
- .circleci/run.sh
- dip1000.mak
It has been running there for a while.
See also: https://github.com/dlang/ci/pull/259
(CircleCi is intended to be fully retired soon, see e.g. https://github.com/dlang/phobos/pull/6663)
> Disable the style_lint target on CircleCi

- etc/c/zlib/win64.mak
- win64.mak
not when setting variable. This avoids having to skillfully quote variables with spaces in them: use `"CC=%cl64%"` instead of `"CC=\"%cl64%\""`
Not sure how the existing misquoting was supposed to work. Using quotes with the command is agnostic to using `/` instead of `\` as a path separator, too.
See also https://github.com/dlang/druntime/pull/2438
> fix quoting in win64.mak: add them only when invoking command

- std/container/binaryheap.d
- std/datetime/systime.d
- std/parallelism.d
- std/traits.d
- std/windows/registry.d
As the issue 14854 suggested the body of a disable function is redundant.
> Remove redundant body of @disable functions. Issue 14854 DMD

- std/utf.d
A ForwardRange's `save()` function has a confusing relationship with the copy constructor. This helps clarify it. `save()` acts like a copy constructor, but it uses assignment semantics instead of construction semantics, carrying the seeds of bugs, besides making it impossible to call `save()` on a `const` object. This PR has `save()` use a constructor to construct the copy.
> add copy constructor to byUTF()

- std/format.d
FormatSpec should never escape the functions it is used in, so ensure it.
> FormatSpec scope parameters

- std/file.d
- Remove one unnecessary TLS variable
- Replace std.conv.to + concatenation with std.conv.text to lower the upper bound of allocations
> [Trivial] std.file: Optimize deleteme a bit

- std/stdio.d
C fclose is allowed to fail, and some libc implementations do cause it to fail. 
For example, reading on a file opened only for writing, or (in Wine's MSVCRT implementation) writing on a file opened only for reading sets an error flag, which then causes fclose to return EOF to signal an error.
However, all descriptions of the function specify that "whether or not the call succeeds, the stream shall be disassociated from the file" and "after the call to fclose(), any use of stream results in undefined behavior" (POSIX) or similar.
Currently, if File.close throws and is called again (e.g. in a destructor), it will retry the fclose call. This is undefined behavior as described above, and may potentially affect an unrelated file.
It also makes it overly difficult to "get rid" of a File …
> Fix Issue 19751 - std.stdio.File should not retry fclose after error

- std/container/rbtree.d
Returning a Node unnecessarily complicates getting it to work with dip1000.
> rbtree _add need only return a bool

- std/range/primitives.d
- std/traits.d
Regardless of how we decide how to deal with autodecoding, Phobos' dependencies on autodecoding need to be removed. By manually setting `Autodecoding` to `false`, Phobos can be gone through module by module to remove those dependencies.
> add std.range.primitives.Autodecoding

- std/range/primitives.d
- std/traits.d
This follows Phobos naming conventions and is more self-documenting.
The field has just been added by #6930.
> std.range.primitive.{Autodecoding -> autodecodeStrings}

- std/algorithm/iteration.d
- std/range/package.d
The first three of probably many functions that need to be fixed in order to resolve [issue 18657](https://issues.dlang.org/show_bug.cgi?id=18657).
Related forum discussion: <https://forum.dlang.org/post/p96gs4$22fp$1@digitalmars.com>.
I'm not sure if this is the right direction. The alternative would be to add assignment to the range interface, and remove `opAssign` from `RefRange`. That would be less busywork, and being able to use assignment with ranges might be better for everyone's sanity. But it would also be more of a breaking change.
> make `group`, `chain`, and `choose` compatible with `RefRange`

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/range/package.d
Part of a series on [issue 18657](https://issues.dlang.org/show_bug.cgi?id=18657). Previously: #6346.
This concludes std.range and std.algorithm.searching. Everything else still needs to be checked.
> make `cycle`, `splitter`, `roundRobin`, and `until` compatible with `RefRange`

- std/algorithm/searching.d
- std/datetime/systime.d
- std/random.d
- std/range/package.d
- std/string.d
This got removed when converting `foreach` over tuple to `static foreach`, but that doesn't make a difference to the slow optimizer.
These changes reduce (single threaded) compile and run time of the phobos unittests from 8min50 to 5min51 for my mobile computer.
> add workaround for slow compilation of large unittest functions

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/range/package.d
This is a fix-up of #6346 and #6935.
As far as I understand, @WalterBright favors this style (cf. #6900, #6903).
Most of these are straight forward, but `chain` and `roundRobin` are still a bit awkward, because they involve tuples. We don't have some kind of `map` for tuples in Phobos, do we?
> use constructors instead of `move`

- std/range/primitives.d
Refer to discussion in https://forum.dlang.org/post/q7tvg0$2tdn$1@digitalmars.com.
> Relax `const` requirement for empty primitive

- std/net/curl.d
Handling bugzilla 7018 is still valid here, however exiting immediately will cause _d_dso_registry to unregister in the wrong thread.
Just returning gracefully from the loop won't cause the testsuite to hang, checked on host without libcurl installed for both native and multilib (-m32 and -mx32).
> std/net/curl.d: Don't call exit in non-main thread

- std/experimental/allocator/building_blocks/region.d
- std/math.d
The asm bits are of course not included.
> Add minimum RISCV support to phobos

- std/traits.d
This currently blocks: https://github.com/dlang/dmd/pull/9585 . The test can be uncommented and fixed after the dmd PR is pulled
> Comment broken test in std/traits.d

- std/stdio.d
Context: https://forum.dlang.org/post/mqzblhbrweydjlcjdppj@forum.dlang.org 
1. Extra parameter validation when compiling for `CRuntime_Microsoft` to prevent ungraceful process termination. Fixes issue 19797. This is a workaround for what looks like a bug in Microsoft's `_fseeki64`.
2. Improved documentation.
> Fix issue 19797 - Ungraceful termination in File.seek() on Windows

- posix.mak
We must have a symlink to the soname because
otherwise it is problematic to link the shared
library.
Before this patch to distribute phobos it was
necessary to manually create the symlink
(e.g. https://github.com/dlang/installer/blob/482840bf5bd8e94ebb12aabaa7ddb0dac319be90/linux/dmd_phobos.sh#L169),
this was a really uncomfortable and confusing solution
for external package maintainers.
This symlink was actually already created in the
phobos build phase but for some reason unknown to
me was not copied into the installation target.
I also noticed that the libphobos2.so symlink is
already created, so I simply removed the redundant
symlink creation with a simple copy from generated/$(OS)/$(BUILD)/$(MODEL)
Signed-off-by: Ernesto Castellotti <erny.castell@gmail.com>
> Make the symlink for phobos soname

- std/math.d
This should hopefully contain only uncontroversial changes required to build phobos for MinGW. We have to hurry a bit to get this still into GCC-9, as that will likely be released next friday.
Related druntime PR: https://github.com/dlang/druntime/pull/2586
Related GDC PR: https://github.com/D-Programming-GDC/gcc/pull/14
ping @ibuclaw @redstar
> [GDC] GCC9 last-minute fix: MinGW changes to get phobos to build

- std/math.d
> [dmd-cxx] GCC9 last-minute fix: MinGW changes to get phobos to build (backport #6980)

- std/range/package.d
- unittests did fail with DIP1000 due to missing return scope
inference in chained range, thus leading to a scope violation
which prevented `@safe` inference
- fixed unittests by adding return scope to chain.Result
- would still fail under dip1000 with other ranges that
miss return scope on their opSlice
- should not have any effect on non-DIP1000 usage
> fix Issue 19777 - SortedRange.opSlice should infer safety

- std/random.d
On 64-bit architectures use 64 bits of entropy to initialize thread-local `rndGen`.
The motivation for this change is std.uuid defaults to using `rndGen` to generate UUIDs. If every `rndGen` starts in one of 2^^32 states then if 77000 independent programs each generate a single UUID there is a 50% chance that at least two of them generate the same initial UUID (and all subsequent UUIDs would be identical as well). Not just Phobos but also C++ `boost::uuids::random_generator` defaults to generating UUIDs with a Mersenne Twister initialized from a 32-bit seed, exacerbating the collision problem further. If instead there are 2^^64 possible initial states of `rndGen` there can be over 5 billion independent `rndGen`s before there is a 50% chance of two having identical initial states.
This …
> Fix Issue 19836 - Excessive probability of UUID collisions in std.uuid.randomUUID

- std/mmfile.d
Not to mention that CRuntime_Glibc wrongly assumes that it is synonymous with linux.
> std.mmfile: MAP_ANON is only defined in core.sys.posix.sys.mman

- std/algorithm/searching.d
Reverts dlang/phobos#6960. Reason: `foreach` does not auto-decode `string` & `wstring`.
> Revert "Decrease template instantiation in std.algorithm.searching : all & any"

- std/numeric.d
Benchmark using DMD, 10 million trials:
| version | arg type  | compiler | time (ms) |
|---------|-----------|----------|-----------|
| old     | float[3]  | dmd -O   | 118.503   |
| new     | float[3]  | dmd -O   |  64.535   |
| old     | float[4]  | dmd -O   | 120.456   |
| new     | float[4]  | dmd -O   |  74.575   |
| old     | float[5]  | dmd -O   | 141.211   |
| new     | float[5]  | dmd -O   |  99.659   |
| old     | float[6]  | dmd -O   | 151.537   |
| new     | float[6]  | dmd -O   | 107.559   |
| old     | float[7]  | dmd -O   | 192.009   |
| new     | float[7]  | dmd -O   | 137.358   |
| old     | float[8]  | dmd -O   | 176.876   |
| new     | float[8]  | dmd -O   | 147.655   |
| old     | float[9]  | dmd -O   | 200.092   |
| new     | float[9]  | dmd -O   | 167.429   |
| old …
> Fix Issue 6657 - dotProduct overload for small fixed size arrays

- std/random.d
Only the two-argument form had this undocumented requirement.
> Fix Issue 19837 - std.random.isUniformRNG(Rng, ElementType) should not require Rng.front to be annotated `@property`

- std/typecons.d
`Nullable(T, T nullValue)` special-cases floating point numbers but this doesn't account for all types where `nullValue != nullValue`. For instance:
https://run.dlang.io/is/hiLncI
```d
struct S
{
float f;
}
void main()
{
import std.typecons : Nullable;
alias N = Nullable!(S, S.init);
assert(N(S.init).isNull); // Fails!
}
```
> Fix Issue 19226 - std.typecons.Nullable(T, T nullValue) doesn't fully handle non-self-equal nullValue

- std/meta.d
> Implement aliasSeqOf for all iterables

- std/conv.d
- std/typecons.d
This PR represents two minor upfront fixes to make the DMD 9029 fix pass. (With 9029, primitive types can be passed to alias parameters same as named types.)
> Fix issues arising from the DMD 9029 fix (types match to alias)

- std/array.d
I was trying to filter out an assocArray and transforming the result back into an assocArray again for debugging in dub, and got the error message "assocArray: argument must be a range of tuples". Expanded it to include the actual type.
Also I noticed that the static assert was never hit in a test, so I've written a trivial test for it.
> Improved error message when an assocArray can't be created

- std/traits.d
Explicitly stated that the enum name can be retrieved with __traits. There was a unittest for this, but it was not stated in the documentation.
I've added an example to generate a switch-statement with static foreach. Furthermore, I removed the generate example from the documentation, as (in my eyes) it is basically a duplicate of the square root example.
Suggestions for improvement are appreciated.
> Added description to EnumMember documentation to get name of value

- posix.mak
With https://github.com/dlang/dmd/pull/9476, this could work now ...
> Build entire Phobos with -preview=dip1000

- changelog/phobos-dip1000.dd
Follow-up to https://github.com/dlang/phobos/pull/6931
> Add changelog entry for -dip1000

- changelog/new_schwartzSort_overload.dd
- std/algorithm/sorting.d
The goal is to be able to specify a `SwapStrategy` without also explicitly specifying the predicate to sort by (see example in the ticket, changelog, or the test I added).
> Fixed Issue 13965 - More handy schwartzSort

- std/random.d
Changed the private enhanced seeding method for `rndGen` to something that is fast on both 64 bit and 32 bit machines so can be enabled regardless of architecture. When compiled with LDC it is about 1.35x the speed of public `Mt19937.seed(uint)`.
> Issue 19836 followup - also fix on 32 bit machines

- std/algorithm/internal.d
The check-and-initialize pattern dates back to when `rnd` was seeded with `unpredictableSeed`. With a fixed seed that's unnecessary.
> Remove unnecessary check-and-initialize in std.alorithm.internal.rndstuff

- std/parallelism.d
Necessary because with the change an rvalue can be an argument to a ref parameter.
> add isLvalue() to prepare for rvalue ref

- std/range/primitives.d
This should make it work when rvalues can be converted to ref parameters.
> hasLvalueElements(): use overloading to detect lvalue

- std/experimental/typecons.d
Relying on rvalues not converting to ref param is no longer viable.
> fix rvalue test for Final

- std/math.d
To test that at least one bit in the mantissa is set, it's faster to just test for inequality instead of one more masking and an AND.
> Faster isNaN test

- std/datetime/date.d
- std/datetime/systime.d
This prevents the compiler from executing the initializers using CTFE during importing, when using unittest.
This works around issue [19874](https://issues.dlang.org/show_bug.cgi?id=19874)
ping @jmdavis
> Change version(unittest) code to use accessors to wrap the static initializers

- std/typecons.d
- std/uni.d
- std/utf.d
> Use selective top-level module imports in std.{typecons,uni,utf}

- std/path.d
- std/range/package.d
- std/regex/package.d
> Use selective top-level module imports in std.{path,range,regex}

- std/functional.d
- std/getopt.d
- std/math.d
- std/net/isemail.d
- std/outbuffer.d
> Use selective top-level module imports in std.{functional,getopt,math,net,outbuffer}

- std/base64.d
- std/csv.d
- std/datetime/date.d
- std/datetime/timezone.d
See also: https://github.com/dlang/phobos/pull/7024
> Use selective top-level module imports in std.{base64,csv,datetime}

- std/bitmanip.d
Fixes Issue 19899 - std.bitmanip.bitsSet should accept const arguments. This also makes `swapEndian` not propagate `const` to its return value which is arguably an improvement (see https://github.com/dlang/phobos/pull/6682#discussion_r213024113).
> `const`ify scalar arguments in std.bitmanip to reduce IFTI template bloat

- std/stdio.d
- std/string.d
> Use selective top-level module imports in std.{stdio,string}

- std/math.d
All these tests call directly or indirectly `resetIeeeFlags` which throws "Not yet supported" if inline assembly isn't supported.
> math.d: disable inline asm tests if unsupported

- std/socket.d
Work on project [#2](https://github.com/dlang/phobos/projects/2)
> Add messages to some asserts in std/socket.d

- posix.mak
Currently, phobos is using `-defaultlib=` to build itself, but is implicitly relying on its library dependencies to be added by dmd.
This change makes the phobos library dependencies explicit rather than relying on its dependencies to be hardcoded into the compiler, which in turn forces all D programs to link to those libraries as well.
This change is required to allow https://github.com/dlang/dmd/pull/9831 to be merged, which removes these implicit libraries from being linked to ALL D programs that use DMD to link.
> Explicitly link to pthread

- std/experimental/allocator/building_blocks/region.d
brk support has been removed from DragonFlyBSD
sbrk has been declared deprecated
mmap() is suggested as a replacement for sbrk()
> (s)brk support has been removed from DragonFlyBSD

- std/range/package.d
blocks and requires DMD https://github.com/dlang/dmd/pull/9889.
> Ternary operator no longer promotes characters to integers

- std/range/package.d
> Ternary operator no longer promotes characters to integers [Part 2]

- changelog/count_processors_via_sched_affinity_on_linux.dd
- std/parallelism.d
Currently std.parallelism.totalCPUs is implemented by
sysconf(_SC_NPROCESSORS_ONLN) on Posix platoform. However, on GNU/Linux,
usable number of processors may be restricted if a process runs in
container. In case it's better to use sched_getaffinity(2).
ref: http://man7.org/linux/man-pages/man1/nproc.1.html
> Fix Issue 19513 - Use sched_getaffinity(2) to get the number of CPU cores if abailable

- etc/c/sqlite3.d
Since the SQLite 3 bindings have been outdated since about 2016, I decided to update them to the latest version of SQLite available
This is a work in progress and I would be grateful if someone with more experience than me about CAPI3REF could analyze this update attempt, thanks
> Update header of sqlite3 to 3.28.0

- std/string.d
starting to work on dlang/phobos/project/2
> assert messages for std.string

- posix.mak
Second pass of https://github.com/dlang/phobos/pull/7021
Looks like we also need `-lm`.
> Explicitly link to math library

- std/process.d
This PR is in support of https://github.com/dlang/dmd/pull/9978
`forkChild` is much too large to be inlined, but noone knew about it until now because `std.process` is not being compiled with the `-inline` flag and because of [Issue 15110](https://issues.dlang.org/show_bug.cgi?id=15110) which https://github.com/dlang/dmd/pull/9978 attempts to fix.
See the output of the CIs in https://github.com/dlang/dmd/pull/9978 for more information.
> std.process.forkChild cannot be inlined

- std/datetime/timezone.d
FuncType is actually `@system` because of this, for some reason it is still `pure` and `nothrow`.
> function attributes go on the right of function aliases

- std/range/primitives.d
It's important to mention this (first), particularly so the user notices the auto-decoding overloads.
> [docs][std.range.primitives] Add links to array range primitives

- std/range/primitives.d
The Win32_64 linker error that prevented this from being included in PR #6743 no longer occurs in CI.
> Add `inout` to range.front to reduce template proliferation

- std/variant.d
Issue: [19987](https://issues.dlang.org/show_bug.cgi?id=19987)
Swapping the `fptr` and `union` around will avoid larger alignment.
> 19987 - Reduce memory used by VariantN

- changelog/std_json_trailing_comma.dd
- std/json.d
I recently encountered a lot of json files with trailing comma's.
std.json rightfully rejected them, but then I kind of really needs to accept them anyway.
This PR allows std.json to ignore trailing comma's.
> std_json allow trailing comma

- changelog/remove-nullable-alias-get-this.dd
- std/typecons.d
This PR deprecates `alias get this` in Nullable.
Nullable effectively creates a "pointer type" out of a regular type, with the addition of a null state that throws an error when trying to access the contained value of an empty `Nullable` with `Nullable.get`.
However, this conversion may happen implicitly.
In the short term, all code that takes advantage of the implicit conversion of `Nullable!T` to `T` will print a deprecation warning, or fail with `-de`. Needless to say this is a **breaking change**.
For better or worse, `Nullable` has become the de-facto type for making a value optional. 
However, it also includes functionality to implicitly call its getter, throwing an error on failure. It is thus to my knowledge the only implicit conversion in the language that can error at runtime. …
> [Breaking] Deprecate `alias get this` in Nullable.

- changelog/errnoexception-errno-attributes.dd
- std/exception.d
I think the field could be a public const(uint) instead; without a property accessor. However, doing so would be a breaking change.
>  Make ErrnoException.errno nothrow pure @nogc @safe 

- std/experimental/allocator/building_blocks/stats_collector.d
- std/parallelism.d
- std/socket.d
This currently blocks [1]. The enum is declared as an integer, but it is assigned to ushort variables. This worked due to a bug in dmd which is now being fixed.
[1] https://github.com/dlang/dmd/pull/10099
> Fix enum type in std.socket to match the receiver type

- changelog/std-file-getAvailableDiskSpace.dd
- std/file.d
> Fix Issue 16487 - Add function to obtain the available disk space

- std/concurrency.d
So... Do people actually use this module ?
I have a test library which spawns `Thread` to simulate Vibe.d servers. Within each node, I need to replicate a simple, re-entrant event loop. I tried to use a local `scheduler` (thread-local) as I don't want to mess with a global instance (why do we even have one to begin with ? The user can define that on their own if they need it...), but it seems this use case hasn't been tested.
> Make locally-defined `FiberScheduler` actually usable

- std/algorithm/mutation.d
- std/traits.d
This PR implements the Phobos side of [DIP1014](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1014.md).
Needs https://github.com/dlang/druntime/pull/2638 to be merged first.
> Implement Phobos side of DIP1014

- std/bitmanip.d
Follow up to https://github.com/dlang/phobos/pull/7098  (I missed one)
In support of https://github.com/dlang/dmd/pull/10130
> Replace D1 operator overloads with D2 operator overloads - Part 2

- std/regex/internal/ir.d
- std/regex/package.d
Even though this does change the behavior of an existing function, it doesn't seem likely that this will be a breaking change. A capture could never be `null` previously (unless, I guess, the haystack string was itself `null`), and I can't think of reasonable situations where the null/non-null distinction of an empty string would be an issue here.
> Fix Issue 19979 - std.regex should return null instead of zero-length slice for non-matched captures

- std/container/array.d
LDC 1.15 and GDC with optimizations enabled recognize that `mulu` with a second argument of 1 will never overflow and elide unnecessary operations but DMD and LDC 1.14 do not.
> Avoid mulu in std.container.array.Array!T when T.sizeof == 1

- std/typecons.d
- std/variant.d
Previously, self-referential `Algebraic` types using `This` could not be nested, since the outer `Algebraic` instance would replace the inner `Algebraic`'s `This` argument when computing `AllowedTypes`, leading to a recursive template expansion. With these changes, each occurrence of `This` in `Algebraic`'s argument list is replaced only by the inner-most `Algebraic` instance that contains it. This ensures that no occurrence of `This` is ever replaced more than once.
These changes are based on pbackus/sumtype@5a6136855acd9e7f3ab7c421fc2f531055114240, which fixed an analagous issue in the `sumtype` DUB package.
> Fix issue 19994 - Can't nest self-referential Algebraic types

- std/traits.d
Issue 19105 was reported as a compiler bug. The reported code is:
```d
module junk;
struct A(Args...) {}
struct B {}
alias C = A!( getSymbolsByUDA!(junk, B) );
```
But reading the docs of `getSymbolsByUDA`is seems that it was meant to work only with aggregate declarations (not with modules). I added a template constraint that requires that the symbol passed is an aggregated type.
The code fails because while getting the members of `junk`, the innards of `getSymbolsByUDA` uses aliases for the list of symbols and at some point alias C ends up aliasing to something that aliases itself.
> Fix Issue 19105 - Bogus recursive template expansion via getSymbolsByUDA

- std/file.d
In support of https://github.com/dlang/dmd/pull/10179
`in` as a parameter storage class is defined as `scope const`.  However `in` has not yet
been properly implemented so its current implementation is equivalent to `const`.  Properly
implementing `in` now will likely break code, so it is recommended to avoid using `in`, and
explicitly use `const` or `scope const` instead, until `in` is properly implemented.
The use of `in` as a parameter storage class is already discouraged in the documentation.  See https://dlang.org/spec/function.html#parameters
> Replace usages of `in` with `const scope`

- std/stdio.d
This is needed for https://github.com/dlang/druntime/pull/2604  otherwise wait(&status) returns given the termination of child spawned by the GC mark
> use waitpid for unittest

- std/file.d
- std/math.d
Changing floating point rounding modes, because it happens off to the side, interferes with optimizing. In particular, common subexpressions may not be common if the rounding mode is changed.
Solutions are:
1. disable CSEs for floating point (what dmd used to do). Not doing CSEs for floating point is kinda sad.
2. make a compiler intrinsic for changing the rounding mode, so the optimizer knows about it, this would be a fair amount of rewrite both for the optimizer and std.math.
3. change the code that mucks with the rounding mode so it won't interfere with optimization
This does option (3).
> std.math: change tests for rounding

- std/experimental/allocator/package.d
Making a shared value object currently fails with a message 'template std.conv.emplaceRef cannot deduce function from argument types...'. This PR fixes that.
> Get make!T to compile when T is a shared value type

- etc/c/curl.d
- etc/c/sqlite3.d
- posix.mak
- std/algorithm/comparison.d
- std/experimental/allocator/building_blocks/package.d
- std/experimental/checkedint.d
- std/functional.d
- std/math.d
- std/parallelism.d
- std/path.d
- std/range/package.d
- std/regex/package.d
- std/typecons.d
- std/uni.d
This PR does two things:
1. Adds the `-preview=markdown` flag to the Phobos Ddoc build.
2. Fixes places in the docs that were unintentionally interpreted as markdown.
The fixes were generally for:
* Lines that start with `-`, `+` or `*`, which in Markdown starts a list item.
* Backslashes that aren't in code blocks, and so are treated as escaping the next character.
* Words in brackets that aren't in code blocks, which Ddoc treats as [reference links](https://dlang.org/spec/ddoc.html#reference_links) to symbols with the same name.
> Turn on -preview=markdown

- std/range/package.d
```
The deduced type for `Enumerator` could contain type modifier
(`const`, `immutable`), but the type was used directly as
a state variable.
```
> std.range.enumerate should work with a non-mutable start index

- changelog/array-opslice.dd
- std/array.d
When building an array, the natural way to get the array is with opSlice(), not data().
> Appender and RefAppender: use opSlice() instead of data()

- std/typecons.d
ReplaceType no longer gives incorrect results for types that can be
implicitly converted to a templated type, either via inheritance (19697,
16132) or alias this (19696).
An attempt to address this issue was made in PR #6880, but it did not fix the inheritance-related issues, and appears to have been abandoned by its author.
These changes are based on pbackus/sumtype@b764942.
> Fix issues 19696, 19697, 16132 - ReplaceType bugs

- std/regex/internal/ir.d
- std/regex/package.d
Demonstrative program:
```d
import std.regex : regex;
import std.stdio : writeln;
void main() {
auto pattern = regex("s+", "U");
writeln(pattern);
}
```
Current output:
>Regex!char([], [Bytecode(2147483763), Bytecode(2231369729), Bytecode(2147483763), Bytecode(2248146945), Bytecode(0), Bytecode(2550136833)], [], 1, 0, 1, 5, 8, [], [], [], Kickstart!char([4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, …
> Fix Issue 20098 - Improve result of printing std.regex compiled pattern

- std/concurrency.d
Allow SysTime to be sendable with std.concurrency.send
> Fix issue 20097

- std/stdio.d
It wasn't clear on inspection if buf could be shortened, or if it was just lengthened. "As necessary" suggested that buf would only be resized if absolutely necessary, which would only be when it needs to be lengthened.
> Clarify that buf can be shortened in readln

- std/array.d
With autodecode turned off, the return value wasn't a `dchar[]`.
First fix for https://github.com/dlang/phobos/pull/7130
> fix array(String) to work with no autodecode

- std/array.d
Another step for https://github.com/dlang/phobos/pull/7130
> fix unittests for array.join() for no autodecode

- std/uni.d
With autodecoding off (and thus `char[]`/`wchar[]` now being random-access ranges), both the range and array `match`/`skip`/`test` functions accepted a `char[]` / `wchar[]`.
> std.uni: Disambiguate templates with autodecoding off

- std/stdio.d
The code compiled and ran, but behaved differently.
The silent breakage was due to the implicit conversion of `char` to `dchar`. Forbidding such conversions would prevent the silent breakage.
> std.stdio: Fix failing unittest with no autodecode

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/range/package.d
As preparation for dlang/dmd#10124, which makes elements of array literals rvalues, so this trick for converting a string literal to an lvalue doesn't work anymore.
> Rewrite dubious refRange() shortcuts in unittests

- win32.mak
- win64.mak
Unfortunately, these files seem untested by CI here, but they are used by Azure pipelines for DMD, so one can easily [break](https://dev.azure.com/dlanguage/dmd/_build/results?buildId=4086) DMD CI by a seemingly fine Phobos change (#7142 in this case, which requires DIP1000). From: https://github.com/dlang/phobos/blob/a2b9977f9b26476264b76034a32c15615dd7af54/posix.mak#L142
> win*.mak: Sync compiler flags with Posix ones

- std/array.d
The type of the assocArray winds up different.
https://github.com/dlang/phobos/pull/7130
> fix assocArray() unittests for no autodecode

- std/utf.d
UTFException should actually be replaced with UnicodeException, but there are some slight differences in behavior, sigh.
> UTFException should derive from UnicodeException

- std/conv.d
- std/format.d
The entire instantiated template hierarchy there actually can't compile or work with a narrow char type, because at some point it wants to decode an escape, which will fit only in a `dchar` anyway.
For https://github.com/dlang/phobos/pull/7130
> std.format: Fix compilation with no autodecode

- std/utf.d
Makes `byUTF()` more of a drop-in replacement for autodecoding.
> std.utf.byUTF: add option to throw on invalid UTF

- std/process.d
In current phobos policy, local imports should be preferred over global
imports.
> std.process: use local imports

- std/variant.d
Accomodate for the fact that a `VariantN!24` without explicit allowed types is at least `real` aligned, and that can be 8 on some platforms (e.g., 32-bit Windows for LDC with 64-bit `real`), so that the size is aligned up to `24+4 + /*padding*/ 4 = 32`.
> [stable] Fix std.variant unittest

- .circleci/config.yml
- .circleci/run.sh
*Edit (see GH message history if needed):*
* Upgrade `HOST_DMD_VER` from `2.078.1` to `2.079.1`, to match the dmd CircleCI build
* Use `../dmd/scr/build.d`, instead of `../dmd/src/posix.mak`, because `BUILD=debug` is broken since dlang/dmd#10212 (comment)
* Merge `gdb` download step into `install_deps`
> Fix CircleCI build

- std/net/curl.d
https://dlang.org/phobos/std_net_curl.html#.HTTP
The Example seems to not work without these fixes.
* Fixed missing http variable
* Fixed deprecated concatenation 
```
Error: Implicit string concatenation is deprecated, use "http://upload.wikimedia.org/wikipedia/commons/" ~ "5/53/Wikipedia-logo-en-big.png" instead
```
> std.net.curl: Fix example in HTTP documentation

- std/random.d
In support of https://github.com/dlang/druntime/pull/2777
> Replace `sizediff_t` with `ptrdiff_t` in std.random.d

- std/format.d
See also: https://forum.dlang.org/post/tdgiytvqpyxevjtqgbao@forum.dlang.org
> get rid of some GC allocations in `sformat` and `formatElement`

- .dscanner.ini
- std/array.d
We can delay the std.format import until the relevant templates are instantiated.
This brings the filesize from 1114048 to 908544 bytes.
CC @JackStouffer
> Fix Issue 20186 - File size of "Hello, world" executable increased by 185KB

- std/bigint.d
Split off as its own PR separate from #7151 because there is a single mathematically correct way to compare numbers without needing to consider rounding mode.
> Fix Issue 20147 - Enable comparison (==, >, >=, <=, <) between std.bigint.BigInt and floating point numbers

- std/datetime/stopwatch.d
Times on benchmarks are not generally comparable (think of the computer heavily swapping during the first benchmark while not doing so during the second). I removed three asserts, which cannot generally be asserted and replaced them with two asserts, which give weaker, but save upper bounds.
> Fix issue 20145 - Random unittest failures in std.datetime.stopwatch

- std/container/dlist.d
@Geod24  found some typos after the fact https://github.com/dlang/phobos/pull/7191
> assert messages container dlist typo fix

- changelog/unconst.dd
- std/traits.d
Existing ˋstd.traits.Unqualˋ removes all qualifiers from a type. Quite often that is a bit too aggressive, because it would also strip off 'shared'. ˋUnconstˋ (which already exists in ˋcore.internal.traitsˋ) is helpful in such cases. This PR adds an alias for ˋUnconstˋ to ˋstd.traitsˋ, very similar to what is already there for ˋUnqualˋ.
> Add Unconst to std.traits

- std/concurrency.d
Unfortunately `PAGESIZE` is private so I can't use default arguments like in `core.thread.Fiber`.
> FiberScheduler: Make the stack size configurable

- std/parallelism.d
This example seems to not have worked ever.
You cannot create a delegate to an uninstantiated template function, and for the task() template function to be able to deduce a function, all optional parameters to read() need to be given.
The delegate issue is kind of obvious. The default parameter issue I don't know whether is a compiler limitation that could be lifted or not.
These fixes make the example less pretty, especially compared to the example of the other overload of task(), but is it how it is.
Runnable variant: https://run.dlang.io/is/WAns8z (not for publication)
> Make task() example compilable.

- std/zip.d
Even on posix systems you cannot rely on unzip being installed. In such cases, the unittest will fail, but should not fail.
> Remove posix only unittest relying on presence of unzip untility.

- std/internal/test/dummyrange.d
- std/math.d
In issue 15881 and 15763 people complain about unintuitiv behaviour of approxEqual. I adapted the documentation of the function to address this.
a) Symmetry: I renamed the first two parameters to make clear, that they have different meaning. Also changed the wording in the documentation and added more unittest to clearify.
b) Purpose of the two checks: I made clearer, why two checks are run (basically, one for numbers close to zero and one for all other) and that passing one check is sufficient. Added unittests to document this.
Additionally I added some more unittests. E.g. for testing 3rd and 4th parameters and for some strange results and cornercases.
I did not change the behaviour of the function, let alone, I removed an (almost) superfluous overload - almost, because an alias in …
> Clearer documentation for approxEqual

- std/zip.d
I replaced the link below "zip archive" to the wikipedia entry, because the old link points to the zip/unzip utility webpage which contains information about this utility but not about zip archieves in general.
Further: From the 6 listed bugs, the first four are no bugs, but just limitations of the current implementation. Bug 592 is "won't fix", refering to D1; Bug 2137 is allready fixed. Therefore I removed the two real bugs and replaced the headline by "Limitations".
> std.zip: Update and correct main documentation

- std/zip.d
This is a preparation step for recognising overlapping data chunks, which eventually will solve the main problem of issue #20027.
Later, each found chunk will be removed from _seg. When overlapping chunks exist, removeSegment will notice, that an allready removed part shall be removed and throw an exception.
> std.zip: Add data structure for detecting overlapping chunks.

- std/algorithm/sorting.d
- std/range/package.d
This may reopen issue 12661. I checked this and I think it does not reopen. But IMHO someone else should confirm this.
Anyway, I think, the original fix for 12661 did not fix the real problem, but was more of a hack inducing issue 15230.
> Fix Issue 15230 - Inconsistent std.range.SortedRange predicate checks

- std/zip.d
This PR removes three public items: digiSignLength, eocd64LocLength and eocd64Length. They are replaced by private enums with names taken directly from the specs, making all names consistent.
Theoretically they should go through a deprecation process. But it's hard to imagine a usecase, where someone used these constants outside of std.zip. In my oppinion they should have been private from the very beginning.
> std.zip: Replace magic constants by constants named after specs

- std/math.d
As suggested in the discussion of this issue, I documented that it cannot be used with int.min.
> Fix issue 20205 - std.math: Wrong result for abs(int.min)

- std/zip.d
The lines around 640 where wrongly indented. I corrected them, although this is not directly related to the bug fix. Hope, this doesn't disturb.
> Fix issue 20239 - chameleon zip-file should be rejected by std.zip

- std/algorithm/iteration.d
- std/typecons.d
Unexpected/unhandled compiler message cause testsuite failures in gdc.
The content of the message suggests this is a deliberate deprecation, rather than a bug in druntime.
> Silence warning: struct Rebindable has method toHash, however it cannot be called with const(Rebindable!(const(C))) this.

- std/zip.d
While working on issue 20027 I noticed this bug. It's there because someone assumed, that the namelength and extralength are the same in the central directory and the local file header. This is not necessarily the case, even in correct files (assuming, that my local zip utility produces correct files).
> Fix issue 20287 - std.zip: Wrong compressed data

- std/zip.d
This fixes the main problem of 20027, namely rejecting zip bombs. I moved all remaining problems to own issues (20290 - 20294). Therefore this issue can be closed with this PR.
There is one unittest missing, namely checking for overlaps of zip64 central dir records with other stuff. This unittests needs to be postponed due to a bug in the implementation of zip64 (see issue 20289).
I verified, that it indeed rejects the zip bombs zbsm.zip and zblg.zip mentioned in the issues. The zip64 zip bomb zbxl.zip does not work yet due to bugs in the zip64 implementation, probably introduced by me in PR #7198. I'll fix this as soon as possible.
I also checked some normal zip-files to make sure that the size of _segs is always O(1).
> Fix issue 20027 - std.zip susceptible to zip malware attacks

- std/mathspecial.d
The two functions use *standard* normal distribution, which implies that mean=0.0, stdev=1.0.
In the bugreport is stated, that reportee was not able to follow the implementation for the case z>=1. Me neither. But as the case z<1 is obviously the standard normal distribution it would be an error, if the case z>=1 would be some other distribution. I compared some computed values to the [table given in the German Wikipedia](https://de.wikipedia.org/wiki/Standardnormalverteilungstabelle) and found no difference.
> Fix Issue 19283 - [std.mathspecial] documentation for normal distribution doesn't list parameters

- std/zip.d
This is PR #7224, but rebased on stable (I probably got something wrong while rebasing, therefore a new PR, sorry), as it's now a real regression...
> Fix issue #20295 - std.zip: zip64 with 0xff bytes in end of central dir record do not work

- std/functional.d
- std/regex/package.d
This PR includes the following commits:
* Fix issue 20302 - Support head const in memoize
Make `std.functional.memoize` accept functions whose return types or parameters are head const.
* ~[refactor]: Simplify memoize(alias fun) implementation~
* ~Use `object.require` to save one hash table lookup~
* ~[style] Consolidate imports~
* Fix Issue 20301 - Support const array of patterns in std.regex.regex
> Fix issues 20301 and 20302

- std/numeric.d
There were actually two bugs in here, that cancelled out in most cases.
First, flags.nan was used instead of Flags.nan.
Second, it was tried to mix the substraction of 1 in case of infinity or nan with the addition of 1 that's needed by definition, by using ~flags instead of flags, which does not always work. Although it's probably possible to find a term that mixes that, I separated these two terms. The speedgain would be little and done at compile time anyway.
> Fix Issue 20283 - CustomFloat.max_exp not working in some cases

- std/numeric.d
If Flags.storeNormalized is *not* set, we have to subtract one from the precision, because one bit is used for the leading 1.
Due to this bug it was never possible that shiftcnt==64 and a second bug in the next line went unnoticed. I fixed that one too.
> Fix Issue 20282 - CustomFloat.dig fails at some values.

- std/algorithm/comparison.d
- std/algorithm/searching.d
This is a replacement for PR #7181, because I had to delete my old account on github. Here my original comment:
The discussion of issue 10448 and of the related pull requests show, that there is no consensus on the best result of min and max, when some parameters are NaNs, even experts, namely people who where involved in writing IEEE754, cannot agree on that. But most people agree, that the functions should be fast and extra treatment for NaNs would slow them down. Therefore, I think, the best solution is to document, that the functions will result in undefined behaviour if NaNs are used and give examples on how to cope with NaNs beyond using this functions.
In the documentation for minElement I added two such examples, namely for ignoring NaNs and for returning NaN in case at least one …
> Fix Issue 10448 - min and max are not NaN aware

- std/algorithm/searching.d
This is a followup on PR #7240. Fixing documentation at some more places, where NaNs do not work as expected.
> More min and max are not NaN aware.

- std/conv.d
- std/format.d
std.format with separator and double causes RangeError
https://issues.dlang.org/show_bug.cgi?id=20288
> Fix Issue 20288 - std.format with separator and double causes RangeError

- std/stdio.d
```
Value '3' is a valid value on Linux (SEEK_DATA, since 3.18).
Hence, in some cases (depending on FS support / Kernel version),
this test can fails.
```
If you're curious, more info [here](https://github.com/alpinelinux/aports/pull/11931#issuecomment-544831142).
> Make tests for issue 19797 Windows-only

- std/numeric.d
I completely rewrote the code, because I think it's difficult to give the bit patterns of epsilon directly (*). There are so many exceptions and quirks around, where you allways have to consider all the flags involved. There are cases, where epsilon is a denormalized number, there are cases, where epsilon does not exist in that type and so on.
My solution here is, not to care about this at all. What I do is to take the value 1, calculate 1+epslion from it by setting the least significant bit of the mantissa to 1 and subtract the value 1 from it. (This is not CTFE though.)
There are obviously cases, where this doesn't work. For example when 1 cannot be represented by that type or 1+epsilon=infinity, but infinity does not exist or where epsilon cannot be represented. As far as I can see, …
> Fix Issue 20261 - CustomFloat.epsilon yields infinity

- std/math.d
Fixes the CTFE test for gdc when x is real.infinity.  It fails as an inf result from ldexp is treated as an overflow in gcc's const fold internals.
> std/math.d: Explicitly handle zero and inf in scalbn.

- std/format.d
This prevents `isInputRange` from noticing that `Nullable!string` is technically an input range (because string is) and hitting the `.get` deprecation.
> Fix issue 20328: only check isInputRange when we've already excluded toString overload.

- std/digest/package.d
- std/string.d
This would unblock [the dmd PR changing `in` to mean `const scope`](https://github.com/dlang/dmd/pull/10506).
> Add `scope` preparing for `in` to become `const scope`

- .circleci/run.sh
And replace the default of 2 with the number of cores.
> Allow user to override number of threads in circleci script

- std/format.d
Probably overlooked in PR #7222.
> Fix Issue 20357 - format should obey space flag when printing nan or inf

- std/numeric.d
When trying to do more covering for findRoot I noticed, that all unittests where commented out. I tried to find out, why this happend. It was in 2009 in commit 0c1429... The reason was probably, that an erroneous assert inside of testFindRoot was added and with little time left (the next release was due), the solution was to comment out the unittests.
I fixed the assert (although I think it's not 100% correct now, because one of the numbers could be 0 and the other >=0 which means, both have the same sign and still the call is correct; maybe, the assert should be removed alltogether?).
> Reactivate unittests for findRoot

- std/algorithm/setops.d
- std/parallelism.d
- std/process.d
- std/random.d
Top10 before:
0.190s PASS release64 std.datetime
0.246s PASS release64 std.uni
0.296s PASS release64 std.uri
0.302s PASS release64 std.socket
0.447s PASS release64 std.digest.sha
0.678s PASS release64 std.datetime.systime
2.066s PASS release64 std.random
3.492s PASS release64 std.parallelism
5.003s PASS release64 std.algorithm.setops
5.099s PASS release64 std.process
Top10 after:
0.192s PASS release64 std.datetime
0.248s PASS release64 std.uni
0.251s PASS release64 std.algorithm.setops
0.298s PASS release64 std.uri
0.305s PASS release64 std.socket
0.447s PASS release64 std.digest.sha
0.653s PASS release64 std.datetime.systime
0.875s PASS release64 std.parallelism
0.917s PASS release64 std.process
1.370s PASS release64 std.random
For std.process I checked the time needed on my computer, it …
> Fix Issue 10902 - some phobos unittests take an excessive amount of time

- posix.mak
We don't want to compile -betterC test files with -unittest because this
will also compile the unit tests of imported files, and those unit tests
were not written in -betterC in mind.
PR https://github.com/dlang/tools/pull/386 allows us to not compile with
-unittest such files and this commit makes this change.
Also enable command output for the last 2 lines of the %.betterc rule is
it's quite helpful in order to see what's going on.
Blocked on:
> [posix.mak]: Build @betterC extracted tests without -unittest

- std/stdio.d
On linux there is nothing left now, but I have no means to check that for other OS.
> Fix partially Issue 11809 - unit tests leave behind temporary files

- std/range/package.d
Those verifications broke SortedRange with -betterC even when they were off.
> Made SortedRange verifications conditionally compiled.

- std/algorithm/searching.d
Two versions of find matched, when called with two strings. Now only the one found in line 1878 matches.
> Fix Issue 11013 - ignoring variable inside the predicate of find

- std/parallelism.d
From the docs of the function taskPool it's clear, that the current behaviour is intentional. Therefore I've choosen to improve the docs. :-)
> Fix Issue 10126 - Make TaskPool terminate on its own or improve docs

- std/typecons.d
The removal was already scheduled for 2.086
> Remove deprecated toString overloads from Nullable

- .dscanner.ini
- std/zip.d
The format of the table in the main documentation is not yet perfect, but I could not find anything better. Especially I found no local link version, where the displayed value is different to the anchor value. I used REF1_ALTTEXT for this.
I left out the flags and internalAttributes of ArchiveMember, because I don't know exactly their meaning. As I have to investigate on this anyway, I'll fill this in, when I know better.
I would be happy if a native english speaker could correct any language mistakes I made.
> Rework documentation of std.zip.

- std/file.d
This is due to issue [11631](https://issues.dlang.org/show_bug.cgi?id=11631). I checked, that the issue still is valid.
> Clarify the behaviour of rename on posix systems.

- std/range/package.d
Let's see if there's any actual reason that the arguments to `only` are `auto ref`.
> Fix issue 20314: pass `only` parameters by value

- std/math.d
DMD allows some illegal expressions in the CaseStatments , which might be fixed by https://github.com/dlang/dmd/pull/10603. This PR fix the cases detected in Phobos.
> prevent cases of illegal implicit convertions in CaseStatement

- std/zip.d
Without multidisk support, numEntries and totalEntries are the same numbers and furthermore they should always be the same as the length of the directory. This is enforced, when reading a directory, but when adding a member to the directory or deleting one this is currently not the case. See [issue 20398](https://issues.dlang.org/show_bug.cgi?id=20398).
This creates a change-feature-and-deprecate case. But I see no merit in first fixing the bug with a PR and then deprecating the feature in the next PR.
I also replaced the private variable endrecOffset by a local variable inside findEndOfCentralDirRecord(). Beside being a return value, this was only used in lines 844 to 851. The checks and the copy there are allready done in the constructor and therefore there is no need to do it once …
> std.zip: Remove some unnecessary private variables

- std/signals.d
This addresses [issue 9603](https://issues.dlang.org/show_bug.cgi?id=9603). I think, inside of Phobos this cannot be repaired (maybe with a complete rewrite), nor is it possible to add an exception to prevent the crash.
I remember, that I've seen an even more impressive warning somewhere, but could not find it again. I think it would be the right thing to add here.
> Add closures to warning and mark warning in red.

- std/typecons.d
They fail with types that have an opCmp defined and are value
types.
> Fix issue 20425: Remove Proxy.opCmp constraints

- std/json.d
Undeprecate JSONType members, which create lots of spam-like
deprecation warnings, which can't be fixed by the user.
See discussion on this issue at
https://forum.dlang.org/post/feudrhtxkaxxscwhhhff@forum.dlang.org
> Undeprecate JSONType member to avoid deprecation warnings

- std/range/package.d
For some reason `std.range.dropBack` **Example** field contains examples from `std.range.drop` in the [docs](https://dlang.org/library/std/range/drop_back.html). I think removing them from here should bring back the actual ones.
> Bring back "std.range.dropBack" code examples

- std/internal/digest/sha_SSSE3.d
wrap already adds a semicolon, so this makes an extra empty statement
> remove unnecessary extra semicolon

- std/traits.d
- std/variant.d
Based on PR #4342. I don't really completely understand the implications of this change, but all tests pass and as the original PR has been more or less approved by JackStouffer and I think, that PR was only closed, because the author of the PR left, I resubmit it.
> Fix Issue 15940 - ImplicitConversionTargets and class alias in struct

- std/net/curl.d
The other examples in std.net.curl should IMHO also be checked...
Is it possible to move them to unittests instead? Or does the internet access needed lead to a problem? And if yes, what is best practice here?
> Fix Issue 18446 - Wrong curl onProgress examples

- changelog/json_number_conversion.dd
- std/json.d
The JSON standard only defines the "number" type. Therefore it is expected that any whole number would be castable as floating and it doesn't. This little PR changes the behaviour of `floating()` so it will cast any numeric type to double and return it.
> Add automatic number conversion to std.json

- std/typecons.d
to get rid of annoying deprecation warnings because in case the rhs is an other Nullable instance the constraint `is(typeof(this.get == rhs))` triggers the deprecation warning because the rhs implicitly calls deprecated `get_` member. This guard constraint prevents the rhs from being an other Nullable instance. No resolution logic change. Just getting rid of useless warning.
> Remove useless warnings

- std/format.d
The style checker gives the following error, that I don't understand, because the normal unittests can compile this. Can anyone help me here?
```
generated/linux/release/64/publictests/std_format.d(1242): Error: template std.format.FormatSpec cannot deduce function from argument types !()(string), candidates are:
std/format.d(1011):        FormatSpec(Char)
with Char = char
must satisfy the following constraint:
!is(Unqual!Char == Char)
std/format.d(1021):        FormatSpec(Char)
```
> Fix Issue 15405 - FormatSpec.writeUpToNextSpec() not documented

- changelog/bigint-safe.dd
- std/bigint.d
- std/internal/math/biguintcore.d
- std/internal/math/biguintx86.d
A start of making std.bigint `@safe`.
It's WIP because it will certainly fail on targets with `version (D_InlineAsm_X86)` active since I haven't touched that.
If anyone knows how to test that on a 64-bit machine, please tell.
> Make std.bigint `@safe`

- std/numeric.d
See https://github.com/dlang/phobos/pull/7219#discussion_r360726810 for the motivation.
One of the unittests for CustomFloat assumed, that the exponent of a real has at least 15 bit, which isn't true. It can only be assumed, that it has at least 11 bits (real==double). This unittest (although broken) worked until PR #7219 because the size of the exponent was never checked until then and the asserts in the unittests had to work with smaller exponents too (see AliasSeq), so the broken part was never checked.
I first tried to fix this, keeping the 15 bit exponent, whenever real supports it, but that proved to be more difficult than I first thought, because the sum of exponent bits and mantiassa bits has to be 8, 16, 32 or 64 and guaranteeing this for all possible exponent sizes would need …
> Fix unittest, which assumed real exponents having at least 15 bit.

- std/numeric.d
See https://github.com/dlang/phobos/pull/7219#discussion_r360729014 for the motivation.
When `real==double`, the function calculates for `x==-double.max` the value `-inf + inf + ...` which produces a `nan` and therefore the overall result is a `nan` which breaks the test in `testFindRoot`.
> Fix unittest, which assumes real > double.

- std/math.d
The original tests compare apples and oranges, that is, left side double/float, right side real. The values on the left side are correct in the precision available but real has better precision and therefore the tests failed. Casting to the lower precision fixes this.
As a side note: I dislike these tests, because the right side could still produce wrong results, depending on the implementation of * and / and rounding errors. I'd prefere to compare to manually calculated literals.
> Fix Issue 5628 - std.math unittest disabled - roundoff error in pow()

- std/path.d
The current documentation is not complete. The user may be surprised when this function returns ".", as it may lead to problems if you are using the output of a call to dirName elsewhere.
> Provide a complete description of dirName output

- std/bigint.d
Limitation: ~~casting to & comparison with quadruple precision floating point numbers are not supported.~~ The path for 80 bit (EDIT: and greater) extended floats use std.math.scalbn which currently is impure ~~and non-CTFE-able~~.
> std.bigint.BigInt: allow casting to floating point numbers

- std/numeric.d
No examples provided which specify use of "sum" parameter.  The current examples imply that template parameters are not required, but this is not true when "sum" value is specified, which may confuse users wondering why normalize(a,50) does not compile.
The added example makes it clearer.
> Add further example for std.normalize

- std/math.d
This is a replacement for PR #7187, because I had to remove my old account on GitHub.
My original comment was:
As suggested in PR #7173, I wrote a new version of approxEqual (called isClose to avoid naming conflicts), which is based on the thoughts given in [1]. The purpose of both functions is the same, namely providing a utility for comparing floating point numbers. This is necessary, because operations on floating point numbers inevitably produce rounding errors and therefore cannot be compared reasonable using ==.
The main difference is, that this function has much stronger default values for the error allowed, based on the capabilities of the used floating point type. This helps in catching errors, especially as approxEqual is mainly used in unittests. This addresses issue #15881. …
> Add isClose, a replacement for approxEqual

- std/typecons.d
In the bugreport another potetial fix is reported:
```
private enum getField(T) = is(T == typeof(this)) ? ("." ~ __traits(identifier, a)) : "";
auto ref opOpAssign(string op, this X, V)(auto ref V v)
{
return mixin("a " ~ op ~ "= v" ~ getField!V);
}
```
I don't know for sure, what the impact of either is exactly and therefore I'm lost in deciding, which one is better...
> Fix Issue 12461 - Typedef and opOpAssign

- posix.mak
OSX 32 bits on the auto-tester isn't supposed to be busy.
It isn't causing any trouble being run here in phobos but in dmd `make install` sometimes hangs and it has to be disabled in phobos first before it can be disabled in dmd.
See: https://github.com/dlang/dmd/pull/10705.
> Disable `make install` for the Darwin_64_32 target on the auto-tester

- changelog/std-functional-curry.dd
- std/functional.d
I wasn't sure the best way to add template constraints to make sure that things without state (e.g. functions) use the alias template version and things with state (callable objects) use the type template version.  LMK how best to go about that.
This addresses bugzilla issue 4391
> bugzilla issue 4391 add curry to std.functional 

- std/concurrency.d
The original issue (docs telling, that the runtime catches the exception) seems not to exist anymore, but anyway, the functions should document, that they might throw. i also cleaned up the docs of the three functions a little bit.
> Fix Issue 7446 - [TDPL] Trivial asynchronous file copy example crashes

- std/algorithm/iteration.d
If sum() is called, it tries to find a default value by constructing it with 0 (e.g. float(0)). This works for numbers, but produces obscure errors if the value cannot be constructed this way (e.g. issue #19525). The error message now states that the problem lies in the default value and suggests to supply one instead.
> Improved error message when calling sum without a default value

- std/math.d
I improved the docs too, including the public unittest.
> Fix Issue 7006 - std.math.pow (integral, integral) crashes on negative exponents

- std/bitmanip.d
Helps with proposed DIP1028 (https://github.com/dlang/dmd/pull/10709, https://github.com/dlang/DIPs/blob/1b705f8d4faa095d6d9e3a1b81d6cfa6d688554b/DIPs/DIP1028.md)
Not sure if there will be more. It's difficult to test this, but this seems to be the most common problem.
cc @WebFreak001
> Mark CTFE bitmanip function for generating longs to a string as @safe and pure

- std/string.d
I subscribe to the view of the author of the bug (and the people in the corresponding forum thread) that `debug` should not be used inside Phobos.
I also sligthly changed the example unittest as the current output `writeln(a) // c` is somewhat confusing.
> Make assumeUTF nothrow

- std/range/package.d
This was more tricky than I originally thought, mostly due to the existing requirement that `chooseAmong` works with strings during CTFE.
Essentially, we only trust the fetching of the pointer to the chosen range, everything else should be inferred.
I'm not sure why I had to remove `return scope`, but that doesn't seem to work, I let the attributes get inferred. The error messages are totally unrelated to this code, it's just not correctly inferring safety with those attributes. But I don't really understand what the `return scope` did in the first place.
Should obsolete #6933 
@thewilsonator @dnadlinger
> Fix issue 19738 -- std.range.choose assignment breaks @safe-ty

- std/internal/math/biguintcore.d
The problem comes down to a buffer overflow.
How could a buffer overflow happen in `@safe` code?
Well, it's basically a logical buffer overflow, while technically no out of bounds memory is accessed.
Two buffers are created in one allocation of size a + b (presumably as an optimization).
`buffer[a..$]` is given to `partial`, while `scratchbuf` remains the whole `buffer[0..$]` instead of `buffer[0..a]`.
That means that if more than `a` elements are written to `scratchbuf`, it messes up `partial`, which is what happens in the bug report.
The buffer size for Karatsuba multiplication of `x * y` is calculated as `2 * x.length` (x and y are a `BigDigit[]` which is a `uint[]`).
Most calls to `mulKaratsuba` claim `2 * half(x.length)` of `scratchbuf` and pass the rest to a recursive call of half …
> Fix issue 20493 - incorrect result of BigInt * BigInt

- std/format.d
The global import of `std.math : FloatingPointControl` caused a performance regression. This PR fixes this by making the import local.
See [discussion](https://github.com/dlang/phobos/pull/7285#pullrequestreview-338238228) for more details.
PS: I checked, using valgrind, that this import indeed caused the regression.
> Fix performance regression introduced by PR #7285.

- std/process.d
- std/typecons.d
- std/uni.d
Please see https://github.com/dlang/druntime/pull/2888
> Some version (unittest) blocks removed

- std/json.d
Works around DMD being unable to infer the recursive toJson call as @safe.
> Fix issue 20511: make toJSON determine safeness based on output range safeness.

- posix.mak
The following druntime commit:
https://github.com/dlang/druntime/commit/ddf4bcc6e315a364e2e9aa57566459c9f793a1e4
removed the need for that, by preventing phobos from instantiating
template nested unittest blocks (from core.time).
> Don't define version CoreUnittest as it's not necessary any more

- std/experimental/typecons.d
In debug mode, the standard unittests produces a series of (useless) warnings. With the new feature of -version=StdUnittest, this warnings can be removed without removing them in other uses too.
```
Could not locate matching function for: FuncInfo!("foo", void())
Could not locate matching function for: FuncInfo!("bar", void())
Could not locate matching function for: FuncInfo!("foo", void())
Could not locate matching function for: FuncInfo!("refresh", int())
Could not locate matching function for: FuncInfo!("refresh", int())
Could not locate matching function for: FuncInfo!("refresh", int())
```
> Remove 'could not locate' warning from std unittests

- changelog/schwartzSort.dd
- std/algorithm/sorting.d
Receiving the element's index in the original range as 2nd parameter. I have a use case for this.
> std.algorithm.sorting: Enable binary transform function for schwartzSort

- std/typecons.d
Includes #7375 because it extends the test case with the appropriate attributes
> Fix Issue 20540 - (White|Black)Hole does not work with return|scope functions

- changelog/mangle_removed.dd
- std/format.d
It's deprecated since January 2018
> Remove deprecated std.format.Mangle

- changelog/isClose.dd
As suggested by @quickfur in #7241 I add a release note for the transition from `approxEqual` to `isClose`.
I would have prefered to have #7340 merged before, but as little happens there and the next release approaches I do not want to postpone it any longer.
> Add release note for the transition from approxEqual to isClose.

- std/traits.d
It's essentially a copy of #5710 from @RazvanN7 but with the problematic `static this` commented out. I tried to hunt down the problem of this `static this` with dustmite (took two weeks to run) and finally ended up with issue 20529, but as I forgot to include the dependency cycle in the test for dustmite I ended up with a different cycle. Not sure if a fix of 20529 will fix this too or if there is more to discover. 
Anyway, IMHO this `static this` is only a minor point and should not hinder fixing the original bug.
> Fix Issue 8388 - std.traits.MemberFunctionsTuple doesn't work with constructors or destructors

- std/range/package.d
The docs didn't describe this function perfectly, and it's behaviour surprised me quite a bit.
> Completed description of PipeOnPop at std.range.tee.

- .dscanner.ini
- std/format.d
> Fix std.format FP printing for soft-float targets

- std/format.d
This is a followup on #7264 (not yet merged) and #7285 (merged). This time it implements %e and %E specifiers. Part of this is identical to #7264 to make this PR independed.
I run essentially the same tests as in #7264.
Concerning correctness: All tests passed. No exceptions this time.
Concerning speed: For floats the new version is faster, but for doubles numbers with large or small exponent are somewhat problematic. snprintf manages here to get much better results. I've got some ideas on how it might be possible to improve this, but I'd like to postpone this for an extra PR. See [pdf-file](https://github.com/berni44/printFloat/blob/master/printE.pdf) for some diagrams.
> Partial replace call to snprintf for '%e' and float or double.

- std/internal/math/biguintcore.d
LDC refuses to compile this, due to the `@safe` parent calling a `@system` lambda. `core.cpuid.dataCaches` is an [appropriate](https://github.com/dlang/druntime/blob/f80a07e1a0140f01878a4b13e2eea61faf6a3063/src/core/cpuid.d#L121) function anyway.
> [Trivial] Remove obsolete hack in std.internal.math.biguintcore

- std/zip.d
So it passes the printf format checker.
Blocking https://github.com/dlang/dmd/pull/10812
> zip.d: fix printf formats

- std/container/array.d
- std/conv.d
See bugzilla [here](https://issues.dlang.org/show_bug.cgi?id=20589)
> Fix issue 20589 - typeof may give wrong result in case of classes defining `opCall` operator

- std/datetime/systime.d
- std/datetime/timezone.d
- std/exception.d
- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/ascending_page_allocator.d
- std/experimental/allocator/building_blocks/region.d
- std/experimental/logger/core.d
- std/file.d
- std/net/curl.d
- std/parallelism.d
- std/path.d
- std/process.d
- std/socket.d
- std/stdio.d
- std/zip.d
I've only tested this on a 64 bit iPhone running iOS 12. 32 bit is obsolete and I don't have access to the other platforms.
* `std.net.curl` is disabled, libcurl is not shipped on these platforms. This should possible to fix by static linking libcurl and shipping libcurl together with the D compilers. But for that, some extra work are required due to `dlopen` not being allowed.
* Most of the functionality in `std.process` is disabled. Creating new processes are not allowed.
* Some of the unit tests in `std.experimental.allocator` fail. Perhaps the https://github.com/dlang/phobos/commit/537cef3c792f797f68bf75db12709d9ca87387d2 commit should be removed since it doesn't fix the unit test anyway
* Some math related unit tests fail
* One test in `std.socket` fail, but that is allowed to fail …
> Add initial support for iOS, tvOS and watchOS

- std/format.d
> don't allocate dynamic array when formatting a single character

- std/json.d
When issue 20655 ("attribute inference accepts unsafe union access as
@safe") is fixed, DMD correctly complains about the operation being unsafe.
Needed for <https://github.com/dlang/dmd/pull/10884>.
> mark access to `value.store.str` as @trusted

- std/conv.d
This fixes the regression for the upcoming release but it the should probably reconsidered how `inout` behaves in heavy templated code
> Add tests for issue 20623 - std.conv.to!string error when argument is an inout float

- std/experimental/allocator/building_blocks/affix_allocator.d
- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/building_blocks/fallback_allocator.d
- std/experimental/allocator/building_blocks/free_tree.d
- std/experimental/allocator/building_blocks/kernighan_ritchie.d
- std/experimental/allocator/building_blocks/quantizer.d
- std/experimental/allocator/building_blocks/region.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/gc_allocator.d
- std/experimental/allocator/mallocator.d
https://github.com/dlang/phobos/pull/7353 moved the declaration of `testAllocator` inside of a version block, but not all of the unit tests that use this template were put in similar version blocks. This causes CI tests for dsymbol to fail when built with 2.091.0.
> Make sure that uses of testAllocator are inside of StdUnittest version blocks.

- changelog/date-isoweek.dd
- std/datetime/date.d
moved functionality from isoWeek into a helper function called isoWeekAndYear which computes both week and year at once, which is then used in isoWeek and isoWeekYear.
Added a date construction method to create a date from the ISO week calendar (year + week + weekday)
> add Date.isoWeekYear and Date.fromISOWeek

- std/algorithm/iteration.d
Taken from patch for gdc bugzilla PR other/93756
> [dmd-cxx] std.algorithm.iteration: Fix typo.

- std/stdio.d
The documentation for `File.name()` stated it "Returns the name of the last opened file..." This implies `name()` is a static function which returns the name of whatever file happened to be initialized and opened most recently, rather than the name of the FILE* which the struct refers to.
I propose correcting the documentation to reflect `name()`'s actual purpose.
> Improve std.stdio.File documentation

- std/algorithm/comparison.d
Rationale: D currently has a perception problem when it comes to how much of the standard library can be used with `@nogc`. It's hard to counter that sentiment without data proving how much of is usable. To that end, I'd like to see a "Are we @nogc yet" webpage (inspired by [the Python wall of superpowers](https://python3wos.appspot.com/) that used to be [the wall of shame](https://news.ycombinator.com/item?id=4907755)) showing exactly what parts of Phobos are usable without the GC. I don't know how the visualisation will work yet, but the first step would be to annotate as many unittest blocks as possible with `@nogc`.
> Add @nogc to all relevant unittests in comparison.d

- std/socket.d
Reduce the length of the Unix socket file path.
> Fix socket test for iOS derived platforms

- posix.mak
This was done in DMD two years ago but never applied here.
https://github.com/dlang/dmd/pull/7578
Originally found while working on Druntime, the PR there will follow soon.
> Bump minimum MACOSX version to 10.9

- changelog/digest.dd
- std/digest/crc.d
- std/digest/digest.d
- unittest.d
> Remove deprecated symbols from std.digest.digest

- std/algorithm/sorting.d
If `-debug` is passed to the compiler, `version(assert)` is true.
TimSort has a `version(assert)` that checks some invariants, and uses
std.format.format for better error messages. Unfortunately, since it
is templated code, this results in Phobos template instantiations of
`format` in the user's code when `-debug` is used.
Given that default dub builds use `-debug`, this is a very common
problem.
Instead of removing the invariant checks, this changes it so they only
happen when testing Phobos itself.
This is blocking removing the special cases in dmd for template codegen when -debug or -unittest are used.
> Remove version(assert) from TimSort

- std/algorithm/setops.d
```
The DMD PR has long been pulled but the comment hasn't been fixed.
```
Not sure this works, let's see what the auto-tester says.
> Enable `@safe` on `cartesianProduct`'s `Result.popFront`

- std/traits.d
> Fix 20733. Remove docs about copy construction from hasElaborateAssign.

- std/range/primitives.d
`version (X86_64)` is not a sure way to test whether length sizes are 64-bits.
> std.range.primitives: Fix static condition for X32 targets

- std/range/primitives.d
> [dmd-cxx] std.range.primitives: Fix static condition for X32 targets

- std/typecons.d
Works around (I suspect) https://issues.dlang.org/show_bug.cgi?id=20670 , which may
cause `Nullable` with arrays of `immutable struct`s to incorrectly strip
away the `immutable`, creating impossible types that can't be reused.
@RazvanN7 Since you added `get(default)`, is there any reason why it would have to infer a different type than the `Nullable`'s?
> Add get(default) same-type overload in Nullable

- std/random.d
This enhancement is now possible (without being DMD-only) because LDC version 1.20.0 added support for data directives in DMD-style inline asm.
> std.random.unpredictableSeed: on x86/x86-64 try using RDRAND when there is no arc4random

- std/range/package.d
I saw the docs, and thought it was going to return a pointer to the element. It returns a bool (basically returns `contains(value)`)
There's no need to hide this in the docs/API.
> specify return type for SortedRange.opBinaryRight!"in"

- std/experimental/checkedint.d
The necessity for this is due to an x86 design idiosyncrasy. If an integer division causes an overflow, a division error occurs, causing SIGFPE to be raised on POSIX systems and the SEH exception EXCEPTION_INT_OVERFLOW to be thrown on Windows. Since the `Warn` hook performs the offending calculation nevertheless, a special case is added such that an overflowing division is not performed.
> Fix Issue 20743 - Checked!(int, Abort) does not abort but raise SIGFPE

- std/algorithm/sorting.d
- std/range/package.d
isTwoWayCompatible should accept functions with ref parameters.
> Fix Issue 20751 - SortedRange with ref predicate parameters fails

- std/exception.d
Accept a false positive/negative for may/doesPointTo
> Fix Issue 20426 - doesPointTo with void[N] fails

- std/conv.d
The commit allows the following code to compile:
```d
enum Enum { oops }
"foo".to!(const Enum);
```
> Fix issue 20782 - allow std.conv.to to convert string to const enum

- std/string.d
Previously, the subsequence comparison was broken and returned a value > -1 if the first character matched (even if the rest of the sequence did not match).
> Fix Issue 20783 - std.string.lastIndexOf doesn't work correctly in CTFE

- changelog/digest.dd
- Documentation fix: std.digest is not going to be removed, std.digest.digest is
> merge stable

- std/complex.d
- std/package.d
Pushing out initial implementation. Unittest incoming...
> std.complex: Add complex exp(), log(), log10(), and pow()

- std/complex.d
- std/math.d
First deprecation was in Jan 2018.
Unittests have been copied across to std.complex where appropirate.
> std.math: Remove deprecated creal functions

- std/complex.d
- std/math.d
And updated newly introduced std.complex tests to use isClose instead.  More precise numbers have been pulled off from wolfram ([example](https://www.wolframalpha.com/input/?i=log+%28+1*cos%28PI%2F3%29+%2B+i*1*sin%28PI%2F3%29+%29)).
> std.math: Implement isClose for std.complex types

- std/math.d
It was removed in PR7473: https://github.com/dlang/phobos/pull/7473#issuecomment-628176305
It caused a two-days-long outage of Buildkite: https://github.com/dlang/ci/pull/418#issuecomment-629223669
> Restore accidentally removed import from std.math

- std/experimental/allocator/building_blocks/bitmapped_block.d
- std/experimental/allocator/common.d
`trailingZeroes` and `leadingOnes` have unit tests and they are still passing.
> std.experimental.allocator: use core.bitop for trailingZeroes and leadingOnes

- std/complex.d
A couple more trivial additions to std.complex, all that remain (future PRs) are a(sin|cos|tan), (sin|cos|tan)h, and possibly isClose.
N.B: should norm be named toNorm?
> std.complex: Add complex norm() and proj()

- std/file.d
This was brought to my attention by [a unit test in CyberShadow/ae](https://github.com/CyberShadow/ae/blob/master/sys/persistence/core.d) that was failing on macOS because it was storing a result of `timeLastModified` then using the stored value as an argument to `setTimes` and expecting that the next call to `timeLastModified` would yield the same result as the stored value. The problem is that core.sys.posix.sys.stat does not have `utimensat` for macOS, which is because it only became available in macOS starting from version 10.13 which was released in 2017. As an alternative `setattrlist` can be used with any version of macOS to set timestamps with the same precision as `utimensat`.
> std.file.setTimes: on macOS use setattrlist to avoid truncating timestamp precision to microseconds

- std/typecons.d
It was previously difficult to see where the implementation of
Nullable ends, because the indentation did not represent the nesting
level.
This also fixes the different DDoc styles used to document Nullable
entries to a single style.
> std.typecons: Fix inconsistent indentation in Nullable implementation

- std/meta.d
by simply unrolling the template instantiations
> speed up instantiation of Filter and staticMap templates

- std/stdio.d
Links to `core.stdc.stdio.stdin`, `stdout`, and `stderr` were broken because the `stdc` part was missing.
> [Trivial] Ddoc: Fix refs to core.stdc.stdio.stdin/stdout/stderr in stdio.d

- std/typecons.d
`areCompatibleTuples` has to check `OriginalType` to account for enums. Also, swap is confused, so we're not using that for these assignments. Casting to `OriginalType` would work, but breaks `@safe`.
> Fix issue 20850 - Can't assign enum of Tuple

- std/socket.d
See https://github.com/dlang/phobos/pull/7433 for details.
> std.socket: Improve 16514 unittest to guard against inherited attributes

- std/math.d
To be precise, for -m32mscoff / -m64.
> Fix Issue 9298 - some std.math functions not implemented for Win64

- std/meta.d
This is a direct realization of AliasSeq that better clarifies its intent.
> Replace template AliasSeq with a simple alias

- std/algorithm/iteration.d
This teaches `sum` to look for `Seed.zero` if no constructor taking an int is found for the type.
> Fix issue 19525 - Duration is not usable with zero-arg std.algorithm.sum

- std/stdio.d
Makes non-`unittest` examples work.
> fix issue 20882 - Outdated examples in the documentation (std.stdio)

- .dscanner.ini
- std/algorithm/mutation.d
Remove the manual check whether move is `@safe` and instead let the compiler do the attribute interference by adding appropriate `@trusted` blocks.
Note: I could've extend the current checks `trustedMoveImpl` but that could easily miss other corner cases.
TLDR: Only use `@trusted` when necessary
> Fix Issue 20869 - `move` is overly trusting of `opPostMove`

- std/digest/package.d
Speed up `std.digest.digest!(Hash, Range)` on non-array ranges by chunking the data. I would have liked to use something like `std.stdio.File.byChunk(ubyte[])` but I didn't find anything equivalent. `std.algorithm.iteration.chunkBy` doesn't work for this purpose.
In the below tables "old/new len 16 time" refers to the time to hash 2^^24 times a range of length 16. "Old/new len. 2^^20 time" refers to the time to hash 256 times a range of length 2^^20. While benchmarking I was surprised to discover that with the implementation prior to this PR `dmd -O -inline` was noticeably faster than `ldc2 -O3` for CRC32 and every MurmurHash3 variant.
**ldc2 -O3**
| Hash               | Old len. 16 time  | New len. 16 time  | Old len. 2^^20 time | New len. 2^^20 time | …
> Improve speed of std.digest.digest!(Hash, Range) on non-array ranges

- std/stdio.d
Especially for non-windows && non-posix
> alias FSChar = char for a wider range of platforms

- std/json.d
Currently targeting `master` because `stable` seems to be broken.
> Fix Issue 20874 - std.json.assign requires '@safe' and 'pure'

- std/stdio.d
Checking for a slice or static array whose first element converts to `const(char)` is enough; it rules out aggregates, enums, `null`.
Also remove local imports for isAggregateType, isStaticArray (use __traits(isStaticArray, ) instead).
> [std.stdio.writeln] Simplify static checks for string specialization

- std/math.d
Do documentation fixes need Bugzilla issue numbers? In this case `isIdentical`'s documented unit test already included `assert(!isIdentical(real.nan, -real.nan))` showing the actual behavior.
> Fix documentation of std.math.isIdentical for NaN: compares all bits not just payload

- std/math.d
Following up on #7516. There exist equivalent binary representations which aren't identical, not just 0 and NaNs.
> std.math: Fix comment for isIdentical

- std/range/package.d
> [dmd-cxx] Don't shorten the width of the iteration variable

- std/path.d
That's the case for CirrusCI/FreeBSD - the user is root, the `USER` env var unset and `HOME` set to `/`, and the tilde expansion for `~` in that case led to an empty string and according failures in https://github.com/dlang/phobos/blob/95e4fb49de41359b6c1f48003601243be691ff5e/std/path.d#L4158-L4163
> std.path: Fix tilde expansion for HOME=/

- std/algorithm/setops.d
I don't believe https://github.com/dlang/phobos/pull/7440/ was the correct thing to do. @Geod24
> Let safety of cartesianProduct.Result.popFront be inferred

- std/experimental/allocator/package.d
https://issues.dlang.org/show_bug.cgi?id=20929
The instantiation failure was caused by trying to get the address of an lvalue
for `emplace`, which was caused by `front`'s auto-decoding of the slice used to
refer to the uninitialised elements of the array.
The fix was to forgo the range functions for the slice, and just index it.
The changes to `ForcedInputRange` may seem unrelated to the fix, but I wanted
to test the input-range code-path, and the only usage of `ForcedInputRange`
was to test this overload of `expandArray`, so it seemed more appropriate to
reuse it, rather than define another input-range.
> Fix issue 20929 - std.experimental.allocator.expandArray's range-based overload fails to instantiate for char and wchar arrays.

- std/bigint.d
- std/internal/math/biguintcore.d
For consistency with other std.bigint functions allows arbitrary ranges.
> Support construction of std.bigint.BigInt from a sign and a byte-array magnitude

- std/experimental/checkedint.d
- std/typecons.d
Seems like those test weren't checked before the recent improvements to `test_extractor.d`. Not sure why the CI didn't fail for those PR's though ...
> Fix public examples failing due to missing imports

- std/meta.d
* Improve `AliasSeq` Map example: inline simple functions, move `testRef` next to where it's used. Fix capitalization of `Func`.
* Don't write *type* when alias is meant.
* Avoid instantiating AliasSeq with a sequence.
* Update private `Pack` template to use sequence terminology.
> [std.meta] Improve AliasSeq Map example & other tweaks

- std/range/package.d
The `ref` has no effect anyway.
Blocks dlang/dmd#10018
> Remove invalid alias from chain's implementation

- std/math.d
~No, there isn't a better way of doing this.  Complements to @schveiguy for an initial version of this PR.~
Rebased and updated following dmd fix.
> std.math: Begin deprecation of accidentally leaked AliasSeq

- std/meta.d
~~Depends on https://github.com/dlang/dmd/pull/11320 being merged first~~
This is needed for dlang/dmd#11320.
> std.meta: Fix wrong assert for Issue #20863

- std/container/dlist.d
stableRemove was listed under the linearRemove documentation for some reason, even though it's aliased to remove.
> Move stableRemove alias to correct place for documentation

- std/meta.d
There are a few separate optimisations here:
1. make `staticMapImpl` , meaning that the template you're instantiating a lot of doesn't have to take the `F` every time. Improvement: only ~1-2% but very stable, I suspect this approach might be more rewarding elsewhere.
2. expand out many small cases (150). Any more than 3 was slower if done inline with `static if` chains, but combined with the following you can really crank it
3. generate the small cases as an `AliasSeq` of strings, so no static if chains, just an O(1) lookup (at least I hope so). This is the big one, enabling the expansion to work cheaply.
4. in the binary split branch immediately do what work you can. Combined with the rest this is an extra ~20% speedup and 10% memory reduction
Overall, this was ~2.5x faster and ~4x less …
> Faster staticMap and Filter

- std/conv.d
- std/traits.d
By looking at the build errors in the calls to `std.conv.to` I reckon I didn't manage to exactly mimic the current definition of `std.traits.isCopyable` in dmd's definition of `__traits(isCopyable)`. Any clues on how to detect these discrepancies?
Add `static assert` inside the current definition `std.traits.isCopyable` that checks that `__traits(isCopyable)` equals `std.traits.isCopyable` is a way forward. I'll try that.
> Reuse new builtin trait isCopyable in std.traits.isCopyable

- std/math.d
This is a partial fix for https://issues.dlang.org/show_bug.cgi?id=19663
A complete fix would be to make it a compiler intrinsic.
> fix fabs() to not use x87 for float/double

- std/digest/sha.d
This causes critical functions identified in https://github.com/dlang/phobos/pull/7534 to be always inlined.
> sha: inline critical functions

- std/utf.d
Reverts dlang/phobos#7566
It was force merged and broke the build.
Usage here: https://github.com/dlang/phobos/blob/2f18e0d0c1e709ec2405d690807dedf6f42a98c1/std/conv.d#L5793
> Revert "EASY: Companion to https://github.com/dlang/druntime/pull/3167/"

- std/conv.d
- std/random.d
- std/utf.d
Companion to https://github.com/dlang/druntime/pull/3169. After this, the old functions in there can be removed.
> unsignedToTempString: use the template version

- std/uni/package.d
Wrap static assert assert in unittests. std.uni seems to be only one that has any of these.
More to come.
Discovered by compiling `import std;` with https://github.com/dlang/dmd/pull/11463.
> Reduce default template instantiations

- std/getopt.d
The line break is encoded as part of the hyperlink:
`http://%20%20%20%20%20%20%20%20%20%20%20perldoc.perl.org/Getopt/Long.html`
> std.getopt: Fix link to perl docs

- std/traits.d
In support of the DMD PR dlang/dmd#11474 , which will be red until this is pulled.
Commit message follows:
```
For a long time, the 'in' storage class was only a second class citizen,
merely an alias for 'const', which is a type constructor.
While it was also documented for a long time as being 'scope',
this was removed when 'scope' actually started to have an effect
(when DIP1000 started to be implemented).
Currently, a switch (-preview=in) allows to get back this 'scope'.
However, the 'in' storage class does not really exists,
it gets lowered to 'const [scope]' at an early stage by the compiler,
which means that we expose what is essentially an implementation
detail to the user.
There is a PR in DMD (dlang/dmd#11474) that aims to give 'in' an actual
identity, instead of it being lowered …
```
> std.traits: Add support for 'in' storage class

- std/array.d
- std/bitmanip.d
- std/format.d
- std/random.d
- std/stdio.d
- std/variant.d
Aplying `immutable` to `T` makes it `immutable T` regardless of whatever qualifiers `T` has. This allows for a simple idiom for type comparison, per this PR.
> Replace Unqual-based idiom with immutable-based idiom

- std/digest/sha.d
...because it increases build speed by 10x.
See also https://forum.dlang.org/thread/lcgitgilixahbnzwpwfp@forum.dlang.org
> Work around issue 21111: Temporarily disable inlining of T_SHA2_16_79

- std/file.d
Fixes [issue 21113](https://issues.dlang.org/show_bug.cgi?id=21113).
I'm quite new to D, and wasn't sure if there's a way to do a condition inside a version, like the following:
```d
version (FreeBSD || NetBSD || DragonFlyBSD) {}
```
Which would make some of this code slightly cleaner in my opinion.
Sysctl numbers are taken from relevant headers:
- [FreeBSD](https://github.com/freebsd/freebsd/blob/8b261beea6bd825db7c891eeea6aaf8621b30268/sys/sys/sysctl.h#L999)
- [NetBSD](https://github.com/NetBSD/src/blob/4455df1e707aa79dd1e5aa5cab05aca949996023/sys/sys/sysctl.h#L587)
- [DragonFlyBSD](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/4c898ae594e26f4901a584d0cfe471cb018bea11/sys/sys/sysctl.h#L610)
> Fix issue 21113: Use sysctl for thisExePath on BSD.

- std/array.d
- std/utf.d
~~This fails on my local machine, but I wanted to see if the auto tester has the same issue. I can't reproduce it outside of this environment, and it makes no sense why it's failing.~~
Turns out my local failure is in master as well, if you do `make -f posix.mak std/array.test`, so this should still pass.
> Fix 21131 -- proper handling of non-dchar appending to Appender!wstring and Appender!dstring

- posix.mak
They are way more likely to fail than the documented unittests (which don't change much), and putting them last makes the push/test/debug cycle much longer for stuff like a missing space on an if statement.
> Make the style checks run first

- posix.mak
This is so CI can run a valid target without failing. It currently does nothing as no autodecode unittests run.
step 2 is to alter a CI (probably buildkite) to run the autodecode tests.
step 3 is to start fixing issues with removing autodecode, and adding no autodecode modules to the list of tests to run.
step 4 (eventually) is to run all of Phobos with autodecode switched off in addition to normal tests.
step 5 is to deprecate autodecoding.
> Add makefile target for testing with no autodecode.

- std/file.d
from man time:
```
The software clock, HZ, and jiffies
The accuracy of various system calls that set timeouts, (e.g.,
select(2), sigtimedwait(2)) and measure CPU time (e.g., getrusage(2))
is limited by the resolution of the software clock, a clock
maintained by the kernel which measures time in jiffies.  The size of
a jiffy is determined by the value of the kernel constant HZ.
The value of HZ varies across kernel versions and hardware platforms.
On i386 the situation is as follows: on kernels up to and including
2.4.x, HZ was 100, giving a jiffy value of 0.01 seconds; starting
with 2.6.0, HZ was raised to 1000, giving a jiffy of 0.001 seconds.
Since kernel 2.6.13, the HZ value is a kernel configuration parameter
and can be **100**, 250 (the default) or 1000, yielding a jiffies value
of, …
```
> fix issue 21148, possible failure of CI when testing nano precision of file time stamps

- std/conv.d
- std/internal/math/errorfunction.d
- std/internal/math/gammafunction.d
- std/math.d
This fixes failing unittests with dlang/dmd#11387 on Linux x64 by appending a `L` suffix to (some) literals, to keep full `real` parsing
precision (instead of double precision).
> Prepare for properly parsed float/double literals

- std/math.d
As the according intrinsics have recently been added to `core.math`.
Also move `pragma(inline, true)` out of the function as required for LDC (and non-templated functions, not getting their body analyzed).
Also avoid superfluously slow `ldexp` calls with constant exponents.
> std.math: Enable proper single- and double-precision ldexp overloads

- std/stdio.d
To fix this issue, the newly added `openModeFlags` (and the enum `OpenMode` from which it's derived) is used to store the current open mode of a file. Thus, `rawWrite` can check if the file was already opened in binary mode to obviate temporarily changing the mode and thus executing two flushes.
A new method, `parseOpenModeString` is used to parse an open mode string, and it stores the desired open mode in `openModeFlags`. It's called in every method that changes a file's open mode. (See the documentation of this function for more information.)
I'd like your input on this, @schveiguy, since you asked to be notified about this.
> Fix issue 7033: File.rawWrite is slow on Windows

- std/uuid.d
'in' and 'in ref' overloads will conflict in the future if dlang/dmd#11000 is accepted.
Even if not, 'in' currently means something different based on a switch,
however the intention of this code is obviously the full 'const scope'.
In the some places, 'scope' was omitted as it is meaningless on value types.
> UUID: Replace 'in ref' overloads with 'const scope ref'

- std/socket.d
This is the only occurence in Phobos where 'in' would get 'ref' applied.
Changing this ensures that users can use '-preview=in' in their code.
Ref: dlang/dmd#11000
> Change Socket constructor to accept its parameter by const scope

- posix.mak
- std/algorithm/comparison.d
- std/array.d
- std/range/primitives.d
- std/utf.d
First module to pass with no autodecoding!
Note that I changed a few unittests in std.array. These aren't strictly necessary to get this one to pass, but they are in the right direction (I was trying to do std.array first, but I found it had too many dependencies on std.utf, so I tackled that one first). std.array is next, but still isn't passing all unittests.
The goal is to make it so eventually, one can simply disable autodecoding and all unittests pass in all dlang repositories.
DO NOT MERGE THIS unless the buildkite job that tests autodecoding passes.
> Make it so std.utf can be tested with no autodecoding.

- std/range/package.d
For static arrays, `only` used to store a reference to its caller. This was bad. I changed it (in https://github.com/dlang/phobos/pull/7253 ) to take its arguments by value, but I didn't realize the static array case - so it started storing a reference to its constructor parameters, which was more obviously bad, as it crashed (`@system`) or failed to compile (`@safe`).
This PR changes `only` to store the tuple of arguments in the range and convert to the common type as late as possible.
ping @JohanEngelen
Note that I test with `const(char)` as there seems to be a bug with `CommonType` - it thinks `char[]` and `string` are best unified as `char[]`.
> Fix issue 21129: Make `OnlyResult` store a value tuple instead of a static array of CommonType.

- std/ascii.d
- std/format.d
- std/range/primitives.d
- std/traits.d
Some are redundant. Others can be replaced by cheaper traits checks.
> Reduce the number of isAggregateType!T checks

- std/internal/digest/sha_SSSE3.d
It may be hopeless to bring type safety to the internal assembler and retain backwards compatibility, but I'm going to try. The trouble with this one is using an array of uints to represent a 128 bit XMM value. The original set up is an array of 20 uints, and the fix is to make it an array of 5 4-uint values. One 4-uint value for 128 bits.
This is blocking https://github.com/dlang/dmd/pull/11570
If I can't make it work, I'll have to abandon fixing https://issues.dlang.org/show_bug.cgi?id=12832
> structure SSSE3 array of constants

- std/typecons.d
Fixes `Nullable.apply!"a.foo"` not working.
Mea culpa!
> Fix issue 21199: call `unaryFun!fun` in `Nullable.apply` to support string parameter.

- std/uuid.d
All characters of interest to `std.uuid.parseUUID` are ASCII so there is no reason it cannot work on a range of `char`s or `wchar`s.
> Fix Issue 21201 - let std.uuid.parseUUID accept input ranges whose elements are char or wchar, not just dchar

- std/typecons.d
This became a problem with the change to make `in` its own storage class, but luckily no release has been made yet.
> std.typecons : AutoImplement: Handle 'in' storage class

- std/algorithm/comparison.d
Sigh. Every time I get back to looking at things, code is more complicated.
> min must be stable

- posix.mak
Cherry-picks https://github.com/dlang/phobos/pull/7586 into stable, s.t. Buildkite is green for stable.
CC @schveiguy
> Cherry-pick auto-decoding Makefile changes to stable

- std/traits.d
I'm using https://github.com/dlang/dmd/pull/11632 as a way to adapt projects.
With this PR, it should pass for Phobos and the documentation tester.
I should probably add it to Buildkite like what Steven did for auto-decoding 🤔
> std.traits: Adapt unittest to pass with `-preview=in`

- std/traits.d
Reverts dlang/phobos#7609
Checking whether this PR broke the Buildkite sumtype build.
> Revert "std.traits: Adapt unittest to pass with `-preview=in`"

- std/traits.d
```
`isAssignable` would previously return `true` for non-copyable types,
even though code that tried to use an lvalue would not compile.
This behavior was originally found when implementing `-preview=in`.
With the new -preview=in check, the const-folding seemed to be a bit
too aggressive when an rvalue is passed, meaning that the check might
fail (probably due to the code that initialize the temporary).
```
The failure with SumType has been fixed.
> Fix 21210:  std.traits : isAssignable false positive on disabled copy struct

- win32.mak
- win64.mak
See https://github.com/dlang/dmd/pull/11653 for details.
> Disable Windows builds on auto-tester

- posix.mak
The preview is now enabled by default.
CC @wilzbach
> Remove deprecated -preview=markdown flag

- std/experimental/allocator/building_blocks/kernighan_ritchie.d
This is so tiny it probably doesn't really warrant a pull request. Noticed it while toying around with import graph visualization.
Before/after:
> kernighan_ritchie imports

- std/math.d
Per https://forum.dlang.org/post/ukdlpmrnwfddeofcgbot@forum.dlang.org.
> Provide float and double versions of fmin and fmax. Improve docs.

- win64.mak
because of https://github.com/dlang/dmd/pull/11736
> remove NOICF linker command, no longer needed

- std/container/array.d
This is a warning that showed up when running the testsuite in GDC with the -Wextra flag.  Said warning is by design and based on the assumption that any function declared to take a const pointer or reference as an argument reads the pointed-to-object.
In the case of GC.addRange(), the possibility is that a scan could occur before the memory is initialized, and the GC sees false pointers as a result of that.
> std.container: Fix warnings that memory may be used uninitialized

- std/algorithm/comparison.d
No need to compute the type separately - just use `auto` and compute it incrementally.
> Simplify min and max

- std/algorithm/iteration.d
- std/range/package.d
- std/range/primitives.d
Arguably this is closer to correctness because some of these ranges don't define `opDollar`.
> EASY: factor implementations of range length into a mixin template

- std/container/rbtree.d
In `RedBlackTree`, add all possible qualifiers `const pure nothrow @safe @nogc` to `empty()` and `length()`. The class is final, thus I assume that this agrees with any user code.
Add the single qualifier `inout` to `front()` and `back()`.
> RedBlackTree.empty: const, .front/.back: inout

- std/file.d
- std/typecons.d
Reproduced the issue on a Linux box, problem was with throwing constructors during `RefCounted` initialization.
> Issue 21250 - dirEntries on non-existent directory causes assert error

- std/bigint.d
- std/math.d
Changes from old PR:`LN2` are are now cast to the appropriate precision, `0.5* _` now have the appropriate precision suffix.
Still to go, functions with `real` only implementations:
* remainder
* remquo
* NaN (creating one with a given payload)
* getNaNPayload
* logarithmic functions
Blocked on:
* https://github.com/Netflix/vectorflow/pull/33 merged, waiting on new tag.
> Mostly fix 18559: std.math.* should stop using real overloads by default

- std/math.d
part of the fix for https://issues.dlang.org/show_bug.cgi?id=18559
Previous PR: https://github.com/dlang/phobos/pull/7463
> fix real precision use for inverse and hyperbolic trig, scalbn, fdim, fma, pow

- std/concurrency.d
This request fixes the following two issues:
- Fix [issue 13930](https://issues.dlang.org/show_bug.cgi?id=13930) - std.concurrency can't send immutable AA to another thread
- Fix [issue 19345](https://issues.dlang.org/show_bug.cgi?id=19345) - std.concurrency does not work with structs of const value type
I used a different issue title for this request from the above two issues because the source of the problem is about `receiveOnly` rather than `send` function or `std.concurrency` itself.
> Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types 

- std/concurrency.d
Reverts dlang/phobos#7655
As mentioned [here](https://github.com/dlang/phobos/pull/7655#issuecomment-706595379), this broke the CI.
> Revert "Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types "

- azure-pipelines.yml
Including the addition of a `x86-mscoff_MinGW` job. The Phobos unittests are currently skipped for that job though, apparently due to an issue with the used LLD linker.
> Sync Azure CI script with druntime's

- std/concurrency.d
- std/variant.d
This is a re-submit version of #7655.
> Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types

- std/math.d
> [LDC] move `pragma(inline, true);` out of function bodies

- .cirrus.yml
Requires https://github.com/dlang/dmd/pull/11868.
> Add Cirrus CI

- std/variant.d
Reopened to see if things build.
> Make Phobos compilable with preview=fieldwise

- std/complex.d
One occurs due to 64-bit vs. 128-bit mismatch, the rest are most likely accounting for precision differences in FP instructions.
All tests that use `isClose` would have being previously using `approxEqual`, which is a lot more forgiving in amount of difference which is acceptable.
> std.complex: Relax some more unittests for floating point precision on ARM64

- std/stdio.d
This moves the std.process import inside the unittest. The import is not used elsewhere, and so is unnecessary for non-unittest builds. This greatly speeds up importing std.stdio. (In a simple testcase, more than 90% of the import time of std.stdio was spent on std.process)
I've tried to keep whitespace changes to a minimum, while keeping the code readable.
> std.stdio: move std.process import inside unittest

- std/math.d
---
I don't really understood the `TODO` here, as `tanImpl` is @safe and `tanAsm` is @trusted, so here should be marked as @safe .
> math: mark tan as @safe instead of @trusted
