dlang/phobos

- std/stdio.d
Instead of using buf.length = 0, use buf = buf[0..0] slice technique to clean
the array and reuse, if possible, the buffer to reduce GC allocations.
---
Benchmark: https://gist.github.com/run-dlang/7d0a5264d186ac8db487447ec5352366
> stdio: optimize readln algorithm for non-char type

- std/regex/internal/backtracking.d
- std/regex/internal/ir.d
- std/regex/internal/thompson.d
- std/regex/package.d
Use pure/enforced version of `malloc` and `free` functions and fake pure the custom memoized `defaultFactory` and `matchOnce`.
> regex: partially make regex pure

- std/file.d
`rmdirRecurse` should be @safe as the cast(string) is safe in this context and
dirEntries, even though @system, it uses a RefCounted iterator which inside
will always make the reference deleted as the reference will never be passed
outside the function scope.
> Fix Issue 18157 - std.file.rmdirRecurse should be usable in @safe

- std/digest/package.d
- std/numeric.d
Code compiled with `-preview=in` is currently supposed to link successfully against druntime/Phobos compiled without `-preview=in`.
There were still a few places where `-preview=in` makes a difference for existing `in` params; convert them to `const [scope]`, analogous to PR #7593.
> Minor fixes for -preview=in and targets preferring by-ref for `real`

- std/bigint.d
`x & 1` is a natural way to check the low bit of `std.bigint.BigInt x` but that allocates unlike the less natural `x.getDigit!uint(0) & 1`. Examples of this appearing in Phobos  are `std.bigint.powmod(BigInt, BigInt, BigInt)` ([PR #7525 fixes it](https://github.com/dlang/phobos/pull/7525)) and `std.numeric.gcd!T(T, T)` when instantiated for `BigInt`. Adding special handling for `x & 1` will aside from helping naive uses also improve performance of generic templated code that operates on arbitrary number-like types.
> std.bigint.BigInt: special case x & non-negative int to avoid unnecessary allocation

- std/complex.d
- std/conv.d
- std/internal/math/gammafunction.d
- std/math.d
These are changes based off the dmd-cxx branch, so there may be a few more cases that need to be dealt with in master, however this is enough for 32-bit FreeBSD to compile and initially pass all phobos unittests.
> Add support for FreeBSD x86 reals

- std/traits.d
>`hasIndirections` is used (among other things) to check whether a memory allocation needs to be registered with the GC (e.g. in `RefCounted`), or whether an object can be safely sent to another thread (e.g. `hasUnsharedAliasing`). For these purposes, it is crucial that it checks _all_ indirections, not just the explicitly declared ones.
This also affects a great deal of code in the wild ([for instance esmi_containers](https://github.com/dlang-community/containers/blob/fc1625a5a0c253272b80addfb4107928495fd647/src/containers/internal/node.d#L60-L64)). However this behavior change has the potential to cause disruption so I thought it would make sense to target master rather than stable. Does that make sense?
> Fix Issue 15425 - std.traits.hasIndirections fails to recognize nested structs

- .cirrus.yml
CI script was updated to handle environment variable in dlang/dmd#11982
> freebsd/ci: Explicitly target FreeBSD 12 in cirrus CI

- std/complex.d
- std/conv.d
- std/internal/math/gammafunction.d
- std/math.d
Backport of #7689, tested on i586-freebsd12.2.
> [dmd-cxx] Add support for FreeBSD x86 reals

- std/array.d
Fixes a unit test to pass with https://github.com/dlang/druntime/pull/3281.
> [trivial] std.array: Don't assume that .idup of immutable array will reallocate

- std/traits.d
Notable dead feature (never been supported) in gdc that should definitely be removed. :-)
> [dmd-cxx] Remove support for extern(Pascal)

- std/datetime/systime.d
For the same reasons why we can't test all clocks in core.time.
> std.datetime.systime: Skip unsupported clocks in unittests

- changelog/deprecate-stdio-bindings.dd
- std/stdio.d
The (accidentally?) publicly available `extern(C)` binding for `getline` in `std.stdio` has been deprecated. Any code that still needs it can import the symbol from `core.sys.posix.stdio` in druntime instead.
Within phobos itself, this function is unused.
> std.stdio: Deprecate extern(C) getline

- changelog/deprecate-stdio-bindings.dd
- std/stdio.d
The publicly available `extern(C)` binding for `getdelim` in `std.stdio` has been deprecated. Any code that still needs it can import the symbol from `core.sys.posix.stdio` in druntime instead.
> std.stdio: Deprecate extern(C) getdelim

- std/stdio.d
@thewilsonator failed my little turing test. :stuck_out_tongue:
> std.stdio: Fix typo in getdelim deprecation message

- changelog/jsonvalue-get-integer-conv.dd
- std/json.d
Currently `JSONValue.get` allows to convert the stored `integer`, `uinteger` or `float_` to a floating point type, but throws a JSONException("JSONValue is not a xxx") when trying to convert a stored `uinteger` to any signed int, or a stored `integer` to any unsigned int.
This can be quite annoying as the parser sets the type to either ulong or long depending on how high is the parsed value.
This patch adds the following conversions:
- `integer` -> any signed or unsigned int
- `uinteger` -> any signed or unsigned int
Note:
- The value will be truncated if the target type is narrower than the stored type, but this seems to be expected as it is the current behaviour when converting for example a `ulong` to `ubyte`
- `JSONException`s are raised if there is a conversion overflow
- Should I …
> Add some conversions to JSONValue.get!T

- std/process.d
The `std.process.uniqueTempPath()` helper is needed for a `std.experimental.checkedint` unittest.
> [stable] Fix little unittest compilability regression for iOS-derived targets

- .cirrus.yml
Using HOST_DC is deprecated in the makefile, and the CI triggers a message
that can be misleading while trying to debug.
> CirrusCI: Use HOST_DMD instead of HOST_DC

- std/mathspecial.d
The documentation alternately describes betaIncomplete as computing the incomplete beta function and the *regularized* incomplete beta function. The definition given is that of the regularized version, and the values returned are consistent with this interpretation as well.
> Clarify documentation for betaIncomplete.

- std/range/package.d
This reverts commit f78fd811f0c34f426b638bb3cf86e0221d8bbeec.
It was merged into master (#7730) but not stable.
See discussion in https://github.com/dlang/phobos/pull/7734
> Stable: Revert "Remove some unnecessary undocumented explicit ctors in std.range"

- std/mmfile.d
MmFile.this claims that it throws std.file.FileException.
However, that never happens in practice:
* On POSIX, ErrnoException is thrown (due to use of errnoEnforce).
* On Windows, WindowsException is thrown (due to use of wenforce).
This change updates the documentation to reflect real types of
exceptions thrown by the constructors.
Another alternative is to change the MmFile itself to throw
FileException as it claims to do, but this will break backward
compatibility with existing programs.
> std.mmfile: correct the documented type of thrown exceptions

- std/format.d
Also use `opSlice` as recommended.
This looks like a simple omission or typo.
> Use templated formattedWrite in the example of it

- std/conv.d
This is currently blocking this PR [1] in dmd.
The commented test looks like this:
```d
static struct S2
{    
int i;
@disable this(this);
this(ref S2){}
}    
S2 s2 = void;
static assert(!__traits(compiles, emplace(&s2, 1)));       // this line is commented                                                                             
emplace(&s2, S2.init);
```
Emplace is not able to run this test because the copy constructor cannot be called with an rvalue (1) and its definition has masked the default constructor.
With the fix in [1], the copy constructor no longer disables default construction and therefore emplace is able to work in this scenario.
I commented the code because it is currently blocking [1], however, after [1] is merged I will uncomment it and make it a runnable test.
[1] …
> Temporarily comment one test

- std/container/array.d
insertAfter should receive a valid element or a Range of values according to
type T of the corresponding instance Array!T.
> container: array: add type checks for passed arguments in insertAfter()

- std/range/package.d
std.conv is not nogc but it's not really neccessary here as far as I can see (a manual > check passes all existing tests).
> Make std.range.enumerate @nogc. 

- std/traits.d
The current implementation relies on issue 21570 to reject enums with
static arrays as their base type.
Use another is-expression instead of `isStaticArray` to detect types
that are (convertible to) static arrays.
See https://issues.dlang.org/show_bug.cgi?id=21570
---
Blocking dlang/dmd#12142
> Make isAutoDecodableString independent of issue 21570

- std/traits.d
Inspired by the discussion in dlang/dmd#9014
> Fix Issue 21103 - isDynamicArray instantiates unecessary templates

- std/container/array.d
Since ae90bc7, we can simplify unittests by using Array!bool ctor instead of
manually do .insertBack(...). This improves example code readability.
> container: array: simplify some unittests by using Array!bool ctor instead

- std/range/primitives.d
- std/utf.d
walkLength can be significantly sped up for narrow strings in the common case where they begin with a run of characters that do not require decoding.
Benchmark on my laptop for 12 character all-ASCII string:
| compile command | string size | old MB/s  | new MB/s | ratio |
|-----------------|-------------|-----------|----------|-------|
| dmd             |   12        |  86.30    |  409.17  |  4.7x |
| dmd -O          |   12        |  92.85    |  840.56  |  9.1x |
| dmd -O -inline  |   12        | 298.88    |  842.44  |  2.8x |
| ldc2            |   12        |  75.58    |  474.29  |  6.3x |
| ldc2 -O3        |   12        | 727.53    | 2248.80  |  3.1x |
Benchmark on my laptop for 2000 character all-ASCII string:
| compile command | string size | old MB/s  | new MB/s | ratio | …
> Speed up walkLength for narrow strings

- std/typecons.d
`Nullable!T` has the following assignment operator: `opAssign()(T value)`. This `opAssign` can be called for both `Nullable!T` and `T` because of the inner `alias get this` of Nullable. However, when a Nullable is assigned to another Nullable
a bit copy is preferred rather then an alias this conversion. Despite this, `hasElaborateAssign` specifically calls opAssign thus triggering the `alias this`. To bypass this, I used the solution proposed by @FeepingCreature and added an opAssign overload that receives a `Nullable!T`. This does get rid of the deprecation, however, I don't know how to test this because when compiled with -de, the deprecation does not appear (and phobos is compiled that way). Suggestions?
> Fix Issue 20552 - Deprecated Nullable.get warning with Appenders

- std/file.d
I didn't look properly at the upstream "fix" for this, it seems.
> [dmd-cxx] Fix double initialization of field errno in std/file.d

- std/format.d
- std/string.d
- std/traits.d
- std/variant.d
Because taking these types out of the language would be [no small feat](https://github.com/dlang/dmd/pull/12069), the simplest place to begin is to stop testing for it.  Listed as the first point to tackle in [issue 14488](https://issues.dlang.org/show_bug.cgi?id=14488).
> Remove tests for complex and imaginary types

- std/format.d
Due to dmd bug 18269, the attributes of delegates are not always printed correctly. This blocks PR #7556 and PR #5797 from being merged and might cause more headaches in the future.
I relaxed the test somewhat to make it bypass that bug. I also added a note for users.
> Fix offending unittest, regarding formatting delegates.

- std/format.d
I just noticed, that CTFE can already be implemented independent of #7757 and followups. Of course, it will be limited to the part, where `snprintf is already replaced`, currently %e and %a applied to float and double.
Thanks to Petar Kirov and Paul Backus for help.
> Fix partially Issue 21573 - formatting floating points should be CTFE

- std/format.d
A fixup for #7393. Now it's guaranteed, that printing float and double with %a or %e will not use gc as long as the output is restricted to 500 characters. (Without this change, this guarantee did only hold for floats but not for doubles.)
> Minimize use of GC for doubles in printFloat.

- std/format.d
The bug is that if `T == immutable(void)[]`, then `const(T)` does not collapse to `const(void[])`, but is actually `const(immutable(void)[])`. So a strict type equality check will fail.
However, `const(T)` *is* implicitly convertible to `const(void[])`, which serves our purpose just as well. So just use that check instead.
> Fix issue 20848: format should work with immutable(void)[]

- std/xml.d
According to [DIP1013](https://github.com/dlang/DIPs/blob/d8f2e769c3a8c711e7886ccecc93eac9795dae9c/DIPs/accepted/DIP1013.md) all public symbols should loose their public comments after 5 non-patch releases. I hope I didn't remove too much...
> Remove documentation from std.xml due to deprecation in midterm.

- std/conv.d
- std/experimental/typecons.d
- std/functional.d
- std/typecons.d
Where it has been moved to. Also get rid of the corresponding tests in Phobos, an exact copy is in druntime (+ more `forward` tests).
Also extend a `scoped` test to make sure it properly forwards r/lvalue-ness of its arguments. This required dlang/druntime#3352
and thus wasn't added in dlang/phobos#7776 directly.
> Replace usages of std.functional.forward with core.lifetime.forward

- std/format.d
Inspired by an [article](https://dlang.org/blog/2020/05/14/lomutos-comeback/) from @andralex I found some speed optimizations for printing floating point numbers with %a. The idea is, to replace branches inside of a loop with arithmetics doing the same.
Some speed messurements (times in ns):
Compiler | fp type | old version with snprintf | current version | proposed version
--|--|--|--|--
dmd | float | 414 | 422 | 408
dmd -O ... | float | 421 | 344 | 306
ldc | float | 520 | 517 | 465
ldc2 -O3 ... | float | 292 | 105 | 105
ldc2 with DPO | float | 207 | 103 | 104
dmd | double | 420 | 504 | 414
dmd -O ... | double | 410 | 406 | 314
ldc | double | 509 | 593 | 513
ldc2 -O3 ... | double | 242 | 106 | 106
ldc2 with DPO | double | 216 | 106 | 105
Compilerflags for optimization with dmd where `-O …
> Improve speed for printing floats with %a.

- std/experimental/allocator/package.d
... and fix broken (public) unittests.
> Remove spurious __EOF__ hiding existing declarations/tests

- changelog/deprecate-approxEqual.dd
- std/math.d
Meanwhile all occurences of approxEqual in phobos, druntime and dmd are removed. 
In [changelog for release 2.091](https://dlang.org/changelog/2.091.0.html#isClose) it has already been announced that approxEqual will eventually be deprecated.
> Deprecate approxEqual.

- std/format.d
The bug was caused by formatElement [implicitly converting](https://github.com/dlang/phobos/blob/dc07f1ae3fe1a5b1fbf8a95f39861ce87964ec58/std/typecons.d#L3136) Nullable!string to string, that resulted in [an error](https://github.com/dlang/phobos/blob/dc07f1ae3fe1a5b1fbf8a95f39861ce87964ec58/std/typecons.d#L3114) when the Nullable was null.
New behavior is to use the toString method when available, instead of implicitly converting the value.
> Issue 17269: formattedWrite of struct with Nullable value fails

- posix.mak
- std/format/package.d
- win32.mak
- win64.mak
Now, that no more conflicting PRs are out there I wanted to reopen #7785, but probably got the order of steps wrong. Github now declines me doing so...
The idea is, to make very small steps here. One of the main problem of splitting modules is, that ideally no other PR should be merged during the process, because it's easy to overlook some of these changes while rebasing a splitting PR. So this PR just moves everything to std/format/package.d (with only a single slight change, that was needed).
See also PR #7765 for the main idea behind this.
Concerning the timing: In my opinion we can already do some preparatory steps before 2.096.0 is out: Moving to `package.d` (this PR) as well as extracting the internals. For me this would be convenient, because I could continue working on formatting …
> Prepare to split up std.format into submodules.

- std/system.d
It is not supported something like "Non-Posix" version in the compilers so I propose this enum here.
Related:
https://github.com/denizzzka/d_c_arm_test/issues/18#issuecomment-766745608
> std.system: adds enum OS.unknown

- std/format/internal/floats.d
This step is the decision, if a %e-like or a %f-like output should be created. According to the [specs](https://www.cplusplus.com/reference/cstdio/printf/) `%g` produces the shorter of the two. That's wrong. The cutting points depend on the requested precision, roughly between `10^^precision` and `0.0001` `%f` is used and `%e` else (sign ignored here). Different rounding modes make this a little bit more difficult, but doable. The result looks like this:
```
final switch (rm)
{
case RoundingMode.up:
useE = abs(val) >= 10.0 ^^ f.precision - (val > 0 ? 1 : 0)
|| abs(val) < 0.0001 - (val > 0 ? (10.0 ^^ (-4 - f.precision)) : 0);
break;
case RoundingMode.down:
useE = abs(val) >= 10.0 ^^ f.precision - (val < 0 ? 1 : 0)
|| abs(val) < 0.0001 - (val < 0 ? (10.0 ^^ (-4 - f.precision)) : 0);
break; …
```
> std.format: Prepare to add %g (step 1).

- std/format/internal/floats.d
Another followup on #7810. Can be merged independently of #7815.
Precision is already adjusted in `printFloatG` so it is not necessary to repeat this in `printFloatE/F`.
> std.format: Add %g (step 3): Add template parameter to printFloatE/F.

- std/format/internal/floats.d
> std.format: Add unittests for %g (step 2).

- changelog/bugfix_for_pow.dd
- std/math.d
Recently I compared several algorithms for calculating `pow(b, e)` with `b` being a floating point and `e` an integer. I checked the current implementation, the implementation suggested in PR #7297, the implementation suggested in issue 16200 and the original algorithm from stepanov quoted in issue 16200 with the intend to replace the current algorithm with the one mentioned in issue 16200.
First, I tested the algorithms for correctness, by comparing several random generated calls with the exact result calculated with the linux tool 'bc' and rounded appropriately. The results showed, that the current algorithm has a design flaw for exponent -2 and PR #7297 has further design flaws for exponent -3 and 3.
|float|current|PR #7297|issue 16200|stepanov
|-|-|-|-|-
wrong|4098 (1.64%)|9411 …
> Fix Issue 21601 - std.math : pow(float/double, -2) produces sometimes wrong result

- std/math.d
I just encountered a unittest next to the `pow(float,int)` overload that actually tested `pow(float,float)`. As I'm unsure if this should have tested longs or reals, I duplicated the test, moved one to the correct overload and fixed the other.
> Correct pow unittest.

- std/complex.d
Although the wrappers are `pragma(inline)`, we're relying on the fact that cross-module inlining is happening.  Using the `core.math` intrinsics directly removes any hidden indirection.
> std.complex: Use core.math intrinsics instead of std.math wrappers

- std/bigint.d
- std/conv.d
- std/format/internal/floats.d
- std/internal/math/errorfunction.d
- std/internal/math/gammafunction.d
- std/mathspecial.d
- std/numeric.d
> Throughout Phobos use core.math intrinsics instead of std.math wrappers

- changelog/nullable-remove-alias-get-this.dd
- std/typecons.d
As per https://github.com/dlang/phobos/pull/7759
This is a bit early. There's three possible interpretations of the deprecation plan: the comments say "after 2.096", the deprecation notice says "in 2.096", and strictly speaking it should be removed in 2.098 because it was deprecated two major versions later than I'd originally intended.
But given all the issues we've had with the damn deprecation warning, at this stage I think people will mostly be glad just to be rid of it - especially considering this does not remove functionality, just convenience.
edit: added changelog entry
> std.typecons.Nullable: Remove deprecated 'alias get this'.

- std/format/internal/write.d
Made `package(std.format)` global. See #7805 for the rationale.
> Break long lines of std.format.internal.write.

- std/algorithm/sorting.d
I once was looking whether Phobos had Quickselect, and it took me really long before I found it's actually called `topN` there.
I think it's useful to mention this in the documentation. 
Some other things:
- topN is missing a Returns: section
- most functions have no blank line separating the summary and description paragraphs
- the docs often mention `swap` referring to `std.algorithm.mutation: swap`, but that is not obvious.
> improve documentation of std.algorithm.sorting

- std/math.d
A few weeks ago I checked the alternative algorithms for `pow` given in issue 16200. Although not the way @andralex suggests there (see attachment of the issue for why I did not implement the suggested algorithm and more details), this finally lead to some other ideas on how to improve speed for this function. The main idea is to bail out early, when the result is a fixpoint (NaN, +/-inf and 0.0).
IMHO, the result speaks for itself (averaged over random bit patterns for the floating point value and iterating the exponent from -500 to 500 on x-axis, run on 2 billion tests for each FP type):
For "normal" operations, that is calls, where the result is not one of the fix points, there is no theoretical advantage in this algorithm. But luckily, there seems to be no disadvantage in practice. …
> Fix Issue 16200 - Faster pow implementation for integral exponents

- std/algorithm/searching.d
This was implied by the previous version, but it's not super intuitive, so it's worth spelling out explicitly.
I also fixed a simple usage error in the docs for `any` and `all`.
> Document behavior of "any" and "all" with an empty range

- std/package.d
Maybe `typetuple` was intentionally left out?
> Add forgotten modules to std.package.

- changelog/transposed-remove-save.dd
- std/range/package.d
Using CI to see if there are any tests that need to be updated.
If changelog entry is too short maybe someone could fill in some more details. I don't know the full story behind the `Transposed.save`.
> Remove deprecated std.range.Transposed.save

- std/format/internal/floats.d
As I already wrote in #7810, I'm rather reluctant to use the functions simulating floating point math. So this PR can be thought of as being a questioning PR, asking, which variation we should use.
Some reasons, why I'd like to remove the simulating functions:
- I compared the results of both variations with the output of glibc's `snprintf`: All three variations differ and I'm convinced that different implementations of `snprintf` will differ too. It might even happen, that the result might differ depending on the compiler and optimization turned on or not.
- I fear, that the simulating functions will cause problems with the implementation of `reals`. It might even be the case, that `real==double` doesn't work. I've got a bad feeling about this, but can't really break this down to …
> std.format: Add %g (step 7): Change calculating the split

- std/digest/hmac.d
References to the local buffer may not be assigned to a parameter with longer lifetime.
---
Blocks dlang/dmd#12260
> Fix DIP1000 violation in sdt.digest.hmac

- std/algorithm/searching.d
See https://issues.dlang.org/show_bug.cgi?id=21473. There is other stuff going on but fixing this makes that code compilable. Because in certain situations this is causing the compiler to crash I think it is reasonable to consider this a bug fix rather than an enhancement.
> Avoid quadratic template expansion in constraints of multiple search term versions of std.algorithm.searching.startsWith & endsWith

- std/base64.d
Same like #7832 for decoding...
> Issue 21706 - Assertion failure in Base64.decoder for empty input range of ranges

- std/sumtype.d
> Fix Issue 21708 - SumType.opEquals gives confusing error message

- std/base64.d
Removed a misleading sentence from the documentation too (my last attempt to fix this, was guided by this sentence...)
Probably this fix is also needed for the unpadded version, but I don't know this exactly yet and don't want to break there anything...
> Fix Issue 21707 - std.base64: Faulty input creates range error instead of Base64Exception

- std/bigint.d
[Some public unit tests are currently being translated into e.g.](https://dlang.org/phobos/std_bigint.html#.BigInt.opCast.3
)
```d
writeln(0x1.abcd_e8p+124f); // cast(float)BigInt("0x1abc_de80_0000_0000_0000_0000_0000_0000")
```
which is not confidence-inspiring. Additionally `writeln` will default to scientific notation instead of float hex format here which makes it not immediately obvious that the result is correct when it's being printed rather than checked in an `assert`.
> Adjust some `assert(a == b)` examples in std.bigint to improve DDoc runnable examples

- std/math.d
This are the unittests promised in #7823. I had to loosen the constraints somewhat. This is due to the way D handles floating point numbers (using real with unknown size internally), especially in CTFE, where there are `floats`, that are larger then `float.max` but not `float.infinity`...
> Add extreme unittests for pow()

- changelog/std-datetime.dd
- changelog/std-exception.dd
Taken from #7545.
Forgotten in #7844 and #7846.
> Add forgotten changelog messages.

- posix.mak
- std/math/package.d
- win32.mak
- win64.mak
As this path worked quite well with `std.format`, I'll try it here too. The idea is to just move everything to package. This is simple to review and makes it much easier to split of single modules later.
@ibuclaw tried this several times in the past, last try with #7326. According to him, meanwhile all problems with compiler magic should be removed.
> Prepare to split up std.math into submodules.

- std/algorithm/iteration.d
Make first example `@safe`.
Add separate example for `each` with index 
Split `opApply` example into separate block.
Remove doc-comment for example that wasn't as clear.
> std.algorithm docs: tweak `each` examples

- std/format/package.d
`array_ptr_diff` has got a public comment and therefore shows up in the docs, where it doesn't belong...
> Remove public comment from array_ptr_diff.

- std/typecons.d
An attempt to avoid depending on a compiler bug (dlang/dmd#12294).
> Simplify some Proxy.opDispatch conditions

- std/format/spec.d
I removed `fmt` from first sentence, because this sentence can be used in overview tables without context, so the reader has to guess what `fmt` is about.
I added a description of the template parameter, because I remember, that I was quite confused by template parameters, when I read the docs as a beginner. Such descriptions probably would have helped.
I added a bug, I found, because I think, listing bugs shows, that we care about bugs. And it motivates (at least me) to remove them. (Here, this won't be difficult, but I wanted to keep bug fixing and documentation separated.)
I changed the public unittest. IMHO, it should show, how `singleSpec` can be used, instead of examples how it throws, when wrongly used. I kept the old test though as a normal unittest and added a few more checks.
> Rework documentation of std.format.spec : singleSpec

- std/json.d
> Fix Issue 16432 - JSON incorrectly parses to string

- std/format/internal/floats.d
Extracting the bits of x87-reals in CTFE is a little bit more difficult than just casting. 
There is one line, where I feel unsure, caused by a remark of @kinke in [issue 21688](https://issues.dlang.org/show_bug.cgi?id=21688#c3): 
```
if (isNaN(val) || val == real.infinity || val == -real.infinity)
``` 
Can we rely on these comparisons to find out, if the value is infinity?
Although it can currently never be executed, I had to change a line inside `printFloatA`, to make the code compile. There is a static assert next to that line, that would fail else. This change would have happened anyway in one of the next PRs.
A side effect of this PR is, that NaNs and infinity can already be formatted, so I added the corresponding unittests.
> std.format: Add x87-reals (step 1) - extract bit patterns

- std/experimental/checkedint.d
It might make sense to support something like `hookToString` but that can be done later.
> std.experimental.checkedint.Checked is not compatible with "%d" and "%x" integer format specifiers

- std/format/package.d
- std/format/write.d
A lot of the former description and most of the unittests are of interest for more than just the "plumping" `formatValue`. So I moved this to the package description, to avoid loss, (but left all unchanged for better reviewability and because I plan to rework the package description anyway, when I'm through with all functions).
> Rework documentation of std.format.write : formatValue

- changelog/deprecate_formatElement.dd
- std/format/internal/write.d
- std/format/package.d
- std/typecons.d
`formatElement` is currently `public`, but undocumented. A comment next to it says "undocumented because of deprecation", but I think this is wrong. Looking into the history of this, I found out, that it was made public, because it was useful in `std.typecons`. I presume, that at that time `package(std)` was not available.
I see two ways out of this:
1. Make it really public, that is add documentation and useful public unittests.
2. Deprecate it's public view.
I've chosen the second way, because in my opinion formatting elements and should not be done differently to formatting these elements as single items (i.e. "%(%s%)" should not format an element different than "%s" does). While this PR doesn't really change this behavior, it makes it easier to do so later with an other deprecation …
> Deprecate public access of formatElement

- std/sumtype.d
> Revert "Fix Issue 21731 - SumType should provide convenient access to the typ…"

- std/file.d
Use selective imports for `listdir` example, not fully qualified calls.
Don't use `args`, use current directory for working runnable example.
Move parallel dmd example into a documented unittest. Use `pattern` argument instead of filter & endsWith for simplicity. Note the `listdir` example already uses `map`.
Only run these 'tests' for `version(StdDdoc)`.
> std.file docs: Tweak dirEntries examples

- changelog/deprecate_unformatElement.dd
- std/format/internal/read.d
- std/format/package.d
This is a logical followup of #7875. IMHO `unformatElement` is even less useful for public use, than `formatElement`.
> Deprecate public access of unformatElement

- std/format/package.d
I removed the link to the "introductory" because it links to a tutorial which is about defining custom format specifiers, which I do not consider "introductory". If wished, I will write a real tutorial in the wiki and link that here.
I removed the remark about easy import from `std.string`, because I cannot see, why `import std.string` is easier than `import std.format`. IMHO, this remark had historical reasons, because `format` has been moved from `std.string` to `std.format` years ago.
> Rework introductory part of std.format package description

- std/format/spec.d
- std/format/write.d
I suggest to replace `separatorCharPos` from `FormatSpec` by a new variable `dynamicSeparatorChar`. The reason is, that `separatorCharPos` is used like a `bool` but is an `int`. Furthermore I perceive the name as misleading because it does not denote a position, but just answers the question, if the character is dynamically provided at runtime or not.
I didn't add a release note, because I think, it is too unimportant for that. If I should guess, I'd say, that probably nobody is using this directly...
> Deprecate separatorCharPos in FormatSpec.

- changelog/deprecate_enforceValidFormatSpec.dd
- std/format/internal/write.d
- std/format/spec.d
That is the third (and last) item in `std.format` that has been made public without any good reason. It's probably only used in `formatValueImpl`.
I did not manage to find a useful workaround here, but IMHO there is no real use case either.
> Deprecate public access of enforceValidFormatSpec

- std/format/internal/floats.d
- std/format/internal/write.d
- std/format/package.d
On my computer there is no failure, but in the [Online D Editor](https://run.dlang.io/is/YrEFFp) it reports failures since 2.074.1, but worked before.
I just added a unittest to find out on which computers this fails.
> Fix Issue 17381 - Checked format string is permissive after floating point argument

- std/format/package.d
- std/format/read.d
I moved the original public unittests to module scope, because I think they apply to `formattedRead` as well. I just copied them without change for better reviewability and will take care of the module docs in a separate PR once this PR (and #7925) are merged.
> Rework documentation of std.format.read : unformatValue

- std/format/package.d
- std/format/write.d
I moved a public unittest, that's about grouping to package, because I think, that's something, that is relevant for other functions of `std.format` to. It even does not use `formattedWrite` directly. I will cope with that later, when reworking the package docs.
I renamed the template parameter `A` to `Args` for consistency with `format` and `sformat`. While at other places it is common to use single letters as template parameters, throughout `std.format` they are descriptive.
I changed the order of the two overloads, like I did with `format` and `sformat` because I think, for beginners the one without template parameters is better comprehensible. For the same reason I did not use idiomatic D for the first example.
The output range is named a writer here, I guess that is for historic …
> Rework documentation of std.format.write : formattedWrite

- std/format/package.d
This is a followup on #7919 but can be handled primarily independent. Its main purpose is to replace the description and the grammar of format strings with something, that describes the current implementation.
The order of the `Parameters` is currently not strictly enforced. I'm even unsure if  `Precision` and `Separator` should be reversed - what do you think?
Concerning issue 15227: There are some more missing things in the documentation of `std.format` mentioned. I will take care of them in followup PRs. Anyway I consider this a fix of the issue, because it's main theme is about the grammar and I don't want to fritter about this.
> Fix Issue 15227 - std.format undocumented grammar

- std/base64.d
It takes char arrays, strings included, without needing to manually call `.byCodeUnit` or `.represenation`
> New overload for std.base64.Base64Impl.decoder 

- std/format/spec.d
IMHO, there is not much documentation needed here, so I only added a few sentences.
But I noticed, that the deprecation warning is not shown automatically by ddoc. So I used this PR to add it too.
> Rework documentation of std.format.spec: Module description

- posix.mak
- std/math/algebraic.d
- std/math/constants.d
- std/math/exponential.d
- std/math/floats.d
- std/math/hardware.d
- std/math/integral.d
- std/math/package.d
- std/math/remainder.d
- std/math/rounding.d
- std/math/traits.d
- std/math/trigonometry.d
- win32.mak
- win64.mak
Since splitting out a whole has not worked out well here (see #7887), I'd like to try a different approach: This PR provides only a skeleton, that needs to be filled. This way it is possible to move the unproblematic functions and care about the problematic ones separately.
I tried to find good names for the subpackages, by going through math packages of other languages. The rough idea was to use the table at the top of `std.math`s docs as a guide. I add `integral` though, which is a new submodule. It should contain integer maths, like `isqrt` or `isSquare` or such things. IMHO this is something, that Phobos is missing.
> Add empty submodules to std.math.

- posix.mak
- win32.mak
- win64.mak
In preparation for making `-transition=complex` the default in D.
See dlang/druntime#3433 for the druntime PR of the same name.
> Remove -transition=complex from the Makefiles

- changelog/add_conversion_target.dd
- std/traits.d
This is meant as an alternative to #7842: The idea is to add two new functions to make clear, if the list contains unsafe conversions, or not.
If accepted, I will use these in a separate PR (because it needs also some changes in `std.variant`) to deprecate `ImplicitConversionTargets`.
I left everything, that is not about builtin types untouched. (I don't understand this part in every detail yet.)
Some points, that might be debatable in `SafeImplicitConversionTargets`:
- I removed `byte` from the list of `char` and likewise `short` from `wchar` and `int` from `dchar`. For me, these casts feel unsafe. What do you think?
- I treated `real` like `double`. For x87-reals this makes no difference, but longer reals should be able to represent all values of `long` and `ulong`. As there is no clear …
> Add AllImplicitConversionTargets

- changelog/formatting_floats_in_CTFE.dd
- std/format/internal/write.d
Finally going life with formatting x87-reals.
I consider this a fix for several issues, although the issues might still remain for some exotic reals: There is no official list, which reals D does support and also no way for me to test if the issues still exist. That means, the issues can never be closed if we do not decide at some time, that it's enough and anyway any fix of these issues will high likely be to support printing floats for that exotic reals, so there is no benefit in leaving the issues open.
> std.format: Replace snprintf for x87-reals

- std/format/package.d
Formatting decimals with `%b`, `%o` and `%x` is often referred to as writing this number in binary, octal and hexadecimal. But that is not, what (C-)users expect and what the current implementation produces: It is just an image of the underlying bits. That means `format!"%x"(-10);` results in `fffffff6` instead of `-a`. I tried to follow this with the descriptions.
A similar problem occurs with `%u`, which is often called as formatting as unsigned integer. This was needed with C, because C has no traits and cannot know if the argument was meant to be a signed or an unsigned integer, as far as I know. In D this does not make any sense and in the current implementation `%u` just produces the same results as `%d`. IMHO `%u` could be discarded completely. Yet, people think of it as a feature …
> std.format: Add overview of format indicator

- std/format/package.d
This functionality is unexpected and buried in between examples down the page. This adds a note just below where compound specifiers are first introduced to make it more prominent for anyone reading the docs.
> Make string/character auto-escaping more prominent

- std/format/package.d
I kept the description of the flags rather brief. They will be given in more detail in the followup PR, which will feature a large table of types and format chars, which will give special meanings of the flags in more detail.
> std.format: Add description of flags, width, precision, separator and positional arguments.

- changelog/add_conversion_target.dd
- std/traits.d
This is a logical followup on #7881 and #7954. `ImplicitConversionTarget` is neither fish nor fowl.
> Deprecate ImplicitConversionTarget

- std/algorithm/sorting.d
Checking sortedness according to a given predicate must not use `==` operator
because it may not be in accordance with the predicate.
> Check for sortedness must not use `==`

- std/format/internal/write.d
- std/format/package.d
I first tried to refactor the old implementation, but soon noticed, that this is a long path leading to nothing. So removed most of it and wrote it anew. What I kept is the handling of "%r" and the calculation of `base`, as well as some other smaller ideas.
What I skipped is: 
- Using three functions instead of one. Seems to me, that this was a relict from ancient times, not necessary anymore. 
- Support for `cent` and `ucent`. The old implementation would not have worked anyway and I see not need in supporting something, that might never be added. And if needed, it should not be a problem to make this work for `cent` too.
- Extra handling for one digit numbers. I checked this. With modern optimization techniques, this had no effect at all.
What changed:
- `%u` has been handled like `%d` …
> std.format: New version for formatting integral values using writeAligned

- std/typecons.d
See related: https://github.com/dlang/phobos/pull/7570
> fix Issue 21801 - std.typecons.ReplaceType does not work for `in` parameters

- std/numeric.d
Whatever tests/observations were done in #4940 no longer apply when I run benchmarks locally:
```
ubyte_euclid: 10 secs, 741 ms, 853 μs, and 9 hnsecs
ubyte_stein: 6 secs, 98 ms, 939 μs, and 7 hnsecs
ushort_euclid: 13 secs, 442 ms, 495 μs, and 6 hnsecs
ushort_stein: 9 secs, 266 ms, 581 μs, and 2 hnsecs
uint_euclid: 13 secs, 285 ms, 480 μs, and 4 hnsecs
uint_stein: 9 secs, 173 ms, 414 μs, and 8 hnsecs
ulong_euclid: 20 secs, 227 ms, 886 μs, and 2 hnsecs
ulong_stein: 9 secs, 181 ms, 300 μs, and 8 hnsecs
```
> std.numeric: Always use Stein's algorithm for integral gcd()

- std/math/exponential.d
- std/math/package.d
- std/math/trigonometry.d
`isClose` does essentially the same as `equalsDigit`, is faster and doesn't use `libc`. This change was suggested by @ibuclaw in #7942 (second to last "show resolved" parts).
> Replace equalsDigit with isClose

- std/numeric.d
This is a pretty lame restriction.  Parameters should always be transformed to an unsigned value.
> fix Issue 21834 - std.numeric.gcd can't handle negative values

- std/format/internal/write.d
It took me a whole month to understand a comment from @Geod24 in #7870. Sorry for being so ignorant. This is essentially the same fix, but with `-preview=in`, so I did not create a new issue; hope this is correct - the testers currently don't check with `-preview=in` as far as I know. I did that locally though. (And I still based on master, due to the heavy changes to `std.format` in the last weeks; again I hope that's ok.)
Finally, I wonder, why there is no `customPutWriterFormatString`. Does anybody know a reason? Or was it just forgotten?
> Fix second part of Issue 21722 - toString(sink, string format) does not work with non-"%s" strings

- std/format/package.d
- std/format/write.d
This one was not easy for me, because I needed to understand some concepts that where new to me. Thanks to @pbackus and @FeepingCreature who helped me here. I hope, I got everything right.
I mainly used the former description from `formatValue` which was temporarily moved to `package.d` and tried to improve it (it was a little bit outdated, but still in good shape) and added two more examples.
I did not include the new overloads of `toString` with `-preview=in` from @Geod24. As far as I understood the preview concept, this should not yet be made public in the docs. If I'm wrong here, please tell me.
> Rework documentation of aggregates of std.format.write

- std/format/internal/write.d
#7949 introduced a small bug: Padding with zeros if zero flag is present even if it should be ignored (which is almost always the case). This PR fixes this.
> std.format: Fix a small bug.

- std/process.d
It simply unblocks all the signals in a forked process spawned by `spawnProcessPosix`.
Note that the unittest for it uses `std.concurrency.receiveTimeout` and waits 3 seconds in the worst case. It may slows down the speed of unittests.
I will be happy if you have ideas to improve the test for it.
> Fix issue 21575 - Child processes spawned by std.process.spawnProcess accidentally inherit signal masks in parent process

- std/process.d
> [dmd-cxx] Fix Issue 17844 - std.process.execute should allow not capturing stderr 

- std/math/algebraic.d
- std/math/exponential.d
- std/math/hardware.d
- std/math/operations.d
- std/math/remainder.d
- std/math/rounding.d
- std/math/traits.d
- std/math/trigonometry.d
I narrowed down all `std.math` imports in `std.math` to the submodule.
With this, I consider the split of `std.math` essentially finished. (Maybe there is a little bit of cleanup needed and all other imports in Phobos should also be narrowed.)
Last: I wonder if we should move `isClose` into `traits` submodule (or at least publically import it there). People will expect it probably there, because it sounds `traits` like.
> Narrow imports in std.math.

- std/math/package.d
Removes a few things from `std.math : package`, that are not needed anymore.
> Clean up std.math.package

- std/format/internal/write.d
- std/format/read.d
- std/typecons.d
Several unittests in `std.format` are scattered around. I collected all of `std.format.internal.write` that belonged to a different place and put them where they should be (e.g. next to the function they test.)
There was one unittest that I moved to `std.typecons`. The original bug resided in `std.format`, but meanwhile the implementation of `std.typecons` changed and `formatElement` isn't called there anymore. IMHO it makes no sense to keep this in `std.format`.
> Move unittests from std.format.internal.write at correct place.

- std/algorithm/iteration.d
Currently the splitter can't be configured to keep the separators.
By using the flag Yes.keepSeparators, the splitter will keep the separators in the bucket.
Examples:
"a|bc|def".splitter!("a == b", Yes.keepSeparators)('|')
> [ "a", "|", "bc", "|", "def" ]
"|ab|".splitter!("a == b", Yes.keepSeparators)('|')
> [ "", "|", "ab", "|", "" ]
"a=>bc=>def".splitter!("a == b", Yes.keepSeparators)("=>")
> [ "a", "=>", "bc", "=>", "def" ]
"abXcdxef".splitter!("a.toLower == b", Yes.keepSeparators)('x')
> [ "ab", "X", "cd", "x", "ef" ]
"a|bc|def".splitter!("a == b", Yes.keepSeparators)('|').retro
> [ "def", "|", "bc", "|", "a" ]
> Fix issue 16288 - Add splitter functionality that allows to keep the sentinels

- changelog/rework_format_docs.dd
- std/format/package.d
Last one in a long row of rework document `std.format` PRs!
While trying to unify the descriptions of compound specifiers I realized, that I erred on the use of them. So I mainly took the former description (which was updated in PR #7944) and merged it somehow with my former description.
I moved all examples to real unittests and added several more to cover most of the stuff explained before.
Finally I added a release note.
> std.format: Repair docs of compound indicator and add examples.

- std/format/internal/write.d
- std/format/package.d
- std/format/read.d
- std/format/write.d
A last leftover from the split of `std.format`: several unittests in `package.d` belong to a different place. Aside from some imports I had to correct, it's all copy&paste.
> Move unittests from std/format/package.d at correct place.

- std/format/internal/write.d
Now, that these tests are moved at the right place (see #7991), there is no need anymore to keep them at `package` scope.
> Make std.format.internal.write: formatTest private.

- std/format/package.d
- std/format/spec.d
`arrayPtrDiff` looks a little bit C'ish... Might have had it's purpose at some time, but is not needed anymore...
> std.format: Remove arrayPtrDiff.

- std/format/package.d
`snprintf` wasn't the only reason, why this test didn't work...
> std.format: make reflection test work for floating point values

- std/format/internal/write.d
The error message changes slightly for the first two overloads, but as this is only for us developers, I don't see a need to fix this.
> std.format: Refactor formatTest

- .dscanner.ini
- std/format/package.d
- Instead of heaving two almost identical functions, let's one call the other
- While doing so, I realized, that the second version had a bug: The last part of the test was never executed due to an `assert(false)`.
- Meanwhile AAs can be handled by CTFE. Thus, no specializing necessary anymore.
- And that means, no more `assert` without message...
> std.format: Refactor formatReflectTest

- std/numeric.d
Seemed surprising that there was a `gcd` without an `lcm`.  I wonder if anyone might know why.
> std.numeric: Implement least common multiple

- std/format/package.d
- std/format/spec.d
The `separator` needs to be after `width`. I don't know though, if it should be before or after `precision`. The current implementation allows both.
> Fix Issue 21846 - std.format: provided format string for toString does not work with grouping

- std/format/internal/floats.d
- std/format/internal/write.d
This is a first step towards making formatting floats 100% `@nogc`, by using `writeAligned`. To do so, `formatValueImpl` in `internal.write` has to pass the writer to `printFloat`. 
To avoid having to do so in all unittests too, I wrote a small wrapper for the unittests. This wrapper is not `@nogc`, but the unittests in `std.format.internal.floats` don't need to be, only the one which guards against allocating.
In this last test, I used `NoOpSink` from `std.format.package.d` as a writer, because for that test the formatted result is not important. Therefore the tests which take nan or inf as argument now return an empty string. I added one more test there, showing, that indeed no allocations happen, even when the width is larger than the buffer size.
Finally I had to make `writeAligned` …
> std.format: Make formatting nan and inf 100% @nogc.

- std/format/internal/floats.d
- std/format/internal/write.d
A copy of #8001. The bot had not noticed my forced push, so I tried to restart the testers with closing and reopening, but I'm not allowed to reopen now, because there are forced pushes...
I had to remove windows from the unittest due to issed 20972, hence to forced push.
> Fix Issue 21853 - std.format: formatting real.max in CTFE fails

- std/format/internal/floats.d
- std/format/internal/write.d
Followup on #7971; see there for the roadmap.
The calls to `printFloat0` are replaced by a calls to `writeAligned` which does the same more general and without allocating.
`writeAligned` needed another parameter: fractional digits are yet another stretchable element due to trailing zeros. The interpretation of `precision` for floating point values differs from the interpretation of it for integral values. Therefore I added an `enum PrecisionType` to distinguish the various meanings of `precision`. Eventually it will replace the boolean parameter `integer_precision` - for the time being I added an additional wrapper.
> std.format: Make formatting 0.0 100% @nogc.

- std/stdio.d
These should have never been public.
```
FPUTC('a', cast(_iobuf*)core.stdc.stdio.stdout);
```
> std.stdio: Deprecate aliases that should be internal to implementation

- std/format/internal/floats.d
- std/format/internal/write.d
Followup on #7971 and #8000. See there for more details. See also #8005.
> std.format: Make formatting %e (and partly %g) 100% @nogc.

- std/file.d
Reverts dlang/phobos#7906
1. Unit-tests should _never_ invoke the compiler (think ARM, or PPC where dmd doesn't exist).
2. PR caused a regression https://issues.dlang.org/show_bug.cgi?id=21796
> fix Issue 21796 - Revert "std.file docs: Tweak dirEntries examples"

- std/traits.d
Symbols without members should produce an empty tuple. `""` is also not a member and hence requires additional special casing.
> Fix 21863 - FieldNameTuple returns emptry string for interfaces

- std/regex/internal/ir.d
The constraint was actually a runtime `if`, leaving `assumePureFunction`
without a `return` at the end of the function.
This was detected by dlang/dmd#12311
> Fix template constraint of assumePureFunction

- std/process.d
`wait(Pid, Duration)` allows to wait until the process terminates
or the timeout expires.
It's currently windows-only because a decent posix implementation
is quite difficult and this allows us to sort out the API beforehand.
CC @andralex as this introduces a new symbol
> Issue 20257 - Add wait(Pid, Duration) for windows

- changelog/fieldnametuple_interface.dd
- std/traits.d
Partially reverts the changes made in #8011 for non-interface types to keep `AliasSeq!""` as a special error code. 
CC @RazvanN7 @Geod24
> Revert change to FieldNameTuple for non-interface types

- changelog/formatting_floats_nogc.dd
- std/format/internal/floats.d
- std/format/internal/write.d
- std/format/package.d
Followup on #8005, #8006 and #8007.
- Add note for the changelog.
- Remove several useless buffers
- Remove two items from note in docs of `sformat` about GC usage.
I also tried to annotate a unittest with `@nogc`, but that failed. The reason is, that there are several calls to range primitives (e.g. `put` in `writeAligned` or indirectly in `graphemeStride`, where the compiler does not manage to deduce that they are `@nogc`.
Please note that the changes in `std.format.internal.write` look like much, but aside from the first few lines it's moving everything four spaces to the right, because the `static if` doesn't need this anymore.
> Clean up after making formating floating point numbers @nogc.

- std/traits.d
Replaces https://github.com/dlang/phobos/pull/7453
ping @berni44 , @RazvanN7 
This should probably go in 2.097 so we don't release an incomplete version of ImplicitConversionTargets a second time. Does that need master or stable?
> Fix issue 20756: Handle interface argument in `AllImplicitConversionTargets`.

- std/process.d
Add `@trusted` wrappers for calls to C functions that are always called with valid arguments.
Targeting stable because this doesn't change the behaviour.
> Make std.process.browse @safe and sync attributes for windows/posix

- std/math/exponential.d
These symbols are required when gdc or ldc builds this module.
> std.math.exponential: Fix imports for non-INLINE_YL2X path

- std/format/internal/floats.d
- std/math/operations.d
Extracting bitpatterns from floating point values is something, that is not only useful in `std.format`. I therefore suggest to move this to `std.math` and eventually make it public.
The new function is only `package(std)` yet, because I'd like to improve it, before going public (if at all): I think, that the implied bit of the mantissa should be added, that the bias should be subtracted from the exponent and that the stupid bit from x87s should be provided. I didn't add this here, to make the review easier and also to avoid merge conflicts with #8000 and its followups.
I think #5825 tried to add something similar, but I don't understand the details of that PR and maybe it's also outdated.
> Move bitpattern extraction from std.format to std.math.

- std/meta.d
This PR:
* simplifies definition of `staticIndexOf` by unifying the type- and alias-based variants
* improves the implementation
> Simplify and improve staticIndexOf

- std/meta.d
Types can also be compared with the isSame trait. This saves a couple of seconds for the entire phobos unittest.
> Simplify isSame

- std/process.d
Both public `pipeProcess` and `pipeShell` functions accept a `scope` program/command parameter.  It looks like a mistake that the internal Impl function doesn't, which triggers an error if the target ABI requires that the caller destroys all arguments ([issue 21880](https://issues.dlang.org/show_bug.cgi?id=21880)).
> std.process: Add scope to pipeProcessImpl command parameter

- changelog/formatting_floats_in_CTFE.dd
- changelog/formatting_some_reals_as_doubles.dd
- std/format/internal/write.d
- std/format/package.d
I'd like to get rid of using `libc` in `std.format`. Meanwhile it is only used to format "exotic" reals, that is reals which are not 64-bit-reals nor x87-reals. I suggest to handle them (until someone volunteers to implement `printFloat` for them), by downcasting them to double and formatting that double.
Advantages:
- No dependency of `libc` anymore, that is, `snprintf` is finally removed.
- And that means: no dependency of the bugs in `snprintf`.
- CTFE for all reals
- Identical results on all platforms (the results from different `libc` implementations vary)
- No more known-to-be-buggy code in the floating point specialization of `formatValueImpl`.
- Support for more than 500 characters in the output.
- Use of the new =-flag also for "exotic" reals.
- No interference with `snprintf` …
> std.format: handle "exotic" reals by casting to double

- changelog/fields_interface.dd
- std/traits.d
`FieldNameTuple` now yields an empty tuple for interfaces, so `Fields` should match that behaviour.
Followup to #8011 / #8014 
---
Also added `History` sections to the documentation of `Fields` and `FieldNameTuple` to make the change more obvious for people who don't read the changelog (as proposed by @adamdruppe)
> Sync Fields with FieldNameTuple for interfaces

- std/meta.d
Further testing reveals that __traits(isSame) has a bug as well. This PR is a workaround.
> Workaround for https://issues.dlang.org/show_bug.cgi?id=21889

- std/container/array.d
Perhaps instead of (_a <= _outer.length) the intention was to write (_b <= _outer.length).
But I feel that (b - 1 < _outer.length) looks even better -- and is more consistent with various other checks (which also use <, not <=).
Yupii !
> container.array: RangeT: moveBack: Improve an assertion.

- std/process.d
This is imported by std.file on OpenBSD.
> [dmd-cxx] std.process: Change visibility of searchPathFor to package

- std/format/package.d
Don't know if it wouldn't be better to have to return type just being `auto`...
> Fix Issue 21456 - std.format does not accept enum member with string base type as template parameter

- std/complex.d
- std/internal/math/errorfunction.d
- std/math/algebraic.d
- std/math/exponential.d
- std/math/operations.d
- std/math/rounding.d
- std/math/trigonometry.d
As in PR #7821 & PR #7825. Mostly changes new imports from `std.math` being divided into submodules.
> Again use core.math intrinsics instead of std.math wrappers

- std/format/internal/write.d
- std/format/package.d
In the description of the issue it was considered a bug, that positional arguments cannot be used to change the order of key and value in an AA. This is not really a bug, because positional arguments are meant to select the argument of the function call and not the order of elements of a compound type.
Anyway, I like the idea of being able to change the order of key and value somehow. With the current implementation this is not possible. Further, positional arguments inside of a compound specifier make only sense for querying values like width or precision (see [issue 18599](https://issues.dlang.org/show_bug.cgi?id=18599)), but not for the whole element, because we know it already.
Although I generally dislike the abuse of features, I think, here it makes sense to use positional …
> Fix Issue 21808 - std.format: It should be possible to change the order of key and value of AAs.

- changelog/add_format_integers_as_floats.dd
- std/format/internal/write.d
- std/format/package.d
- std/format/write.d
- std/uni/package.d
Inspired by [issue 16078](https://issues.dlang.org/show_bug.cgi?id=16078) I added formatting with `%e` etc. for integers. I tried to reach an identical result to first casting and then formatting, while preserving all digits:
```
writefln!"%.10e"(1234567890);
writefln!"%.10e"(cast(float) 1234567890);
```
yields:
```
1.2345678900e+09
1.2345679360e+09
```
As can be seen: With the cast, the last four digits are lost while they are preserved without.
I decided to deviate from the floating point behavior in two places:
- Default precision isn't anymore 6, but just as large as necessary to keep all digits. The reason for this change is, that the trailing fractional digits of floating point values normally don't contain any information and thus can be cut away. This is not true for integrals and …
> std.format: Add formatting integers with %e, %f, %g and %a.

- std/math/operations.d
Like suggested in #7775 by @jondegenhardt I added the transition note from the release note and additional information on how to cope with 0.0 in the out of date note of `approxEqual` to make the transition easier.
> Add transition note from approxEqual to isClose.

- std/format/internal/floats.d
- std/math/operations.d
Followup on #8004.
`extractBitpattern` now returns the mantissa with implied bit and subtracts the bias from the exponent.
In `std.format` I removed this repeating code. For `%a` I had to move part of the code ahead of the digit extraction (and alter it slightly) to keep it working. All else is straight forward.
> extractBitpattern: Add implied bit to mantissa and subtract bias from exponent.

- std/bitmanip.d
Compiling a file that only imports `std.bitmanip` with `-vtemplates` printed before this PR:
```
/dlang/dmd/linux/bin64/../../src/phobos/std/bitmanip.d(182): vtemplate: 8 (8 unique) instantiation(s) of template `createFields(string store, ulong offset, Ts...)` found
/dlang/dmd/linux/bin64/../../src/phobos/std/bitmanip.d(229): vtemplate: 7 (6 unique) instantiation(s) of template `sizeOfBitField(T...)` found
/dlang/dmd/linux/bin64/../../src/phobos/std/bitmanip.d(150): vtemplate: 7 (6 unique) instantiation(s) of template `createStoreName(Ts...)` found
/dlang/dmd/linux/bin64/../../src/phobos/std/bitmanip.d(77): vtemplate: 6 (6 unique) instantiation(s) of template `createAccessors(string store, T, string name, ulong len, ulong offset)` found …
```
> Reduce template instantiations when importing std.bitmanip

- std/format/internal/write.d
Two nits: A space and a forgotten outcommented "pure".
> std.format: formatting floating points is meanwhile pure

- std/format/internal/write.d
I introduced a bug in #8015: I forgot, that even hex character digits have an odd ascii value...
> Fix Issue 21900 - std.format: round to even does not work for hex integers with letters

- std/regex/internal/ir.d
- std/regex/package.d
It's redundant and has the same invalid constraint that was
fixed for the other implementation
> Remove duplicate assumePureFunction from std.regex

- std/meta.d
No difference measured in unittest compilation time/memory consumed for unittests.
> Make staticIsSorted use static foreach instead of recursion

- std/conv.d
For example:
Evaluating `to!(int[])("")`
Leads to `ConvException` with message:
`Can't parse string: unexpected end of input when expecting"["`
but should be
`Can't parse string: unexpected end of input when expecting "["`
> Fix missing space in exception text in std.conv.to

- std/complex.d
Hopefully with #8065 in, `sqrt` won't be done at the wrong precision.
> std.complex: Add missing imports in unittests for non-DigitalMars targets

- std/encoding.d
- std/experimental/allocator/typed.d
- std/socket.d
Avoid conflicts with builtin `.init`.
Related [DMD pull](https://github.com/dlang/dmd/pull/12512).
> Rename the initial value of some enums from init to _init

- std/format/internal/write.d
- std/format/write.d
- std/stdio.d
This fixes the first of the two errors described in issue 9489. However, I'm not sure, if I don't break something else. This is especially true for the `ref` in the `foreach`-loop, especially, because when I try to fix the second part too, I get a "Error: symbol `_param_0` cannot be `ref`" pointing to this `foreach`.
Additionally, this produces a lot of merge conflicts with #8031.
So I'm quite unsure, if this should be merged. What do you think?
> Fix Issue 9489 - writeln of struct with disabled copy ctor

- std/format/internal/floats.d
- std/format/internal/write.d
See #8050 for the general idea.
I had to do two more things here
1. The rounding tool needs to have access to the integral part, therefore I included it into `hex_mant` and thus had to move there everything one character to the right.
2. When calling the rounding tool, I know ahead, that the integral part is always 0 or 1. Therefore a carry can never happen. To avoid adding a never used character to the left of `hex_mant`, I had to relax the in-constraint.
> std.format: Use rounding tool to round %a on floats.

- std/format/internal/floats.d
#8015 introduced a "rounding tool", that is a function in `std.format.internal.write` that can be used to round a sequence of decimal or hexadecimal digits according to the current rounding mode.
A series of pull request will now move over to use this tool for floating point values too. During the transition process, rounding is queried twice: Once in `formatValueImpl`, forwarded to `printFloat` and then discarded, just to be queried again in the "rounding tool". This had impacts on the unittests, that did not use the default rounding mode: They can now only be run, when the target computer supports `FloatingPointControl` form `std.math`. (When the transition process is finished, I'll add a cleanup-PR to remove the first querying.)
With this, there is an other thing to notice: IEEE knows …
> std.format: Use rounding tool to round %e on floats.

- std/process.d
Hi,
I've noticed that a couple temp files are leaked after each full
gcc test-suite run.
I'd like to fix that by the following patch.
Bootstrapped and reg-tested on x86_64-pc-linux-gnu.
Is it OK for trunk?
Thanks
Bernd.
> Cleanup temp files in libphobos unittest at src/std/process.d

- std/algorithm/searching.d
Part of https://github.com/dlang/phobos/pull/8076
> Annotate std/algorithm/searching.d to please dlang/dmd#12520

- std/traits.d
Looks like a copy-paste error from a similar unit test for std.traits.isIntegral.
> std.traits: Fix unittest for isNumeric

- std/path.d
Reverts dlang/phobos#8090
Something broke master, and this is the only change that touches absolutePath.
> Revert "Annotate std/path.d to please dlang/dmd#12520"

- std/format/internal/write.d
- std/format/write.d
- std/stdio.d
> Revert "Fix Issue 9489 - writeln of struct with disabled copy ctor"

- std/range/package.d
> Annotate std/range/package.d to please dlang/dmd#12520

- std/path.d
Copy of https://github.com/dlang/phobos/pull/8090 but with absolutePath excluded.
> Annotate std/path.d to please dlang/dmd#12520, absolutePath excluded

- std/bigint.d
Adds missing `return` annotations for opOpAssign() uncovered by https://github.com/dlang/dmd/pull/10924
> bigint.d: add return annotations for opOpAssign()

- std/json.d
> Annotate std/json.d to please dlang/dmd#12520

- std/conv.d
First of all, the DDoc currently says that:
"Leading zero is allowed, but not required."
The current implementation doesn't respect that.
D lexer allows leading zero(s) also.
And when considering octal from string, there is no possibility
of confusion, as the comments in the code claim. Disallowing
leading zeros for octal conversion from string, does not help
with anything actually.
So lets allow leading zeros.
Allowing leading zeros, does help when implementing various
APIs (i.e. glibc, Linux kernel), where a lot of octal constant,
are defined with multiple leading zeros, for readability and alignment,
in C headers. Having to manually or automatically special case
these when porting such API definitions, is counter-productive.
Example from a Linux kernel (`include/uapi/linux/stat.h`): …
> Fix issue 21926 - Allow leadings zeros in std.conv.octal(string)

- std/format/internal/floats.d
- std/format/internal/write.d
After #8073, #8059 and #8050 the rounding parameter is not needed anymore, because it is queried in the rounding tool directly.
PS: Due to personal reasons I'll take a break - this will be the last PR for the time being.
> std.format: Clean up rounding of floats.

- std/file.d
- std/path.d
Part of #8076
The https://github.com/dlang/phobos/pull/8107 and this PR are the two remaining Phobos blockers for dlang/dmd#12520.
> Annotate std/file.d to please dlang/dmd#12520

- std/utf.d
For <https://github.com/dlang/dmd/pull/12010>. Part of an ongoing effort to fix [issue 20150](https://issues.dlang.org/show_bug.cgi?id=20150).
> add `scope` to parameters of `toUTF32` and `toUTFImpl`

- std/range/package.d
Because it came up on the forum that the documentation of `release` is not informative: [When should I use SortedRange.release?](https://forum.dlang.org/post/csuedvxconyemajeifyp@forum.dlang.org)
> improve documentation of SortedRange.release

- std/format/internal/write.d
When checking whether `T.toString` for some class `T` is inherited from base class `Object`.
The runtime check fails when using a druntime DLL on Windows, where `Object.toString` in other DLLs/executables is a trampoline (in the druntime import library) to the dllimported function, with its own identity.
> [stable] std.format.internal.write: Replace brittle runtime check by compile-time check

- std/xml.d
Split off from https://github.com/dlang/phobos/pull/8113
> Add `return scope` to xml.toType

- std/bigint.d
- std/internal/math/biguintcore.d
Split off from https://github.com/dlang/phobos/pull/8113
The idea being to separate easy fixes from more tricky ones for easier review and regression testing.
> Annotate more return/scope on bigint functions

- std/getopt.d
Split off from https://github.com/dlang/phobos/pull/8113
`split` eagerly returns a GC-allocated array of slices. Since `scope` only applies to the top level, this returned array escapes the input string as far as dip1000 is concerned.
> Use splitter instead of split in getopt

- std/getopt.d
Part of https://github.com/dlang/phobos/pull/8113
The loop variable `v` is inferred `scope`, while `toUpper` simply accepts `string`. The input of `toUpper` could be annotated `return scope`, but that depends on the template `toCase` being inferred correctly.
> Use `icmp` instead of `toUpper` in getopt

- std/math/exponential.d
There are multiple issues with that commit, incl. out-of-bounds read on x86 systems and a significant performance decrease for qualified floating-point types; see #8124 for a full list of flaws.
I'm questioning the tackled goal in the first place, because I expect users to use that `pow` mainly with small integral exponents, *not* expecting underflows to 0 or overflows to ±infinity, so optimizing for these cases and sacrificing performance for the regular case doesn't make a lot of sense to me.
> [stable] Revert #7823 - Faster pow implementation for integral exponents

- std/math/exponential.d
> [stable] std.math.exponential: Minimally relax a pow() unittest for targets with 64-bit real

- std/format/internal/floats.d
Such as non-Apple AArch64; `printFloat()` doesn't support that format.
> [stable] std.format.internal.floats: Restore compilability of unittests for targets with quadruple `real` precision

- std/math/operations.d
Incl. fixing an out-of-bounds read on 32-bit x86 with `real.sizeof == 12` (detected via an LLVM assertion after merging to LDC).
> [stable] std.math.operations: Slightly revise extractBitpattern()

- std/conv.d
The buffer is initialized from right-to-left in `initialize()`, and unused bytes are left alone. Previously, the whole result wasn't preinitialized with `T.init`, so the unused buffer bytes weren't well-defined. Initialize it now (with zeros), as the whole buffer is still used for equality/identity comparisons etc.
> std.conv: Avoid undefined bytes in toChars() results for radix 10

- std/algorithm/searching.d
Improved the module documentation. Although the method documentation is correct, as it states the correct return type (a sub-type of `Tuple!()`), the same is not applied to the initial module documentation.
Made all tuples of Result have named types. This can improve readability and easiness when writing functional code.
> Fix std.algorithm findSplit methods module documentation

- std/internal/cstring.d
- std/internal/memory.d
- std/uni/package.d
Split off from https://github.com/dlang/phobos/pull/8113
Since realloc could return the input if there is enough capacity, it should be `return scope`. While in practice realloc is all `@system` and `@trusted` code, it does seem to trip up issue 20150.
> Add `return scope` to realloc

- std/conv.d
- std/range/package.d
Part of https://github.com/dlang/phobos/pull/8113
Turns `foreach` over an AliasSeq into `static foreach` because of [issue 21209 - scope attribute inference with does not work well with foreach](https://issues.dlang.org/show_bug.cgi?id=21209). Without this, `text` and `chain` are not `scope` compatible.
> Use `static foreach` for correct `scope` inference

- std/math/hardware.d
Because of bugs https://issues.dlang.org/show_bug.cgi?id=20565 and https://issues.dlang.org/show_bug.cgi?id=14831 the code generation for template functions declared inside static foreach loops is not reliable. Until this gets fixed, it's best to move these outside the static foreach.
> declaring templates inside static foreach is not reliable

- std/typecons.d
An attempt to avoid depending on a compiler bug (dlang/dmd#12668).
Backport of #7901
> [dmd-cxx] Simplify some Proxy.opDispatch conditions

- std/format/read.d
- std/format/spec.d
Function readUpToNextSpec in std/format/spec.d returned false when it encountered some specific types of errors and threw an exception on other types, however this wasn't taken into account in formattedRead in which it was assumed that readUpToNextSpec always threw exception. The change makes it so that readUpToNextSpec throws an exception instead of returning false.
> Fix Issue 20393 - formattedRead accepts input, that should be rejected

- std/traits.d
In microbenchmarks the new version of `isIntegral` took between 77% and 44% the memory of the old version depending on the specific types being tested. Reduction in time was similar.
> Improve memory usage & speed of std.traits.isIntegral & isSomeChar

- posix.mak
Segmentation faults or linker errors occur on 32-bit PIE platforms if any object is not compiled with `-fPIC`.
> Issue 21488 - Always compile phobos library with -fPIC on POSIX targets

- changelog/add_isValidCharacter.dd
- std/utf.d
For improving formatting characters with `std.format` I need this function (e.g. fixing [issue 21815](https://issues.dlang.org/show_bug.cgi?id=21815), but can also be used for [issue 6125](https://issues.dlang.org/show_bug.cgi?id=6125)). I could add it as a private function to `std.format`, but I think, it fits better in here and might be useful for users too. Especially, because the `dchar` version already exists here as `isValidDchar`, while `isValidWchar` and `isValidChar` are missing (and it's not D like to use these functions instead of a single template).
I did not manage to find out, why `isValidDchar` was designed like this. It was added in 2007 to git, but probably existed prior to that somewhere else. Eventually, `isValidCharacter` might replace `isValidDchar`. (Should I do so …
> std.utf: Add isValidCodepoint.

- azure-pipelines.yml
Working pipelines finish within 30 minutes, this prevents choking up the PR queue when there are real issues going on that cause Azure CI to stop and stall until the timeout limit.
(Also, cirrus CI timeout is set at 60m too).
https://github.com/dlang/phobos/blob/73e51d395ebee36029f337b3b97bd5efbcb694a4/.cirrus.yml#L32
> azure-pipelines.yml: Reduce timeout time to 60 minutes

- std/algorithm/comparison.d
because the general case instantiates a large number of templates.
> specialize max/min for common case

- std/algorithm/mutation.d
- std/array.d
- std/datetime/timezone.d
- std/internal/math/biguintcore.d
- std/path.d
- std/process.d
- std/random.d
- std/range/package.d
- std/string.d
Continuation of https://github.com/dlang/phobos/pull/8076, but for https://github.com/dlang/dmd/pull/12010 instead of https://github.com/dlang/dmd/pull/10924
I'm still figuring out what to do with range functions like `array`, `text` and `toCase`. `scope` fails to be inferred for simple `char[]` cases, but putting `scope` on them forces every InputRange it's called on to be `scope` compatible, while a generic `InputRange` can escape its innards through global variables or Exceptions. Not that I *want* to support such ranges, but it would make transitioning to `-dip1000` more diffcult for users, so it may be better to leave them be and use work-arounds for current Phobos functions that need them to be `scope`, like I did in `std.getopt` by replacing `split` (not `scope` compatible, returns …
> Annotate more of phobos with `return` and `scope`

- std/signals.d
This is #8137,changed to target stable
> Issue 19842 - only class member functions must be used be used as slots

- std/datetime/date.d
- std/datetime/systime.d
While the leading 0 looks nice in dates and times, they are misleading since they aren't meant to be octal literals and they give the impression that you can also use `08` and `09`, which you can't. It's not even used consistently in std.datetime's unittests: many number literals don't have a leading zero even when they are under 8. See also https://github.com/dlang/druntime/pull/3519
> Remove usage of octal literals

- std/array.d
`canExtend` suggests we can extend, but the code just tries to extend and then falls back to realloc.
> Change std.arrray.Appender.Data private variable canExtend to tryExtendBlock to reflect use

- std/stdio.d
- std/string.d
- std/uuid.d
Removing the redundant `Unqual` does not change the result.
> isSomeChar!(Unqual!T) -> isSomeChar!T

- std/array.d
std.array.insertInPlace: added tests for class and union.
> [DSSv3] Fix issue - 16339

- std/concurrency.d
Improved compiler error message and amended documentation to document the limitation.
> Fix  issue 20665 - std.concurrency.spawn should document not working with delegates

- std/file.d
I marked readImpl with @system because most of its code was already @trusted.
> [DSSv3] Fix Issue 16218 - Windows std.file.readImpl should be marked @system

- std/concurrency.d
Currently `std.concurrency.Tid` cannot be converted to a string safely by `std.conv` family, for example.
This request fixes this issue.
- It fixes the signature of `Tid.toString` to work with safe code (See also [std.format.formatValue](https://dlang.org/phobos/std_format.html#.formatValue)), and
- encloses an unsafe cast from `MessageBox` to `void*` with a trusted lambda function.
> Make `std.concurrency.Tid.toString` @safe-able

- std/typecons.d
Revert https://github.com/dlang/phobos/pull/7759
`alias Nullable.get this` is removed anyways.
See https://issues.dlang.org/show_bug.cgi?id=22176
Ping @RazvanN7
> Fix issue 22176: Revert #7759 "Deprecated Nullable.get warning with Appenders"

- std/container/rbtree.d
Needed for https://github.com/dlang/dmd/pull/12812
`RedBlackTree` is problematic for dip1000 because it has double links: a `RBNode` stores pointers to both left/right and parent nodes, so `scope` is defeated by a single round-trip `left.parent` or `right.parent`. It can be made to work by encapsulating the tree, but `RBNode` has a public `@safe` API that stores `&this` (a `scope` pointer) in a node supplied by a parameter. In the long term, either dip1000 needs to be improved or the current `RedBlackTree` API needs to be deprecated.
Related: https://github.com/dlang/phobos/pull/6922
> Mark RBNode.left and RBNode.right `@trusted`

- .cirrus.yml
As DMD bumped that base image, and Phobos CI depends on the DMD CI scripts (libcurl3 vs. libcurl4 etc.).
> Fix Cirrus CI (bump Ubuntu to 18.04)

- std/outbuffer.d
As with `std.stdio.{ writef, writefln }`, compile-time checked variants of these functions are nice to have, particularly when paired with `assumeWontThrow`.
> Add compile-time checked variants of writef and writefln to std.outbuffer.

- std/algorithm/iteration.d
- std/algorithm/searching.d
- std/path.d
This pull request is based on #8183. I merged the branch from #8183 into this one. I fixed this issue by implementing bidirectional range support for std.algorithm.iteration.joiner with separator. I included #8183 because std.path.asRelativePath, used in the issue example,(```ex.any!(e => t.asRelativePath("/folder").endsWith(e))```) cannot return a bidirectional range due to following reason : 
```
auto asRelativePath(CaseSensitive cs = CaseSensitive.osDefault, R1, R2)
(R1 path, R2 base)
....
auto r1 = ".."
.byChar
.repeat(basePS.walkLength())
.joiner(dirSeparator.byChar);
auto r2 = pathPS
.joiner(dirSeparator.byChar) //issue fixed in this pull request
.byChar; //byChar(alias of byUTF!char) cannot return a bidirectional range for non-auto-decodable ranges
//issue fixed in my #8183 pull …
```
> [DSSv3] Fix Issue 19727 - std.algorithm.endsWith fails to compile while startsWith succeeds

- std/stdio.d
Fixes #22222.
`exit(0)` call from libc does an exit sequence before exit and therefore
doesn't exit immediately. This causes problems on custom unittest runners. To
circunvent this problem we should call `_exit()` syscall to exit immediately.
In this context this is just fine to do and can prevent any future frustration
when debugging.
> Fix issue #22222 - Custom unittest runner on phobos fails due to segfault on fork() exiting

- std/experimental/allocator/mallocator.d
`GCAllocator` members are already `const` so I see no reason for `Mallocator` not to mimic that behaviour.
> Qualify Mallocator members as const

- std/math/trigonometry.d
Somehow, separating asm blocks in small pieces produces additional
`mov`s and other instructions on LDC that breaks the tanAsm logic and
therefore returns wrong values.
---
CC: @kinke 
I'm pretty sure this is not being tested on LDC. I would love to see some coverage reporting for LDC builds. A comparison of DMD and LDC coverage is desired to seek some problems on LDC code generation.
Here's the problem isolated: https://godbolt.org/z/bEhGa1d9P
Here is the asm diff of this change for more context:
```diff
--- t1  2021-08-19 19:21:19.595248484 +0100
+++ t2  2021-08-19 19:20:58.704874438 +0100
@@ -5,8 +5,9 @@
mov     rbp, rsp
fld     tbyte ptr [rbp + 16]
fstp    tbyte ptr [rbp - 16]
+        fld     dword ptr [rip + .LCPI0_0]
+ …
```
> std.math.trigonometry: fix tan asm x86 implementation for ldc compiler

- std/sumtype.d
Previously, the assignment of the local variable 'newStorage' to the
longer-lived member variable 'storage' caused scope inference to
(correctly) fail.
newStorage was necessary to work around issues 21229 and 22118. Since
those issues have been fixed, newStorage can be safely removed.
> Fix Issue 22117 - Can't store scope pointer in a SumType

- std/range/package.d
> std.range: make unittests reproducible when -boundscheck=off is present

- std/meta.d
According to `heaptrack` this improves memory consumption for this module's unittest in release mode by a couple of megabytes.
> Improve ReplaceAll

- std/algorithm/iteration.d
To be more precise, I made `chunkBy` infer `@safe` with forward ranges. Didn't touch the non-forward range implementation.
As always with marking formerly `@system` code `@safe`, reviewing definitely welcome.
> Partially solve issue 18161 - splitWhen and most of chunkBy now @safe

- std/array.d
Also replaced `emplaceRef` with `emplace` to remove dependency on DRuntime internals.
> fix issue 20937 - std.range.array of a lengthless range with indirection is not @safe

- std/meta.d
because the symbols referenced in these unittests are defined as
```d
// Used in template predicate unit tests below.
private version (StdUnittest)
{
template testAlways(T...)
{
enum testAlways = true;
}
template testNever(T...)
{
enum testNever = false;
}
template testError(T...)
{
static assert(false, "Should never be instantiated.");
}
}
```
Trivial, @RazvanN7.
> Use version (StdUnittest) in std/meta.d

- std/typecons.d
> std.typecons: make Nullable payload void initialized

- std/socket.d
This fixes a systematic assertion error when trying to receiveFrom a
non-blocking UDP socket. In this case, 'from.addressFamily' is equal to UNSPEC,
eventually failing the comparison and crashing the program.
> Only use 'from' if a packet was actually received

- std/traits.d
Building as `make -j1 -f posix.mak DFLAGS=-vtemplates` currently outputs
```
std/traits.d(5750): vtemplate: 1871 (1871 distinct) instantiation(s) of template `AliasThisTypeOf(T)` found
std/meta.d(1445): vtemplate: 990 (946 distinct) instantiation(s) of template `isSame(alias a, alias b)` found
../druntime/import/object.d(3456): vtemplate: 743 (743 distinct) instantiation(s) of template `RTInfo(T)` found
std/traits.d(5967): vtemplate: 447 (447 distinct) instantiation(s) of template `StaticArrayTypeOf(T)` found
std/traits.d(7476): vtemplate: 511 (362 distinct) instantiation(s) of template `isSomeFunction(T...)` found
```
As the template is private, and an template instantiation is significantly more costly memory wise than two traits-calls and an indexing, and that @andralex has expressed …
> Replace template AliasThisTypeOf with inlined calls to __traits

- std/traits.d
Introduced in: https://github.com/dlang/phobos/pull/7148/files#diff-b7918b17cede734a2dd4ecbf2a981d597a5978f52e02f9a3c6f53c9abd797f05R2717
Will revert and fix the test once: https://github.com/dlang/druntime/pull/3569 gets in.
> Temporarily comment one test in traits to be able to graciously fix druntime implementation

- std/algorithm/sorting.d
- std/string.d
std.sorting.algorithm's `HeapOps` has a static assert that requests "swappable of assignable" elements, where it clearly means "or". This PR fixes that typo and since it was such a small thing I scanned through the rest of the assert texts in that module, making some other minor changes, and then looked for more of the "greater equal" language elsewhere in Phobos, and changed those to "greater than or equal to".
Note that `>= n` comparisons with "greater than [n-1]" messages are very common in std.algorithm.sorting, e.g. in `topNPartitionOffMedian`:
```d
assert(r.length >= 12, "The length of r must be greater than 11");
```
So I adjusted the one off-by-one number down rather than use "greater than or equal" language, following this existing pattern.
> std.algorithm.sorting: fix typo and related texts

- std/format/internal/floats.d
- std/format/internal/write.d
- std/math/operations.d
Extracted from https://github.com/dlang/phobos/pull/8247.
`make -f posix.mak unittest` passes locally.
> Draft: Qualify some function parameters under std.format as const to reduce template bloat

- std/process.d
- Avoid extra layers by calling `to` directly instead of via `text` => `textImpl`.
- Use type-inference via `typeof` when possible.
> Improve searchPathFor

- std/datetime/systime.d
This pull request is aimed to solve the issue that toIsoExtString outputs a variable number of characters and this can break the alignment of documents.
> Fix issue 21507 - added precision for function SysTime.toIsoExtString

- std/socket.d
This simplifies the code and removes the need for a separate
version (StdDdoc) block.
> Replace FieldProxy with @property ref functions

- std/container/array.d
Simply propagate the const'ness to the return slice.
> Fix 22488 - Add inout to allow Array.data for const/immutable Array's

- std/container/array.d
Explicitly return `[]` when `store` wasn't intialized yet.
---
Targeting `stable` because this is minor fix.
> Fix 22487 - Don't access payload for unititialized array data

- .circleci/run.sh
- .cirrus.yml
- std/container/array.d
- std/datetime/timezone.d
- std/math/algebraic.d
- std/parallelism.d
- std/system.d
Conflicts:
* [`.cirrus.yml`](https://github.com/dlang/phobos/pull/8313/files#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bb)
---
Other PRs:
> Merge `stable` in `mater`

- std/container/dlist.d
Worksaround Issue 22510 (https://issues.dlang.org/show_bug.cgi?id=22510)
which prevented us from using structs with explicit copy ctors with DList.
> Add explicit default ctor for DList.PayNode

- std/container/dlist.d
- std/typecons.d
as they are essentially non-breaking bug fixes.
> Merge PR #8315 & #8316 in to `stable`

- std/file.d
- std/internal/cstring.d
- std/json.d
- std/process.d
- std/stdio.d
- std/uni/package.d
Currently, `inout` gives a free `STC.return_` lifetime to functions without an actual lifetime restriction on the returned value. See: https://github.com/dlang/dmd/pull/12689
In Phobos, this means that e.g. `tempCString()` gives unrestricted access to `TempCStringBuffer.buffPtr()`, so I fixed that by adding explicit `return` and adding `scope` to some functions that didn't have it already.
> Add explicit `return` to `inout` functions

- std/datetime/interval.d
- std/datetime/systime.d
- std/datetime/timezone.d
- std/file.d
- std/typecons.d
Currently, `inout` gives a free `STC.return_` lifetime to functions without an actual lifetime restriction on the returned value. See: [dlang/dmd#12689](https://github.com/dlang/dmd/pull/12689)
The `SysTime` struct has a `Rebindable!(immutable TimeZone) _timezoneStorage;` field with a getter that's inferred `scope` because `Rebindable.get()` is qualified `inout`. This PR makes `SysTime` and `TimeZone` compatible with `scope` without relying on the `inout` bug.
> Fix `scope` usage of SysTime/TimeZone

- std/random.d
(Of the machines I have immediately in-front of me).
X86_64 generates:
```
[7, 4, 2, 0, 1, 6, 8, 3, 9, 5]
[2, 0, 4, 5, 1]
```
X86 generates:
```
[4, 8, 7, 3, 5, 9, 2, 6, 0, 1]
[4, 2, 5, 0, 1]
```
X32 generates:
```
[4, 8, 7, 3, 5, 9, 2, 6, 0, 1]
[4, 2, 5, 0, 1]
```
SPARC64 generates:
```
[7, 4, 2, 0, 1, 6, 8, 3, 9, 5]
[2, 0, 4, 5, 1]
```
MIPS32 generates:
```
[4, 8, 7, 3, 5, 9, 2, 6, 0, 1]
[4, 2, 5, 0, 1]
```
MIPS64 generates:
```
[7, 4, 2, 0, 1, 6, 8, 3, 9, 5]
[2, 0, 4, 5, 1]
```
MIPSN32 generates:
```
[4, 8, 7, 3, 5, 9, 2, 6, 0, 1]
[4, 2, 5, 0, 1]
```
Obviously there's nothing target specific about this test, it's simply a 32-bit vs. 64-bit pointer discrepancy.
> std.random: Fix test for version(X32) targets

- std/traits.d
Can we please have this target stable? We depend on this at work and would like to avoid an intermediate fix of copying `fullyQualifiedName` into our code base.
Resolves https://issues.dlang.org/show_bug.cgi?id=22557.
> Fix Issue 22557 - std.traits.fqnType is missing support for typeof(null)

- std/algorithm/sorting.d
That way it's only impure for transformations that yield indirections, because (de-)registering memory ranges with GC is impure.
> schwartzSort to use pureMalloc so it's more pure

- std/parallelism.d
On line 2741, `if (nBytesNeeded < maxStack)` will force memory allocation in the case when `nBytesNeeded == maxStack` , even though it's not technically required, because the stack buffer can hold those bytes.
On line 2762 though, the check `if (nBytesNeeded > maxStack)` is slightly wrong then. If `nBytesNeeded == maxStack`, it would cause a memory leak.
The fix is to not allocate if they're equal.
> Fix a potential memory leak, typos

- std/datetime/timezone.d
On Arch Linux, there's an ASCII file in /usr/share/zoneinfo with instructions on how to submit security bug reports, as can be seen in the listing here:
https://archlinux.org/packages/core/x86_64/tzdata/files/
Currently the timezone unit tests fail due to this.
> Ignore SECURITY file when listing timezones

- std/range/interfaces.d
Previously, isInfinite!(RandomAccessInfinite!T) would always evaluate to
false, because the 'empty' method inherited from InputRange could not be
evaluated at compile time. Since isRandomAccessRange!R requires
(isBidirectionalRange!R || isInfinite!R), this meant that
RandomAccessInfinite!T was not recognized as a random-access range.
> Fix issue 22608 - RandomAccessInfinite is not a valid random-access range

- std/utf.d
This is an attempt to see how extensive the problems with https://github.com/dlang/dmd/pull/12989 are. I.e. is put() really throwing its parameter?
> put scope on std.utf.encode() functions

- std/conv.d
- std/utf.d
- std/xml.d
Attempt to make Phobos compile with https://github.com/dlang/dmd/pull/12989
The biggest problem so far is that range functions on narrow strings can throw exceptions on invalid encoding, so their free `scope` is gone. This does not fix the unittest build yet, and is still WIP. The `@trusted` on `put` needs to go and forcing `scope` on generic range objects is bad practice.
@nordlow
> Make `throw` functions compile with dip1000 pure-scope fix

- azure-pipelines.yml
See https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows
> Azure: Replace deprecated vs2017-win2016 image with windows-2019

- std/experimental/allocator/package.d
I'm tired of this heisenbug.
https://issues.dlang.org/show_bug.cgi?id=22660
> Comment out randomly failing test in std.experimental.allocator

- std/stdio.d
when the code is `!isOpen` it now means:
- in exception documentation it's now always saying "not opened" (or similar, it's clear the file is in error state in that case)
- in general documentation it now always says "closed or not yet opened" (to avoid mistaking it with eof)
- in runtime error messages it always says "unopened"
> std.stdio: clarify "not opened" documentation

- std/typecons.d
Copy ctors are still buggy, so unconditionally adding one for `Nullable` is everything but a non-breaking change (and was added in the 2.098.1 point release - #8318).
> Work around issue 22619 - Avoid Nullable copy ctor unless required

- std/conv.d
- std/file.d
- std/json.d
- std/path.d
- std/process.d
- std/range/package.d
- std/stdio.d
- std/utf.d
combines the very common constraint
`isInputRange!R && !isInfinite!R && isSomeChar!(ElementEncodingType!R)`
and adds a bunch of documentation with examples for users to understand
it better. This should lower the neccessary needed technical insight to
read basic docs, especially std.path and std.file docs.
Came up on a discord conversation:
> I have some clues already, but what is the reasoning behind this:
> [...]
> https://github.com/dlang/phobos/blob/4f979130d36e4292898f1c249cac5cd1582855ee/std/file.d#L2933-L2966
> Few simple terms in english would help
so now the docs for `isSomeFiniteCharInputRange` say: (IDE screenshot)
I initially wanted to put it in std.string, but it looked like adding it to std.range would least change the existing dependency cycles. (std.traits would have been …
> add isSomeFiniteCharInputRange as simplification

- std/typecons.d
When generating methods to implement e.g. an interface, it is also very useful to have an alias to the (abstract) function being overridden. E.g. to have access to UDAs.
> Also expose 'parent' when it's abstract

- std/array.d
Partial fix for -profile=gc to detect allocations from std.array.array.
This fix could be improved by propagating file/line/function info from user code down to `arrayAllocImpl`. But due to a limitation in IFTI, there's no clean way to do this without intrusive changes that have runtime costs when not compiling with `-profile=gc`. So  leaving that for a future PR.  We could at least get this fix in first to address the primary complaint in 14892 (allocations from std.array.array are not tracked). A more helpful file/line/function indication in the output is a further enhancement.
Depends on: https://github.com/dlang/dmd/pull/13545, https://github.com/dlang/druntime/pull/3681
> Fix issue 14892: std.array.array support for -profile=gc.

- azure-pipelines.yml
- win32.mak
The previous assumption was MODEL=32 because MODEL=32mscoff is built by
win64.mak.
Verified locally because Azure requires further changes outside of this repository - see dlang/druntime#3703.
> Make win32.mak compatible with MODEL=32omf

- posix.mak
- std/complex.d
- std/traits.d
Documented unittests should not depend on symbols hidden behind `version(StdUnittest)` because:
- users will see exmples containing functions that do not appear in the documentation (for example: Ctrl-f ceqrel on https://dlang.org/phobos/std_complex.html)
- this may cause linker failures for template instances because the module where the documented unittests are extracted is compiled with `-version(StdUnittest)` whereas phobos is not.
The fix is to compile the module where the documented unittests are extracted without `-version(StdUnittest)`. This makes sure that hidden symbols will not make it to the public user interface and also get rid of the linker errors.
cc @MoonlightSentinel @kinke
> Fix Issue 22704 - Linker error when running the public unittests

- std/range/package.d
`chooseAmong` is currently implemented by recursing `ChooseResult` which is really designed for `choose`. This is needless template bloat.
I made it the other way around: `ChooseResult` is implemented linearly with alias sequences in `chooseAmong` terms, `choose` becoming a `bool`-taking special case of it.
> Changed chooseAmong implementation from recursive to linear.

- std/traits.d
`isRvalueAssignable`, `isLvalueAssignable`, `isAssociativeArray`, `isSIMDVector`, `isPointer`, and `ifTestable` don't have any examples, so I'm adding some.
> std.traits: add examples

- std/typecons.d
To quote my bug report:
As I said in my DConf talk, `__traits(compiles)` is Satan, the Great Deceiver. The presence of `is(typeof())` (`__traits(compiles` by any other name) in the definition of `apply` needlessly turns a clear, readable error in the passed lambda into an incomprehensible template error that requires advanced language knowledge or blind guessing to untangle. And there's no point, because there's only one apply function! It should just be removed.
(Let's see if this passes the testsuite!)
> Fix issue 22701: Remove is(typeof()) callable check in std.typecons.apply.

- std/functional.d
When forward was moved to core.lifetime, a wrapper template was left in
std.functional for the sake of documentation. Since that wrapper
template is now undocumented, it no longer serves any purpose, and can
be removed.
> std.functional: use public import for 'forward'

- win32.mak
The makefile explicitly targets `-m32omf`, `-m32mscoff` is built by
`win64.mak`. The recent update to support `MODEL=32omf` broke support
for `MODEL=32` which used to indicate the old default (32 + OMF).
Ignoring the external `MODEL` parameter here fixes several components
(e.g. the installer repo) that rely on the old behaviour. This hack is
acceptable IMO because `win32.mak` never supported 32 + MS COFF and
will become obsolete once `-m32omf` is removed.
---
Complementary to dlang/druntime#3707
>  win32.mak: Explicitly use 32omf instead of $(MODEL)

- std/file.d
Bug https://issues.dlang.org/show_bug.cgi?id=22738
Discovered due to dub CI being broken due to [17488](https://issues.dlang.org/show_bug.cgi?id=17488) adding an additional path separator when it can on some platforms already have it at the end.
Workaround to get dub passing CI https://github.com/dlang/dub/pull/2208
> Fix Issue 22738 - std.file.tempDir adds an addition / even when it already has one

- std/datetime/systime.d
Most notably, the `fromSimpleString` format was plain wrong.
> Fix SysTime.fromXXXString() documentation errors.

- etc/c/odbc/sql.d
- etc/c/odbc/sqlext.d
- etc/c/odbc/sqltypes.d
- etc/c/odbc/sqlucode.d
I raised the original PR in 2019, but it didn't get merged until 2021, so the time-based deprecation process that was being used then is completely useless.
> etc.c.odbc: Update removal dates for ODBC deprecations

- std/zip.d
Now that 2.099 beta has been tagged and merged into stable, these are due for removal.
> std.zip: Remove declarations with expired deprecations

- std/uni/package.d
For https://github.com/dlang/dmd/pull/12689. The first parameter of `test` is not inferred `scope` anymore when `inout` doesn't imply a free `return`. I simply remove the needless `scope` from `testAll`,  I don't want to delve through multiple layers of templates to find the missing `return` / `scope` annotation when I don't need to.
> Make std.uni unittest compile with inout-return fix

- std/container/rbtree.d
Give `inout` functions explicit `return` annotations for https://github.com/dlang/dmd/pull/12689
> Fix return/inout usage in rbtree

- std/bigint.d
It's returning itself by value. See https://issues.dlang.org/show_bug.cgi?id=22790
> Fix bigint `return scope` order

- std/sumtype.d
This makes it clearer why SumType.opAssign must sometimes be @system.
> sumtype: add example of memory corruption to docs

- std/getopt.d
> getopt: mark defaultGetoptPrinter as @safe

- std/file.d
Since ReadFile requires an offset buffer and the maximum size is size_t.max, we
should offset with size_t to avoid overflow on dereferencing.
---
Blocking https://github.com/dlang/dmd/pull/13732 .
> std/file: use size_t instead of ulong for ReadFile on Windows

- std/range/primitives.d
...fails to mention different behavior depending on
hasElaborateCopyConstructor
The new wording is based on the documentation for core.lifetime.move.
> Fix Issue 18036 - Documentation of moveFront()

- std/sumtype.d
Reverts dlang/phobos#8394
---
Issue 21975 was fixed by https://github.com/dlang/dmd/pull/13738, so this is no longer needed.
> Revert "sumtype: work around issue 21975 in isSumType"

- std/experimental/allocator/mallocator.d
AddressSanitizer will report an error (rather than returning `null`) for such large allocations.
> Disable large allocation test that is not supported by AddressSanitizer

- std/bitmanip.d
This fixes issue 22838
https://issues.dlang.org/show_bug.cgi?id=22838
All hail AddressSanitizer! ;-)
> Fix 22838 - BitArray.count reads beyond data

- std/sumtype.d
Add `Source: $(PHOBOSSRC std/sumtype.d)` to `std.sumtype`'s module documentation.
> Fix 22851 - Add source reference to std.sumtype

- std/sumtype.d
- std/traits.d
The template constraint is needed to ensure that the inout constructor
overload is only considered when it is an exact match, without qualifier
conversions.
Without the constraint, a constructor call such as
const(SumType!(int[]))([1, 2, 3])
...would be ambiguous, since it would match both the const constructor
overload and the inout constructor overload at the "match with qualifier
conversion" level.
> Fix issue 22901 - Can't construct inout SumType

- std/conv.d
- std/functional.d
- std/sumtype.d
Previously, it was duplicated in std.functional and std.sumtype.
> [Refactor] Move toCtString to std.conv

- std/uni/package.d
Needed for https://github.com/dlang/dmd/pull/12989
A `@safe` unittest in `std.algorithm` tests `find` with a lambda `toUpper(a) == toUpper(b)` which can throw an exception on a bad encoding. This means it no longer has a free `scope` parameter, so it's no longer `@safe` to call on `scope` strings. Here I mark the input strings `return scope`, but only the `isSomeString!S` cases, because a generic range may implement non-scope range primitives. That means there's now separate overloads for the two cases instead of a `static if`.
> Make `toLower` and `toUpper` `return scope`

- changelog/std_typecons_nullable_range.dd
- std/typecons.d
Let's get Nullable working with the rest of phobos. Is this overkill? Probably. Definitely. 100% yes.
I genuinely have no idea what sort of documentation to write for these functions.
> Fix Issue 18374 - Add range functions to Nullable

- std/windows/syserror.d
Catch possible exceptions arising from e.g. UTF decoding and ensure that the message buffer doesn't contain partial output from a failed step.
The logic is seperated into a dedicated method because it's required for another bugfix.
---
Extracted from #8420.
CC @CyberShadow.
> Fix 22946 - Mark WindowsException ctor as nothrow

- std/file.d
- std/process.d
- std/socket.d
- std/stdio.d
- std/windows/charset.d
- std/windows/syserror.d
`sysErrorString` is used internally when creating an exception message for another error. But `sysErrorString` might throw an exception when the error message could not be retrieved - suppressing the actual error.
This patch replaces the internal usages of `sysErrorString` with `wenforce` / a helper function which report `Error X` if the lookup fails.
> Fix 13541 - Replace plain usages of sysErrorString for errors

- std/conv.d
Needed for unblocking the unittest build of Phobos with https://github.com/dlang/dmd/pull/12989
For the `isIntegral!Target` overload, make `scope` inference work.
For the `isFloatingPoint!Target`, avoid `@trusted`, and make `scope` inference work instead of forcing `scope` on the `source` range parameter (follow up of https://github.com/dlang/phobos/pull/8410).
> Improve `std.conv.parse` support for `scope` strings

- std/regex/internal/parser.d
Uncovered by https://github.com/dlang/dmd/pull/13972
> Fix switch fallthrough in std.regex

- std/base64.d
Improve attributes of std.base64
> Fix issue 22213 - Base64: Missing `@nogc` attribute on encodeLength

- std/path.d
Uncovered by https://github.com/dlang/dmd/pull/13993
typesafe variadic parameters are allocated on the stack, so they shouldn't be returned. This doesn't give an error here because the unittest is `@system`, since `buildPath` is not `@safe` yet.
> Fix std.path unittest returning dangling pointer

- std/exception.d
This allows retrieval of the error number when compiling with -dip1008.
> Issue 22986: Mark ErrnoException.errno as scope

- changelog/std_outbuffer_align.dd
- std/outbuffer.d
Extend the fill, alignSize, align{2,4} methods of `std.outbuffer.OutBuffer` to specify value to write
when filling (up to an alignment).
For flash device images it is desirable to use 0xff as the fill value,
because 0xff is the value of the unprogrammed flash memory cell. Padding
with 0 requires to programm the flash cell from 0xff to 0x00, which
increases wear and tear on the flash memory device. Usually there is some
larger block at the end if the flash memory image, which must be padded
up to the size of the flash device (usuallay a power of two). Instead
of padding with 0x00 the PR allows to fill with 0xff instead.
There might also be other use-cases, where it might be reasonable to fill
the alignment gaps with some other value than 0x00, e.g. when debugging
and viewing output data in …
> Add custom fill value to std.outbuffer.OutBuffer class

- changelog/scopesocket.dd
- std/socket.d
This is to fix issues with compiling projects with dip1000.
I'm not sure how to add appropriate tests, since dip1000 is a compiler switch.
> Add scope decorations to std.socket

- std/socket.d
https://github.com/dlang/phobos/pull/8438#issuecomment-1117421314
> std.socket: Always compile slow unit tests

- std/math/hardware.d
---
This triggered my editor to think Phobos is aligned by 3 spaces.
> chore(math/hardware): align spaces by 4 instead of by 3

- std/package.d
Previous change that moved std.checkedint out of experimental stage
didn't added the module to the list of modules on std module
`std/package.d`. This patch does that.
> chore(std): add std.checkedint to std module

- std/utf.d
> chore(utf): documentation of byUTF is wrong about thrown exceptions

- std/mmfile.d
blocking https://github.com/dlang/dmd/pull/14175 with:
```
.\unittest.exe
std.file.FileException@std\file.d(1061): C:\Users\VSSADM~1\AppData\Local\Temp\deleteme.dmd.unittest.pid3528-test.tmp: The process cannot access the file because it is being used by another process.
----------------
0x00E64640 in std.file.cenforce!int.cenforce
0x014AD3AA in std.mmfile.__unittest_L729_C9 at D:\a\1\phobos\std\mmfile.d(759)
0x014BBBA0 in void std.mmfile.__modtest()
```
because the unittests are using `scope` to allocate on the stack and is expecting the destructors to run.
> add scope to MmFile constructors

- std/sumtype.d
SumType.opAssign now avoids calling core.lifetime.move or
core.lifetime.forward during CTFE whenever possible.
> Fix Issue 23182 - Can't assign struct with opAssign to SumType in CTFE

- std/file.d
The issue is mostly blocked by https://github.com/dlang/phobos/pull/8368 since `dirEntries` and `byLine` use `RefCounted` and are consequently not `@safe`, but these two unittests can be made `@safe`.
> Issue 23190 - make some std.file unittests `@safe`

- std/math/hardware.d
According to RISCV specifications
https://riscv.org/wp-content/uploads/2019/12/riscv-spec-20191213.pdf,
figure 11.2, the mask flags should be NX, UF, OF, DZ, NV in order.
> RISCV: Fix wrong ExceptionMask values

- std/numeric.d
The CustomFloat should be converted to real before most operations, but
there is no support for convertions of real types with
quadruple-precision (e.g. real type on RISCV64 platform). As the
significand is stored using 112 bits, which cannot fit in a ulong type
(CustomFloat do not allow significand more than a ulong), we should only
use the highest 64 bits of significand (this may cause presicion loss
from real type, but is enough for what CustomFloat can support
at most). So add 48 padding bits by declaring a uint and a
ushort before the significand, and set align(1) in this case.
> std.numeric: Hack with quadruple-precision real type

- std/algorithm/comparison.d
With this change, at least my code compiles again successfully.
> Fix 23132 - Avoid ranges copy when compared for equality

- std/file.d
This blocks a fix for [Issue 22977](https://issues.dlang.org/show_bug.cgi?id=22977) - [dip1000] can escape scope pointer returned by nested function.
The offending code being:
```D
void rmdirRecurse(scope const(char)[] pathname) @safe
{
//No references to pathname will be kept after rmdirRecurse,
//so the cast is safe
rmdirRecurse(DirEntry((() @trusted => cast(string) pathname)()));
}
```
> Add missing `return scope` to std.file

- std/stdio.d
fixes [issue 23196](https://issues.dlang.org/show_bug.cgi?id=23196).
~~unfortunately, while i believe it should be possible to make this function `@nogc nothrow` [since we are throwing an error, which cannot be recovered from], i wasn't able to figure out how to get enforce to realise it. advice would be greatly appreciated on this front.~~
> preallocate oom error

- etc/c/zlib/win64.mak
- win64.mak
* Remove some unused variables.
* Default to a matching MSVC `cl.exe` & `lib.exe` in PATH instead of an ancient Visual Studio 2010 installation.
* Remove explicit 32-bit recipes, requiring a separate make invocation.
Analogous to https://github.com/dlang/druntime/pull/3853.
> Somewhat clean up win64.mak

- std/file.d
```d
string s = null;
remove(s);
```
would break as s is null and the removeImpl function has two arguments:
1. name as D string
2. name as tempCString
for dynamic ranges the D string is resolved from the tempCString by slicing the pointer up to strlen, however if the actual data is null, then the returned string by tempCString is a null pointer and attempting to strlen the null pointer segfaults.
Now a FileException is thrown, stating that a null string is not allowed and in the other methods that contained this strlen bug, `"[null]"` is now used as filename in the FileException.
> fix Issue 23215: segfault in std.file.remove

- posix.mak
Don't assume that the path relative from phobos->dmd is the same as druntime->dmd (tested using merged repositories).
e.g:
```
make -f posix.mak DMD_DIR=../dmd DRUNTIME_PATH=../dmd/druntime
```
> posix.mak: Pass absolute path of dmd when invoking druntime's makefile

- etc/c/zlib/gzguts.h
- posix.mak
ImportC is a C11 compiler, so this upgrades the zlib C sources to C11.
It paves the way to using ImportC to compile zlib.
> upgrade zlib C files to C11

- std/complex.d
I suspect this'll double the speed of complex log10, and fixes a potential precision bug.
> std.complex: Use complex(LN10) as divisor in log10

- std/random.d
`auto ref` is not needed on `Range` param
An overload with explicit `ref Range` added to support ranges returning `ref`
> Fix Issue 18631 - std.random.choice does not work with const arrays

- .circleci/run.sh
- posix.mak
- win32.mak
- win64.mak
Fixes build script paths to work with new merged dmd-druntime repository
See https://github.com/dlang/projects/issues/92
> [project] Merge druntime into the dmd repository

- std/math/package.d
- std/math/rounding.d
Use the [same algorithm](https://github.com/dlang/phobos/pull/5820) for floor(double) as used by floor(float).
[Shrinks the function size](https://d.godbolt.org/z/9n5fnGsY1) by half for gdc and ldc, and a third for dmd.
In all compilers the function is at most 2x faster.
> std.math: Faster floor(double) implementation

- .cirrus.yml
See https://github.com/dlang/dmd/pull/14076
> [stable] cirrus.yml: Use an alternative mirror for FreeBSD 11

- std/format/internal/write.d
- std/format/package.d
In general, we should be wary of forcibly converting user-defined types to `const` in generic code.
> Fix 23245, 23246 - std.format regressions

- std/file.d
Because 'in' are forbidden on extern C function with preview=in.
> std.file: Remove 'in' on OSX setattrlist declaration

- std/algorithm/iteration.d
The explanation of what `filter` actually does has been moved from the
"Returns" section to the main description.
The "Returns" section now documents the range capabilities of the return
value, which were previously undocumented.
> std.algorithm: improve documentation of filter

- posix.mak
- win32.mak
- win64.mak
I had a linker error due to a missing symbol for the ModuleInfo for std.internal.memory. This commit fixes that.
> Add std.internal.memory to the makefiles

- std/bigint.d
toDecimalString has pure nothrow @safe
and toHex has only @safe
> std.bigint: toHex pure attrib missed

- posix.mak
The linker errors out on MacOS 11.
> posix.mak: Don't link pthread and libmath on MacOS

- etc/c/zlib/inflate.c
Hello --
As mentioned in the bug report, this fixes a potential buffer overflow in zlib. It is a combined diff from
https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1
and
https://github.com/madler/zlib/commit/1eb7682f845ac9e9bf9ae35bbfb3bad5dacbd91d
I wasn't sure whether this should go in master or stable, so I chose master. In any event, we probably want this.
> Fix Issue 23288 - zlib: Fix potential buffer overflow

- std/json.d
The code has a kludge in it where it is recursively attempting to infer @safe, but that doesn't work, as the compiler assumes it is not @safe if recursive. The workaround in the code is to use a delegate. The trouble with the delegate a dynamic closure is allocated for it. Dynamic closures can escape, so dip1000 complains about `ref json` escaping the scope.
The solution is to get rid of the delegates, and use a nested function directly. Mark it as @trusted, which is also a workaround, but a better workaround than the old method, and at least this will work with https://github.com/dlang/dmd/pull/14364
For the future, it would be better to simply require the `json` parameter to be @safe.
> replace delegate with simple nested function

- std/getopt.d
The error message:
```
std/getopt.d(1863): Error: `@safe` function `std.getopt.__unittest_L1838_C7` cannot call `@system` function `std.getopt.__unittest_L1838_C7.makeAddNHandler`
std/getopt.d(1842):        `std.getopt.__unittest_L1838_C7.makeAddNHandler` is declared here
std/getopt.d(1866): Error: `@safe` function `std.getopt.__unittest_L1838_C7` cannot call `@system` function `std.getopt.__unittest_L1838_C7.makeAddNHandler`
std/getopt.d(1842):        `std.getopt.__unittest_L1838_C7.makeAddNHandler` is declared here
``` 
when compiled with https://github.com/dlang/dmd/pull/14364 because the delegate is enclosing a ref. This blocks that PR.
> getopt: make unittest @system because of delegate

- std/regex/package.d
Split up Synopsis examples, add titles and make them runnable.
Fix wrong multi-regex assert in example.
Remove redundant `auto` after `const`.
Move link out of `opCast!bool` example (as the macro is not expanded in a code block).
Change ctRegex `alias flags` parameter to string (which is already required by the implementation template).
> [std/regex] Improve docs

- std/typecons.d
blocking https://github.com/dlang/dmd/pull/14364
> get std.typecons to compile with PR #14364

- std/array.d
Non-static classes and structs have a hidden pointer to the outer stack frame, which can cause memory safety errors.
Blocking https://github.com/dlang/dmd/pull/14367
> make nested class & struct static

- std/complex.d
So that `std.complex` can be passed to extern(C) complex functions where ABI compatibility is required.
> std.complex: Add member function to returnComplex as a native type

- std/meta.d
Now that
- https://issues.dlang.org/show_bug.cgi?id=22421 has been fixed via https://github.com/dlang/dmd/pull/13252 and
- quadratic behavior of alias assign has been removed via https://github.com/dlang/dmd/pull/14332.
When compiling https://github.com/nordlow/phobos-next/blob/master/snippets/benchmark_staticMap.d,
the first implementation is the fastest and least memory consuming.
Implementations:
1. 0.08s 90 Mb
2. 0.12s 109 Mb
3. 0.12s 109 Mb
FYI, @andralex @atilaneves.
> Switch to faster version of staticMap

- CODEOWNERS
GitHub says "This CODEOWNERS file contains errors". I changed ZombineDev -> PetarKirov and klickverbot -> dnadlinger. I don't know what to do about code owners that don't have writing permissions to Phobos.
> Update GitHub usernames in CODEOWNERS

- std/algorithm/iteration.d
Needed for https://github.com/dlang/dmd/pull/14367 to eliminate escaping uplevel references.
> iteration: use static class

- std/container/rbtree.d
In service of getting https://github.com/dlang/dmd/pull/14367 to compile.
The trouble boils down to:
```
final class RedBlackTree(alias less)
{
this() { }
}
auto redBlackTree(alias less)()
{
return new RedBlackTree!(less)();
}
@safe void test()
{
auto rbt2 = redBlackTree!((a, b) => a < b)();
}
```
where the lambda initializing rbt2 is inferred to be a delegate, with a reference to the stack frame of test(). This causes the return statement to fail as the RedBlackTree is presumed to save a copy of the `less` delegate, referencing that frame.
I'd file an enhancement request on this, but bugzilla is down for the moment.
> rbtree lambda references stack frame

- std/path.d
dlang/dmd#14383 deprecates throwing from contracts of `nothrow` functions. This change removes such cases from Phobos.
> std.path.globMatch: Don't throw from nothrow contract

- std/socket.d
In the service of making class destructors `scope`. See:
https://github.com/dlang/dmd/pull/14402
> std.socket: add scope to close

- std/logger/core.d
@WalterBright maybe this helps. From the errors I saw, there is a race somewhere on 32 bit.
> std.logger 32 bit unittest race condition fix

- std/logger/core.d
At this point I'm quite sure that the sporadic unittest errors happen because the created Thread is still active after the unittest is finish. The log message is written after the test is done.
This PR makes the test join the thread.
> std.logger.core unittest forgotton thread.join

- std/sumtype.d
According to earlier versions of the language spec, checking the
invariant of a struct would also cause its fields' invariants to be
checked, recursively. SumType's invariant was added to make SumType
behave consistently with other structs in this regard.
The spec, however, was wrong: invariants of struct fields are not
checked unless the field is accessed directly, and never have been.
Thus, to make SumType behave consistently with other structs, its
invariant must be removed.
This change should not break any valid programs, since code that relies
on the failure of an invariant has undefined behavior per the spec.
Spec correction PR: https://github.com/dlang/dlang.org/pull/3405
> Remove SumType's invariant

- std/container/dlist.d
Unless I'm missing something this looked like an easy win to me.
Haven't done the full test-suite yet, and I am super out of date with what the newest dev/testing methodology is. Let me know if I've missed anything~
> Fix issue 23333: Make DList range access @nogc

- std/path.d
Respect other valid errno codes that mean the name or uid given was not found on the system, instead of incorrectly raising an OOM error.
> fix Issue 23340 - std.path: expandTilde erroneously raises onOutOfMemory on failed getpwam_r()

- std/stdio.d
While the proper fix would be to define the missing getc/putc macros, for now to keep the build happy, just treat uClibc as a GENERIC_IO platform.
From comment here https://github.com/compiler-explorer/compiler-explorer/issues/3973#issuecomment-1250074395, and tested using the given crosstools-ng scripts.
> partial fix for Issue 23344 - std.stdio: error: undefined identifier fputc_unlocked

- std/concurrency.d
Previously, a TOCTOU bug in threadInfo could result in a null dereference if 'scheduler' was changed to null between the evaluation of the 'if' condition and the call to scheduler.threadInfo.
> Fix Issue 23350 - Nondeterministic test failure in std.concurrency

- std/algorithm/sorting.d
`@system` in that position applies to the variable on the next line, not the function.
Blocking / uncovered by https://github.com/dlang/dmd/pull/14478
> Fix `@system` annotation in multisort unittest

- std/experimental/allocator/building_blocks/affix_allocator.d
- std/experimental/allocator/building_blocks/aligned_block_list.d
- std/experimental/allocator/building_blocks/allocator_list.d
- std/experimental/allocator/building_blocks/fallback_allocator.d
- std/experimental/allocator/building_blocks/free_list.d
- std/experimental/allocator/building_blocks/free_tree.d
- std/experimental/allocator/building_blocks/quantizer.d
- std/experimental/allocator/building_blocks/region.d
- std/experimental/allocator/building_blocks/scoped_allocator.d
- std/experimental/allocator/building_blocks/segregator.d
- std/experimental/allocator/building_blocks/stats_collector.d
- std/experimental/allocator/package.d
This PR addresses [issue 23090][1] for `std.experimental.allocator.building_blocks.region` by splitting the functionality previously accessed using `NullAllocator` out into two new allocators, `BorrowedRegion` and `SharedBorrowedRegion`. The original `Region` and `SharedRegion` are now assumed to always own the memory they allocate from, and will always (attempt to) deallocate it in their destructor.
To avoid code duplication, `Region` and `SharedRegion` have been refactored to use `BorrowedRegion` and `SharedBorrowedRegion` internally.
cc @atilaneves 
[1]: https://issues.dlang.org/show_bug.cgi?id=23090
---
Buildkite is green so hopefully this won't be too disruptive.
> [allocator/region] Issue 23090 - Don't use NullAllocator as a sentinel type

- std/path.d
This improves the somewhat hacky implementation of #8547 ~~and, more generally, makes `std.algorithm.searching.balancedParens` `nothrow` when both the range's element type and `E` are either `char`, `wchar`, or `dchar`~~.
> improve precondition of std.path.globMatch

- std/base64.d
Unfortunately the issue's claim that "The decoding functions in std.base64 would be automatically marked as @nogc" is not true because they throw exceptions for invalid characters in the string.
> Fix 23370 - std.base64 can have more @nogc functions

- std/net/curl.d
This is now possible now the site now has a new front for its bucket.
> Update downloads.dlang.org links to use https

- std/format/internal/write.d
No behavioral change, but simplifies the code.
---
See discussion in #8593 for additional context.
> Use __traits(identifier) to format enum member

- std/uni/package.d
The codegen is literally the same.
I could have delegated to std/ascii, and in fact, I do think this would be the right thing to do int he absence of DMD's inliner being what it is.
> Simplify std.uni.isAlpha

- std/ascii.d
Using recent version of LDC, here are the codegen I get:
```
lea     eax, [rdi - 48]
cmp     eax, 74
ja      .LBB2_1
lea     ecx, [rdi - 97]
mov     al, 1
cmp     ecx, -39
jb      .LBB2_4
add     edi, -65
cmp     edi, 26
setb    al
.LBB2_4:
ret
.LBB2_1:
xor     eax, eax
ret
```
And now:
```
lea     eax, [rdi - 48]
cmp     eax, 9
setb    cl
or      edi, 32
add     edi, -97
cmp     edi, 26
setb    al
or      al, cl
ret
```
Which is much better all around: less instructions, no branches, etc...
I will note that doing `isDigit(c) || isAlpha(c)` also gives me good codegen using LDC, but I chose against it as DMD fails to inline properly and the end result is pretty bad.
> Improve isAlphaNum

- std/ascii.d
Before:
```
lea     eax, [rdi - 48]
cmp     eax, 54
ja      .LBB0_1
lea     ecx, [rdi - 97]
mov     al, 1
cmp     ecx, -39
jb      .LBB0_4
add     edi, -65
cmp     edi, 6
setb    al
.LBB0_4:
ret
.LBB0_1:
xor     eax, eax
ret
```
After:
```
lea     eax, [rdi - 48]
cmp     eax, 10
setb    cl
or      edi, 32
add     edi, -97
cmp     edi, 6
setb    al
or      al, cl
ret
```
> Optimize isHexDigit

- std/typecons.d
Those fixes were done in PR #8509 but PR #8368 accidentally reverted them.
> Re-instate accidentally reverted fixes on RefCounted

- .cirrus.yml
This was done in DMD (https://github.com/dlang/dmd/commit/c63a8be0aa0781a59df63a98f56aa09f0fec4645) but not here, and the CI is currently broken on 11.
> Cirrus: Bump FreeBSD from v11/12 to v12/13

- .circleci/config.yml
The circle/ images were [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) in 2021, and no longer receive updates.  As seen by a couple repositories [beginning to fail](https://circleci.com/gh/dlang/dlang.org/4716) due to outdated curl/ca certificates.
> circleci: Migrate to circleci convenience images

- std/algorithm/mutation.d
- std/array.d
- std/bitmanip.d
- std/digest/murmurhash.d
- std/json.d
- std/random.d
- std/string.d
Found using https://github.com/dlang/dmd/pull/14527.
> Fix missing unittests in docs

- std/exception.d
That would break `dlang.org/tools/dspec_tester.d` test extraction. Currently that script only works for `spec/*.dd`, but I'm working on support for Phobos `RUNNABLE_EXAMPLE` too. 
Remove empty last line.
No other changes.
> [trivial] Remove leading '*' from assumeUnique examples

- std/exception.d
These get wrapped in `void main {...}` by both `dspec_tester.d` and `run_examples.js`. Workaround this.
Note: I'm working on extracting tests for Phobos RUNNABLE_EXAMPLE, but currently these are not tested. This is the 2nd and last change needed for that to work.
> [trivial] Fix assumeUnique RUNNABLE_EXAMPLE tests

- std/format/package.d
Resolve a `then`/`than` error and focus on what the flag does instead of on the default behaviour when the flag is absent. This way the descriptions for the `-` and `=` flags are more in line.
> Clarify the format flags documentation.

- etc/c/zlib/osx.mak
- posix.mak
This fixes `make -j4 -C ../phobos -f posix.mak` on Apple OSX with an ARM cpu.
Related DMD PR: https://github.com/dlang/dmd/pull/14586
> Force makefile to x86 on Apple ARM cpu (dmd does not support ARM)

- std/experimental/allocator/building_blocks/package.d
- std/experimental/allocator/package.d
Add missing LREFs in top table.
Use RUNNABLE_EXAMPLE for synopsis.
> Improve std.experimental.allocator docs

- std/format/internal/write.d
Follow-up to https://github.com/dlang/phobos/pull/8593.
> Avoid two calls to put in enum overload of formatValueImpl

- std/array.d
@schveiguy explained there is a thread-local cache that avoids a global lock once the cache is filled.
See https://github.com/dlang/dlang.org/pull/3445#discussion_r1002773401. 
Add link to spec (instead of capacity LREF which already exists just above Appender).
> [std/array] Fix wrong Appender docs 'global locking for each append'

- std/format/internal/write.d
Also see https://github.com/dlang/phobos/pull/8591.
> Avoid use of EnumMembers in enum specialization of formatValueImpl

- std/typecons.d
I am currently working on improving D-Scanner and currently it does not catch this "redundant attributes" situation for this particular file, hence my version of D-Scanner applied to phobos will fail because of this. (even if the warning is valid)
Concretely, the `private` access modifiers that I deleted are not necessary, because all these declarations are inside a private scope (that starts on line 5467)
https://github.com/dlang/phobos/blob/master/std/typecons.d#L5467
> remove redundant attributes in typecons.d

- std/checkedint.d
- std/datetime/systime.d
- std/digest/hmac.d
- std/format/internal/write.d
- std/socket.d
- std/sumtype.d
- std/uni/package.d
I am currently working on improving D-Scanner and currently it does not catch this "same name variable" situation for the changed files, hence my version of D-Scanner applied to phobos will fail because of this. (even if the warning is valid)
Concretely, current D-Scanner won't throws a warning for situations like this:
```
int a;
// ...
void foo() { auto a = 3; }
```
This was just an example but from what I can tell it won't throw the warning for any `auto` declarations (even when that's the case)
> same name fix

- std/bitmanip.d
The documentation for flip(size_t) indicates that the variable name is `pos`, but the parameter is named `i`.  This PR changes the parameter name to `pos` to match the documentation.
> Update parameter name to match documentation

- std/internal/windows/advapi32.d
- std/stdio.d
- std/typecons.d
Dub uses `-preview=in` to compile in its `build.d` script, but not in the `dub.sdl` (because Vibe.d wasn't DIP1000 compatible).
DMD v2.101.0 introduced a change that means `-preview=in` now disallows `in` on non-`extern(D)` / `extern(C++)` functions.
But since the fixes were done 3 days after the start of the v2.101 release, the dub CI is currently broken with latest.
> [stable] Cherry-pick changes from master that are needed for `dub` to compile

- std/socket.d
This is remarkable to me - git blame says this was there in the initial commit to git in 2007, meaning it goes back to prehistory (though I could probably download some ancient phobos and check there, but i suspect it has been there the whole time), but I'm almost certain this is wrong.
Windows sockets are blocking by default. The Phobos docs, the constructor for Socket, states that it "creates a blocking socket". The behavior is blocking. But this property defaults to false.... and a new commit to my code happened to use it, assuming it had correct info, causing a regression for me!
But, as far as I can tell, this should have been true by default the whole time.
> fixes #23507 sockets are blocking by default, this needs to reflect that

- std/traits.d
This was discovered in https://github.com/dlang/dmd/pull/14554.
`hasUDA` uses `getUDAs` underneath which in turn uses `traits(getAttributes)`. Up until dmd PR 14554 `getUDAs` would happily accept an overload set and because of the bug in `__traits(getAttributes)` it would just check the first lexicographically overload encountered.
`getSymbolsByUDA` which uses `hasUDA` internally would first check if `hasUDA` is callalble on the members of the passed aggregate by using `__traits(compiles, hasUDA!member)`. This was done to prevent calling `traits(getAttributes)` on types or alias sequences, however, with the new deprecation from dmd PR 14554 and since phobos compiles with -de the `__traits(compiles)` check now fails for functions that have overloads, thus breaking `getSymbolsByUDA`.
The …
> Fix getSymbolsByUDA by replacing broad __traits(compiles) with a more narrow condition

- std/traits.d
I have no idea why the isScalar check is there. Let's see if removing it breaks anything. The is checked should be sufficient.
> remove isScalar check from std.traits.isPointer

- std/utf.d
as it is unnecessary. It also removes the need for the `typeof`.
> remove isPointer use in std.utf

- std/parallelism.d
Targeting stable because it's a pretty embarrassing bug and was just encountered at work, in a VM with a single CPU core.
> [stable] Fix Issue 22745 - std.parallelism.parallel fails to process empty range on a single CPU

- std/math/hardware.d
1. The `pragma(inline, false)` doesn't do what the author thinks it does (Issue 23520).
2. Change that introduced `blockopt` seems to have a slight misunderstanding about what constant propagation is (`a /= 0.0L` can always be constant propagated regardless of what surrounds it).
3. Undocument tests that depend on the need for forcing operations to disarm the optimizer, and replace with simple tests behind `StdDdoc`.
> std.math.hardware: Fix broken IEEE FP flags tests

- std/math/hardware.d
This unittest was default disabled in GDC, using the non-inlinable forceOp functions allows it to be enabled again.
> std.math.hardware: Use forceOp in another ieeeFlags test

- std/stdio.d
Make `readlnImpl` `@trusted`.
Make `File.readln` overloads `@safe`.
> Make std.stdio.File.readln @safe

- std/algorithm/iteration.d
See: https://forum.dlang.org/post/tmtgli$17v$1@digitalmars.com
> Clarify that .uniq by default expects a sorted range.

- std/random.d
According to issue 15147, uniform() will return a different values on 64-bit vs. 32-bit pointer targets when passed a size_t.
The x32 ABI is a 32-bit pointer target on x86_64, so all these tests currently fail.  Change the condition to only run the test on 64-bit _pointer_ targets.
> std.random: Fix unittests on x32 ABI targets

- changelog/log_float_double_implementations.dd
- std/math/exponential.d
- std/math/operations.d
- std/numeric.d
- std/parallelism.d
Software implementations are unchanged - only conditionally compiling in the `log(x) = z + z^^3 R(z) / S(z)` branch depending on the float format (as can be seen when reviewing with [`w=1`](https://github.com/dlang/phobos/pull/8499/files?w=1)). 
Coefficients are taken from Cephes single and cmath libraries.
FYI @kinke.
> std.math.exponential: Implement log/log2/log10 for double- and float-precision

- changelog/unicode_properties_c.dd
- std/uni/package.d
This is a bit of unfortunate breakage, but it is what it is.
It shouldn't come up again and doesn't need a test as it should never have diverged from the standard like this.
There is a mitigation code in the changelog & I'll do an announcement to give people time to mitigate this and the tables being updated.
> Fix issue 23540 - std.uni loadProperty aliases for C are incorrect

- std/conv.d
- std/typecons.d
1. Remove workaround for fixed compiler bug.
2. Remove unnecessary `static` attribute for struct (nested struct works and the example doesn't appear to be nested in the docs).
3. Remove unnecessary `@trusted` for dtor.
> [trivial] Tweak a few tests

- .cirrus.yml
We seem to have missed the memo saying that the Intel-based runners will be removed from 1st Jan 2023, no idea if we are even ready to run on M1 hosts?
https://cirrus-ci.org/blog/2022/11/08/sunsetting-intel-macos-instances/
> ci: Update cirrus macOS image to macos-monterey-xcode

- std/file.d
Part of Issue 12391.
Add example showing how to handle subdirectory read permission failures.
> Document dirEntries throws without read permission

- std/typecons.d
~~Technically a breaking change: `nullable[]` no longer allows ref access. But that functionality was always weird.~~
~~Code sample broken by this PR: `Nullable!int n = Nullable!int(3); n[][0] = 5;` Who does that?~~
edit: Hang on, that never worked. All good!
The `opIndexImpl` hack is because `inout` doesn't work for a field of a struct (`NullableRange.value`), and `empty_` must remain mutable (that's the whole point) so we can't return `inout(NullableRange)`, but `opIndex` can't be a template (`(this This)`) because then DMD doesn't notice it as the right overload for `nullable[]`.
edit: Changing the overload from `opIndex` to `opSlice` removes the need for the const overload hack.
> Fix issue 23640: Use `Nullable[]` to allow iterating `Nullable` of immutable type.

- std/array.d
- std/exception.d
- std/format/internal/write.d
- std/traits.d
Alias this for classes is getting deprecated: https://github.com/dlang/dmd/pull/14812 .
It's a good sign that we are not using it in client code, just in tests.
> Remove alias this from classes in phobos

- std/algorithm/package.d
Fixed Issue 20397 - missing nthPermutation link in std.algorithm documentation page
> Fix Issue 20397

- std/container/binaryheap.d
Fix issue 18333: binaryHeap documentation inadequately describes slice store invalidation
https://issues.dlang.org/show_bug.cgi?id=18333
> Better document the use of Heaps with Dynamic Array as Store

- std/range/primitives.d
ReturnType is quite a big template for what it is accomplishing here. In my tests (see my post here: https://www.schveiguy.com/blog/2023/01/the-cost-of-compile-time-in-d/), I measured about 56k RAM savings, and if enough ranges are used, about 64microseconds per instantiation.
Note that there is no worry about losing the benefit of caching here -- isInputRange!T is calculated once per T, so the instantiation of ReturnType for the internal lambda will never be used again.
Not sure if there is a way to measure this using CI. But the code itself isn't really that much more complex.
> Slim down the range constraints a bit

- std/process.d
POSIX follow-up to Issue 13447 / 09a0b876c87cec6bb7af62b55179aff745b203dc.
> Fix Issue 23706 - Do not escape POSIX shell parameters unless necessary

- std/net/curl.d
Fixes issue 23724 - HTTP.onReceive example does not compile
> std.net.curl: add missing import to examples

- std/array.d
- std/exception.d
- std/getopt.d
- std/traits.d
- std/utf.d
The behaviors are different and the changes appears accidental rather than deliberate. In at least one case the change would result in wrong behavior: https://github.com/dlang/phobos/pull/8635#issuecomment-1433898162
Affected PRs: #8635, #8636, #8637, #8638, #8639
> Fix recent isPointer changes to use is(T == U*, U) instead of is(T : U*, U)

- std/algorithm/sorting.d
Typo specifically introduced in:
- baaa1117dec05d9547c319726fbd195910cc1b52
> algorithm/sorting: Fix typo introduced in PR #8678

- std/process.d
In the forked process, the array "pfds" is allocated and never free'd. That's a problem if you're going to spawn and keep running a lot of processes, since it's a quite big array.
> Memory leak on std.process

- std/process.d
Reverts dlang/phobos#8695
A forked process does not affect the original process's memory usage. And the process image is either going to be replaced with a new one via exec, or exec is going to fail and the process is going to exit.
There is no need to clean up the fds, it's just wasting cycles.
> Revert "Memory leak on std.process"

- std/regex/internal/parser.d
I don't know how much we can actually do to speed it up, but this is at least still a win at about ~100ms. That shouldn't change anything other than build times.
Tracking issue (does not close): https://issues.dlang.org/show_bug.cgi?id=23737
> Improve std.regex build times by removing a formattedWrite call

- std/format/internal/write.d
This is a minor internal change, but will allow us to deprecate in ref at the parser level.
> Change how preview=in is detected

- std/math/exponential.d
FYI @jmh530.
I gathered that because the implementations are otherwise identical, just smash together `log` and `log1p` into `logImpl`.
> fix Issue 23750 - log1p for floats/doubles not actually providing extra accuracy

- std/math/exponential.d
After some probing, looks like Apple M1 emulation of x86 instructions is bugged.  Nothing we can do besides opening a ticket with Apple, so disabling use fyl2xp1 intrinsics on the target.
> std.math.exponential: Disable use of fyl2x and fyl2xp1 intrinsics on dmd/macOS port

- std/traits.d
I thought I was done with Phobos, but it strikes yet again.
> Fix a printf prototype in std.traits test

- std/traits.d
**Note: Originally this recommended using __traits instead, now it just says see also.**
---
That will reduce template instantiation overhead.
Note that some __traits accept type instances in addition to just types.
~~I've left `isNested` as that only applies to types not functions - ideally it would be named `isNestedType` to avoid confusion with `__traits(isNested)`.~~
@schveiguy
> [std.traits] Add 'See also: __traits'

- std/json.d
Following this thread on the forums: https://forum.dlang.org/thread/okawuksiklgephzlhkeq@forum.dlang.org
I also discovered that it's a bit unwieldy to make an empty object, and usually I just resort to the following:
```d
JSONValue j = JSONValue(string[string].init);
```
But this is not very clear for beginners and is also a bit of a mouthful. I propose with this PR to change it to this:
```d
JSONValue j = JSONValue.emptyObject();
```
In addition, I have added an equivalent function to initialize an empty array node:
```d
JSONValue j = JSONValue.emptyArray();
```
> Add emptyObject() and emptyArray() functions to std/json

- std/math/exponential.d
And add a few more simple tests.
> std.math.exponential: Fix wrong placement of 1.0 in log1p coefficient

- std/container/dlist.d
- std/range/package.d
- std/range/primitives.d
also fixes isBidirectionalRange not allowing `@disable this(this)` items (which isInputRange allows)
<details>
<summary>German Train rant</summary>
I couldn't test entire phobos locally yet, because I couldn't get the newest dmd commit to build, because the internet in German trains is about 4 kb/s, with the connection constantly dropping and me needing to pull 1 MB of changes first.
</details>
>  fix 22147: allow @disable this(this) T in DList!T 

- std/random.d
Unblocks: https://github.com/dlang/dmd/pull/14986
Even if https://github.com/dlang/dmd/pull/14986 does not go through, this still makes the code cleaner.
> Fix std.random to not use this in static contexts

- std/file.d
I've seen many times that people are confused about how to read a text or binary file. This should avoid the need for asking about this on the forums.
> Add doc hints between read and readText

- std/range/package.d
On each `empty`, `popFront`, or similar call, `chain` iterates over the same empty ranges again and again, which seems wasteful for me. This PR changes that. The index of first and last non-empty ranges are now cached in the range instead.
I benchmarked the resulting chain against that coming with version 2.100.1:
```D
@safe void main()
{   import std;
auto testData = uninitializedArray!(long[])(600_000);
foreach(ref el; testData) el = uniform(0, 10);
long total = 0;
StopWatch sw;
sw.start();
foreach(i; 0 .. testData.length / 120) total |= chain
(   testData.drop(i*120).take(60),
testData.drop(i*120 + 60).take(60)
).fold!"a+b"(1L);
sw.stop();
writeln("time: ", sw.peek);
writeln("result: ", total);
}
```
On my computer, the new version wins at factor 5 : 6. …
> Optimised std.range.chain

- changelog/rebindable_all_types.dd
- std/typecons.d
Implement `Rebindable!T` where `T` is any type, including const and immutable.
Arrays, objects and interfaces are still handled by the old `Rebindable` implementation.
Note that you cannot access a reference to the contained value in `Rebindable`. This is unavoidable; otherwise you could violate constness. For this and related information, see my 2022 DConf talk https://www.youtube.com/watch?v=eGX_fxlig8I 
As opposed to the previous PR, this implementation deliberately contains the least amount of code to do something useful. As per review feedback, this PR is a simplified version of #8674 , which was a rewrite of #6136, which was itself a revival of #4363. This time for sure!
> Feature: Implement Rebindable for non-class/non-array types.

- std/algorithm/iteration.d
This allows use with `immutable T[][]` and similar.
I don't think this is a complete answer to `immutable` and `joiner`, but it solves the testcases I had on hand. When I find another, I'll file another bug.
> Fix issue 22785: `joiner` should `Unqual` child ranges.

- std/algorithm/searching.d
- std/typecons.d
Supersedes https://github.com/dlang/phobos/pull/8669
Making `Rebindable` alias to `T` for arrays was a sorry mistake. (See #8735)
> Fix issue 22786 (immutable element in maxElement) by always using Rebindable.

- std/traits.d
When I have to read the implementation to figure out what the documentation means, it needs improvement.
> clarify documentation for std.traits.isIntegral

- std/range/package.d
Apply the suggested change from https://issues.dlang.org/show_bug.cgi?id=19642
> Fix issue 16942: slide!(No.withPartial): Correctly handle first slide exhausting input range.

- std/range/package.d
same as #8714
code not fully covered
> fix 14478: support non-copyable elements in many range algorithms

- std/conv.d
Eliminates a layer of function calls.
Blocked by https://github.com/dlang/dmd/pull/15198
> std.conv handle default integer-to-string with core.internal.string

- changelog/std_system_instruction_set_architecture.dd
- std/system.d
I tried to keep things aligned with the [Predefined Versions](https://dlang.org/spec/version.html#predefined-versions), so hopefully there's nothing surprising here. This does not cover ABIs, which would be somewhat more complicated to support.
> fix issue 23881: add std.system.instructionSetArchitecture and std.system.ISA

- std/range/package.d
Fixes issue 23844.
`only` is a range that may be *mutable*, but not *assignable*. `chain` falls over here because it assumes it can make a struct with ranges, and reassign them with new values, which isn't necessarily the case even if the ranges are not `const`. Solved by creating a separate tuple of `Rebindable` ranges for this case.
> Fix issue 23844: Support ranges with immutable fields (like `only` with `immutable struct`) in `chain`.

- std/path.d
When using `expandTilde` with 'priview=in' enabled, it requires to duplicate value to be able to call this function. Within this commit the signature of expandTilde function is changed from `string expandTilde(string inputPath) @safe nothrow` to `string expandTilde(return scope const string inputPath) @safe nothrow` thus, after this commit it is possible to use this func in scope context.
Also, in this PR tests for `expandTilde` become safe.
Example case:
```d
/+ dub.sdl:
name "dub-example"
dflags "-preview=in" "-preview=dip1000"
+/
import std.path;
@safe:
string fun(in string path) {
return path.expandTilde;
}
void main() {
string p = fun("~/tests/1");
writefln("P: %s", p);
}
```
---
PS: Not sure if it is good enough to target this on stable branch, but it seems that …
> std.path.expandTilde: make compatible with scope and preview='in'

- std/typecons.d
The access through `p` to `rc1` outside the scope of `rc1` is undefined behavior. We have to artificially end the scope of `rc1` ~~and `rc2`~~, such that within the same scope we can check that the destructor calls do the correct thing of nulling the `_store`.
@dkorpel 
Related work on LDC: https://github.com/ldc-developers/ldc/pull/4395#issuecomment-1548389374
> typecons: fix use-after-scope bug in RefCounted unittest

- std/path.d
When using `absolutePath` with 'priview=in' enabled, it requires to duplicate value to be able to call this function. Within this commit the signature of `absolutePath` function is changed from `string absolutePath(string path, lazy string base = getcwd())` to `string absolutePath(return scope const string path, lazy string base = getcwd())` thus, after this commit it is possible to use this func in scope context.
Example case:
```d
/+ dub.sdl:
name "dub-example"
dflags "-preview=in" "-preview=dip1000"
+/
import std.path;
@safe:
string fun(in string path) {
return path.absolutePath;
}
void main() {
string p = fun("~/tests/1");
writefln("P: %s", p);
}
```
> std.path.absolutePath: make compatible with scope and preview='in'

- std/regex/internal/ir.d
This will improve std.regex build times by about ~500ms if used. It delays initialization of the wordMatcher tables till runtime if possible. This should mean it won't work at CTFE, but we'll see if we need to fix that later (it can be cached where it's used and computed each time).
Tracking issue (does not close): https://issues.dlang.org/show_bug.cgi?id=23737
> Improve std.regex wordMatcher build times by delaying its work from CT to RT if possible

- std/algorithm/searching.d
- std/range/package.d
- std/typecons.d
`Rebindable2` is a simplified version of `std.typecons.Rebindable` that cleans up every special case: classes, arrays and structs now have the same `struct Rebindable2`.
Whichever type you instantiate `Rebindable2` with, you always get the same type out by calling `value.get` on the resulting container.
Also use this type to simplify the parts of Phobos I previously used `Rebindable` for.
This PR is the announced follow-up to https://github.com/dlang/phobos/pull/8735
> Add std.typecons.Rebindable2 for internal use.

- std/stdio.d
I am not very happy with this, because stdio.d is such a confusing mess. However, the error return from __setmode() is not checked for, which is clearly wrong.
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-170
> fix Issue 23312 - Crash when calling writeln in WinMain

- std/range/package.d
I think possibly `hasShownPartialBefore` is just simply wrongly named in the `withPartial` branch.
> Fix issue 23976: std.range.slide fails in dmd-2.104.0

- std/traits.d
Don't rely on result `.stringof`, which also failed to check each overload of `a` was present.
This is also necessary for https://github.com/dlang/dmd/pull/15363.
> [std/traits] Improve getSymbolsByUDA test

- std/algorithm/searching.d
This looks ugly, but it's just for the `stable` branch - this is fixed on `master` via the `Rebindable2` rewrite https://github.com/dlang/phobos/pull/8768
> Fix issue 24027: Instead of a bunch of special-cases, just check that `Rebindable` did in fact alias itself away.

- std/json.d
Production experience as well as synthetic tests have shown that std.json's use of associative arrays combined with GC issues causes heavy heap fragmentation. Furthermore, its heavy GC usage makes it unperformant in a threaded environment. Despite this, people keep using std.json for production workloads, then being disappointed when it doesn't measure up. So let's warn them upfront.
> Add warning to std.json that it doesn't play well with the GC.

- std/format/internal/write.d
Trying to unblock https://github.com/dlang/dmd/pull/14827 by removing Phobos' reliance on overlapped pointer access in `@safe` code.
- Don't read `val.tupleof[i]` unless we actually want to format the value
- Access `T.tupleof` instead of `val.tupleof` when we can
- Remove the `val.tupleof[i].stringof[4 .. $]` hack (the first 4 characters are "val.") and use `__traits(identifier)` instead
- Make `U2.toString` which reads an overlapped pointer `@trusted`, otherwise the unittest can't be `@safe`
> Fix unsafe union access in std.format

- std/traits.d
Use alias assignment instead.
Also use `return scope` instead of `@trusted` workaround for `ParameterDefaults`.
> [std/traits] Avoid template recursion for 3 ParameterSeq traits

- std/conv.d
~~**Depends on https://github.com/dlang/dlang.org/pull/3670**~~
Fix formatting of `Integer` grammar.
Minor tweaks.
Use the [new PANEL macro](https://github.com/dlang/dlang.org/pull/3670) to introduce the `parse` overloads (under the first overload). 
Improve `parse` overload descriptions.
Reorder `parse` constraint expressions to follow parameter order. In particular, `Target` expressions should come first.
> [std.conv] Tweak to, parse docs

- std/regex/internal/ir.d
- std/uni/package.d
Similar to https://github.com/dlang/phobos/pull/8786, trying to unblock [dlang/dmd#14827](https://github.com/dlang/dmd/pull/14827) by removing Phobos' reliance on overlapped pointer access in `@safe` code.
> Fix unsafe union access in std.regex and std.uni

- std/range/package.d
`source` is `Unqual!Ranges`, not `Ranges`.
> Fix issue 24064: use consistent types for ResultRanges.

- std/array.d
It's much easier to follow with the array overload docs separate from the range overloads. 
Tweak wording.
> [std/array] Split staticArray docs into two groups

- std/exception.d
> [std/exception] Tweak docs

- std/int128.d
`toString` has template parameter `FormatSpec` instead of template parameter `Char` and argument `std.format.FormatSpec!Char` so importing `std.int128` does not require importing `std.format` unless `toString` is actually used (pay as you go).
On the other hand most other places in Phobos import `std.format` in the enclosing scope and use the signature `toString(Writer, Char)(scope ref Writer, scope const ref std.format.FormatSpec!Char)` instead. Reviewers let me know if you prefer to keep it consistent.
> Fix Issue 24082 - add Int128.toString that supports std.format

- std/int128.d
Needed to make opCmp a template to avoid causing `Int128(-1L) < ulong.max` to return the wrong value or causing the compiler to complain that it can't determine which overload to call for `Int128(1) > 10`.
> Fix Issue 24083 - Int128.opCmp's behavior with negative numbers is inconsistent with Int128.opEquals

- std/stdio.d
Untangling the soup of versions here.
> std.stdio: untangle fdopen references

- std/stdio.d
> std.stdio: remove redundant version declarations

- std/string.d
It was written in the docs, but I think the example shows it more clearly and doesn't require the user to test it if in doubt anymore.
> show that chomp doesn't remove spaces in example

- std/range/primitives.d
Moves the declaration into a CTFE-only context so that nothing gets emitted at codegen
> Adjust conditions in putChar to avoid declaring static symbol

- std/parallelism.d
No valid code should be using these members, they are thread-unsafe.
Note, this appears to have been changed to public to workaround some compiler issue, but the PR doesn't seem to be real: https://github.com/dlang/phobos/commit/9d151ac1f9e45d4d57a0b74508b41b303a6a293d
> make std.parallelism.AbstractTask inaccessible

- .github/workflows/main.yml
This reverts commit 4f6de8489409849f04448e33ace1f527aa0dad68, as DMD master has been fixed (https://github.com/dlang/dmd/pull/15745).
> Revert "GHA: Work around a `$p:`bug in DMD's d_do_test.d"

- changelog/unshared.dd
- std/traits.d
This is the shared equivalent of Unconst. It allows code to strip off shared without stripping off const.
> Add Unshared to std.traits.

- changelog/is_forward_range_element.dd
- std/range/primitives.d
> Add optional element type to isForwardRange

- std/logger/package.d
Error was missing from the documentation here.
> Add missing log function

- std/logger/package.d
Fixes the typo made in https://github.com/dlang/phobos/pull/8846.
> docs(std.logger.package): Fix ddoc macro typo in "Basic Logging" section

- std/algorithm/searching.d
Improve wording.
Fix wrong `LREF`.
Don't repeat same array literal in example.
Don't use `== true`.
Use meaningful lambda parameter names.
Fix typo.
Also fix wrong `REF` to `among`.
> [std.algorithm] Improve `canFind` docs

- std/algorithm/searching.d
It's much clearer to have separate docs for the overload not taking `needle`, because its `pred` has a different signature and its behaviour is simpler. It was necessary to move that overload (including unittests) from between the other two. No changes were made to the overload body, or unittests except the `bool pred(` line which was tweaked.
Also improve the docs for the `needle` overloads:
Remove duplicate BIGOH sentence already present under *Complexity*. 
Fix wrong `input` name.
Move `"a != b"` predicate tip to a note so it stands out more.
Use `e, n` for predicate parameter names in examples, short for `element, needle`.
> [std.algorithm] Split `find` docs into two

- std/algorithm/iteration.d
Mention iteratively calling predicates in summary.
Use list to explain calling a single predicate with a seed. 
Mention multiple results can be produced in description. 
Use list for _see also_.
Rename `seed` parameter `seeds` and fix docs.
Fix result docs when >1 predicate.
> [std.algorithm] Improve `fold` docs

- std/conv.d
Adds newlines at the end of statements in the source code.
> Update conv.d: textImpl(): make static if more readable.

- std/algorithm/searching.d
Use list to show returned tuple elements.
Fix type of `result[1]` for After/Before.
Fix `pred` description.
Show example using custom `pred`.
> [std/algorithm/searching] Improve findSplit docs

- std/algorithm/searching.d
Partly why I'm doing this is too make adding overloads easier:
https://issues.dlang.org/show_bug.cgi?id=10933
> [std.algorithm.searching] Refactor `findSplit` result types

- std/uni/package.d
Need an issue report. Just want to make sure it passes CI
> make it so grapheme can be used as an aa key

- std/math/algebraic.d
The documentation states the return type for an argument of integral types (assuming under phobos: (u)byte,short,int,long) should equal its own type.
Under current implementation this is not the case. Exemptions are made for short and byte.
Using `isIntegral` instead yields the correct behavior, also for unsigned types (which simply return themselves).
> Update math.algebraic.d#abs to return correct integral type

- Makefile
No need to be explicit about the Makefile name.
> Makefile: Slightly simplify recursive make invocations

- std/datetime/package.d
- std/datetime/systime.d
Add links to package.d.
Tweak formatting for SysTime, use PANEL.
Use REF_SHORT after first reference.
List TimeOfDay cast target.
Move currTime link to See Also.
Fix anchor for currTime - need `.` prefix before fully-qualified names.
Extend example.
Fix typo.
Part of Issue 24288.
> [std.datetime] Tweak docs

- Makefile
- etc/c/zlib/gzwrite.c
According to earlier CI results, this works - except for a problem on Win64 only:
```
phobos64.lib(gzwrite.obj) : error LNK2019: unresolved external symbol __va_start referenced in function gzprintf
```
So looks like this `__va_start` could be a candidate for inclusion in druntime's `__builtins.di` (which already defines a `__builtin_va_start` alias).
> Makefile: Compile zlib .c files with DMD via importC

- Makefile
- etc/c/zlib/gzwrite.c
Reverts dlang/phobos#8865
Broke dmd mainline, and release builds.
```
Error: C preprocess command C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\cl.exe failed for file etc\c\zlib\compress.c, exit status 2
Error: C preprocess command C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\cl.exe failed for file etc\c\zlib\deflate.c, exit status 2
cl : Command line warning D9002 : ignoring unknown option '/Zc:preprocessor'
cl : Command line warning D9002 : ignoring unknown option '/PD'
etc\c\zlib\deflate.c: fatal error C1083: Cannot open include file: '../dmd/druntime/import\importc.h': No such file or directory
Error: C preprocess command C:\Program Files (x86)\Microsoft Visual …
```
> Revert "Makefile: Compile zlib .c files with DMD via importC"

- std/typecons.d
https://github.com/dlang/phobos/pull/6619#issuecomment-1877406035
> Fix Issue 24318 - Nullable should support non-copyable objects

- std/exception.d
This property provides an error message returned by `strerror`/`strerror_r`. See commit message for more details.
> Add errnoMsg property to ErrnoException

- Makefile
- etc/c/zlib/gzwrite.c
Reverts https://github.com/dlang/phobos/pull/8870
The regression for this was fixed by https://github.com/dlang/dmd/pull/15975
> Revert "Revert "Makefile: Compile zlib .c files with DMD via importC""

- std/bitmanip.d
Reduce semantic analysis time from ~75 ms to ~50 ms for a simple `bitfields` instantiation.
> Remove std.conv import from bitfields template

- .github/workflows/main.yml
Analogous to https://github.com/dlang/dmd/pull/15979
It keeps failing, because there's no git package anymore?
```
+ echo '::group::Install git'
+ sudo pkg install -y git
Updating FreeBSD repository catalogue...
repository FreeBSD has no meta file, using default settings
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/meta.txz: Not Found
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/packagesite.pkg: Not Found
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/packagesite.txz: Not Found
Unable to update repository FreeBSD
Error updating repositories!
```
> Remove failing FreeBSD 12 CI

- std/regex/internal/backtracking.d
- std/regex/internal/ir.d
It's meant to be a debugging tool, but gets compiled anyways. Other debugging functions use `debug(std_regex_parser)`, so add them here to. This saves ~50 ms semantic analysis time when compiling Phobos, and reduces resulting libphobos.a size by 278 Kb
> std.regex: put disassemble function in debug version

- std/format/internal/floats.d
- std/format/internal/write.d
Saves a few ms of compilation time when compiling `writeln(1.0)`. I couldn't get rid of the `std.uni` import entirely yet because `writeAligned` calls `getWidth` which calls `graphemeStride`.
> Reduce imports needed to print floats

- std/math/hardware.d
Given #8850 passed all CI pipelines, I gather dscanner has been fixed to not complain about gcc-style asm statements (or maybe it's no longer used).
> std.math.hardware: Remove mixin around RISCV implementations

- std/algorithm/searching.d
Fix Bugzilla issue 24342: Actually check that range and sentinel types match in `until` before using "sentinel as subrange" mode.
`until` does special magic when `Sentinel` consists of multiple elements of `Range`. However, because `Range` can be a range of ranges, in which case even a `Sentinel` that is a range may still only be a single element, we must confirm that the element type of `Sentinel` is actually the same as `Range` before enabling this. The `immutable ElementEncodingType` idiom is stolen from `startsWith`, which forms the basis of `until` anyways (see `predSatisfied`).
> Fix issue 24342: Actually check that range and sentinel types match

- std/range/primitives.d
The requirement for opSlice on an infinite range to return the result of take or takeExactly was removed in commit c828a08b64, which was included in Phobos 2.067.0, released in March 2015. However, the documentation was never updated to take this change into account.
This change updates the documentation and adds a unit test for the "new" behavior.
Fixes bugzilla issue 24348.
> Update docs for hasSlicing with inifnite range

- changelog/is_forward_range_element.dd
- changelog/range_predicate_element.dd
- std/range/primitives.d
Continuation of #8819 and #8842 for `isBidirectionalRange` and `isRandomAccessRange`. Also adds missing docs for `isForwardRange`.
cc @atilaneves
> Add optional element type to remaining range predicates

- std/bitmanip.d
```D
struct A
{
mixin(bitfields!(
uint, "x",    2,
int,  "y",    3,
uint, "z",    2,
bool, "flag", 1));
}
static assert(__traits(allMembers, A)[0] == "_x_y_z_flag_bf");
```
> Fix std.bitmanip.bitfields documentation

- std/range/package.d
This allows the ranges returned by only to be used in algorithms that require assignable elements, such as reverse, sort, and transposed.
Fixes bugzilla issue 24382.
> Allow assignment of std.range.only elements

- std/range/package.d
> Document range capabilities of only() result

- Makefile
zlib can't be built with importC on FreeBSD 14, because qsort_r in stdlib.h uses some asm instructions, which dmd can't handle.
https://github.com/dlang/dmd/pull/16184 fixed it so that we got a proper error message about it (and theoretically making it so that zlib could be compiled on FreeBSD 14 with gdc or ldc, though I haven't tried that), but it didn't fix it so that it could build on dmd, since that would require that dmd be able to handle GNU assembly code, which isn't a planned feature AFAIK.
https://github.com/dlang/phobos/pull/8914 fixed it so that it's possible to build Phobos without using importC by providing a make variable, but it didn't do anything for FreeBSD specifically.
This commit changes it so that FreeBSD sets that make variable in the makefile so that you don't have …
> Fix bugzilla issue 24389 - Make Phobos compile on FreeBSD 14 again.

- etc/c/zlib/ChangeLog
- etc/c/zlib/LICENSE
- etc/c/zlib/README
- etc/c/zlib/adler32.c
- etc/c/zlib/compress.c
- etc/c/zlib/crc32.c
- etc/c/zlib/deflate.c
- etc/c/zlib/deflate.h
- etc/c/zlib/doc/algorithm.txt
- etc/c/zlib/gzclose.c
- etc/c/zlib/gzguts.h
- etc/c/zlib/gzlib.c
- etc/c/zlib/gzread.c
- etc/c/zlib/gzwrite.c
- etc/c/zlib/infback.c
- etc/c/zlib/inffast.c
- etc/c/zlib/inffast.h
- etc/c/zlib/inflate.c
- etc/c/zlib/inftrees.c
- etc/c/zlib/inftrees.h
- etc/c/zlib/test/example.c
- etc/c/zlib/test/infcover.c
- etc/c/zlib/test/minigzip.c
- etc/c/zlib/trees.c
- etc/c/zlib/uncompr.c
- etc/c/zlib/zconf.h
- etc/c/zlib/zlib.3
- etc/c/zlib/zlib.h
- etc/c/zlib/zutil.c
- etc/c/zlib/zutil.h
Which should cleanly compile with C11 now, without walls of warnings with e.g. recent clang versions.
> Bump zlib to latest v1.3.1

- lib/sys/meta.d
This adds lib.sys.meta, containing just AliasSeq and Alias for now. They've been taken from std.meta more or less as-is, since they work just fine as they are.
For Phobos v3, we really need a replacement for std.traits in order for most stuff to work, so I was going to start there, adding symbols from there piece by piece, adjusting them as necessary (or skipping them if appropriate) so that we'd have at least the basic traits necessary for everything else, but it turns out that some of the meta stuff is needed as well for the unit tests and documentation of traits stuff, so I'm starting by adding lib.sys.meta as a replacement for std.meta with the two most basic items from std.meta.
So, this starts the process of building up lib.sys.meta and lib.sys.traits piece by piece.
> Add lib.sys.meta.

- lib/sys/traits.d
This starts lib.sys.traits with just Unconst, Unshared, and Unqual. Both the tests and documentation have been beefed up from what std.traits has, with many more examples provided to try to make the exact semantics crystal clear, whereas the previous explanation in the docs was pretty sparse. The actual semantics are the same though.
This isn't what I would have chosen for traits first, but they're used heavily in unit tests, so they got moved up in the list.
I used version (StdDdoc) for the ddoc version, since that's what we do normally in Phobos. I don't know if we'll want or need to change that later given than Phobos v3 technically isn't Std, but all that really matters there is that it's a specific version identifier that we use for building Phobos' documentation and which no other …
> Add the beginnings of lib.sys.traits.

- std/sumtype.d
A common cause of the "handler never matches" error is a template handler that contains a typo or other compile-time error. Since the location of the actual error is suppressed by __traits(compiles), users often do not think to look for a mistake inside the handler itself. Now, the message itself includes a hint to do so.
> sumtype: add hint to "never matches" message

- std/range/package.d
> std.range.choose: call payload postblit correctly

- std/path.d
There's a good reason why we don't do this automatically (at least on POSIX): `foo` and `foo/bar/..` may point to different things, if `foo/bar` is a symlink. This is because `..` is a hard link which "physically" goes to the parent directory in the real hierarchy.
So just note this in the docs as a potential footgun.
> [trivial] std.path: Note that absolutePath and co. do not collapse ".."

- lib/sys/traits.d
These do the same as their std.traits counterparts, but I've beefed up the documentation and examples a bit.
I'm not sure that it's worth adding SharedConstOf, SharedInoutOf, or SharedConstInoutOf as well, since that seems kind of excessive to me - though it looks like std.variant does use SharedConstOf in its tests - but in either case, I think that those can be left for a later commit if we want to keep them, since this is already adding four symbols.
> Add ConstOf, ImmutableOf, InoutOf, and SharedOf to lib.sys.traits.

- std/bitmanip.d
- std/conv.d
- std/math/algebraic.d
- std/variant.d
`cast()` removes the qualifiers from an expression's type.
> use cast() where we can

- std/algorithm/searching.d
Fix `value` missing reference.
Tweak wording.
Explain `pred` better.
Separate out needle overloads from the other 2.
Fix 'Returns' info.
Split example into 2.
> [std.algorithm.searching] Improve `count` docs

- std/socket.d
Fixes needed for https://github.com/dlang/dmd/pull/16315
With that pull, using a type qualifier cast is not `@safe` to use as an lvalue.
Workaround this with `@trusted` lambdas. This is not ideal, but the alternative of making the whole softUnittest argument `@trusted` then might fail to check the other calls are `@safe`.
> [std.socket] Cast assign to getaddrinfoPointer is not @safe

- lib/sys/meta.d
- lib/sys/traits.d
The reason for this is because Unqual currently gets used heavily when in many (most?) cases, Unconst should be used instead, because the code in question is not supposed to be operating on shared, and thus stripping off shared will either allow shared types in when they shouldn't be (e.g. with a template constraint), or in the case of a cast, it will actually strip off shared and the protections that it provides, risking concurrency bugs. But a lot of D programmers are in the habit of using Unqual rather than Unconst (probably in part because Unqual has been around longer) when they simply want to remove const, and by renaming it, we will hopefully discourage its use - or at least make programmers think about it briefly rather than unthinkingly grabbing Unqual.
Obviously, there are cases …
> Rename lib.sys.traits' Unqual to Unqualified.

- std/typecons.d
The error exhibits as:
```
std/typecons.d(984): Error: none of the overloads of template `std.algorithm.mutation.swap` are callable using argument types `!(Tuple!(ubyte, uint))(Tuple!(ubyte, uint), Tuple!(immutable(ubyte), uint))`
std/algorithm/mutation.d(2840):        Candidates are: `swap(T)(ref T lhs, ref T rhs)`
std/algorithm/mutation.d(3102):                        `swap(T)(ref T lhs, ref T rhs)`
with `T = Tuple!(ubyte, uint)`
must satisfy the following constraint:
`is(typeof(lhs.proxySwap(rhs)))`
iteration.d(69): Error: template instance `std.typecons.Tuple!(ubyte, uint).Tuple.opAssign!(Tuple!(immutable(ubyte), uint))` error instantiating
iteration.d(13):        instantiated from here: `Group!("a == b", immutable(ubyte)[])`
iteration.d(109):        instantiated from here: `group!("a …
```
> swap-and-destroy called too eagerly

- dub.sdl
- lib/package.d
- lib/sys/package.d
- phobos/sys/compiler.d
- phobos/sys/meta.d
- phobos/sys/system.d
- phobos/sys/traits.d
As discussed in a recent planning meeting, we're renaming lib to phobos, making it so that the root for Phobos v3 is phobos. So, that's what this commit does.
However, on top of that, I removed the existing package.d files (both lib/package.d and lib/sys/package.d) rather than fixing them, since I'm inclined to think that we should be very selective about when we use package.d, and I think that allowing something like import phobos; is a mistake.
It wouldn't surprise me if we get screaming about that later, and maybe we'll add it back at that point, but I'd rather not worry about maintaining it as modules get added, and if we can get away with it, I think that we should just not have it at all, since it's better practice in general to limit the symbols that you import to something close …
> Rename lib to phobos.

- std/math/hardware.d
This pull request switches `std/math/hardware.d` to use an alternative register naming for LoongArch64 so that LDC/LLVM can recognize certain fp instructions.
> std/math/hardware.d: use an alternative register naming to fix LDC compilation

- phobos/sys/meta.d
They're the same as their std.meta counterparts except that the documentation and examples have been tweaked.
> Add allSatisfy and anySatisfy to phobos.sys.meta.

- std/net/curl.d
@schveiguy Helped discover and fix the problem
> Fix Bugzilla Issue 24458 - Mac M3 associative array keys on std.net.curl gets overwritten

- std/experimental/allocator/building_blocks/kernighan_ritchie.d
This fixes a bug with strong optimization (LDC LTO).  `ubyte` arrays are not necessarily word aligned.
> Fix alignment of buffers in kernighan_ritchie unittests.

- .dscanner.ini
This appears to be the check which is making
https://github.com/dlang/phobos/pull/8924 fail the style check with warnings such as
std/internal/test/range.d(43:14)[warn]: Variable b is never modified and could have been declared const or immutable.
It makes no sense to require that unit tests follow such a rule, and it is actually detrimental when tests involve stuff like copy constructors, because then the type of the target variable matters as part of the test.
Honestly, I think that it should probably not be checked at all, since it's a pretty questionable requirement in many cases given how strict D's const and immutable are, but that's more debatable, whereas this check really makes no sense with unit tests, so I'm just disabling it for unit tests for now. We can disable it more …
> Remove dscanner check for const/immutable variables in unit tests.

- std/internal/test/range.d
- std/range/package.d
Since the compiler is treating the auto-generated copy-constructor for OnlyResult as private (thus rendering it useless outside of std.range.package), this commit adds an explicit one and makes it public. Once the dmd bug has been fixed, the explicit copy constructor should be removed.
> Work around bugzilla issue 24415 - only doesn't work with elements with a copy constructor.

- phobos/sys/traits.d
isAggregateType is the same as isAggregateType from std.traits but with tweaked documentation and examples.
isInstantiationOf is the equivalent of std.traits' isInstanceOf. The documentation and tests have been updated, and an overload for partial instantiation has been added.
The reason for the name change is that "instance" is not normally used with templates (instantiation is typically considered to be the correct term). Rather, instance is normally used to indicate that a value is an instance of a particular type. So, using isInstanceOf to check whether a type is an instantiation of a particular template seems like a misuse of the term and like it could easily cause confusion. The downside of course is that the new name is longer and harder to type, but while it's a trait that is …
> Add isAggegregateType and isInstantiationOf to phobos.sys.traits.

- phobos/sys/traits.d
FieldNames is roughly equivalent to std.traits' FieldNameTuple, and FieldTypes is roughly equivalent to std.traits' Fields (which used to be FieldTypeTuple).
The primary difference implementation-wise is that the phobos.sys.traits versions require that the types that they're given be aggregate types. For some reason, the std.traits versions accept any type and then try to give a result that at least sort of make sense when they're given a type which isn't an aggregate type (even though they really can't, because a type which isn't an aggregate type has no fields, making any choice kind of arbitrary).
For types which aren't aggregate types, Fields gives the type back in an AliasSeq, and FieldNameTuple gives AliasSeq!"". Neither makes any sense to me. I assume that it was done so that those …
> Add FieldNames, FieldSymbols, and FieldTypes to phobos.sys.traits.

- std/range/package.d
In an attempt make it so that non-copyable types worked with some of the functions in std/range/package.d, they were made to use moves instead of assignment, which broke the code for types which work with assignment but not moves (which affected the folks at Weka).
The code checked for assignment but not whether move could be used, and that didn't change when the code was changed to use move, meaning that the checks didn't match what the code was actually doing.
So, to support both the non-copyable types and the ones that can be assigned to but not moved to, this changes the code so that it uses a static if to check whether using move compiles, branching the code based on whether move works on not. If move works, it's used. If it doesn't, then assignment is used like used to be the case. …
> Fix bugzilla issue 24481: retro stopped working

- std/math/hardware.d
This PR fixes the following compile error for LoongArch:
```
std/math/hardware.d(187):1:19: error: invalid operand for instruction
movfcsr2gr $a0, $r2
```
> std/math/hardware.d: Fix compile error for LoongArch

- std/process.d
The true fix I think would b to make it so tempCString never returns null (it doesn't make a lot of sense). But the code was clearly intended to work this way, and was set up because of a long ago regression.
Even if that problem is eventually fixed, this fix is not invalidated.
> Fix issue 24549 - std.process.environment.get(null) segfaults

- std/regex/internal/ir.d
These are disallowed in `@safe` code with https://github.com/dlang/dmd/pull/16558.
> [std.regex] Fix unsafe casts to bool

- std/algorithm/searching.d
- std/typecons.d
PR fixes https://github.com/dlang/phobos/pull/8768 for classes.
`object.destroy` is, perhaps appropriately, the most destructive function ever written.
It does something useful (resetting the value and calling the destructor) for structs and struct derivatives, but something horrible (destroying the *class data*) for objects. So you're always tempted to use it, but you have to remember, every time, to disable the cases where it silently causes future crashes.
I forgot this time.
edit: `core.internal.container.common.destroy` looks like it does it right... Maybe I just switch to that? Is that safe to call from `std.typecons`?
> Fix bugzilla 24596: std.typecons.Rebindable2: Don't destroy classes! Only destroy structs!

- std/math/exponential.d
- Prevent redundant code generation for different instantiations
- Preparing to move the implementation of `^^` to `core.math`
Purely a cut and paste, only this alias and the previous imports were moved inside `_powImpl`:
```D
alias F = real;
import core.math : fabs, sqrt;
import std.math.traits : isInfinity, isNaN, signbit;
```
> Move `std.math.exponential.pow` implementation outside template

- std/bitmanip.d
- std/exception.d
- std/format/package.d
Caught with `grep -Er '\(\$[A-Za-z]'`
> fix ddoc blunders

- std/datetime/timezone.d
- std/experimental/allocator/building_blocks/region.d
- std/experimental/allocator/mmap_allocator.d
- std/json.d
- std/numeric.d
- std/stdio.d
- std/utf.d
Found with the following script
```
for link in $(grep -Eor 'https?://[^\\)", ]+' | grep -v dlang.org \
| grep -Eo 'https?://.+'); do (printf "%s: " "$link"; curl -Is "$link" \
| head -n1) | grep -E '4..$'; done
for link in $(grep -Eor '\\$\\(HTTP .+, ' | grep -v dlang.org \
| cut -d' ' -f2- | sed 's/, .*$//'); do out="$(curl -Is "$link")"; \
(! [ $? = 0 ] || printf '%s' "$out" | head -n1 | grep -Eq '4..') \
&& printf '%s\\n' "$link"; done
```
> replace dead links

- std/experimental/allocator/building_blocks/package.d
- std/experimental/allocator/building_blocks/stats_collector.d
- std/experimental/allocator/mallocator.d
Fixes Bugzilla Issue 24667 - goo.gl is going away.
Note: [www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html](http://www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html) jemalloc link isn't responding, replaced with jemalloc.net (link at end of https://github.com/jemalloc/jemalloc?tab=readme-ov-file#readme).
> Expand `goo.gl` links that may break

- std/range/package.d
The `Lockstep`/`lockstep` feature does not work with attributes. Because `Lockstep` uses `enforce`, it’s never `@nogc` or `nothrow`, but it should work with `@safe` and `pure`, and now it does.
> Fix Lockstep attribute limitation

- std/logger/core.d
- std/logger/filelogger.d
- std/logger/package.d
Without the cast recent compilers complain with
```
Error: none of the overloads of `sharedLog` are callable using argument types `(FileLogger)`
Candidates are: `std.logger.core.sharedLog()`
`std.logger.core.sharedLog(shared(Logger) logger)`
```
> Fix sharedLog assignment.

- std/stdio.d
> Removes DEPRECATED_2.107 code from std.stdio

- std/datetime/date.d
Fixes https://issues.dlang.org/show_bug.cgi?id=18552
> Fix bugzilla 18552: Adds check bounds of year to std.datetime.date.Date

- std/typecons.d
The second opCast overload is necessary to allow built-in implicit conversions (e.g., mutable to const) to be performed explicitly via a cast expression. Nullable.opEquals depends on this behavior.
> Fix Bugzilla 22293: opCast!bool for Nullable

- std/datetime/date.d
- std/datetime/systime.d
The documentation for the from*String functions specifies what they accept, and the fromISO*String functions accept ISO or ISO extended strings, but it is technically the case that there are ISO and ISO extended strings which they do not accept (since the standard specifies what the fields should look like for each string but doesn't specify that all fields must be present or that any code parsing them must accept all variants).
So, technically, the error messages which have said that the given strings are not valid ISO or ISO extended strings are not necessarily correct. So, this changes the error messages to remove that ambiguity.
> Fix issue 24704: Improve error messages for from*String in std.datetime.

- std/algorithm/sorting.d
Uses a regular initialized temporary array when sorting elements with an elaborate assignment to avoid undefined behavior when destructors, postblits or copy constructors are invoked during the array assignment.
> Fix Bugzilla 24773: don't invoke destructors on uninitialized elements in stable sort

- Makefile
Remove the -de switch to allow future deprecations in Phobos.
> Remove -de switch from Phobos builds to allow deprecations.

- std/process.d
The current implementation of spawnProcessPosix is broken on systems with a large `ulimit -n` because it always OOMs making it impossible to spawn processes. Using the libc implementation, when available, for doing file descriptor operations en-mass solves this problem.
This PR requires https://github.com/dlang/dmd/pull/16806 to be merged first.
> std/process: Default to libc closefrom in spawnProcessPosix

- changelog/pop-grapheme.dd
- std/uni/package.d
Since it's Hackathon today, even if I'm not there I decided to do something in similar spirit.
@atilaneves new symbol canditate for phobos, meaning it needs your approval!
> Added a new popGrapheme function to std.uni

- std/algorithm/mutation.d
The two overloads are widely separated. This puts them together for easier study. The changes are mostly indenting.
Also has its own error message rather than the compiler generated one.
> co-locate overloads of std.algorithm.mutation.swap()

- std/process.d
This took a better part of my week to chase down...
> Fix issue 24824 - ensure we exit a child that does not succeed in exec.

- std/json.d
This is the same goal as https://github.com/dlang/phobos/pull/6059 , but a more minimal / conservative approach - instead of adding a policy framework, this is behind a new `JSONOptions` flag.
In theory this is perfectly backwards compatible, as pre-existing D code will never cause any `orderedObject` to be created. The `orderedObject` type is entirely opt-in, whether via `JSONOptions.preserveObjectOrder`, or created manually by starting from a `JSONValue.emptyOrderedObject` or the `.orderedObject` setter.
The only gotcha might be any possible `final switch`-es over `JSONType`, let's see what BuildKite says - if this is an issue then `JSONType.orderedObject` could be moved to a `bool` instead.
> Fix Issue 24823 - std.json: Allow optionally preserving the order of fields in JSON objects

- phobos/CONTRIBUTING.md
- phobos/Design.md
- phobos/PackageMap.md
- phobos/README.md
This adds the documentation from the Phobos VS Design repo into the Phobos repo and adds a Phobos 3 specific README to make it easier to find the documentation.
> Add Phobos 3 Documentation

- std/algorithm/searching.d
- std/typecons.d
Rebindable2 did not handle types with opAssign correctly, which affected both minElement and maxElement. Namely, Rebindable2 assigned to memory which was not properly initialized when the correct solution in such a situation is to use copyEmplace. Assignment works when assignment is just a memcpy, but in the general case, opAssign needs to have a properly initialized object in order to work correctly. copyEmplace instead copies the object and then places the copy into the unitialized memory, so it avoids assigning to uninitialized memory.
This commit also adds additional tests for types with destructors (which do get opAssign automatically) and types with postblit constructors or copy constructors to try to ensure that the code is doing the correct thing in those cases with regards to …
> Fix Bugzilla issue 24827: maxElement does not handle opAssign correctly.

- std/bitmanip.d
They're overly complex (e.g. testing for the native endianness of the machine when that's actually completely unnecessary), and they use unions in a manner that is undefined behavior in C/C++ (since they write to one field and then read from another). I don't see any mention of whether that behavior is defined in D in D's spec, but it's probably undefined in D given that it's undefined in C/C++. Either way, it's an overly complex solution.
This solution gets rid of all of the endian version checks in std.bitmanip, and it allows the implementations of the endian conversion functions to be the same between CTFE and runtime.
@atilaneves Assuming that I didn't screw up the implementation somehow, this should be much more to your liking than what's been here. Either way, it results in a lot …
> Simplify endian conversion functions in std.bitmanip.

- std/typecons.d
https://github.com/dlang/phobos/pull/9070 Addendum
This PR fixes some more linting errors found in the typecons.d file. Fixed a bug in dmd-as-a-lib D-Scanner that prevented it from detecting those issues in the first place.
> Fix UndocumentedDeclarationCheck linting issue in typecons.d

- std/algorithm/sorting.d
* https://github.com/dlang/phobos/pull/9049
* https://github.com/dlang/phobos/pull/9067
> [stable] Cherry-pick 2 master fixes

- std/process.d
Replaces #8990, refactored after merge of #9048 
Credit to @trikko
> Fix bugzilla 24524: Very slow process fork if RLIMIT_NOFILE is too high

- std/socket.d
#8389 plus a reference link as requested by @CyberShadow.
Text has been adjusted to provide further explanations.
Further reading: <https://stackoverflow.com/a/14388707>
> Fix 17416 - Add REUSEPORT to std.socket

- std/conv.d
Documents that add similar function for run time use cases has been added and warns about their differences.
(I'm not a native English speaker. Please proof-read.)
> Reference std.digest.fromHexString in doc of std.conv.hexString

- std/array.d
Not going to reproduce all the junk I did in the bug report. See the report.
> Fix appender code that might not initialize memory that might point at huge allocations

- std/sumtype.d
**Please review this PR commit-by-commit.**
The changes in this PR can be grouped into two categories:
1. Refactoring of helper templates use by `matchImpl` to eliminate unnecessary instantiations.
2. Addition of a fast path for single dispatch to `matchImpl`.
Altogether, these changes reduce the time take to run `std.sumtype`'s test suite by about 14%.
See also pbackus/sumtype#91, which added these changes to the dub version of `sumtype`.
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `../dmd/generated/linux/release/64/dmd -conf= -I../dmd/druntime/import  -w -preview=dip1000 -preview=dtorfields -preview=fieldwise -m64 -fPIC -O -release -main -unittest -version=StdUnittest generated/linux/release/64/libphobos2.a -defaultlib= -debuglib= -L-lpthread -L-lm …
> sumtype: reduce template overhead of match

- std/traits.d
This makes it so that enums whose base type is an aggregate type are also considered an aggregate type. It probably doesn't affect much code, since isAggregateType isn't needed often, and it's fairly rare to declare enums whose base type is an aggregate type, but in general, code that cares whether a type is an aggregate type is going to care that an enum's base type is an aggregate type.
> Fix Bugzilla issue 24875

- phobos/sys/traits.d
These are the Phobos v3 equivalents of std.traits' hasElaborateAssign, hasElaborateCopyConstructor, and hasElaborateDestructor. After some discussion with Adam Wilson, I went with "Complex" rather than "Elaborate" with the idea that it would be easier to understand for non-native English speakers. It's also shorter, which is a plus. I also tried to make the names more consistent (and avoided having "CopyConstructor" in the name, because it also deals with the postblit constructor).
For the moment, I have not created hasComplexMoving to check for move constructors, since that situation has yet to be finalized in the language. I was surprised to find out that hasElaborateMove was even a thing, since it was my understanding that opPostMove had never actually been implemented, so I don't know …
> Add hasComplex{Assignment,Copying,Destruction).

- phobos/sys/traits.d
In many cases, even when using Unqualified makes sense (as opposed to Unconst or Unshared), using is(immutable T == immutable U) works just as well and avoids instantiating any additional templates. This seems to becoming more known in the D community over time, but it seems appropriate to mention it in Unqualified's documentation so that more people will be made aware.
Also, I changed it so that Unqualified is always a wrapper template instead of directly being an alias of Unqual in core.internal.traits. This is because the names don't match, and the alias will show up in any error messages. Long term, we would ideally rename the symbol in core.internal (potentially turning the std.traits versions into a wrapper templates instead of an alias). However, since the functionality is …
> Add note to Unqualified about is(immutable T == immutable U).

- std/conv.d
- std/format/internal/write.d
See https://github.com/dlang/dmd/pull/17068#issuecomment-2502010252
`hasToString` is a bit of a tangle, it tries to force passing `FormatSpec` by `const ref` for `customPutWriter`, but not for `constCharSinkFormatSpec`. It's not necessary to require it, I guess copying it is discouraged because it is slower than needed, but it's hard to statically enforce this in the presence of overloads.
> Fixes for `-preview=rvaluerefparam`

- std/format/package.d
Someone tried to \\( instead of $(LPAREN) inside of a bold macro. Didn't work and made the description very misleading.
> Fix typos in compound format descriptions

- std/process.d
This is a nasty problem. This sort of works around the issue by assuming the environment is as expected in the child process.
If you want to merge parent + custom environment, there is still a risk of segfault here, as another thread can easily change the environment pointer and cause the pointer being iterated to be invalidated.
But that is a separate problem that has no good solution. See discussions on the Julia lang github: https://github.com/JuliaLang/julia/issues/34726
> Fix #10574 - environment pointer sometimes changes before exec, causing error in child process.

- std/logger/filelogger.d
Fix a linting issue introduced in filelogger.d:
```
std/logger/filelogger.d(279:12)[warn]: Auto function without return statement, prefer inserting void to be explicit
```
> Fix linting issue in filelogger.d

- std/math/traits.d
I took the modifications @n8sh made in _math.d_ and moved in _traits.d_ since _math.d_ doesn't exist anymore and the math library is now composed of multiple files, and then added more tests because the piece of code that is interpreted in CTFE wasn't covered.
Credit to @n8sh for the code in isIdentical.
> Fix Issue 10386: Make std.math.isIdentical work in CTFE with coverage tests

- std/logger/package.d
Fixes #10581.
Revamp of #10573.
> Fix #10581 – `std.logger` has an ostensibly broken example and wrong docs

- changelog/shared-allocator-list.dd
- std/experimental/allocator/building_blocks/allocator_list.d
Revamp of #6465; recreated by applying the changes to current ~master.
The unresolved reviews of the original PR haven’t been addressed yet.
> Add `SharedAllocatorList`

- std/algorithm/searching.d
Thanks a lot to @MartinNowak for suggesting this solution on Slack.
CC @RazvanN7
> Fix #10257 - variadic overload of std.algorithm.searching.countUntil should return which needle was found

- std/process.d
Fixes https://github.com/dlang/phobos/issues/10587
> Fix issue 10587 - std.process.kill should fail for a terminated pid

- std/functional.d
Found this issue while experimenting with #8769 and #10599.
Gonna open an issue to document the problem.
> Fix #10603 - `toDelegate` accepts but can’t handle a templated `opCall`

- std/functional.d
Revamp of #8769.
While I’m not sure whether it covers all use-cases that @Bolpat’s patch had considered and that exist (also see Dennis’ unanswered question over there), it at least passes the testsuite on my machine.
As this is a `@trusted` hack, I’d appreciate my patch to be thoroughly reviewed.
> Make `toDelegate` safe for function pointers

- std/stdio.d
Still need
I just first want to see that it doesn't break anything.
> Fix #10607 - Structs `lines` and `ByLineCopy` cannot be usefully constructed in `@safe` code

- std/stdio.d
This depends on #9035.
Fixes one of the objectives from #10605.
> Make `File.byLineCopy` usable in `@safe` contexts

- std/algorithm/searching.d
Performs `< 3n/2` comparisons, unlike the naive `< 2n`.
Implemented for an input range.
TODO add `alias map = a => a` parameter, once design is confirmed OK.
> [std.algorithm.searching] Add extrema to compute min and max

- std/process.d
Comment says,
<https://github.com/dlang/phobos/blob/8c6fca9ccdb30b69b627808c698526a76f7c4248/std/process.d#L131-L133>
Turns out, *druntime* already provides equivalent functionality in `core.sys.posix.unistd`:
<https://github.com/dlang/dmd/blob/9d72ed4249075ccd6edbb4732b9027ebe92d4c0f/druntime/src/core/sys/posix/unistd.d#L2726-L2771>
> Replace internal `getEnvironPtr` with its equivalent from druntime

- std/json.d
Works around issue seen in dlang/dmd#20675.
> std.json: Void initialize return value in emptyOrderedObject

- std/algorithm/mutation.d
- std/typecons.d
Avoid CTFE unsafe cast by swapping elements of `tupleof`.
> Fix #10538 - Cannot swap a std.typecons.Tuple

- std/stdio.d
> Fix #10605 - Make `File.byLine` usable in @safe contexts

- std/array.d
This provides an appender that doesn't hold its data in an indirection which needs allocating, the lack of which reduces overhead substantially for situations where the amount of actual work done with the appender is small (e.g. the number of elements appended is small). For maybe 95% of use-cases, the user does not want to pass an appender around by value, in fact it's hard to see why that would be desirable, so we take advantage of that and create a non-copyable `FixedAppender` which can store all its data "in-place".
I intend to spread its use around Phobos initially, for testing the interface, then expose it publicly later (so we can defer arguing about the name too much for now plz).
A separate attempt was made to improve `Appender` by deferring the allocation to the first copy using …
> Introduce low-overhead `InPlaceAppender`

- std/checkedint.d
Before it read:
> **For signed integrals**, the reserved value is `T.min`. **For signed integrals**, the reserved value is `T.max`.
Now it reads:
> **For signed integrals**, the reserved value is `T.min`. **For unsigned integrals**, the reserved value is `T.max`.
> Fix 'for signed integrals' appearing twice `WithNaN` in docs

- std/format/internal/floats.d
- std/format/internal/write.d
- std/math/operations.d
`3.05e2312L` is an unrepresentable number on targets where `real.mant_dig == double.mant_dig`, so the test ends up requesting the result of `log2(real.infinity)`.
Best viewed with [hide whitespace](https://github.com/dlang/phobos/pull/10627/files?diff=unified&w=1).
> unittest: Don't run x87 log2 test on 64-bit real targets

- std/datetime/stopwatch.d
Thread.sleep sleeps for a minimum amount of time, it doesn't guarantee a maximum wait time. Consequently, it can randomly fail: https://github.com/dlang/dmd/pull/20751#issuecomment-2605539022
> Remove flakey stopwatch test

- std/functional.d
As discovered by @Bolpat over there: <https://github.com/dlang/phobos/pull/10599#discussion_r1925219756>
> Fix unittests of `toDelegate`

- std/random.d
This patch changes `unpredictableSeed` to use the `getrandom` syscall on Linux.
Currently, `unpredictableSeed` calls `arc4random()` on applicable BSD systems;
for everything else it executes `RDRAND` on `InlineAsm_X86_Any`-compatible targets or falls back to a [homebrew solution](<https://github.com/dlang/phobos/blob/231ae8b68ab5d4d81df4ffd4ec08c896b6c9ca81/std/random.d#L1735>).
> Make `unpredictableSeed` use `getrandom` (syscall) on Linux

- std/random.d
~~This patch changes `unpredictableSeed` to call `CryptGenRandom` on Windows.~~
This patch changes `unpredictableSeed` to call `BCryptGenRandom` on Windows.
Analogous to #10623 (Linux).
~~On the one hand, the legacy CryptoAPI might be deprecated, on the other hand using it does not introduce a new DLL dependency. `advapi32` is already required by `std.registry` and Phobos is linked against as seen in the current `Makefile`.~~
~~Using the more modern CNG (`BCryptGenRandom`) would not only introduce a new dependency, but also require us to add the corresponding bindings to druntime. I figured that wouldn’t be worth the effort for now.~~
> Make `unpredictableSeed` use `BCryptGenRandom` (CNG) on Windows

- std/sumtype.d
Previously, code that already knew the desired index was forced to compute a type to pass to `get!T` or `memberName!T`, just for `get!T` or `memberName!T` to turn that type back into an index. Removing this unnecessary round trip simplifies the code.
Additionally, since `memberName` is no longer dependent on `SumType.Types`, it can be moved to module scope, and its instantiations can be shared across different `SumType` instances.
> Refactor: access SumType value by index, not type

- std/functional.d
Implements a `ctEval` function as suggested in #10023.
> Fix #10023 - Add `ctEval` to Phobos

- phobos/sys/traits.d
It does the same thing as the std.traits version. They both alias the one in druntime. However, the documentation and tests have been beefed up a bit.
I also added assertWithQualifiers as a private test helper, which it may make sense to add later as a public test helper somewhere, but we don't currently have any module or package for that sort of thing, so for now, it's private. Some of the existing tests should probably also be refactored to use it, but I'm not worrying about that as part of these changes.
I was going to do some other traits at the same time as hasIndirections, but the tests got extensive enough (and caught some bugs in the process) that I cut it down to just the one trait.
> Add phobos.sys.traits.hasIndirections.

- std/getopt.d
Fixes #9662
revival of https://github.com/dlang/phobos/pull/3491 as the suggested "better" solution never happened
> Name argument if data conversion fails in std.getopt

- std/container/dlist.d
See https://forum.dlang.org/post/vkubcdpniiseeuxvdvim@forum.dlang.org
This matches SList's `insertFront`:
https://dlang.org/phobos/std_container_slist.html#.SList.insert
> [std.container DList docs] Fix time complexity of `insertFront` etc

- std/sumtype.d
Github issue #10563
I tried doing this with a template mixin that takes the new tag as an alias parameter to avoid having to deplicate the static check all over the place, but that gave me deprecation warnings about assigning a variable to itself and also failed the unittest in line 936 where one postblit destructor didn't execute correctly ...
> Fix Bugzilla Issue 24818 Sumtype with single-type wastes space

- std/range/package.d
The constructor of the result of std.range.chain copies it's input tuple and then has to check which of the input-ranges in the first non-empty one. The member function empty is not guaranteed to be const, filter is probably the most prominent function that has to be "primed". On the first call to empty(), filter will try to advance all it's input ranges to the first element that matches the predicate.
For ranges with full value semantics, using the old input object instead of the new internal buffer means that the work of priming is done twice. If any ranges have reference semantics, the references gets advances, but the value-semantic parts of the range-composition gets reset.
This fixes #10561 and #9877
> Fix chain potentially mutating a stale object

- std/typecons.d
* Use formattedWrite instead of format
* Remove some workarounds for shared types that have been put in there a few years ago
I'm not entirely sure why these workaround have been added, but I suspect that #6207 fixed this in `std.format`.  The unittests still work.
This is a breaking change. See line 1787 (in the new version), If a class is null, the Tuple.toString will now print null instead of the mangled typename (because this is what std.format does)
> Tuple toString

- std/typecons.d
Now, member structs won't become const due to transitiveness and the code in `std.format` can choose (erroneously) non-cost toString() functions of member structs.
An expert has to decide whether this is worth the breaking change. Now, code that uses `const` tuples and calls toString directly on them will break. Alternatively, we could use
[Template this parameters](https://dlang.org/spec/template.html#template_this_parameter).
That way, we get a template parameter with the real type of this. Then we can cast away constness of `this` when we now for certain that it isn't, since `is(T != typeof(this))` (where T is the template this parameter). Of course, this implies making toString `@trusted` too.
This might also lead to unforeseen bugs when `const` is cast away but the member objects are …
> Fix #9811 Remove const from Tuple.toString

- std/sumtype.d
Handlers that return a non-copyable value by reference are now capable of successfully matching.
Fixes #10647
> sumtype: fix canMatch for non-copyable ref return

- changelog/bit-cast.dd
- std/conv.d
This helper function is a more readable alternative to the traditional pointer-cast-based syntax for reinterpreting casts.
The name bitCast is used for this operation in several other languages, including C++ [1], Swift [2], C# [3], Zig [4], and LLVM IR [5].
[1] https://en.cppreference.com/w/cpp/numeric/bit_cast
[2] https://developer.apple.com/documentation/swift/unsafebitcast(_:to:)
[3] https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.bitcast
[4] https://ziglang.org/documentation/0.10.0/#bitCast
[5] https://llvm.org/docs/LangRef.html#bitcast-to-instruction
---
~~Alternative to https://github.com/dlang/dmd/pull/20728~~
For related discussion, see https://github.com/dlang/dmd/issues/20644
> Add std.conv.bitCast

- std/format/internal/read.d
- std/format/read.d
This PR addresses issue #10598. The problem lies in the lack of handling for certain specifiers in the `skipData` function of `std/format/internal/read.d`. The `switch` statement only handles `%c`, `%d` and `%u`. Handling of `%s` was added but the problem is analogous in the case of other specifiers. For example, the program:
```
import std.format;
void main()
{
string str = "3.14159 0.0 6.28318";
double pi, tau;
str.formattedRead("%f %*f %f", pi, tau);
writeln("Pi is: ", pi , ", Tau is: ", tau);
}
```
outputs this:
```
core.exception.AssertError@/home/nick/dlang/dmd/generated/linux/release/64/../../../../../phobos/std/format/internal/read.d(43): Format specifier not understood: %f
----------------
??:? _d_assert_msg [0x55af8fd75528]
??:? pure @safe void …
```
> Fix %*s handling by formattedRead()

- changelog/readfln.dd
- std/stdio.d
Compared to readf, these functions provide a less error-prone way to read a single line of formatted input.
Fixes #10370
> stdio: add readfln and File.readfln

- changelog/sumtype_procedural_api.dd
- std/sumtype.d
This PR introduces three new convenience functions that allow code using `SumType` to be written in a more procedural style (as opposed to the functional style of `match`).
* `has!T` checks whether a `SumType` contains a value of type `T`.
* `get!T` accesses a `SumType`'s value if it has type `T`, or asserts if it does not.
* `tryGet!T` is like `get!T`, but throws an exception instead of asserting on failure.
To make room for `get!T`, the existing `SumType.get` method is renamed to `getByIndex`.
CC @atilaneves since this introduces new public symbols
CC @jmdavis who requested this in the community Discord
> Procedural API for SumType

- std/sumtype.d
Strictly speaking, the Kelvin scale is not measured in degrees, so the previous name was incorrect. Changing it in all cases preserves consistency.
Fixes #10540
> sumtype: rename 'degrees' to 'value' in example

- std/file.d
Remove range support from the constructor of `DirIteratorImpl`.
This was unused, untested and potentially broken (even before #10666).
> Remove range support from `DirIteratorImpl.__ctor`

- std/math/algebraic.d
fixed  issue [std.math] std.math.algebraic.cbrt is not pure #10577
https://github.com/dlang/phobos/issues/10577
> Fix #10577 - [std.math] std.math.algebraic.cbrt is not pure

- std/conv.d
Optimize std.conv.parse by eliminating unnecessary count increments
> Fix issue  std.conv.parse!(int, string) counts when doCount is false #9829

- std/json.d
To work around https://github.com/dlang/dmd/issues/20675.
> [stable] std.json: Avoid setting union members, set the whole union instead

- std/functional.d
Fixes #10637
- Removed the outdated BUGS entry about `@safe` functions in the documentation of `std.functional.toDelegate`.
- Verified that PR #10599 resolved this issue, with test cases added.
1. **Test support for `@safe` functions**:
```d
@safe int add(int a, int b) {
return a + b;
}
assert(toDelegate(&add)(2, 3) == 5); // Test passes
> Remove outdated @safe bug entry from toDelegate documentation in `std.functional.toDelegate` (Fixes #10637)

- std/getopt.d
Reworked the conversion function so it returns the value instead of accepting a (possibly const) pointer.
> Fix #10680 - std.getopt doesn't accept const(string)[] anymore

- std/complex.d
- std/math/algebraic.d
This ports the fixes from abs(T)(ComplexT) regarding NaN and skipping
potentially inaccuracy inducing mathematical no-ops when one arg is 0 to
hypot. Both functions do the same thing and should be deduplicated.
hypot also has some logic regarding under and overflows, and while I
don't fully understand it, it should probably not be removed for complex
numbers.
followup to #10679
> Unify abs(Complex!T) and hypot

- std/variant.d
There has been code that handles alignment for a long time now, and while this module is unlikely to be touched anymore, create a regression test so the issue can be closed.
> Fix #9585 Add check `variant` alignment

- std/traits.d
Fixes #10527.
Also remove type parameter overload as that's handled by the `alias` overload now.
Cc @schveiguy.
> std.traits.TemplateOf doesn't return void for non-template functions

- std/uuid.d
Arguments to DDoc macros must be separated by a comma and at most one space, not spread over multiple lines.
CC @0xEAB
> Fix #10701 - Broken link in documentation of randomUUID

- std/json.d
Allows using JSON values in sets and map keys.
> std.json: Add JSONValue.toHash

- std/experimental/allocator/building_blocks/allocator_list.d
Otherwise hitting a consistently failing assertion for LDC CI.
> [stable] std.experimental.allocator.building_blocks.allocator_list: Fix unittests on macOS arm64

- std/file.d
AFAICT there’s no indication that the new line would have been there on purpose.
- <https://github.com/dlang/phobos/commit/0b153a28844187f815375eae54880cb2dbc39704#diff-4710c350a9e857256a051a404aa4aade17b784a0ae5460bddc10bd248d5b1debR2257-R2259>
- <https://github.com/dlang/phobos/pull/6320>
> Remove empty line between doc comment and unittest

- std/algorithm/iteration.d
* Document the function signatures for the passed in functions at the most obvious place (in the past, it was often faster for me to try this out instead of searching it in the docs)
* paragraphs
* equalize fold/reduce documentation a bit
I also changed predicate to function, which is slightly more correct, but actually should be `callable`. I think function is easier to understand for newcomers to the language while everybody else probably understands from context that the alias can be any callable, but reviewers might object here.
> Change documentation for reduce

- .github/workflows/main.yml
Currently, our FreeBSD CI tests…
- either complete within about 11 minutes
- or timeout after 60 mins – ~49 of them spent idling erroneously.
I think it wouldn’t hurt to tune this a bit.
---
The old timeouts seemingly date back to the Cirrus CI to GHA migration and haven’t been adapted since:
<https://github.com/dlang/phobos/blame/91af96cddbc6ff23e0453ec31165d7fa85b9100e/.github/workflows/main.yml#L129>
---
The new values are calculated as follows:
$Value\ from\ DMD + 5\ extra\ minutes$
- <https://github.com/dlang/dmd/blob/2036516c1758815739c069a19b0832ef6a0d26e7/.github/workflows/main.yml#L194>
- <https://github.com/dlang/dmd/blob/2036516c1758815739c069a19b0832ef6a0d26e7/.github/workflows/main.yml#L201>
The extra headroom could be remove later on, if practice shows we can tighten …
> Tune FreeBSD timeouts on GitHub Actions

- std/variant.d
Adresses part of #10518, now adding to Variant(Variant[string]) doesn't segfault anymore, but at least throws.
The issue was calling the destructor of unitinialized memory.
How to fix the exception is harder. I think there are 3 places where this could handled, either in `get(T)`, `tryPutting` inside the handler, or `case OpID.indexAssign:` . Of these, `tryPutting` probably is the most "correct", but also seems the hardest to understand to me and will have the biggest fallout in unrelated places if you get it wrong.
Whatever place is eventually chosen, you can't just memcopy the storage, as big types are often implicitly allocated on the heap and stored as a pointer.
> Variant segfault

- std/experimental/allocator/common.d
This can be reverted after the fix for dlang issue 21065 is merged
Refs: dlang/dmd#21065
> std.allocator: Comment out broken class instance size test

- std/file.d
This essentially reverts commit 274109b3de5f5d61d5a1f99a53a83e5e10056230.
It doesn’t remove the added unittest yet because it wonderfully underlines the point I’m going to make:
It adds no value.
The patch was a nerfed version of #6125. Well, it was nerfed to provide backwards compatibility. But this came at a cost: It no longer helped with the footgun imposed by relative paths that the original version did actually help with.
Let’s verify that Phobos still passes its testsuite and remove it for better (or worse).
In addition it still failed to address the underlying problem that `DirEntry`-s that hold relative paths aren’t really aware of which directory they are relative to. That’s what needs to be fixed to resolve the UX issue at hand. I’ve spent quite a while hacking on the module and …
> Revert "Fix #9584 - Using dirEntries and chdir() can have unwanted results (#10666)"

- std/math/exponential.d
The key optimizations I've made are:
128-bit multiplication via inline assembly:
For 64-bit types on x86_64 platforms, I've added direct use of hardware multiplication that produces a 128-bit result (stored in high:low registers)
This avoids the repeated addition loop in the original algorithm
Efficient modular reduction:
Implemented a reduction algorithm that handles the 128-bit result efficiently
Uses a simplified approach for when the high bits are zero
Early reduction:
The base value is reduced modulo m at the beginning, which improves performance when the base is large and modulus is small
Special case handling:
Added explicit handling for modulus=1 and exponent=0 cases up front
Version checks:
The code falls back to the original algorithm if inline assembly is not available
This …
> Fix #10513 - powmod is slow for ulong

- std/format/spec.d
- std/format/write.d
Increases the ``startIndex`` and ``endIndex`` types to ``ushort``, documents that the maximum value is now used as a sentinel (was previously, but not documented nor worked).
> Fix #10699 - std.format with position with omitted second number does not work

- changelog/write-text.dd
- std/conv.d
These are variants of text, wtext, and dtext that write their output to an output range instead of returning a string.
Fixes #10550
> std.conv: add writeText, writeWText, writeDText

- changelog/add_lazycache_function.dd
- std/algorithm/iteration.d
PR: Add lazyCache function to std.algorithm.iteration
Description
This PR adds a new lazyCache and lazyCacheBidirectional functionality to std.algorithm.iteration to complement the existing cache and cacheBidirectional functions.
Unlike the existing cache function which eagerly evaluates the front element on construction and after each popFront call, lazyCache delays evaluation until elements are explicitly requested via front or back calls. This is particularly useful when working with ranges where element evaluation has side effects that should be delayed until absolutely necessary.
Changes
Added lazyCache and lazyCacheBidirectional functions
Added private LazyCache struct implementation
Added documentation explaining the differences from cache
Added unittest demonstrating lazy …
> Adding  a lazy version of std.algorithm.iteration.cache #10687 Open Feature

- std/net/curl.d
For HTTP, the response body encoding is specified in the "Content-Type" header, e.g.: "Content-Type: application/json; charset=utf-8".
MDN [says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Type#directives):
> - `charset`: Indicates the character encoding standard used.
>   The value is **case insensitive but lowercase is preferred**.
However, `_decodeContent` was comparing the encoding with the exact string "UTF-8", which causes most HTTP requests to go through the slow path.
Fix this by using `icmp`, like elsewhere in the module for case-insensitive string comparisons.
> std.net.curl: Fix fast-path check when encoding is "utf-8" (lower-case)

- std/internal/math/biguintcore.d
Added if statements to call free only at runtime so that the functions can also execute at compile time.
> Fix Issue 10523 - Enabled BigInt to work in CTFE

- std/encoding.d
**Changes:**  
- Replaced `return cast(immutable(E)[]) array[0 .. offset];` to `return array[0 .. offset];`.
**Explain:** 
- It seems like that: It works because it's a template function and the compiler can see that the array slice array[0 .. offset] is unique (no other references exist) at the point of return, so it allows the implicit conversion to immutable. If it's not a template function, and the compiler cannot prove the uniqueness of the array slice. I tested it by following codes: 
**Tests:**
This snippet code could be compiled: 
```d
@safe immutable(E)[] templateFunc(E)(immutable(E)[] s) {
E[] array = new E[s.length];
array[0..s.length] = s;
return array[0..5];
}
int main(string[] args) {
writeln(templateFunc("SSSSSSSSSS"));//SSSSS
return 0;
}
```
This snippet code could NOT be …
> fix std.encoding.sanitize usable in @safe.Fix #10545

- Makefile
- std/internal/windows/bcrypt.d
- std/random.d
Load `Bcrypt.dll` ourselves as needed.
> Fix #10731 - Windows link error with std.random.uniform() in v2.111

- std/file.d
fixes: #10727
This PR fixes a segmentation fault that occurs in `std.file.renameImpl` when either `fromz` or `toz` is null.
In the original implementation, if the `toz` or `fromz` pointer is null, a `wcslen(null)` call is made, which results in undefined behavior and a segmentation fault.
This patch adds proper null checks before calling `wcslen(...)`, and assigns a fallback value of `"<null>"` if the pointer is null.
```d
string from = "input.txt";
string to = null; 
rename(from, to); // triggers FileException with segmentation fault
```
Now, instead of crashing, the function throws a safe and descriptive FileException:
```d
Attempting to rename file input.txt to <null>
```
#Notes
Verified manually using custom Phobos build and runtime tests
Fix is Windows-specific and guarded inside …
> fix: Add null checks in std.file.renameImpl to avoid segmentation fault via wsclen

- std/path.d
The `extSeparatorPos` has a useless `const` in its signature. This prevents using it with ranges that do not support `const`, so even an obvious combination like `chainPath(...).setExtension(...)` fails to compile.
```d
private ptrdiff_t extSeparatorPos(R)(const R path)
```
> Fix withExtension for types incompatible with const

- changelog/README.md
This pull request fixes a small typo in `changelog/README.md` by removing an extra closing parenthesis from the sentence describing how to preview the changelog.
Before:
... repo),
After:
... repo,
This improves clarity and maintains consistency in documentation.
> fix: remove stray parenthesis in changelog README

- Makefile
- std/random.d
People have been unhappy about the new `getrandom()` dependency.
- <https://github.com/dlang/phobos/pull/10623#issuecomment-2778500400>
- <https://forum.dlang.org/post/dxgjgvfrlawgiajklzpm@forum.dlang.org>
Instead of [reverting](https://forum.dlang.org/post/txltgbfjxvsclwjuotry@forum.dlang.org) the whole thing, we could supply a compatibility mode to users stuck with legacy systems.
> `getrandom()` backwards compatibility shim

- std/conv.d
Partial Fix: #10559
This PR improves compile-time diagnostics when attempting to convert an infinite input range to a string using to!string.
Currently, the following code fails with a long and unhelpful template constraint error:
```d
import std.range, std.conv;
void main() {
auto s = 42.repeat.to!string;
}
```
Error :
```d
none of the overloads of template std.conv.toImpl are callable using argument types !(string)(Repeat!int)
```
The reason is that Repeat!int is an infinite range and does not meet any of the constraints for string conversion — but the compiler doesn’t provide a meaningful message.
This patch adds a specialized overload of toImpl in std.conv to detect the pattern of:
```d
to!string(range) // where range is an infinite input range
```
And explicitly raises a meaningful …
> Improve error message for to!string when used on infinite ranges

- std/container/rbtree.d
Useful in case we need >= or <= (instead of > or < or = as provided by lowerBound/upperBound/equalRange).
Same convention as SortedRange.trisect, except just return a static array instead of a tuple (as the type is the same).
CC @schveiguy
> std.container.rbtree: Add trisect

- changelog/emulate_getrandom.dd
- std/random.d
Adds a changelog entry.
Comments out the message pragma.
I wouldn’t mind it, but it’s really a bit spammy. Also see Atila’s upvote on my message suggesting this change: <https://github.com/dlang/phobos/pull/10741#discussion_r2030025301>
> Polish `getrandom()` backwards compatibility shim

- std/format/internal/write.d
Remaining Fix: #10559
This PR tackles the issue of infinite loop during runtime when providing format with infinte range . Now it shows compilation error for the same .
Passing an infinite range (e.g., 42.repeat) to format("%s", ...) would result in the format engine trying to consume the entire range, which leads to a non-terminating loop at runtime .
format did not have a guard to catch infinite ranges. This allowed constructs like :
```d
auto s = format("%s", 42.repeat); // hangs forever
```
to compile successfully but hang during execution.
This patch adds a static assert within the formatRange function that triggers at compile time if the range is detected to be infinite and the formatting is not in test mode (Writer != NoOpSink).
```d
static if (!formatTestMode && isInfinite!T)
{ …
```
> fix: give compile error for infinite range in format

- std/container/rbtree.d
I don't see any downsides, and it will allow updating value types in-place as we're iterating over the tree.
Some counter-arguments I can think of:
- What if this is used to change the key such that the tree is no longer ordered?
- Well you can do that already anyway if `Elem` is a reference type, it's not like we're returning `const`.
- What if the tree is changed while we're holding a reference to a node?
- We're allocating nodes with `new`, so even if they're gone from the tree, it shouldn't result in a dangling pointer.
Did I miss anything?
CC @schveiguy
> std.container.rbtree: Return range elements by ref

- std/file.d
I suspect that this unittest might pass as-is with the current codebase already.
> Add unittest from #10769

- std/typecons.d
Because some overloads of `Nullable!T.toString` are not templates, instantiating a `Nullable!T` also always instantiates `formatValue!T`, and all of its dependencies.
For large type hierarchies, this can add a significant amount of compilation overhead.
We can avoid this by making remaining overloads of `Nullable!T.toString` templates as well, similar to `Tuple`.
Timings from internal motivating use case:
Before:
```
9.00user 1.38system 0:10.57elapsed 98%CPU (0avgtext+0avgdata 5851516maxresident)k
21968inputs+48144outputs (0major+1468687minor)pagefaults 0swaps
```
After:
```
5.11user 0.61system 0:05.75elapsed 99%CPU (0avgtext+0avgdata 2762392maxresident)k
0inputs+34528outputs (0major+685900minor)pagefaults 0swaps
```
> std.typecons: Make Nullable.toString always a template

- std/experimental/allocator/common.d
Reverts dlang/phobos#10717
Behaviour has been clarified.
> Revert "std.allocator: Comment out broken class instance size test"

- std/uni/package.d
This caused a segfault in testing the new GC on windows, as this new GC is more aggressive uncomitting freed memory.
redo of #10786
> Fix #10785 - Fix invalid access of GC memory from destructor when inside a GC finalizer with debug build

- std/uni/package.d
While in a GC finalizer:
1. This can be run from another thread, the refcount is NOT shared. So decrementing is not safe
2. The referenced array might already be collected
See #10785 for the first fix, which did some of this, but not for the refcount.
technically, we really should just ban use of the array from inside a finalizer. But this should be enough to get past the segfaults we are seeing.
This does mean that any `CowArray!GcPolicy` which has a reference from a finalized block, will have extra references that never go away. This is OK, because, if you write to the array, you will make a copy. And then there is now a refcount of 1 again, and the original can truly become garbage. If you read from it, nothing is different.
In general, we should probably examine why we need the …
> Further fix for CowArray to prevent using the refcount from GC

- std/container/rbtree.d
The implicitly defined move constructor of `RBNode` shadows the otherwise implicitly defined per-field struct constructor. This could also be considered a language regression, but the fix here is pretty simple and shouldn't otherwise have negative consequences.
Fixes #10811.
> Fix compile error in RedBlackTree caused by the presence of a move constructor

- std/traits.d
Extend example with function pointer, lambdas.
Template functions only work with `!()`.
Fixes https://github.com/dlang/phobos/issues/10814.
> [std/traits] Improve docs for `isCallable`

- std/experimental/allocator/building_blocks/kernighan_ritchie.d
Also added these flags to all the functons it calls.
In order to make the functions safe I isolated the 'unsafe' parts inside @trusted lambda expressions, inspired by [edi33416](https://github.com/edi33416)'s pull request [#6416](https://github.com/dlang/phobos/pull/6416).
Additionally, added nothrow @nogc @safe to the allocateAll function, since it only calls allocate.
> Added nothrow @nogc @safe to the allocate function.

- std/array.d
dlang/dmd#21525 Adds the template `_d_newarrayUTrace`. To fix dlang/dmd#21033, this commit needs to replace the use of the non-template hook with the newly added template in `std.array.d`.
> `std.array.d`: Use template `_d_newarrayU{,Trace}

- std/datetime/date.d
- std/datetime/systime.d
The types Date, DateTime and TimeOfDay already implement adding and subtracting a Duration to them.
This makes the addition of a Duration commutative via implementing opBinaryRight.
I chose opBinaryRight over Duration.opBinary, since Duration is in druntime, which shouldn't depend on phobos.
Only addition is implemented here. DateTime and Date already principally support negative Dates, i.e.
Date(0, 1, 1) - days(7) // 0001-Dec-25
works and can be interpreted as Before Christ (BC) dates. On the other hand opUnary isn't implemented (yet), which seems like a precondition for making subtraction commutative in a way that makes sense via the transformation:
days(7) - Date(0,1,1)
=> -Date(0,1,1) + days(7)
and even then the semantics of subtracting a Date from a Duration is debatable.
> Fix dlang#10783: Datetime: Make adding a Duration to Date commutative

- std/internal/math/gammafunction.d
- std/mathspecial.d
This adapts `std.mathspecial.digamma` so that it IEEE 754 way of handling +/-0.0, i.e., it treats them as values that are infinitesimally greater/less than zero. `digamma(+0.) == -real.infinty` and `digamma(-0.) == +real.infinity`. See #10802 for more information.
The DDOC and unit tests are also updated.
_Even though this is a small change, it results in a change in behavior. This would break any application that relies on `digamma(0.)` evaluating to `real.nan`. Therefore, I'm making this PR for the master branch._
> 10802: digamma maps +/-0 to -/+inf

- std/getopt.d
calling std.format, even though an awesome library, increases compile time quite a bit. This PR removes most calls to std.format.format.
> Reduce std.getopt compile time by removing std.format calls

- std/mathspecial.d
When x > MAXGAMMA or y > MAXGAMMA and the other argument is negative, std.mathspecial.beta now correctly computes the sign of B(x,y). See #10823 for more details.
> 10823 fix, fixed sign of beta(x,y) when x+y large

- phobos/PackageMap.md
This PR does the following: 
1. Adds the `platform` system binding root package.
2. Adds the `based` root package.
3. Moves Phobos 2 modules into `based`.
4. Adds the `phobos.crypto` package.
5. Adds the `phobos.io` package, and moves relevant modules into it.
@jmdavis @pbackus @rikkimax @schveiguy
> Update Phobos 3 Package Map to account for DConf 2025 announcements.

- std/format/internal/write.d
The Linux-specific restriction was added in #4464, but the reasoning for this limitation is unclear. These tests should work across all platforms, so remove the restriction.
> enable a formatValue test runs on all platforms

- std/range/package.d
dropBackOne was the only element in the overview table that was wrappen in a `D` markup. This made is stand out in (only) the ddox version of the docs, since it got slightly indented.
> docs: Fix small inconsistenc for dropBackOne
